### ISSUE TITLE
Inactive prices should not be modified when copied

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1008]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Inactive prices are modified when copied
#### Which are the steps to reproduce?
Have a pricelist with

* a M_ProductPrice with IsActive=N
* a M_ProductScalePrice with IsActive=N

Create a new PLV and copy these prices, using a M_DiscountSchemaLine which modifies the standard prices (e.g. +1.00)

=> prices with IsActive=N are modified as well
### What is the expected or desired behavior?
Prices with IsActive=N should not be modified, see old task 07102

**Comment by teosarca** [comment]
Follow-up of #942

**Comment by teosarca** [comment]
NOTE to IT:
* the discount schema shall not be applied to product scale price if the M_ProductPrice.IsActive='N', even if the M_ProductScalePrice.IsActive='Y'

* not really subject of this task, but related: make sure the product price attributes are cloned, i.e.
** copy a price list version
** on target price list version: pick one price which has attributes, and change one of them 
** on source price list version: make sure for the same price, the attributes were not changed

**Comment by metas-dh** [comment]
(looks like the issue was rolled out, but the status not updated)

 Results of IT 1

tested on w101:

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231008.md: OK

**Comment by metas-dh** [comment]
tested on swing as well, working fine too:

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231008.md: OK
