### ISSUE TITLE
M_DiscountSchemaLine for M_Product_Category not considered when copying pricelists

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1009]
### Is this a bug or feature request?
Bug
### What is the current behavior?
M_Product_Category is not considered correctly when copying prices
#### Which are the steps to reproduce?
Have a pricelist with

* a M_ProductPrice with M_Product_Category=Transport
* a M_DiscountSchemaLine with no M_Product_Category, which modifies the standard price (e.g. +1.00)
* a M_DiscountSchemaLine for M_Product_Category=Transport, which does NOT modify the standard price 

Create a new PLV and copy the price, using the M_DiscountSchema 

=> price with M_Product_Category=Transport is modified as well
### What is the expected or desired behavior?
M_Product_Category should be considered correctly, in this case the price should not be modified since the   M_DiscountSchemaLine for M_Product_Category was set to not modify the price, see old task 07082

**Comment by teosarca** [comment]
Follow-up of #942

**Comment by metas-dh** [comment]
![2017-02-22 09_54_36-decloudit001](https://cloud.githubusercontent.com/assets/18696715/23203993/1615b814-f8e5-11e6-8dbf-6ca33a55e075.png)

**Comment by teosarca** [comment]
IMHO that's ok because the first discount schema line rule that matches is picked.
For your desired behaviour i think u shall set the line without Product and without Product category to a bigger sequence (i.e. keep it last).
wdyt?

**Comment by metas-dh** [comment]
Not sure, created the testcase according to an old task & testcase, and expected the discount schema to work like before.
I will create a taskchat to get mk's and nw's opinion too

**Comment by teosarca** [comment]
yes pls

**Comment by metas-dh** [comment]
info from mk:
* in future the user will know that she/ he has to define top down matching
* what matches first wins
 (=> testcase works fine when product category set is the one with the smaller sequence)
