### ISSUE TITLE
M_ProductPrice with Season fix price=Y should not be modified when copied

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1010]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Season fix price is modified when copying pricelist
#### Which are the steps to reproduce?
Have a pricelist with
* a M_ProductPrice with Season fix price=Y
* a M_DiscountSchemaLine with no M_Product_Category, which modifies the standard price (e.g. +1.00)

Create a new PLV and copy the price, using the M_DiscountSchema 

=> price with Season fix price=Y is modified as well
### What is the expected or desired behavior?
M_ProductPrice with Season fix price=Y should not be modified, see old tasks 07082, 05832

**Comment by teosarca** [comment]
Follow-up of #942

**Comment by teosarca** [comment]
Fixed by https://github.com/metasfresh/metasfresh/commit/002e821f659b2d6f2a1ccdbc9145dc3e8b4d6968 which is in master.
A rollout might be needed so i am adding this task to "Rollout".

**Comment by metas-dh** [comment]
Results of IT 1 

* copy pricelist including a M_ProductPrice with Season fix price=Y: not modified in new PLV: OK
