### ISSUE TITLE
Support for using the login user as default filter

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#10264]

**Comment by metas-rc** [comment]
# 🔀 R&I to branch `master`

-https://github.com/metasfresh/metasfresh/pull/10265
  - _(optional review URLs here...)_

Review guidelines for both reviewer (what to look out for) & dev (what to expect/prepare for): https://github.com/metasfresh/me03/wiki/Code-review-guidelines

# After integration
- [ ] set `branch:`-label in metasfresh-issue XOR pullrequest
- [ ] set `branch:`-label in customer-issue
- [ ] set customer milestone (either hotfix milestone or "normal" UAT milestone)
- [ ] if needed, set `rm:manual_rollout`-label in customer-issue

**Comment by metas-dh** [comment]
IT successful, see me03 issue.
