### ISSUE TITLE
extract distributable stuff into dedicated repo

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1028]
### Is this a bug or feature request?

feature

### What is the current behavior?

Right now the metasfresh repo contains both the "backend" and the distributable (i.e. de.metas.endcustomer.mf15). This is problematic in a number of ways

### What is the expected or desired behavior?

in future we want what is currently de.metas.endcustomer.mf15 to be in a dedicated repo called metasfresh-dist

**Comment by metas-dh** [comment]
Results of IT 1

tested on mf15, swing:

* rolled out from repo called metasfresh-dist to mf15 swing client: rollout worked fine. OK
* swing client was updated correctly, had the correct rolled out version: OK
