### ISSUE TITLE
"SELECT public.db_alter_table" are not logged to migration scripts

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1031]
"SELECT public.db_alter_table..." commands are not logged to migration scripts which leads to corrupted migration scripts.

**Comment by teosarca** [comment]
@metas-ts  pls review and check if there are other cases.
The issue was introduced by https://github.com/metasfresh/metasfresh/commit/21896891a314951498d663fb1a24abf42be94d52

**Comment by metas-lc** [comment]
alter table is logged
