### ISSUE TITLE
DLM - restrict number of mass-archived records

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1035]
### Is this a bug or feature request?

Feature Request..sortof.
It's a follow up to issue #969 "Mass archive old DB records". That process updated a log ot `DLM_Level` columns and was faster than the auto-vacuum deamon and caused the DB to fill up.

### What is the current behavior?

The `DLM_MassMigrate` process does whatever is specified in the `dlm.massmigrate` table, until it's done.

### What is the expected or desired behavior?

The `DLM_MassMigrate` process should stop after a given numer (e.g. 10.000.000) of records. Then the admin who ran the process can check the DB and verify that autovacuum is done with the tables that were processed by `DLM_MassMigrate` and only then start another run.

**Comment by metas-dh** [comment]
checked with ts: no IT necessary; process was already run 2 times by ts and worked OK
