### ISSUE TITLE
System Elements w/ centrally maintained Y shall also migrate migration scripts for Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1044]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When Changing the System Element Name, migration scripts are created for  AD_Element, AD_Column, AD_Process_Para, AD_Field,  AD_PrintFormatItem. When changing the AD_Element_Trl name, the migrations scripts are not created for the corresponding other translation tables.

#### Which are the steps to reproduce?
Try and change the translation name for a system element.

### What is the expected or desired behavior?
Create Migration Scripts also for Translation elements automatically.

**Comment by teosarca** [comment]
see org.compiere.model.M_Element.afterSave(boolean, boolean)

**Comment by metas-rc** [comment]
* TODO
** For each of the translation tables, write an update sql then transcribe it into a function. 
** The tables to be updated are the following, wth their columns that have to be modified: 

- AD_Column_TRL 			-- name, isTranslated
- AD_Process_Para_TRL 	-- name, description, help, isTranslated
- AD_Field_TRL 			--name, description, help, isTranslated
- AD_PrintFormatItem_TRL -- printname, isTranslated

**Comment by teosarca** [comment]
rolled out on w101.
@metas-mk  can u pls test it?

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
