### ISSUE TITLE
Automatic Naming of Pricelist Version Name

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1046]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Name of Pricelist version is initially set to a date time created.

#### Which are the steps to reproduce?
Go to Window Pricelist and create a new Pricelist Version of an existing Pricelist. Check the name generated.

### What is the expected or desired behavior?
Generate a name that is set together w/ "Name of Pricelist" + "valid-from" + counter if more PLV on same valid-from date

**Comment by teosarca** [comment]
@metas-mk  why not making the price list and DateFrom part of the identifier.
regarding "counter if more PLV on same valid-from date" i think that shall not be possible/allowed.

**Comment by metas-mk** [comment]
Like the idea:
Identifier of PLV should then be PL Name + PL Country + PL currency + PLV valid from (as date)

**Comment by teosarca** [comment]
@metas-mk  to be more precise, the identifiers shall be configured as:

* M_PriceList_ID, which on it's turn it shall the identifiers configured as:
** Name
** C_Country_ID
** C_Currency_ID
* ValidFrom

**Comment by metas-rc** [comment]
@teosarca thanks!

**Comment by metas-mk** [comment]
perfect.
@metas-rc please also make sure that the PLV has a unique constraint on valid from for given Pricelist_ID

**Comment by metas-dh** [comment]
Results of IT 1

tested on sp80 swing

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231046.md: OK
