### ISSUE TITLE
Support Flatrate Term Period Calendar Year

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1052]
### Is this a bug or feature request?
Feature

### What is the current behavior?
When creating a new flatrate term with duration one year the contract starts today and ends in today + 1 year.

#### Which are the steps to reproduce?
create flatrate term from sales order

### What is the expected or desired behavior?
if the flatrate condition is set to calendar year the flatrate term starts today but always ends on 31.12. of the current year.

**Comment by metas-ts** [comment]
Hi @metasnw 
as far as i can see we already have this feature: Please checkout the "Vertragslaufzeit" window (table `C_Flatrate_Transition`). There (tab "Laufzeit") should be a field "Endet mit Kalenderjahr" (column `EndsWithCalendarYear`). If you set this to yes, then contracts which use the flatrate conditions that have this transition record shall always end at the end of the year, no matter when they started.

Please ping me if there are problems.

**Comment by metasnw** [comment]
@metas-ts thx you are right. closing issue.
