### ISSUE TITLE
Purchase Order from Sales Order process, wrong InvoiceBPartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1056]
### Is this a bug or feature request?
Bug
### What is the current behavior?
A BPartner w/ Invoice BPartner Relation that works fine w/ manual Purchase Order creation, does not work for generated Purchase Orders from Sales Order.
#### Which are the steps to reproduce?
Create an Invoice BPartner Relation for a BPartner. Create a manual Purchase Order for that BPartner. Works. Create a Sales Order and generate a Purchase Order where that BPartner is triggered. Does not work. The invoice BPartner is wrong.
### What is the expected or desired behavior?
The Process Generate Purchase Order from sales Order shall have the correct Invoice BPartner in Purchase Order when BPartner Relation exists.

**Comment by metas-lc** [comment]
IT https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231056.md OK
