### ISSUE TITLE
Move HU to garbage

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1064]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, there is no possibility to destroy HU and move to garbage via Handling Unit Editor.
### What is the expected or desired behavior?
Provide a functionality to move HU to garbage and destroy in Handling Unit Editor for selected HU. 
We need a document that also allows the accounting for this procedure. This Document must be generated w/ the needed data (taken from HU) and HU must be assigned to the Document. HU must then be changed in status (destroyed). The dangling/ empty Packing Materials are moved to Packing Material Warehouse automatically.

belongs to main issue: https://github.com/metasfresh/metasfresh/issues/547

**Comment by metas-rc** [comment]
Update: 
Needed messages ( from Lili) 
* Translate MoveToQualityWarehouse
* Translate MoveToGarbage
* Translate ReturnToVendor
* Define ( + translate) user friendly error message when there is no QualityWarehouse
* Define ( + translate)user friendly error message when no HUs are selected
* Ask Mark what to do or define user friendly error message when you try MoveToQualityWarehouse 2nd time

**Comment by metas-rc** [comment]
Other thing I need to change in the garbage doc
* Add uom, asi, hu qty aand packvorschrift(hu name) in the inventory line
* Make different inventory per bpartner

**Comment by metas-mk** [comment]
* Translate MoveToQualityWarehouse (Warenbewegung)
* Translate MoveToGarbage (Entsorgung)
* Translate ReturnToVendor (Lieferanten Rücklieferung)
* Define ( + translate) user friendly error message when there is no QualityWarehouse (Es konnte kein Beanstandungslager gefunden werden.)

**Comment by teosarca** [comment]
is this task ready to be integrated?
Asking because there is a PR for it but the task is in Development lane.

**Comment by metas-rc** [comment]
Please, don't integrate it yet. I want to integrate it together with vendor returns and movements. There are still pending problems.

**Comment by metas-lc** [comment]
IT
1. selecting korrectur again after you did Entsorgung 
=> the HU is still there (destroyed) and you can't do anything with it NOK
=> we have follow-up for this https://github.com/metasfresh/metasfresh/issues/1327

2. when you do Entsorgung from korrectur vs from hu pos
=> on korrectur, warehouse from inventory (and line) is the one from order NOK (should be in HU's location - make sure if this is wanted)

3. (question only) in inventory line you have kosten = materialenthname (don't know for what is used this?)

4. press on korrectur, select the LU with 2 products and press on Entsorgung
=> error (something with qty to alloc) NOK

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
The last problem about the LUs for different products will be solved in https://github.com/metasfresh/metasfresh/issues/1604

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
Retesting last IT:
both swing and webui: 
1. selecting korrectur again after you did Entsorgung 
=> works now: solved in this https://github.com/metasfresh/metasfresh/issues/1327 OK

2. when you do Entsorgung from korrectur vs from hu pos
=> fixed : both have same warehouse (the one from HU) OK

3. (question only) in inventory line you have kosten = materialenthname (don't know for what is used this?) OK, wanted

4. press on korrectur, select the LU with 2 products and press on Entsorgung
=> error (something with qty to alloc) NOK - will be solved in another task

5. use entsorgung on a new LU (an LU split from an original one, after the inout was created)
=> nothing happens. We need retraceability. Follow-up: https://github.com/metasfresh/metasfresh/issues/1496

6. error when you try to do dispose: no errors anymore! OK


OTHER:
1. multiple inouts, different bpartner
=> entsorgung created per bpartner, the ones with same bpartner are aggregated per line OK
2. partial entsorgung from inout
=> the qty is set as you selected OK
