### ISSUE TITLE
Move HU to other Warehouse/ Locator

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1065]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, there is no possibility to move an HU to another Warehouse via Handling Unit Editor.
### What is the expected or desired behavior?
Provide a functionality (button) to create a material movement (w/ assigned HU) in Handling Unit Editor for selected HU. Movement and Transaction must be generated w/ the needed data (taken from HU) and HU must be assigned to the movement Document.

This new functionality shall be used to move the HU w/ bad quality to a special Warehouse/ Locator for bad Quality Performance.

belongs to the main issue: https://github.com/metasfresh/metasfresh/issues/547

**Comment by metas-rc** [comment]
* If the HU was already moved to a quality warehouse, it shall be no longer displayed in the Korrektur list
 -> Done

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 et al., Swing

* button for moving HU to other warehouse in Handling Unit POS, Handling Unit Editor: "Warenbewegung", OK
* pressing that button opens panel for warehouses where the selected HU can be moved to (must be IsQualityReturnWarehouse: Y): OK
* movement is created for the selected HU, to the selected IsQualityReturnWarehouse: OK
* notification for user about that movement: OK
* movement includes movement lines for the product as well as the HU(s): OK
* movement line for product has HU assignment: OK
* HU used in the movement is not displayed in the HU Editor of Korrektur option anymore: OK

* the selected & moved HU remained displayed in HU Editor, i had to close and reopen the Editor for the HU to disappear: i could select the same HU for e.g. Return to Vendor or Splitting or Materialentnahme (=> error): NOK
* when i tested, after creating the movement, the whole HU POS and Editor sometimes disappeared and then reappeared again; not sure if this is related with this task, but it's not happening with e.g. Materialentnahme 
* attributes as set in the HUs (e.g. quality note) are not displayed in the movement: not sure if this is wanted, afaik the attributes are also not displayed for movement of Materialentnahme, so might be OK? (attributes are displayed in movements for e.g. receipt in Wareneingang POS)

**Comment by metas-dh** [comment]
Results of IT2
tested on mf15 Swing (Windows as well)

problems i had before:

* the selected & moved HU remained displayed in HU Editor, i had to close and reopen the Editor for the HU to disappear: i could select the same HU for e.g. Return to Vendor or Splitting or Materialentnahme (=> error): fixed, OK

* when i tested, after creating the movement, the whole HU POS and Editor sometimes disappeared and then reappeared again; not sure if this is related with this task, but it's not happening with e.g. Materialentnahme: did not happen on Windows, so prob. x2go related

* attributes as set in the HUs (e.g. quality note) are not displayed in the movement: not sure if this is wanted, afaik the attributes are also not displayed for movement of Materialentnahme, so might be OK? (attributes are displayed in movements for e.g. receipt in Wareneingang POS): will test in followup for this problem: #1545
