### ISSUE TITLE
WebUI BPartner not saved mandatory Field IsHidePackingMaterialInShipmentPrint not set

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1066]
### Is this a bug or feature request?
Bug
### What is the current behavior?
BPartner not saved because of missing mandatory Field
#### Which are the steps to reproduce?
Try to create a new Business partner.
### What is the expected or desired behavior?
BPartner shall be savable.

**Comment by metas-dh** [comment]
Results of IT 1
tested on mf15releasetest

* newly created bpartner can be saved without problems: OK
* additional info can be added, like e.g. address, without problems: OK
