### ISSUE TITLE
Material Tracking ID not editable in Purchase Order Attributes Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1069]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When editing the Purchase Order line for a Product with Material Tracking ID, then it's not possible in WebUI, even though the Vendor and Product fits.
#### Which are the steps to reproduce?
Create a Material Tracking ID for a vendor and Product. Now create a Purchase Order for that vendor and Product and try to choose an existing Material Tracking Attribute value.
### What is the expected or desired behavior?
The correct Material Tracking ID shall be choosable.

**Comment by metas-mk** [comment]
Created Testcase and tested in Swing Client where it works. Does not work in WebUI
![image](https://cloud.githubusercontent.com/assets/13365687/23587344/5fe176e0-01aa-11e7-9590-c924b361b0f5.png)

**Comment by teosarca** [comment]
UPDATE:
* i've commited the work in progress code to gh1069 branch
* it might be that the changes are totally wrong and the solution is actually to implement #1082
