### ISSUE TITLE
Price not transferred to flatrate term

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1070]
### Is this a bug or feature request?
bug

### What is the current behavior?
price that is shown in order line is not copied to c_flatrateterm.priceactual

#### Which are the steps to reproduce?
1. create an order with one orderline
1. select a flatrate condition in order line
1. complete the order
1. go to window flatrate
NOK: check flatrate term price field. its null

### What is the expected or desired behavior?
price in c_flatrateterm.priceactual is the same as shown in order line

**Comment by metas-rc** [comment]
Results of IT1

Tested on mf15cloudit

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-1070.md OK
