### ISSUE TITLE
Empties document Jasper takes very long to generate

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1071]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The generation of an empties return/ receive document takes very long (20 secs).
#### Which are the steps to reproduce?
Create an empties return in WebUI. Complete. Print Document.
### What is the expected or desired behavior?
Shall be much faster 1-3 secs max.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* created and printed Empties document Jaspers, Return & Receive: jasper print took ~1 sec.: OK
