### ISSUE TITLE
NoDataFoundHandlers can cause StackOverflowError

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1076]
### Is this a bug or feature request?
Bug

### What is the current behavior?

```UnArchiveRecordHandler``` is called from PO if a record can't be found. It assume that the only reason the record wasn't found is that the record was archived. Therefor it extends the scopt to archived records and thries to load the record PO was unable to load. for this, it uses PO.
Now, if the record was un-loadable for other reasons that no `INoDataFoundHandlers` can migitate, then this behavior leads to a StackOverflowError

### What is the expected or desired behavior?

NoDataFoundHandlers which invokes the registered INoDataFoundHandler implementations needs to make sure that an already invoke implementation is not invoked again..at least not for the same record

**Comment by metas-dh** [comment]
was rolled out in swing yesterday

tested in swing, sp80: all problems from before related to this issue worked fine:

* creating orderline in purchase order: OK
* changing an existing (ASI) price, or creating a new one: OK
* processing of OLCands: OK
