### ISSUE TITLE
Implement support for table references in M_Attribute

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1082]
### Is this a bug or feature request?
Feature request

### What is the current behavior?
Atm the attribute's value type can be: String, Number, Date or List.
In case of list we can also pick AD_Val_Rule_ID which will filter the M_AttributeValue(s).

### What is the expected or desired behavior?
Implement support for Table attribute value type.
In this case the user shall pick the AD_Reference_Value_ID (new) and AD_Val_Rule_ID.

In case of List attribute value type, the AD_Val_Rule_ID shall no longer be available.

Reason: this would naturally allow us to reference things like M_Material_Tracking_ID without the need to create an M_AttributeValue for each M_Material_Tracking which would be eligible as an attribute value.
More (and important), this will allow the framework to decide how to cache the values, i.e. in this case we might not want to cache the values.

**Comment by teosarca** [comment]
Status update: WIP
* branch: https://github.com/metasfresh/metasfresh/compare/gh1082
* just introduced the new column... no BL

**Comment by metas-ts** [comment]
closing this issue..just the column is a dangling end and we can easily redo it if and when we want to perform the complete job
