### ISSUE TITLE
Introduce C_BPartner_QuickInput table/window to capture new BPartners

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1090]

**Comment by teosarca** [comment]
Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/126#issuecomment-284404187

**Comment by metas-mk** [comment]
Tested together w/ implementation of https://github.com/metasfresh/metasfresh/issues/1113 and https://github.com/metasfresh/metasfresh-webui-frontend/issues/126. Works as required.
