### ISSUE TITLE
Drop deprecated and confusing I_AD_User get/setFirstName methods

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1094]
in de.metas.adempiere.model.I_AD_User, drop confusing getFirstName/setFirstName, getLastName/setLastName because we already have them in org.compiere.model.I_AD_User as getFirstname/setFirstname ....

**Comment by teosarca** [comment]
pull request created.

**Comment by metas-rc** [comment]
Results of IT1

Tested on mf15cloudit

I created a user with first name and last name, was able to save. Was able to create user related entries. Had no errors. IT OK
