### ISSUE TITLE
Fix Materialentnahme movement creation

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1099]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Movement line for TU is not created

#### Which are the steps to reproduce?
* Create a purchase order for a product on a TU;
* Create a receipt for this (remember the HU value)
* Go to Hanling Unit POS, select the HU value 
* Click on Materialentnahme 
* Go to the created movement and then to its lines
* =>NOK: There are only lines for the LU and for the Product. No line for the TU 
### What is the expected or desired behavior?
* A line for TU should also be created.

**Comment by metas-ts** [comment]
Note: the BL is in `InventoryHUEditorModel.doDirectMoveToWarehouse()`

**Comment by metas-dh** [comment]
rolled out this morning

 Results of IT 1
tested on sp80 swing

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231099.md: OK
