### ISSUE TITLE
TU Ordered Qty in Material Receipt Schedule shows movedQty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1103]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Field "TU Ordered Qty" in Material Receipt Schedule shows the amounts of movedQtyTU and not orderedQtyTU.
#### Which are the steps to reproduce?
Create a Purchase Order. Jump to Material Receipt Schedule filtered Reference. Check the orderedQtyTU. Should match to QtyEnteredTU from the Purchase Orderline.
### What is the expected or desired behavior?
Show the orderedQtyTU.

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* before receipt: TU Ordered Qty in Material Receipt Schedule: shows orderedQtyTU from purchase order: OK
* after partial receipt: TU Ordered Qty in Material Receipt Schedule: still shows orderedQtyTU from purchase order, only movedQtyTU is updated: OK
