### ISSUE TITLE
inactive org still selectable on login

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1106]
### Is this a bug or feature request?
bug
### What is the current behavior?
deactivated org is still selectable on login 
#### Which are the steps to reproduce?
1. go to organisation window and create a new org e.g. TestOrg
2. deactivate this org (now you might need to logout/login to apply the changes)
3. log in => notice that you can choose TestOrg even if it's not active
### What is the expected or desired behavior?
don't show an inactive org on login

**Comment by teosarca** [comment]
note to IT: rolled out to w101

**Comment by teosarca** [comment]
tested, works.
