### ISSUE TITLE
webui HU Editor: conversion error when selecting SubProducer

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1110]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* receipt candidates
* receive some HU
* in attributes, try to select something in subproducer attribute
* assumption: there are some subproducers defined for current BPartner (the receipt candidate BP)
* so, select one of the subproducers
=> ERROR: cannot convert....

### What is the expected or desired behavior?
* subproducer shall be selectable selectable
* subproducer is used (consult e2e)

**Comment by teosarca** [comment]
NOTE to IT: if needed, bellow it's an SQL to fetch all subproducers for a given C_BPartner_ID:

```
select * from C_BPartner
where EXISTS (
	SELECT 1 FROM C_BP_Relation
	 WHERE (
		C_BP_Relation.C_BPartner_ID = C_BPartner.C_BPartner_ID 
		and C_BPartner_ID is not null
		AND (
			(C_BPartnerRelation_ID = <YOUR BPartner>)
			AND (IsMainProducer = 'Y')
			AND (IsActive='Y')
			AND (AD_Client_ID=1000000)
		)
	)
)
 AND (IsActive='Y')
 AND (AD_Client_ID=1000000)

```

**Comment by teosarca** [comment]
note to IT: rolled out on w101

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing.
