### ISSUE TITLE
HU receipt label is just a white sheet of paper

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1121]
### Is this a bug or feature request?
Bug

Related to metasfresh/metasfresh-webui#209

### What is the current behavior?

Material receipt labels coming out of the printer are white.
Looking at the archived PDF, it turns out to be just a white sheet either.

So: jasper worked, but aparently didn't have anything to print.
Btws, what works is if you prtint the thing "manually".
So I suspect the jasper is invoked too early. Going to invoke it *after* the commit instead

#### Which are the steps to reproduce?

Set up automatic printing of material-receipt-TU labels (metasfresh/metasfresh-webui#209) and make a material receipt

### What is the expected or desired behavior?

the printout should contain a TU label :-)

**Comment by metas-dh** [comment]
Results of IT1
tested on swing (tested by ts on webui)

* receipt label is correct, no white pages: OK
* label is printed automatically after receipt for each top level HU (once for 1 LU, 3 times for 3 IFCOs if those are top level etc.): OK
