### ISSUE TITLE
Reporting SQL for Products and vendor/ customer

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1122]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Create a new SQL which select the following Data for Products and BPartner
a) Product value
b) Product name
c) Attribute combination
d) BPartner value
e) BPartner name
f) qty in kg
g) first and last date of appearance in grouping a) - e)

Create for Vendor and Customer separated pls.

**Comment by metas-dh** [comment]
Results of IT1

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231122.md: OK
