### ISSUE TITLE
metasfresh App Server start takes considerably longer

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1124]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Server starts up in ~4 min but it used to be ~1 min

#### Which are the steps to reproduce?
use standard docker image 

### What is the expected or desired behavior?
should be ~1 min as before

Log is spammed with:
`2017-03-09 07:25:52.992  INFO 838 --- [main] o.a.ad.housekeeping.impl.HouseKeepingBL  : Skip checking sequence X_AD_Sequence[1254] because there is no key column name CM_Template_Ad_Cat_ID`

**Comment by metasnw** [comment]
as we are not using ad_sequence anymore we might want to drop the housekeeping task there...

**Comment by metas-ts** [comment]
note that this problem might be related to #941

> as we are not using ad_sequence anymore we might want to drop the housekeeping task there...
* we do still use it, for document numbers. But idk if those are fixed by this housekeeping task anyways.
* also, this house-keeping task deals with native sequences.

> Log is spammed with:

then i suggest to deactivate or delete that sequence

**Comment by teosarca** [comment]
Duplicate of #1123

**Comment by metas-ts** [comment]
I didn't remove AD_Sequence as #1123 suggests, but hopefully dealt with this concrete problem. 
therefore I reopen this issue so it can be ITed etc.

**Comment by teosarca** [comment]
> I didn't remove AD_Sequence as #1123 suggests, but hopefully dealt with this concrete problem.
> therefore I reopen this issue so it can be ITed etc.

just to be clear, #1123 does not suggest to drop AD_Sequence completely but to (completely) drop support for table sequences (i.e. those AD_Sequence records which have IsTable=Y).

> we do still use it, for document numbers. But idk if those are fixed by this housekeeping task anyways.
nop, it does not and the main reason why it cannot is because we support prefix and suffix for document sequence numbers and it's quite hard and/or inefficient to try to recompute it.

**Comment by metas-ts** [comment]
> just to be clear, #1123 does not suggest to drop AD_Sequence completely but to (completely) drop support for table sequences (i.e. those AD_Sequence records which have IsTable=Y).

ok, thx. got it now

**Comment by metasnw** [comment]
tested on 5.2
startup is back to 82 secs :-)
