### ISSUE TITLE
Product of Type Service can not be shipped using Shipment Schedule

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1127]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
use version 4.58.57

1. have an order with product type Service (Dienstleistung)
2. go to shipment schedule 
3. generate shipment
4. NOK: qtytodeliver is 0 (Liefermenge )

**Comment by metasnw** [comment]
solution:
disable type as it can be replaced by type item and no storage handling checkbox

workaround:
1. set product to type item
2. server cache reset / restart
3. update shipment schedule

**Comment by metas-dh** [comment]
Results of IT 1
tested on sp80

* disable type: type Service is no longer selectable for products: OK

@metasnw: what about old products which still have type Service set? e.g. sp80: Transport: do those need an update?

**Comment by teosarca** [comment]
@metas-dh  @metasnw  IMHO they shall be changed to ProductType=Item and IsStocked=N.
But I am not sure, we need to test it before...

**Comment by metasnw** [comment]
@teosarca agree. 
talked with mark. once we support this case fully we will renable producttype service again.

**Comment by metasnw** [comment]
decided to not provide migration script but just to prevent the users from creating new products type service which will not work at the moment
