### ISSUE TITLE
Close/ Open Action for Material Receipt Candidate Lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1132]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Currently, there is not possibility to close and open Material Receipt Lines in WebUI.
#### Which are the steps to reproduce?
Check the Material Receipt Candidates Window.
### What is the expected or desired behavior?
Provide the Processes/ Actions that are available in Swing Client.

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* close material receipt candidate line: option in Actions: OK
* after closing the line, user cannot receive anything / open the HU Editor for this line, but still available are Empties, Picture, Print Receipt & reactivating the line: OK
* after reactivating the line, you can create receipts / open the HU Editor again: OK
* Reverse (Korrektur) still available after closing the line: not nice, shall be changed in the future: https://github.com/metasfresh/metasfresh/issues/1151
