### ISSUE TITLE
Reorder the columns in Grid View for Material Receipt Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1133]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Community feedback about the sequence of Columns in Grid View of Material Receipt window showed that this can be optimized.
#### Which are the steps to reproduce?
Open grid view of Material Receipt Window in WebUI.
### What is the expected or desired behavior?
Reorder the columns after product as follows:
a) TU ordered
b) TU moved/ received
c) Packing Instruction
d) CU ordered qty
e) CU moved/ received qty

And pls. add the processed flag to Grid View, before the target Warehouse.

**Comment by metas-lc** [comment]
columns after product are ordered as follows:
b) TU moved/ received 
a) TU ordered
c) Packing Instruction
d) CU ordered qty
e) CU moved/ received qty

is it ok? or we want to change a <-> b?

processed flag is added to Grid View, before the target Warehouse. - OK

**Comment by metas-mk** [comment]
Thx @metas-lc Is ok like it is now. Closing.
