### ISSUE TITLE
Show Order ID in main window of Empties Receive

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1134]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Field Order ID is not shown in the main window of Material Receipt.
#### Which are the steps to reproduce?
Open the window and check.
### What is the expected or desired behavior?
Display the Field Order ID in the window near PO Reference.

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* order id displayed in window Leergut Ausgabe: OK

open questions, @metas-mk:
* order id NOT displayed in window Leergut Rücknahme: OK?
* bpartner from material receipt schedule is set in both Leergut Ausgabe & Rücknahme, OK?
=> it's different in swing: when selecting Rücknahme, the bpartner field is empty!

info from teo on the latter, from testing chat:
basically in receipt schedules we deal ONLY with vendors
and we are
* sending empties to them
* receiving empties from them

so as it looks like the customer use case is not handled at all

**Comment by metas-dh** [comment]
checked with mk:
* empties inouts for all bpartners should be done in material receipt warehouses, not only for the vendors: => users need to be able to "clear" the info already set in the empties when creating a new one:
https://github.com/metasfresh/metasfresh/issues/1207
