### ISSUE TITLE
Translation de_DE for Process Empties receive

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1135]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Translation for Process Empties Return
#### Which are the steps to reproduce?
Check the window and actions in Material Receipt.
### What is the expected or desired behavior?
Rename the Process Translation to "Leergut Rücknahme".

![image](https://cloud.githubusercontent.com/assets/13365687/23768602/e490c46c-050c-11e7-93fa-857f2de9a135.png)

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* Process Empties Return is now called "Leergut Rücknahme": OK
