### ISSUE TITLE
Show all request types in tab request in window Business Partner

### ISSUE THREAD

**Issue by nebergd** [metasfresh/metasfresh#1139]
### Is this a bug or feature request?
It is helpfull for working as a sales department if you can see all entries for the customer

![image](https://cloud.githubusercontent.com/assets/24392763/23790764/c91b1e2a-0580-11e7-9864-1cbc0513f8aa.png)

So as a sales man I can see in an overview what happens with the customer in date oriented sort

Thanks
Dieter

**Comment by nebergd** [comment]
Hi,
I tried this feature again and I saw request types for older GP. I added a new GP and also 2 new request types... but I cant see them after I look again this new GP
Dieter

**Comment by teosarca** [comment]
Might be that u just hit the issue described here: https://github.com/metasfresh/metasfresh-webui/issues/19


NOTE: as a workaround/quick solution we could:
* flag R_Request as HighVolume
* mark the BPartner->Request tab as readonly
reason: in that case the webui engine would pick a different strategy for querying the tab which does not involve caching.

**Comment by metasnw** [comment]
Problem is solved
