### ISSUE TITLE
too many prices in pricelist report

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1140]
### Is this a bug or feature request?
bug
### What is the current behavior?
1) if we have 2 productprices, one with price 0 (nu attributes) and one with price x (attribute price set, but nothing more) , then the one with price x appears twice.
2) if there is a productprice with a package+bpartner x is shown even for bpartner y
### What is the expected or desired behavior?
-price 0 and X show only X
- price for cu-tu of bpartner x -> show only for bpartner x

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
