### ISSUE TITLE
Change "sent by" in Request Notifications

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1146]
### Is this a bug or feature request?
feature

#### Which are the steps to reproduce?
1. enable request notifications
2. assign a request to an user with email address

### What is the expected or desired behavior?
mail body should have sent by metasfresh

**Comment by metas-dh** [comment]
Results of IT1
tested an mf15 swing

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231146.md: OK
