### ISSUE TITLE
Reverse (Korrektur) still selectable for a material receipt candidate line after it was closed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1151]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
A material receipt candidate line which was closed can still be reversed, Korrektur option is still selectable in Actions button.
#### Which are the steps to reproduce?
* in material receipt candidates, select a line
* in Actions, select Close (Zeile schließen)
* select Actions again for this line: Korrektur (Reverse) is still selectable
* you can reverse the material receipt that was already created, although line was closed
### What is the expected or desired behavior?
Reverse should not be a selectable option in Actions for a material receipt candidate line after it was closed.

**Comment by teosarca** [comment]
@metas-dh 
* i think that's an issue for metasfresh-webui
* i think the same logic shall be applied for: attach photo, empties receive/return. right?

**Comment by teosarca** [comment]
moved to https://github.com/metasfresh/metasfresh-webui-api/issues/251
