### ISSUE TITLE
Automatic login failed in Swing client

### ISSUE THREAD

**Issue by dram** [metasfresh/metasfresh#11582]
### Is this a bug or feature request?

Bug.

### What is the current behavior?

In Swing client (master branch), login is failed after Automatic Login is enabled in preference.

#### Which are the steps to reproduce?

1. Login Swing client using account metasfresh,  without app server
2. Click Tools > Preference, enable Automatic Login and click OK
3. Logout and open Swing client again

### What is the expected or desired behavior?

Swing client should be logged in automatically after Automatic Login preference is enabled.

**Comment by teosarca** [comment]
thx @dram but I have to close it because basically, we slide in this direction:
* https://github.com/metasfresh/metasfresh/pull/13965
