### ISSUE TITLE
Failed to update field value using rich text editor in grid mode in Swing UI

### ISSUE THREAD

**Issue by dram** [metasfresh/metasfresh#11593]
### Is this a bug or feature request?

Bug.

### What is the current behavior?

In grid mode, field value can not be updated using rich text editor.

#### Which are the steps to reproduce?

1. Open Swing UI, go to project page
2. Toggle grid mode
3. Right click "Description" column in any row, select "Editor"
4. Do some modification, and click OK button

### What is the expected or desired behavior?

Field value should be updated.

**Comment by teosarca** [comment]
@dram  closing because we are in process of getting rid of swing UI
