### ISSUE TITLE
Split from non-aggregate HUs can lead to wrong TU quantities

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1162]
### Is this a bug or feature request?
Bug
### What is the current behavior?
* If you split from an aggregate HU, that represents e.g. 175kg in 50IFCOs, and you want to split off one CU, then the system assumes that one CU is 175kg
* to make it worse, it looks like we allow the split to load more than what was unloaded, so we have a wonderful CU multiplication if the source is relatively small.

**Comment by metas-ts** [comment]
Note: it's not the swing client's fault, check my fix to learn more (if interested ;-) )

**Comment by metas-dh** [comment]
Results of IT1
tested on swing

* original bug did not appear anymore: OK
* splitting LUs / TUs / CUs from non-aggregated HUs did not result in weird or incorrect qties, worked fine: OK
