### ISSUE TITLE
TU Qty not in InOutLine after generated via w/ picked Qty in Shipment Schedule

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1164]
### Is this a bug or feature request?
Bug
### What is the current behavior?
TU Qty not in InOutLine after generated via w/ picked Qty in Shipment Schedule

**Comment by metas-lc** [comment]
IT
1. create new sales order with 5 TU A x 7
go to komm terminal and use verteilen 5 TU A x 7 
go to lieferdispo - gear - auswahl liefern - create inout from picked qty
go to inout => draft, only 1 line with product which has 5 qty TU and TU A x 7 as package, qty 35
complete inout => new line with 5 TU A x 7 appears

2. create new sales order with 6 TU A x 7
go to komm terminal and use verteilen 2 TU B x 10 
go to lieferdispo - gear - auswahl liefern - create inout from picked qty
go to inout => draft, only 1 line with product which has 2 qty TU and TU A x 7 as package!!, qty 20
complete inout => new line with 2 TU B x 10 appears

1. regression: normal lieferdispo with lieferungen fertigstellen
continue testcase 2 , make inout for remaining 22 
inout created and completed with 
- product line 4 TU A x 7, qty 22
- TU line 4 TU A 
- LU line 1

2. regression test 2
komm terminal + verdichtung to put them on LU  - inout from gear and from verdichtung
both work fine, LU and TU are set
