### ISSUE TITLE
QtyDelivered not set back correctly after reactivating and voiding a material receipt

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1165]
### Is this a bug or feature request?
Bug
### What is the current behavior?
QtyDelivered of product is not set back accordingly in material receipt schedule after material receipt was reactivated and voided. QtyDelivered of the TU is set back, however.
#### Which are the steps to reproduce?
* Make an inout in material receipt schedule, e.g. receive 10 G1 x 10kg of product A
* Open the material receipt, reactivate it, then void it
* Material receipt schedule: QtyDelivered of TU is back to 0, OK
* QtyDelivered of product A: still 100, NOK
=> QtyDelivered is set back correctly for product as well when voiding the material receipt directly, without reactivating it first. This happens on both WebUI and Swing.
### What is the expected or desired behavior?
If the material receipt was voided, then the QtyDelivered in material receipt schedule should be set back correctly for both product and TU, no matter if the material receipt was reactivated first or not.

material receipt:
![2017-03-16 16_30_04-metasfresh](https://cloud.githubusercontent.com/assets/18696715/24004284/2c1cc93a-0a66-11e7-95bb-7b80512fd5aa.png)

material receipt schedule:
![2017-03-16 16_30_28-metasfresh](https://cloud.githubusercontent.com/assets/18696715/24004296/36e07916-0a66-11e7-8cf2-118386efef3a.png)

**Comment by teosarca** [comment]
IMHO, the QtyDelivered shall be reset as soon as u reactivate.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 et al.

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231165.md: OK
