### ISSUE TITLE
Reactivate of Purchase Orders fails when completing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1166]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Reactivate of Purchase Orders fails when completing. Seems to be connected to remaining Material Receipt Schedule lines.
### What is the expected or desired behavior?

![image](https://cloud.githubusercontent.com/assets/13365687/23999797/a59803f4-0a59-11e7-8da6-ba5e8b5e8a18.png)

**Comment by teosarca** [comment]
NOTE: #1167 is also part of this task.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 et al.

* reactivating purchase order working fine, no error bc of remaining Material Receipt Schedule lines: OK
* after completing purchase order again, remaining Material Receipt Schedule lines are created again: OK
* after (partial) material receipt, purchase order cannot be reactivated anymore: OK

**Comment by metas-mk** [comment]
This issue happens when order complete - reactivate - material receipt done: after that not completion of order possible.
see solution https://github.com/metasfresh/metasfresh/issues/1209
