### ISSUE TITLE
Prevent C_Flatrate_Terms with overlapping dates

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1169]
### Is this a bug or feature request?
Has aspects of both

### What is the current behavior?
Currently, a user can create two `C_Flatrate_Term`s with the same `C_Flatrate_Data_ID` such that
`FlatrateDAO.retrieveNonSimTermOrNull(final I_C_Invoice_Candidate ic)` throws an exception like this one
```
Error: We can have only one non-sim term for X_C_Invoice_Candidate[C_Invoice_Candidate_ID=0, trxName=TrxItemChunkProcessorExecutor_af2c0cb1-cedb-417c-a37a-fac3c0c5f3e6], but we have the following terms with at least two being non-sim: [MCFlatrateTerm[C_Flatrate_Term_ID=1001240, trxName=TrxItemChunkProcessorExecutor_af2c0cb1-cedb-417c-a37a-fac3c0c5f3e6], MCFlatrateTerm[C_Flatrate_Term_ID=1001909, trxName=TrxItemChunkProcessorExecutor_af2c0cb1-cedb-417c-a37a-fac3c0c5f3e6]]; Exception: {}
```

Notes:
* the exception is thrown while the invoice candidate is created
* the proble is that there are two C_Flatrate_Terms with one term's `EndDate` being after the second term's `StartDate` and overlapping products in their `C_Flatrate_Matching`s
* Btw, in the concrete case the `C_Flatrate_Conditions.Type` is "Leergutverwaltung" (Refundable), but that 
doesn't matter in how the C_Flatrate_Term to apply is selected.

#### Which are the steps to reproduce?

Create two different "Refundable" contracts (from C_BPartner window) for the same BPartner, with Overlapping start/enddates and with `C_Flatrate_Conditions` that have overlapping products.

Now make a receipt that causes the system to try and create an IC for one of the overlapping products.

### What is the expected or desired behavior?

The system should sheck for this condition and create the C_Flatrate_Term, but not complete it *an* show a message to the user that tells him/her where the problem is.

### Additionall requirement

* Identify and fix existing C_Flatrate_Terms which have this problem
* Create an SQL that identifies and deletes exisingt ICs that ran into the problem.
AFAIK they are existing ICs without an aggregation group. They will be recreated by the system

Note: This issue might be related with #776

**Comment by metas-ts** [comment]
This SQL finds existing overlapping terms (with dates in present and future):
```sql
SELECT 
	part.Name as Partner_Name,
	part.Value as Partner_Value,
	t.C_Flatrate_Term_ID AS Term_1, 
	t.StartDate as StartDate_1,
	t.endDate as EndDate_1,
	cond.name as Flatrate_Conditions_1,
	x.C_Flatrate_Term_ID AS Term_2, 
	x.StartDate as StartDate_2,
	x.endDate as EndDate_2,
	x.name as Flatrate_Conditions_2,
	m.M_Product_Category_Matching_ID AS Product_Category, 
	string_agg( p.value||'_'||p.name, ', ' order by p.value) AS Product_Values
from c_flatrate_term t

join c_flatrate_matching m on t.c_flatrate_conditions_ID = m.c_flatrate_conditions_ID
join C_BPartner part on t.Bill_BPartner_ID = part.C_BPartner_ID
join C_Flatrate_Conditions cond on t.C_Flatrate_Conditions_ID = cond.C_Flatrate_Conditions_ID
join lateral
( 
	select t2. C_Flatrate_Term_ID, t2.StartDate, t2.EndDate, cond2.name
	from C_Flatrate_Term t2
	join c_flatrate_matching m2 on t2.c_flatrate_conditions_ID = m2.c_flatrate_conditions_ID
	join C_Flatrate_Conditions cond2 on t2.C_Flatrate_Conditions_ID = cond2.C_Flatrate_Conditions_ID
	where t.startDate <= t2.endDate AND t.endDate >= t2.startDate 
	AND 
	(
		(m.M_Product_ID = m2.M_Product_ID) -- product overlap
		OR
		(m.M_Product_ID <= 0 AND m2.M_Product_ID <= 0 AND m.M_Product_Category_Matching_ID = m2.M_Product_Category_Matching_ID) -- product category overlap
		OR
		(m2.M_Product_ID <= 0  and m.M_Product_ID > 0 and m.M_Product_Category_Matching_ID = m2.M_Product_Category_Matching_ID) -- product 1 in product category 2
		OR
		(m.M_Product_ID <= 0 and m2.M_Product_ID > 0 and m2.M_Product_Category_Matching_ID = m.M_Product_Category_Matching_ID) -- product 2 in product category 1
		
	)
	AND t.Bill_BPartner_ID = t2.Bill_BPartner_ID
	AND t.C_Flatrate_Term_ID <> t2.C_Flatrate_Term_ID
	AND (t2.C_Flatrate_Term_ID = t.C_FlatrateTerm_Next_ID OR (t.C_FlatrateTerm_Next_ID IS NULL AND t2.C_Flatrate_Term_ID > t.C_Flatrate_Term_ID))
) x on true

left join M_Product p on (m.M_Product_Category_Matching_ID = p.M_Product_Category_ID AND m.M_Product_ID IS NULL) OR (m.M_Product_ID = p.M_Product_ID AND m.M_Product_ID IS NOT NULL)

group by t.C_Flatrate_Term_ID, x.C_Flatrate_Term_ID, m.M_Product_Category_Matching_ID, part.name, part.value, t.startdate, t.enddate, x.startdate, x.enddate, cond.name, x.name
order by t.C_Flatrate_Term_ID;
```

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* tested flatrate terms for Gebinde, Lagerkonferenz, Liefervereinbarung & Ausschreibung (checked with ts: the latter 2 and Abo from orderlines were not included in this task's description, i will create new issues for those)

problems i had:
* when creating a flatrate term for the same / an included product with overlapping dates of an already existing term, i got the error msg about the newly created flatrate term not being completed bc of overlapping dates, with the ID of the new term (OK), BUT: when checking in C_Flatrate_Term, i could not find that new term, and in db i got no results for this ID from the msg

* the already existing flatrate term is only considered when it is active and completed, so you can create a new term with overlapping dates if the existing one is inactive or e.g. was reactivated by another user and is not completed while creating the new term

**Comment by metas-ts** [comment]
From what i can see, @metas-rc now addressed the first item of the "[problems i had](https://github.com/metasfresh/metasfresh/issues/1169#issuecomment-295162177)" comment.

Is is harder than expected to also check for overlapping if a contrat is set to IsActive='Y'?

**Comment by metas-rc** [comment]
One cannot activate and deactivate a term manually. Everything should be covered at completion, 
with logs in the 2 processes (term creation, term extention) and with exception when a user tries to complete a term by hand.
Shall I add an extra interceptor nevertheless?

**Comment by metas-rc** [comment]
I talked with @metas-ts  and @metas-dh and we decided to not add the IsActive interceptor. The changes while testing were done via direct db queries. Since the flag IsActive is not displayed, the interceptor is not needed.

**Comment by metas-dh** [comment]
Results of IT2
tested on Swing

https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_tests_collection/Testcase_%231169.md: OK

* for Liefervereinbarung: https://github.com/metasfresh/metasfresh/issues/1337
* for Ausschreibung: https://github.com/metasfresh/metasfresh/issues/1338
