### ISSUE TITLE
Inactive BPartner is not shown in open items report

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1171]
### Is this a bug or feature request?
bug

### What is the current behavior?
Inactive bpartner is not shown in open items report.

#### Which are the steps to reproduce?
* run open items report
* pick a partner which has some open invoices
* deactivate it
* run the report again
=> the bpartner is no longer there => NOK

### What is the expected or desired behavior?
An open invoice is an open invoice and shall be present in open items even if bpartner was deactivated.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
