### ISSUE TITLE
Show only those weighing machines which are available for HU's warehouse

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1172]
### Is this a bug or feature request?
Bug/ missing configuration
### What is the current behavior?
Opening the HU Editor in Material Receipt Candidates does not show the Weighing Machine Buttons.
#### Which are the steps to reproduce?
Select a Material Receipt Candidate w/ weight uom (e.g. kg), and do the receipt. HU Editor opens. Select the LU Level and try to weight. No weighing machine button.
### What is the expected or desired behavior?
Show the weighing machine buttons.

**Comment by teosarca** [comment]
Configuration:
Introduced sysconfig de.metas.device.<deviceName>.M_Warehouse_ID (optional) to be able to configure on which warehouse the given device is available.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 et al.

* weighing machine buttons displayed when opening HU Editor: OK
* pressing weighing machine buttons: weight of the selected HU (LU/TU) is updated accordingly to what was displayed on the button: OK
* weighing machine button only affects the gross and net weight, not tara: OK

@metas-mk:
* weighing machine buttons are also displayed and work for products with UOM=Stk, but it's the same in Swing, so i presume that is OK?

**Comment by teosarca** [comment]
i would suggest to create a new task for that

**Comment by metas-dh** [comment]
Also tested full WebUI e2e (w101).

All working fine, except for invoicing (2 invoices instead of 1), will be fixed in https://github.com/metasfresh/metasfresh/issues/1186.
