### ISSUE TITLE
Shipment problem when different order lines are commissioned into one HU

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1174]
### Is this a bug or feature request?

bug

### What is the current behavior?

Assume you have two different sales orders from the same customer, with the same datepromised and small quantities. The system creates `M_ShipmentSchedule` records for all the sales order lines.

Commission both of them into *one* shared TU. 
Now there is one TU with status "picked" which is assigned to all the two sales orders' `M_ShipmentSchedule ` records.

Now, go to the shipment schedule window, filter for the first of those two sales orders and create (and complete!) a shipment.
This means the the TU's status ich changed to "shipped".

Now, still in the ShipmentSchedule window, filter for the second of the two sales order and attempt to create another shipment. This fails, because the respective TU is not available anymore.

### What is the expected or desired behavior?

* When the first InOut it's created, the TU is flagged a "shipped", because that's reality. The whole TU is shipped, no matter if all its VHUs are already assigned to an inout line or not.
* However, it shall still be possible to create the second inout. Then the shared HU(s) need to be assingned to all relevant inout lines and basically that's it.

**Comment by metas-ts** [comment]
# Workaround/Troubleshooting

```sql
-------
-- Diag
-------
select sp.*, hu.hustatus
from M_ShipmentSchedule s
	join M_ShipmentSchedule_QtyPicked sp on s.M_ShipmentSchedule_ID=sp.M_ShipmentSchedule_ID
		join M_HU hu ON sp.m_tu_hu_id=hu.m_hu_id
where s.C_Order_ID=<ID of the Order that causes problems>
and hu.hustatus='E' -- 'E' means "shipped"

------
-- Fix
------
update M_ShipmentSchedule SET IsActive='N'
WHERE M_ShipmentSchedule_ID IN (<shipment-schedules-IDs-with-already-shipped-HUs>)

INSERT INTO M_ShipmentSchedule_Recompute (M_ShipmentSchedule_ID) values (2137638),(2137643),(2137649),(2137646)

--
-- run the manual shipment schedule update process if needed
-- create the inout without the deactivated scheds
--

update M_ShipmentSchedule SET IsActive='Y'
WHERE M_ShipmentSchedule_ID IN (2137638,2137643,2137649,2137646)

INSERT INTO M_ShipmentSchedule_Recompute (M_ShipmentSchedule_ID) values (2137638),(2137643),(2137649),(2137646)

UPDATE M_ShipmentSchedule_QtyPicked
SET IsActive='N'
WHERE M_ShipmentSchedule_ID IN (2137638,2137643,2137649,2137646)

INSERT INTO M_ShipmentSchedule_Recompute (M_ShipmentSchedule_ID) values (2137638),(2137643),(2137649),(2137646)
--
-- run the manual shipment schedule update process if needed
-- create the inout for the remaining scheds (which area now "uncommissioned" as far as metasfresh is concerned)
--
```

**Comment by metas-ts** [comment]
# TODO

if different products with different `M_ShipmentSchedules`are commissioned into one TU and if then a shipment is created for one of those schedules, then the respective VHU needs to get the "shipped" status and the other need to remain "picked", until it is also shipped

**Comment by metas-ts** [comment]
when testing, please also verify that https://github.com/metasfresh/metasfresh/issues/759 still works

**Comment by metas-dh** [comment]
Results of IT1
tested on sp, Swing

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%20%231174.md: OK

https://github.com/metasfresh/metasfresh/issues/759: still working fine, OK
