### ISSUE TITLE
Price is found for C_OlCand despite it was deactivated

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1184]
### Is this a bug or feature request?

i'll call it a bug

### What is the current behavior?

if you go to the curret/recent price list version and deactivate a product-price, then a `C_OLCand`with that product is still not flagged with error. Instead, the system fetches the price not from the recent PLV, but instead from the pricelist's base pricelst `M_PriceList.BasePriceList_ID` this is actually a (very old) feature which was accidentally turned into use.

### TODO

* The immediate workaround is to deactivate the related pricing rule `BasePriceList`.
* Also, this rule shall not even apply if there is a PLV-ID specified in the priving context
* Further, we chall check the other rules accordingliy
* Lastly, we need to add a nice javadoc to explain the rule and when it should or should not be used

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* price for product in recent PLV deactivated, product used in OLCands for EDI import: OLCand is flagged with error: OK
* OLCand shows info about the product not being included in the pricelist used, with date: OK
* price is not taken from pricelist's base pricelst, where the product price is still active: OK
