### ISSUE TITLE
small adjustments in jasper documents

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1191]
### Is this a bug or feature request?
bug
### What is the current behavior?
- asi and qtyTU are not bolded: in purchase invoice pdf (header)
- logo on the second page gets above document no for: empties, sales invoice and sales order
- see if there is a way to not have a second empty page
#### Which are the steps to reproduce?
printing the jaspers for documents with lots of lines 
### What is the expected or desired behavior?
- all header fields to be bold
- logo on the second page to be as high as on the first page
- no second empty pages

**Comment by metas-dh** [comment]
Results of IT1
tested on mf, Swing & WebUI

* asi and qtyTU are not bolded: in purchase invoice pdf (header): header fields are bold, OK
* logo on the second page to be as high as on the first page OK
* second empty page in sales invoice jasper: still included, NOK

**Comment by metas-dh** [comment]
Results of IT2
tested on mf, Swing & WebUI

* second empty page in sales invoice jasper: not included anymore, OK
