### ISSUE TITLE
Pricing: IsDefault was not properly migrated

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1192]
###  Is this a bug or feature request?
bug

### SQL to migrate isDefault 

(thx @teosarca)

```sql
drop table if exists M_ProductPrice_IsDefault_ToUpdate;
create temporary table M_ProductPrice_IsDefault_ToUpdate as
select
    t.M_ProductPrice_ID
    , pa.IsDefault
from backup.TMP_M_ProductPrice_New t
inner join backup.M_ProductPrice_Attribute_BKP pa on (pa.M_ProductPrice_Attribute_ID=t.Old_ProductPrice_Attribute_ID)
;

--
create index on M_ProductPrice_IsDefault_ToUpdate(M_ProductPrice_ID);

-- Check it
select * from M_ProductPrice_IsDefault_ToUpdate;

--
-- Update
/*
update M_ProductPrice pp set IsDefault='Y'
from M_ProductPrice_IsDefault_ToUpdate t
where pp.M_ProductPrice_ID=t.M_ProductPrice_ID
;
*/
```

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 et al.

* IsDefault not included in mf15, => we had a rollout problem, script was not included, need to check again after next one
* sp: IsDefault wasn't missing in the 1st place, tested with EDI import: created https://github.com/metasfresh/metasfresh/issues/1193

**Comment by metas-dh** [comment]
Results of IT2
tested on mf15 et al.

* IsDefault now also included in mf15 after last rollout: OK
* sp: ISDefault prices from old db not migrated atm, will be back with the next db version we'll get: OK
* note: pricing tests will continue, this task was about the migration of the IsDefault price checkbox
