### ISSUE TITLE
HU "Herkunft" HU_Attribute is not propagated from LU to VHU

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1194]
### Is this a bug or feature request?

Bug

### What is the current behavior?

If you receive goods lying directly on a palette and change the "Herkunft" attribute, then that change is not propagated to the underlying VHU

#### Which are the steps to reproduce?

* make a purchase order with a product, with a certain Herkunft attribute instance, but no TU
* receive the product on a pallete (i.e. don't insert a TU now)
  * and ofc change the Herkunft in the HU edotor

Note: in this case, the HU is an aggregate one, i.e. there is just
* LU (M_HU, "Pallet")
  * M_HU_Item with type= HA
    * VHU with the actual product

=> to verify the bug, find the VHU in the HU (non-POS) window, check its attributes verify that its Herkunft attribute still has the wrong value

### What is the expected or desired behavior?

if you change an attribute like Herkunft in the HU editor, then that change should be propagated downwards

**Comment by metas-lc** [comment]
IT
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%231194.md
OK
