### ISSUE TITLE
Clean up ReplicationException

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1202]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Currently, `org.adempiere.server.rpl.exceptions.ReplicationException` has an addParameter method which is as of #1197 now also avaiable in AdempiereException.

Therefore, we can now remove this from ReplicationException

**Comment by metas-dh** [comment]
checked with ts: cannot be tested, putting it to Done.
