### ISSUE TITLE
Provide Default KPI Config

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1205]
### Is this a bug or feature request?
feature request

### What is the current behavior?
elastic search is available as container but no KPI are configured so the dashboard looks like usual

#### Which are the steps to reproduce?
log on and there are no kpis on dashboard

### What is the expected or desired behavior?
have default KPIs for sales

**Comment by metasnw** [comment]
basically, pls export/import following tables:
KPI definition: WEBUI_KPI, WEBUI_KPI_Field
Dashboad definition: WEBUI_Dashboard, WEBUI_DashboardItem
Then, from swing client
login as System Administrator
open Table and Columns and go to "C_OrderLine" table
gear -> call the process which is adding this table to ES index (forgot how is called)

**Comment by metas-ts** [comment]
..also cherry-picked this one into the release branch

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15releasetest

* KPIs for sales are displayed in dashboard after log in: OK
