### ISSUE TITLE
Remove Gebinderückgabe from Shipment Note for mf15 endcustomer

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1206]
### Is this a bug or feature request?
feature request

### What is the current behavior?
Gebinderückgabe is always displayed on shipment note 

#### Which are the steps to reproduce?
1. Create a shipment
2. open print preview

### What is the expected or desired behavior?
remove that text from jasper only on mf15 endcustomer

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, Swing & WebUI:

* if no packing item is used in shipment (e.g. only VPI), no "Gebinde Retouren" displayed in the jasper anymore: OK
* if packing item was used, "Gebinde Retouren" section is still included: OK
* regression: only on mf, always displayed for other customers: OK
