### ISSUE TITLE
Preparation Time: Change to first possible on same Day as Promised Date-Time

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1211]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Preparation Date-Time is calculated as the earliest possible from now on.
#### Which are the steps to reproduce?
Create a Sales Order and check.
### What is the expected or desired behavior?
The Preparation Date-Time shall be calculated as the earliest possible on the same day of Promised Date.

Today is 27.03.2017
Tour for BPartner is 2 times every day: a) 11:30h b) 18:30h buffer) 4h

Case 1: Promised Date-Time = 27.03.2017 23:59h, Sales Order Creation 27.03.2017 11:29h
--> Result: 27.03.2017 11:30h

Case 2: Promised Date-Time = 27.03.2017 23:59h, Sales Order Creation 27.03.2017 11:31h
--> Result: 27.03.2017 18:30h

Case 3: Promised Date-Time = 02.04.2017 23:59h, Sales Order Creation 27.03.2017 11:29h
--> Result: 02.04.2017 11:30h

**Comment by metas-lc** [comment]
IT
https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_tests_collection/Testcase_%231211.md OK
