### ISSUE TITLE
Show orderline description only in the first column of the Jasper

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1222]
### Is this a bug or feature request?
feature request 

### What is the current behavior?
text is going all the way to the end of the line making the doc unreadable

#### Which are the steps to reproduce?
have a sales order line and put lots of text into description field

### What is the expected or desired behavior?
text should stop where the next field start on the jasper document (e.g. Quantity)

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 Sing & WebUI

* long text in description is not displayed over the whole page to the end of the line anymore:  OK
* texts stops where the next field starts (Menge / Quantity), continues after break: OK
