### ISSUE TITLE
show line number in jaspers

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1223]
### Is this a bug or feature request?
feature
### What is the current behavior?
line nr are not shown on details
#### Which are the steps to reproduce?
make a docu with lines - print
### What is the expected or desired behavior?
show line no in the first column of details jasper (sales/purchase order, invoice, inout)

**Comment by metas-lc** [comment]
- lineno not bolded in pdf (everywhere) 
- uom cut off (purchase order)

**Comment by metas-ts** [comment]
opps, sorry, looks like I unintentionally closed this issue :blush:

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing & WebUI, mf15 et al.

* line no. included in jaspers & PDFs, orders, inouts, invoices: OK
* header for line no. bold as the others: OK
* no cut-offs in the other headers: OK
* displayed in mf15, not sp: OK

follow-up: https://github.com/metasfresh/metasfresh/issues/1378
