### ISSUE TITLE
hide HU related data where is not used 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1224]
### Is this a bug or feature request?
feature
### What is the current behavior?
there are documents where we don't have HUs but still show in details header when printing jasper
(for now sales order and inout are done)
#### Which are the steps to reproduce?
create docu with lines with no Hus - print: you will have a column for package material and qty TU
### What is the expected or desired behavior?
remove package material when there are no HUs used

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* documents without HUs (order -  inout -  invoice, PO & SO): no column for package material and qty TU in the jaspers: OK
