### ISSUE TITLE
drop legacy jasper sql logic

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1225]

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* docbasetype = 'SOO' AND dt.docsubtype IN ('ON', 'OB'), when  pl.istaxincluded = 'N' (plus):  'plus' and 'included' were taken out from jasper (mf): OK
* checked with mk:  dt.docsubtype IN ('ON', 'OB') not used for sp, so no regression necessary
