### ISSUE TITLE
Reactivated Purchase Order Lines shown in Receipt Schedule

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1232]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Reactivated Purchase Order Lines are shown in Receipt Schedule 
#### Which are the steps to reproduce?
Create a purchase Order. Complete. Reactivate. Jup to Material Receipt Candidates.
### What is the expected or desired behavior?
Don't allow the receipt for not completed Receipt Schedule Lines. (or don't show them)

**Comment by teosarca** [comment]
NOTE: might be related (somehow) with https://github.com/metasfresh/metasfresh/issues/1166
