### ISSUE TITLE
Split fails with aggregate HUs that don't have an integer storage qty

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1237]
### Is this a bug or feature request?
Bug
### What is the current behavior?

If you try to split an aggregated HU with an overall storage quantity such as 109.4kg, there will be an exception. See this issue's private pendant for a screenshot.

But i think it will happen always, if you try to split a TU from an aggregate HU whose storage quantity is not a natural number

**Comment by metas-lc** [comment]
quick check:
1. purchase order with 5 HUx4.5 => 22.5 kg
2. open it in hu editor, split on 12 HUx2 => no errors
3. open the line in hu editor again, this time 1 HU with qty 103.4 
4. split a part of it => ok, no errors

**Comment by metas-dh** [comment]
Results of IT1
tested in w101 for WebUI et al for Swing

* split off aggregated HUs where TU type was e.g. 12.5 kg, overall weight 62.5kg: no exception or errors, split worked fine
* split off aggregated HUs where overall weight after weighing was e.g. 32.4 kg or 20.08kg: no exception or errors, split worked fine
