### ISSUE TITLE
Barcode on Bestellkontrolle report

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1239]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Currently, the Bestellkontrolle report created after Sales Order complete does have a document No, Product No but not a barcode for those.
#### Which are the steps to reproduce?
Check the report.
### What is the expected or desired behavior?
Behind each line, show a barcode which has the OrderNo and Product No, Line No.
This barcode shall be used later to scan that Barcode and automatically open the Manufacturing Issue/ Receipt modal overlay.

**Comment by metas-mk** [comment]
Tested. Currently, the char "_" is shown as ? when scanning w/ barcode ready. It seems that the reader does not recognize that sign. I took a look at the character set of code39. Seems that it would be better to take "-" (minus) or "+" (plus) as a separator instead.
https://de.wikipedia.org/wiki/Code39

**Comment by teosarca** [comment]
rolled on w101

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Tested on swing.
Works fine. THe barcode is saved in the database with "-" signs.
