### ISSUE TITLE
Number-of-copies parameter is ignored in direct print

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1240]
### Is this a bug or feature request?

Bug

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* no. of material receipt printed automatically (proper print, not preview): no. of copies printed was as set in de.metas.handlingunits.MaterialReceiptLabel.AutoPrint.Copies for the org used: OK
* no. of copies printed for invoice as set in bpartner (proper print, not preview): OK
