### ISSUE TITLE
Shipment Schedule's QtyDeliveredTU is not updated correctly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1244]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* create sales order
* pick some aggregated HUs for shipment schedule; mind the number of TUs you are picking
* generate shipments for that shipment schedule (use qty picked, complete)
* check the shipment schedule QtyDeliveredTU => it's wrong, it's always ONE instead of the real number of TUs => NOK

### What is the expected or desired behavior?
QtyDeliveredTU  shall be incremented with the actual number of TUs which were issued.

**Comment by teosarca** [comment]
@metas-ts  pls check the TODOs, R&I

**Comment by metas-dh** [comment]
Results of IT1
tested on sp

* picked aggregated HUs only (5 TUs) in picking terminal, created shipment in shipment schedule for qty picked: QtyDeliveredTU = 5, OK
* picked aggregated HUs (3 TUs) plus free HUs (2 TUs) in picking terminal, created shipment in shipment schedule for qty picked: QtyDeliveredTU = 5, OK
