### ISSUE TITLE
Empties movements are not generated from empties shipment/receipt

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1248]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Case 1.
* from webui
* create a new empties shipment or receipt (via Receipt candidates view, quick actions)
* fill it with some packing materials
* complete it
Check the movements window => no movements were generated to move from/to empties warehouse to/from the warehouse where the shipment/receipt was created.

Case 2.
* create an empties shipment/receipt using Swing client, Wareneingang POS
* open the generated empties inout (shipment/receipt)
* check also the empties movements which were generated => those movements were not linked to that empties inout => NOK
* reverse the generated empties inout => check the movements, they were not reversed => NOK

Case 3.
* split some HUs
* check the empties movements: they were generated in opposite direction => NOK

hint: to quick test you can pick some HUs and split 1LU x 1TU x 1CU out. You shall have an empties movement which moves the empties FROM empties wh to HU's wh.

### What is the expected or desired behavior?
Solve the NOKs ;)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 (WebUI) et al (Swing)

WebUI:
* movement generated from warehouse to HU warehouse (empties receipt) / from HU warehouse to warehous (empties shipment) when empties inouts are created: OK
=> could not add products in empty inouts using Add new, see https://github.com/metasfresh/metasfresh-webui-api/issues/295

Swing:
* empties shipment / receipt is linked to movement: OK
* reversing the empties shipment / receipt: movement is also reversed: OK
* splitting off HUs in Verdichtung POS: movement for new HU from empties warehouse to warehouse in Verdichtung created: OK
