### ISSUE TITLE
DocumentNo not generated for manual invoices in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1260]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The DocumentNo not generated for manual invoices in WebUI
#### Which are the steps to reproduce?
Try to create one.
### What is the expected or desired behavior?
Create DocumentNo automatically in WebUI for Invoice Documents.

Belongs to https://github.com/metasfresh/metasfresh-webui-api/issues/281

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* Document No is generated for manual sales invoice: OK

@metas-mk, @teosarca: is this supposed to work for manual purchase invoices as well? (in Swing, the Doc No. for purchase invoice is generated when saving the document for the 1st time;  in WebUI, it has to be set)

**Comment by metas-mk** [comment]
@metas-dh thx for the info. no, that shouldn't be. should also be set automatically for purchase invoices. checking.

**Comment by metas-mk** [comment]
@metas-dh @teosarca the reason that it was not working for purchase orders was in the doctype, it was not document no controlled. i switched to 'Y'. works now.

**Comment by metas-lc** [comment]
IT
checked again, both sales and purchase invoice generate document number OK
