### ISSUE TITLE
ITrxListener.afterCommit is fired twice with TrxPropagation.REQUIRES_NEW

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1263]
### Is this a bug or feature request?
Bug
### What is the current behavior?

Check out `AbstractTrxManager.call0()`:
it's fired directly after the "commit" and once again in the finally block, when the trx is closed

#### Which are the steps to reproduce?
Set a breakpoint in `HUReportExecutor.executeHUReportAfterCommit()` and enable automatic HU label on receipt creation

### What is the expected or desired behavior?

should only be fired once

**Comment by metas-dh** [comment]
checked with ts: automatic label printing is working fine at customer, task can be closed.
