### ISSUE TITLE
Material Receipt document best before date missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1264]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the best-before-date is missing on Material Receipt Document.
#### Which are the steps to reproduce?
Create one, set a date and check the Receipt document.
### What is the expected or desired behavior?
Print the best-before-date on the Material Receipt Document.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* best-before-date included in Material Receipt Label: when printed manually, when printed automatically with receipt: OK
* best-before-date also included as attribute in Jasper for receipt (printed in Wareneingang POS & M_Inout): OK

**Comment by metas-dh** [comment]
when testing https://github.com/metasfresh/metasfresh/issues/1240, i noticed that the MHD field, if left empty in HU Editor, returns a "null" in the material receipt label: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested on Swing

* best-before-date included in Material Receipt Label: when printed manually, when printed automatically with receipt: OK
* best-before-date also included as attribute in Jasper for receipt (printed in Wareneingang POS & M_Inout): OK
* MHD field, if left empty in HU Editor, does not return "null" in the material receipt label: OK
