### ISSUE TITLE
Best-before-date is missing on Material Receipt Label.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1265]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the best-before-date is missing on Material Receipt Label.
#### Which are the steps to reproduce?
Create one, set a date and check the Receipt Label.
### What is the expected or desired behavior?
Print the best-before-date on the Material Receipt Label.

**Comment by metas-lc** [comment]
solved in https://github.com/metasfresh/metasfresh/issues/1264 
to be tested when this task gets in IT

**Comment by metas-dh** [comment]
works fine, see IT for https://github.com/metasfresh/metasfresh/issues/1264
