### ISSUE TITLE
Cannot open ASI editor in Swing

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1267]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* select a draft order which has some lines with some ASI set.
* try to open the ASI editor => nothing happens when clicking on that small button

### What is the expected or desired behavior?
ASI editor shall be opened (even if the product does not have an attribute set assigned)

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 et al.

* ASI editor opens in orderline: OK
* ASI can be added / changed / taken out: OK
* ASI editor opens also when product has no ASI set yet: OK

@teosarca: ASI editor does not open if the product category of the resp. product does not have any M_AttributeSet set yet, i guess that is NOK?

**Comment by teosarca** [comment]
> @teosarca: ASI editor does not open if the product category of the resp. product does not have any M_AttributeSet set yet, i guess that is NOK?

* If the ASI is currently empty/not set => OK
* If there are some attributes set, you always shall be able to edit them

**Comment by metas-dh** [comment]
thanks, then it's working fine
