### ISSUE TITLE
webui - allow using the session's remote host name or IP as hostkey

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1274]
### Is this a bug or feature request?
Feature request

**Comment by metas-ts** [comment]
* The AD_Session.HostKey value is now initially set to `<not-yet-determined>` and then "lazily" set to its real value when it is first needed.

* The swing-client still works with a UUID value that is stored in the metasfresh.ini file (as before)
* For the webui, you can now use the SysConfig value `de.metas.printing.webui.HostKeyStorageMode` and set if to either `cookie` or `session.remote_host`. With the latter setting, the system will use the AD_Session.Remote_Host value as host key.

**Comment by metas-dh** [comment]
checked with ts: running & working fine for customer, was tested there: OK.
closing & moving to Done
