### ISSUE TITLE
Performance Business Partner Pricelist generation process

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1286]
### Is this a bug or feature request?
Feature
### What is the current behavior?
The Performance of Pricelist generation via Business Partner gear process takes too long (several minutes).
#### Which are the steps to reproduce?
Open a Business partner and start the Price List process.
### What is the expected or desired behavior?
Make it faster (seconds).

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

*  Pricelist generation via Business Partner gear process: takes sev. seconds, not minutes (also the comparison one): OK
* purchase pricelists take longer (prob. bc of several TU and ASI options) than sales ones, but still only seconds, not minutes: OK
