### ISSUE TITLE
Search for name in product window in webUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1287]
### Is this a bug or feature request?
feature

### What is the current behavior?
you can only search for number 

#### Which are the steps to reproduce?
open product window and click on search

### What is the expected or desired behavior?
add the name field to standard filter

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, w101 et al.

* working fine in mf15 et al. WebUI: OK
* no filter for name in product search on w101:  not rolled out yet?

**Comment by metas-dh** [comment]
Results of IT2
tested on w101

*  checked again: filter for name in product search now included as well: OK
