### ISSUE TITLE
Report with Attribute Set Parameter cannot be started anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1294]
### Is this a bug or feature request?
Bug
### What is the current behavior?
A Report with Attribute Set Parameter cannot be started anymore. The user receives an exception.
#### Which are the steps to reproduce?
Start the Report "ADR Auswertung" and press on the Attribute Button.
### What is the expected or desired behavior?
Allow the Attribute selection and start the report.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* open report "ADR Auswertung", click on attribute button: no exception, you can select all available attributes: OK
* select an attribute, set a time frame, click OK: report is created for the parameters set
