### ISSUE TITLE
Jasper Document for Material disposal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1304]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have a printable document for Material Disposal.
### What is the expected or desired behavior?
Create a Material Disposal Document with Jasper Reports and make it available/ printable in the disposal (internal inventory) record.
![image](https://cloud.githubusercontent.com/assets/13365687/24896723/86f6afd0-1e96-11e7-842b-943196369e9c.png)

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/547

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, Swing

* got an exception when trying to open the Jasper:
org.adempiere.exceptions.AdempiereException: Caught class java.io.IOException trying to invoke URL http://mf15cloudit:8282/adempiereJasper/ReportServlet?AD_Process_ID=540789&AD_PInstance_ID=1002539&AD_Language=de_DE&output=JasperPrint; message: Server returned HTTP response code: 500 for URL: http://mf15cloudit:8282/adempiereJasper/ReportServlet?AD_Process_ID=540789&AD_PInstance_ID=1002539&AD_Language=de_DE&output=JasperPrint: NOK

**Comment by metas-lc** [comment]
IT
webui:
the signature words are cut off NOK - make the fields bigger
swing:
same cuts NOK
OK: draft docus have "Entwurf"

**Comment by metas-ts** [comment]
cherry-picked into `release`, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/171/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
signature words are not cut off anymore
