### ISSUE TITLE
Customer Returns Functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1306]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have an easy way to receive Customer Returns based on delivery Note lines and HU Assignments.
### What is the expected or desired behavior?
Create the Functionality via Customer Returns Window or Material Receipt Window. Still in Discussion.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/547

**Comment by metas-dh** [comment]
Results from IT1
tested on mf15 Swing

* HU creation for the customer return: TU as set in M_HU_PI_Item_Product, plus 1 LU (per product line): OK
* movement for the HUs created: from Gebinde warehouse to warehouse selected in return: OK (had to create a warehouse for PIs first)
* HU Assignment in the customer return, with the HUs created (LU): OK
* invoice candidates created for the products customer return, with neg. qty (correct qty CU): OK
* customer return for >1 product: >1 HU created, => 1 LU per product an resp. TU: OK
* invoice candidates for the products customer return can be invoiced, are shown under "Kundenwarenrückgabe" with inout no., date, correct qty CU and price in invoice Jasper: OK

already reported  problems (see task chat):
* do not check the IsManualPackingMaterial checkbox, it is trying to create LU line which is not yet implemented
* do not add lines with no M_HU_PI_Item_Product, the virtual PI part is not covered
* qtyCU the user inserts is pretty much ignored in the HU creation, the LUTU config will be the expected one, based on the qtyEnteredTU and the Handling Unit Element Lager will have the max qty that fits into those TUs

new problems / questions:
* customer return HU Assignment only shows the LU, no TU, OK??
* TU created for return is shown with M_HU_PI_Item: "Virtual PI" in M_HU, only M_HU_Item shows the M_HU_PI_Item like e.g. G1: is that bc of the aggregation of HUs?
* products to choose from for the inoutline in customer return: all available products can be selected, no matter if they were on customer pricelist or not: NOK imho
* if the product chosen was not on the customer pricelist, then the IC created for this return has an error bc of that: NOK
* pressing "Create Credit Memo" button in return creates an invoice, but it is a normal sales invoice, not a credit memo: will that button be used? if yes, this needs to be fixed

**Comment by metas-ts** [comment]
accidental close-by-intrgarting a commit that had "fix" in it

**Comment by metas-lc** [comment]
* Part 1: manual return

1. create customer return manually
- go to Kunden Rücklieferung and create a new one: Kundenwarenrückgabe

- add all mandatory fields

- add a new line, for a product e.g. P0001

- set a package and a qty TU
	=> qty is not updated. OK???
	
- set a qty, complete
	=> it needs distribution network from your WH to an isHUDestroyed WH . OK???
	=> should i get lines for TU and LU when i complete? I Don't.  OK???
	=> 2 new HUs are created: LU and TU, both Active OK
	=> movement for the HUs created: from Gebinde warehouse to warehouse selected in return OK
	=> HU Assignment in the customer return, only for the LU. Should it also create one for the TU? OK???
	
- go to zoom in and select invoice candidates:	
	=> invoice candidate created for the product in customer return, with neg. qty (correct qty CU) OK
	=> should i also get ICs for HUs? I don't. OK???
	
- create invoice	
	=> invoice created for the product, doctype Ausgangsrechnung, qty with minus OK
	=> should i also get HUs in my invoice? I don't. OK???
	=> VK price is with minus, same as the qty so the total is with plus. OK???

- print jasper for your invoice 
	=> product is shown under "Kundenwarenrückgabe" with inout no., date, correct qty CU and price
	
2. repeat the same testcase for multiple products (let's say 3 LUs, with 2, 10 and 1 TUs)
	=> works the same. 
	=> You get 3 LUs, 3 assignments and total of 6 HUs (the TUs are aggregated) OK
	=> 1 invoice created with all 3 products OK

* Part 2: return from shipment

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-ts** [comment]
CPed the latest into the `release` branch: https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/167/

**Comment by metas-lc** [comment]
Part 1: manual return
swing and webui:

1. create customer return manually
2. go to Kunden Rücklieferung and create a new one: Kundenwarenrückgabe
3. add all mandatory fields
4. add a new line, for a product e.g. P0001
5. set uom, a package and a qty TU
=> qty is updated. OK
6. change qty => qty TU is updated. Change qty TU => qty is updated OK
7. complete
=> no distribution needed OK
=> got lines for TU and LU OK
=> 2 new HUs are created: LU and TU, both Active OK
=> movement for the HUs created: from warehouse set in my docu, to quality returns wh OK
=> HU Assignment in the customer return created OK (Followup created: https://github.com/metasfresh/metasfresh/issues/1761)
=> jasper printed fine OK
8. go to zoom in and select invoice candidates:	
=> ICs for product + HUs OK
9. create invoice	
=> sales invoice candidate created, doctype credit memo, with neg. qty (correct qty CU), negative price, positive total price OK
=> qtys and hu qtys correctly set OK
10. print jasper for your invoice 
=> product is shown under "Kundenwarenrückgabe" with inout no., date, correct qty CU and price
	
11. repeat the same testcase for multiple products (let's say 3 LUs, with 2, 10 and 1 TUs)
=> works the same OK
=> 1 invoice created with all 3 products OK

* Part 2: return from shipment 
swing and webui

**Comment by metas-lc** [comment]
IT
- retested manually vendor return => works fine, as above OK
- retested shipment (swing)
select all HUs and press on return from customer => you get a notification that the vendor return is created
open vendor return => doctype Kundenwarenrückgabe, product and TUs are set correctly.
run jasper preview => works fine, TUs are set, qtys are ok
=> one issue: when you use split before/ after receipt you don't get all the HUs. Follow-up: https://github.com/metasfresh/metasfresh/issues/1496
