### ISSUE TITLE
Only show Partner Name fields needed for case company

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1307]
### Is this a bug or feature request?
feature 

### What is the current behavior?
if company is set in partner window both company name and name fields are shown although only company name is needed

#### Which are the steps to reproduce?
1. open business partner window
2. create new partner
3. NOK: both fields are displayed

### What is the expected or desired behavior?
only show the name field applicable for the case

**Case Company**
![image](https://cloud.githubusercontent.com/assets/16079655/24899838/10daa7a0-1ea2-11e7-99d0-2c9c87034237.png)

**Case Person**
![image](https://cloud.githubusercontent.com/assets/16079655/24899861/2293cf4e-1ea2-11e7-8c1a-0999f3046f4f.png)

**Comment by metas-mk** [comment]
Tested. 
Create a new Businesspartner. isCompany is selected. Record is not saved because "Name" Field is not updated. NOK

**Comment by teosarca** [comment]
Suggestion to fix/improve UX:
* if IsCompany=Y, and if user changes the CompanyName there shall be a callout which is updating the Name (from CompanyName).
* if IsCompany=N, it shall work like now

**Comment by metasnw** [comment]
@teosarca yep. Agree.

**Comment by teosarca** [comment]
note to IT: pls do regression on swing UI too

**Comment by teosarca** [comment]
(available for testing on w101)

**Comment by metas-lc** [comment]
IT
1. go to bpartner window
2. create a new one
=> company is set on Y
=> company name is shown OK
=> name is also shown OK? shouldn't only company name be shown?
3. set the company name 
=> the name is also set OK

**Comment by metasnw** [comment]
@teosarca one thing from the original scope was that only either companyname or name should be displayed.
is that a big thing to achieve to hide partner.name when iscompany = Y and show it when iscompany = N ?
That behaviour should be that same both in webui and java client

**Comment by teosarca** [comment]
imho not.... mainly i didn't because i didn't want to break UX for current users.
but yes, let me do it now :)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT (w101)
1. go to bpartner window
2. create a new one
=> company is set on Y
=> company name is shown OK
=> name is hidden OK
3. set the company name 
=> the bpartner is saved OK
4. set company on N
=> company name is hidden OK
=> name appears and it's already set with the company name. You can change it OK
