### ISSUE TITLE
lazy-assigned Hostkey is not shown in swing-client's settings

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1314]
### Is this a bug or feature request?
bug
### What is the current behavior?

![image](https://cloud.githubusercontent.com/assets/1264789/24943524/5396426a-1f57-11e7-9c8a-1acd0ab37ade.png)

Note that at this time the hostkey was already assinged an could be selected via
```sql
select hostkey from ad_session where ad_session_ID=<session_id-from-the-screenshot>;
```

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. download the app to your computer and open it
2. in sysconfig make sure that printing is enabled
3. go to Extras -> Settings -> Context
=> #AD_Session.HostKey is set OK
