### ISSUE TITLE
2D Barcode wit ad_table_id/ record_id on bestellkontrolle

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1315]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Barcode on Bestellkontrolle Reports.
### What is the expected or desired behavior?
The idea is to print a Barcode in each line of Bestellkontrolle report. This Barcode shall be used in Manufacturing to scan the code and the automatically select the corresponding manufacturing order for that line.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/601 and

**Comment by metas-ts** [comment]
integrated into master together with the #523 - WIP

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing & WebUI

* Barcode in each line of Bestellkontrolle report: normal Bestellkontrolle Jasper: OK
* Barcode in each line of Bestellkontrolle report: normal Bestellkontrolle PDF WebUI: OK
* Barcode in each line of Bestellkontrolle report: Bestellkontrolle zum Kunden Drucken: OK
* Barcode in each line of Bestellkontrolle report: Bestellkontrolle für Lager Drucken: OK

* 1 cut-off in Header for Gebinde part:  => giving back to lc for fixing

* Header for Gebinde (header only) at the end of 1st page, and also displayed once more at beginning of 2nd page: creating task, possibility to check if the whole part fits on the rest of the page or not: to research for lc: https://github.com/metasfresh/metasfresh/issues/1434

**Comment by metas-dh** [comment]
Results of IT2
tested on Swing & WebUI

* no more cut-off in Header for Gebinde part (normal Bestellkontrolle only):  OK

**Comment by teosarca** [comment]
NOTE to IT: before testing it again, pls check https://github.com/metasfresh/metasfresh/issues/1460#issuecomment-299464643
