### ISSUE TITLE
AD_ChangeLog: don't log Updated and UpdatedBy

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1317]
### Is this a bug or feature request?
Enhancement
### What is the current behavior?

Currently if you enable changelog, then by defaul you also log changed to the `Updated` and `UpdatedBy`

Now, on an "active" DB we found roughly 300M AD_ChangeLog records (written within roughly 6 months) and roughly one third of them is just about those two columns.

So there is a lot of space to be saved here :-)

SQL to disable logging for existing columns:
```sql
UPDATE AD_Column SET IsAllowLogging='N' WHERE ColumnName IN ('Updated', 'UpdatedBy');
```

SQL to delete existing records:
```sql
delete from ad_changelog where AD_Column_ID IN (select AD_Column_ID from AD_Column where ColumnName IN ('Updated', 'UpdatedBy'))
```

SQL (migration script) to deactivate AD_ChangeLog for M_HU_TrxLine (also worth some 40'000'000 records or that particular DB):
```sql
--
-- Deactivate AD_ChangeLog for M_HU_TrxLine
--
UPDATE AD_Table SET IsChangeLog='N',Updated=TO_TIMESTAMP('2017-04-12 10:07:33','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Table_ID=540515
;
UPDATE AD_Table SET Help='I deactivated AD_ChangeLog for this table, because the lines are created once and then remain static and won''t be changed', IsDeleteable='N',Updated=TO_TIMESTAMP('2017-04-12 10:08:50','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Table_ID=540515
;
UPDATE AD_Tab SET IsReadOnly='Y',Updated=TO_TIMESTAMP('2017-04-12 10:09:13','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Tab_ID=540515
;
```

### TODO

* put the SQL to disable logging for existing records into a migration script (might want to rather run the delete-SQL manually on selected machines)
* implement that new `Updated` and `UpdatedBy` columns are created with `IsallowLogging = 'N'? 
* add something to the two columns AD_Element records' Help, so that people know it doesn't make sense to set that flag (as far as we see it today ;-) )

**Comment by metas-ts** [comment]
Also put the following, for C_Order columns that are just for intormation and also pollite changelog a lot (i.e > 1.3M records in that DB):

```sql
DELETE FROM AD_ChangeLog l
WHERE l.AD_Table_ID=get_table_ID('C_Order') 
	AND l.AD_Column_ID IN (505001, --;"Qty_FastInput"
		550220, --;"Qty_FastInput_TU"
		552712, --;"QtyInvoiced"
		552713, --;"QtyMoved"
		552714 --;"QtyOrdered"
); 

UPDATE AD_Column 
SET Updated=now(), UpdatedBy=99, IsAllowLogging='N' 
WHERE AD_Table_ID=get_table_ID('C_Order') 
	AND AD_Column_ID IN (505001, --;"Qty_FastInput"
		550220, --;"Qty_FastInput_TU"
		552712, --;"QtyInvoiced"
		552713, --;"QtyMoved"
		552714 --;"QtyOrdered"
);
```

**Comment by cristinamghita** [comment]
**Dev Test**
* create a new table - use the template for table
* column Updated and UpdatedBy were created with IsAllowLogging='N'  **OK**
* modify flag to Y and save, The change was allowed. **OK**

**Comment by metas-lc** [comment]
IT
repeated the devtest above. Works fine OK
