### ISSUE TITLE
Exception when creating translation entries for new System Language

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1318]
### Is this a bug or feature request?
bug

### What is the current behavior?
Adding missing translations is failing

#### Which are the steps to reproduce?
1. go System in Java client
2. make  nl_NL active and Systemlanguage
3. run process "manage translation records"
4. pick option "add missing translation records"
5. NOK: Exception https://pastebin.com/8w5jvXUQ

![image](https://cloud.githubusercontent.com/assets/16079655/24963628/65eb3dd8-1f9f-11e7-9391-f7fdaab34b82.png)

**Comment by metasnw** [comment]
extend column ad_process_trl.description to text and size 2000 chars and it ran fine

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing, mf15

* repeated testcase from description, could not reproduce, process ran without problems or errors: OK
