### ISSUE TITLE
Translation for nl_NL in WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1320]
### Is this a bug or feature request?
feature

**Comment by metasnw** [comment]
```
--select * from ad_tab where name ilike '%auftrag%'


select w.ad_window_id, t.ad_tab_id,f.ad_field_id, w.name as window, t.name as tab,   f.name  as "name (de_DE)", ftrl.name  as "name (en_US)", '' as "name (nl_NL)" from ad_field f
join ad_tab t on t.ad_tab_id = f.ad_tab_id 
join ad_field_trl ftrl on f.ad_field_id = ftrl.ad_field_id
join ad_window w on w.ad_window_id = t.ad_window_id 
where true
and
	(f.ad_tab_id in (187, 186) or w.name in ('Geschäftspartner'))
and isdisplayed = 'Y'
and t.isactive = 'Y'
and ad_language = 'en_US'
and f.displaylogic is NULL
order by w.name, t.seqno,f.ad_field_id
```

**Comment by Arjanvb** [comment]
Translated
[metasfresh Translation en_US nl_NL.xlsx](https://github.com/metasfresh/metasfresh/files/921601/metasfresh.Translation.en_US.nl_NL.xlsx)

**Comment by Arjanvb** [comment]
New file added and also translated
[Metasfresh Translation en_US nl_NL Part 2.xlsx](https://github.com/metasfresh/metasfresh/files/967425/Metasfresh.Translation.en_US.nl_NL.Part.2.xlsx)

**Comment by metas-mk** [comment]
Quickly checked the Sales Order window for the Dutch Translation in WebUI.
![image](https://cloud.githubusercontent.com/assets/13365687/26367460/f4fb3b30-3fee-11e7-8435-5debdf4e6419.png)
Same for Business Partner Window.
![image](https://cloud.githubusercontent.com/assets/13365687/26367498/115034d4-3fef-11e7-8799-7c3d620ac5fa.png)

Nice. Requirements for this issue fulfilled. Further work will be done in other Tasks.
