### ISSUE TITLE
Create Request in BPartner Window WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1323]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, you cannot create a request from BusinessPartner window in WebUI
### What is the expected or desired behavior?
Enable the possibility to create a Request from BUsinessPartner Window (or same as in Swing, from all windows).

**Comment by metasnw** [comment]
linked with https://github.com/metasfresh/metasfresh-webui-api/issues/300

**Comment by metas-mk** [comment]
Don't need this task. Working further on https://github.com/metasfresh/metasfresh-webui-api/issues/300
