### ISSUE TITLE
Do not display Destroyed HUs in Korrektur panel

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1327]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Destroyed HUs appear in the Korrektur Panel
#### Which are the steps to reproduce?
* GO to Wareneingang pos,, create a receipt, then destroy the HUs
* Open Korrektur => NOK: THe destroyed HUs are still displayed
### What is the expected or desired behavior?
* The hus that are destroyed shall not be displayed in Korrektur any more.

**Comment by metas-rc** [comment]
Tests fixed.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
- i'll postpone the IT because i cannot move the HU to garbage. i get
* Nicht gefunden * Belegart - Document BaseType : Physischer Warenbestand (Doc Sub Type: MD, Mandant: 1000000, Sektion: 1000000)

**Comment by metas-lc** [comment]
IT
webui
1. go to receipt candidates and select one. Use the green action button to receive HUs. Remember the HU value, create receipt
2. select the line and select Korrektur
3. select your HU and dispose
=> hu disappeared OK
4. close Korrektur and open again
=> hu is still not there OK

swing
1. go to receipt pos, select a line and open hu editor with new HUs
2. create receipt and remember the HU value
3. select the line again and select Korrektur
4. select your HU and dispose
=> hu disappeared OK
5. close Korrektur and open again
=> hu is still not there OK
(also checked HU POS => the HUs are not there OK)
