### ISSUE TITLE
Display created/ createdby in BusinessPartner contracts window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1334]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, one cannot see who created the BusinessPartner contracts.
### What is the expected or desired behavior?
To be able to better distinguish between manually created contracts and automatically prolonged contracts, it is needed to display the createdby field in BusinessPartner contracts window.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. go to contract window, select one and open doc view
=> contrat line => created and created by are there
