### ISSUE TITLE
Forecast Window as Document

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1339]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently the Forecast records can be processed, but Forecast cannot be drafted, prepared, completed, voided, reactivated.
#### Which are the steps to reproduce?
Check the Forecast window and processing workflow.
### What is the expected or desired behavior?
Change Forecast, so that it is a real document with ~~~doctype~~~, docactions and docstatus.

**Comment by teosarca** [comment]
Please consider implementing https://github.com/metasfresh/metasfresh/issues/2432 first and then use that process to transform Forecast to a document.

**Comment by teosarca** [comment]
@metas-mk  why do we need docType?

**Comment by metas-rc** [comment]
Results of IT

The Forecast is now a document, with document specific columns, workflow and actions.
I created a followup for updating the webui design for this window: https://github.com/metasfresh/metasfresh/issues/2660

I also creating a followup for some detail problems I noticed in actions of this new document: https://github.com/metasfresh/metasfresh/issues/2661
