### ISSUE TITLE
Cannot "LU zuteilen" (Swing HU Editor)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1346]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* receive 1 LU from manufacturing order (make sure the manufacturing order has no C_BPartner_ID set!)
* split 2 TUs out
* select both TUs and press "LU zuteilen" 
* get some error about "bpartner is null" => NOK

### What is the expected or desired behavior?
Allow running "LU zuteilen" even if the HUs which we aggregate does not have an C_BPartner_ID set.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* repeated testcase from above: no error about bpartner being null: OK
