### ISSUE TITLE
M_ShipmentSchedule_EnqueueSelection ignores role's org access

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1348]
### Is this a bug or feature request?
Bug

Suggestion: add the role access in processInfo.getQueryFilter

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* Create several sales orders, for different orgs I & II, as Admin (select Org I when logging in)
* Log in in another session, with a different role, that has access to only Org II (Handel or Spedition)
* Search for the M_ShipmentSchedule created for the day of test: only the ones for Org II are displayed, OK
* Gear, Auswahl liefern: shipments for the M_ShipmentSchedules of the resp. org only are created, OK
* Check in the Admin session: the M_ShipmentSchedules for the sales order of Org I are not changed, can still be shipped: OK
* Log in in another session, with a different role, that has access to only Org I (Handel or Spedition)
* Search for the M_ShipmentSchedule created for the day of test: only the ones for  Org I are displayed, OK
* Gear, Auswahl liefern: shipments for the M_ShipmentSchedules of the resp. org only are created, OK
* Check in the Admin session:  all M_ShipmentSchedules are shipped: OK
* Delete the first shipment for Org II, and ship them as Admin (logged in with Org I): working fine, OK
