### ISSUE TITLE
Problem with C_Order filtering in M_ShipmentSchedule

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1353]
### Is this a bug or feature request?
Bug

### What is the current behavior?

It seems as if in the swing client the auto-completion/field lookup can be confused by identical sale order line document numbers among different orgs
 
Hint: It might be related to overlapping sales order document number sequences between two orgs

#### Which are the steps to reproduce?

* Log in with a role whose access is restricted to one particular org.
* Open the shipment schedule window and start entering a particular sales order document number
  * aparently it's important for the bug to show up that there has to be an existing sales order with the same document number in a different org

* Note that instead of filling in the sales order, the extended swing sales order search dialog opens. 

### What is the expected or desired behavior?

when entering a sales order number, the system should directly the numbers that are visible to the current role.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_tests_collection/Testcase_%231353.md: OK
