### ISSUE TITLE
Allow Business Partner group without setting price system

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1355]
### Is this a bug or feature request?
feature 

### What is the current behavior?
when you create a new bp group you have to enter sales and purchase price system

#### Which are the steps to reproduce?
1. open window Business Partner group
2. create new record

### What is the expected or desired behavior?
Price System should not be mandatory

**Comment by metas-ts** [comment]
Sorry @metas-lc , I hadn't "fully" integrated this one. Now done. Pulled the task back to "rollout"

**Comment by metas-lc** [comment]
IT
1. open window Business Partner group
2. create new record
=> both price systems are not mandatory OK
