### ISSUE TITLE
Drop de.metas.order.callout.CheckDouble

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1358]
reason: not used

**Comment by teosarca** [comment]
note to IT: pls do regression on Sales/Purchase order windows.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* regression testing in sales order & purchase order window: all OK
=> will keep this task until after next e2e, to make sure nothing pops up then

**Comment by metas-dh** [comment]
weekly e2e was fine, concerning orders: OK
