### ISSUE TITLE
Translating processes and windows for order to shipment process to en_US

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1360]
### Is this a bug or feature request?
feature

**Comment by teosarca** [comment]
(available on w101)

**Comment by metas-lc** [comment]
translated:
- purchase order window
- sales order window
- generate shipments process (and parameters)
- Material Receipt Candidates
- Material Receipt
- Create Material Receipt process (button)
- generate invoices process name
OK

partially translated: 
- Shipment Candiates (+ line)
- Shipment (+line)
- Billing Candidates (+ line)
- generate invoices process parameters
OK? shall these also be translated?

**Comment by metasnw** [comment]
@metas-lc Scope was to translate visible parts to en_US not all fields.
We can make another issue with your list  to add missing translations for the sales process

**Comment by metas-lc** [comment]
thank you. moving the task to done
