### ISSUE TITLE
Activate auto numbering for incoming and outgoing payments

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1362]
### Is this a bug or feature request?
bug

### What is the current behavior?
payment document No's are not automatically numbered in web UI

**Comment by metasnw** [comment]
CAUTION: this one is not an easy as it changes existing client doctype payment. We need to see what will be the impact on existing systems. May be we find a way to only apply to new systems?

**Comment by metasnw** [comment]
@metas-ts
Were you able to create the dynamic script?

**Comment by metas-ts** [comment]
@metasnw yes, it's here: https://github.com/metasfresh/metasfresh/issues/1362#ref-commit-0a9fb08 and integrated together with your changes

**Comment by metas-rc** [comment]
Results of IT

* Tested on webui


* I manually created paymenst 9 incoming and outgoing)  and their document numbers were filled correctly, increasing with 1, different sequences for each payment doctype.

**Comment by metas-rc** [comment]
The document number being readonly will be dealt with in https://github.com/metasfresh/metasfresh/issues/1860
