### ISSUE TITLE
Translate request type to de_DE Vorgang Art

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1369]
### Is this a bug or feature request?
feature

**Comment by metas-lc** [comment]
IT
in menu is called Aufgaben Typ
in window is Vorgang - Art
the fields are all translated

**Comment by metas-mk** [comment]
@metas-lc I believe this was solved with menu migration last week
here the current menu entries in english

![image](https://cloud.githubusercontent.com/assets/13365687/26043917/39cf72bc-3941-11e7-865f-49648d634f6d.png)

**Comment by metas-lc** [comment]
IT
in de_DE it's still Aufgaben Typ . Shall be Vorgang - Art

**Comment by metas-mk** [comment]
Please move to Done. Will adjust the menu entry name in next Menu migration issue.
