### ISSUE TITLE
Make request type names translatable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1370]
### Is this a bug or feature request?
feature

### What is the current behavior?
request type names are not translatable 

### What is the expected or desired behavior?
1. open request window
2. translated request names are displayed in the list according to the language I am logged in with

### concept
1. _trl table needs to be created
2. transations for request types need to be added
3. make drop down list show the translations

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing, mf15

* logged in with language EN-US, opened request window: request type names all translated to EN-US: OK
* translations for request types: shown where existing (german where translation missing): OK
