### ISSUE TITLE
HU Editor (POS) weight change not propagated to HU_Storage

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1372]
### Is this a bug or feature request?
Bug

### What is the current behavior?

If you have an existing HU and open it in the "Handling Unit (POS)" Editor, 
you can change an safe the HU's weight attributes, but thatchange is not propagated into HU-Storage

### What is the expected or desired behavior?

When the weight attribute is changes, that change shall be propagated into HU-storage.

### Note
If it turns out that this is not a simple omission from our side, but that there are some deeper reasons/problems why we didn't implement it so far, please ping @metas-mk

**Comment by metas-ts** [comment]
* I guess we needs create HU-transactions, right?
* Also need to make sure that those are recorded in HU-tracing (with type: TRANSFORM_LOAD)..that might already happen right now, but nwe need to make sure

**Comment by teosarca** [comment]
As discussed with @metas-mk  and @metas-ts  ... shall be solved by https://github.com/metasfresh/metasfresh/issues/2647.

Changing the HU's weight without any document behind does not make sense.
