### ISSUE TITLE
Make Packing Item editable in Manufacturing Order Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1382]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Currently, it is not possible to edit the packing instruction to Manufacturing Order Header.
#### Which are the steps to reproduce?
Create a Manufacturing Order and try.
### What is the expected or desired behavior?
Make the Fields for Packing Instructions editable.

**Comment by metas-lc** [comment]
IT
packing instruction config field is editable
