### ISSUE TITLE
HU from Cost Collector is locked and cannot be selected anymore after the CC was reversed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1388]
### Is this a bug or feature request?
Bug
### What is the current behavior?
After reversing the Cost Collector of a PP_Order, the HU in that CC is locked and cannot be selected anymore in production, issue.
#### Which are the steps to reproduce?
* Create a PP_Order
* In Produktion, issue 1 or more HUs for that order
* Open Cost Collector of the PP_Order and reverse it
* Try issuing the same HU from the CC once more: HU is displayed in the HU Editor again, but is grey and locked so you cannot select it 
### What is the expected or desired behavior?
HUs from reversed Cost Collectors should be selectable for issueing again after reversing the CC.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* HU from Cost Collector is not locked and can be selected again after the CC was reversed: OK
* the same HU can be used in issueing >2 times (issue - reverse - issue - reverse - issue): OK
