### ISSUE TITLE
Make eMail adress fields longer

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1389]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
currently, the Fields for eMail adresses in mail editor are not big enough to add a few receipients.
#### Which are the steps to reproduce?
Try to add 5 receipients.
### What is the expected or desired behavior?
Make the email receipient and cc fields bigger.

**Comment by metas-lc** [comment]
IT
1. go to bpartner window and select one. Go to user subtab and add multiple emails (i added about 10, and used 200 characters in total)
2. go to sales order and create a new one for this bpartner
3. select the email icon and email again
=> all the emails i set on step 1 are there OK
