### ISSUE TITLE
Check for java8 in the rollout-scripts

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#139]
* related to FRESH-339
* Pls extend sql_remote.sh and minor_remote.sh to check if we have hava-8 (both, because also no rollout SQL should be done unless the server will be able to run). If there is no java-8, please exit and provide a link to the update documentation.
* if JAVA_HOME is set, afair, then that'S the java-version to check, even if that version is not in the path (but pls verify)
* i recommend to add the check to tools.sh
* i reccomend to also update that diag-script which we have

**Comment by metas-jb** [comment]
Closing after successful tests
