### ISSUE TITLE
Check for existing unique HU when completing the manufacturing order

### ISSUE THREAD

**Issue by riadmen** [metasfresh/metasfresh#13949]
### Is this a bug or feature request?
BUG
### What is the current behavior?

If we create a manufacturing order with a unique attribute (e.g: `SeqNo`) with a  value that it's already set in existing handling unit, when trying to receive for this order, receiving does not work because the `Serial No`. is already set: 

![MO](https://user-images.githubusercontent.com/93593841/201686007-17d08429-dfa5-4649-a115-3c445351f19d.gif)

### What is the expected or desired behavior?
The check for existing HU with the same value of a unique attribute should be done when completing the manufacturing order

**Comment by teosarca** [comment]
@riadmen  consider closing this PR. I think the feature was already delivered by
* https://github.com/metasfresh/metasfresh/pull/13972
