### ISSUE TITLE
cannot connect to db with swing client using ip address

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#1397]
scenario: the mf-server works on 192.168.x.50
and I have no entry in my etc\hosts `192.168.x.50	test01`
so
`ping 192.168.x.50` works,
and `ping test01` does not

### Is this a bug or feature request?

for me it is a bug (in swing client)

### What is the current behavior?

I cannot start the swing client,
* Teste Verbindung zur Application is OK
but
* Teste Verbindung zur Datenbank is NOT OK

Hint:
The client recieves the server name from the server (it is `test01`) and this cannot be resolved by the system. In former AD the field Datenbank-Server on the client-login panel was not read only as is in mf.
So `test01` could be change to `192.168.x.50`

#### Which are the steps to reproduce?

see above

### What is the expected or desired behavior?

Because I can connect with web-UI via IP, exmpl via https://192.168x.50/login
I expect to connect to mf in the same way without changing my etc\hosts

**Comment by metasnw** [comment]
@homebeaver 
The Java Client as far as I know was never working with IP address as hostname and as we are replacing it by the webUI we will not work on that.
Feel free to change that behaviour by yourself and issue a pull request if you think its worth the effort.

**Comment by homebeaver** [comment]
not worth the effort if there is no need for other clients (my first intention). 
Because this happens only on the mi67-testsystem and a workaround is installed for the tester:

_auf dem Rechner ... habe ich mf so eingerichtet, dass der Client gestartet werden kann._

there was a second intention for this issue:
* to have an example for a good issuetext :wink:

_Was ist eine "gute" Problembeschreibungen?
 ein kurzer Titel und 2 Apekte beschreiben
 was ist das von mir erwartete Verhalten
 was ist das tatsächliche verhalten_
