### ISSUE TITLE
Take out "New" in C_DocTypeTarget_ID in PP_Order

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1398]
### Is this a bug or feature request?
Bug, i think
### What is the current behavior?
When creating a new PP_Order, the C_DocTypeTarget_ID field displays ** Neu ** or ** New **. Since the field is set, it is not marked as a mandatory field, so if the user does not select a C_DocTypeTarget_ID, and tries to complete the order, an error is displayed bc the document cannot be cmpleted (both in Swing and in WebUI).
#### Which are the steps to reproduce?
* Create a new PP_Order: C_DocTypeTarget_ID field displays ** Neu ** or ** New **
* fill all mandatory fields, try to complete: error
### What is the expected or desired behavior?
C_DocTypeTarget_ID in PP_Order should be empty in a new document, so it is marked as mandatory.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 & Swing

* C_DocTypeTarget_ID in new manufacturing order: set with "Produktionsauftrag" instead of "New": OK
* other C_DocTypeTarget_IDs can be selected, e.g. Waschprobe: OK
