### ISSUE TITLE
DocumentNo not generated for PP_Orders in WebUI

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1399]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The DocumentNo is not generated for PP_Orders in WebUI.
#### Which are the steps to reproduce?
Try creating one.
### What is the expected or desired behavior?
Create DocumentNo automatically in WebUI for PP_Orders.

**Comment by teosarca** [comment]
Document type is not documentNo controlled (see https://w101.metasfresh.com:8443/window/135/1000037 ).

Wondering if we shall apply the change only to template database?

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 & mf15 WebUI

* DocumentNo generated for PP_Orders in WebUI: DocumentNo  generated when  creating a new PP_Order in WebUI: OK
