### ISSUE TITLE
DocumentNo not generated for empties in WebUI

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1400]
### Is this a bug or feature request?
bug
### What is the current behavior?
document no is not generated for empties receive (Leergut Rücknahme) when they are manually created
#### Which are the steps to reproduce?
1. go to Leergut Rücknahme, create a new one
2. set all mandatory fields
=> the document no is not generated NOK
### What is the expected or desired behavior?
document no shall generate automatically

**Comment by teosarca** [comment]
have u checked if the doctype is documentNo controlled?

**Comment by metas-lc** [comment]
IT
1. go to Leergut Rücknahme, create a new one
2. set all mandatory fields
 => the document no is generated OK
