### ISSUE TITLE
Translate Process "New Request" to de_DE

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1401]
### Is this a bug or feature request?
feature

#### Which are the steps to reproduce?
0. have language de_DE
1. open window business partner
2. actions => "create request"
3. NOK: should be german

**Comment by metas-lc** [comment]
on settings pick different languaged, like en and de.
Go to Business Partner and open actions
en US: Create request
de DE: Neuen Vorgang anlegen
OK
