### ISSUE TITLE
technical: refactor TaxNotFoundException

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1403]
refactor TaxNotFoundException and introduce a builder for it because there are way too many parameters.

Note to IT:
* just do regression tests

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing (regression testing)

manual orders:
* Tax_Not_Found in ICs: for packing item prices set inactive or deleted from pricelist after order was completed: OK
* product prices set inactive or deleted from pricelist after order was completed: tax still taken from order, not set to Tax_Not_Found after inout: OK
* deleting ICs with Tax_Not_Found, setting the price active / adding it to pricelist, and refresh ICs: IC is created again, with correct tax: OK
* price set inactive before creating order: product: can't be selected for orderline: OK / PI: order cannot be completed bc price is not found in pricelist: OK
* price set inactive while creating order (product):  order cannot be completed bc price is not found in pricelist: OK

OLCands:
* for prices set inactive or deleted from pricelist before import / before Freigabe: OLCand is marked with error, info about missing price, Freigabe not working: OK
* if price for packing item is set inactive or deleted from pricelist before import / before Freigabe: all products that have this pi set in their OLCand are marked with error, info about missing price for pi, Freigabe not working: OK
* for prices set inactive or deleted from pricelist after import & Freigabe: works like for manual order, see above: OK

* no price & tax for product / packing item has no influence on inout: OK

@teosarca: afair, the tax for products is taken from the orderline;
 so if if i set the product price inactive after the order is completed, and the IC is updated after inout, the tax is still taken from orderline, and therefore the IC does not have Tax_Not_Found
BUT: if i delete the IC after the inout, and it is recreated, the tax is again set as in orderline, no Tax_Not_Found bc of the inactive in pricelist, is that OK?
