### ISSUE TITLE
Possible 1:1 switch for Data Lifecycle Management users

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1411]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Currently, it is possible to switch Data Lifecycle Management on, but only for all users.
#### Which are the steps to reproduce?
Switch on and check,
### What is the expected or desired behavior?
Allow to switch Data Lifecycle Management on, initially, all users are switched off, those users that want to use shall switch on individually 1 by 1.

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_tests_collection/Testcase_%231411.md: OK
