### ISSUE TITLE
Window for c_activity in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1417]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for c_activity in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain the c_activity in WebUI. Add the new window in webui menu in finance/settings.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101, mf15 WebUI

* window for c_activity in WebUI: OK
* window in webui menu in finance/settings: OK

@metas-mk:
=> i could only see this window  when logged in with role: Admin and access to full menu, not role: WebUI, also not with the normal testuser we use in w101 ("it"): OK?

**Comment by metas-dh** [comment]
checked with mk: role access not fully defined and solved yet, so if window is existing, it's OK
