### ISSUE TITLE
Window for c_bank in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1418]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for c_bank in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain the c_bank in WebUI. Add the new window in WebUI menu in finance/settings.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* window for C_Bank in WebUI: OK
* window in WebUI menu in finance/settings: OK
