### ISSUE TITLE
Window for c_currency in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1419]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for c_currency in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain the c_currency in WebUI. Add the new window in WebUI menu in finance/settings.

**Comment by teosarca** [comment]
Note to IT: also test activating and deactivating a currency, e.g.
* browse https://w101.metasfresh.com:8443/window/115
* pick a deactivated currency and activate it
* hit Back => it shall be active
* click it again and deactivate it
* hit back => it shall be deactivated

**Comment by metas-lc** [comment]
IT
1. opened Wahrung directly, quicksearch, menu - OK opens fine, no errors
2. select a currency and activate it, press back
=> still active OK
3. select it again and make it inactive, press back
=> inactive OK
