### ISSUE TITLE
Fresh Migration of WebUI Menu for rel. 5.8

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1424]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The WebUI Menu is not the latest from Development.
#### Which are the steps to reproduce?
Compare release with Development Version.
### What is the expected or desired behavior?
Create a fresh migration Script for menu WebUI.

**Comment by metasnw** [comment]
5.8 does not seem to have latest menu

e.g. Initial Setup Wizard, Production, etc. is missing

**Comment by metas-ts** [comment]
* fix looks good in the release branch
* now also merged into master

**Comment by teosarca** [comment]
rolled out on w101 (even though there does not matter)

**Comment by metas-dh** [comment]
checked with ts: can be closed and moved to Done.
