### ISSUE TITLE
make price field bigger in sales invoice document 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1425]
### Is this a bug or feature request?
bug
### What is the current behavior?
price field is too small

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, Swing

sales invoice Jasper: 
* cut-off in "Einhei(t)": NOK
* line break for Betrag: .00 displayed underneath in next line: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested on mf15, Swing & WebUI

sales invoice Jasper:

* cut-off in "Einhei(t)": fixed, OK
* no more line break for Betrag: .00 taken out (was a requirement): OK
* price field bigger (fine with e.g. 200.000): OK
