### ISSUE TITLE
Window for Bank Account in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1429]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for Bank Account in WebUI. The Window for Master data Bank is already created and added to finance/settings menu.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain the Bank Accounts including accounting subtab in WebUI. Add the new window in WebUI menu in finance/settings.

**Comment by metas-lc** [comment]
IT
Finance/Bankkonto (window 540337) + Buchfuhrung subtab OK
Name field is mandatory but missing. NOK

**Comment by metas-mk** [comment]
Fixed. The Name field was marked as an identifier but was not mandatory. Adjusted that now and pulled the name field into the primary group in the main window.

**Comment by metas-lc** [comment]
IT
name is  the primary group in the main window and it's mandatory. Once set the document is saved and valid OK
