### ISSUE TITLE
Window for c_conversion_rate in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1430]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for c_conversion_rate in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain the c_conversion_rate in WebUI. Add the new window in WebUI menu in finance/settings.

**Comment by metas-lc** [comment]
IT
1. menu:  /Finance/Settings/Währungskurs (window 116) OK 
2. open a conversion rate, make it inactive, press back => still inactive OK
3. open a conversion rate, make it active, press back => still active OK
