### ISSUE TITLE
technical: HUReportService shall work with AD_Process_ID instead of I_AD_Process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1432]
Reasons:
* performance
* avoiding caching issues

Note to IT:
* full regression on HU related processes (print label etc), on Swing and Webui
* make sure the label is printed after HU receipt was created

**Comment by teosarca** [comment]
rolled out on w101

**Comment by metas-lc** [comment]
IT
swing: 
- labels are printed OK
- label is printed after receipt was created OK
- number of printed (not print preview) documents was as set in sysconfig OK
- drucken productanlieferung works fine OK
- (donno if related but jaspers from print preview, gear and menu work fine)

webui
- labels process starts but no preview generated (there is no printer config) OK
- drucken productanlieferung returns an error that there is no printer: java.awt.print.PrinterException: Not a 2D print service: IPP Printer : null PrintServiceName=null OK
- (donno if related: jaspers from print preview, gear and menu work fine)
