### ISSUE TITLE
Fix spring scanBasePackageClasses and introduce profiles

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1438]
### Is this a bug or feature request?
feature request

### What is the current behavior?
* each of our spring boot applications are configuring the scanBasePackageClasses in their own way because they try to avoid loading components from other projects (e.g. webui shall not load the server components, jasper server components etc)

### What is the expected or desired behavior?
* all our spring boot applications shall use the same scanBasePackageClasses={ "de.metas", "org.adempiere" }
* introduce "metasfresh-server", "metasfresh-jasper-server", "metasfresh-swingui" and "metasfresh-webui" profiles

**Comment by teosarca** [comment]
Note to IT:
* full regression needed, focus on jaspers, logo in jasper
* make sure /serverMonitor works

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 by lc: OK

tested on Swing:
* checked jaspers (order, inout, invoice, pricelist, pp_order etc.), all working fine: OK
* checked logo on jaspers: OK
* ServerMonitor still working: OK
