### ISSUE TITLE
ClassCastException: CompositeQueryFilter cannot be cast to SqlQueryFilter

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1440]
### Is this a bug or feature request?

Bug

### What is the current behavior?

This error happens when the process `SendPDFMailsForSelection` is run.
Acording to the code, it would also happen when `EDIExportDocOutboundLog` is run.

That is doesn't work anymore is a consequence of #1348

**Comment by metas-dh** [comment]
Results of IT1
tested on Swing

* sending Emails from C_Doc_Outbound: OK
* correct language of the email, acc. to language set for bpartner: OK
* only send data that was not sent before considered correctly: OK
* sending EDI (INVOIC) from C_Doc_Outbound: OK
* access to data in C_Doc_Outbound according to role & Org: OK
