### ISSUE TITLE
Window for C_Doc_Outbound_Config in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1442]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for C_Doc_Outbound_Config in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to maintain C_Doc_Outbound_Config in WebUI. Add the new window in WebUI menu in crm/settings.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* C_Doc_Outbound_Config window in WebUI: OK
* show in menu in CRM/Settings: OK
