### ISSUE TITLE
Window for  C_Doc_Outbound_Log in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1444]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for C_Doc_Outbound_Log in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a Window to filter and maintain C_Doc_Outbound_Log in WebUI. Add the new window in WebUI menu in crm/.

**Comment by metas-lc** [comment]
IT
window is there:
CRM/ Settings/ Ausgehende Belege Konfig OK
