### ISSUE TITLE
Add filter to currency conversion window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1446]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is not filtering criteria in currency conversion window.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
There shall be currency, currency to and ValidFrom as filtering criteria.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

filters in currency conversion window: 
* Filter Standard: includes currency and currency to criteria: OK
* additional Filter for ValidFrom: OK
* quick check: all filters work fine: OK
