### ISSUE TITLE
Too many prices on Pricelist comparison report

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1448]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Too many prices on Pricelist comparison report for 3 Product prices, Attribute prices and different Attributes. Result: 5 Price Comparisons., should be 3.
#### Which are the steps to reproduce?
Open the Pricelist comparison report and check.
### What is the expected or desired behavior?
Return the correct amount of comparison lines.

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 Swing

tested with 3 prices for the same product, in 2 different PLV, the prices have different ASI (=> country; additional Bio, AdR):

* product with the same ASI has same price in both versions: price is displayed in both columns, price new & old nothing bold: OK
* product with the same ASI has different prices in both versions: displayed in both columns, price new: bold: OK
*  product prices are empty / inactive in first PLV (= the one you set first in bpartner, Gear, pricelist comparison), but included in the second PLV: prices are not displayed at all: OK
* product prices are empty / inactive in second PLV, but included in the firstPLV:  prices are displayed only for 1st column price new: OK
* product prices have different ASI: if set in 1st PLV, the ASI are displayed with the price, and the 2nd column is empty: OK
* product prices have different ASI: if set in 2nd PLV, the ASI are not displayed with the price, and the 2nd column is empty: OK
