### ISSUE TITLE
Add scale Price Tab in Window Product Price

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1451]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the scale Price is missing in Product Price window of WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Scale Price Tab to product price window.

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* tab for Scale Price in Product Price window: OK
* tab includes qty and prices (standard price etc.): OK
* Scale Prices remain active even if Scale Price is not checked anymore: like in Swing, OK
