### ISSUE TITLE
Translation of Initial Setup Wizard Process Window and Menu entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1456]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Initial Setup Wizard is only available in language de_DE.
#### Which are the steps to reproduce?
Try other languages and check.
### What is the expected or desired behavior?
Have an en_US Translation for Initial Setup Wizard Process window and Menu.

**Comment by metas-lc** [comment]
IT
Initial Setup Wizard is translated: process and parameters OK
