### ISSUE TITLE
The Bestellkontrolle barcodes shall be generated and persisted in database

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1460]
### What is the current behavior?
the barcode is generated in jasper report.

### What is the expected or desired behavior?
Introduce C_Order_MFGWarehouse_ReportLine.Barcode and populate it.
The jasper report shall read the barcode from there.

Why?
* because we want to keep all the business logic in one place
* reporting's responsibility is not to generate data but present data

This is a follow-up of https://github.com/metasfresh/metasfresh/issues/1315

**Comment by teosarca** [comment]
@metas-lc  can u pls fix the report and always use C_Order_MFGWarehouse_ReportLine.Barcode.
Also pls drop that database function which generates the barcode because we don't need it.

**Comment by metas-lc** [comment]
left barcode only in C_Order_MFGWarehouse_Report (bestellkontrolle) print preview

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on sp Swing

* Barcodes still displayed in Bestellkontrolle (normal Bestellkontrolle only!): OK
