### ISSUE TITLE
Add Window for S_Resource_Ressource to WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1463]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is not Window for Manufacturing resources in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for S_Resource_Ressource and add to WebUI menu in manufacturing/settings

**Comment by metas-lc** [comment]
IT
window is here Manufacturing/Settings/Produktions Ressource
