### ISSUE TITLE
New Window for Manufacturing Workflow in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1464]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Manufacturing Workflow in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Manufacturing Workflow and add to WebUI menu in manufacturing/settings

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window Manufacturing Workflow (Produktion Arbeitsablauf): OK
* WebUI menu: anufacturing/settings: OK
