### ISSUE TITLE
New Window for Distribution Network in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1465]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Distribution Network in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Distribution Network and add to WebUI menu in manufacturing/settings

**Comment by metas-lc** [comment]
IT
window is there:
Manufacturing/Settings/Distributions Konfiguration
distribution line is included tab
