### ISSUE TITLE
New Window for Product Planning Data in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1467]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Produkt Planning Data in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Product Planning Data and add to WebUI menu in manufacturing/settings

**Comment by metas-lc** [comment]
IT
window is here:
Manufacturing/ Settings/ Produkt Plandaten
has 4 included tabs, you can add new data planning
