### ISSUE TITLE
New Window for Node Transitions in webUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1473]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Manufacturing Workflow Node Transitions in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Manufacturing Workflow Node Transitions and add to WebUI menu in manufacturing/settings

**Comment by metas-lc** [comment]
IT
window is here:
Manufacturing/ Settings/ Produktion Arbeitsablauf Übergang
all fields readonly
