### ISSUE TITLE
New Window for InvoiceSchedule in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1478]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is now Window for InvoiceSchedule in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window for InvoiceSchedule in WebUI and include the new Window in menu invoicing/settings.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window InvoiceSchedule (Terminplan Rechnung): OK
* menu:  invoicing/settings (Fakturierung / Einstellungen): OK
