### ISSUE TITLE
New Window Distribution Order in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1485]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Distribution Order in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Distribution Order and add to WebUI menu in manufacturing.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window for Distribution Order (Distributionsauftrag): OK
* in WebUI menu in manufacturing: it's actually included in Logistik, not manufacturing, is that OK?

**Comment by metas-dh** [comment]
checked with mk: OK in Logistik
