### ISSUE TITLE
Add Status Field to Material Disposition Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1486]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
The new column Status is missing as Field in material Disposition Window in WebUI.
#### Which are the steps to reproduce?
Open the Window and see.
### What is the expected or desired behavior?
Add the new Field "status" to Material Disposition window in WebUI. Check if also other columns have been created in the meanwhile and add them to Main View/ Advanced edit if makes sense.

**Comment by metas-lc** [comment]
IT
1. open Materialdisposition => status field is there
2. use advance edit => status field is there
