### ISSUE TITLE
Allow the editing of Workflow Node in Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1487]
### Is this a bug or feature request?
Allow the editing of Workflow Node in Window
### What is the current behavior?
Currently, the field workflow node is not editable in Window Workflow Node Transition.
#### Which are the steps to reproduce?
Open Window Workflow Node Transition and try.
### What is the expected or desired behavior?
Allow selecting existing Workflow Nodes and insert new Workflow Node Transition records.

**Comment by teosarca** [comment]
rolled out on w101

**Comment by metas-lc** [comment]
IT
1. Open Window Workflow Node Transition, select one which is not made in system
=> the workflow node field is editable OK
2. create a new one 
=> the workflow node field is editable OK
