### ISSUE TITLE
New window Order MFGWarehouse Report in WebUI

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1488]
### Is this a bug or feature request?
feature request
### What is the current behavior?
Currently, there is no Window for Bestellkontrolle in WebUI
### What is the expected or desired behavior?
Create a window for C_Order_MFGWarehouse_Report (Bestellkontrolle) and add to WebUI menu.

**Comment by metas-mk** [comment]
The window was already created via other issue and is included in WebUI menu. Closing/ Done.
