### ISSUE TITLE
Disable/delete legacy Cockpit window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1489]
### What is the current behavior?
Cockpit window appears in document references for almost all our primary documents.

#### Which are the steps to reproduce?
e.g. open a sales order, go to document references.

### What is the expected or desired behavior?
Cockpit window shall not be displayed there.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
