### ISSUE TITLE
Add HU_PI_Item to Product Price Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1494]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, The HU_PI_Item Field is not shown in WebUI.
#### Which are the steps to reproduce?
Open Product Price Window in WebUI.
### What is the expected or desired behavior?
Show the HU-PI-Tem in Product Price Window in WebUI.

**Comment by metas-lc** [comment]
IT
packvorschrift field is added in product price
