### ISSUE TITLE
Update to spring-boot 1.5.3

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1499]
### Is this a bug or feature request?

feature request

### What is the current behavior?

* We currently use spring-boot-1.4.2
* That version contains logback 1.1.7 which gives me this: https://github.com/pukkaone/logback-gelf/issues/13

I updated to 1.5.3 locally and that problem went away. Btw, I ran into the logback problem when i tried to create augmented log messages for the ELK stack (upcoming issue)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
checked with ts: can be closed and moved to Done.
