### ISSUE TITLE
Rename "No Handling Unit" and "Virtual PI" PIs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1501]
Rename as follows:
* "No Handling Unit" => "Template PI" (or similar)
* "Virtual PI" => "No PI" (or similar)

Reason: because that's how they are actually used ;)

**Comment by teosarca** [comment]
rolled out on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 and mf15 Swing

Swing:
Wareneingang POS, Gebindekonfig:
* former "No Handling Unit" (LU): now called "Packing Item Template": OK
* former "Virtual PI" (TU): now called "No Packing Item": OK
Purchase Order:
* "Virtual PI" (TU): still called "Virtual PI"??

WebUI:
material receipt schedule:
* former "No Handling Unit" (LU): both "No Packing Item" & "Packing Item Template" available?
* former "Virtual PI" (TU):  still called Virtual PI (also in purchase order

@teosarca: is this ok?
![2017-05-17 17_21_24-metasfresh](https://cloud.githubusercontent.com/assets/18696715/26161921/91987260-3b25-11e7-89eb-79a5ab8fd732.png)

**Comment by teosarca** [comment]
hmm, nop... we shall get rid of VirtualPI term

**Comment by metas-mk** [comment]
Fixed. Renamed the CUTU and other elements too.

**Comment by metas-lc** [comment]
IT
repeated testcase above:

Swing:
Wareneingang POS, Gebindekonfig:
* former "No Handling Unit" (LU): now called "Packing Item Template": OK
* former "Virtual PI" (TU): now called "No Packing Item": OK

Purchase Order:
* "Virtual PI" (TU): called "No Packing Item": OK

WebUI:
material receipt schedule:
* former "No Handling Unit" (LU): both "No Packing Item" & "Packing Item Template" OK
* former "Virtual PI" (TU):  "No Packing Item" OK

Purchase order:
