### ISSUE TITLE
Configure our services for logstash

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1504]
### Is this a bug or feature request?
Feature

### What is the current behavior?

Currently we log to files and to console

### What is the expected or desired behavior?

In addition we want to be able to send logs to logstash.
* the logstash hostname and port shall be configurable from the outside 
* despite there seem to be no problems if the logstash destination is not there, i would like to have a way to switch the whole log-to-logstash thing off via env variable or spring property

Reading:
* https://logback.qos.ch/manual/configuration.html#conditional
* https://blog.codecentric.de/2016/07/spring-boot-apache-cxf-logging-monitoring-logback-elasticsearch-logstash-kibana/
* https://layer4.fr/blog/2016/10/25/efficient-logging-spring-boot-logback-logstash/
* https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#_environment_properties

**Comment by metas-dh** [comment]
checked with ts: can be closed and moved to Done.
