### ISSUE TITLE
Add the possibility to track easily contracts that ended naturally

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#1506]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
You can't see easilly when a 3 month contract ended
### What is the expected or desired behavior?
Add in FT, the option for contract status called EndingContract.

**Comment by cristinamghita** [comment]
Test:
* end a contract
* all shall be as before

**Comment by metas-rc** [comment]
Results of IT

Tested on swing
Regression: Created a contract and canceled it. ll worked fine
