### ISSUE TITLE
Add the possibility to close or not invoice candidates when canceling a contract

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#1507]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
The invoice candidate will not be invoiced when contract is terminated.
### What is the expected or desired behavior?
We want to allow to cancel a contract, but to not close invoice candidate

**Comment by cristinamghita** [comment]
Test:

* close a contract that has invoice candidates
*check that the candidates were closed be default

**Comment by metas-rc** [comment]
Results of IT

Tested on swing

Note: The handler that closes invoice candidates in not active in mf15 to the candodates were never closed.
Furthermore, the shipment schedules for orderlines that belong to a running contract are not created ( this is an old feature)

Regression: Ending contracts works correctly.
