### ISSUE TITLE
No Default BOM found in Stücklisten-Struktur verifizieren 

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#1508]
### Is this a bug or feature request?

bug

### What is the current behavior?

exception: `No Default BOM found: Check BOM Parent search key`

![stucklisten-struktur-verifizieren](https://cloud.githubusercontent.com/assets/3493126/25950039/f098d910-3659-11e7-9c0e-c6191c705630.PNG)

#### Which are the steps to reproduce?

goto product `Convenience Salat 250g` and push Processing-button

### What is the expected or desired behavior?

no exception, because there is a record in `PP_Product_BOM - PP_Product_BOM_ID=2002873`

**Comment by homebeaver** [comment]
see https://forum.metasfresh.org/t/stucklisten-konfiguration-fehlermeldung/211

**Comment by homebeaver** [comment]
the reason for the error is in the mf-demo/test data table `PP_Product_BOM`

The columns `value` and `name` contains corrupted data. Both contains value+name
See screeshot:

![1508](https://cloud.githubusercontent.com/assets/3493126/26002038/9e06298e-372e-11e7-9e29-204df0d70d2b.PNG)

**Comment by teosarca** [comment]
hmmm, i think the PP_Product_BOM.Value shall be *identical* with M_Product.Value.

**Comment by metasnw** [comment]
meanwhile process was removed from product window
you should use the one in BOM window
in any case make sure: https://github.com/metasfresh/metasfresh/issues/3485#issuecomment-365181362
