### ISSUE TITLE
New Window for Doctype in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1509]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Document Types in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Document Type maintenance and add to WebUI menu in system.

**Comment by metas-lc** [comment]
IT
window is here: System/Belegart (135) OK

created task for document copies field, which is underlines with blue, even if set https://github.com/metasfresh/metasfresh-webui-frontend/issues/755
