### ISSUE TITLE
Translating Shipment Candidates and other fields to en_US

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1513]
### Is this a bug or feature request?
feature

### What is the current behavior?
Some parts are not translated

#### Which are the steps to reproduce?
1. switch to english
1. open shipment chandidates

### What is the expected or desired behavior?
all fields in english

**Comment by metasnw** [comment]
@Arjanvb thx for the translation!

**Comment by metas-lc** [comment]
IT
shipment candidates:
https://w101.metasfresh.com:8443/window/500221/1000000
not translated:  "Liefermenge abw."

The advanced edit should also be translated?
not translated: Lieferbare Menge, Packvorschrift,abw. Anschrift, Sammel-Lieferscheine erlaubt

The Included tabs should also be translated? 
- liefer-/kommissionierzeile (versand-/wareneingangsdisposition)
- handling units zuordnung (all fields inside translated)

**Comment by metas-lc** [comment]
retested: all fields are translated. The window now is called Shipment Disposition OK
