### ISSUE TITLE
HU Transform - split out some TUs from LU does not work correctly with custom LUs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1516]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
Consider following setup and test case (you can have it with different numbers):
* have a product which has the CU-TU capacity: 7 Kg per TU
* receive an LU with 10 TUs each of the TU shall have 10 Kg (and NOT 7Kg as the standard says)
* use HU Transform process to take out 2 TUs

You will get:
* 3 TUs instead of 2 TUs
** TU1 : 7Kg
** TU2: 7Kg
** TU3: 6Kg

That's because the BL considered the standard TU capacity when splitting out.
But when the BL calculated how much Qty CU in total shall be splitted out, it used 2x10Kg=20Kg

### What is the expected or desired behavior?
We shall get 2 TUs, each of them having 10Kg.

**Comment by teosarca** [comment]
rolled out on w101

**Comment by metas-lc** [comment]
IT
repeated the testcase above

1. have a product which has the CU-TU capacity: 8 Kg per TU
2. receive an LU with 10 TUs each of the TU shall have 10 Kg (and NOT 8Kg as the standard says)
3. use HU Transform process to take out 2 TUs
=> on the old i have 8 x 10 TU OK
=> the new LU did not appear NOK
If for e.g. you move the while qty on new LU then HU Editor will be empty (NOK)

**Comment by teosarca** [comment]
@metas-lc 
* in which window did u tested?
* can u pls attach a screenshot with HU transform params?

**Comment by metas-lc** [comment]
@teosarca 
https://w101.metasfresh.com:8443/window/540196?page=1&viewId=540196-34e058c0-284c-4601-81dd-dcc0b8c55871

![hu1](https://cloud.githubusercontent.com/assets/16001666/26160638/8472dc06-3b2a-11e7-9de5-1140272c0079.png)

![hu2](https://cloud.githubusercontent.com/assets/16001666/26160640/8755e2f6-3b2a-11e7-8dac-352e9ffd24ae.png)

![hu3](https://cloud.githubusercontent.com/assets/16001666/26160647/8a1a470c-3b2a-11e7-9ca6-3a29686ea192.png)

**Comment by metas-lc** [comment]
IT2
repeated the testcase above

1. have a product which has the CU-TU capacity: 8 Kg per TU
2. receive an LU with 10 TUs each of the TU shall have 10 Kg (and NOT 8Kg as the standard says)
3. use HU Transform process to take out 2 TUs
=> on the old i have 8 x 10 TU OK
=> new LU was created with 2x10 TUs OK
4. receipt both LUs
=> inout created with 10 TUs and 2 LUs OK
