### ISSUE TITLE
intern: refactor LanguageDAO and LanguageBL

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1517]
AIM: 
* implement ADElementOrADMessageTranslatableString.getAD_Languages()
* implement ADMessageTranslatableString.getAD_Languages()
(atm those are throwing UnsupportedOperationException).

Reason: ImmutableTranslatableString.copyOf is not working which is heavily used by webui.

Note to IT:
* check login languages
* check available languages

**Comment by teosarca** [comment]
status update:
* partial refactoring
* moved all language and translation related classes to de.metas.i18n package

**Comment by metas-lc** [comment]
IT
1. login languages are the same as the ad_language(s) which are system language or base language OK
2. login with en, then with de (tested more languages) 
=> windows and fields are translated OK
3. checked jasper a bit by changing bpartner's language
=> jaspers are translated accordingly OK
