### ISSUE TITLE
Show currency from pricelist in pricelist / pricelist comparison Jasper

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1518]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The currency displayed in pricelist / pricelist comparison Jasper is hardcoded, always CHF.
#### Which are the steps to reproduce?
Check a pricelist jasper, e.g. for a bpartner with pricelist currency: EUR.
### What is the expected or desired behavior?
Currency in pricelist / pricelist comparison Jasper shall be the currency set in the resp. pricelist.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
currency not hardcodeded anymore. Tested with Eur. OK
