### ISSUE TITLE
standard database: add SSCC attribute to "DIM_Barcode_Attributes" dimension spec

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1521]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Current vanilla database (and also w101) does not have the SSCC attribute added to "DIM_Barcode_Attributes".
As a result, the BLs which are searching HUs by barcode are checking only the M_HU.Value and not the SSCC attribute.

#### Which are the steps to reproduce?
(TODO)
atm it's reproductible only on development workstation because there i am calling those BLs.
See task https://github.com/metasfresh/metasfresh-webui-api/issues/364

### What is the expected or desired behavior?
When searching by Barcode, the SSCC attribute shall be also checked.

### Migration script to fix it
(5462450_migration_2017-05-12_postgresql.sql)
```
-- 2017-05-12T22:50:43.533
-- I forgot to set the DICTIONARY_ID_COMMENTS System Configurator
INSERT INTO DIM_Dimension_Spec_Attribute (AD_Client_ID,AD_Org_ID,AttributeValueType,Created,CreatedBy,DIM_Dimension_Spec_Attribute_ID,DIM_Dimension_Spec_ID,IsActive,IsIncludeAllAttributeValues,IsValueAggregate,M_Attribute_ID,Updated,UpdatedBy) VALUES (1000000,1000000,'S',TO_TIMESTAMP('2017-05-12 22:50:43','YYYY-MM-DD HH24:MI:SS'),100,540015,540007,'Y','Y','N',540011,TO_TIMESTAMP('2017-05-12 22:50:43','YYYY-MM-DD HH24:MI:SS'),100)
;
```

**Comment by teosarca** [comment]
update: applied manually on w101

**Comment by metas-ts** [comment]
hi teo, wdyt about adding a `where not exists (...)`? then we could add it to the repo without causing problems on the next w101 rollout

**Comment by teosarca** [comment]
@metas-ts  yup, sounds good

**Comment by metas-rc** [comment]
Tested on webui.
Receiven HUs, checked sscc, copied it, went to Handling Units editor and searched for the copied string
= OK: The HU was correctly found
