### ISSUE TITLE
New Window for Print Format in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1523]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Print Format in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Print Format maintenance and add to WebUI menu in system.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window Print Format in WebUI (Druck-Format): OK
* to be found in menu under System: OK
