### ISSUE TITLE
New Window for Document Sequence in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1524]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Document Sequence in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Document Sequence maintenance and add to WebUI menu in system.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window for Document Sequence maintenance (Nummernfolge für Belege): OK
* in WebUI menu in System: OK
