### ISSUE TITLE
FRESH-488 PaymentRule = S in Invoice

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#153]
Although niot set in C_BPartner the PaymentRule = S sometime is set Invoice (Purchase and Sales).
Please deactivate S as PaymentRule and make sure that this does not have any Side Effects.

**Comment by teosarca** [comment]
Also see org.compiere.model.CalloutInvoice.docType(Properties, int, GridTab, GridField, Object) ... basically, by default, if it's a Vendor invoice, by default the PaymentRule is set to S (Check).
