### ISSUE TITLE
Performance Picking on Button "Distribution"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1532]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Since a short time, the performance of "Distribution" Functionality in Picking is Decreasing.
#### Which are the steps to reproduce?
Select a Picking product. Go to 2nd Window. Add a Packing Item to Picking Slot. Select the Picking Slot and Product. Press on "Distribution" Button and select 1 pce of Product per TU and a larger amount of TU.
### What is the expected or desired behavior?
It takes approx. 1 sec per TU to distribute. Shall be much faster.

**Comment by teosarca** [comment]
closing because it's too old
