### ISSUE TITLE
Menu Maintenance improvement

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1533]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is tough to maintain the different Menus for WebUI.
### What is the expected or desired behavior?
It could be a solution to add the AD_Role.Root_Menu-NOde_ID to Role definition and allow the Menu maintenance in an easy way. Only 1 Menue but w/ different Root-Nodes. No need to sync those menus anymore.

**Comment by teosarca** [comment]
Fixed in https://github.com/metasfresh/metasfresh-webui-api/issues/391

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/391 OK
