### ISSUE TITLE
New Window for Product BOM in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1539]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Product BOM in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for Product BOM (PP_Product_BOM) and add to WebUI menu in manufacturing.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* new window Multi Level BOM & Formula Detail: OK
