### ISSUE TITLE
Zoom-to S_Ressource in Manufacturing Order opens wrong window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1540]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When pressing on Zoom-to S_Resource in Manufacturing Order window in WebUI, the window ID 236 is opened.
#### Which are the steps to reproduce?
Open WebUI and check.
### What is the expected or desired behavior?
The zoom-to shall open the window AD_Window_ID 53004 Newly created window in WebUI)

**Comment by teosarca** [comment]
shall be fixed by https://github.com/metasfresh/metasfresh-webui-api/issues/381

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/381 OK
