### ISSUE TITLE
Add login Field to User Window in WebUI Main View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1546]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the field Login is only shown in advanced edit.
#### Which are the steps to reproduce?
Open the User Window and see.
### What is the expected or desired behavior?
Show the login field in Main View.

**Comment by metas-lc** [comment]
IT
go to User window (window/108), open a user in document view
=> login field is there, editable and mandatory only if system user is set OK
