### ISSUE TITLE
Jasper Document for Customer Returns

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1551]
### Is this a bug or feature request?
feature
### What is the expected or desired behavior?
same as Jasper Document for Vendor Returns

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, Swing

* Jasper for customer returns: OK
* if no lines for Gebinde exist, the packing item for the product is not displayed, no header either ("Packvorschrift"), as in order etc.: OK
* in Draft, Jasper is missing the "Entwurf": NOK

**Comment by metas-lc** [comment]
IT
webui
"Entwurf" issue is solved OK
rest works the same OK
