### ISSUE TITLE
add default search fields for business partner window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1555]
### Is this a bug or feature request?
feature request

### What is the current behavior?
no usable fields in standard search available

#### Which are the steps to reproduce?
open search in bpartner window

### What is the expected or desired behavior?
have at least name, value and bp group

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested  on w101

* filter in bpartner window, standard: name, company name, value, bpartner group: OK
(Additional filters: first name, last name, Vertriebsbeauftragter)
* filters working correctly: OK
