### ISSUE TITLE
Minor Invoice Layout Issues

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1559]
### Is this a bug or feature request?
bug

### What is the current behavior?
![image](https://cloud.githubusercontent.com/assets/16079655/26150647/9a07708e-3aff-11e7-9212-bb7412fb4ad2.png)

#### Which are the steps to reproduce?
open any invoice with a line

### What is the expected or desired behavior?
1. put a little space between Menge and Einheit
1. increase Einheit so the word is not cut off
1. Margin on the left of the page is much smaller than the margin on the right of the page
1. product names are cut off

**Comment by metasnw** [comment]
on w101 the word Einheit is complete

![image](https://cloud.githubusercontent.com/assets/16079655/26150793/6be17de8-3b00-11e7-8efb-56b02108e4a7.png)

**Comment by metasnw** [comment]
@metas-lc as discussed we will make the product name break into next line and as there are pos numbers user still can see where the next line begins

**Comment by metas-lc** [comment]
updated jaspers for invoice, inout and order. Fixed 1,2 and 4. Will create a task for 3 because it requires multiple changes.
Now product names can appear on multiple lines if there is not enough space.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
![image](https://cloud.githubusercontent.com/assets/13365687/26634951/7cf1f946-4618-11e7-8058-fbb27b0956fc.png)
