### ISSUE TITLE
Add description fields to invoice window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1560]
### Is this a bug or feature request?
Feature

### What is the current behavior?
add description fields like we did for delivery note to invoice window in webUI

#### Which are the steps to reproduce?
open invoice window

### What is the expected or desired behavior?
Have this also for invoice:

![image](https://cloud.githubusercontent.com/assets/16079655/26150887/ce4699aa-3b00-11e7-86ba-b6027f1f7742.png)

**Comment by metas-mk** [comment]
Added the 2 fields to new section for advanced edit.

**Comment by metas-lc** [comment]
IT
1. go to sales invoice and select a line, open it in doc view
2. go to advanced edit 
=> ok both description fields are there
