### ISSUE TITLE
Invoicing problem with reversed inouts that have a quality discount

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1566]
### Is this a bug or feature request?
Bug
### What is the current behavior?

If you want to invoice an IC that is associated with an M_InOut that is both
* reversed
* has quality discount lines

then the system only invoices only a wrong qty

#### Which are the steps to reproduce?

* create two inouts with quality discounts for the same order line
* reverse one of them
*create an invoice

the invoiced quantity is different from the delivered qty

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15, Swing

repeated testcase described above:

* qty delivered and qty invoiced are the same, = only the qty that was not reversed: OK
* qties and quality issue correctly displayed in invoice & invoice jasper: OK
