### ISSUE TITLE
User Window adjustment in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1572]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Some Fields in User Window of webUI are not optimized on the current requirements. The window shall be rearranged to move the most important fields to the main view and primary element group.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Rearrange the fields.

![image](https://cloud.githubusercontent.com/assets/13365687/26210173/28a4faba-3bef-11e7-867e-3d6e4a19e174.png)

**Comment by metas-ts** [comment]
@metasnw @metas-mk I just cherry-picked this task into the `release`-branch

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
