### ISSUE TITLE
New Field for  Menu Root Node in Role window of WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1574]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
A new Column is added to Role Table. The corresponding Field is not shown in Role Window in WebUI yet.
#### Which are the steps to reproduce?
Open the Roles Window in WebUI and check.
### What is the expected or desired behavior?
Add the Field to Role Window in WebbUI.

belongs https://github.com/metasfresh/metasfresh-webui-api/issues/391

**Comment by metas-lc** [comment]
IT
go to Role window => Root menu node is only in advance edit

**Comment by metas-mk** [comment]
Hi @metas-lc 
Yes, thanks. That's on purpose.
