### ISSUE TITLE
Introduce /test/ping/notifications server troubleshooting endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1577]
### Is this a bug or feature request?
Feature

### What is the expected or desired behavior?
When you will call http(s)://metasfresh-server/test/ping/notifications the metasfresh-server  will send a general notification, "Notifications system test".

The endpoint shall be secured (only for SuperUser, same as /serverMonitor.

**Comment by teosarca** [comment]
Tested on w101 using:
```
curl -u SuperUser:password http://w101.metasfresh.com:8181/test/ping/notifications
```

and it worked.

**Comment by metas-ts** [comment]
hi @teosarca in your test, port 8181 is the webui-api's port, right? 
does this feature also create (JMS-)event and ping the backend from the webui-api? or does it "just" cause the webui-api to send a notification to the webui-frontend?

**Comment by teosarca** [comment]
hi @metas-ts  the endpoint is on metasfresh-server (NOT the webui)
when called, the metasfresh-server will create a general event and it will post it to event bus.
From there the event will be broadcasted to all other instances like metasfresh-webui-api server, via JMS/ActiveMQ.
The metasfresh-webui-api server will pick up that event and will forward it to web browsers via web sockets.
The web browsers will pick that event from websocket and it will display in the notifications widget.

Technically, see org.adempiere.serverRoot.servlet.TroubleshootingRestController.pingNotifications()
