### ISSUE TITLE
Changing the qty in PP_Order causes error

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1581]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Changing the qty of the product to be produced in PP_Order throws an error:  https://pastebin.com/ywXmhxsL
#### Which are the steps to reproduce?
* Create a new PP_Order, set all mandatory fields: qty is 1
* Change the qty, try to save: Error, NOK
![image](https://cloud.githubusercontent.com/assets/1264789/26710410/faf5caa6-4759-11e7-806c-5d8f9e660888.png)

### What is the expected or desired behavior?
User should be able to change the qty without error.

**Comment by metas-ts** [comment]
moving this to rollout, so the workarond which covers most of the cases (everything besides reactivate and then change) can already be pushed forward.
going to create a dedicated issue for the comprehensive fix

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT (swing, webui)
1. create a new pp order, add all mandatory fields, save
2. change the qty , save
=> qty changed without errors OK
