### ISSUE TITLE
One time unifying Full Migration of current Menu Tree

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1588]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, for the use of Menu Node ID functionality for Submenus as main menu, we will need a Full Migration of the menu initially on all hosts.
### What is the expected or desired behavior?
Migrate the Main menu once.
Important: we should think about to create a completely new menu as duplicate called "metasfresh base menu" or similar. For the case, that other users/ customers have already made changes to their menus. We should avoid to overwrite them. WDYT?

**Comment by teosarca** [comment]
fixed in https://github.com/metasfresh/metasfresh/issues/1599
