### ISSUE TITLE
Translate User Window to en_US

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1590]
### Is this a bug or feature request?
feature request

### What is the current behavior?
some fields like firstname are not translated

#### Which are the steps to reproduce?
open window user

### What is the expected or desired behavior?
all translated to english

**Comment by metas-mk** [comment]
Tested. NOK
Sprache = Language
system user = System User
Organization = Organisation
Ldap Processor = LDAP Processor
Rolle = Role
Nutzersitzung = User Session
(some of the words mentioned above are in Subtabs)
![image](https://user-images.githubusercontent.com/13365687/27227805-430ea050-52a5-11e7-8491-dad2024e61d9.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works nicely as required. User window is translated. Done/ Closing.
