### ISSUE TITLE
Password Field is missing in user window in WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1591]
### Is this a bug or feature request?
bug

### What is the current behavior?
its not shown in 5.9 nor 5.10

![image](https://cloud.githubusercontent.com/assets/16079655/26274897/1e79306c-3d55-11e7-8d21-f9db7aae5d8f.png)

#### Which are the steps to reproduce?
1. open window user
1. tick systembenutzer
1. NOK: No password field

### What is the expected or desired behavior?
should be displayed as soon as systembenutzer is ticked

**Comment by metasnw** [comment]
checked on 5.10 and it seems to be disabled:
![image](https://cloud.githubusercontent.com/assets/16079655/26275025/a9761fd4-3d57-11e7-80f5-a6fd1e0c5bc6.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Closed and Done.
