### ISSUE TITLE
Show manufactoring order documentno in production order overview

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1602]
### Is this a bug or feature request?
feature

### What is the current behavior?
number is not shown:
![image](https://cloud.githubusercontent.com/assets/16079655/26303975/ebda2a30-3ee9-11e7-8fdd-d743e769646b.png)

#### Which are the steps to reproduce?
open window production order

### What is the expected or desired behavior?
show it as column in grid

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested on w101. Works as required. Closing.
