### ISSUE TITLE
Enhance Vendor returns

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1603]
Followup for https://github.com/metasfresh/metasfresh/issues/1062

### Is this a bug or feature request?
* Bug/ Enhancement
### What is the current behavior?
See results of IT from #1062

Additional requirements:
* The POReference to the original purchase order must be added in the vendor return and in the vendor return's invoice candidates.

**Comment by metas-lc** [comment]
please also set and display m_hu_pi_item_product and qtyenteredtu, in inoutline

**Comment by metas-lc** [comment]
case: 
1. create an order with a product ASI "a"
2. go to receipt pos and change the ASI to "b"
3. create inout
=> inout created with ASI "b"
4. create vendor return 
=> inout created with ASI "a" OK??

**Comment by metas-lc** [comment]
note for IT:
complete the testcase from here https://github.com/metasfresh/metasfresh/issues/1062 and create a test docu

**Comment by metas-ts** [comment]
also cherry-picked this one into the branch `release_gh1306`

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. ASI is now taken from inout OK
