### ISSUE TITLE
Enhance Material disposal (garbage)

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1604]
Followup for https://github.com/metasfresh/metasfresh/issues/1064

### Is this a bug or feature request?
* Bug/enhancement
### What is the current behavior?
> Check IT of #1064

* Create invoice candidates for the material disposals

* The POReference to the original purchase order must be added in the material disposal and in the material disposal's invoice candidates.

* Make return to garbage work for HUs with TU's of multiple products.

**Comment by metas-lc** [comment]
IT
(see testcase 3)
1. Create invoice candidates for the material disposals => works fine: i got 1 invoice candidate per product (no HUs are included), qty with minus. Invoice created with qty and price with minus, total with plus, credit memo OK

2. the POReference to the original purchase order must be added in the material disposal and in the material disposal's invoice candidates.
=> reference is in inventory, invoice candidates and invoice OK
(i did simple case: order to disposal and complex, with creating receipt from 2 different orders at the same time, with different reference. I got 2 different disposal, each with the correct reference)
OK

3. Make return to garbage work for HUs with TU's of multiple products
=> doesn't work. I got this error message: "Assumption failure: Cannot allocate 10 when qtyToAllocate is 0"
(i did purchase order 2 products => wareneingang pos put them on 1 LU => material dispsal => error ) NOK

4. webUI (on swing works): create 1 purchase order, 2 products. Open both of them in material receipt candidates - hu editor. go to invoice candidates, select both of them, create invoice =>
"org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "master"↵  Position: 452↵	SQL: INSERT INTO T_SELECTION(AD_PINSTANCE_ID, T_SELECTION_ID)  SELECT 1005908, C_Invoice_Candidate_ID FROM C_Invoice_Candidate↵ WHERE ((((/* MQuery-e4dc650c-bec6-41cb-8629-7b65095fe752 */((↵	↵exists (↵	select 1 from M_Inventory i↵	join M_InventoryLine il on i.M_Inventory_ID = il.M_Inventory_ID↵	join C_Invoice_Candidate ic on ic.AD_Table_ID = get_table_ID('M_InventoryLine') and ic.Record_ID =  il.M_InventoryLine_ID ↵	↵	where ic.C_Invoice_Candidate_ID = master.C_Invoice_Candidate_ID and i.M_Inventory_ID = 1000007↵	)))) AND (exists (select 1 from T_WEBUI_ViewSelection sel  where  UUID='540092-1622cb35678c4d04be31e05febb16840' and sel.Record_ID=C_Invoice_Candidate.C_Invoice_Candidate_ID) AND C_Invoice_Candidate.C_Invoice_Candidate_ID IN (1000102,1000101))) AND (AD_Client_ID=1000000) AND (1=1)) AND (IsActive=?) AND (AD_Client_ID=?))  AND ↵ /* security-client */ C_Invoice_Candidate.AD_Client_ID IN (0,1000000)↵ /* security-record */ AND C_Invoice_Candidate.C_Invoice_Candidate_ID NOT IN ( SELECT Record_ID FROM AD_Private_Access WHERE AD_Table_ID = 540270 AND AD_User_ID <> 2188224 AND IsActive = 'Y' )↵	SQL params: [true, 1000000]"
NOK

**Comment by metas-lc** [comment]
IT
retested cases 1,2 and 3 - works fine OK
for 4 created issue https://github.com/metasfresh/metasfresh-webui-api/issues/500
