### ISSUE TITLE
Add IsQualityReturnWarehouse flag to warehouse window WebUI

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1606]
![image](https://cloud.githubusercontent.com/assets/1244701/26309054/3b81e1f8-3f04-11e7-96cc-cabeb33dce10.png)

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/396

**Comment by metas-lc** [comment]
IT
open warehouse window (139) and select one
=> isQualityReturnWarehouse checkbox is there, editable OK
