### ISSUE TITLE
New Window for Business Partner Group in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1612]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for the Business Partner Group in WebUI
#### Which are the steps to reproduce?
Open WebUI and see.
### What is the expected or desired behavior?
Create a window for the Business Partner Group and add to WebUI menu in CRM.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 & mf15, WebUI

* new window  Business Partner Group in WebUI: OK
* in CRM (Settings): OK

=> when searching for "Geschäfts" in  mf15 WebUI, you have "Geschäftspartnergruppe" & "Geschäftspartnergruppen" displayed in the results (see pic); the windows seem to be the same according to URL, and when browsing the whole menu tree, only Geschäftspartnergruppen is displayed in CRM section

@metas-mk: is that wanted?
![2017-05-24 10_33_04-metasfresh](https://cloud.githubusercontent.com/assets/18696715/26394489/6e6daf1a-406d-11e7-9686-2c5cb27f2234.png)

**Comment by metas-lc** [comment]
IT
checked again and there is only 1 "Geschäftspartnergruppen" or "Business Partner Group" in crm/settings OK
window seems fine. OK
