### ISSUE TITLE
Address lines is cut off on shipment jasper document

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1615]
### Is this a bug or feature request?
bug

### What is the current behavior?
after you uploaded a logo with the wizard the address is cut off 

#### Which are the steps to reproduce?
https://forum.metasfresh.org/t/webui-adresse-in-allen-belegarten-merkmale-fuer-ein-produkt/405/4

### What is the expected or desired behavior?
company name should not be cut off. GmbH is missing

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
webui
name fields are bigger (on both left and right, with names of 30 chars) OK
