### ISSUE TITLE
Check if imported esr file is v11 file

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#1617]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Any file can be imported.
#### Which are the steps to reproduce?
Try to import a txt file. Will be imported as record.
### What is the expected or desired behavior?
To import just v11 files.

**Comment by metas-lc** [comment]
IT
Imported xml files and v11 => works OK
imported txt files => Der Datentyp der zu importierenden Datei konnte nicht anhand des Dateinamens festgestellt werden. Bitte setzen Sie den Typ im entsprechenden Feld des Import-Datensatzes. OK
