### ISSUE TITLE
Do not process reverse booking lines and improve esr import

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#1619]
### Is this a bug or feature request?
Feature
### What is the current behaviour?
Try to process any line
### What is the expected or desired behaviour?
Do not process the lines with TrxType 005(reverse booking). Those lines will be dealt manually by the user.

**Comment by cristinamghita** [comment]
* Lines with transaction code 005 will not be automatically processed

Test:
* Do a regular import
* All should work as usual

**Comment by metas-lc** [comment]
IT
regular import => works fine, no errors OK
005 import (on the first line, the first 002 have to change with 005)
=> The calculated amount for lines (-111.00)  does not fit the control amount (111.00). The document will not be processed.
