### ISSUE TITLE
NPE when closing the pp_order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1624]
### Is this a bug or feature request?
bug
### What is the current behavior?
NPE when you try to complete a pp_order
#### Which are the steps to reproduce?
1. create a new pp_order, waschprobe, and complete it
2. go to fertigstellung maske pos and select your order, issue and receive
3. close it
=> Error Processing Document
document: Waschprobe 1046019 Belegverarbeitung: CL Cause: NullPointerException: componentType (NullPointerException)
 NOK
4. close it again 
=> works but you can't get anything in Ausvertung subtab in Produktionsauftrag NOK
### What is the expected or desired behavior?
document should close and ausvertung lines to be created

**Comment by teosarca** [comment]
stacktrace: https://pastebin.com/L2niRhSd

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-dh** [comment]
Results of IT1
tested on sp80, Swing

repeated testcase from above:
* no error when closing the pp_order, works fine: OK
* data in Auswertung for the pp_order: OK
* invoice candidates are created with the correct qties (according to qties in Auswertung): OK
