### ISSUE TITLE
Sales Order Window Advanced edit rearrangement

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1628]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit Mode of Sales Order looks a bit untidy after changings the Layout from 1 column to 2 column.
#### Which are the steps to reproduce?
Open the window window/123/ in advanced edit and see.
### What is the expected or desired behavior?
Create an own section for the advanced edit fields so that they are seamlessly shown underneath the main view layout.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
