### ISSUE TITLE
Invoice data goes missing in payment after save

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#1629]
### Is this a bug or feature request?
Bug
### What is the current behavior?
After selecting an invoice in payment, save, the invoice disappears again, and Skonto & Unter-/ Überzahlung are not displayed.
#### Which are the steps to reproduce?
* have a sales invoice
* in payment, select outgoing payment, and a bank account to use
* don't select the bpartner of the invoice, but the invoice itself: => bpartner is set, OK
* save: invoice you selected disappears, Skonto & Unter-/ Überzahlung are not displayed: NOK
### What is the expected or desired behavior?
No data shall disappear when saving the document, Skonto & Unter-/ Überzahlung shall be displayed after saving.

Pls note: if you set the invoice a second time and save, it works; also works when you set the bpartner first and then the invoice!

**Comment by metas-rc** [comment]
Notes after troubleshooting
* Not reproduceble in webui
** Invoice could not be selected in webui because of a valrule -> I fixed the valrule so now invoices can also be selected in Payment in webui.
** With this problem solved, when inserting Invoice in Payment via webui it all works correctly and data is not lost.

* Now I will do the troubleshooting in swing version

**Comment by metas-rc** [comment]
Note to IT
Please, make sure it works on webui. We don't need it to work in swing.

**Comment by metas-lc** [comment]
IT
tested it in webUI:

1. create new payment
2. don't set any bpartner, start searching in invoice field
=> all invoices are selectable OK
3. set a bpartner, start searching in invoice field 
=> only invoices from that bpartner are selectable OK
4. set document type
=> document is saved, invoice data is still there OK
.
5. create a new payment, add invoice
=> bpartner is set correctly, to the one from invoice OK
6. set document type
=> payment is now saved, invoice data is still there OK
