### ISSUE TITLE
Producer Invoices w/ price override after invoice void wrong

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1630]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when setting a price override in invoice candidate, invoicing, voiding the invoice and invoicing again, the price actual in the newly created invoice is wrong.
#### Which are the steps to reproduce?
Create a Purchase Order with a product Line. Do the Material Receipt. Go to Invoice Candidates and override the price. Create the invoice. Void the invoice. Create a new invoice. The Priceactual in the new invoice is wrong (initial Purchase order price). Price entered remains correct, as in Price Override.
### What is the expected or desired behavior?
Price actual shall also have the price override.

**Comment by metas-rc** [comment]
I wasn't able to reproduce the bug any more. Moving task to done.
