### ISSUE TITLE
Column Resizing in Sales Order Grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1642]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, some content of important data is cut off and others like currency or some dates are too wide.
#### Which are the steps to reproduce?
Open the Sales Order Window in Grid view and check.
### What is the expected or desired behavior?
Resize the important columns to large and less important to a smaller size to allow a better-focused overview according to the importance of the field.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
