### ISSUE TITLE
Add CountExpected in Async Batch and improvements

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#1655]
### Is this a bug or feature request?
Feature
### What is the expected or desired behavior?
We want to know to how many records to expect in case when that is possible.

**Comment by teosarca** [comment]
rolled on w101

**Comment by cristinamghita** [comment]
* Add CounExpected in C_Async_Batch - used when we know exactly how many WPs will be
* Add skipTimeout in C_Async_Batch_Type -used when we want to change the standard skip time

Test: 
* do a esr import
* all work as before

**Comment by metas-dh** [comment]
Closing issue since it's old and the esr imports i recently tested all worked fine.
