### ISSUE TITLE
No Packing Item in jaspers

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1656]
### Is this a bug or feature request?
bug
### What is the current behavior?
you can see "No Packing Item" in jasper if you don't set any HU on your document line
#### Which are the steps to reproduce?
1. go to sales or purchase order and create a new one
2. add a product without HU
3. print preview
=> on the product's line is "No Packing Item"
### What is the expected or desired behavior?
should be empty

**Comment by metas-lc** [comment]
Add a checkbox in M_HU_PI something like dontPrintText and use it in Jasper's sqls so we don't have to update them each time the name's changed

**Comment by metas-lc** [comment]
Affected jaspers: sales and purchase order, inout and invoice, empties and pricelist

**Comment by metas-lc** [comment]
IT
inout - the assignments are made by "no package item" but there actually is an HU. You can see it via M_HU_PI_Item_Product - M_HU_PI_Item - M_HU_PI_Version_ID (instead of checking M_HU_PI_Version_ID from tu directly)

**Comment by metas-ts** [comment]
Cherry-picked the latest fix into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/157/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
tested on webui => works fine OK
