### ISSUE TITLE
make process field autocomplete  in table and columns window 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1661]
### Is this a bug or feature request?
feature

### What is the current behavior?
long dropdownlist. hard to find particular process

#### Which are the steps to reproduce?
1. open window table and column
2. go to tab assigned processed
3. add new record
4. NOK: try to fill out process

### What is the expected or desired behavior?
have autocomplete in java client

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
IT
Tested on swing
* Autocomplete of AD_Process in the window Tabelle Und Spalte works correctly.
