### ISSUE TITLE
new order checkup jasper

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1663]
### Is this a bug or feature request?
feature
### What is the current behavior?
we have a jasper for bestellkontrolle but we are going to make a new one
### What is the expected or desired behavior?
new jasper for bestellkontrolle, wilth less info than the one before
left side: info about the document
right side: info about bpartner
details: barcode on the left, first field, then data about the product line

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
jasper for bestellkontrolle window is updated
