### ISSUE TITLE
Adjustments to Product Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1677]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Client Field is not added to Product Window in WebUI.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Add the Client Field to Product Window in WebUI.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
open product window => client field is there OK
