### ISSUE TITLE
New Window for Standard Response in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1681]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Standard Response is missing in WebUI
#### Which are the steps to reproduce?
Open the WebUI and see.
### What is the expected or desired behavior?
Create a new Window for Standard Response (R_StandardResponse) and add in the menu to CRM/Settings.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
