### ISSUE TITLE
Refactor Request Tab in Partner Window to allow zoom and advanced edit

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1687]
### Is this a bug or feature request?
feature

### What is the current behavior?
1. you cant zoom directly into request lines
2. open advanced edit throws error

#### Which are the steps to reproduce?
1. open partner with a request
2. NOK: try to open the request in advanced edit from grid
3. NOK: try to zoom into

### What is the expected or desired behavior?
1. zoom into => open request window
2. advanced edit => shows advanced edit for the row

![image](https://cloud.githubusercontent.com/assets/16079655/26555111/e84ab880-4493-11e7-8de4-532802981cfc.png)

![image](https://cloud.githubusercontent.com/assets/16079655/26555568/eca06e46-4495-11e7-89d3-75b5dbde601c.png)

### Impact
**Warning**: The display of documents within the request list will be dropped and instead there will only request be displayed.

**Comment by teosarca** [comment]
rolled on w101

**Comment by teosarca** [comment]
Update: in task https://github.com/metasfresh/metasfresh-webui-api/issues/431 i've reverted the change from here (about setting the R_Request_ID's reference from ID to TableDir).

To fix this task, i've implemented following behaviour:
* primary key is always zoomable
* so if you show it, user shall be able to right-click and zoom

**Comment by metas-lc** [comment]
IT
1. go to business partner window and open one that contains requests
2. select a line with right click - advance edit
=> advance edit opens without errors
3. select a line with right click - zoom into
=> the corresponding request opens in a new tab, with no errors
4. (regression) go to actions and create a new request, set the summary
=> request created without errors
=> zoom into and advance edit works fine
