### ISSUE TITLE
Introduce AD_User.Avatar_ID and AD_Language fields

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1695]
### Is this a bug or feature request?
feature request

### What is the expected or desired behavior?
Introduce following fields to AD_User:
* Avatar_ID - user's picture/avatar, image, not mandatory (same as C_BPartner.Logo_ID)
* AD_Language - user's preferred language, point to AD_Language(s), not mandatory (same as C_BPartner.AD_Language)

Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/802

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. open user window
=> avatar and language fields are there, not mandatory
2. set them
=> saves ok, no errors OK
3. remove them
=>ok, no errors, user is saved OK
