### ISSUE TITLE
Add Handling Unit Editor Window to WebUI Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1705]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Handling Unit Editor window is not included in the WebUI menu.
#### Which are the steps to reproduce?
Open the Menu and See.
### What is the expected or desired behavior?
Add the Handling Unit Editor into WebUI Menu in logistic group.

**Comment by metas-mk** [comment]
The window Number is 540189

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
