### ISSUE TITLE
Add Handling Unit Assignment Tab to Customer Returns Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1707]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Handling Unit Assignment Tab in Customer Returns window
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Define the Layout for the Grid view of the Handling Unit Tab in Customer Returns window.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
