### ISSUE TITLE
Pimp the old "My Profile" window to be used in webui as User settings

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1709]
### Is this a bug or feature request?
feature request

### What is the expected or desired behavior?
The "My Profile" window (AD_Window_ID=53100) shall have a nice single row layout.
We shall use it in webui to allow the user changing it's current profile.

Related tasks:
* main frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/802
* Introduce AD_User.Avatar_ID and AD_Language fields: https://github.com/metasfresh/metasfresh/issues/1695

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Checked the first draft window. A few further adjustments are needed:
* Instead of Name Field, show Firstname & Lastname
* Take out the Subtab

**Comment by metas-mk** [comment]
Added further changes to Window.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
