### ISSUE TITLE
Support Product Search in window BOM

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1711]
### Is this a bug or feature request?
feature

### What is the current behavior?
no search available

#### Which are the steps to reproduce?
https://w101.metasfresh.com:8443/window/53006 

### What is the expected or desired behavior?
at least search fields for product

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
webui
1. open window Bill of Materials (53006)
=> there is default filter
2. open the filter 
=> you can search for product
3. use the filter 
=> filtering for products works fine
