### ISSUE TITLE
Wrong Handling Unit Assignment in Shipment Schedule via aggregated Picking

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1712]
### Is this a bug or feature request?
Bug
### What is the current behavior?
2 Sales Orders with same Business Partner and Location and Produkt, lead to the wrong result in Handling Unit Assignments via Picking Terminal. They are picked together in one sum and seem to be wrongly distributed onto the shipment schedule lines.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Distribute the Handling Units and Assignments onto the correct Shipment Schedules and Shipments.

**Comment by metas-ts** [comment]
Cherry-Picked to the release branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/155/

**Comment by metas-lc** [comment]
IT
swing
1. org2 having a config to not aggregate products on picking. org1 default config
2. login with org2, create 2 orders, same bpartner, location, product. You can add different qtys
3. go to picking slot 
=> there are 2 rows for your product
4. select them and do picking using hu editor, with already existing TUs
=> 2 inouts created, hu assignments set ok, but i didn't get lines for TU in inout.. ok?

5. repeated the same testcase for org1. 
=> got 1 line in picking terminal, 2 inouts, both containing TUs and LUs, correct qty and assignments
