### ISSUE TITLE
Add Validation Rule to Empties Return/ Receive M_Product_ID

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1714]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Validation Rule for M_Product (Trading Unit/ Packing Material) is on column Level, which does not for all InOut Windows.
#### Which are the steps to reproduce?
For example, open the Vendor Return Window and try to add a return Product which is not a Packing Material.
### What is the expected or desired behavior?
Allow the restriction of M_Product Packing Materials only for empties return/ receipt windows.

Solves this problem: https://github.com/metasfresh/metasfresh-webui-api/issues/295

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
