### ISSUE TITLE
Fix BPartner Contact advanced edit layout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1718]
### Is this a bug or feature request?
bug

### What is the current behavior?
BPartner Contact advanced edit looks very awkward.
e.g.
* First name it's on top but last name some where deep down,
* Name is displayed but i am not sure if we shall display it
* etc

#### Which are the steps to reproduce?
* open a BPartner 
* add new contact

![image](https://cloud.githubusercontent.com/assets/1244701/26734973/b63dc5d4-47c8-11e7-8e4f-a5df4cc8d11f.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
