### ISSUE TITLE
New Window for Request Status in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1722]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window in WebUI to allow the user to maintain the Request Status.
#### Which are the steps to reproduce?
Open the menu and see.
### What is the expected or desired behavior?
Create the window for Request Status and add to the menu in CRM/settings.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
