### ISSUE TITLE
Adjustments to Request Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1723]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Client Field is not added to Product Window in WebUI and different Layout criteria are not equal to our current default.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Add the Client Field to Request Window in WebUI and harmonize the layout/ Look&Feel.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
