### ISSUE TITLE
Adjustments to window Product Category in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1729]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Product Category is not harmonized with current default Look&Feel. Also, the Widget sizes in Grid View have not been adjusted after Size functionality. Also, Check the other windows like UOM or Attributes.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Harmonize the Look&Feel and adjust the Field sizes for Grid View.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
