### ISSUE TITLE
New Window for Discount Maintenance in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1730]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window Definition for Discount Maintenance in WebUI.
#### Which are the steps to reproduce?
Open the and see.
### What is the expected or desired behavior?
Create the window for Discount.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
discount schema window in product management. Created one, saves OK
