### ISSUE TITLE
Add avatar selection for user

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh#1732]
### Is this a bug or feature request?

Feature request

### What is the current behavior?

Avatar cannot be selected or uploaded.

### What is the expected or desired behavior?

User should have possibility to change his avatar by:
- uploading new avatar from disk
- selecting to "Use Gravatar"
- removing avatar (will switch back to silhouette)

### TODO

1. Provide API to set new avatar.
2. Provide API to get avatar URL. From #1695?

**Comment by metas-mk** [comment]
@cadavre we've prepared a backend window which has the possibilities to upload add the image. same for language settings. Check out in window /window/53100/ or in window window/108/

Here is an example how it looks like atm:

![image](https://cloud.githubusercontent.com/assets/13365687/26784262/0196ba78-49fd-11e7-9d0b-8298e9250eeb.png)

**Comment by metas-mk** [comment]
@cadavre the idea was to use the email of the user to fetch the gravatar. is that not the case how to do, or do we need an additional email field?

**Comment by cadavre** [comment]
The question is – do we allow user to upload photo or only use Gravatar? If we want to give him possibility to do so – you would need additional switch in this doc. If only Gravatar – yes, we don't have email address and we would need to receive it in one of first API calls after login.

So if you have already implemented – we're waiting for instruction of how to integrate. :)

**Comment by metas-mk** [comment]
No need for further changes here atm. Closing.
