### ISSUE TITLE
istransferwhennull not working in webUI but in java client

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1735]
### Is this a bug or feature request?
bug

### What is the current behavior?
istransferwhennull  is ignored on webui
tested on version 5.11

#### Which are the steps to reproduce?
1. have an attribute e.g. MasterNo with istransferwhennull = Y
1. material receipt for a product with istransferwhennull = Y
1.1. set MasterNo  = 'test'
1. do pp order
1. issue HU with MasterNo  = 'test'
1. receive
1. OK: on java swing the MasterNo  = 'test' 
1. NOK: on webui the MasterNo  is NULL

Case using LotNo on w101
https://w101.metasfresh.com:8443/window/53009/1000035

### What is the expected or desired behavior?
webui shall behave like swing

**Comment by teosarca** [comment]
Note to IT:
* full regression swing/webui is required

**Comment by metasnw** [comment]
@teosarca I checked for the original case first and the problem still occurs.
When I receive the attribute was not inherited.
https://w101.metasfresh.com:8443/window/53009/1000035

**Comment by teosarca** [comment]
@metasnw pls try with a completely new manufacturing order.

NOTE: i did not migrate the data.

**Comment by metasnw** [comment]
@teosarca yes, tried that as well. I am now comparing the config to be 100% sure its correctly configured

**Comment by metas-rc** [comment]
IT
* Created a purchase order, set a tageslot datum ( this triggers lotNo setting; lotNo has IsTransferrWhenNull = ' Y' )
* Added a line for Carrots
* Completed the order
* Went to the material receipt candidate, performes Rceive HUs
* OK: The LotNo was set (235)
* Went to PP Order, created a new one, for a bom containg carrots, completed
* I selected issue/receipt
* Selected the co-product, performed " Issue" 
* => OK: The HU was issued, the lotNo was there, 235
* Selected main product and performed Receipt
* => : NOK: The lotNo is no longer there

![image](https://user-images.githubusercontent.com/16001442/26974986-8b7d1a4e-4d26-11e7-829c-281f52f5fc25.png)

**Comment by teosarca** [comment]
Finally i found out why.
That attribute is not in the PP_Order_ProductAttribute_Transfer dimension. See: https://w101.metasfresh.com:8443/window/540262/540004

I know it's not obvious at all but i have no idea how to make it more obvious.

PS: anyways i've improved the trace logging a bit

**Comment by teosarca** [comment]
Update: the query which i used to check it out was:
```
select
	pa.M_HU_ID
	, a.M_Attribute_ID, a.Value, a.Name, a.IsTransferWhenNull
	, pa.Value, pa.ValueNumber
	, exists(
		select 1
		from DIM_Dimension_Spec d
		inner join DIM_Dimension_Spec_Attribute da on (da.DIM_Dimension_Spec_ID=d.DIM_Dimension_Spec_ID)
		where InternalName='PP_Order_ProductAttribute_Transfer'
		and d.IsActive='Y' and da.IsActive='Y'
		and da.M_Attribute_ID=pa.M_Attribute_ID
	) as IsTransferable
from PP_Order_ProductAttribute pa
inner join M_Attribute a on (a.M_Attribute_ID=pa.M_Attribute_ID)
where PP_Order_ID=1000050
and a.IsTransferWhenNull='Y'
order by a.Value
```

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

*  Attributes that are flagges with isTransferrWhenNull and appear in the im spec of the pp_Order attributes are propagated in the issued and received HUs
* Regression: The attributes which do not respect the rule above are not propagated.
* Regression: The functionality from purchase order to Manufacturing order then to issued and received HUs works correctly.
