### ISSUE TITLE
Menu entry for M_ProductCategory window wrong

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1739]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the menu entry for M_ProductCategory Window points to the wrong window. window/540116 instead of window/144
#### Which are the steps to reproduce?
Open the menu (not on 1101) and see.
### What is the expected or desired behavior?
Let the menu entry show to window/144.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-ts** [comment]
Cherry-Picked to release branch using https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/154/

**Comment by metas-lc** [comment]
IT
webui
open Product Category window from menu => window 144 opens OK
open product category window from Product window, using zoom in => window 144 opens with the corresponding entry (in a new tab) OK
