### ISSUE TITLE
Translation for en_US in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1742]
### Is this a bug or feature request?
Feature Request
### What is the expected or desired behavior?
When User Language is en_US, then show all elements in WebUI in English Language.
Procedure; Start with going through each window in WebUI and add missing Translations in en_US Language.

**Comment by metas-mk** [comment]
Current Menu Tree in WebUI in english Language. Go through all entries and check all windows for untranslated elements.

WEBUI

CRM
New Business Partner
New Request
Business Partner
Request
Ausgehende Belege
Settings
Greeting
Ausgehende Belege Konfig
Payment Term
Partner Relation
Business Partner Group
Request Type
Vorgang Status
Ergebnis Vorlage

PRODUCT MANAGEMENT
New Product
Product
Attribute
Merkmals Satz
Bill of Materials
Discount Schema
Settings
Maßeinheit
Product Category

SALES
New Sales Order
Sales Order
Sales Order Candidates
Reports
Revenue Busines Partner

PURCHASE
New Purchase Order
Purchase Order
Bestelldisposition
Material Vorgang
MRP Produkt Info

PRICING
Neue Preisliste
Price System
Preisliste
Produkt Preise
Settings
Preis Schema
Preisberechnung

WAREHOUSE MANAGEMENT
New Warehouse
Warehouse
Warenbewegung

CONTRACT MANAGEMENT
Contract

MANUFACTURING
New Manufacturing Order
Manufacturing Order
Prognose
Materialdisposition
Settings
Produkt Plandaten
Produktion Arbeitsablauf
Produktion Arbeitsablauf Übergang
Produktions Ressource
Ressourcenart

FINANCE
New Payment
New General Ledger
Bankkonto
Bankauszug
Payment
Zahlung Zuordnungen
General Ledger
Dunning
Dunning Candidates
Buchungen
Settings
Steuersatz
Steuer Kategorie
Bank
Währung
Währungskurs
Mahnart

LOGISTICS
Tour
Tourversion
Liefertage
Distributionsauftrag
Packvorschrift
Packvorschrift Version
Packmittel
Handling Unit Editor
Settings
Distributions Konfiguration

MATERIAL RECEIPT
New Material Receipt
Material Receipt
Material Receipt Candidates
Leergut Rücknahme
Lieferanten Rücklieferung

BILLING
New Sales Invoice
New Purchase Invoice
Billing Candidates
Sales Invoice
Purchase Invoice
Settings
Terminplan Rechnung

SHIPMENT
New Shipment
Shipment
Shipment Candiates
Leergut Rückgabe
Kunden Rücklieferung

MANDANT/ ORGANISATION
Organisation
Mandant
Einstellungen
Organisationsart

SYSTEM
Role
User
Menu
User Dashboard
KPI
Belegart
Druck - Format
Beleg Nummern
Mein Profil
Actions
Initial Setup Wizard
Settings
Land, Region, Stadt

**Comment by metasnw** [comment]
consider these pending PRs as they are already translating windowS:
https://github.com/metasfresh/metasfresh/pull/1593
https://github.com/metasfresh/metasfresh/pull/1514

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Moving thid task back in Development. 
We usually create one task / window when we find cases of translations lacking.

**Comment by metas-mk** [comment]
Closing this issue. Translations have been done 1:1 in individual issues.
