### ISSUE TITLE
Layout Optimization of User Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1746]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
There are a few Optimizations to be done to User Window in WebUI
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Take out Name Field from Grid View. Add Login Field to Grid View.

![image](https://user-images.githubusercontent.com/13365687/26882306-46d0642e-4b9a-11e7-9ec8-2a508cb00c55.png)

**Comment by metas-lc** [comment]
IT
checked user window: name is not there anymore. Login is there OK
