### ISSUE TITLE
System Element overwrite on Window Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1752]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is possible to define System Elements on Column Level. These can be centrally maintained by the Translation Sync process. If you have generic columns e.g. C_BPartner_ID that can have different meanings depending on isSOTrx then you have to take out centrally maintained and Translate on your own.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
The concept of System elements is nice but not thought to the end. It would be nice to have a System Element overwrite possibility on Field Level, so one can define Window dependent meanings AND have them centrally maintained.

First rough ideas.

**Comment by teosarca** [comment]
Here are my 2 cents,

1. Remark that we have AD_Window.IsSOTrx.
I think, when propagating names & translations from AD_Element/AD_Column to AD_Field, the AD_Window.IsSOTrx shall be considered and in case IsSOTrx=N it shall copy the PO_Name instead of Name. (same for Description and Help).

PS: if the IsSOTrx is not enough we shall come up with a concept which allows defining AD_Element translations for each "functional context". e.g. a C_BPartner_ID might be named differently if it's in Sales, if it's in Purchase, if it's in Subscriptions etc.

2. We shall check current state and update the IsCentrallyMaintained flags everywhere (because we were not using that flag for a long time).
After the IsCentrallyMaintained is up2date, i remember there is a window where you can see not translated things (element, field etc). We shall use that to figure out what's pending to be translated.

**Comment by metas-mk** [comment]
Had a talk w/ @metas-ts about this. would be great to also have the other translatable elements like window, tab covered by system elements too.

**Comment by teosarca** [comment]
update: Had a talk with mark and we decided to go with the "AD_Element" approach.
Bellow it's a short concept.

----
AD_Element:
* make ColumnName not mandatory
* introduce "AD_Element_WithColumnName" validation rule which selects only those AD_Element(s) which have the ColumnName not null

AD_Column.AD_Element_ID - use AD_Element_WithColumnName validation rule

AD_Field:
* introduce AD_Name_ID column, not mandatory, which points to AD_Element table.
As soon as the user sets it, the AD_Field's Name, Description, Help is copied from that AD_Element. Also the AD_Field_Trl(s) are updated from that AD_Element. In case the AD_Name_ID is not set, it shall work as before (i.e. copied from AD_Column and AD_Column_Trl).
* drop IsCentralyMaintained flag, we will no longer use it

If user is changing an AD_Element or AD_ELement_Trl, the changes shall be propagated accordingly, i.e. the AD_Field.AD_Name_ID will be considered. See org.compiere.model.M_Element.afterSave(boolean, boolean)

**Comment by metas-ts** [comment]
Hi @metas-mk @teosarca @cristinamghita 
not sure it belongs here, *but* could Cristina also locate and comment out the code that updates/overrides 
`AD_Column.Note` and `AD_Column.Help` ? To me it's a major pain.
I would like to e.g. have a `C_BPartner_ID` column and set it to "Not-Foreign-Key" or "Not-Lazy" and add write a short info about it. 
wdyt?

**Comment by teosarca** [comment]
@metas-ts IMHO, for that case we would need another column (e.g. InternalNote or something), because Name, Description, Help have other usages.
wdyt?

**Comment by teosarca** [comment]
I also suggest to check and maybe delete following:
* org.compiere.process.SynchronizeTerminology process ... not sure if is up2date with what are we doing now. Might be that we just need to adapt it
* /de.metas.adempiere.adempiere.migration-sql/processes_post_migration/postgresql/02_SynchronizeTerminology.sql - legacy 

@metas-ts  @metas-mk  wdyt?

**Comment by metas-rc** [comment]
I checked if I can quickly apply my changes in org.compiere.process.SynchronizeTerminology but I couldn't. It's huge, ugly and completely hardcoded.
Please, check if it is still neded and let's drop it if it isn't.

**Comment by metas-lc** [comment]
IT
AD_Field and AD_Field_Trl are updated to what you have in element and element trl only if you add the AD_Name_ID before you save a new ad_field. If you add it after, AD_Field_Trl is not updated anymore. Only AD_Field is updated NOK

**Comment by metas-ts** [comment]
@teosarca i'm not sure if this is really important for this week's RC...do you know something I don't?
@metasnw , do you need it?

**Comment by metas-lc** [comment]
IT
1. made an element without column name. Also translated de_CH. Added description and help
2. added a new column in a table, e.g. testvalue
=> the fields like name, description and help took values from testvalue
3. press save
4. go to window and add this new field, press save
=> the fields like name, description and help took values from testvalue
5. add your element in name id
=> name, description and help are updated
6. go to field trl and select the one for de_CH
=> it's translated OK
7. update ad element and ad_element trl
=> ad_field is updated OK
=> ad_field_trl is not updated NOK
8. delete this new field and add a new one, exactly the same, but add your element before you save
=> field and field trl are translated OK
9. update ad element and ad_element trl
=> ad_field is updated OK
=> ad_field_trl is not updated NOK

**Comment by metasnw** [comment]
@metas-ts I dont need it now

**Comment by metas-rc** [comment]
Update: After we set the sys configs from here http://docs.metasfresh.org/developers_collection/en/getting_started_db_en.html into the db we were testing on and we also got access to the migration script logs folder, the problems did not occur any more. Now the field translations update correctly.
