### ISSUE TITLE
New Window for Material Transactions in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1753]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window to see Material Transactions in WebUI
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Provide a Window to filter and select Material Transactions in WebUI. Allow the user to jump/ zoom-to detail windows. Filtering shall be possible per default on BusinessPartner, Product, Transaction type, Movement Dates.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
