### ISSUE TITLE
New Window Shipper Transportation in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1757]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window Shipper Transportation is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window for Shipper Transportation in WebUI and add ti WebUI menu in Logistics.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
