### ISSUE TITLE
HUTransform might pick the wrong capacity definition

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1759]
### Is this a bug or feature request?

Bug

### What is the current behavior?

When loading stuff into HUs, the system gets the capacity from a `M_HU_PI_Item_Product` record..

It finds that record via  `M_Product`, `M_HU_PI_Item` and 'C_BPartner` 

if is are more than one matching `M_HU_PI_Item_Product` it orders them and takes the first one...

Now the problem is, that when the user started the "transform" action, she actually selected one very  specific `M_HU_PI_Item_Product` ..and expect that capacity of tha one to be used.

#### Which are the steps to reproduce?

see the private customer specific issue description

**Comment by teosarca** [comment]
rolled on w101

**Comment by teosarca** [comment]
isn't this related to https://github.com/metasfresh/metasfresh-sp80/issues/102 ?

**Comment by metas-lc** [comment]
IT
1. Go to Product window and select one (P001)
2. add 3 new M_HU_PI_Item_Product_IDs (cu-tu zuordnung): 
1 TU A infinite capacity
2 TU B - 1 infinite capacity, 1 capacity 1
3. create a purchase order with P001 and complete it
4. go to receipt candidates and select your line. Choose Receive CUs with qty
5. qty CU 20
6. select the CU and choose transform: CU on new TU, select TU A (one with infinite capacity), qty 3
=> you know have the old line with qty 17 and the new lines with qty 3: 1 TU A, 3 CU OK
7. press done and receive CUs with qty again (same qty 20)
8. transform: put it on new TU: TU B infinite capacity, qty 3
=> you know have the old line with qty 17 and the new lines with qty 3: 1 TU B, 3 CU OK
9. transform again the line with CU - put it on new TU: TU B capacity 1, qty 3
=> you know have the old lines with qty 14 and TU B CU 3,  and the new lines with: 3 TU B, 1 CU each OK
10. repeat the same cases for TU B after you go to Product window and set your bpartner on the one with infinite capacity
=> works the same OK
11. repeat the same cases for TU B after you go to Product window and set your bpartner on the one with capacity 1, and no bpartner on the one with infinite cap
=> works the same OK
12. repeat the same cases for TU B after you go to Product window and set your bpartner on both
=> works the same OK
13. repeat the same cases for TU B after you go to Product window and set another bpartner on the one with infinite capacity, and no bpartner on the one with capacity 1
=> while you do transform: CU on new TU, you cannot select TU B with infinite capacity OK
=> rest works the same OK
14.  repeat the same cases for TU B after you go to Product window and set to both no bpartner and make the infinite capacity one finite, qty 2, and the one with qty 1 infinite
=> works the same, but when you select TB 1 capacity 2 it puts qty 2 per TU. OK
