### ISSUE TITLE
Adjustment of advanced edit in Doctype Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1765]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit definition of Doctype window is in the first main section in the first column.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Move the advanced edit to an own Advanced Edit section w/ 1 column.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
