### ISSUE TITLE
New Window Board in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1767]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window "Board WebUI" is not available in WebUI menu.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Create the "Board WebUI" Window Layout and add to WebUI menu for Sysadmin role.

**Comment by teosarca** [comment]
to be implemented after https://github.com/metasfresh/metasfresh-webui-api/issues/441 is rolled out

**Comment by teosarca** [comment]
rolled out the first increment of https://github.com/metasfresh/metasfresh-webui-api/issues/441

**Comment by metas-rc** [comment]
Results of IT

Tested on webui.

*OK: The window was introduced in the menu
* NOK: There are some problems with it. Followup created: https://github.com/metasfresh/metasfresh/issues/3192
