### ISSUE TITLE
New Window for KPI Widgets in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1770]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window for KPI Widgets is not defined for WebUI yet. Only the initial Setup is shown.
#### Which are the steps to reproduce?
Open the window in WebUI and see.
### What is the expected or desired behavior?
Configure the KPI Widget Window for WebUI, including 2-column Layout, Sidelist, Grid View, Advanced Edit and Subtabs.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
