### ISSUE TITLE
Add Description Field to User Dashboard

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1773]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Description Field in User Dashboard Window
#### Which are the steps to reproduce?
Open the Window and see.
### What is the expected or desired behavior?
Add a Description Field to the table column and add the Field in WebUI Dashboard Window underneath Name in column 10 in an own Element Group.

![image](https://user-images.githubusercontent.com/13365687/27001131-467463de-4dc2-11e7-9f96-c8a4939e73de.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
