### ISSUE TITLE
New Window/ Tab for KPI Field Translation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1778]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to translate the KPI Field Names in other languages via WebUI Window because it is on 3rd Level hierarchy.
#### Which are the steps to reproduce?
Open the KPI Window and see.
### What is the expected or desired behavior?
Move the Translation Tab to the second Level and Join to KPI ID or create another window which only shows the filtered Translation for one specific field.

**Comment by metas-mk** [comment]
After the talk with Teo. Will proceed w/ creating a new window for the Field Translation, allowing the user to Zoom-To referenced window to maintain the Translations.

**Comment by metas-mk** [comment]
Note to IT: Testing this new window needs this one to be done first https://github.com/metasfresh/metasfresh-webui-api/issues/449

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
