### ISSUE TITLE
New Window for Flatrate Conditions in Webui

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1786]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there ist not Window for Flatrate Conditions Maintenance in WebUI
#### Which are the steps to reproduce?
Open the WebUI Menu and see
### What is the expected or desired behavior?
Create the Window Flatrate Conditions (C_Flatrate_Conditions, Vertragsbedingungen) in WebUI and add to WebUI menu in Contracts Group.

**Comment by metas-mk** [comment]
@metas-rc Thanks for the info. Fixed. Should work now.

**Comment by metas-rc** [comment]
Result of IT

Tested on webui

The problem described in the last IT results persists. Please, check again

**Comment by metas-mk** [comment]
@metas-rc just tries on w101 and seems to work. can u pls recheck and create a followup w/ your test case. thx.

**Comment by metas-rc** [comment]
Results of IT

* OK: Now the window Contract Terms is fine and I can add lines etc.  Maybe it was a rollout issue or maybe the problems solved meanwhile.
