### ISSUE TITLE
New Window for Quality Inspection Conference Results in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1787]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is not Window for Quality Inspection Conference Results Maintenance in WebUI
#### Which are the steps to reproduce?
Open the WebUI Menu and see
### What is the expected or desired behavior?
Create the Window Quality Inspection Conference Results (M_QualityInsp_LagerKonf, Lagerkonferenz) in WebUI and add to WebUI menu in Contracts Group.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing

NOTE: The window is named "Storage Conference Terms" and is under the id of 540230.

OK: The windows in webui and swing are similar. -> OK
I was able to create new entry and add new version -> OK
