### ISSUE TITLE
New Window for Flatrate Transition in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1788]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Flatrate Transition Maintenance in WebUI
#### Which are the steps to reproduce?
Open the WebUI Menu and see
### What is the expected or desired behavior?
Create the Window Flatrate Transition (C_Flatrate_Transition, Vertragslaufzeit) in WebUI and add to WebUI menu in Contracts Group.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest

The window for Flatrate Transition ( Vertragsfaufzeit)  is correctly added to the webui.

I can find it if I search it in dashboard.

It is fully functional.
