### ISSUE TITLE
New Window for Calendar in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1790]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Calendar Period Maintenance in WebUI
#### Which are the steps to reproduce?
Open the WebUI Menu and see
### What is the expected or desired behavior?
Create the Window Calendar Period (C_Period, Periode) in WebUI and add to WebUI menu in Finance Group. Also add the standalone Window to new Period Window.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
