### ISSUE TITLE
fix jasper document for vendor returns

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1793]
### Is this a bug or feature request?
bug
### What is the current behavior?
jasper doesn't open because sql fails
#### Which are the steps to reproduce?
open a vendor return inout and print preview
sql is not up to date with latest change of columns
### What is the expected or desired behavior?
print preview should work

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
quickly checked: jasper for vendor returns opens and works fine
