### ISSUE TITLE
Advanced Edit: Business Partner Main View and Customer

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1794]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit Screens are not optimized.
### What is the expected or desired behavior?
Create an Advanced Edit Prototype w/ Business Partner Window Main View and Advanced Edit, and also for Customer Subtab.

Belongs to main Issue: https://github.com/metasfresh/metasfresh/issues/1781

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
