### ISSUE TITLE
Prototype Dashboard for Board frontend development

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1798]
### Is this a bug or feature request?
Feature Request
### What is the expected or desired behavior?
A Prototype Dashboard is needed for testing purpose during Board Frontend development. Create a Sales Opportunity dashboard with c_order table items and prototype Card Layout.

**Comment by metas-mk** [comment]
Belongs to this main Issue: https://github.com/metasfresh/metasfresh-webui-api/issues/441

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Nothing to Test at the moment. The prototype Dashboard is created and put to WebUI menu. Closing/ Done.
