### ISSUE TITLE
Translation of My Profile Window to en_US

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1801]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, not all fields are translated to en_US in My Profile Window.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
To Have all Fields translated.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/1742

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
