### ISSUE TITLE
picking terminal is not opening

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1802]
### Is this a bug or feature request?
bug
### What is the current behavior?
picking terminal is not opening
#### Which are the steps to reproduce?
menu - open picking terminal
=> error https://pastebin.com/cnDRiNhJ

### What is the expected or desired behavior?
should open without errors

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* opened the window Kmmissionier Terminal (prototype) : https://w101.metasfresh.com:8443
* OK: It opened with no error.
