### ISSUE TITLE
Add the new Picking Window to WebUI Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1805]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, the new Picking Window is not added to the WebUI Menu.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the new Picking Window to the WebUI menu.

Here is further information about the window to add. https://github.com/metasfresh/metasfresh-webui-api/issues/424

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
