### ISSUE TITLE
Sometimes i get empty window when i zoom to related sales invoices of a given sales order

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1808]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
Easily to check on webui, open an order (try with several ones), document references, zoom to invoices. For some of them, the view will be empty.
Also pls check a test case where your invoice is aggregated from multiple orders (might be that's the actual case).

### What is the expected or desired behavior?
If on document references, the counter says "X" then it shall be X rows in your view.

### Note to IT:
Pls do regression tests (also on Swing!) and check other document references.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


For any document I tried, old or new, the references had the same number as many they were on the list. But I will keep this task in testing and also suggest to be checked during e2e.

**Comment by metas-lc** [comment]
tested on swing as well. Works fine
