### ISSUE TITLE
New User Query Window on WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1809]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility on WebUI to define the User Queries needed for Filter configuration.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have a generic window that enables to define User Queries by an admin (first step).

**Comment by metas-lc** [comment]
IT
new window: User Query
you can create a new one
TL: important, mandatory
TR: isActive
BR: org, client
Translations: YES
