### ISSUE TITLE
Responsible mandatory Field missing in Request

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1810]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The mandatory Field "Responsible" is missing in Request window.
#### Which are the steps to reproduce?
Open, create new and see.
### What is the expected or desired behavior?
Show the responsible field again.

**Comment by metas-ts** [comment]
cherrypicked into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/172/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing.

The Responsible (Sales_Rep_ID) field is displayed in the request window.
