### ISSUE TITLE
Hide Processed flag from all M_InOut/Returns windows (webui)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1814]
### Is this a bug or feature request?
Bug

### What is the current behavior?
At the moment the Processed flag is displayed in webui's customer/vendor/empties returns windows.
That's not OK because user can click on it, so it flags the document as processed, which is
* not OK because the Processed flag shall be managed by the API (via completing, reversing, reactivating the document)
* as soon as you click it, the document becomes readonly and you cannot unclick it.

#### Which are the steps to reproduce?
Check those windows, e.g. https://w101.metasfresh.com:8443/window/540322

### What is the expected or desired behavior?
The Processed flag shall not be present in those windows, or at least shall be always readonly.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

OK: The 3 inout windows don't have the processed flag either before completion or after.
