### ISSUE TITLE
Fix the webui layout for Vendor returns (Lieferanten Rücklieferung) window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1816]
### Is this a bug or feature request?
Bug

### What is the current behavior? / Which are the steps to reproduce?
See https://w101.metasfresh.com:8443/window/53098 .
The layout looks ugly

### What is the expected or desired behavior?
Should look sexy ;)

NOTE: Found while fixing https://github.com/metasfresh/metasfresh-webui-api/issues/332#issuecomment-308444084

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
layout fixed. Now lookd similar with other windows. OK
