### ISSUE TITLE
Allow to switch off transmission to Procurement UI via PMM_Product

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1817]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, all Products are transmitted to Procurement UI when Contracts exist.
#### Which are the steps to reproduce?
Try it and see.
### What is the expected or desired behavior?
Have the Possibility in PMM_Product to switch off the transmission globally, although contracts are existing.

**Comment by teosarca** [comment]
Fixed by allowing the user to deactivate a PMM_Product even  if it has a running contract.
When user will untick the flag, the PMM_Product will be sent to procurement server but the "procurement product" will be marked as Deleted.

**Comment by teosarca** [comment]
rolled on w101 (but does not matter)

**Comment by metas-ts** [comment]
Cherry-Picked to the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/175/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on procurement webui. OK
