### ISSUE TITLE
make new pricelist a sales pricelist by default

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1819]
### Is this a bug or feature request?
feature

### What is the current behavior?
a new pricelist is automatically a purchase pricelist

#### Which are the steps to reproduce?
1. go to window pricelist
1. create a new one
1. check issotrx

### What is the expected or desired behavior?
issotrx = Y

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
swing and webui: creating a new pricelist has issotrx on Y by default OK
