### ISSUE TITLE
New Procurement Windows in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1823]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Procurement Windows are missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the following Procurement Windows for WebUI and add to WebUI Menu in Procurement Group
a) PMM_week
b) PMM_weekReport_Event (Reports)
c) PMM_Product
d) PMM_QtyReport_Event (Reports)
e) PMM_Message

**Comment by metas-ts** [comment]
Cherry-Picked to the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/174/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
