### ISSUE TITLE
New Request for Quotation Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1824]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Request for Quotation (RFQ) Window is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the RFQ Windows for WebUI and add to WebUI Menu in Procurement Group

**Comment by metas-ts** [comment]
Cherry-Picked to the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/173/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
