### ISSUE TITLE
Disable Quickstart, Admin and System Administrator Roles for WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1825]
### Is this a bug or feature request?
feature

### What is the current behavior?
both roles are displayed but are not optimized for webui

#### Which are the steps to reproduce?
1. logon with user metasfresh
1. pick one of the roles

### What is the expected or desired behavior?
should be available in java client but not web

**Comment by teosarca** [comment]
rolled on w101

**Comment by teosarca** [comment]
tested on w101, works.

This task was developed based on feature https://github.com/metasfresh/metasfresh-webui-api/issues/376
