### ISSUE TITLE
Different RFQ Windows in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1829]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, different Request for Quotation (RFQ) Windows are not integrated into WebUI yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the RFQ Windows for WebUI and add them to the WebUI Menu in Procurement Group
a) C_RFQ_Topic
b) C_RFQResponse
c) C_RFQReponseLine

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
