### ISSUE TITLE
Add filter for HU status in handling unit editor

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1830]
### Is this a bug or feature request?
feature

### What is the current behavior?
no way to see only the active HUs or search for HUs

#### Which are the steps to reproduce?
open window Handling Unit and see

### What is the expected or desired behavior?
make field HU status and value search field

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

* Went to Handling Units editor, opened the default filter
* OK: It has Gebinde status option
* OK: Selecting a status in the list then pressing filter => Only the HUs of that status are displayed 
* OK: This filter works well also when paired with other filters from Default.
