### ISSUE TITLE
Adjustments for Empties Receive Window WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1836]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the empties receive window is not nicely set to the 2-column layout in the subtabs. Also, the validation rule set to products seems not to be the one used in empties return window.
#### Which are the steps to reproduce?
Open the window and try and see.
### What is the expected or desired behavior?
Adjust the window subtabs to the look&feel of empties receive window and add the proper validation rule to product field.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-ts** [comment]
cherry-picked into the branch `release_gh1306`

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
