### ISSUE TITLE
New Window for Period & Period Control in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1839]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Subtabs of Period and Period Control are currently on level 2+3 of the Calendar Window and cannot be shown Calendar Window.
#### Which are the steps to reproduce?
Open the Calendar Window and see.
### What is the expected or desired behavior?
Create a new Window called Calendar Period, with a subtab Period Control.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
