### ISSUE TITLE
internal: refactor and improve PO translation code

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1840]
### Is this a bug or feature request?
feature request

### AIM
* when changing the translation for a given record, don't set the IsTranslated=N  for all the translation records. Just do nothing
* technical: implement a way to have more translation update strategies (used programmatically)
* technical: the PO translation code shall be much more cleaner and organized

### Note to IT
* full regression test on translations is required

**Comment by metas-lc** [comment]
IT
- settings -> change language => window refreshes, fields, data , everything is translated OK
- check notifications => not translated (they are translated only after you refresh) NOK task:
- check my profile (3 dots) => partially translated  (they are translated only after you refresh) NOK same task as above
- check the menu => translated OK
- go to other windows => fields and data are translated. Same for included tabs OK
