### ISSUE TITLE
Customer Returns Layout Improvement

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1845]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the usability for Line recording in Customer Returns window is not good.
#### Which are the steps to reproduce?
Open the window and edit a line.
### What is the expected or desired behavior?
Optimize the customer returns layout in the Advanced edit of lines.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
