### ISSUE TITLE
Material Receipt Dispo window sequence OrderedQty CU vs. TU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1854]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Sequence of Fields in FGrid View for OrderedQty CU vs. TU is not harmonized in Window Material Receipt Dispo.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Have the same sequence of ordered/ moved for TU and CU.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
material receipt candidates =>
quantity ordered TU, moved TU qty, ordered quantity , moved qty OK
