### ISSUE TITLE
Translation de_DE for static UI components in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1857]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In the issue, https://github.com/metasfresh/metasfresh-webui-api/issues/443 the infrastructure was created. The German translations (base language) are missing for the new messages.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Translate the base values for the ad_messages.

**Comment by metas-mk** [comment]
@metas-ts can u please add this one to the release candidate 5.14 (2017-25). It belongs to this https://github.com/metasfresh/metasfresh-webui-frontend/issues/861 frontend issue.

**Comment by metas-ts** [comment]
@metas-mk done
cherry-picked into the `release`branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/179/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested: The "New" Translation is missing. Corrected and committed.

**Comment by metas-mk** [comment]
Tested. Works as required. Possible further changes will be done in follow-up issues. Done/ Closing.
