### ISSUE TITLE
Export all webui AD_Messages from w101

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1859]
Export all webui AD_Message(s) from w101 and create migration scripts.
The webui messages are those which start with "webui.".

This task relates to https://github.com/metasfresh/metasfresh/issues/1857

**Comment by metas-ts** [comment]
cherry-picked into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/180/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
