### ISSUE TITLE
Make documentNo readonly in Payments (and other document types)

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1860]
### Is this a bug or feature request?
* Feature request
### What is the current behavior?
* Currently I can manually set a documentNo to a payment.
* Problem: I can ad a document no that is the same as an existing one. This could create confusion. 
#### Which are the steps to reproduce?
* Create a payment with a docno, complete it.
* Create a new payment with the same doctype, partner, docno, complete it.
* => No error/warning message, the second document completes correctly.
### What is the expected or desired behavior?
* The documentNo field shall be readonly. 

Note: Check if this also fits with other document types.

**Comment by metas-rc** [comment]
Followup for https://github.com/metasfresh/metasfresh/issues/1362

**Comment by metasnw** [comment]
I am experiencing the same problem with sales order documentno.
I tried to set it to isreadonly=Y to solve the problem but its still updatable

**Comment by metasnw** [comment]
readonly logic fixed by metasfresh/metasfresh#1860
on top we should think about a unique contraint for payment documentno as we have it in other windows

**Comment by metas-rc** [comment]
I checked other documents

I found that in Invoice, there is a unique constraint on documentno, c_doctype_id, c_bpartner_id.
Also there is one on c_bpartner_id, documentno , c_doctypetarget_id

In C_Order, there is also a unique index on documentno , c_doctype_id, c_bpartner_id.

In M_InOut there is no  unique index on documentno.

**Comment by metas-rc** [comment]
In invoice, the documentNo is not updatable. This means that, at the beginning, before the invoice is saved, you can change the docno to another string and it will be correctly saved as that, as long as the unique index is fulfilled.

**Comment by metas-lc** [comment]
IT
tried to make 2 payments with the same documentNo => can't OK
a problem could be that IsUpdateable is ignored in webUI. But it doesn't make sense in webui, because you don't have "Save" button.
another issue, is that the red line is missing when the document is not saved (e.g. set a documentNo that already exists for doctype and bpartner). Task https://github.com/metasfresh/metasfresh-webui-frontend/issues/1707
