### ISSUE TITLE
add is webui role to advanced edit of role window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1865]
### Is this a bug or feature request?
feature

### What is the current behavior?
checkbox is missing and can only be set via sql and java client

#### Which are the steps to reproduce?
1. open window role
1. try to find "is webui role"

### What is the expected or desired behavior?
have it advanced edit

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
go to Rolle window, advanced edit => WebUI Rolle checkbox is there OK
