### ISSUE TITLE
restore old ordercheckup jasper files

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1867]
### Is this a bug or feature request?

Feature

**Comment by metas-ts** [comment]
We have now the former jasper file versions in the ordercheckup folder. The barcoded ones are not used right now.
They were moved to a new folder named ordercheckup_with_barcode

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
print preview an order checkup => old ordercheckup jasper version is now set, instead of new barcode one OK
