### ISSUE TITLE
WebUI Default Filter missing in Windows compared to Swing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1872]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Swing default Filters are missing in various Windows of WebUI.
#### Which are the steps to reproduce?
As example. Currently, it is not possible to Filter via Document No in Purchase Invoice. Open the window and see.
### What is the expected or desired behavior?
Check which implicit default Filters exist in Swing and set these to "searchcolumn" in Application Dictionary.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
