### ISSUE TITLE
Material Receipt multiselect Close Lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1874]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to process/ close Material Receipt Dispo Lines w/ multi-selection.
#### Which are the steps to reproduce?
Open the window, try and see.
### What is the expected or desired behavior?
Allow the multi-selection of Material Receipt Dispo Lines and use the Close/ Processing Action for the selected lines.

**Comment by metas-lc** [comment]
IT (swing and webui)
I can open (webui) and close (webui and swing) multiple rows at the same time OK
To see the lines are processed you need to refresh. You cannot see it's processed in doc view. We already have an issue for that https://github.com/metasfresh/metasfresh-webui-api/issues/398
