### ISSUE TITLE
New Order Control Report cut off left/ cut off right

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1875]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Sometimes the new Order Control Report ist printed out cut off left/ cut off right, on the same printer.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Don't cut off any side.

![image](https://user-images.githubusercontent.com/13365687/27432002-c1c2a948-574e-11e7-999b-305a3dc871bf.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Talked with Mark. This task will be tested by our customer.
