### ISSUE TITLE
New CU Labels

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1876]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are no CU Labels in metasfresh. 
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create default CU Labels for produced Goods in metasfresh manufacturing.
5,5 cm width
10cm height

**Comment by metas-lc** [comment]
note for IT:
task is not done yet. Please put it back in dev

Remaining todo: add temperature, best before date and complete lot-nr. Check also if properties work fine..

**Comment by metas-lc** [comment]
changed the barcode to be able to integrate. After IT will need it back for the same issues above

**Comment by teosarca** [comment]
update: fixed jasper compile errors and now i am putting it back to dev as @metas-lc advised.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15:

* got an error when printing the CU label from PP_Order window: 
There was an unexpected error (type=Bad Request, status=400).
Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: "540802,PDF": NOK
* if no error, then the CU label is an empty PDF: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15:

still get an error when printing the CU label from PP_Order window: checked with lc, CU-EAN was missing; but label should work without that as well: NOK

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* CU label displayed correctly, no errors, no empty pages: OK
* including all info about product: name, no., ingredients etc. (translations where available): OK
