### ISSUE TITLE
Translations de_DE for Handling Unit QuickActions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1877]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, some of the Handling Unit QuickActions are not translated in baselanguage de_DE.
#### Which are the steps to reproduce?
Open the HU Ediotr, select a line, Open the QuickAction dropdown list.
### What is the expected or desired behavior?
Translate the Entries to de_DE.
![image](https://user-images.githubusercontent.com/13365687/27433400-dd92ba9a-5754-11e7-88f0-de0a4c7a1582.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
log in with en => the names are like in the picture above OK
log in with de => the QuickActions are translated in de OK
