### ISSUE TITLE
assign role webui to user IT

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1882]
### Is this a bug or feature request?
feature

**Comment by metas-ts** [comment]
cherry-picked into the `release` branch

**Comment by metas-ts** [comment]
also CPed into `release`..

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

I logged in with the user IT => All went fine, I was able to connect and have access to all webui components of other users with role Webui.
I checked the roles of user IT => webui among them.
