### ISSUE TITLE
make sure no bookmarks for user metasfresh so fallback menu is displayed

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1884]
### Is this a bug or feature request?
bug

### What is the current behavior?
one bookmark is shown to window menu

#### Which are the steps to reproduce?
log on with user metasfresh on 5.14

### What is the expected or desired behavior?
all menu items are displayed

**Comment by metas-ts** [comment]
cherry-picked to `release` branch

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
- was already tested and works fine OK
- when there is no bookmark the entire menu is shown. When you have bookmark(s) only those windows are shown + dashboard and browse whole tree OK
