### ISSUE TITLE
Harmonize the Shipment Window to our current Look&Feel concept

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1890]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Shipment Window looks a little bit untidy and unstructured w/ the dangling primary layouit. 
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Harmonize the Shipment Window to our current Look&Feel concept.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
shipment window is harmonized to our current Look&Feel OK
