### ISSUE TITLE
Default Doctype for Shipment Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1893]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when opening the window Shipment in webUI and creating a manual Shipment Document, the Doctype as mandatory Field has to be filled.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Set a Default value for the Doctype, so that the Field is filled initially.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest

When creating a new shipment it has the deffault doctype already set (Lieferchein)
Also, the document number is correctly set based on the sequence of the Lieferchein doctype.
When changing the doctype to "Lieferchein indirect" the document number changes accordingly.
