### ISSUE TITLE
Overhaul the Product Planning window and subtabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1896]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Product Planning is not adjusted to the primary Layout w/ separate 1-column configuration. Additionally, the Product Planning Subtab data is somehow unstructured.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Adjust the Advanced Edit for main data and enhance the look&feel of the subtab data.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
Product Planning is adjusted to our look and feel
