### ISSUE TITLE
Migration Script for "Select all lines count"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1900]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the "Select all lines" count does not work because of a translation issue.
Should be "view.selectAllItems.caption": "Select all %(size)s items" not "Select all %(size) items"
#### Which are the steps to reproduce?
Open any window in Grid view and press the button "Select all lines"
### What is the expected or desired behavior?
The Button shall show the next message and add a number of lines that can be selected.

Belongs to this issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/925

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.

**Comment by metas-ts** [comment]
Cherry-picked into `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/186/
