### ISSUE TITLE
Support camt.054.001.04 explicitly

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#1903]
### Is this a bug or feature request?
feature

### What is the current behavior?
currently only camt.054.001.06 is supported

#### Which are the steps to reproduce?
import a file with camt.054.001.04 in the header and the async package will fail

### What is the expected or desired behavior?
also camt.054.001.04 is supported

**Comment by teosarca** [comment]
rolled on w101

**Comment by metasnw** [comment]
successfully tested on port
