### ISSUE TITLE
"Wareneingangsetikett LU (Jasper)" prints >200 pages

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1905]
### Is this a bug or feature request?

Call it feature and le me film how the user reacts;-)

### What is the current behavior?

When receiving a HU which contains TUs with 30 different products (herbs in this case) in them, the system prints "a lot" of paper

#### Which are the steps to reproduce?

* We'll get the document and can the see for ourselves
* I'll also think i can obtain the PDF, M_HU_Ids etc from the live DB

### What is the expected or desired behavior?

Not sure, but i guess we need something way south of 200 pages :-)

**Comment by metas-ts** [comment]
i had problems testing this with my local DB..
i'm going to do "dev-testing" as soon as it's rolled out

**Comment by metas-ts** [comment]
Cherry-picked to release_gh1306, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/188/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-ts** [comment]
how to IT:

* you can make a purchase order with at least two different lines..and small quantities
* then in "material receipt candidates" choose "receive CUs" and put the CUs into one TU and put that TU onto one LU
* then make the receipt
* that way, on the receipt, you have multiple `M_HU_Assignment`s which have the same top level HU.
if you achieved this and still get only one label per product, you are fine

**Comment by metas-rc** [comment]
Results of IT


*Tested the above steps for HUs created on both webui and swing.
I only got 1 page per product. -> OK

Wasn't able to switch on the auto print functionality. To be verified if it still works.

**Comment by metas-rc** [comment]
Talked with Tobi and we can close this. Movign it to done also.
