### ISSUE TITLE
memory issue related to swing-client picking terminal

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1911]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
added the fix or improvement to the following branches
* `gh1911-mf`: the normal task branch
* `release_20170620-hf`: based on a past release, can be isntalled at the user in question, to test

**Comment by metas-rc** [comment]
I talked with Tobi and there is nothing to be tested. Moving this task directly in Done.
