### ISSUE TITLE
Customer return from HUs coming from Verdichtung POS don't have the right quantities

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#1912]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Customer return from HUs coming from Verdichtung POS don't have the right quantities
#### Which are the steps to reproduce?
* Create a sales order with 3 TUs containing 10 kg of product each
* Go to Kommissionier Terminal, put 10 kg on a slot using Hinzuf, close the slot
* Put the other 20 kilos, one by one, on another picking slot, using hu=inzuf, closr the slot
* Go to verdichtung pos, select the 2 HUs, select a shipper transportation
* Create shipment, complete it
* Perform "Return From Customer" for both HUs
* => NOK: The Customer return only has 1 in qtyEnteredTU and in Qty of the TU line.
### What is the expected or desired behavior?
* The qtys shall be the according to what was selected in the Editor. In my case, 2 TUs

Followup for #1869

**Comment by metas-ts** [comment]
Cherry-picked into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/191/

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
tested the case above => got qtyTU =2 OK

regression
- manual customer return OK
- return from shipment swing OK 
- return from shipment webui - you can't use the process: Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Assumption failure: Parameter instance is not null

but it doesn't look like it's task related so i'll rpobably create a new issue for that
