### ISSUE TITLE
Additional static element Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1919]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are new static element captions available that are not translated for WebUI.
#### Which are the steps to reproduce?
Check the messages starting with value "webui." and search for ones with english message Text.
### What is the expected or desired behavior?
Translate them.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
checked only in database and found the following hat didn't have en trl:
select * from ad_message where ad_message_id in (544491,544486,544487,544490)

created follow-up https://github.com/metasfresh/metasfresh/issues/2758
