### ISSUE TITLE
ESR Line AcctDate not set error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1924]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when creating Bank Statements via ESR Payments import process, it leads to an error that the Accounting Date is not set.
#### Which are the steps to reproduce?
Import ESR. Complete. Create Bankstatement. Import ESR. Error.
### What is the expected or desired behavior?
The import shall be possible. The Accountingdate shall be set in ESR Line.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-ts** [comment]
tested and works
