### ISSUE TITLE
New Window for C_Allotment in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1925]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is now Window for C_Allotment in WebUI menu.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a window for C_Allotment

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing.

The window is similar in both versions.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

The email works only for one address, not for 2 addresses separated by ";"
