### ISSUE TITLE
Change Column Reference of C_Allotment_ID to search

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1926]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Column Reference of C_Allotment_ID is List. It's hard to find the allotment you need with a lot of entries.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Change the Reference to Search and autocomplete instead.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
go to material tracking, check Allotment_ID => it's search field OK
