### ISSUE TITLE
Translate & export webui messages (round 2)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1929]
The aim of this task is to take care of newly introduced/changed webui AD_Message(s), i.e. those AD_Message which start with "webui." prefix.

Below, i will link frontend tasks/comments were webui messages were add/changed.

**Comment by metas-mk** [comment]
Exporting current menu from w101. Creating a Testcase on w101 and importing again, to ensure that the workflow works properly. After that preparing the migration scripts.
