### ISSUE TITLE
Menu Translations for Language en_US

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1933]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Ther are a lot of Menue entries which are not translated to en_US yet.
#### Which are the steps to reproduce?
Open with user Language en_US set and check.
### What is the expected or desired behavior?
Translate all WebUI Menue entries to en_US

**Comment by metas-rc** [comment]
Things that are not yet translated in the menu: 

* Static felds: 
* Einstellungen
* ÜBERSETZUNG
* MANDANT/ ORGANISATION 
 Windows:
* Asynchrone Verarbeitungswarteschlage
* ESR Zahlungsimport

**Comment by metas-lc** [comment]
IT
Static felds:
settings is translated oK
ÜBERSETZUNG  NOK
MANDANT/ ORGANISATION NOK
Erweiterte Fenster NOK
Einstellungen NOK

Windows:
Prozess Revision
Druck Warteschlange
Drucker
Drucker Zuordnung
Asynchrone Verarbeitungswarteschlage
Kommissionier Fach Trx


created follow-up https://github.com/metasfresh/metasfresh/issues/2756
