### ISSUE TITLE
Adjust Window Greeting in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1938]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Greeting Window does not have the 2-column Layout yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Layout. Add the Client Column in Grid View.

**Comment by metas-lc** [comment]
IT
Greeting Window has the 2-column Layout OK
Client Column is in Grid View OK
