### ISSUE TITLE
Adjust the Business Partner Relations Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1939]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Business Partner Relation Window does not have the 2-column Layout yet. Also, the Grid view is not prepared to current default.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Layout. Rearrange and add the Grid View.

**Comment by metas-lc** [comment]
IT
Business Partner Relations Window has the right layout OK
