### ISSUE TITLE
Subtabs Layout for Business Partner Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1940]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Subtab Layout in Grid View and Advanced Edit in Business Partner Window ist not optimized.
(vendor, location, contact, bank account, print format, status)
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Subtab Layouts to the current best practice.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* All the included windows of the Partner are functional and respect our layout.

* Order of the included tabs:  Vorgange, Customer, Vendor, Location, Contact, Bank Account, Print Format, Statistic.

* I was able to fill in all the included tabs without errors.
