### ISSUE TITLE
Subtab Layout for Window Outbound Document

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1941]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Subtab Layout in Grid View and Advanced Edit in Outbound Documents Window is not optimized. (log)
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Subtab Layout of the log subtab to the current best practice.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

The included tab (Log) works fine and respects our best practice.

Found some problems while testing. Followup created: 
* backend issue: https://github.com/metasfresh/metasfresh-webui-api/issues/505
* frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1040
