### ISSUE TITLE
Payment Terms Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1942]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
The Advanced Edit Layout does not match to our current look&feel concept.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Advanced Edit view to our latest concept.

**Comment by metas-lc** [comment]
IT
 Advanced Edit Layout in Payment Terms Window matches to our current look&feel OK
