### ISSUE TITLE
Window Business Partner Group Advanced Edit

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1943]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Advanced Edit mode does not have a proper layout yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a proper Layout for Advanced Edit.

**Comment by metas-lc** [comment]
IT
Business Partner Group Advanced Edit looks fine OK
