### ISSUE TITLE
Request Type Window adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1944]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Advanced edit view is not created properly. Same for Subtab "update notification".
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the proper Layout for the elements mentioned above.

**Comment by metas-lc** [comment]
IT
Request Type Window adjustments are fine
