### ISSUE TITLE
camt54 import does not support multiple Ntrys

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1947]
### Is this a bug or feature request?

Bug

### What is the current behavior?

only the data from the first `<Ntry>...</Ntry>` is processed

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

* I got an xml cam54 file with 2 NTry sections.
* I imported the fine in a new ESR entry
* => OK: I got the lines from the both NTry sections ( in my case, teh sections were identical, so I got similar lines)
