### ISSUE TITLE
eMail Editor does not open anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1948]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The eMail Editor does not open anymore.
#### Which are the steps to reproduce?
Open Window Purchase Order. Press on eMail Button Icon in Window Menu for an existing Purchase Order.
### What is the expected or desired behavior?
Shall open.

![image](https://user-images.githubusercontent.com/13365687/27829591-94dafbd8-60c2-11e7-89b7-7e6cc911564d.png)

**Comment by metas-ts** [comment]
Probably a regression introduced here: https://github.com/metasfresh/metasfresh-webui-api/issues/456

**Comment by metas-ts** [comment]
Cherry-Piced the fix into `release` and `20170628-release-157-br`

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
checked on swing and webui, Window Purchase Order. Press on eMail Button => opens, no errors OK
