### ISSUE TITLE
Add Inventory Valuation Report to WebUI menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1949]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Inventory Valuation is not available in WebUI menu.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Allow starting the Inventory Valuation Report via WebUI menu. Add the report to warehouse/reports menu group.

**Comment by metas-lc** [comment]
IT
inventory valuation process is in menu in Warehouse management -> Reports .
Params: product, warehouse and date (date mandatory). 
run the report => works fine 
OK
