### ISSUE TITLE
Window for Swiss ESR Payment Import in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1951]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is nor window for Swiss ESR Payment Import in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the ESR Payment Window for WebUI and add to Finance/ESR Payment Import

**Comment by metas-lc** [comment]
IT
ESR Zahlungsimport window is in menu in finance OK
