### ISSUE TITLE
intern: option bind related processes to a particular window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#1952]
### Is this a bug or feature request?
FR

### What is the current behavior?
Atm you can link processes only to a given table.
From a window, when you check related processes (gear), all those which were linked to the table which window is displaying are fetched.

### What is the expected or desired behavior?
Be able to define that a given process shall be displayed for a given table (mandatory, as it is now) but optionally specify that it shall be only for a particular window.
![image](https://user-images.githubusercontent.com/1244701/27865502-781c17fa-619b-11e7-85ce-7c013761c384.png)

### Note to IT
* nothing to test. It would be tested indirectly on https://github.com/metasfresh/metasfresh-webui-api/issues/490
* just keep an eye on e2e: the gear processes shall work

**Comment by teosarca** [comment]
Required for https://github.com/metasfresh/metasfresh-webui-api/issues/490

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Moving to done. 

e2e was successful.
