### ISSUE TITLE
Different adjustments for Contract Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1954]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Contract Window in WebUI has a few topics to be improved.
a) Subtab Vertragsperiode Translation for en_US (Contract Periods)
b) Subtab Vertragsperiode Order by created desc
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
See improvements described above.

**Comment by metas-lc** [comment]
IT
Vertragsperiode are Ordered by created desc
but the translations are missing
