### ISSUE TITLE
Shipment Document sometimes shows 0 qty instead of correct movement qty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1958]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Shipment Document sometimes shows 0 qty instead of correct movement qty
#### Which are the steps to reproduce?
FurtherDetails to follow.
### What is the expected or desired behavior?
Shall show the correct qty in all cases.

**Comment by metas-ts** [comment]
this issue was not reprodcible anymore, also didn't happen any more.
we assume that the swing client crashed or was killed in an unfortunate moment
