### ISSUE TITLE
Add window asynchronous workpackage queue to webui

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1960]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
searched for "asynch" and also the tree and could not find it
#### Which are the steps to reproduce?
searched for "asynch" and also the tree and could not find it
### What is the expected or desired behavior?
have the window there so you can check as admin why documents could not be created

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing (in comparison)

* The windows are similar, same information is displayed in both -> OK

The only difference is that the "Statistic"  field group is only displayed in swing version but not in webui.
