### ISSUE TITLE
AD_BoilerPlate variables not resolved in Email editor

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#1961]
### Is this a bug or feature request?
Bug

**Comment by metas-rc** [comment]
Results of IT

On webui the boilder plate field is not displayed in the email window. WHen it is needed, we shall retest this on webui too.


Tested on swing

Create a document, complete it. Open email for it, select a boilerplate that contains variables. The email contains the values of those variables (e.g. the document number) => OK
