### ISSUE TITLE
Adjustment on Average Purchase Prices Function

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1969]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the columns receiptdate and documentno are not returned
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Return the columns receiptdate and documentno too.

**Comment by metas-ts** [comment]
Note that the function returns a table with german column names. but i guess the win of this issue was to salvage it from a customer DB and add it to the repo to start with (in additionn to adding the fro columns)..so i guess it's fine until someone actually *needs* translated columns

**Comment by metas-lc** [comment]
nothing to test for now
