### ISSUE TITLE
new LU is created as planning in production

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1975]
### Is this a bug or feature request?
bug
### What is the current behavior?
using transform, new LU is created as planning in production
#### Which are the steps to reproduce?
1. purchase order with product P0001 + TU (P0001 is a co product of P0002)
2. receipt candidates - receive P0001 + TU (without LU)
3. manufacturing - new one for P0002, complete it
4. select the line, issue/receipt -> issue the co product
5. select the TU, use transform to put it on a new LU
=> LU is created as planning and you cannot issue anymore. You can only create a receipt NOK

**Comment by metas-ts** [comment]
implemented the fix in `release`, then merged it to `master`

**Comment by metas-lc** [comment]
IT
retested the testcase above. Works fine OK
