### ISSUE TITLE
Internal Use Action for Handling Unit Editor WebUI 

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1986]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Internal Use Action is missing in Handling Unit Editor in WebUI.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Add the Internal Use ("Materialentnahme" de_DE) Action for the Handling Unit Editor in WebUI.

**Comment by metas-lc** [comment]
IT
1. make sure you have a warehouse configured as Materialentnahme (inventory)
2. go to handling units editor and select an active hu
3. press on Materialentnahme
4. check the locator of this HU => it's in Materialentnahme OK
5. check movements => new one created from the initial warehouse to Materialentnahme OK
