### ISSUE TITLE
Mandatory Field Packing Material in Doctype "Saldokorrektur"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1990]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, in Window Customer Returns, in Lines, the Field "Packing Material" is mandatory. For Packing Material and Doctype "Saldokorrektur" that does not make sense.
#### Which are the steps to reproduce?
Open the Window Customer Returns in Sing Client. Doctype Saldokorrektur. Add Line for Palette. Not possible to save.
### What is the expected or desired behavior?
Shall work, probably similar to Sales Order/ Purchase Order?

**Comment by metas-rc** [comment]
I could not reproduce this anymore, neither on swing or webui. It was fixed meanwhile.
Moving the task and moving the task to testing, for doublecheck.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui. The problem was also solved there.
