### ISSUE TITLE
Set default Widget width for certain Columns

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1993]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the widget width for similar Fields is not identical in WebUI.
#### Which are the steps to reproduce?
Open Different Windows in Grid View and check similar Fields, e.g. Product or Business Partner, Sometimes they have a large width, sometimes not set explicitly.
### What is the expected or desired behavior?
Harmonize the width of certain Columns so that they all have the same look & feel in Grid View.

Large:
C_BPartner_ID and similar Partner_ID Columns
M_Product_ID
Name

Medium:
AD_Client_ID
AD_Org_ID

Small:
Dates
C_Currency_ID
C_UOM_ID
AD_Language

**Comment by metas-lc** [comment]
IT
took a quick look for bpartner in some grid views
and i see for e.g.here is difefrent:
https://mf15cloudit/window/169 (smaller) - like in orders
https://mf15cloudit/window/184 (bigger) - like in invoices
is it ok?
not sure how to test this one, and if there is an easier way to check..??
