### ISSUE TITLE
Window Design WebUI: Adjust Sales Invoice Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1994]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Look & Feel of Sales Invoice WIndow is not matching the current concept in MainView, GridView, and Subtabs.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Adjust the Look and Feel of Sales Invoice Window.

**Comment by metas-mk** [comment]
belongs to https://github.com/metasfresh/metasfresh/issues/2045

**Comment by metas-lc** [comment]
IT
1. doc layout:
top left: important, mandatory OK
top right: doctype, no, date OK
bottom right: org, client OK

2. gridview
first: doctype, no, date OK
last: status, org OK
together: pricelist + currency OK
order by: docdate desc OK

3. filters
date, bp, no, doctype: date and doctype are missing only on mf15

4. included tabs
all subtabs are missing white background NOK

other: attributes are mandatory

created followup https://github.com/metasfresh/metasfresh/issues/2271
