### ISSUE TITLE
Language Names too Long

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1995]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Names for Languages are too long, because they are chosen as a combination between Language and Country (locale).
#### Which are the steps to reproduce?
Open window/123 in Grid View and see.
### What is the expected or desired behavior?
Adjust the Language Names only to Language and put the 2 Char ISO country in brackets.

**Comment by metas-lc** [comment]
IT
checked language field in window 123 => they are like expected: Language and the 2 Char ISO country in brackets OK
