### ISSUE TITLE
Take out all AD_Client_ID from GridView in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#1996]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the AD_Client_ID is shown in Grid Views in WebUI. In 99% of all cases, this makes no sense.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Take out all AD_Client_ID from GridView in WebUI. Only show the the AD_Client_ID in Main Views/ Advanced Edits.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

Places where I still found the Client in grid mode:
* Partner Relation ( https://mf15cloudit/window/313) 
* Price List Schema (  https://mf15cloudit/window/337)
* Included tab Schema line from Price List Schema
* Pricing rule (https://mf15cloudit/window/53189)
* Included tab locator from window Warehouse ( https://mf15cloudit/window/139) 
* Included tab Accounting from window Warehouse
* Included tab Order Parent Product from window Manufacturing Order (https://mf15cloudit/window/53009)
* Included tab  Workflow  from window Manufacturing Order 
* Included tab Handling Unit Assignments from window Manufacturing Order 
*  Included tab  Produkt Attribute   from window Manufacturing Order

**Comment by metas-mk** [comment]
@metas-rc thx for the feedback. query missed the subtabs specialty. will fix and commit.

**Comment by metas-mk** [comment]
found the issues and created a follow up task for them. will take care there about them. moving this one to done.

https://github.com/metasfresh/metasfresh/issues/2013
