### ISSUE TITLE
Feedback WebUI CRM

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2007]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
User Feedback arrived for CRM in WebUI
### What is the expected or desired behavior?
Check and decide adoption.

Business Partner User:
Greeting S, Lastname L, Firstname L, eMail L

**Comment by metas-lc** [comment]
IT
go to Business Partner, User tab:
Greeting S, Lastname L, Firstname L, eMail L OK
