### ISSUE TITLE
Feedback WebUI Prices

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2009]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
User Feedback arrived for Prices in WebUI
### What is the expected or desired behavior?
Check and decide adoption.

Product Price:
Active is missing

Price List
Discount Schema wrong, shall be Price Schema

**Comment by metas-lc** [comment]
IT

1. Active in product price OK
2. Price List => didn't find Price Schema, only Rabatt-Schema => i think NOK
