### ISSUE TITLE
Broken Included Tabs to be redone

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2013]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Some Included Tabs are not created properly and seem to not take any layout adjustments.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Check the following Included Tabs 1 by one and see if the Layout can be adjusted. If not, then delete the ui elements, groups, sections and redo via the process. After that, the layout shall be adjustable again.

Windows where I still found the Client in grid mode:
Partner Relation ( https://mf15cloudit/window/313)
Price List Schema ( https://mf15cloudit/window/337)
Included tab Schema line from Price List Schema
Pricing rule (https://mf15cloudit/window/53189)
Included tabs Locator, Accounting from window Warehouse ( https://mf15cloudit/window/139)
Included tabs Order Parent Product, Workflow, Produkt Attribute, Handling Unit Assignments from window Manufacturing Order (https://mf15cloudit/window/53009)
Included tabs Bedarfsdetail, Produktionsdetail, Bereitstellungsdetail from window Material Schedule (https://mf15cloudit/window/540334)
General Ledger (https://mf15cloudit/window/132)
Included tab Journal from window General Ledger
Included tabs Handling Unit Element, Handling Unit Attribute, Handling Units Lager from window Handling Unit Editor (https://mf15cloudit/window/540189/)
Menu (https://mf15cloudit/window/105)

**Comment by metas-mk** [comment]
Done:
Included tabs Order Parent Product from window Manufacturing Order (https://mf15cloudit/window/53009)
Workflow, Produkt Attribute, Handling Unit Assignments were not broken

**Comment by metas-mk** [comment]
Other windows mentioned above still have to be created w/ ui elements. will do this in seperate issues.

**Comment by metas-lc** [comment]
IT
checked all windows above and created followup https://github.com/metasfresh/metasfresh/issues/2468
