### ISSUE TITLE
Create Window Price List Schema in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2015]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Layout of Price List Schema is not created in WebUI Window
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Layout of the Price List Schema window in WebUI.

**Comment by metas-mk** [comment]
Taken out from https://github.com/metasfresh/metasfresh/issues/2013

**Comment by metas-lc** [comment]
IT
open  Price List Schema window. Notice there is an included tab for lines. Use advanced Edit => it is grey and some fields are missing, compared with swing (have to check if it should be change in this task or another, or if it's fine like it is)
