### ISSUE TITLE
Create Window Pricing Rule in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2017]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Layout definition of Window Pricing Rule is missing in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Layout for Pricing Rule Window in WebUI

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/2013

**Comment by metas-lc** [comment]
IT
you can create a new one, logged in as admin. No errors, works like the one from swing. OK
