### ISSUE TITLE
Add System Configuration Window to WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2020]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the System Configuration Window is missing in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the System Configuration Window and add to system/ group in the menu.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

The window System Configuration respects is in the menu. It respects our best practices. All fields are translated in German and English (US). The window is also functional.
