### ISSUE TITLE
Create Window Textvariablen in WebUI

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2022]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Textvariablen  is not created in WebUI Window
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Textvariablen  window in WebUI.

**Comment by metas-lc** [comment]
IT
Text Variable in System folder
create a new one, add line => ok, no errors OK
