### ISSUE TITLE
Create Window Textbausteinein WebUI

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2023]
### Is this a bug or feature request?

Feature Request

### What is the current behavior?

Currently, the Textbausteinein  is not created in WebUI Window

#### Which are the steps to reproduce?

Open and see.

### What is the expected or desired behavior?

Create the Textbausteinein  window in WebUI.

**Comment by metas-lc** [comment]
IT
Boiler Plate window
=> you cand create a new one, saves ok, same fields as in swing OK
