### ISSUE TITLE
New Window for Validcombination in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2028]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Validcombination in WebUI
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Create the Window for Validcombination and Add to Finance menu.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/2025

**Comment by metas-lc** [comment]
IT
Account Combination window looks fine, completely readonly and has all fields like in swing (some of them showing only in advanced edit). It's in Finance window OK
