### ISSUE TITLE
New Window for Accounts and Elements in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2029]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no WIndow for Accounts and Elements in WebUI
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Create a Window for Chart of Accounts and Elements in WebUI. Think about to split the WIndows to reduce Performance Issues in Large Subtabs.

**Comment by metas-lc** [comment]
IT
window Account Elements is there and you can create a new one (no errors). The window respects our layout conventions. ok
