### ISSUE TITLE
Layout for Handling Unit Editor Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2032]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Handling Unit Window does not have the proper layout for Main View yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the proper Layout.

**Comment by teosarca** [comment]
@metas-mk  this is hardcoded atm
