### ISSUE TITLE
Additional 0,00 row in year end accounting generation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2035]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when doing the year end accounting generation in General Ledger, an additional row w/ 0,00 is created.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Don't create the empty/0,00 row.

**Comment by metas-rc** [comment]
Talked with Mark. Moving this to done
