### ISSUE TITLE
Picking Slot Label

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2036]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currenlty, the Picking Slot Labels are created outside of metasfresh, because most of the picking slots are used w/ static references.
#### Which are the steps to reproduce?
-
### What is the expected or desired behavior?
Create the Picking Slot Labes from new Picking terminal Window in WebUI. Add a quickaction that can be used when a picking slot is selected.
The Label shall have the following Information and shall be more wide than high (exact dimensions will follow):
Picking Slot No. (bigger, bold)
Business Partner Value
Business Partner Name
Location
Date+Time created

**Comment by metas-dh** [comment]
Results of IT1
testet on w101

* no quickaction for Picking Slot Label available in Picking Slot, when a slot is selected in Picking Terminal: NOK

**Comment by metas-lc** [comment]
note for IT: the process will be added there in other task. Until then, can be tested in window 540206 (picking slot)

**Comment by teosarca** [comment]
Postponed for now. See https://github.com/metasfresh/metasfresh/pull/2454#issuecomment-331436354

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* quickaction for Picking Slot Label available in Picking Slot window:  OK
* Picking Slot Labels created: the labels are created, but they are empty : general label issue, will be fixed in another task
