### ISSUE TITLE
Adjusted Business Partner Window for Small Companies

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2038]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Business Partner Window does not seem to fit perfectly for smaller companies in B2C.
Organisation, Client, BusinesspartnerGroup, Language, Tax ID is not needed. Same for Crop Rotation, EDI Documents and Replication. Instead, the Salesrep in/ extern shall be shown.
The R_Request Tab subtab shall be reorganized. Created, CreatedBy, Type, Note as Sequence. Order By created desc.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new window as described above. Find a concept to switch the Windows in the Menu in future. For now, the new Window is sufficient.

**Comment by teosarca** [comment]
> Find a concept to switch the Windows in the Menu in future

Also we need a concept about how to switch the default window (SO/PO) for each table.

**Comment by metas-ts** [comment]
just verified that all changed from this issue are already in the `release` branch

**Comment by metas-lc** [comment]
IT
Businesspartner B2C window:
- Organisation, Client, BusinesspartnerGroup, Language, Tax ID  are not shown OK
- Crop Rotation, EDI Documents and Replication are not shown OK
- Salesrep is shown OK
- The R_Request Tab subtab has the following fields: Created, CreatedBy, Type, Note as Sequence. 
but it's Order By created asc and the task said desc NOK
