### ISSUE TITLE
Window Design WebUI: Attribute Set

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2046]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Attribute Set does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the windowAttribute Set  respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
attribute set
- grid: ordered by name ask OK
- docview: important fields: top left OK, flags (active first): top right OK, org and client: bottom right OK
- included tabs: you can add/ remove data, fields are in 1 elem group and have white background OK
