### ISSUE TITLE
Window Design WebUI: Sales Order Candidates

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2048]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Sales Order Candidates does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Sales Order Candidates  respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Sales order candidates - usual window
1. doc view layout:
top left: mandatory, important OK
top right: important flags OK
bottom right: org, client OK

3. included tabs
- don't have enough data to check for now (will postpone)
