### ISSUE TITLE
Window Design WebUI: Purchase Order

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2049]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Purchase Order does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Purchase Order respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Purchase order:

grid view:
first 3: doc type, no, date OK
last 2: docstatus, org OK

CORNER STONES FOR DOCUMENTS
TOP RIGHT: Target document type, Document no, Doc date OK
written as Document Type, No. and Date OK
mandatory and important fields are on top left OK
org and client on bottom right OK

Included tabs:
line - white background, you can add/delete OK
tax - white background, readonly OK

Filter:
date is missing. NOK?

**Comment by metas-lc** [comment]
created followup https://github.com/metasfresh/metasfresh/issues/2155
so i'm moving this task to done
