### ISSUE TITLE
Window Design WebUI: Material Tracking

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2051]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Material Tracking does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the windowMaterial Tracking respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Material tracking - usual window 

1. doc view layout:
top left: mandatory, important OK
top right: active, important flags OK
bottom right: org, client OK

2. included tabs
all tabs: don't  have white background NOK
created followup: https://github.com/metasfresh/metasfresh/issues/new
