### ISSUE TITLE
Window Design WebUI: Price System

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2052]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Price System does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Price System respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
price system:
- grid: ordered by name ask OK
- docview: important fields: top left OK, flags (active first): top right OK, org and client: bottom right OK
- included tabs: there aren't any  OK
