### ISSUE TITLE
Window Design WebUI: Inventory Move

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2053]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Inventory Move does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Inventory Mover respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Inventory Move

IT
attributes

1. layout
top left: important fields OK
top right: doc type, no, date OK
bottom right: client and org OK

2. grid view
order by date desc OK
first 3: doc type, no, date OK
last 2:  status, org OK

3. included tabs
=> white background OK
