### ISSUE TITLE
Window Design WebUI: Manufacturing Order

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2054]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Manufacturing Order does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Manufacturing Order respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Manufacturing order:
CORNER STONES FOR DOCUMENTS
TOP RIGHT:  Target document type, Document no, Doc date OK
written as Document Type, No. and Date OK
mandatory and important fields are on top left OK
org and client on bottom right OK

grid view: 
first 3: doc type, no date OK
last 2: docstatus, org NOK? it's only org

Included tabs: 
workflow, hu assignments, cost, auswertung and produkt attribute does not have white background NOK?

Filter:
docstatus is missing. NOK?

**Comment by metas-lc** [comment]
created followup https://github.com/metasfresh/metasfresh/issues/2156
so i'll close this issue
