### ISSUE TITLE
Change AD_Table_ID Identifier to Name only

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2058]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the AD_Table_ID Identifier is Tablename + Name
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Change the Identifier to Name Only.

![image](https://user-images.githubusercontent.com/13365687/28511832-4b84ab86-704f-11e7-826d-e93ce7e42a05.png)

**Comment by metas-lc** [comment]
IT
checked several windows where there is a Table field => only Name is shown OK
