### ISSUE TITLE
Window Design WebUI: Product

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2070]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Product does not respect our  layout conventions (for included tabs)
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window  Bill of Materials respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
Product window, subtabs:
- Price: you can add, remove product prices. Ordered by version pricelist name 
- cu-tu allocation: you can add, remove TUs. Ordered by valid from desc
- replenish: you can add, remove one
- business partner: you can add, remove one. Ordered by bp asc
- accounting: readonly
- uom: you can add, remove one
- allocated product: readonly

Zoomm into for each of them: 1 element group, white background. Same fields like in swing
