### ISSUE TITLE
Window Design WebUI: Payment Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2071]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045
### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Payment does not respect our layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Payment respect our cornerstones and layout conventions

**Comment by metas-mk** [comment]
Belong to https://github.com/metasfresh/metasfresh/issues/2071

**Comment by metas-lc** [comment]
IT
Payment window - document window
1. doc view layout: 
top left: mandatory important OK
top right: Document type, no., date OK
bottom right: docstatus, org OK

2. grid view:
first: doctype, docno, date(should be). NOK: bpartner is first, docno missing
last: docstatus, org(should be). Docstatus is missing NOK

order by: doctade desc OK

3. filters:
org, no, bp NOK. 
org is wanted? missing: date, doctype

**Comment by metas-lc** [comment]
created follow-up, https://github.com/metasfresh/metasfresh/issues/2189
closing this one
