### ISSUE TITLE
CRM: Document List in Subtab Functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2074]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when drag&drop done on record, then theses are shown in document sidelist.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
For the Business Partner Window, we want the attached Documents to be shown in a Document Subtab. Additionally the user shall be able to write a description into the document entry (shall be done post-upload and entry creation, not needed when dragging&dropping). The new data structure shall have created, createdby, filename, description (always updateable). The data shall be ordered by created desc.

![image](https://user-images.githubusercontent.com/13365687/28624776-7f58a8dc-721a-11e7-944f-b7d28ab0c245.png)

### Note to IT:
full regression on everything related to attachments is REQUIRED. i.e.
* Swing attachments window
* ESR
* Swing Letter

**Comment by metas-ts** [comment]
Cherry-picked this issue to the `release`branch; see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/205/

**Comment by metasnw** [comment]
IT OK
