### ISSUE TITLE
Window Design WebUI: Payment Allocation Translation en_US

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2080]
Belongs to https://github.com/metasfresh/metasfresh/issues/2045
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Window Payment Allocation is not properly translated w/ according to current guidelines.
#### Which are the steps to reproduce?
Check an see.
### What is the expected or desired behavior?
Finish the translation of en_US properly.

**Comment by metas-lc** [comment]
IT
all fields are translated, including No. and Date (will keep it a bit more in IT for a migration check)

**Comment by metas-rc** [comment]
Results of IT

* The Payment allocation does not respect all our conventions. I created a followup: https://github.com/metasfresh/metasfresh/issues/2608
