### ISSUE TITLE
Window Design WebUI: Customer Returns

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2083]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window  Customer Returns does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window  Customer Returns respect our corner stones and layout conventions

**Comment by metas-rc** [comment]
Followup created: https://github.com/metasfresh/metasfresh-webui-api/issues/523

**Comment by metas-lc** [comment]
IT
Customer returns:

grid view:
first 3: doc type, no, date OK
last 2: docstatus, org OK

CORNER STONES FOR DOCUMENTS
TOP RIGHT: Target document type, Document no, Doc date OK
written as Document Type, No. and Date OK
mandatory and important fields are on top left OK
org and client on bottom right OK

Included tabs:
receipt lines - white background, you can add/delete OK
hu assignments - readonly ok, not white but we have task https://github.com/metasfresh/metasfresh-webui-api/issues/523

Filter:
date, docstype is missing. NOK?

**Comment by metas-lc** [comment]
created followup
https://github.com/metasfresh/metasfresh/issues/2154
so i'm closing this issue
