### ISSUE TITLE
Sales Order Advanced Edit Window in main View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2086]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit in Sales Order Window Main view is not optimized. Primary Layout is not shown in the first section. Also, Fields are not translated to en_US.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Layout and add Translations. Also, take out GrandTotal (shall be added to Grid and Breadcrumb in Future)

![image](https://user-images.githubusercontent.com/13365687/28678324-603e5934-72f0-11e7-9faf-e6b2488c0e12.png)

**Comment by metas-lc** [comment]
IT
Sales order advanced edit:

- grand total is in advanced edit and not on doc view OK
- layout is adjusted OK
- Anzahl Zeilen, Netto Summe and Steuersumme are not translated NOK

**Comment by metas-rc** [comment]
Results of IT

All the fields are translated in main view, advanced edit and in the 2  included tabs.
