### ISSUE TITLE
Purchase Order Advanced Edit Window in main View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2087]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit in Purchase Order Window Main view is not optimized. Primary Layout is not shown in the first section. Also, Fields are not translated to en_US. In Main View, there are 2 primary groups.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Layout and add Translations. Also, take out GrandTotal (shall be added to Grid and Breadcrumb in Future). Create an own section for Advanced Edit.

![image](https://user-images.githubusercontent.com/13365687/28679316-16ae8cd2-72f3-11e7-9538-4df385aa161e.png)

![image](https://user-images.githubusercontent.com/13365687/28679339-285346b2-72f3-11e7-8a09-1baec1cd96d7.png)

**Comment by metas-lc** [comment]
IT
Purchase order advanced edit:
- grand total is in advanced edit and not on doc view OK
- layout is adjusted OK
- Anzahl Zeilen and Steuersumme are not translated NOK

**Comment by metas-rc** [comment]
Results of IT:

*OK: The cornerstones and layout conventions are respected.
* NOK: Anzahl Zeilen and Steuersumme are still not translated.

**Comment by metas-mk** [comment]
@metas-rc thx. for the info.

> NOK: Anzahl Zeilen and Steuersumme are still not translated.

Done.

**Comment by metas-rc** [comment]
Results of IT

* OK: Now all the fields are translated

* I found 2 processes that are not translated. Followup:  https://github.com/metasfresh/metasfresh/issues/2730
