### ISSUE TITLE
Inventory Move Window improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2089]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Advanced Edit in Inventory Move Main View is not optimized. Primary Layout is not shown in the first section. Also, some Fields are not translated to en_US.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Layout and add Translations. Also, take out GrandTotal (shall be added to Grid and Breadcrumb in Future)

![image](https://user-images.githubusercontent.com/13365687/28679835-b5e08700-72f4-11e7-825f-2d15ebc19990.png)

**Comment by metas-lc** [comment]
IT
all fields are translated and advanced edit layout adjusted ok
