### ISSUE TITLE
Improve text Variable Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2090]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
The Sequence Of Field Organisation is not properly in Grid View.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Move the Organisation Field to the end in Grid View.

![image](https://user-images.githubusercontent.com/13365687/28681217-08488a02-72f9-11e7-88ee-6426fb7ec3b9.png)

**Comment by metas-lc** [comment]
IT
checked Text Variable Window (grid view) => organisation field is at the end, first one is Name and is ordered by name asc OK
