### ISSUE TITLE
Scheduler - improve error handling if AD_Role_ID can't be found

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2092]
### Is this a bug or feature request?
Feature
### What is the current behavior?

`AD_Schedule.AD_Role_ID` is not set, then the scheduler tried to get the role of the respective user.
If that fails, the scheduler fails with an error message that is hard to interpret.

### What is the expected or desired behavior?

The error message shall be easier to interpret so that an admin knows what to do about the problem

**Comment by metas-lc** [comment]
can be moved to done
