### ISSUE TITLE
Businesspartner B2C Location Editor missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2096]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Location Editor is missing in new Window Businesspartner B2C
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the location editor to Businesspartner B2C Location window in WebUI.

**Comment by metas-ts** [comment]
Cherry-picked into the `release` branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/204/

**Comment by metas-lc** [comment]
IT
Businesspartner B2C -> address tab => location editor is there (both grid and advanced view)
