### ISSUE TITLE
maven change "local" version from 1.0.0 to 10.0.0

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2102]
### Is this a bug or feature request?
feature

### What is the expected or desired behavior?
goal: 
* it shall not be a requirement anymore to have everything checked out and open in the local eclipse
* instead, for projects that are not open, maven shall get their artifacts from repo.metasfresh.com

## Results/Hightlights

* less complex/repetitive Jenkinsfiles (=> library)
* fixes some problems introduced before my vacation
  * SQL migrations 
  * build version info
* external downstream jobs can fail the "main" build
* no more need to check out "everything" (e.g. metasfresh-parent, metasfresh)
* less disk usage and weekly maintainance effort on private maven repo

**Comment by metas-lc** [comment]
can be moved to done
