### ISSUE TITLE
Create and implement the usage of a pdf printer

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2103]
### Is this a bug or feature request?
Feature request
### What is the current behavior?
currently each document is printed automatically into one PDF.
What if we need to print 100 documents into one PDF ?

### What is the expected or desired behavior?
We want to have a virtual pdf printer available and to be able to print documents into pdf files with specific layout as would be a real printer.

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/29163605-ab39e824-7dc5-11e7-9a43-c1c31ce60d0c.png)

**Comment by teosarca** [comment]
NOTE to IT: pls also do regression testing

**Comment by metasnw** [comment]
IT results:

1. set user it (also metasfresh user) to islogonkey = Y
1. closed java client
1. logged in (both it and metasfresh)
1. NOK: context does not show host key
![image](https://user-images.githubusercontent.com/16079655/29510530-69f6f740-865c-11e7-813e-e518d1fb01bb.png)


general todo list:
1. add field logonwithkey to webui

**Comment by cristinamghita** [comment]
@metasnw the problem is that the printing module is not activated by default in metasfresh and the configuration of hosting key is done there.
So please, run this first:
```
update ad_sysConfig 
set value ='Y'
where name = 'de.metas.printing.Enabled';
```

**Comment by metasnw** [comment]
tested again and found:
1. loginhostkey working in java client after enabling printing via sysconfig
1. NOK: but not in webui. Do I have to touch "de.metas.printing.webui.HostKeyStorageMode" ? Its set to "cookie" 
1. OK Printing queue => print all => created new PDF
1. NOK: cant download the PDF via process "PDF" in printing queue. log: [PDF ?ffnen-1036125] d.m.a.form.swing.SwingClientUIInstance   : Failed opening file:/tmp/data.pdf5558546013907662909.pdf

**Comment by metasnw** [comment]
IT sucessful
