### ISSUE TITLE
Move Currency Records from System to Client level so user can edit them

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2109]
### Is this a bug or feature request?
feature

### What is the current behavior?
users can not activate a currency because the record is on system and system is not accessible by user

#### Which are the steps to reproduce?
1. log on as user
1. open window currency
1. try to activate any currency which is inactive
1. NOK: not possible

### What is the expected or desired behavior?
records should be maintainable by user

**Comment by metasnw** [comment]
` update c_currency set ad_client_id = 1000000 where ad_client_id != 1000000;`

**Comment by metas-lc** [comment]
IT
go to currency - activate one => works OK
