### ISSUE TITLE
make version/build infos more transparent

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2110]
### Is this a bug or feature request?
Feature

### Results
* the rollout package's version is now stored in a file `build-info.properties` in the `dist` folder of both the `sql-only-tar.gz` and `dist-tar.gz` artifact
  * used in issue #2111 
* the version is also store within the deployable aritfacts such that is can be seen in metsfresh-admin:
![image](https://user-images.githubusercontent.com/1264789/29107267-9d26460c-7cd9-11e7-8a37-1d4e670f5452.png)

**Comment by metas-lc** [comment]
can be moved to done
