### ISSUE TITLE
Store version number in DB after successful sql remote

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2111]
## Is this a bug or feature request?

Feature

## Description

* As of #2110 we have the build's version in the DB rollout package
* TODO: use it to avoid unneccesary invocations of `sql_remote.sh`

## Results

* the rollout package's version is now stored in a file `build-info.properties` in the dist folder of both the `sql-only-tar.gz` and  `dist-tar.gz` artifact
* the rollout tool tha `sql_remote.sh` invokes checks the version and only runs if the package's version is higher
  * this is the default; call the tool with `-h` to learn more

### Example: two consecutive rollouts with the same version:

First run with the special case that the DB column + initial value had to be created oin the fly:
![image](https://user-images.githubusercontent.com/1264789/29106293-9b9827e2-7cd4-11e7-9ea2-855d1ec7aa7d.png)

Second run:
![image](https://user-images.githubusercontent.com/1264789/29106321-b98ea56e-7cd4-11e7-979d-701e5d06affa.png)

**Comment by metas-lc** [comment]
can be moved to done
