### ISSUE TITLE
Move verify BOM process to BOM window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2113]
### Is this a bug or feature request?
feature request

### What is the current behavior?
you need to start it from the product window

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/Create_BOM.html
see "verify BOM"

### What is the expected or desired behavior?
have it directly in BOM window

**Comment by metas-rc** [comment]
Results of IT

* The process Bom Validate is linked with the table PP_Product_BOM (Bill Of Materials window): OK
* The process works for single entries: OK
* The process is available always, but it only works for single entries. Followup created: https://github.com/metasfresh/metasfresh/issues/2868
