### ISSUE TITLE
ESR - add sysconfig to ignore non-credit lines 

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2118]
### Is this a bug or feature request?

Feature

### What is the current behavior?

* If a `ESR_ImportLine` transaction type is *not* "credit-memo" like (i.e. if it is a reversal, or a debit), then we don't yet have the business logic to process them.
* Currently, those import lines are marked with valid='N'

### What is the expected or desired behavior?

We want the option to "ignore" such import lines.
By that, we mean
* set them to valid=Y
* set them to processed=Y

The goal is that if a v11 or camt54 file with "non-standard" transactions is imported, 
then those transactions that are "standard" should be processed as ususal, and the others shall be "ignored"

And we want a way to switch this "ignoring" on and off with AD_Sysconfig.
Suggestion: add a Y/N column `ESR_ImportLine.IsErrorOnUnsupportTrxType` and set it from AD_SysConfig when the file is evaluated. 
That way we know what setting is/was applied and also can change it on an individual basis.

**Comment by cristinamghita** [comment]
# Results of IT - tested on webui
## Use a reversal transaction code
* Set sys config _de.metas.payment.esr.ProcessUnspportedTrxTypes_ to Y
* Import a file like this:
  ```
0020100014562345370001000006420023125290000014555000000000018011818011818011800000000000000000000000
005010001456999999999999999999999999999000000014555000000000001150416000000000000000000
```
* The line is processed and valid **OK**
* 005 is the code for reversa;
