### ISSUE TITLE
ESR - Show actual number of transactions

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2119]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Currently we show the column `ESR_Import.ESR_Control_Trx_Qty` as our number of transactions.
That value is coming from the input file and if it's not equal to the "real" number of transaction lines, there file is inconsistent and there is an error.

The problem is that with camt.54 , the inout file might not have such a control value in the input file and we tolerate that. however, to give a user a quick overview, we still need the number of transactions.

So this task is about providing it, as SQL column.
The control value is still stored, and if it is available also validated against. It's just not shown anymore (only in an error message if there is an inconsistency).

**Comment by metasnw** [comment]
IT OK
