### ISSUE TITLE
cant save purchase order

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2121]
### Is this a bug or feature request?

Bug

### What is the current behavior?

under certain circumstances, the purchase order can't be saved. 
* the json returned by the api indicates a missing C_PaymentTerm_ID.
* however, the vendor in question does have its `PO_PaymentTerm_ID` set to the defaulkt payment term

### Result

The problem was that the `C_BPartner_Stats` record was only created on-demand, but `CalloutOrder` **inner-joined** `C_BPartner_Stats` to C_BPartner.

with the inner-join-resultset beeing empty, `CalloutOrder`did not retrieve the `C_PaymentTerm_ID`.

I solved it by:
* making sure that new C_BPartners always get their `C_BPartner_Stats` record when they are created
* supplying a migration script that inserts missing `C_BPartner_Stats` records

**Comment by metasnw** [comment]
IT was successfull
