### ISSUE TITLE
Export all webui AD_Messages from w101

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2134]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are static elements missing in webui.
#### Which are the steps to reproduce?
Open the Sitemap. See that "Browse whole Tree is missing".
### What is the expected or desired behavior?
Migrate all messages.

**Comment by metas-lc** [comment]
IT
Open the Sitemap. See that "Browse whole Tree is there OK
