### ISSUE TITLE
Window Design WebUI: Shipment Schedule

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2140]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Shipment Schedule does not respect our current Window Design cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Shipment Candidates respect our cornerstones and layout conventions

**Comment by metas-lc** [comment]
IT
Product window - usual window
1. doc view layout:
top left: mandatory, important OK
top right: active(doesn't exist), important flags OK
bottom right: org, client OK

2. grid view
order by: there is no name so i assume is OK

3. included tabs
shipment picking tab doesn't have white background NOK

**Comment by metas-lc** [comment]
created followup https://github.com/metasfresh/metasfresh/issues/2191
closing this one
