### ISSUE TITLE
Customer Returns error w/ create from Shipment in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2142]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, an error occurs in process/ action "return hu from customer" from shipment window in webui.
#### Which are the steps to reproduce?
Check Testcase on erptest. Shipment 42763.
### What is the expected or desired behavior?
Shall work w/o error.

**Comment by metas-mk** [comment]
Could belong to this one: https://github.com/metasfresh/metasfresh-webui-api/issues/498

**Comment by metas-rc** [comment]
Right, it is the same problem as in  metasfresh/metasfresh-webui-api#498, which was not fixed.

**Comment by metas-rc** [comment]
https://pastebin.com/apgUGUEt

**Comment by metas-rc** [comment]
Talked with Teo about the problem. 
The HU Returns to  Customer is a form in swing and webui does not support forms. 
I will make the Customer Returns process similar with de.metas.ui.web.handlingunits.process.WEBUI_M_HU_ReturnToVendor

**Comment by metas-rc** [comment]
Note: 
I did not dev test this because I don't have webui locally. To be tested after rollout

**Comment by metas-lc** [comment]
note for IT: shall be solved in https://github.com/metasfresh/metasfresh/issues/2112

**Comment by metas-mk** [comment]
Quick Test with newer Testcase (Shipment from 31.08.2017 w/ HU Assignments): Error 
![image](https://user-images.githubusercontent.com/13365687/30014666-cf45da16-914d-11e7-9cff-620a63e8bf70.png)

**Comment by metas-lc** [comment]
IT
it's called Shipped HUs => works. It opens the HU you shippend, you select it and press on recturn to customer => inout created OK
