### ISSUE TITLE
Disposal reverse-correct does not  recreate the HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2143]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When reverse-correcting a Disposal Document, then the HUs are not recreated.
#### Which are the steps to reproduce?
Create a Disposal. Reverse-Correct/ Void it. The disposed HU are recreated/ reactivated.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-lc** [comment]
IT
swing/webui
1. create a purchase order and complete it (warehouse x)
2. go to receipt candidates and create inout (warehouse y)
=> hu is active (warehouse y)
3. go to korrectur and use dispose
=> Disposal Document created ok
=> hu is destroyed (warehouse y)
4. open Disposal Document and reverse/void it
=> hu is active (warehouse y)
=> no movement created OK???
5. go to korrectur and dispose it once again
=> Disposal Document created ok
=> hu is destroyed (warehouse y)

**Comment by metas-mk** [comment]
Quick Test: Works nicely.

**Comment by metas-dh** [comment]
Results of IT2

repeated test above: 
* HUs are recreated after Reverse/Correct & Void of Disposal: OK
* movements are created correctly for Disposal & Disposal Reverse: OK
