### ISSUE TITLE
Action for Warehouse Movements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2144]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user can only move HU via Action for Quality Issue Warehouses. It's not possible to move in other Warehouses.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Create an identical action, but allow to move from and to all possible warehouses.

**Comment by metas-lc** [comment]
IT
swing:
receipt pos -> korrectur -> select an HU and pick MoveHUToWarehouse
=> a list with whs appear and you can select one => movement created for HUs and product OK

handling units pos ->  select an HU and pick MoveHUToWarehouse
=> a list with whs appear and you can select one => movement created for HUs and product OK

probably NOK: when you do MoveHUToWarehouse you can also select the warehouse where you are currently in. And if you select that one, you get an error

webui:
hu editor

**Comment by metas-ts** [comment]
Also cherry-picked this fix to `2017-09`

**Comment by metas-lc** [comment]
IT
repeated the testcases above
=> all OK, no errors, the process was added in quickactions OK
but you can still choose the warehouse you are already in (Lagerort == Lagerort An and Merkmale == Attribute Set Instance To) NOK

**Comment by metas-lc** [comment]
IT
I  can still choose the warehouse i am already in (Lagerort == Lagerort An and Merkmale == Attribute Set Instance To) NOK

**Comment by metas-lc** [comment]
IT
repeated the testcase above -> works fine, the wh you are in doesn't appear anymore

**Comment by metas-ts** [comment]
cherry-picked to `release`
