### ISSUE TITLE
Partial Internal usage action in Handling Unit Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2145]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to have a partial Internal Usage from an HU w/o Transforming first.
#### Which are the steps to reproduce?
Open, check and see.
### What is the expected or desired behavior?
Adjust the Internal Usage action/ process to also allow the selection of partial quantities. Initially, always the whole HU is set in Parms, but the user can adjust the Quantities when needed.

**Comment by teosarca** [comment]
note to IT: to be tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/561

**Comment by metas-mk** [comment]
Quick test: Works w/ Handling Units that have "real TU". Then the qty added to action parm is "split off and moved away". As soon as you select an LU which only had CU directly on it, then the whole LU is moved.

**Comment by metas-ts** [comment]
cherry-picked to `2017-09`

**Comment by metas-dh** [comment]
update: checked with metas-mk: OK for now; created follow-up Partial Internal Usage action in Handling Unit Editor shall be possible for CUs as well #2837
