### ISSUE TITLE
backend: Labels widget

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2146]
### Is this a bug or feature request?
feature request

### What is the expected or desired behavior?
1. have a way to add one or many tags to a record 
1. persist those tags so they can be used in reports

example:
add "nice" and "cooperative" to a bpartner record

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1138

**Comment by metas-rc** [comment]
Results of IT

* Adding and removing labels in the window Business Partner works correctly.
* WHen labels are added/ removed to/from a business partner entry, the modifications are applied in the databse.
