### ISSUE TITLE
Window Design WebUI: Shipment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2150]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Shipment does not respect our current Window Design cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the Shipment window respect our cornerstones and layout conventions

**Comment by metas-lc** [comment]
IT
Shipment window - document window
1. doc view layout: 
top left: mandatory important OK
top right: Document type, no., date (is not there, but we have it in grid view. Check why and how we want it. probably rename pick date and move it above?) NOK?
bottom right: org, client OK

2. grid view:
first: doctype, docno, date OK
last: docstatus, org OK
order by: doctade desc  (should be) NOK is ordered by docno desc

3. filters:
no, bp NOK. 
missing: date, doctype

4. included tabs:
included tab doesn't have white background. NOK

**Comment by metas-lc** [comment]
created follow-up https://github.com/metasfresh/metasfresh/issues/2190
closing this one
