### ISSUE TITLE
Prepare Default Filters for Retraceability window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2152]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the default Filter in Retraceability Window does not allow to filter by HU No.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add further Filter criteria to Retraceability window.

**Comment by metas-rc** [comment]
Results of IT

* OK: The filter by HU value was added and it works correctly.
* OK: Order by date desc
* OK: Multiple filters
* OK: Everything is translated
* OK: Corner stones and layout conventions are respected.
