### ISSUE TITLE
Window Design WebUI : Business Partner Group

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2161]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Businesspartner group needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Businesspartner group to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
Business Partner Group - usual window
1. doc view layout:
top left: mandatory, important OK
top right: active, important flags OK
bottom right: org, cient OK

2. grid view
order by name asc OK

3. included tabs
accounting tab doesn't  have white background NOK
assigned partners tab looks like it has more elements (i think NOK) and only the first one has white background. I guess it shall be one element with white background . NOK

**Comment by metas-lc** [comment]
created follow-up https://github.com/metasfresh/metasfresh/issues/2192
closing
