### ISSUE TITLE
Window Design WebUI : Outbound Documents Config

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2162]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Outbound Documents Config needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Outbound Documents Config to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
Outbound Documents Config - usual window

1. doc view layout:
top left: mandatory, important OK
top right: active, important flags OK
bottom right: org, cient OK

2. grid view
there is no name to order by so i assume is ok

3. included tabs
- no included tabs
