### ISSUE TITLE
Do not show new button in B2C tab customer

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2163]
### Is this a bug or feature request?
bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/29271539-3b5a3114-80fc-11e7-883a-72c5d94271b5.png)

### What is the expected or desired behavior?
no new button

**Comment by teosarca** [comment]
imho, this was wrongly defined in application dictionary. The tab shall not allow inserting.
Same thing applies for Vendor tab.

**Comment by teosarca** [comment]
@metasnw just saw u self-assigned ... so nevermind

**Comment by metasnw** [comment]
IT OK
