### ISSUE TITLE
Window Design WebUI : Product

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2167]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Product needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Product to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
Product window - usual window
1. doc view layout:
top left: mandatory, important OK
top right: active, important flags OK
bottom right: org, cient OK

2. grid view
order by name asc OK

3. included tabs
tabs have white background OK
