### ISSUE TITLE
Window Design WebUI : Bill of Materials

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2170]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Bill of Materials needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Bill of Materials to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
1. layout:
top left - important fields OK
top right - active OK
bottom right - org, client OK

2. grid view
order by name asc OK

3. included tabs -> white background OK
