### ISSUE TITLE
Window Design WebUI : Unit of Measure

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2174]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Unit of Measure needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window unit of Measure to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
sales order candidates

1. layout
top left: important fields OK
top right: flags OK
bottom right: client and org OK

2. grid view
order by name asc OK

3. included tabs
=> white background is missing NOK

follow-up: https://github.com/metasfresh/metasfresh/issues/2285
