### ISSUE TITLE
New Window for Attribute Search in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2177]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the recording Possibility is missing for Attribute Search.
#### Which are the steps to reproduce?
Open the Attribute Window in WebUI and see.
### What is the expected or desired behavior?
Create a new Window Attribute Value Search.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

OK: The window ws added.
The window name is not translatd into English. Followup created: https://github.com/metasfresh/metasfresh/issues/3191

OK: All the fields are translated
*OK: Our cornerstones are respected
