### ISSUE TITLE
Window Design WebUI : Sales Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2183]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Sales Order needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
Adopt the window Sales Order to our design Guidelines and layout conventions

**Comment by metas-lc** [comment]
IT
sales order - doc window
1. layout
top left: important fields NOK - in some part dropship is split
top right: doctype, no, date OK
bottom right: org, client OK


2. grid view
first: doctype, no, date OK
last: doc status, org OK
price system+currency together
order by date desc OK

3. filters: no, bp, doctype. Date missing NOK

4. included tabs
some parts have white backgrouds, some not. NOK

created follow-up https://github.com/metasfresh/metasfresh/issues/2222
