### ISSUE TITLE
Window Design WebUI: Payment Allocation Window Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2188]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Payment Allocation does not respect our layout conventions.
#### Which are the steps to reproduce?
follow-up of https://github.com/metasfresh/metasfresh/issues/2077
### What is the expected or desired behavior?
1. grid view:
forder by: doctade desc  (should be) NOK is ordered by docno desc

2. filters:
org, no NOK. 
org is wanted? missing: date

**Comment by metas-mk** [comment]
checked on w101 and mf15releasetest. issues have been solved in the meanwhile. closing this issue.
