### ISSUE TITLE
Window Design WebUI: Shipment Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2190]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Shipment does not respect our current Window Design cornerstones and layout conventions
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2150
### What is the expected or desired behavior?
IT
Shipment window - document window
1. doc view layout: 
top right: Document type, no., date (is not there, but we have it in grid view. Check why and how we want it. probably rename pick date and move it above?) 

2. grid view:
order by: doctade desc  (should be) NOK is ordered by docno desc

3. filters:
no, bp. 
missing: date, doctype

4. included tabs:
included tab doesn't have white background. NOK

**Comment by metas-rc** [comment]
Results of IT

I checked the things specified in the requirements and they are all solved now.
The window Shipment respects all our cornerstones and layout conventions.
