### ISSUE TITLE
Window Design WebUI : Business Partner Group Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2192]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Businesspartner group needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2161
### What is the expected or desired behavior?

1. included tabs
accounting tab doesn't  have white background 
assigned partners tab looks like it has more elements (i think NOK) and only the first one has white background. I guess it shall be one element with white background

**Comment by metas-mk** [comment]
@metas-lc I checked the thing about the white background in advanced edit mode. Currently one has to choose between a white background (all in one ui group) or having section headers. Both used together does not look good atm, so will postpone this design decision for now.

**Comment by metas-lc** [comment]
IT
1. accounting tab has white background OK
2. Business Partner one looks the same (wanted for now) OK
