### ISSUE TITLE
Shipment Candidates dropship vendor ID missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2194]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Vendor ID is missing when isDropship = Y.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Vendor Businesspartner ID to Main View and display when isDropship = Y.

**Comment by metas-lc** [comment]
IT
1. create a new sales order with bpartner x
2. add a product that has this bpartner x as customer and dropship, with bpartner y as vendor
3. complete and go to shimpment candidates
=> dropship is on Y and dropship bpartner is shown
4. set dropship on N => dropship bpartner field is hidden
5. set it back => dropship bpartner is shown OK
