### ISSUE TITLE
Window Design WebUI : Bank Statement

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2196]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Bank Statement does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Bank Statement respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
bank statement - doc type
1. layout
there is no target doctype and docdate. Docno top right OK
top left: important fields OK
bottom right org, client OK

2. grid:
first: docno, last: status org OK

3. filters: org, no, name

4. included tab:
background is not white NOK
mandatory date field is missing (valuta) NOK  

other NOK: doc no is not generated by default (you have to set it manually)
