### ISSUE TITLE
New Window for filtered Bank Statement Line References

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2198]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is now Window for Bank Statement Line References.
#### Which are the steps to reproduce?
Open and See.
### What is the expected or desired behavior?
Create a new Window for Bank Statement Line References and let it be opened from Bank Statement Line Window.

**Comment by metas-rc** [comment]
Results of IT

* Some of the callouts for  Bank StatementLine Reference are not webui compliant. Followup created: https://github.com/metasfresh/metasfresh/issues/2634

* Also, some of the fields are not translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/2635
