### ISSUE TITLE
Window Design WebUI : Payment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2200]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Payment does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Payment respect our cornerstones and layout conventions

**Comment by metas-lc** [comment]
IT
rechecked payment window and edited the follow-up task https://github.com/metasfresh/metasfresh/issues/2189
