### ISSUE TITLE
Window Design WebUI : GL Journal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2201]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window GL Journal does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window GL Journal respect our cornerstones and layout conventions

**Comment by metas-rc** [comment]
Results of IT
The window GL Journal respect our cornerstones and our layout conventions. 

Check also https://github.com/metasfresh/metasfresh/issues/2226
