### ISSUE TITLE
Window Design WebUI : Tour Version

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2202]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Tour Version does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Tour Version respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
tour version: usual window

doc view:
important fields on top right OK
active and other flags on top right OK
org, client on bottom right OK
 
grid view:
order by valid from desc OK

included tab:
tour version line doesn't have white background NOK

created follow-up https://github.com/metasfresh/metasfresh/issues/2217
