### ISSUE TITLE
Window Design WebUI : Delivery Days

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2203]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Delivery Days does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Delivery Days respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
delivery days - usual window

1. doc layout
top left - important, mandatory fields OK
top right - active and flags OK
bottom right: org, client OK

2. included tab - cannot create new data there yet
