### ISSUE TITLE
Window Design WebUI : Contract

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2204]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Contract does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Contract respect our corner stones and layout conventions

**Comment by metas-lc** [comment]
IT
gridview: order by date desc? Date is empty (also NO. is 0 to all) - if it's nok i'll create a separate task
docview: TL: important, TR: Contract Type, No. and Date, BR: org and client OK
advanced edit: looks OK
included tabs: white background OK
translated OK
