### ISSUE TITLE
Window Design WebUI : Product

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2207]
* Belongs to https://github.com/metasfresh/metasfresh/issues/2045

### Is this a bug or feature request?
* Feature Request
### What is the current behavior?
* The window Product does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Make the window Product respect our cornerstones and layout conventions

**Comment by metas-lc** [comment]
IT
gridview: order by name asc OK
docview: TL: important, TR: active and flags, BR: org and client OK
advanced edit: looks OK
included tabs: white background OK
translated OK
