### ISSUE TITLE
take out password field from user window and use process instead

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2212]
### Is this a bug or feature request?
feature

### What is the current behavior?
you can edit the password in user window
if you do not match password criteria you do not see the error message but the new button is not appearing

#### Which are the steps to reproduce?
follow http://docs.metasfresh.org/webui_collection/EN/NewUser.html
but use password with < 8 characters
NOK: no error message

try workaround:
1. action "Reset password"
1. NOK: does not work

### What is the expected or desired behavior?
1. password field is not shown at all
1. process for reset password works in window user for all systemuser records
1. update documentation

**Comment by metasnw** [comment]
addressed by https://github.com/metasfresh/metasfresh-webui-api/issues/610

**Comment by metasnw** [comment]
tried on w101 to create a new user:
setting issystemuser and login does not allow to save user

error in console: "Das Passwort muss mindestens 8 Zeichen lang sein und darf keine Leerzeichen enthalten."

**Comment by metas-mk** [comment]
@metas-nw works for me.
![image](https://user-images.githubusercontent.com/13365687/31263889-90eec512-aa65-11e7-8a7b-bf55fa14cac7.png)

@teosarca the adjustment in the process for empty "old" password doesn't seem to work
![image](https://user-images.githubusercontent.com/13365687/31263902-b7410360-aa65-11e7-9347-cba5bd912af0.png)

**Comment by metas-lc** [comment]
1. open user window
2. create a new one: add firstname, lastname and login
=> it's saved. OK
3. go to actions, "Change password", add new password + retype (make it 4 char length), start
=> Error: Das Passwort muss mindestens...
Server error
Das Passwort muss mindestens 8 Zeichen lang sein und darf keine Leerzeichen enthalten.
OK
4. repeat step 3 but make it 8 chars
=> password is set (checked the db)
5. go to actions, "Change password", add new password + retype (don't set old password)
=> "Altes Passwort stimmt nicht überein"
6. repeat 5 but set old password
=> password updated successfully OK
7. open "Change password" process again
8. write something random on each field, long press on the eye button
=> you can see what you wrote, when you let go it disappears OK
