### ISSUE TITLE
User would like to import default values for contact and address

### ISSUE THREAD

**Issue by eoss-sh** [metasfresh/metasfresh#2218]
### Is this a bug or feature request?
yes
### What is the current behavior?
isbillto_default, isshipto_default and isdefaultcontact can not be imported

#### Which are the steps to reproduce?
open Import-Format and try to add default values for the above mentioned fileds

### What is the expected or desired behavior?
We would like to be able to add to an address or contact if it is the default value while we import the data with the "Ladeprogramm für Import". Only that way we are able to mark default data when additional contacts or addresses are imported.

**Comment by metasnw** [comment]
this issue is also needed for #2224 as defaultlocation is used on import of flatrate term to determine which address to use of a partner as dropship

**Comment by teosarca** [comment]
update: now we can import those IsShipToDefault, IsBillToDefault and IsDefaultContact flag,
but pls note that i didn't change the "Geschäftspartner Standard" import format.

**Comment by cristinamghita** [comment]
Modified the import format

**Comment by metasnw** [comment]
IT was successfull
