### ISSUE TITLE
Window Design WebUI : Bank Statement Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2221]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Bank Statement does not respect our cornerstones and layout conventions
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2196
### What is the expected or desired behavior?
1. included tab:
 - background is not white - should be white
- mandatory date field is missing (valuta) - shall be added. You cannot create new line

2. other: doc no is not generated by default (you have to set it manually) - needs to be generated

**Comment by metas-mk** [comment]
> other: doc no is not generated by default (you have to set it manually) - needs to be generated

This is wanted. Normally the document No. comes from the paper statement or is imported automatically. So better to not generate the statement No automatically.

**Comment by metas-rc** [comment]
Results of IT

* OK: The included tab has white background. New entries can be added to it, there is no error.
* OK: All the fields are translated in English
* Some things are still not complying with our conventions. I created a followup for them: https://github.com/metasfresh/metasfresh/issues/2609
