### ISSUE TITLE
Window Design WebUI : Sales Order Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2222]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Sales Order needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2183
### What is the expected or desired behavior?
1. layout
top left: important fields - in mf15 dropship is split, while in w101 is ok
2. filters: no, bp, doctype. Date missing in mf15. In w101 is a separate one => need one in mf15 too
3. included tabs: in mf15 they don't have white background. Only in w101

![sales_order_docview](https://user-images.githubusercontent.com/16001666/29606415-e4aa302e-87f6-11e7-917f-1f1416a0a935.png)

**Comment by metas-lc** [comment]
IT
1. TL: mandatory and important fields are in 1 element group OK
2. Date is missing in both w101 and mf15 NOK
3. included tab: white background OK

**Comment by metas-rc** [comment]
Results of IT : Date filter is still missing.

**Comment by metas-mk** [comment]
@metas-rc thx for the info.

> Results of IT : Date filter is still missing.

Done.

**Comment by metas-rc** [comment]
Results of IT

* OK: Now the date filter is also in Sales Order
