### ISSUE TITLE
Support longer numbers on documents

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2223]
### Is this a bug or feature request?
feature

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/29606603-10c24622-87ef-11e7-989e-5bfa012605bc.png)

1. price is supporting only 5 digits on sales order and invoice. rest is not displayed
1. line is broken

#### Which are the steps to reproduce?
enter a sales order with price 1.000.000,12

### What is the expected or desired behavior?
1. make sure numbers are never cut off. Worse case: break the line
1. try to make number as long as possible. Take decimal digits also into account.
e.g. support sth. like 12345,12 (should be fine for most)

**Comment by metas-dh** [comment]
Results of IT1

tested on w101

* price with 8 digits (e.g. 100.000,50) displayed correctly, for both sales order & invoice docs: OK
* line is broken for price with more digits (e.g. 1.000.000,21): OK?
