### ISSUE TITLE
Import Subscriptions / Flatrate Terms

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2224]
### Is this a bug or feature request?
feature request

### What is the current behavior?
it needs know how to to import subscriptions 

#### Which are the steps to reproduce?
NA

### What is the expected or desired behavior?
find a procedure / tool / best practice to import subscriptions

example:

|Value | firstname | lastname | condition | price | startdate | enddate|
|-------|-------|-------|-------|-------|-------|-------|
|12345|Jack| Taylor| 1 year auto | 100 | 02.06.2013 | NULL |

**Comment by teosarca** [comment]
Test file i've used for first iteration:
```csv
1231,flatrate_conditions1,2017-01-02,2017-07-09
1232,flatrate_conditions2,2017-01-02,2017-07-09
1233,flatrate_conditions3,2017-01-02,2017-07-09
1234,flatrate_conditions4,2017-01-02,2017-07-09
1235,flatrate_conditions5,2017-01-02,2017-07-09
```

**Comment by metasnw** [comment]
@teosarca is the first column the product or the partner?

**Comment by teosarca** [comment]
> @teosarca is the first column the product or the partner?

partner

**Comment by metasnw** [comment]
I tested and got this result:
 Error Processing Document document: Pauschale - Vertragsperiode 1000000 Belegverarbeitung: CO Cause: Erforderliche Felder ausfüllen:  Preissystem, Lieferadresse, Produkt (FillMandatoryException), 

test data:
`G0001,abo,2017-01-01,2017-03-03,P002737,3.45`

condition:
![image](https://user-images.githubusercontent.com/16079655/30109715-b27938f4-9307-11e7-8b8a-e3a2d294797d.png)

transition:
![image](https://user-images.githubusercontent.com/16079655/30109739-bdc2fac4-9307-11e7-8f73-ba9d1e05ad78.png)

**Comment by metasnw** [comment]
I tested again and found this problem:
` Error Processing Document document: Pauschale - Vertragsperiode 1000001 Belegverarbeitung: CO Cause: Zum angegebenen Preissystem "Divers" konnte keine Verkaufspreisliste gefunden werden. (PriceListNotFoundException), `

although this "Testpreisliste Kunden" is set in flatrate condition.

![image](https://user-images.githubusercontent.com/16079655/30150212-d1542592-93aa-11e7-8bda-75825fcf9727.png)

**Comment by teosarca** [comment]
that's a config issue, for sure... will debug it a bit later

**Comment by metasnw** [comment]
I put a price system here:
![image](https://user-images.githubusercontent.com/16079655/30150332-3cc625e6-93ab-11e7-9c76-df541f657a3f.png)

**Comment by metasnw** [comment]
after unticking "AB mit neuer Vertragslaufzeit" the flatrate term was imported

**Comment by teosarca** [comment]
@metasnw  pls close the task is everything was delivered.
