### ISSUE TITLE
New Window for GL_Journal in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2226]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window in WebUI to maintain the GL Journal Lines. Further on the Batch LÖevel on Journal is not wanted anymore. Add a new Window in WebUI, menu and join
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new GL Journal Window without Batch Lavel and add the included Tab for Journal Lines., Create a menu entry.

**Comment by metas-rc** [comment]
Results of IT

* OK: Menu entry created (name; Hauptbuch Journal)
* OK:  Cornerstones and layouts are respected
* Cannot add new line. Shall be solved in https://github.com/metasfresh/metasfresh/issues/2305
* Some of the fields and the window name itself are not translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/2606
