### ISSUE TITLE
New Window for Product Costs in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2229]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Productcosts is missing in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window Productcosts for WebUI and add to WebUI menu.

**Comment by metas-lc** [comment]
IT
product costs: 
1. menu
=> it's added in menu, under Finance

2. layout
top left: important fields OK
top right: flags OK
bottom right: org and client OK

3. gridview
order by searchkey - should be by name

4. included tabs
all have white background OK

TODO:
gridview - order by name asc
