### ISSUE TITLE
New Window for Fact_Acct_ActivityChangeRequest

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2230]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Fact_Acct_ActivityChangeRequest is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window Fact_Acct_ActivityChangeRequest in WebUI and add to WebUI menu.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* window for  Fact_Acct_ActivityChangeRequest (Kostenstellen Belege) in WebUI, in menu: Finanzen: OK
