### ISSUE TITLE
New Window for c_activity in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2232]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Activity maintenance is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window for Activity maintenance in WebUI and add to WebUI menu.

**Comment by metas-mk** [comment]
Adding rough Prototype window definition.

**Comment by metas-lc** [comment]
IT
1. Cost Center window is added in Finance menu
(on mf15 is missing from menu. You can open it with direct link)

2. layout 
top left - important fields OK
(on mf15 description is not in the ui element group. See w101)
top right - active OK
bottom right - org, client OK

3. grid view - order by name OK

4. creating a new one
=> you can create a new one, saves with no errors, but you have to add the value manually.

TODO: 
1. see why Cost Center is missing from menu in mf15
2. see why description is not in ui element group in mf15
3. when you create a new cost, after you add a name, the search key should be set by default
