### ISSUE TITLE
New Window for Payment Selection in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2234]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Payment Selection is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window Payment Selection in WebUI and add to WebUI menu.

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* new window Payment Selection, in Finance: OK
