### ISSUE TITLE
New window for Shipper in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2235]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Shipper maintenance is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window for shipper Shipper in WebUI and add to WebUI menu.

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* new window Shipper, in Logistics / Settings: OK
