### ISSUE TITLE
New Window for Printing Queue in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2236]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Printing Queue is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window for Printing Queue in WebUI and add to WebUI menu.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* window for printing queue ("Druck-Warteschlange"): OK
