### ISSUE TITLE
Order Control Report Attribute missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2237]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Some Attributes are not printed to Order Control report.
#### Which are the steps to reproduce?
Open a report w/ attributes and see.
### What is the expected or desired behavior?
It shall show the attributes.

**Comment by metas-lc** [comment]
IT
label attribute is added in Order Control Report. (both normal and barcode)
