### ISSUE TITLE
Make Request Type a search field

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2247]
### Is this a bug or feature request?
feature

### What is the current behavior?
no way to use it in request window

#### Which are the steps to reproduce?
open request window and try

### What is the expected or desired behavior?
make it a search/filter field

**Comment by metasnw** [comment]
deployed to live15

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* Request Type as search / filter field in Request window: OK
* Searching / filtering for request type: works fine, OK
