### ISSUE TITLE
Revamp Validcombination Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2255]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to create new Validcombinations in WebUI and add them to Accounting instructions.
#### Which are the steps to reproduce?
Open the Validcombination Window and see.
### What is the expected or desired behavior?
Make it possible to use the Validcombination window for creation of new account combinations.

**Comment by metas-rc** [comment]
Results of IT

* OK:  New Account Combinations can be created and saved
* OK: The window and its fields all have English translations.
* OK: The  window Account Combinations respects our layouts and corner stones. There are some small details that I created a followup for: https://github.com/metasfresh/metasfresh/issues/2637
