### ISSUE TITLE
SQL - problem to rollout master build to DB with issue-build

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2260]
### Is this a bug or feature request?

Bug

### What is the current behavior?

Example: 
* assume you rolled out a ussur branch to `w101`
* the DB_version string is set to e.g. `5.23.2-<somebuildnumber>..`; note: the `2` is because it's not-master
* now you want to rollout the master build. The master build's version is  `5.23.1-<somebuildnumber>..`; note: the `1` is because it's master

This causes the rollout script to fail, unless it is called with -v

### What is the expected or desired behavior?

When flipping between the `1`and `2` patch version (and given that the major and minor version is the same!), we simply can't reasonably determine whiche one is later.

Therefore, in this case, we need to act as if a migration is needed and then let the migration tools check each script one-by-one

**Comment by metas-dh** [comment]
checked with metas-ts: OK

**Comment by metas-lc** [comment]
can be moved to done
