### ISSUE TITLE
Window Design WebUI: Adjust Sales Invoice Window Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2271]
### Is this a bug or feature request?
fr
### What is the current behavior?
The Look & Feel of Sales Invoice WIndow is not matching the current concept in MainView, GridView, and Subtabs.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/1994
### What is the expected or desired behavior?
1. all included tabs should have white background (atm all are without)
2. check why date and doctype filters are missing only on mf15
3. other: attributes are mandatory. I think they shouldn't be. When you create a new line manually, the document is not saved if you don't add an attribute

**Comment by metas-rc** [comment]
Results of IT

* OK: The included tabs have white backbrounds

*NOK: The Date and DocType filter are missing from mf15cloudit even if they exist on w101.

* M_AttributeSetInstance problem persists. Follouwp created: https://github.com/metasfresh/metasfresh-webui-api/issues/614

**Comment by metas-rc** [comment]
Results of IT

* OK: The Date and DocType filters were added.
