### ISSUE TITLE
Payment Selection as real Document

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2273]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Payment Selection is not a real document with common document actions/ status.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Refactor Payment Selection so that it becomes a real document.

**Comment by teosarca** [comment]
Please consider implementing https://github.com/metasfresh/metasfresh/issues/2432 first and then use that process to transform payment selection.

**Comment by metas-lc** [comment]
IT
1. created/completed a new sales invoice.
2. went to payment allocation for and made a Payment Selection from there
3. opened Payment Selection from swing and webui
=> both sides have doc actions
4. select the dropdown
=> you can void or complete
=> void not implemented yet: "The action VoidIt is not implemented for PaySelection documents"
=> if you complete, then the document becomes readonly and the actions to create allocations are now available OK
5. see the docactions after you complete
=> reactivate and close - both work fine OK
