### ISSUE TITLE
Window Design WebUI: c_activity

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2280]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Activity does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2232
### What is the expected or desired behavior?
TODO: 
1. see why Cost Center is missing from menu in mf15 (you can only open it with direct link)
2. see why description is not in ui element group in mf15
3. when you create a new cost, after you add a name, the search key should be set by default

**Comment by metas-rc** [comment]
Tesults of IT

* The window Cost Center respects our cosnercases.
* 1) OK : The Cost Center window appears in the menu. It can be found via search and it can bee seen in the whole tree under the FINANCE header.
* 2) OK:  The description is displayed in the main UI element group.
* 3) OK: When you create a new cost, after you add a name, the search key is set by default
