### ISSUE TITLE
Window Design WebUI: Product Costs

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2281]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Product Costs does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
ssee https://github.com/metasfresh/metasfresh/issues/2229
### What is the expected or desired behavior?
TODO:
gridview - order by name asc

**Comment by metas-rc** [comment]
Results of IT

The window Productcosts respects our cornerstones.
Its included tabs have white background.
In gridview, the entries are ordered by name, ascending.
