### ISSUE TITLE
Window Design WebUI : Purchase candidate Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2282]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Purchase Candidate does not respect our corner stones and layout conventions
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2050
### What is the expected or desired behavior?
1. included tabs - add white background
2. doc view, bottom right: client and org are a bit higher - move them lower

**Comment by metas-mk** [comment]
> included tabs - add white background

done

> doc view, bottom right: client and org are a bit higher - move them lower
decided to not do that in this window to have comparable fields on same level in 2nd section
