### ISSUE TITLE
Window Design WebUI : Order Candidates Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2283]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Order Candidates needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2184
### What is the expected or desired behavior?
included tab should have white background

**Comment by metas-mk** [comment]
Checked. Seems to be already fixed in other task. Closing.

**Comment by metas-mk** [comment]
Reopening. Improving Translations for en_US needed.

**Comment by metas-rc** [comment]
Results of IT
* OK: Sales Order Disposition windows respects our cornerstones and layout conventions.
* OK: All the fields are translated into English.
