### ISSUE TITLE
Window Design WebUI : Unit of Measure Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2285]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Unit of Measure needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2174
### What is the expected or desired behavior?
included tab should have white background

**Comment by metas-rc** [comment]
Results of IT

The window Unit of Measure respects our cornerstones.
The included tab of the window has white background.
Creating new entries and new convertions work.
