### ISSUE TITLE
Window Design WebUI : Discount Schema Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2286]
### Is this a bug or feature request?
fr
### What is the current behavior?
The window Discount Schema needs some improvements to adopt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2173
### What is the expected or desired behavior?
included tabs should have white background
value should be set by default

**Comment by metas-rc** [comment]
Results of IT

The window Discount Schema respects our corner stones.
It also has white background in the included tab. 
The value is set directly after all the mandatory fields are set.
