### ISSUE TITLE
Kunden Vertriebsmitarbeitern zuordnen

### ISSUE THREAD

**Issue by pickapea** [metasfresh/metasfresh#229]
Hallo, für uns ist es wichtig, dass die Kunden verschiedenen Vertriebsmitarbeitern zugeordnet werden können. Danke

**Comment by metas-ts** [comment]
Hallo @pickapea,
wir haben zur Zeit die Möglichkeit, einem Kunden je *einen* Vertriebsmitarbeiter zuzuweisen.
Der würden dann auch z.B. in Aufträge automatisch übernommen.
Würde das reichen?
Falls ja müsste man in eurem metasfresh nur das entsprechende Feld in Geschäftspartner-Fenster anzeigen.
Würde es reichen, wenn Norbert (@metasnw) das nach seinem Urlaub mit euch durch geht?

Viele Grüße
Tobias

**Comment by pickapea** [comment]
Guten Morgen, Tobias,

Norbert weiss schon, worum es geht, ich hab ihm vor ein paar Wochen darüber
hin und her gemailt
Und er meinte, ich möchte doch bitte zu diesem Thema ein github erstellen
:-)


Hier  meine Fragen an ihn und seine Antworten:
> 1) Als Vertrieblerin habe ich viel mit "potenziellen Kunden" zu tun. In
> vielen Systemen kann ich die als "Interessenten" anlegen. Erst, wenn sie
> tatsächlich kaufen, wandle ich sie als Kunde/Debitor um.

Es gibt ein Feld Interessent, das zur Zeit ausgeblendet ist welches genau
diesen Zweck erfüllt.
Wir können prüfen die Funktion im Standardprodukt freizuschalten so dass für
euch keine Kosten entstehen.
Dazu müsstest Du einen Github Issue hier anlegen:
https://github.com/metasfresh/metasfresh/issues


> 2) Normalerweise ist es üblich, dass Kunden eine laufende Kundennummer
> zugewiesen wird. Euer System macht das nicht automatisch, oder? Ich gebe
> die händisch bei "Suchschlüssel" ein, oder?

Das kannst Du Dir aussuchen.


> können. Kann ich die Kunden unterschiedlichen Mitarbeitern zuordnen?
Ja. Es gibt ein Feld das wir dafür schon haben.
Hier gilt ebenfalls:
Dazu müsstest Du einen Github Issue hier anlegen:
https://github.com/metasfresh/metasfresh/issues




Wenn ich Norbert richtig verstanden habe, dann müssen diese Funktionen für
uns nur frei geschaltet werden :-)


Liebe Grüße,

Barbara




Und hier ist seine Antwort:


Mit freundlichen Grüßen


Barbara Peukert


pick-a-pea

bio food


Flachsweg 6 .  D - 50933 Köln

Fon +49 (0)2234 . 8099 099

mobil +49 (0)176 . 235 42 912
Fax +49 (0)2234 . 8099 095

www.pick-a-pea.com



pick-a-pea Lindenstraße UG (haftungsbeschränkt)

Geschäftsführende Gesellschafterin: Kathrin Möntenich

HRB 69910 - Köln .  Ust-Id: DE 272905693 .  Köln-West



pick-a-pea ist Mitglied im Verband der nachhaltigen Unternehmen *Das selbe
in Grün www.dasselbe-in-gruen.de <http://www.dasselbe-in-gruen.de/>*

Am 21. Juli 2016 um 08:57 schrieb Tobias Schöneberg <
notifications@github.com>:

**Comment by metas-ts** [comment]
Wie bei #228 gesagt.

Apropos, nur zur Sicherheit:
Was wir hier scheiben steht öffentlich "im Internet", unter dieser Addresse: https://github.com/metasfresh/metasfresh/issues/229. github schickt Dir *auch* eine Mail, wie gesagt.

Ich möchte nur sicher gehen, dass es euch klar ist, falls ihr mal eine Aufgabe für uns habt, die Details enthält die nicht jeden etwas angehen.

Viele Grüße
Tobias

**Comment by metasnw** [comment]
@metas-ts after checking we just need to unhide the field in tab Kunde. Its already working as expected.
