### ISSUE TITLE
Window Layout for Picking Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2294]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is not proper Window Layout for the Picking Window in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a dedicated WebUI Layout.

**Comment by metas-lc** [comment]
IT
usual window
Kommissionier Fach

1. window name is not translated NOK
2. rest of the fields are translated in en OK
3. included tab: white background OK
4. docview: TL: important, TR: Contract Type, No. and Date, BR: org and client OK
5. gridview:  there is no name to order by so it's ok
