### ISSUE TITLE
Doc Outbound missing Columns

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2300]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the columns Doctype and created by is missing in Doc Outbound window, especially in Grid View.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Shall have those columns in Grid View. Also, check the initial order by criteria.

**Comment by metas-lc** [comment]
IT
Doctype and created by are added in Doc Outbound window (both grid and doc views)
