### ISSUE TITLE
Auto Product No when new

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2303]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Product No are not automatically provided when creating a new Product Master data record.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
When creating a new Product Master Data record, the Product No. shall be automatically calculated and provided. The record shall be saved.

**Comment by teosarca** [comment]
update: fixed for all "documents" where we have a "Value" field.
The AD_Column.IsUseDocSequence is considered.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Create new product: 
 * product no. is automatically calculated and provided: OK
 2. save: 
 * new product is saved with that product no.: OK
3. Checked for price system as well, works the same: OK
