### ISSUE TITLE
New Action: Create new Product Prices from selected Pricelist Version

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2304]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to create new Product Prices from a selected Pricelist Version.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create an action that does exactly what the button in Pricelist Version did before.

**Comment by teosarca** [comment]
note to IT: to be tested after https://github.com/metasfresh/metasfresh-webui-frontend/issues/1279 is fixed

**Comment by metas-lc** [comment]
IT
1. created new price system
2. created new price list and version
3. on version: set Discount Schema: Preislisten kopieren
and Basis Pricelist Version to an existing plv
4. while being in Pricelist Window, select the plv line, go to actions and select Create price list
5. go to product prices and filter for your pricelist version
=> the products are copied OK
