### ISSUE TITLE
Create GL Journal No. automatically when new

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2305]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the GL Journal No. is not created automatically when new.
#### Which are the steps to reproduce?
Open Window, create a new Entry. The No. is not automatically created and set.
### What is the expected or desired behavior?
The GL Journal No. shall be created automatically.

**Comment by teosarca** [comment]
note to IT: full regression on GL_Journal is needed

**Comment by metas-lc** [comment]
IT
1. add all mandatory fields => No. is set auto OK
2. regression

**Comment by teosarca** [comment]
fixed; the test case which was failing is when you are trying to save a GL_Journal which does not have GL_JournalBatch_ID set (the webui case)

**Comment by metas-lc** [comment]
IT
regression: 
i can now save a gl journal, but i can't add lines without issues: 
https://w101.metasfresh.com:8443/window/540356/1000000
on the tab it says "Mandatory field DR_Tax_Acct_ID not filled"

**Comment by metas-mk** [comment]
Did some adjustments to Mandatory overwrite fields in Tax Fieldgroup. Still no success. Needs to be debugged.
