### ISSUE TITLE
Period mass actions missing in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2306]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility to open/ close all document actions at once in Period Window in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add a new Action to the Period Window and allow the mass actions.

**Comment by metas-dh** [comment]
Results of IT1
tested in w101

* possibility to open / close all document actions at once in period (Calendar Periods): OK
* open / close action opens / closes all document actions for a period when run: OK
