### ISSUE TITLE
Window Period adjustments, add missing Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2307]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The window Period needs some improvements to adapt our cornerstones and layout conventions.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Adapt the window to our current design guidelines and add missing translations.

**Comment by metas-lc** [comment]
IT
usual window
Calendar Periods

1. gridview: usually it;s order by Name asc, but can't apply here. It's ordered by year and period no desc OK
2. docview: TL: important, mandatory, TR: isActive, BR: org, client OK
3. advance edit looks ok, just like doc view
4. included tab: white background
5. translations: all fields are translated in en
