### ISSUE TITLE
Customer Invoices and Invoice Candidates adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2311]
### Is this a bug or feature request?
feature Request
### What is the current behavior?
Currently, the Windows in WebUI for Customer Invoices and Invoice Candidates are not fine-tuned completely. A few adjustments are needed.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the columns widths in Grid View (Invoice + Candidates). Add Action for Invoice Generation (Candidates). Renaming window to "Rechnungsdisposition" (for Candidates and de_DE), and more details.

**Comment by metas-lc** [comment]
IT
sales invoice - doc type window
1. doc view  
TL: mandatory, important  OK
TR: doctype, docno, date OK
BR: org, client OK

2. grid view:
first: doctype, docno, date OK
last: status, org OK
order by:  docdate desc OK

3. filters
date, bp, no, doctype OK

4. names:
Document Type OK
No. => OK
Date => OK
Status => OK

5. included tabs
fields in 1 element group
white background
OK 

6. translations OK

II. Invoice Candidates - usual window

1. doc view  
TL: mandatory, important  OK
TR: isactive, flags NOK
BR: org, client NOK

5. included tabs
fields in 1 element group
white background
OK 

6. translations 
Zu ber. Menge abw. erl. (see advance edit) NOK

7. Action for Invoice Generation (Candidates). 
=> Generate invoices (Auswahl Fakturieren) OK

8. Renaming window to "Rechnungsdisposition" OK

Created follow-up: https://github.com/metasfresh/metasfresh/issues/2783
