### ISSUE TITLE
Sales Order detail adjustments from User Feedback

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2314]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few improvements to be done for Sales Order Window. Thanks for the Feedback given from users.
#### Which are the steps to reproduce?
Open the Sales Order Window and see.
### What is the expected or desired behavior?
Adjust the following in Sales Order Window:
a) Add the Listprice to Sales Order Lines
b) Add Shipment Location, PO Reference, Drop Location in main Grid View.
c)  Take out the Business Partner Relations Action from Sales Order Window.

**Comment by metas-rc** [comment]
Results of IT

* OK: List Price is displayed in order lines
* OK:  Add Shipment Location, PO Reference and  Drop Location are displayed in the main Grid View.
* OK: All actions for the sales order window are specific processes for the sales order. Partner relations not included.
