### ISSUE TITLE
Improvement of Delivery Days Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2317]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window Delivery Days needs some improvement in WebUI. The Column "Location" is missing in Grid View. Column width in Grid view is not optimum.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adapt the window Delivery days as described in current behavior.

**Comment by metas-rc** [comment]
Results of IT

Some of the fields in Delivery Days window are not translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/2626
