### ISSUE TITLE
Purchase Order detail adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2337]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few changes to be done in Purchase Order to make it more focused for the procurement user.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Field drop shipment to Grid View. Remove Invoice from in Grid View.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* drop shipment added to Grid View, invoice from not displayed anymore: OK
