### ISSUE TITLE
Relation Type: fact_accounts

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2338]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In swing client, it was possible to press a button and see the accountings for a filters document (Posted Button). In WebUI, we don't have this functionality until now.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a relation Type for Documents that allow opening the fact_accounts (accounting transactions, window/162) window in WebUI filtered by the document. The posting relation shall be shown in referenced documents.

**Comment by metas-lc** [comment]
IT
checked in shipment, sales and purchase invoice, receipt and payment
=> all had relations to fact acct (Accounting Transactions window id 162) OK
