### ISSUE TITLE
New Window in WebUI for Changelog

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2339]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility in WebUI to see the change log of a record.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a window that shows the change logs.

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* new window for Change Log, in System: OK
