### ISSUE TITLE
Relation Type: changelog

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2340]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility in WebUI to see the change log of a record.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a relation Type for Records that allow opening the change-log window in WebUI filtered by the record. The change log relation shall be shown in referenced documents.

**Comment by metas-lc** [comment]
IT
go to Role, select the one you are currently using - advance edit - set Maintain Change Log on Y
go to a window for a table that has change log - e.g. sales order
modify some fields there, go to related documents
=> there is SYSTEM ->Change Log (#7) OK
(7 is the number of changes i did - logs that were created)
pres on change log => change log window opens for my order OK
