### ISSUE TITLE
java.math.BigDecimal Exception when using process quotation to sales order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2345]
### Is this a bug or feature request?
bug reported by mafi

### What is the current behavior?
works fine in webui but exception is thrown in java client and sales order is not created

#### Which are the steps to reproduce?
1. create a new quotation and complete it
1. use process sales order from quotation (Auftrag aus angebot)
1. NOK: Error message

stack trace: https://forum.metasfresh.org/t/problem-beim-erzeugen-eines-auftrags-aus-einem-angebot/618/3?u=metasnw

**Comment by metasnw** [comment]
It on w101 was OK. Bug is fixed

**Comment by metas-ts** [comment]
Cherry-picked the commits from Teo's PR https://github.com/metasfresh/metasfresh/pull/2336 in to the `release` branch
