### ISSUE TITLE
Add BPartner Value to Material Receipt Label

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2348]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the BPartner value is not printed to the Material Receipt Label
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the BPartner Value to vendor and Producer Section (aligned bottom right above the dotted line)

**Comment by metas-lc** [comment]
IT
bpartner walue is set OK
