### ISSUE TITLE
Fix AD_Column of C_BPartner.AD_OrgBP_ID

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2349]
### Is this a bug or feature request?
Bug

### What is the current behavior?

Due to a recent [change](9f6ba628e3a77e3bbbc3eb962bc3f52009fdd3a1), `C_BPartner.getAD_OrgBP_ID()` throws a class cast exception

#### Which are the steps to reproduce?

it happens e.g. when a counter-doc is completed, but you can just believe me :-)

### What is the expected or desired behavior?

should work.
to make it work, change this Reference from `Button` to `Table`:
![image](https://user-images.githubusercontent.com/1264789/30062016-f4e11acc-9249-11e7-9f57-9d9a42cde424.png)
and unset the process.
According to @metas-mk we already have an alternative action. Please make sure what it is and that it works, and if the process from the screeshot is then obsolete, please delete it

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* process for bpartner, Mit Organisation verknüpfen: no more button, but still available in Gear & menu: OK
* counter documents still correctly created automatically: working fine on live system, acc. to ts: OK
