### ISSUE TITLE
Invoice Customer window adjustments for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2352]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Invoice Customer needs some detail improvements.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Optimize the Column width in Grid View. Add the actions for Creditmemo and more to Action menu.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Optimize the Column width in Grid View: all column headers displayed, no cut-offs: OK
* Creditmemo and more to Action menu: Credit memo (Gutschrift erstellen) and Nachbelastung are available in Action menu: OK
