### ISSUE TITLE
Invoice Candidates Window in WebUI detail improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2353]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window for Invoice Candidates needs some detail improvements in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Optimize the column width. Rename to "Rechnungsdisposition" in de_DE. Add action "Freigabe zur Fakturierung". Adjust look & Feel like shipment candidates for override Fields.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Optimize the column width: OK
* Rename to "Rechnungsdisposition" in de_DE: OK
* Add action "Freigabe zur Fakturierung": OK
* Adjust look & Feel like shipment candidates for override Fields: OK
