### ISSUE TITLE
LU has HU_Status Active after picking

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2354]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* After picking an LU with TUs on it and processing the picking, the TUs have the correct status picked, but the LU stays with status Active.
#### Which are the steps to reproduce?
* Create a sales order: 1 TU, some CUs, on warehouse a certain X , complete.
* Create a purchase order with the same TUs and CU, complete, create receipt for it, for the same warehouse X.
* Go back to the sales order, open the Picking Terminal (Prototype)  for it
* Pick HU, Select the LU
* Process the picking
* Check the handling units' HU_Status
** OK: TUs have status Picked
** NOK: THe LU is still Active
### What is the expected or desired behavior?
* They shall all be Picked

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

tested together with #1172 (also see steps above):
* HU Status of LU after picking: Picked, OK
* HU Status of TU after picking, with TU as top-level HU: Picked, OK
