### ISSUE TITLE
exception when using process quotation to sales order with parameter complete order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2357]
### Is this a bug or feature request?
bug

### What is the current behavior?
if you tick complete order in process new sales order is not created with messsage 

![image](https://user-images.githubusercontent.com/16079655/30059736-a73bbd8a-9240-11e7-86cd-39b4d6658796.png)

Error: Document does not have...
Server error
Document does not have expected status (Expected=CO, actual=IP) document: Standardauftrag 2432 Belegverarbeitung: CO

#### Which are the steps to reproduce?
1. https://w101.metasfresh.com:8443/window/143/1005935
1. follow this manual http://docs.metasfresh.org/webui_collection/EN/Quotation_to_SalesOrder.html
1. set "abschließen" = Y 

### What is the expected or desired behavior?
either should work without exception or we disable the parameter as its not important anyway

**Comment by cristinamghita** [comment]
Fixed punctual, but the general fix is related to this: [#2656 Null values aren't set from database ](https://github.com/metasfresh/metasfresh/issues/2656)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* using process quotation to sales order with parameter complete order: no exception, sales order is created (and completed): OK
* using process quotation to sales order without parameter complete order: also still OK
