### ISSUE TITLE
translate process quotation to sales order to en_US

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2358]
### Is this a bug or feature request?
feature 

### What is the current behavior?
not translated

#### Which are the steps to reproduce?
follow http://docs.metasfresh.org/webui_collection/EN/Quotation_to_SalesOrder.html

### What is the expected or desired behavior?
shall be in EN

**Comment by metas-dh** [comment]
Results of IT1

* process  is translated to en_US
