### ISSUE TITLE
Invoice Candidates Action Approval for Invoicing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2361]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Process "Approval for Invoicing" is included in the right Facettes Bar.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a Process for that and include to Action Menu in WebUI Invoice Candidates table.

**Comment by teosarca** [comment]
See de.metas.invoicecandidate.callout.IC_ApproveForInvoicing_Action.execute0()

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Have a couple of invoice candidates, e.g. from a purchase order with several material receipts
2. Open invoice candidate window, select >1 invoice candidate
3. Click Action menu: "Approve for invoicing" is available: OK
4. Select the invoice candidates you want to invoice, and select "Approve for invoicing" in Action menu: process is started, OK
5. Check the invoice candidates from your order: marked as approved for invoicing, OK (atm, only Swing Client includes that checkbox!)
6. Select the approved ICs plus additional ones
7. Select generate invoices in action menu, and check the checkbox for approved ICs only
8. Check the invoice that was created: only the ICs were invoiced that were approved for invoicing, the other ICs that were selected are not included: OK
9. Select more ICs and approve them for invoicing
10. In Filter, search for "Freigabe zur Fakturierung": the ICs approved the 2nd time are displayed, OK

**Comment by teosarca** [comment]
imho we shall introduce the "Freigabe zur Fakturierung" (approved for invoicing) as a standard filter.

**Comment by metas-dh** [comment]
follow up: #2517
