### ISSUE TITLE
Default Reports to WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2362]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the default Reports are not added to WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the default Reports to WebUI Menu.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

missing reports:
* Einkaufs- & Verkaufsstatistik: will be provided in https://github.com/metasfresh/metasfresh/issues/2453
* Kostenstellenwechsel: will be provided in https://github.com/metasfresh/metasfresh/issues/2453
* Packing Items Preview Report will also be provided in https://github.com/metasfresh/metasfresh/issues/2453
* what about Offene Posten Fibu and Rüstliste?
