### ISSUE TITLE
Rename all Windows with suffix "kandidaten" to suffix "disposition"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2365]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have windows with the de_DE Name and suffix "kandidaten" and others with "disposition"
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Find those windows and change the names to suffix "disposition"

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* windows like invoice candidates or material receipt candidates: now have suffix "disposition" in de_DE: OK
* remaining window with "kandidaten": C_Invoice_Clearing_Alloc: OK?
