### ISSUE TITLE
Price Topic improvements in Product Price and Pricelist

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2370]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
There are a few detail improvements to be done in pricing topics.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Translate the Action for Calculate SeqNo in Pricelist. Order By Pricing System name in Product Prices.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Translate the Action for Calculate SeqNo in Pricelist:  ".Zeilen Nr. aktualisieren", OK
* Order By Pricing System name in Product Prices: OK
