### ISSUE TITLE
Detailed Improvements in different Finance Functionalities

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2372]
### Is this a bug or feature request?
Feature Requests
### What is the current behavior?
Currently, there are a few Improvements left to be done in Finance Section.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
These adjustments shall be done:
a) Bankstatement Window: Add actions “Bankauszugszeilen aus ESR Zahlungsimport, "Bankauszugszeilen aus Zahlung anweisen", "Bankauszüge abgleichen”
b) Dunning Window:Aktion “Process dunning” einfügen und übersetzen
c) Dunning Dispo: Actions “ create/update duning candidates, process dunning candidates, set dunning grace” translations

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

a) Payment Window: Add actions “Bankauszugszeilen aus ESR Zahlungsimport, "Bankauszugszeilen aus Zahlung anweisen", "Bankauszüge abgleichen”:  not found!
b) Dunning Window:Aktion “Process dunning” einfügen und übersetzen: "Mahnungen verrbeiten", OK
c) Dunning Dispo: Actions “ create/update duning candidates, process dunning candidates, set dunning grace” translations: "Mahnkandidaten erstellen / aktualisieren", "Mahnkandidaten verarbeiten", "Mahnkarenz setzen": OK
