### ISSUE TITLE
Detail adjustments to Shipment Candidates Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2374]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Shipment Candidates needs some few improvements to be done for a better user experience.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the possibility to override the Packing Instruction. Rearrange the Advanced edit section.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* possibility to override the Packing Instruction: Packvorschrift abw., OK
* Rearrange the Advanced edit section: ?
