### ISSUE TITLE
Detail Improvements to Order Candidates Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2376]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Order Candidates Window in WebUI needs some improvement.
#### Which are the steps to reproduce?
Open the Order candidate window and shipment candidate window and compare the concept.
### What is the expected or desired behavior?
The Order Candidates Window shall have a similar concept as the Shipment candidates Window in WebUI.

**Comment by metas-rc** [comment]
Results of IT

The window Purchase Candidate respects our cornerstones and is similar with the SHipment Schedule one.

Some of the fields are not translated into english. Followup created : https://github.com/metasfresh/metasfresh/issues/2603
