### ISSUE TITLE
Procurement candidates detail Improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2378]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a few detailed improvements are missing in Purchase Order Window and Procurement Candidates Window in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Detailed improvements:
a) Actions missing (create Purchase Orders, update prices)
b) promised, ordered Field visibility

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Action Update Prices: OK
* promised, ordered Field visibility: OK
* Action create Purchase Orders: will be provided in https://github.com/metasfresh/metasfresh/issues/2379
