### ISSUE TITLE
Procurement Candidates generate Purchase Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2379]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Process "Create Purchase Order" is included in the right Facettes Bar.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a Process for that and include to Action Menu in WebUI Purchuremend Candidates table.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15/sp80

* "Create Purchase Order" included in Action Menu: Action button for Create Purchase Order in procurement candidates window, in mf15: OK

**Comment by metas-dh** [comment]
update:
* "Create Purchase Order" included in Action Menu: no Action button for Create Purchase Order in procurement candidates window, also not avaliable in Action Menu in sp80: NOK
