### ISSUE TITLE
Detailed Improvement of Flatrate Term window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2381]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a few detail changes are wanted in Flatrate Term window.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjustments:
a) Action: Create new Term
b) Field: enddate missing
c) subtab: qty and prices missing
d) subtab: sorting costs, quality issues missing
e) report: "Vereinbarung Anbauplanung" /de_DE name) missing

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

a) Action: Create new Term: available now, OK
b) Field: enddate missing: now included, OK
c) subtab: qty and prices missing: now included in subtabs, OK
d) subtab: sorting costs, quality issues missing: in which subtab?? not found!
e) report: "Vereinbarung Anbauplanung" /de_DE name) missing: now available in Actions, OK
