### ISSUE TITLE
New Window for M_PickingSlot in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2385]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window in WebUI that shows the data for Picking Slots (M_PickingSlot).
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Window for M_PickingSlot and add to WebUI menu in Logistics.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for Picking Slot, in Logistics menu: OK
* when opening the window from menu, the order is: slot 115, 102, 101, 103, 104 etc. (all empty); why?
