### ISSUE TITLE
New Window for M_PickingSlot_Trx in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2386]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window in WebUI that shows the data for Picking Slot Transactions (M_PickingSlot).
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Window for M_PickingSlot_Trx and add to WebUI menu in Logistics.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for Picking Slot Trx (Kommissionier Fach Trx), in Logistics menu: OK
