### ISSUE TITLE
Autocomplete for zip / postal code and city

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2387]
### Is this a bug or feature request?
feature

### What is the current behavior?
dont have it

### What is the expected or desired behavior?
when editing a new or existing address the system should autocomplete postal code and city

1. entering a part of postal code, part of city or a combination of both shows valid combinations of postal and city where the user can select from

e.g.
531 => 53179 Bonn
Bo =>  53179 Bonn
53 Bo => 53179 Bonn
Bo 31 => 53179 Bonn

Questions
1. shall we ask an online service or import the data into c_postal ?

### Configuration
Enable this functionality via de.metas.ui.web.address.UsePostalLookup sysconfig.

**Comment by metas-mk** [comment]
We built/ wanted to build something similar in the past. The Table we created is c_postal. This table can take the combinations of all existing City-Postal No. 
When entering a new combination - can be done w/ lookup "new Postal/ City" (similar behavior like proposing new Businesspartner in Sales Order) then the data shall be stored in that table.
Important: Currently the Lookup Fields only provide a search of tokens in exactly the same sequence as typed. For the city-postal search, the sequence typed shall not matter.

**Comment by metasnw** [comment]
@metas-mk I am not sure if customers want the user to create new combinations as 
1. the data we have is pretty complete 
1. users rather create new combinations than checking if they might have a typo in the zip
1. admins want to maintain zip and city combinations to have control over it as some orgs and sales team use it to assign sales reps or the target org

I would suggest to provide adding new combinations for the user to second iteration

**Comment by teosarca** [comment]
Note to IT:
* by default this functionality is disabled (see de.metas.ui.web.address.UsePostalLookup sysconfig)
* regression: pls test and make sure editing addresses still works when this feature is disabled

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* by default the functionality is disabled: OK
* postal codes with cities get suggested when you start writing e.g. "51" (only CH data atm): OK
* postal codes with cities get suggested when you start writing e.g. "be" (only CH data atm): OK
* country is set accordingly after selecting a postal code (atm, only CH): OK
* creating & editing an address is working as before when functionality is disabled: OK

=> not all CH postal codes are available yet, e.g. 4001 or Basel was not found
