### ISSUE TITLE
edi problem for customer returns

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2389]
### Is this a bug or feature request?
Bug
### What is the current behavior?
if an 
* shipment was send via EDI
* and a customer return was made for that shipment
* then that customer return can't be reversed because of the original EDI-send inout's EDI_Desadv

**Comment by metas-ts** [comment]
needs to be CPed to branch `2017-09-12`

**Comment by metas-ts** [comment]
cherry-picked to branch `2017-09-12`

**Comment by metas-lc** [comment]
IT
1. tested importing EDI -> inout with HU -> customer return -> storno customer return => worked fine OK
2. tested without EDI file, just sales order with EDI customer and checkbox set -> inout with HU -> customer return -> storno customer return => worked fine OK
