### ISSUE TITLE
copy report.properties for purchase order to dist repo

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2396]
### Is this a bug or feature request?
feature request

### What is the current behavior?
1. its not possible to change labels on dist level for purchase order
e.g. metasfresh\de.metas.fresh\de.metas.fresh.base\src\main\jasperreports\de\metas\docs\purchase\order
1. removing Rekapitulation from "summary="

#### Which are the steps to reproduce?
metasfresh-dist\de.metas.endcustomer.mf15.base\src\main\jasperreports\de\metas\docs\purchase\order

does not contain report_de_DE.properties or report_de_CH.properties , etc.

### What is the expected or desired behavior?
copy all purchase order .properties to /dist so we can change them there without affecting other dists

**Comment by metas-ts** [comment]
CPed into `release` branch

**Comment by metas-rc** [comment]
Moving to done after talking with Torby.
