### ISSUE TITLE
Import and Store Contract meta-data e.g. startdate on flatrate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2397]
### Is this a bug or feature request?
feature request

### What is the current behavior?
you can import flatrate terms for a period (thanks to #2224) but not meta data like start and enddate of a contract

#### Which are the steps to reproduce?
try to import a contract with start date 01.01.2001 and store it somewhere where the user can actually find it
 
### What is the expected or desired behavior?
1. add two new fields to flatrate import (I_Flatrate_Term)
* ContractStartDate
* ContractEndDate
2. store them in flatrate data, i.e. C_Flatrate_Data.ContractStartDate, ContractEndDate
(see de.metas.flatrate.impexp.FlatrateTermImportProcess.importRecord(IMutable<Object>, I_I_Flatrate_Term))
3. don't forget to update the Subscriptions import format

### More info
The subscription import window and import process are:
![image](https://user-images.githubusercontent.com/1244701/30209672-fa0f50d6-94a1-11e7-962d-124684a070ca.png)

To import a new file, use the Import File Loader:
![image](https://user-images.githubusercontent.com/1244701/30209812-8d1b3048-94a2-11e7-93b2-f1f8dd12bba0.png)

**Comment by cristinamghita** [comment]
* add MasterStarDate and MasterEnd in C_FlatRate_Term
** Added the fields in all windows; webui also
* Tested with file :
`G0001,Lagerkonferenz (Karotten),2017-01-01,2017-03-03,P002737,3.45,G0001,2016-12-27,2017-04-04`

**Comment by metasnw** [comment]
IT worked fine.
