### ISSUE TITLE
Reverse Correct of Disposal takes too long

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2398]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Reverse Correct an existing Disposal Document. Takes > 30s.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
The Document reversal must be much faster.

![image](https://user-images.githubusercontent.com/13365687/30211370-1780ae36-94a1-11e7-92cf-805aa4fd6429.png)

**Comment by metas-ts** [comment]
implement in `2017-09-12` merge to `master`

**Comment by metas-lc** [comment]
IT
reverting a disposal works fast. The document also refreshes and you can see the new status OK
