### ISSUE TITLE
uom in customer return lines

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2399]
### Is this a bug or feature request?
bug
### What is the current behavior?
uom piece is set by default when you want to create a new line, even if the product is on kg
#### Which are the steps to reproduce?
1. go to customer return window and create a new one
https://w101.metasfresh.com:8443/window/53097
2. add all mandatory fields, doctype Kundenwarenrückgabe
3. add a line with a kg product (topinambour), add HUs
=>
Error: Ihr Test hat einen...
Server error
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
 Bitte leiten Sie diese Meldung an metas weiter: Error: Failed to convert Qty=10.000000000000 of product=P002748 from UOM=Kilogramm to UOM=Stück

### What is the expected or desired behavior?
we need a callout that when you add a product, the uom to be set directly, accordingly

**Comment by metas-ts** [comment]
cherry-picked to branch `2019-01-12`

**Comment by metas-lc** [comment]
IT 
tested the testcase above in both swing and webui => works fine, the uom is set accordingly to product's uom OK
