### ISSUE TITLE
discount in manual sales invoice

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2400]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you set discount in manual sales invoice, it's not taken in consideration on total
#### Which are the steps to reproduce?
1. create new sales invoice
2. add a product, qty, price
=> see total: qty x price OK
3. add discount (rabatt), see total
=> nok: didn't change, still like in step 2
### What is the expected or desired behavior?
shall consider discount

**Comment by cristinamghita** [comment]
**Dev Test**
* create a sales invoice (swing and webui)
* set a discount an invoice line => the priceActual is recomputed also linenetAmt and in than the total

**Comment by metas-lc** [comment]
IT
I. Swing
Manual invoice
1. create a manually sales invioce. Add a product, qty and price. => line net amt is qty*price OK
2. add a discount, save => line net amt = (qty* price) - (qty*price*discount/100) OK
3. complete the invoice => line net amt is still the same as in step 2 OK

invoice from order
1. create a new sales order.  Add a product, qty, price and discount
=> line net amt = (qty* price) - (qty*price*discount/100) OK
2. complete the order, create inout and then create invoice
=> invoice's line net amt = (qty* price) - (qty*price*discount/100) OK

II.
Webui

repeat the same testcases on webui
=> worke the same OK

note: i tested only sales part, because the puchase part doesn't have the discount field
