### ISSUE TITLE
vendor return with quality discount 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2401]
### Is this a bug or feature request?
bug
### What is the current behavior?
vendor return has product line doubled when it has quality discount lines (after storno+ return again)
#### Which are the steps to reproduce?
<strike>
1. create an inout with quality discount
2. create vendor return for it
=> vendor return created for both lines: normal product and quality discount
3. storno vendor return
4. create vendor return again
=> you have the quality discount line doubled NOK
</strike>

Testcase 1
1. create an inout with quality discount
2. create vendor return for it
=> vendor return created for both lines, in 1 line: normal product + quality discount
=> we want 2 lines, just like in receipt

testcase 2
1. create purchase order, go to receipt schedules 
2. open 1 LU / 1 TU / 5 or 10 CUs, add quality attributes, craete inout
3. close and open the line again, 1 LU / 1 TU / 5 or 10 CUs, don't set quality discount. Create inout
4. close and open the line again, this time using korrectur, select vendor returns for BOTH LUs
=> the inout is created ok
5. storno this vendor return, and create it again, same as in step 4
=> nok; the first line gets doubled

### What is the expected or desired behavior?
only 1 line for quality discount (+ the other one for normal product which already works)

**Comment by metas-ts** [comment]
cherrypicked to branch `2017-09-12`

**Comment by metas-ts** [comment]
also cherry-picked PR https://github.com/metasfresh/metasfresh/pull/2424 into branch `2017-09-12`

**Comment by metas-lc** [comment]
IT
1. repeated testcase 1 OK
2. repeated testcase 2 OK
