### ISSUE TITLE
New Window for C_Invoice_Clearing_Alloc in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2405]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window for C_Invoice_Clearing_Alloc is a Tab in Running Contracts Window and not available in WebUI because it's on 3rd Level.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a separate window for C_Invoice_Clearing_Alloc and let the User Reach it from the corresponding Included Tab lines in new Contract Window in WebUI. Probably a new relation is needed too. Please check.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for C_Invoice_Clearing_Alloc /Vertrag Rechnungskandidaten) in WebUI: OK
* corresponding Included Tab lines in new Contract Window??
