### ISSUE TITLE
Translate included Subtabs of Contract Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2407]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the included Subtabs of Window Contract are not translated to en_US
#### Which are the steps to reproduce?
Open the Contract Window via Menu and see.
### What is the expected or desired behavior?
Translate the Fields in included Subtabs of Contract window to en_US

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Subtabs of Contract Window in WebUI: all translated to en_US
