### ISSUE TITLE
Contract Date and Contract DocumentNo

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2408]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Contracts don't have a Contract Date and Contract DocumentNo
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add new Fields to Contract, Contract Date, and Contract DocumentNo and add them to WebUI Window and Main view.

**Comment by metasnw** [comment]
@metas-mk just for info: there is also this related issue in the same direction maybe #2397 that brings new fields to be shown on contract data but I am sure you have that also on your radar ;-)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new fields Contract Date and Contract DocumentNo in contract: OK
* in window and main view: OK
