### ISSUE TITLE
OrderCheckout Jaspers display empty C_BPartner_Product.ProductName

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2412]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If ` trim(C_BPartner_Product.ProductName)=''` the OrderCheckup jasper report (i'm not sure which one I'm looking at, please check all) does not fallback, but dispays basically nothing

#### Which are the steps to reproduce?

You can check it out by setting C_BPartner_Product.ProductName to an empty string and then make an order etc for the respective BPartner.
Or I can show you on the machine of the user who reported this issue.

### What is the expected or desired behavior?

if  `trim(C_BPartner_Product.ProductName)=''`, then there should be the same fallback (to `M_Product.Name` ?) that takes place if `C_BPartner_Product.ProductName IS NULL`

**Comment by metas-ts** [comment]
cherry-picked into branch `2017-09-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Make sure OrderCheckout Jaspers are created for each sales order 
2. Go to Product window, set C_BPartner_Product.ProductName to an empty string for a product
3. Create a sales order for the resp. bpartner, using this product and check the OrderCheckout Jasper:
 => the normal product name is displayed, no empty space: OK
