### ISSUE TITLE
New Window for M_QualityInsp_LagerKonf_Version in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2416]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is only a window for the Top-Level Data available. A Window for M_QualityInsp_LagerKonf_Version is missing, same for the corresponding Subdata.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a Window for M_QualityInsp_LagerKonf_Version and add the Subtabs to it. Rearrange the WebUI window for M_QualityInsp_LagerKonf and don't show the included Subtabs there.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window M_QualityInsp_LagerKonf_Version: OK
* new window includes the Subtabs from Lagerkonferenz (Sortierkosten, Qualitätslagerausgleich, Zusätzlicher Beitrag): OK
* window M_QualityInsp_LagerKonf does not include these subtabs anymore, only the one for M_QualityInsp_LagerKonf_Version: OK
* window M_QualityInsp_LagerKonf displayed twice in menu, but same in Swing!
