### ISSUE TITLE
Problem with FilterWarehouseByDocTypeValidationRule in M_ReceiptSchedule

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2417]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In `M_ReceiptSchedule.M_Warehouse_Dest_ID` has two validation rules
* `M_Warehouse_Target` which is set in the application dictionary
* `FilterWarehouseByDocTypeValidationRule` which is generally registered for columns that point to the `M_Warehouse` table.

The problem is that because of `M_ReceiptSchedule.C_Doctype` (=>target doctype for the material receipt M_InOut), `FilterWarehouseByDocTypeValidationRule` only allowes M_Waresouses that are assigned to the `MMR` doc base type.

#### Which are the steps to reproduce?

Try it out. Note that it only works if there are actually `M_Warehouse_Routing` records with the material receipt doc base type.
If the intersection of the two rules is empty, you can't select a dest warehouse.
I guess you can select the WHs taht match both rules via
```sql
select wh.* 
from M_Warehouse 
wh where
	EXISTS( 
	select *
	from DD_NetworkDistributionLine ddl
	join DD_NetworkDistribution dd on ddl.DD_NetworkDistribution_ID = dd.DD_NetworkDistribution_ID 
	where  true
		and wh.M_Warehouse_ID = ddl.M_Warehouse_ID
		and ddl.isActive = 'Y' 
		and dd.isActive = 'Y'
	)
	AND EXISTS (select 1 from M_Warehouse_Routing whr where whr.M_Warehouse_ID=wh.M_Warehouse_ID and whr.docBaseType='MMR')
order by value
```

### What is the expected or desired behavior?

I think we should extend the `IValidationRuleFactory` API to allow registering exception to the rule registered with `registerTableValidationRule()`. Then we could still register `FilterWarehouseByDocTypeValidationRule` , from swat for the general case,
but could also register an exception for M_ReceiptSchedule.M_Warehouse_Dest_ID from the inoutcandidate module

**Comment by metas-rc** [comment]
Solved in https://github.com/metasfresh/metasfresh-webui-api/issues/633
Please, move to done when https://github.com/metasfresh/metasfresh-webui-api/issues/633 passes tests
