### ISSUE TITLE
New Fields MasterStartDate and MasterEndDate in FlatRate Term

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2421]
### Is this a bug or feature request?
Feature Request
belongs to https://github.com/metasfresh/metasfresh/issues/2397
### What is the current behavior?
Currently, there are 2 new Fields MasterStarDate, MasterEnd in Flatrate Term Window. They are not shown in WebUI Window yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the new Fields to WebUI Window Main View/ grid View and as selection criteria in Filter.

**Comment by metas-dh** [comment]
Results of IT1
tsted in mf15

* new fields MasterStartDate and MasterEndDate in window FlatRate Term, in main view & grid view: OK
* as selection criteria in Filter:  filter for MasterStartDate: OK, but MasterEndDate is no filter criteria: OK??
