### ISSUE TITLE
Translation for window "Ausschreibung" in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2426]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, not all fields are translated in window "Ausschtreibung".
#### Which are the steps to reproduce?
Open the window window/315 and see.
### What is the expected or desired behavior?
Add all Translations to the window for de_DE and en_US.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* all fields are translated in window "Ausschreibung" (de_DE and en_US): OK
