### ISSUE TITLE
hide qty TU when HU name is empty

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2429]
### Is this a bug or feature request?
fr
### What is the current behavior?
when you order products without HUs, in some cases qtyTU is set. The jasper doesn't look nice
### What is the expected or desired behavior?
hide qty TU when packworschrift is empty

**Comment by metas-lc** [comment]
affected jaspers: sales order, invoice and inout; purchase order, invoice and inout
devtest: 
1. i created a purchase order with 2 products, one with HU and one without (i did this so the jasper will show me HU's qty and name. Else the headers would be hidden)
2. print jasper
=> the one without HU has qty TU empty (you can see in orderline is 1)
3. go to receipt pos and create purchase inout, print
=> the one without HU has qty TU empty (you can see in inoutline is 1)
4. create invoice for this order (make sure somehow that your HUs will get together with your product in 1 invoice)
=> couldn't test that, but shall work the same
5. create a sales order with the same qtys as your bestellung, print
=>  the one without HU has qty TU empty
6. go to picking terminal and pick the HUs created on step 3, then create a sales inout, print
=>  the one without HU has qty TU empty
7. create a sales invoice from your order, print
=>  the one without HU has qty TU empty

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1.-5.: working fine
6. & 7.: could not be tested yet, bc of https://github.com/metasfresh/metasfresh-webui-api/issues/597 & https://github.com/metasfresh/metasfresh-webui-api/issues/599

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

6. & 7.: working fine as well
