### ISSUE TITLE
Product Filter in Handling Unit Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2431]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Filter for Product on Handling Unit Editor in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Filter for Product.

**Comment by metas-ts** [comment]
cherry-picked to `2017-09-12` (note that the SQL was already applied where needed)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* filter for product in Handling Unit Editor: OK
* filtering for products working correctly: OK
