### ISSUE TITLE
Use default values for IsShipTo and isBillTo when importing bpartner

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2436]
### Is this a bug or feature request?
Feature
follow up #2218
### What is the expected or desired behavior?
When we import partners,  if we have in the import flag IsShipToDefault on Y, then go with this value also flag for flag isShipTo
And same thing for isBillToDefault , isBillTo.

**Comment by cristinamghita** [comment]
## Tested in an import context

_File used for importing partner:_
```
G0003	Testkunde gh2218				gh2218 straße 996		teststadt 3		DE	Standard	N	Y
G0003	Testkunde gh2218				gh2218 straße 995		teststadt 2		DE	Standard	Y	N
G0004	Testkunde gh2218_1				gh2218 straße 997		teststadt 4		DE	Standard	N	Y
G0004	Testkunde gh2218_1				gh2218 straße 998		teststadt 5		DE	Standard	Y	N
```
_File used for imporitng FT:_
`G0003,Abo,2017-01-01,2017-03-03,P002737,3.45,G0004,2016-12-27,2017-04-04`

**Result**
The imported FT:
![image](https://user-images.githubusercontent.com/15378036/30328696-cbf8be64-97d8-11e7-8d40-226b6cdbfd49.png)
Locations are set accordingly with the flags.

**Comment by metasnw** [comment]
IT was successful
