### ISSUE TITLE
Material Tracking adjustments in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2440]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Material Tracking Window in WebUI needs some adjustments.
### What is the expected or desired behavior?
a) New Filter for Tracking ID
b) New Filter for Business Partner
c) New Filter for Tracking Terminated
d) New Tracking Record (Lagerkonferenz)
e) Set Dates automatically

**Comment by metas-ts** [comment]
Hi @metas-mk 
i fixed the underlying issue https://github.com/metasfresh/metasfresh-webui-api/issues/585 , 
d) and e) work now (at least on my machine :-P )

**Comment by metas-mk** [comment]
Moin @metas-ts Thx. Checked. Works.

**Comment by metas-lc** [comment]
a) New Filter for Tracking ID - lotno OK
b) New Filter for Business Partner - OK
c) New Filter for Tracking Terminated - processed OK
d) New Tracking Record (Lagerkonferenz) - created new one, saved OK
e) Set Dates automatically - when i created a new record and added quality inspection, the dates (valid from/to) were set automatically OK
