### ISSUE TITLE
New Window for GL Journal Category in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2442]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window in WebUI to maintain the GL Journal Categories
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Window for GL Journal Category in WebUI-

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

new window for GL Journal Category (Haubtbuch Kategorie): OK
