### ISSUE TITLE
Adjust the window Product for Procurement Contracts

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2449]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window "Product for Procurement Contracts" does not fulfill the current WebUI design guidelines. Adjustments needed.
#### Which are the steps to reproduce?
Open the window window/540288/ and see.
### What is the expected or desired behavior?
a) Take out ProductName from Grid View (already Product Field in there)
b) Advanced edit section is visible w/o advanced edit.
c) Translations missing for en_US

**Comment by metas-lc** [comment]
IT
Product for Procurement Contracts window (usual window)
- TL: mandatory, important OK
- TR: isactive OK
- BR: org , client OK
- window is translated OK
