### ISSUE TITLE
Add missing Reports to WebUI menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2453]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a few of the default Reports are missing in WebUI or not moved to proper Report Section.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Check the following reports
a) Purchase Statistic
b) Sales Statistic
c) Cost Center Change Report
d) Packing Items Preview Report (move to Procurement)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Purchase Statistic: OK
* Sales Statistic: OK
* Cost Center Change Report: OK
* Packing Items Preview Report (move to Procurement): ?
