### ISSUE TITLE
Duplicate locations on partner import when multiple contacts

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2457]
### Is this a bug or feature request?
bug

### What is the current behavior?
when you import a partner with two contacts but the same address two locations are created

### What is the expected or desired behavior?
if location fields (e.g. zip, city, address) are the same , only one location shall be created

**Comment by cristinamghita** [comment]
*Concept*

* refactor method org.compiere.model.MBPartnerLocation.makeUnique(MLocation address) so that the algorithm can be used from outside
* Use that method to obtain the name for the address when we import
* Compare the name for the address we are importing with what is in DB, if exists, update that address.

**Estimation: 2xS**

Risk: to brake the unique name when saving locations

**Comment by teosarca** [comment]
@cristinamghita  nop, pls do as discussed.

**Comment by cristinamghita** [comment]
We will drop this and will gather addresses in context and compare fields.

**Comment by cristinamghita** [comment]
# Tests
## Test 1
Used file:
```
G0010             FNTest1    LNTest1    gh2457 straße 996        teststadt 3        DE    Standard    Y    Y
G0010             FNTest2    LNTest2    gh2457 straße 996        teststadt 3        DE    Standard    Y    Y
G0010             FNTest3    LNTest3    gh2457 straße 996        teststadt 3        DE    Standard    Y    Y
```
We have one partner, 3 contacts and one adress. We import the file and in the address is just one address. **OK**

## Test 2
Used file:
```
G0011			 FNTest1	LNTest1	gh2457 straße 997		teststadt 4		DE	Standard	Y	N
G0011			 FNTest2	LNTest2	gh2457 straße 996		teststadt 3		DE	Standard	N	Y
G0011			 FNTest3	LNTest3	gh2457 straße 996		teststadt 3		DE	Standard	N	Y
```
We have one partner, 3 users, 2 adresses. After import, in adresses, there are 2 adresses. **OK**

## Test 3
Used file:
```
G0012			 FNTest1	LNTest1	gh2457 straße 997		teststadt 4		DE	Standard	Y	N
G0012			 FNTest2	LNTest2	gh2457 straße 996		teststadt 3		DE	Standard	N	Y
G0012			 FNTest3	LNTest3	gh2457 straße 996		teststadt 3		DE	Standard	N	Y
G0013			 FNTest4	LNTest4	gh2457 straße 998		teststadt 5		DE	Standard	N	Y
G0013			 FNTest5	LNTest5	gh2457 straße 998		teststadt 5		DE	Standard	N	Y
```
We have 2 partners. First has 3 users and 2 addresses. Second one has 3 users and one address.
Import the file, and in addresses we have for first partner 2 addresses and for seconde one, just one address. **OK**

**Comment by metasnw** [comment]
IT was successful
