### ISSUE TITLE
shipto and billto contact / user 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2459]
### Is this a bug or feature request?
FR

### What is the current behavior?
today we got this fields in ad_user:

- issalescontact_default 
- issalescontact 
- ispurchasecontact_default 
- ispurchasecontact 
- issubjectmattercontact  
- isdefaultcontact 

problem: we cant distinguish between shipment and invoicing contact on sales side as there is only issalescontact + issalescontact_default 

**why we need that?**

in subscriptions we do have a billtopartner, location and user and a dropshippartner, -location, -user. in case we want to import flatrate terms and a partner has got multiple users we need to have a way to tell the user for shipment apart from the billto user.

#### Which are the steps to reproduce?
check ad_user table

### What is the expected or desired behavior?
1. add two new fields
   1. issshiptocontact_default
   1. isbilltocontact_default
1. both can be ticked only once per partner 

with this we can distinguis in future contacts relevant for sales, shipping and invoicing

**Comment by cristinamghita** [comment]
Implemented

**Comment by metasnw** [comment]
IT was successful

**Comment by metasnw** [comment]
IT was successful
