### ISSUE TITLE
Extend Partner Import to support contact flags

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2463]
### Is this a bug or feature request?
FR

### What is the current behavior?
can not import these fields from issue #2459 
- issshiptocontact_default
- isbilltocontact_default

#### Which are the steps to reproduce?
check import table and format

### What is the expected or desired behavior?
1. define in import format
1. add to import table for partner
1. can be Yes only once per partner and user

**Comment by cristinamghita** [comment]
Tested with file:

```
G0018			 FNTest1	LNTest1	Y	N	gh2459 straße 997		teststadt 4		DE	Standard	Y	N
G0018			 FNTest2	LNTest2	Y	Y	gh2459 straße 996		teststadt 3		DE	Standard	N	Y
G0018			 FNTest3	LNTest3	N	Y	gh2459 straße 996		teststadt 3		DE	Standard	N	Y
```

**Comment by metasnw** [comment]
IT was successful
