### ISSUE TITLE
Prevent User from working with the system via Docker when db migration failed

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2465]
### Is this a bug or feature request?
feature request

### What is the current behavior?
environment: docker
when a migration script fails and the update is therefore not complete 
the user still can work on the webui and its showing the updated version although not all services are fine. 

#### Which are the steps to reproduce?
1. perform an update via docker and have one script failing
1. NOK: log on to webui and everything seems fine

### What is the expected or desired behavior?
either show a message, prevent starting the services, in any case prevent the user from working on the system

**Comment by metas-jb** [comment]
Suggestion:
* don't start the processes for `webui` and `webapi` containers, until the `app` container is reachable on port `8080` internally
Similar to how the app-container currently waits for the `db` container to be ready:
```
wait_dbms()
{
 until nc -z $DB_HOST 5432
 do
   sleep 1
 done
}
```

However:
This solution is just to prevent users from accidentally logging in.

This does NOT notify the user that something went wrong. The containers will still start. Just the services won't be available.
The user will just see a blank page in case of an error when starting `app`... the other containers will be in a perpetual loop until `app` is actually reachable.
