### ISSUE TITLE
Window Design WebUI: gridview with client

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2468]
### Is this a bug or feature request?
fr
### What is the current behavior?
there still are some windows with clients in gridview

#### Which are the steps to reproduce?
(follow-up for https://github.com/metasfresh/metasfresh/issues/2013)
open: 
1. https://w101.metasfresh.com:8443/window/337?viewId=337-ef9fb5b522b74f6798556a2f4555cab9&page=1
2. https://w101.metasfresh.com:8443/window/53189?viewId=53189-2489f57f7a6a42948a72b604803d533d&page=1
3. https://w101.metasfresh.com:8443/window/139?viewId=139-f473a0a2cbfb432288be3b6d933a0e34&page=1 (subtabs accountong and locator, only on mf15)
4. https://w101.metasfresh.com:8443/window/53009 (subtabs workflow, hu assignment and attribute only on mf15)
5. https://w101.metasfresh.com:8443/window/540334/1000000 (all 3 subtabs)
6. https://w101.metasfresh.com:8443/window/105?viewId=105-ce195902b2c0474a86b02970bfd7a717&page=1
### What is the expected or desired behavior?
client shall not appear in gridview

**Comment by metas-rc** [comment]
Results of IT

* OK: Pricing schema: Client not displayed in greid view
* OK: Pricing Rule: Client not displayed in greid view
*OK: Warehouse and all it's included tabs don't have Client displayed in grid
* OK: Manufacturing Order and all it's included tabs don't have Client displayed in grid
* OK: material Schedule r and all it's included tabs don't have Client displayed in grid
*OK: Menu: Client not displayed in greid view
