### ISSUE TITLE
Window for C_Postal in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2469]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for C_Postal in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Window for C_Postal to allow the maintenance of valid Postal-City-Country combinations.

**Comment by metas-lc** [comment]
IT
Country, City and Postal window (usual)
- TL: mandatory, important OK
- TR: isactive, other flags OK
- BR: org , client OK
- window is translated OK
- advanced view looks the same OK
