### ISSUE TITLE
Subscription Import Window Adjustments

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2477]
### Is this a bug or feature request?
FR

### What is the current behavior?
1. window name does not match pattern "Import" + <Object>
1. cant search for anything

**Comment by cristinamghita** [comment]
## Results of IT
### Tested on webui
* Search in menu for import -> suggestion Subscriptions Import appears **OK**
* Create manually a new record
	* Then try to filter
	* Default filter appears and is possible to filter by Imported, processed, partner value, product value **OK**
