### ISSUE TITLE
Check Filter Sequence for Default Fields Organisation and Warehouse

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2478]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Default Filter sequence depends on the sequence of columns in a table configuration.
#### Which are the steps to reproduce?
Open any window in WebUI and see.
### What is the expected or desired behavior?
Check Filter Sequence for Default Fields Organisation and Warehouse and add the the last 2 entries of each filtercriteria in WebUI.

**Comment by metas-dh** [comment]
Closing issue since it's an old one.
