### ISSUE TITLE
HUs with wrong product displayed in HU Editor for Issue

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#2481]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Sometimes not the HUs with the selected product are shown in HU Editor for Issue, but those with another product used for production / no HUs at all.
#### Which are the steps to reproduce?
Make sure you have a PP_Order for a product that needs >2 components, and you have HUs available for production of 2 of these products, but not all of them.
 
1. open window 53009, press produzieren to start production for the PP_Order
2. select e.g. radiesli on the left side, press hinzufügen: HU Editor opens with the available HU of radiesli, OK
3. select e.g. frisée on the left side, press hinzufügen: HU Editor opens with the available HU of radiesli again, NOK
4. press Done to go back to initial PP_Order, then press produzieren again
5. select karotten on the left side, press hinzufügen: HU Editor opens with the available HU of karotten, OK
6. select radiesli on the left side, press hinzufügen: HU Editor opens with the available HU of karotten again, NOK
7. leave the modal window, then go back and select frisée on the left side, press hinzufügen: HU Editor is empty since no HUs are available: OK
8. select radiesli on the left side, press hinzufügen: HU Editor is empty again, although HUs are available: NOK
### What is the expected or desired behavior?
HU Editor shall include the available HUs of the selected product that can be used for Issue.

![2017-09-12 10_57_55-metasfresh](https://user-images.githubusercontent.com/18696715/30481314-3cb2ee4e-9a1e-11e7-810b-7bca36b6305e.png)

![2017-09-12 10_57_33-](https://user-images.githubusercontent.com/18696715/30481323-44b7bf34-9a1e-11e7-8321-fe321be14e49.png)

![2017-09-12 11_00_28-metasfresh](https://user-images.githubusercontent.com/18696715/30481326-4968eddc-9a1e-11e7-8891-81d817e22e74.png)

**Comment by metas-lc** [comment]
i created a frontend task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1214
closing this one
