### ISSUE TITLE
New Dist-Orgs Businesspartner Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2483]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
An individual Business Partner Window is needed in WebUI for dist-orgs.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Businesspartner Window in WebUI that is individually maintainable. Add to System group (like B2C Businesspartner).

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh-dist-orgs/issues/26

**Comment by metas-rc** [comment]
Results of IT

* OK: The window respects our cornerstones and layout
* There are some problems I found and created a followup for them: https://github.com/metasfresh/metasfresh/issues/2653
