### ISSUE TITLE
allow using partner product numbers and name for entering order line

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2484]
### Is this a bug or feature request?
FR

### What is the current behavior?
partner related product name and number are printed on documents (order, shipment, etc.) but you can not use them in sales order or purchase order to find products.

#### Which are the steps to reproduce?
1. create new sales order
1. go to batch entry
1. NOK: using partner product number does not bring any hits

### What is the expected or desired behavior?
a) new Virtual Column in M_Product (Businessparter Product)
b) Provide Fallback Szenario for when no Businesspartner is in Context
c) Add the new Virtual Column as Identifier for Product
d) implement the usage of context variables in SQL Columns
--> Will work in All Product_ID Fields (check potential sideffects)

**Comment by teosarca** [comment]
Update:
* implemented for Order line batch entry and Invoice batch entry
* unfortunately the suggested solution was not viable so i had to implement it in java, from scratch

**Comment by metasnw** [comment]
@teosarca I was testing on w101 this feature but I could not get it to work.
can you check my case and see if I did something wrong:
1. open https://w101.metasfresh.com:8443/window/143/1000029
1. add new product via "abcde" or "12345" in batch entry
1. Expectation: should find convenience salad as i defined partner-related value and name for "Test kunde"

**Comment by teosarca** [comment]
changes:
* now we are searching by C_BPartner_Product.ProductNo and ProductName
* we are NO LONGER searching by C_BPartner_Product.VendorProductNo
* the lookup will display only C_BPartner_Product.ProductNo

**Comment by metas-ts** [comment]
cherry-picked to `release` branch

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15releasetest

1. set different C_BPartner_Product.ProductNo and C_BPartner_Product.ProductName for 2 bpartners
2. use these for creating order and invoice lines with batch entry:
* C_BPartner_Product.ProductNo taken in sales orderline of matching bpartner: OK
* C_BPartner_Product.ProductName taken in sales invoiceline of matching bpartner: OK
* C_BPartner_Product.ProductNo taken in purchase orderline of matching bpartner: OK
* C_BPartner_Product.ProductName taken in purchase invoiceline of matching bpartner: OK
* C_BPartner_Product.ProductNo and C_BPartner_Product.ProductName NOT taken for another bpartner that has different / no C_BPartner_Product.ProductNo and C_BPartner_Product.ProductName set: OK
3. regression:
* using standard ProductNo & ProductName still work fine: OK
* for both bpartners with and without their own C_BPartner_Product.ProductNo and C_BPartner_Product.ProductName: OK

**Comment by metas-rc** [comment]
Results of IT

Retested this and it works well.
