### ISSUE TITLE
Process C_Dunning_Candidate_Process fails

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2492]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Running the process `C_Dunning_Candidate_Process` fails because of a missing C_Async_Batch_Type:
![image pasted at 2017-9-18 10-34](https://user-images.githubusercontent.com/1264789/30534826-285c8ccc-9c60-11e7-85e2-9b7ad6c7a1ec.png)

**Comment by metas-lc** [comment]
IT
go to async bathc type : there is 1 for dunning oK
process some dunning candidates => works OK
(couldn't  test yet on new data)

**Comment by metas-lc** [comment]
Testcase to create new Dunning Candidates on new database:
1. open window Mahnart (159) and create a new one: Standard, new line: Tage nach Fälligkeit 1
Tage zwischen Mahnungen 10.
2. go to your bpartner in customer tab, Payment Term: immediately (sofort),Dunning: the one you created.
3. create a new invoice date yesterday, for your bpartner (make sure it's sofort), run Mahnkandidaten erstellen/ aktualisieren
=> dunning candidate created
