### ISSUE TITLE
Prices changing in FlatrateTerms after Prolongation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2494]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to switch prices for Subscriptions after Prolongation after the first year.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Implement the possibility to prolong a flatrate Term and choose a different price for the 2nd year.

**Comment by metas-ts** [comment]
Hi @metas-mk 
i don't see why it shouldn't work..you can select a pricing system in the subscription contract's `C_Flatrate_Conditions`..i'm going to try it out..

**Comment by metas-ts** [comment]
Hi @metas-mk 
hre is an update: it does *not* work out of the box :-(,
due to legacy code that was not touched/adapted for a long time.
I'm going to fix it today

**Comment by metas-rc** [comment]
Results of IT

Please, check the test data creation and IT in this task: https://github.com/metasfresh/metasfresh/issues/2502

Everything was similar for this task, until the creation of the Contract.

* Go to created Contract and check its Pricing System ( remember it) 
* Its price is the current Price Standard for the product, currency and state in the Contract.
* GO to the Product Price where that price was set ( fit for Product, Pricing System, Location)  and change the standard price 
* Go to the Contract and open the Actions List
* Run the process C_Flatrate_Term_Extend
* OK: => There is a new Contract, not completed, with the new price.
* Change the start date in the new contract so it won't overlap with the old one
* Complete the Constract
* Check created Invoice Candidate
* => OK: It also has the right price, the one that I last set in the Product Price.
