### ISSUE TITLE
Window Design WebUI: Returns Improvements 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2498]
### Is this a bug or feature request?
fr
### What is the current behavior?
Customer Returns window - filter for doctype is missing (see mf15)
Vendor Returns window - filter for doctype is missing, order by docno desc instead of date desc (see mf15)
#### Which are the steps to reproduce?
open Customer Returns window and Vendor Returns window and see

### What is the expected or desired behavior?
on w101 works fine. Shall work like there: both windows shall have doctype filter and vendor returns grid shall be ordered by date, desc

**Comment by metas-rc** [comment]
Results of IT

The filters are corect.
The ordering is still not fixed. Followup created: https://github.com/metasfresh/metasfresh/issues/2595
