### ISSUE TITLE
Import Requests

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2501]
### Is this a bug or feature request?
Feature
### What is the expected or desired behavior?
Be able to import requests

**Comment by cristinamghita** [comment]
Tested with file:
```
G0006	eMail	offen	2008-02-02	2009-04-02	Yousty - Azubi Registrierungen	30
G0007	eMail	offen	2008-03-18	2013-01-16	Präsentation vor Ort	40
```
**Important:** 
* For RequestType use name field
* For R_Status use also name field

**Comment by metasnw** [comment]
IT worked fine
