### ISSUE TITLE
Allow multiple shipment schedules per orderline

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2502]
### Is this a bug or feature request?
Enhancement

### What is the current behavior?

Currently, shipment schedules are restricted to one per order line

### What is the expected or desired behavior?

We shall be able to create subscription-shipment flatrate terms, and the system shall one shipment schedule per delivery for them.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/2495

**Comment by metas-mk** [comment]
belongs to https://github.com/metasfresh/metasfresh/issues/2496

**Comment by metas-rc** [comment]
Data for IT: 

* Go to Contract Period window
* Create a new entry * Set a name to remember  ( I named mine "one Per Day Transition")
* Set term duration, term of notice , and their units
* Important: Set Subscription term and unit (e.g. 1 day)
* Complete the Contract Period.

* Go to Contract Terms window
* Create a new entry
* Give a name to remmber ( I named mine "Term For Multiple Shipment Schedules")
* Set the Type to Abonament
* Set the Contract Period created before
* Create a line in the included tab: Select a product category and the Contract Period from before.

* Modify the sys config C_SubscriptionProgress.Create_ShipmentSchedulesInAdvanceDays to a bigger number (e.g. 7)
* The reason for thiis is to have the shipment shcedules created before the date 

* Go to Sales Order Window
* Add a line with a product from the product category set in the term
* in the line, set Terms and Conditions to the Contract term before
* Complete the order


Results of IT

* => OK: There is  a new entry in the Contract window with product, partner etc from the orderline
* Go to the last included tab (Subscription Progress)
* =>OK:  There is one entry for each day included in the period of the contract.
* Go to Shipment Candidate window
* OK: => There are shipment schedules for all the subscription progress entries that are dated within the range of today and + 7 days ( or how many were defined in the sys config)

**Comment by metas-ts** [comment]
CPed the more recent NPE fixes to the release branch
