### ISSUE TITLE
Typo in German Translation of Contract Terms menu Entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2503]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The German Translation of Contract Terms in WebUI Window has a Typo.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Fix the Typo.

**Comment by metas-lc** [comment]
IT
Vertragsbedingungen OK
