### ISSUE TITLE
Prevent users from creating duplicate main prices

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2510]
### Is this a bug or feature request?
Enhancement

### What is the current behavior?

It does not make any sense from a functioal POV, but sues can create multiple "main prices".
A main price is a price without attributes, packagings etc.
It is for example used to get the default price UOM.

If a user creates two main prices for one PLV and product, they can do so, but later there will be `DBMoreThenOneRecordsFoundException`s

#### Which are the steps to reproduce?

E.g. 
* create two main prices
* create a new sales order line with the respective product
* select a subscription contract (`C_Flatrate_Conditions`)

=> fails with a `DBMoreThenOneRecordsFoundException` and one needs to look at the stacktrace and the exception's whereclause and params info to see wtf is going on
 => not to be excepted from a user who might have a customer on the phone right now :-)

### What is the expected or desired behavior?

* If a user enters a new main product and there is one already, throw an exception the user can understand
  * same if we hit a prexisting dublicate
* But if there are somehow preexisting dublicates, then don't hassle the user if he/she tries to
  * deactivate one of them
  * add a not-main product

**Comment by metas-rc** [comment]
Results of IT

* OK: Duplicate main prices cannot be created
* OK: Other kind of duplicate prices ( with attributes or handling units)  are allowed.
* OK: I get a human friendly error message when I try to save a duplicate in swing.
* NOK: I get no message at all when I want to do it on webui, only that the entry is invalid. No other reason. I talked with Teo and he said the solution shall be related with this task so I added the case here: https://github.com/metasfresh/metasfresh-webui-api/issues/614
