### ISSUE TITLE
Add Rüstliste Report to WebUI

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#2516]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Rüstliste is not yet included in WebUI
#### Which are the steps to reproduce?
Open and see
### What is the expected or desired behavior?
Add Rüstliste to WebUI

**Comment by metas-rc** [comment]
Results of IT

* OK: The report Rüstliste is added in the webui;
* OK: The report Rüstliste  works correctly

The name of the process and its parameters don't have English translations. Followup created: https://github.com/metasfresh/metasfresh/issues/2636
