### ISSUE TITLE
Generate Picking Document 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2525]
### Is this a bug or feature request?
FR

### What is the current behavior?
1. you can use picking terminal to pick the products (e.g. on mobile device)
1. there is no document you could print

### What is the expected or desired behavior?
print automatically a picking document for each sales order that has bereitstellungsdatum of today and which is deliverable  (basically the same as bestellkontrolle / produktionskontrolle but for delivery)

**Comment by metas-lc** [comment]
TODO: we also need to add it in https://w101.metasfresh.com:8443/window/540345
in actions, to run for the selected lines

for now, it's in menu, parameters: order, preparation date start - end

**Comment by metas-lc** [comment]
TODO: rename _v2 jrxmls

**Comment by metas-rc** [comment]
Results of IT


* I can't find this in webui.
* I found it in swing, in the menu, but I got an error when I tried to run it: 

@metas-lc : Please, check this when you have time. It it's obsolete, please, move it in done.

**Comment by metas-lc** [comment]
found a difference in barcode parameter from bestellkontrolle, so i change it like we have it there.

**Comment by metas-lc** [comment]
i think i finally found the reason.. hope it will fix it.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* Swing: opens without errors, barcode included in the jasper: OK
* got 2 cut-offs, and barcode is not really alligned with the header: NOK
* not available in WebUI

=> checked with metas-nw: not needed anymore at this point, so closing this task.
