### ISSUE TITLE
Import System users

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2529]
### Is this a bug or feature request?
Feature
### What is the expected or desired behavior?
We can import system users and assign with a role.

**Fields:**
```
firstname
lastname
name
email
issystemuser
bp.value
ad_role.name
user.value
loginname
```

**Comment by cristinamghita** [comment]
Test File
```
G0017	PW	Paul	Wagner	paul.wagner@gmail.com	paul.wagner	Y	Admin
G0016	AI	Andrei	Ionescu	andrei.ionescu@gmail.com	andrei.ionescu	Y	Admin
```

**Comment by metas-rc** [comment]
Moving to done, since client level task https://github.com/metasfresh/yo98/issues/38 is already in done.
