### ISSUE TITLE
Adjust Contract Period Window in WebUI for Subscriptions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2533]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are 2 Fields missing in Contract Period Window. Delivery Interval, Delivery Interval Unit. They are needed for Subscriptions.
#### Which are the steps to reproduce?
Open the window and see.
### What is the expected or desired behavior?
Add Delivery Interval, Delivery Interval Unit. to primary group in Main View (remove from advanced edit).

**Comment by metas-rc** [comment]
Results of IT

The window Contract Period respects our cornercases.
The fields Delivery Interval and  Delivery Interval Unit appear in the main view ( in English they are Subscription Interval and Subscription Interval Unit)
