### ISSUE TITLE
Remove legacy LDAP code

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2538]
### Is this a bug or feature request?
Enhancement

### What is the current behavior?

There are LDAP related fiels in AD_User and AD_System. Also there is an LDAP-Processor..not sure what it does. This code is around since 2006 and we never-ever used it.
It's annoying, we don't know what to do with it and it generates an lot of compile warnings.
And when we need something along the lines of "remote" autentification (which is aparently the only thing it's used for), we will rather use oauth2

**Comment by metas-lc** [comment]
can be moved to done
