### ISSUE TITLE
Translate report_en_US.properties for order, inout, invoice

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2539]
### Is this a bug or feature request?
FR

### What is the current behavior?
properties are not translated for EN leading to NULL Labels in report

#### Which are the steps to reproduce?
1. have partner with language English
1. open print view of any order, inout, invoice document

### What is the expected or desired behavior?
all labels which are working fine in DE should work also in EN

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

some cut-offs, and some missing translations (Material Receipt & Purchase Invoice have de_DE name):

sales:
* order
![2018-06-05 17_09_56-143_0004 pdf](https://user-images.githubusercontent.com/18696715/40985641-d965e044-68e4-11e8-9946-1951d9ef4415.png)

* shipment:
![2018-06-05 17_09_35-169_545147 pdf](https://user-images.githubusercontent.com/18696715/40985677-e9c92f36-68e4-11e8-856a-7c65a817d4ff.png)

* invoice:
![2018-06-05 17_09_16-167_145810 pdf](https://user-images.githubusercontent.com/18696715/40985703-f4900476-68e4-11e8-8002-78f1107f7f6d.png)


purchase:
* order:
![2018-06-05 17_15_05-181_820476 pdf](https://user-images.githubusercontent.com/18696715/40985758-13ed1ce6-68e5-11e8-80bd-ff3b2d1fc65c.png)

* receipt:
![2018-06-05 17_15_58-184_1000009 pdf](https://user-images.githubusercontent.com/18696715/40985784-1ee6db1e-68e5-11e8-8357-be698ab8d7bb.png)

* invoice:
![2018-06-05 17_27_59-](https://user-images.githubusercontent.com/18696715/40986203-efbbf08a-68e5-11e8-8cfb-c2a703ffb2b1.png)


**question:** date format is german, shall that be en_US as well?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* all cut-offs were fixed: OK
* set missing translations, all were displayed correctly in the Jaspers: OK
