### ISSUE TITLE
Mark all Value and DocumentNo columns as IsCalculated=Y

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2546]
Reason: Usually those contain generated values. When copying/cloning we don't want to copy their value but generate a new one (next one).

This task was triggered by https://github.com/metasfresh/metasfresh-webui-api/issues/54

### Query to identify all columns which have to be updated:
```
select t.TableName, c.ColumnName, c.IsCalculated, c.AD_Column_ID, c.EntityType
from AD_Column c
inner join AD_Table t on (t.AD_Table_ID=c.AD_Table_ID)
where 
c.ColumnName in ('DocumentNo', 'Value')
and c.IsCalculated='N'
and t.IsView='N'
order by t.TableName, c.ColumnName;
```

### Note to developer
* create a migration script to update those columns and set IsCalculated=Y
* change org.compiere.model.Callout_AD_Column.onAD_Element_ID(Properties, int, GridTab, GridField, Object) and in case the "Value" or "DocumentNo" set the IsCalculated flag.

**Comment by metas-rc** [comment]
Results of IT

* tried to clone each entry I could and all went fine: OK

I I found some issue in BOM's documentno while testing this and created a followup: https://github.com/metasfresh/metasfresh/issues/2869


I also found some documents that don't have a default value for the field Posted and I created a folowup: https://github.com/metasfresh/metasfresh/issues/2871

I also found some problems in the Distribution Order window and I created a followup: https://github.com/metasfresh/metasfresh/issues/2872
