### ISSUE TITLE
Menu Window improvements in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2560]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The window Menu does not have 2-Column Layout.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Improve the Window for Menu maintenance.

**Comment by metas-rc** [comment]
Results of IT

The window Menu respects our cornerstones and layout conventions.
It also has all the fields translated into English.
