### ISSUE TITLE
Order compensation groups

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2564]
### Is this a bug or feature request?
FR

### What is the current behavior?
today metasfresh uses line bases discounts 

### What is the expected or desired behavior?

1. have a way for the user to add multiple discounts that are applied to the total of an sales order in an sequence and not in total
1. discounts are displayed on order confirmation and invoice

Example: 

amount: 200
discount1: 10%
= 180
discount2: 10%
=: 162
discount3: 10%
total: 145,8

**Comment by metas-mk** [comment]
Example:

Sum LineNetAmounts: 200
discount1: 10% = -20
= 180
discount2: 10% = -18
=: 162
discount3: 10% = 16,20
total: 145,8

**Comment by teosarca** [comment]
NOTE: task is in progress, but i am committing directly to master.

**Comment by metas-dh** [comment]
Successfully tested & included in weekly e2e.
