### ISSUE TITLE
Swing Client. Window for Printing Queue does not open properly anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2576]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Print Queue Window in Swing cannot be opened.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Please Fix.
![image](https://user-images.githubusercontent.com/13365687/30897211-53588ad8-a355-11e7-86c8-b735c00b6d65.png)

**Comment by metas-ts** [comment]
..I also applied the fix on swing-user's metasfresh system

**Comment by metas-rc** [comment]
Results of IT

The Printing Queue opens correctly now. The data is displayed and there are no errors in the console.
