### ISSUE TITLE
Add Subscription history in Contract window WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2580]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Subscription history Window is not added to the Contract window as subtab.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Add the Subscription history to Contract window as subtab.

**Comment by metas-rc** [comment]
Note: I cannot test this because we lack data. I cannot create a contract -> I cannot see its included tabs.

**Comment by metas-rc** [comment]
Results of IT

* OK: The included tab Subscription History was added in the window Contract.
* OK: The included tab has white background and it respects our conventions.

I created a followup for translating everything in the Contract window to English ( this included tab also): https://github.com/metasfresh/metasfresh/issues/2666
