### ISSUE TITLE
Action/ Process to reopen processed Shipment Schedules

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2585]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to reopen processed Shipment Schedule entries when the qtyToDeliver/ qtyOrderedOverride is set to 0.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow to reopen the Shipment Schedule Entry when overriding 0 and initialize the override qty to null again.

**Comment by metas-lc** [comment]
IT
you cannot unclose it because the shipment schedule is not closed (only processed). Created follow-up since there are changes in the area introduced after this task: https://github.com/metasfresh/metasfresh/issues/3374
