### ISSUE TITLE
Make use of product documentnote on Quotation and Order Document

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2590]
### Is this a bug or feature request?
FR

### What is the current behavior?
field documentnote is existing but not displayed in window or jasper

#### Which are the steps to reproduce?
go in product window and see
 
### What is the expected or desired behavior?
1. have field documentno in product window
1. show it on jasper document for order (which is also used for quotation)

**Comment by metas-lc** [comment]
added document note from product in jasper, under the product value and above the sales order line description

**Comment by metas-rc** [comment]
Results of IT

I added a long, multi line, empty line document note to one of the products, made a sales order for it and then print previewed the jasper.
OK: The full document note I added was correctly display in the report below the product and the handling unit names.
