### ISSUE TITLE
Make letter print preview work with AD_BoilerPlate jasper process

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2592]
### Is this a bug or feature request?
Bug
### What is the current behavior?
jasper process is not used
feature was originally implemented here: https://github.com/metasfresh/metasfresh-webui-api/issues/178

#### Which are the steps to reproduce?
1. define a text tempate (boilerplate)
1. select jasper process in template
1. go in existing sales order 
1. press letter action
1. select template
1. click print preview
1. OK: letter is opened showing the text of template
1. NOK: jasper process is not used

### What is the expected or desired behavior?
When you print preview form the letter window, the jasper assign to the boiler plate to be included in the preview.

**Comment by teosarca** [comment]
note to dev: see
* de.metas.letters.model.MADBoilerPlate.getReportEngine(String, BoilerPlateContext)
* de.metas.letters.report.AD_BoilerPlate_Report.doIt()

**Comment by metas-rc** [comment]
Results of IT

OK: The default jasper process for letters is used when set in a template and the template is used in a letter.
