### ISSUE TITLE
New Window for Dunning Level in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2593]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window for Dunning Level Settings is not prepared in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window Layout for Dunning Level.

**Comment by metas-rc** [comment]
Results ot IT

Note: The window is named Dunning Type .


* OK: The Dunning Level window respects all our cornercases and layout conventions.
*OK: All its fields are translated into English.
