### ISSUE TITLE
New Window for Dunning Candidates in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2594]
### Is this a bug or feature request?
Feature Requests
### What is the current behavior?
Currently, the window Layout for Dunning Candidates is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window for Dunning Candidates in WebUI.

**Comment by metas-rc** [comment]
Results of IT: 

* OK:  The window Dunning Candidates was added in webui.
* OK: The filters were added
* OK: The cornerstones and layout conventions are respected.
* OK: All fields are translated.

* NOK: There is no  order by. Please add an order by and it's all fine.
