### ISSUE TITLE
Export AD_System relevant fields to /info endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2601]
Expose AD_System relevant fields to **webui-api's** /info endpoint.
e.g. when calling http://w101.metasfresh.com:8081/info it shall display something like
![image](https://user-images.githubusercontent.com/1244701/30987631-5d19e1a6-a4a0-11e7-9e5e-55410bf5f69f.png)

**Comment by metas-lc** [comment]
IT
open http://w101.metasfresh.com:8081/info
"AD_System": {
    "lastBuildInfo": "5.39.1-7098+master",
    "dbVersion": "5.39.1-7098+master"
  }

**Comment by teosarca** [comment]
@metas-lc  just saw that @metas-ts  commented out those 2 missing properties because they are legacy (see https://github.com/metasfresh/metasfresh/commit/fd882f7ad0018bbc9b5c7b5261a5d17ccebc6b6d).

So i think it's OK.

**Comment by metas-ts** [comment]
@teosarca  @metas-lc 
afair i did that because "lastBuildInfo" is misleading...because when rolling out a new version, lastBuildInfo is loaded for this endpoint **before** it's updated by the startup-housekeeping-task

**Comment by metas-lc** [comment]
@metas-ts @teosarca  thanks. Moving the task to done.
