### ISSUE TITLE
Business Partner Import with empty location

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2611]
### Is this a bug or feature request?
FR

### What is the current behavior?
address1 needs to be provided on import 

#### Which are the steps to reproduce?
1. have partner import and leave address1 empty
1. NOK: the location is not created although city, zip and country was provided

### What is the expected or desired behavior?
partner shall and address shall be created no matter if address1 is provided or not

**Comment by cristinamghita** [comment]
The fact that you can not import Locations without address1 field is coming from method '''org.adempiere.impexp.BPartnerImportProcess.createOrUpdateBPartnerLocation(I_I_BPartner, List<I_I_BPartner>)''' , more exaclty from condition:
```
else 	// New Location
		if (importRecord.getC_Country_ID() > 0
				&& !Check.isEmpty(importRecord.getAddress1(), true)
				&& !Check.isEmpty(importRecord.getCity(), true))
		{
			bpartnerLocation = createNewBPartnerLocation(importRecord);
		}
```
So, ig Address1 is empty, the location is not created.
Is enough to remove that and will work.

**Estimation: 1h**

**Comment by metasnw** [comment]
IT was OK
