### ISSUE TITLE
overhaul shipment schedule closing

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2623]
### Is this a bug or feature request?

Enhancement

### What is the current behavior?

i was aware that we already have a way to close shipment scheds, but now I saw that's just done by setting `QtyToDeliver_Override := QtyDelivered`..
i think that's suboptimal..i was probably good enough in the past,
but generally, `QtyToDeliver_Override` is  a "user" field and not a proper way to close a shipment sched.

..so..i was thinking..how else to close it..

### What is the expected or desired behavior?
* Add an M_ShipmentSchedule.IsClosed flag => it would be good to have an info for the user why it is closed..we could show that in M_ShipmentSchedule.Status

**Comment by metas-ts** [comment]
hi @metas-mk 
can you please display M_ShipmentSchedule.IsClosed in the webui?

**Comment by metas-mk** [comment]
> can you please display M_ShipmentSchedule.IsClosed in the webui?

done.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

process to close shipment schedules:
* process run from Action menu: closes the schedules, M_ShipmentSchedule.IsClosed=Y: OK
* setting M_ShipmentSchedule.IsClosed to Y: closes the schedule as well, OK
* `QtyToDeliver_Override` is not affected: OK
* shipment schedules which are already processed cannot be closed anymore: OK
* re-opening the schedules with the resp. action: working fine, OK
