### ISSUE TITLE
Create Zoom Across Reference between Flatrate Term and Invoice Candidate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2627]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
have a reference from contract in /window/540359
to invoice candidates

**Comment by metasnw** [comment]
I think we already have an existing reference in one of the legacy projects.
Guess we just have to port it as the data structure remains the same

**Comment by cristinamghita** [comment]
* Implemented
![image](https://user-images.githubusercontent.com/15378036/31121544-4be2725a-a841-11e7-916f-afd895dc6359.png)

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

* reference from contract in /window/540359 to invoice candidates: OK
* no reference in IC to the contract, or any info about the contract: is that OK?
