### ISSUE TITLE
Show fields product, qty, price and contractstatus in window contracts

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2628]
### Is this a bug or feature request?
FR

### What is the current behavior?
1. cant see product  product, qty, price in window contracts grid view and single view
workaround: they are in advanced edit
1. contractstatus is neither in single view or advanced edit

#### Which are the steps to reproduce?
open /window/540359 and see

### What is the expected or desired behavior?
for type "subscription" we need to have those fields in single and grid view because without them user does not know what the contract is about

**Comment by metas-rc** [comment]
Results of IT

* OK: Now, all product, qty, price and contractstatus fields were added. 
* The tanslations shall be solved in  https://github.com/metasfresh/metasfresh/issues/2666
