### ISSUE TITLE
Window Design Webui: Improve Business Partner window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2631]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The Business Partner window does not respect our layout conventions
#### Which are the steps to reproduce?
* Check
### What is the expected or desired behavior?
* Please, add order by Name in Business Partner ( currently it is on Value)
* Please, add white background to all of Business Partner's included tabs

**Comment by metas-mk** [comment]
> Please, add filter in Business Partner on Name ( currently it is on Value)

Was already there as Filter. Seems as if here "OrderBy" was meant instead. Done.

**Comment by metas-rc** [comment]
Results of IT

* OK: Order by name
* OK: All included tabs have white background

* I found some untranslated things and created a followup: https://github.com/metasfresh/metasfresh/issues/2728
