### ISSUE TITLE
Make the CalloutBankStatement webui compliant

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2634]
### Is this a bug or feature request?
* BUG
### What is the current behavior?
* I get a NUllPointerException when I try to set a currency into a Bank Statement Reference.
#### Which are the steps to reproduce?
* Open Bank Statement Reference, add new entry, try to set a currency.
### What is the expected or desired behavior?
* Please, make the CalloutBankStatement.paymentAmounts webui compliant. Also, please make all the other callouts from that class webui compliant

**Comment by cristinamghita** [comment]
### Test in swing for regression
* Create bank statement and play with amounts and currency for regression

### Test in webui
* The error is not there anymore

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no NUllPointerException when settingt a currency in a Bank Statement Reference: OK
* played with currency etc. in bank statement & bank statement reference, also in Swing: OK
