### ISSUE TITLE
Flatrate Import: Support explicit enddate and terminated contracts

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2642]
### Is this a bug or feature request?
FR
#### Which are the steps to reproduce?
Import an ended contract. 
The contract will be imported as active, according to  the conditions.
### What is the expected or desired behavior?
1. if enddate is set always use that one 
1. if enddate is null calculate it according to flatrate condition (this is how it is today)
1. if enddate is in the past contractstatus is terminated

**Comment by cristinamghita** [comment]
###  Enddate is null = active
 * Import creates FT, ICs and C_SubscriptionProgress. The end date is computed accordingly to the conditions
###  enddate in future = active but terminated
* import behaves exaclty as above
### enddate in past = inactive
 * Import creates FT, no ICs and no C_SubscriptionProgress. 
* The end date is set from import, ContractStatus='Qu', DocumentStatus='CO', Processed='Y', IsAutoRenew='N'

**Comment by metasnw** [comment]
IT was OK
