### ISSUE TITLE
Source HU Automatism for Manufacturing Issue

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2645]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to select a Source HU as Default Action Issue Source when fitting.
#### Which are the steps to reproduce?
Open, check and see.
### What is the expected or desired behavior?
Allow defining Source HU's for Action issue and a given Manufacturing Ressource/ Plant. Something similar was already developed in Picking.

**Comment by metas-ts** [comment]
to start, seach for code that references `I_M_Source_HU`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Source HU selectable as Default Action Issue Source: OK
* selecting an LU as Source HU: Internal Server Error, java.lang.NullPointerException: topLevelHU

**Comment by teosarca** [comment]
@metas-dh  pls check it again after next rollout. Yesterday i've fixed this issue.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* Source HU selectable as Default Action Issue Source: OK
* selecting an LU as Source HU: => HU is made available for picking
* picking of Source HU: => HU is moved to selected picking slot, and the selected shipment schedule is updated
* HU status: picked

problem: status  of CUs inside the picked LUs not always correctly updated to picked, but remaining active

**Comment by metas-dh** [comment]
checked with metas-mk:
* picking of components is OK, but not necessary
* picking of received product from production: to be tested in Picking from Handling Unit Editor (WebUI) #472
