### ISSUE TITLE
MRP Product Info Just in Time

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2646]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
Currently, the MRP Product Info is created w/ different Data that does not belong to core data of material management (e.g. daily counting data). Additionally, the recalculation of the MRP Product Info data takes too long (avg 20mins).
#### Which are the steps to reproduce?
Open, check and see.
### What is the expected or desired behavior?
Provide a Window in WebUI that allows to see/ filter/ select the MRP Product Info data similar to today. See if we can move special data usage nearer to core functionalities (like inventory). Provide/ Recalculate data just in time.

**Comment by metas-ts** [comment]
Main class or the info window: `de.metas.fresh.gui.search.MRPInfoWindow`

# Query-Fields

date
* Datum => Date widget with an up- and a down-arrow

product related
* Product => Lookup
* Name => substring
* Suchschlüssel => substring
* M_ProductCategory_ID => opt list field

Other
* Purchased => opt Y/N (list) field
* Sold => opt Y/N (list) field
* Konferenz

# The main table

## Main table fields

the *main table* is backed by the view `X_MRP_ProductInfo_V`

* M_Product_ID
* Name
* Value
* M_ProductCategory_ID
* SP80_QtyOnHand_OnDate_Plant1 (Zählbestand "particulat-plant-1")
* SP80_QtyOnHand_OnDate_Plant2 (Zählbestand "particulat-plant-1")
* Fresh_QtyOnHand_OnDate (Zählbestand)
* Fresh_QtyPromised (Zusagbar Zählbestand)
* PMM_QtyPromised_OnDate (Zusage Lieferant)
* QtyReserved_OnDate (Reservierte Menge Tag)
* QtyOrdered_OnDate (Bestellte Menge Tag)
* QtyMaterialentnahme (Materialentnahme)
* Fresh_QtyMRP (MRP Menge)

The view `X_MRP_ProductInfo_V` 
* uses the table `X_MRP_ProductInfo_Detail_Poor_Mans_MRP` (just for the `Fresh_QtyMRP` column)
* selects the other columns from `X_MRP_ProductInfo_Detail_MV` (with sum and group-by)
  * `X_MRP_ProductInfo_Detail_MV` is kept up to date by the function 
     `"de.metas.fresh".x_mrp_productinfo_detail_mv_refresh(dateat date, m_product_id numeric, m_attributesetinstance_id numeric)`
   * ...where the actual data is coming from  the **function** `X_MRP_ProductInfo_Detail_V(datefrom date, m_product_id numeric)`

## The function `X_MRP_ProductInfo_Detail_V`

... is one large parameterized select

It's building blocks are
* `"de.metas.fresh".M_Product_ID_M_AttributeSetInstance_ID_V`
  * selects all distict relevant `M_Product_ID`s, `M_AttributeSetInstance_ID`s, and dates from a `UNION` from the tables
    * `M_Transaction`
    * `C_OrderLine`
    * `Fresh_QtyOnHand`
    * `PMM_PurchaseCandidate`
  * everything else is left-joined to this view, so this view decides which (product, ASI, date) tuples needs further data to be joined to it
* `"de.metas.fresh".RV_C_OrderLine_QtyOrderedReservedPromised_OnDate_V`
   * selects the reserved and ordered quantities
   * based on the tables `C_Order`, `C_OrderLine` and `M_ShipmentSchedule`
* `"de.metas.fresh".RV_HU_QtyMaterialentnahme_OnDate`
  * `M_Transaction`s related to the DirectMove-Warehouse SysConfig `de.metas.handlingunits.client.terminal.inventory.model.InventoryHUEditorModel#DirectMove_Warehouse_ID`
* `"de.metas.fresh".X_Fresh_QtyOnHand_OnDate`
  * "plain table" with just product, ASI, date and qty
  * updated via trigger-function `"de.metas.fresh".m_transaction_update_x_Fresh_qtyonhand_ondate` on inserts and deletes regarding `MTransaction` records with ` MovementType IN ('C-', 'C+', 'V-', 'V+')`
* `Fresh_QtyOnHand_Line`
  * one time for a sum (=> `Fresh_QtyOnHand_OnDate`)
  * and one time per plant
* PMM_PurchaseCandidate
  * for column `PMM_QtyPromised_OnDate` (Zusage Lieferant)

## Sorting
..can be defined date stored in 
* `AD_User_SortPref_Hdr`
* `AD_User_SortPref_Line`
* `AD_User_SortPref_Line_Product`

in class ` org.compiere.apps.search.Info.java`

# Sub tab fields

The two sub tables relate to the currently selected main table row.

## `X_MRP_ProductInfo_AttributeVal_V` (Aufschlüsselung nach Attributgruppen)

* Shows the different lines with their different "attribute keys" and quantities that are summed up in the respective main table row
* The attribute keys to group by are defined in `DIM_Dimension_Spec` (`InternalName='MRP_Product_Info_ASI_Values'`)

The function `X_MRP_ProductInfo_AttributeVal_V`,  is basically a parmeterized select from `X_MRP_ProductInfo_AttributeVal_Raw_V` which in turn leans on `X_MRP_ProductInfo_Detail_MV`, just like the main table

## `MRPInfoWindowAttribs` (Aufschlüsselung nach Attributen)

based in the view `C_OrderLine_HU_Info_v`
* C_Order, C_OrderLine, M_ShipmentSchedule
* shows reserved and ordered quantities per ASI and M_HU_PI_Item_Product_ID

# Notable details:
  * Group names is an array of varchars; the chars that were mapped from ASI-ID with demension-stuff

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* qties in Material Cockpit were changed shortly after order / receipt was created
=> stopped testing bc connections crashed (a lot of requests were sent for material cockpit update)

**Comment by metas-dh** [comment]
Results of IT2
tested in releasetest 

Material Cockpit:

* Fresh_QtyOnHand_OnDate (Zählbestand): 
  * increased correctly after material receipt: OK
  * decreased correctly after material receipt reverse: OK
  * decreased correctly after shipmen0t complete: OK
  * increased correctly after shipment reactivate: OK

* Fresh_QtyPromised (Zusagbar Zählbestand):
  * increased correctly after Zählbestand (Einkauf) processed: OK
  * decreased correctly after Zählbestand (Einkauf) unprocessed OK
  * decreased correctly after sales order complete: OK
  * increased correctly after sales order reactivate: OK

* PMM_QtyPromised_OnDate (Zusage Lieferant): not tested yet

* QtyReserved_OnDate (Reservierte Menge Tag):
  * increased correctly after sales order complete: OK
  * decreased correctly after sales order reactivate: OK



* QtyOrdered_OnDate (Bestellte Menge Tag):
  * increased correctly after purchase order complete: OK
  * decreased correctly after purchase order reactivate: OK
  * decreased correctly after material receipt: OK
  *  increased correctly after material receipt reverse: OK

* QtyMaterialentnahme (Materialentnahme): not tested yet

* Fresh_QtyMRP (MRP Menge):: Benötigte Menge für Produktion:
  * increased correctly after manufacturing order complete:
  => the qties did not add up correctly for my PP_Order; also: the qty in Fresh_QtyMRP was changed right after the PP_Order component qties were created, and was not changed anymore after i changed the qty in PP_Order or reactivated it: not sure this is ok (tested with manual PP_Order)

**Comment by metas-ts** [comment]
Cherry picked the last two commits to `2018-06`

**Comment by metas-dh** [comment]
Testing with attribute qties:

* attribute qties correct after sales order: OK
* attribute qties correct after shipment: OK
* attribute qties correct after purchase order: OK
* attribute qties correct after material receipt: OK

* in case the purchase order had attribute set, but the material receipt not, the attribute qty in QtyOrdered_OnDate (Bestellte Menge Tag) was decreased nevertheless, is that ok?

**Comment by metas-dh** [comment]
Update:

checked again during last e2e for customer:

Fresh_QtyMRP (MRP Menge):: Benötigte Menge für Produktion: incorrect in WebUI (Swing was ok, MRP qty for the production i needed): NOK

**Comment by metas-dh** [comment]
Checked once more in mf15:

* Fresh_QtyMRP (MRP Menge):: Benötigte Menge für Produktion: not updated when the order is closed: qty is correctly updated after order is closed, also after qty in the order is changed: OK

=> closing this one since we have a bunch of other tasks in that area for specific problems.
