### ISSUE TITLE
Window Design Webui: Improve Businesspartner Dist-Orgs window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2653]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The included tab Vorgänge (Request)  lacks a mandatory field (Summary)  so new entries cannot be added
* Some of the included tab titles and some of the fields in the window Businesspartner Dist-Orgs do not have English translations
* Businesspartner Dist-Orgs is ordered by value and not Name in grid view
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Please, display the field Summary in Vorgänge (Request) included tab
* Please translate all the tab titles and all the fields in the window and its included tabs into English
* Please, add order by Name in Businesspartner Dist-Orgs ( currently it is on Value)

**Comment by metasnw** [comment]
@metas-mk 
these fields are also needed in case you decide to take em into the scope of this issue:
ft.enddate, ft.masterstartdate, ft.masterenddate, ft.contractstatus

**Comment by metas-mk** [comment]
@metasnw
thx. added them and the invoice bpartner and shipment bpartner too.
