### ISSUE TITLE
Handling Unit Attribute Propagation from LU to CU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2654]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, Attributes are not Propagated from LU to CU when done in HU Editor. e.g. Country.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
talked with @metas-mk , works.
