### ISSUE TITLE
flatrate import: Make use of isdefaultcontact

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2664]
### Is this a bug or feature request?
FR

### What is the current behavior?
new default flags implemented here: #2459 are ignored

#### Which are the steps to reproduce?
1. have a partner with issshiptocontact_default and isbilltocontact_default set to Y
1. import a flatrate for this partner
1. NOK: contact fields in flatrate term are empty

### What is the expected or desired behavior?
1. use isbilltocontact_default for billtouser
1. use issshiptocontact_default for dropshipuser

**Comment by metas-ts** [comment]
cherry-picked into release

**Comment by cristinamghita** [comment]
**To the IT team: have some regression in FT area. This task implied refactoring some contract validators.**

**Comment by metasnw** [comment]
tested on 5.30 and did not work.
invoice partner has one billto_default_contact
dropship partner has a shipto_default_contact:

![image](https://user-images.githubusercontent.com/16079655/31584155-2707a484-b1a9-11e7-8c7c-610b6e08ba82.png)

**Comment by metasnw** [comment]
Second problem:
Partner value of Invoice Partner is not resolved:
![image](https://user-images.githubusercontent.com/16079655/31584220-8bd4e9ca-b1aa-11e7-9eb8-603d8b66420d.png)

**Comment by cristinamghita** [comment]
Tested with : 
```G0027,Abo,2017-01-03,2017-12-12,P002737,3.45,2,G0027,2016-12-27,2017-04-04```

**Comment by metasnw** [comment]
problem No 1: tested on master and it worked fine
problem No 2: when using encoding UTF you have to use UTF with BOM or otherwise there will be a special character in front of the first value
