### ISSUE TITLE
Translate Add URL Attachment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2665]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the message to add an URL attachment is not translated to de_DE.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Translation for this Feature. "Lesezeichen/ URL hinzufügen"

![image](https://user-images.githubusercontent.com/13365687/31267596-fe908d7c-aa78-11e7-8529-1d140359532a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* message to add an URL attachment is translated to de_DE: OK
