### ISSUE TITLE
Window Design Webui: Tanslations for the window Contract

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2666]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Some of the fields in the window Contract and in its included tabs are not translated into English
* The process names for window Contract are not translated into English
#### Which are the steps to reproduce?
* Open and see.
### What is the expected or desired behavior?
* Please, add translations in English for all the fields and processes in the window Contract

**Comment by metas-rc** [comment]
Results of IT

*  NOK: The fields in the window are not all translated.
Please, also translate: 
* Lieferpartner
* Einzelpreis
* Planmenge pro Maßeinheit


*NOK: The process names were not translated: 


![image](https://user-images.githubusercontent.com/16001442/31544269-a8eb31d8-b022-11e7-94b6-b8c1a3add4e2.png)

**Comment by metas-lc** [comment]
IT
fields and processes are translated OK
