### ISSUE TITLE
Window Design Webui: Improvements and translations in Shipment Candidates

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2669]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* There is a typo in the name of the window. It reads "Shipment Candiates"
* Some of the fields are not translated into English
* The included tab doesn't have a white background
* The window doesn't have sorting for grid view
#### Which are the steps to reproduce?
* Open and check
### What is the expected or desired behavior?
* Please, fix the typo in the title
* Please add translations to ENglish to all the fields in Shipment Candidates window.
* Please, add white background to the included tab
* Please, add a sorting.

**Comment by metas-rc** [comment]
Results of IT
* OK: The name was changed into Shipment Disposition => no more typo :)
* OK: All fields except "abw. Anschrift"  are translated into English
* OK: The included tab has a white background.

* NOK: abw. Anschrift is not translated into English
![image](https://user-images.githubusercontent.com/16001442/31546690-08bc1820-b02d-11e7-8390-d67b3b07d5be.png)


* NOK: Order by Order is no longer reliable since the shipment schedules are not mandatory linked with order lines any more. Please, add another ordering

**Comment by metas-lc** [comment]
all translated OK
