### ISSUE TITLE
New window for AD_Scheduler in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2690]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for AD_Scheduler in WebUI.
#### Which are the steps to reproduce?
Open and check
### What is the expected or desired behavior?
Add the Window AD_Scheduler to WebUI Menue and create the Window according to WebUI Guidelines.

**Comment by metas-rc** [comment]
Results of IT

* The window Shcedules respects our cornerstones and layout conventions
* All the fields are translated into english
* All included tabs are usable and have white backgrounds
* Filters are ok

I found some problems. Followup created: https://github.com/metasfresh/metasfresh/issues/2719
