### ISSUE TITLE
Adjustments in Materialdispo Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2691]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few adjustments needed in Materialdispo Window in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
* Add Sub-Type to Fields
* Take  out the fields Qty Planning, Qty Override
* Add new/ missing Subtabs

**Comment by metas-rc** [comment]
Results of IT

* Note: The name in English is Material Schedule
* OK: The Subtype fields was added
* OK: The Qty Override and QtyPlanning to not appear in the window

The included tabs names are not translated into English, Followup: https://github.com/metasfresh/metasfresh/issues/2722
