### ISSUE TITLE
C_Flatrate_Conditions.C_Flatrate_Transition_ID needs to be mandatory

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2693]
### Is this a bug or feature request?
Bug

**Comment by teosarca** [comment]
note, when rolling on w101 i got an error because some C_Flatrate_Conditions.C_Flatrate_Transition_ID are null.

My fix there was to delete them, as @metas-ts  adviced ;)
```
delete from c_flatrate_conditions where C_Flatrate_Transition_ID is null;
select C_Flatrate_Transition_ID, * from c_flatrate_conditions;
```

**Comment by metas-lc** [comment]
IT
open Contract Terms, create a new one: flatrate transition is marked with blue line (mandatory) 
checked both swing and webui. Works fine OK
