### ISSUE TITLE
Window Design Webui: Add subscription details in Shipment Candidate window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2696]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, in WEBUI, the Shipment Disposition window does not contain the M_Shipment_Constraint_ID and the flag IsDeliveryStop .
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, also display the field M_Shipment_Constraint_ID and the flag IsDeliveryStop  in the window Shipment Disposition

**Comment by metas-lc** [comment]
IT
open Shipment Disposition Window =>
Shipment constraint field is there OK
Delivery Stop flag is there OK
