### ISSUE TITLE
Show an explicit error message when reports don't open because of logo missing

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2704]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, if there is no logo file set in the organization, the reports won't open and the error message is not explicit.
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Add an explicit error message so the users easily know why the report won't open and what they can do to solve this problem.

**Comment by teosarca** [comment]
nothing to IT.
