### ISSUE TITLE
productdescription in sales order jasper

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2711]
### Is this a bug or feature request?
fr
### What is the current behavior?
we don't have orderline.productdescription in jasper for sales order
#### Which are the steps to reproduce?
sales order - add line, set productdescription , run jasper
=> productdescription is missing 
### What is the expected or desired behavior?
should see productdescription + have property file to switch it off/on

**Comment by metas-lc** [comment]
order: documentnote (from product), description and productdescription (from orderline)

**Comment by metas-rc** [comment]
Results of IT
Tested on swing
* OK: If I add a description in the order line, it is displayed also in the sales order jasper report.
* The description field is missing from webui. Followup created: https://github.com/metasfresh/metasfresh/issues/2732
