### ISSUE TITLE
Window Design Webui: Improve window Schedules

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2719]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* There are duplicated fields: 

![image](https://user-images.githubusercontent.com/16001442/31536908-0fe7fb88-b009-11e7-857f-1e4c89c8b8e5.png)

* When the Cron Pattern Type is selected, there is an empty white band displayed in the advanced edit. It has no name and it is not editable: 

![image](https://user-images.githubusercontent.com/16001442/31537373-95691c8c-b00a-11e7-8dad-f326182d0498.png)

* The Cron Pattern shall not be mandatory when the type is Frequency

![image](https://user-images.githubusercontent.com/16001442/31538266-aea081f6-b00d-11e7-8318-35431e9593ee.png)

#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Please, delete the duplicated fields
* Please, check the white band element.
* Please, add a mandatory logic to the cron pattern so we can create frequency type schedulers.

**Comment by metas-dh** [comment]
Results  of IT1
tested in mf15

* duplicated fields deleted: OK
* white band element not displayed anymore: OK
* mandatory logic to the cron pattern: not mandatory when the type is Frequency: OK
