### ISSUE TITLE
WebUI Design Window: Improve window Material Schedule

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2722]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* THe included tab names are not translated into English.

#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, add translations to the included tabs names.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

material schedule: included tab names are translated to English: OK
