### ISSUE TITLE
Webui Design Window: Improve window Internal Use

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2723]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The field Posted is mandatory but not displayed; it cannot be set Because of this, when creating a new entry, it can't be saved:

![image](https://user-images.githubusercontent.com/16001442/31543195-c141d7c8-b01d-11e7-99fb-4beacad035fd.png)

* There is a white, readonly, unnamed band when opening Advanced edit

![image](https://user-images.githubusercontent.com/16001442/31543854-d30a5b80-b020-11e7-8783-4a80b8dd11b0.png)

#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Please, add a default value No to the Posted flag (as we do with all fields)
* Please, check what the white band is and name it or delete if not needed.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* still can't save in Advanced Edit bc of Mandatory field Posted not filled: NOK
* still got the white band in Advanced Edit, no name: NOK

![2017-10-26 14_49_18-metasfresh](https://user-images.githubusercontent.com/18696715/32054318-52b26dcc-ba5e-11e7-9c51-f5fc64a523b6.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* saving in Advanced Edit working fine, no problem bc of Mandatory field Posted not filled: OK
* no white band in Advanced Edit anymore: OK
