### ISSUE TITLE
Window Design Webui: Please, add translations to the window Contract Term

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2724]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Contract Term has fields that are not translated into English
* The included tab in Contract Term has fields that are not translated into English
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, add translations in English to all the fields of the window Contract Term and to all the fields in its included tab.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

all the fields of the window Contract Term and all the fields in its included tab are translated: OK
