### ISSUE TITLE
Set correct identifiers in the table M_ShipmentSchedule (v2)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2726]
### Is this a bug or feature request?
FR
Follow-up of https://github.com/metasfresh/metasfresh/issues/2700 where we set the table/record as identifiers.

Needed for https://github.com/metasfresh/metasfresh/issues/472

### What is the current behavior?
Shipment schedule string representation shows the table/record Id.

#### Which are the steps to reproduce?
* check subscription progress window.
* check the "Pick" process params (see https://github.com/metasfresh/metasfresh/issues/472)

### What is the expected or desired behavior?
Following fields ONLY shall be part of the identifier:
* bpartner
* bp location
* date promised
* order document no
* product
* QtyToDeliver

**Comment by metas-mk** [comment]
* product: 10
* bpartner: 20
* bp location: 30
* date promised: 40
* order document no: 40
* ~~QtyToDeliver~~
