### ISSUE TITLE
Tax is not set properly when creating ICs from flatrate term

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2727]
### Is this a bug or feature request?
bug
#### Which are the steps to reproduce?
Import FT and check the IC for that FT. It will have TaxNotFound
or
Extend a flatrate term and the IC of the new FT also will have TaxNotFound

### What is the expected or desired behavior?
The IC should have set the proper tax.

#### Test cases:
1. price system
   1. price list germany, tax excluded
      1. price list version valid from 01.10.2017
      1. product tax category 19%
      1. product price 90
   1. price list switzerland, tax included
      1. price list version valid from 01.11.2017
      1. product tax category 2,5%
1. FT 
   1. price 100 
   1. country of location: germany
   1. startdate 01.10.2017
   1. Expectation: tax 19%, net price 100, gross price 119
1. FT 2
   1. price 100 
   1. country of location: switzerland
   1. startdate 01.11.2017
   1. Expectation: tax 2,5%, net price 88,88  gross price 100

Nice to have:
1. FT 3 
   1. price NULL
   1. country of location: germany
   1. startdate 01.10.2017
   1. Expectation: tax 19%, net price 90, gross price 107,1

**Comment by cristinamghita** [comment]
**Note to the dev:**
Check this ```de.metas.contracts.impl.FlatrateBL.createCand(Properties, I_C_Flatrate_Term, I_C_Flatrate_DataEntry, int, BigDecimal, String)```
The tax is retrieved with taxCategoryId = -1, which is not treated.

**Comment by metasnw** [comment]
ToDos from my POV:
1. add c_taxcategory_id to c_flatrate_term
1. use that to compute c_tax_id on c_invoice_candidate
1. add c_taxcategory_id to flatrate import

**Comment by metas-ts** [comment]
> add c_taxcategory_id to c_flatrate_term

i'm not sure..c_taxcategory_id is already in the pricing system..where also the price actual is coming from when a contract is extended

**Comment by cristinamghita** [comment]
c_taxcategory_id  isn't in M_ProductPrice  ?

**Comment by cristinamghita** [comment]
**Concept**
* Create pricing context based on flatrateTerm
* Create pricing result and computing price, but in the end, in the new IC, use price and uom from ft
* if the price is null in UOM. use the computed price(allow FT with price null??)
* Use the tax category computed like that

**Comment by metas-ts** [comment]
Hi, here are my comments:

> Create pricing context based on flatrateTerm

agree. I think you can use FlatrateTermPricing to compute the IPricingResult

> Create pricing result and computing price, but in the end, in the new IC, use price and uom from ft

not sure anymore..maybe we should rather add the tax caregory to the term? or better remove the priceactual?
What makes me unsure is that the priceActial might or might not be incl. tax. Ask @metas-mk ?

> if the price is null in UOM. use the computed price(allow FT with price null??)

i didn't really understand

**Comment by metasnw** [comment]
> What makes me unsure is that the priceActial might or might not be incl. tax. Ask @metas-mk ?

Talked with @metas-mk last week and the idea was to take it from price list because there we have the info if it is tax included or not

**Comment by metasnw** [comment]
wondering if we need "ismanualprice" like in sales order line to protect the price from being updated when extending the FT

**Comment by cristinamghita** [comment]
> i didn't really understand
The idea behind this was to import FT with no price(since is the same).
And when the IC is created the price will be computed. Same thing we extend the FT.

> agree. I think you can use FlatrateTermPricing to compute the IPricingResult
Yes. Saw it meanwhile.

>not sure anymore..maybe we should rather add the tax caregory to the term? or better remove the priceactual?
>What makes me unsure is that the priceActial might or might not be incl. tax. Ask @metas-mk ?

yes, kind of those are hand in hand
With the included tax, I need to test. Not sure how it is now, at least. I mean case we have a price from FT and the tax categ should make the difference btw included and not, I think. Need to check this.

**Comment by cristinamghita** [comment]
@metasnw not sure we need IsManualPrice
When we will use it and when not?
I think is more like when we need to stick with the price from FT and when NOT?

**Comment by metas-mk** [comment]
The pattern how this information shall get into invoice candidate, and the corresponding behavior, can be taken from orderline -> invoicecandidate pattern
in orderline we have 
a) priceactual (can be overwritten)
b) tax category (can be overwritten)
c) istaxincluded (cannot be overwritten, is taken from pricesyste,/ list)
<-- same shall be for flatrate term

**Comment by cristinamghita** [comment]
@metas-mk Thx for clearing up!

**Comment by cristinamghita** [comment]
So needed:
* Add column C_Tax_category_ID mandatory in C_Flatrate_Term (be default be tax categ _Tax_Not_Found_Category_ )
* and basically this solved all - we have tax category and the tax will be now found

**Comment by metasnw** [comment]
IT was OK
