### ISSUE TITLE
Window Design Webui: Improvements in window Purchase order

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2730]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* 2 processes  is not translated to English:

![image](https://user-images.githubusercontent.com/16001442/31549257-4a188df4-b036-11e7-9eaa-23cf6c6ba00a.png)

* One of them has parameters which are also not translated:

![image](https://user-images.githubusercontent.com/16001442/31549305-74cce7fc-b036-11e7-8e39-1f3000fcd226.png)

#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please translate

**Comment by metas-lc** [comment]
IT

open purchase order window, check actions =>
Add Material Tracking ID, parameters: SeqNo. and Material Tracking ID OK
Create Sales Order from this Quotation: all params are translated OK
