### ISSUE TITLE
Picking slot Rack System flag

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2740]
### Is this a bug or feature request?
FR

Follow-up of https://github.com/metasfresh/metasfresh/issues/2298

### What is the current behavior?
When the picking modal window is closed,
if sysconfig WEBUI_Picking_Close_PickingCandidatesOnWindowClose is Y,
the processed picking candidates are closed.

Closing means flagging them as Closed and also adding the HUs to picking slot (M_PickingSlot_HU).

### What is the expected or desired behavior?
Introduce M_PickingSlot.IsRackSystem flag.

Based on that flag, the picking candidate's Process and Close action will work as follows:

M_PickingSlot.IsRackSystem=Y:
* process:
	add to SS => row visible
* close:
	add to Picking Slot rack system => row not visible
	=> close will be triggered when closing the modal window

M_PickingSlot.IsRackSystem=N:
* process:
	add to SS => row visible
	add to Picking Slot => row STILL visible
	and also do close

**Comment by teosarca** [comment]
note to IT: full picking terminal (webui) testing required

**Comment by metas-lc** [comment]
IT
1. check sysconfig
=> WEBUI_Picking_Close_PickingCandidatesOnWindowClose is not there anymore OK
2. go to picking slots window (in swing) 
=> Rack System flag is there OK
3. set Rack System flag to Y on one picking slot (let's say 102)
4. go to webui and create+complete a new sales order with a product on 4 TUs
5. go to referenced documents and select "Picking Terminal (Prototype)"
6. select your line, press on "Pick" action
7. select slot 101 and press on "open HU Selection window"
8. select an HU and press on "Pick HU" action
=> your HU is now on 101
=> if you check M_Picking_candidate for your HU and slot, the status is IP
9.  select slot 102 and press on "open HU Selection window"
10. select an HU and press on "Pick HU" action
=> your HU is now on 102
=> if you check M_Picking_candidate for your HU and slot, the status is IP
11. press on done, go to shipment disposition from your order
=> the HUs are not yet linked to shipment disposition
=> if you check M_Picking_candidate for your HU and slot, the status is IP
=> if you check picking slots window, the HUs are not linked to your slots
12. go back to "Picking Terminal (Prototype)" window, select your line, press on "Pick" action
13. select the LU from slot 101, click on "Process Picking" action
=> the HU is readonly
14. repeat step 13 for slot 102 (make sure you don't close picking terminal window)
=> the HU is readonly
15. check in database and swing for your slots and shipment dispo
=> if you check M_Picking_candidate for your HU and slot, the status is CL (for 101) and PR (for 102)
=> if you check picking slots, only the HU from 101 is linked to to the slot
=> if you check shipment schedule, both HUs are linked
16. press on done
=> if you check M_Picking_candidate for your HU and slot, the status is CL for both
=> if you check picking slots, both HUs are linked to picking slots
17. press on pick again
=> the HU from 101 is still there, 102 is empty
18. go to shipment disposition and press on generate shipments, select both checkboxes, ok
=> shipment created for these HUs
=> if you check picking slots, both HUs are not linked anymore
19. go to picking slots, select the line and press pick
=> the HUs you made shipments with are not there anymore (this only if you picked the whole qty! else it's still there OK?)
