### ISSUE TITLE
Add flatrate term relations from order and partner to new window contract

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2751]
### Is this a bug or feature request?
FR

### What is the current behavior?
cant use relations to jump

#### Which are the steps to reproduce?
1. have order with flatrate term => CTRL+6 => nothing
1. have partner with flatrate term => CTRL+6 => link to old window but no link to new window

### What is the expected or desired behavior?
1. order <=> flatrate term (new window "vertrag")
1. partner <=> flatrate term (new window "vertrag")

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* relation from order to new window contract ("Vertrag"): OK
* relation from partner to new window contract ("Vertrag"): OK
