### ISSUE TITLE
Inherit C_Taxcategory_ID and IsTaxIncluded from orderline to FT

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2752]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
Follow up [#2727 Tax is not set properly when creating ICs from flatrate term](https://github.com/metasfresh/metasfresh/issues/2727)

**Comment by metas-ts** [comment]
Please be sure to check out this comment: https://github.com/metasfresh/metasfresh/pull/2748/files#r144885270

**Comment by metas-lc** [comment]
IT
tested once with pricelist isincludedprice on Y and once on N
=> each time was set ok
tested with 2 products, different taxes
=> tax was set accordingly OK
