### ISSUE TITLE
remaining static element Translations

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2758]
### Is this a bug or feature request?
fr
### What is the current behavior?
some ad_message(s) are not translated
#### Which are the steps to reproduce?
go to ad_message window and take a look for the following ones
"WEBUI_Picking_SelectSourceHU"
"WEBUI_Picking_Select_Active_UnSelected_HUs"
"WEBUI_Picking_SelectPickedCU"
"WEBUI_Only_TopLevelHU"

select * from ad_message where ad_message_id in (544491,544486,544487,544490)
### What is the expected or desired behavior?
should be translated

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked ad_message window: resp. messages are translated: OK
