### ISSUE TITLE
New Window Picking Tray Clearing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2763]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Picking Tray Clearing Functionality is wrongly adapted to existing Picking Try window (maintenance/ master data window).
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Window "Picking Try Clearing". Have the old window "Picking Tray" as generic master data window again.

**Comment by teosarca** [comment]
@metas-mk  pls add the window https://w101.metasfresh.com:8443/window/540371 to menu.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* could not find the window in menu, only by link:

![2017-10-20 11_43_39-metasfresh](https://user-images.githubusercontent.com/18696715/31815237-6345f310-b58c-11e7-9289-d4f50eb7e6d8.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* window Picking Tray Clearing (Kommissionierung Abschluss (Prototyp)), in menu: OK
* Action "Take out HU" now available for the new window, not for winow Picking Tray: OK
