### ISSUE TITLE
Window Design Webui : Material receipt 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2764]
### Is this a bug or feature request?
fr
### What is the current behavior?
window: 184
Material Receipt gridview is missing fields
docview fields order is a bit wrong
included tab doesn't have white background

#### Which are the steps to reproduce?
Open and see

### What is the expected or desired behavior?

Material Receipt gridview: 
- Date shall be the 3rd field 
- the last 2 fields shall be status and org
- usually we order by date desc (see if we want here too. Now it's by docno)

Material Receipt docview: 
- under document type shall be No. and Date. 
- Organisation and client shall be the last two
- the included tab should have white background

**Comment by metas-rc** [comment]
Results of IT

* The problems were mostly solved. Followup created for the ones remaining: https://github.com/metasfresh/metasfresh/issues/2867
