### ISSUE TITLE
add description in c_doctype_trl

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2766]
### Is this a bug or feature request?
fr
### What is the current behavior?
we don't have description in c_doctype_trl
#### Which are the steps to reproduce?
select * from c_doctype_trl limit 1
### What is the expected or desired behavior?
we need description field in c_doctype_trl (like we have in c_doctype)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15cloudit

description field in included in c_doctype_trl: OK
