### ISSUE TITLE
Translate window for process "Change Password" into EN

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh#2768]
As per issue https://github.com/metasfresh/metasfresh-documentation/issues/180, documentation was updated.
Please translate the process window into English for consistency. See following png:
![password](https://user-images.githubusercontent.com/29163573/31765732-b30891f4-b4c5-11e7-8997-494f27415e89.png)

**Comment by metas-mk** [comment]
done.
![image](https://user-images.githubusercontent.com/13365687/31776280-60af84a0-b4eb-11e7-913a-f5a85cccd14e.png)

**Comment by metas-lc** [comment]
IT
logged in with en_US, open User -> actions -> change password => all fields are translated OK

**Comment by metas-Kay** [comment]
IT logged in with en_US
Open **User** (from Navigation Menu, not "User Menu" (i.e. "My Profile" via Settings)) -> **Create New User** (System User) -> **Actions Menu** -> **Change Password** => **Fields are not translated**
