### ISSUE TITLE
sales order jasper: group products by product category 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2771]
### Is this a bug or feature request?
fr
### What is the current behavior?
we don't have a jasper that can group products by product category 
#### Which are the steps to reproduce?
open and see
### What is the expected or desired behavior?
depending on properties files, we should group products by product category

**Comment by metasnw** [comment]
important is that the new groups created within the discount extension issue from teo are used and not m_product categories

**Comment by metas-dh** [comment]
Results of IT1

checked with lc: customer specifc, cannot be tested in mf15; regression: order jasper in mf15 still working as before, OK
issue in customer project was closed, closing this one too.
