### ISSUE TITLE
Vendor Invoice Layout and Translations in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2774]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window Vendor Invoice in WebUI is not adapted to the current Design Guidelines. Translations for en_US are missing too.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adapt the Window Vendor Invoice to the current WebUI Design Guidelines and add missing Translations for de_DE and en_US.

**Comment by metas-lc** [comment]
IT
purchase invoice - doc type window
1. doc view  
TL: mandatory, important  OK
TR: doctype, docno, date OK
BR: org, client OK

2. grid view:
first: doctype, docno, date OK
last: status, org OK
order by: NO desc (shall be docdate desc) NOK

3. filters
date, bp, no, doctype OK

4. names:
Target Document Type => shall be Document Type NOK
No. => OK
Date Invoiced => shall be Date NOK
Document Status => shall be Status (see gridview) NOK

5. included tabs
fields in 1 element group
white background
NOK - no white background

6. translations
untranslated: Anschrift-Text (advanced edit)

follow-up https://github.com/metasfresh/metasfresh/issues/2777
