### ISSUE TITLE
WebUI design: Invoice Candidates adjustments 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2783]
### Is this a bug or feature request?
fr
### What is the current behavior?
few adjustments needed in Invoice Candidates
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/2311
### What is the expected or desired behavior?
1. isactive, flags should be first in Top Right
2. org, client should be last in Bottom Right
3. remaining field to trl: Zu ber. Menge abw. erl. (see advance edit)

**Comment by metas-mk** [comment]
> isactive, flags should be first in Top Right

Normally yes, but isActive does not make sense for invoice candidates (transactional data), that's why it's not in there.

> org, client should be last in Bottom Right

Yes, but making a exception for dispo windows.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* remaining field to trl: Zu ber. Menge abw. erl.: OK
