### ISSUE TITLE
Partner Import : Add fields address3 and address4

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2784]
### Is this a bug or feature request?
FR

### What is the current behavior?
cant be imported

#### Which are the steps to reproduce?
1. open import format
1. go to line
1. click column
1. NOK: only address 1+2 selectable

### What is the expected or desired behavior?
1. Expectation: address 3+4 is selectable

**Comment by cristinamghita** [comment]
Tested with file:
```
G0051			 FNTest1	LNTest1	Y	N	Addr1	Addr2	Addr3	Addr4	Berlin		DE	Standard	Y	N	de_CH
```

**Comment by metasnw** [comment]
It was successful
