### ISSUE TITLE
Show LoginasUserHostkey in webui window user

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2790]
### Is this a bug or feature request?
FR

### What is the current behavior?
field is not there

#### Which are the steps to reproduce?
1. open user window
1. check advanced edit

### What is the expected or desired behavior?
its there so a user can be setup for PDF printing

**Comment by metasnw** [comment]
![image](https://user-images.githubusercontent.com/16079655/31853019-0f4e0300-b682-11e7-90a3-2a57964bfcbd.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

LoginasUserHostkey is shown in window User, Advanced Edit: OK
