### ISSUE TITLE
Problem with picking for subscription deliveries

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2794]
### Is this a bug or feature request?

Bug

### What is the current behavior?

the packageable view still uses some fields like bpartner-address from C_OrderLine instead of shipment schedule which leads to different glitches

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* flatrate term created from sales order, picking terminal: bpartner & its address are taken from the shipment schedule which is created for the flatrate term (not for the order): OK
* missing: reference from flatrate term to shipment schedule: Create Zoom Across Reference between Flatrate Term and Shipment Schedule #2835
