### ISSUE TITLE
Make de.metas.document.archive.process.ExportArchivePDF work in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2800]
### Is this a bug or feature request?
FR
### What is the current behavior?
pdf is not open
#### Which are the steps to reproduce?
Run process Open PDF from Printing queue window
### What is the expected or desired behavior?
Process should work and the pdf file should be open in browser.

**Comment by cristinamghita** [comment]
Follow up task for a proper name:
[#2807 Fix archive name when pdf printing](https://github.com/metasfresh/metasfresh/issues/2807)

**Comment by metasnw** [comment]
IT was successful
