### ISSUE TITLE
Set hostkey for printing module when login in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2803]
### Is this a bug or feature request?
FR
### What is the current behavior?
The hostkey is not set when log in
#### Which are the steps to reproduce?
Activate printing module and set in login user , flag Isloginhostkey on 'Y'.
Then login in the app and check Duck-zuordnung.  The HK is set on <not-yet-determined>
### What is the expected or desired behavior?
The hostkey for the user should be set as the login name of the user.

**Comment by metasnw** [comment]
@cristinamghita I understood a server cache reset is a workaround?

**Comment by cristinamghita** [comment]
@metasnw, no. Is not implemented.
I implemented now the fix.

**Comment by metas-ts** [comment]
Hi @cristinamghita @teosarca 
i'm not sure how the fix changes the "loginName" vs. "remote IP" as-hostkey-behavior of the system.

At any rate we still need the ability to use the **IP-address** of the remote computer as login key for some users.
Does that still work?

**Comment by cristinamghita** [comment]
Hi!
@metas-ts 
If the user is not setup to use the loginname, should be as before.
But, I should test remote_IP. Could you help me or tell me how to test?

**Comment by cristinamghita** [comment]
**Note to IT**
Please to a regression test regarding the "remote IP" as-hostkey.
It is neccesary to test that the remote-ip-as-hostkey still works if that flag in AD_User is not checked

**Comment by metas-lc** [comment]
IT
what i noticed during ITs
1. new database - hostkey is not defined OK???
=> if i create printer configs, hostkey is "not defined" OK???
2. i go to user "metasfresh" - i set login as hostkey on Y
=> login with metasfresh  - hostkey is metasfresh. Also if i create printer configs, hostkey is metasfresh OK
=> but if i login with IT - hostkey is still metasfresh OK??? Also if i create printer configs, hostkey is metasfresh (on swing) and IT (on webui) OK???

3. i set login as hostkey on N, restart app, server etc
=> hostkey is still metasfresh everywhere. I think NOK

**Comment by metasnw** [comment]
@metas-ts 
I am using login as hostkey and it works fine
also you are using the other way for printing clients
is it ok with you when we close this?
