### ISSUE TITLE
new flag in Picking Tray window

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2815]
### Is this a bug or feature request?
fr
### What is the current behavior?
Rack System is a new flag in picking slots, that currently is shown only in swing. Need it in webui as well
#### Which are the steps to reproduce?
open https://w101.metasfresh.com:8443/window/540206/
select any slot
### What is the expected or desired behavior?
Rack System flag shall be added (probably in gridview as well)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15cloudit

Rack System flag added in Picking Tray window, in gridview as well: OK
