### ISSUE TITLE
Material Dispo - include storage-relevant attributes

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2816]
### Is this a bug or feature request?
FR
### What is the current behavior?
currently, material dispo only works along the coordinates of
* product
* time
* warehouse

### What is the expected or desired behavior?

what we need is to also include the storage relevant attributes. so that records with different attributes can be distinguished..e.g. organic/bio vs "conventional" versions of the same product

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* include storage-relevant attributes in Material Cockpit: ever product line has an indent for attributes: OK
* qties correct for attributes: had material receipts with attribute: Bio, was also set for the HUs, but the resp. qties were not displayed with attribute Bio in material cockpit, but in "sonstige": NOK
* all storage-relevant attributes are displayed for all types of products, also for e.g. Gebinde or things like Erdbesatz & Ohne Packmittel: not sure this makes sense

**Comment by metas-dh** [comment]
Update:

* attribute qties correct after sales order: OK
* attribute qties correct after shipment: OK
* attribute qties correct after purchase order: OK
* attribute qties correct after material receipt: OK

* in case the purchase order had attribute set, but the material receipt not, the attribute qty in QtyOrdered_OnDate (Bestellte Menge Tag) was decreased nevertheless, is that ok?
