### ISSUE TITLE
Flatrate: Have relation from Sales Order to invoice candidate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2818]
### Is this a bug or feature request?
bug

### What is the current behavior?
you cant jump from order to invoice candidate

#### Which are the steps to reproduce?
1. sales order 
1. have one line
1. chose a flatrate condition
1. complete
1. CTRL+6 => no invoice candidates

### What is the expected or desired behavior?
jump like from normal sales order

**Comment by cristinamghita** [comment]
Implemented
![image](https://user-images.githubusercontent.com/15378036/31943763-6fae5130-b8d2-11e7-8120-6d4ab5270d71.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* relation from sales order for flatrate term to invoice candidate: OK
