### ISSUE TITLE
Calibrated PDF changes ESR Line using OCR Font to italic

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2820]
### Is this a bug or feature request?
bug

### What is the current behavior?
OCR ESR Line is italic

#### Which are the steps to reproduce?
1. do a printing of an invoice with an ESR with an output type = PDF printer (implemented via #2103 ) 
1. compare the archive PDF with the created PDF
1. archive PDF: ESR Line OK
1. printed PDF: ESR Line italic

### What is the expected or desired behavior?
shall look like archive pdf

**Comment by cristinamghita** [comment]
The conclusion is that itext , when scaling a pdf , doesn't recognize the embedded font', whch was renamed.
See ```de.metas.printing.PdfPrinter.print(Printable, Printable)```

Workaround - Use the real name in the jasper report.
TODO: update itext version

**Comment by metasnw** [comment]
problem was solved by using the precise name of the font in jasper report and putting the font into server jar
