### ISSUE TITLE
Window Material Dispo in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2821]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
After the last changes in Material Dispo the following adjustments have to be done in WebUI Window,
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
- Main View: Remove AD_Table_ID and Record_ID
- New Tab for MD_Transaction_Detail
- Tab Bedarfsdetail: Add ShipmentscheduleID and forecastId
- Remove isActive in all Tabs

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Materialdispo:
* Main View: Remove AD_Table_ID and Record_ID: OK
* New Tab for MD_Transaction_Detail: OK
* Tab Bedarfsdetail: Add ShipmentscheduleID and forecastId: OK
* Remove isActive in all Tabs: OK
