### ISSUE TITLE
Empty Country in Price List not working

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2822]
### Is this a bug or feature request?
bug

### What is the current behavior?
can not use price list with empty country to calculate price

#### Which are the steps to reproduce?
1. have price system with two price lists like this one https://w101.metasfresh.com:8443/window/146/2000837
  1. take out country from DE so the field is empty
1. create a sales order for testkunde in DE
1. NOK: currency CHF. Expectation: takes DE pricelist because customer address is not switzerland

### What is the expected or desired behavior?

Expectation: takes DE pricelist because customer address is not switzerland

**Comment by metas-lc** [comment]
IT
repeated the testcase above => currency is CHF NOK

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The pricelist with empty country is correctly taken when the partner's country doesn't have a pricelist of its own.
* OK: This works both for SO and PO pricelists
* OK: If the partner is from a cuntry that has a pricelist, that pricelist is correctly taken (both SO and PO)
