### ISSUE TITLE
Add C_Invoice_Candidate.Priority missing column

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2823]
### Is this a bug or feature request?
Bug.
Introduced by https://github.com/metasfresh/metasfresh/issues/1771

### What is the current behavior?
C_Invoice_Candidate.Priority column is missing

#### Which are the steps to reproduce?
* as a developer you can generate the model classes for C_Invoice_Candidate and you will get some compile errors because that column is missing (e.g. compile errors in de.metas.invoicecandidate.api.impl.InvoiceCandidateEnqueuer.enqueueSelection0(ILock, int))
* as a tester you can run following query and it will fail
```sql
select Priority from C_Invoice_Candidate limit 10
```

### What is the expected or desired behavior?
column shall be present

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

C_Invoice_Candidate.Priority column is present, query has results: OK
