### ISSUE TITLE
WebUI: Orderlines adjustment for new Discount Groups

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2826]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In Issue https://github.com/metasfresh/metasfresh/issues/2564 new Columns/ Fields were created.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the new Fields to Orderlines in Advanced edit and in Grid View (at the end before org, for now)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new fields in orderlines: Gruppe, Gruppen Zeile, Gruppen Preisminderung, Gruppen Art, Preisminderung Betrag Art: OK
* in  Advanced edit and in Grid View (at the end before org): OK
