### ISSUE TITLE
Tweak material-dispo window

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2834]
### Is this a bug or feature request?
FR

### Tell me more dear tobi

We need some (web)-UI tweaks

* The window for material-dispo
 * in the main- tab, remove AD_Table_ID und Record_ID
 * add a new tab for the new MD_Transaction_Detail table
* in the tabl for MD_Demand_detail, show fields for M_ShipmentSchedule_ID and M_foreCastLine_ID

**Comment by metas-mk** [comment]
Issue already here: https://github.com/metasfresh/metasfresh/issues/2821
closing this one.
