### ISSUE TITLE
Setup wizard shall not inactivate ESR

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2836]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If you change anything with Setup wizard, sys config 'de.metas.payment.esr.Enabled' is set on N
#### Which are the steps to reproduce?
Start Setup wizard and modify something,
### What is the expected or desired behavior?
Esr should not be deactivated.

**Comment by cristinamghita** [comment]
## Dev test

* Activate esr module like this
[Configure ESR]http://docs.metasfresh.org/howto_collection/Wie_konfiguriere_ich_den_ESR_Zahlschein.html)
* Then start the setup, do some changes and save
* Go to the db and chek the value of sys config ```de.metas.payment.esr.Enabled```. Should be on 'Y'

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

changes made with SetUp Wizard, sys config de.metas.payment.esr.Enabled still set 'Y' afterwards: OK
