### ISSUE TITLE
WebUI: Add new Fields for SQL Columns to Material Dispo Transaction Subtab

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2843]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Follow-Up for https://github.com/metasfresh/metasfresh/issues/2821.
#### Which are the steps to reproduce?
None.
### What is the expected or desired behavior?
Add new Fields for SQL Columns in transactions Subtab.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

new Fields for SQL Columns in transactions Subtab, Materialdispo: OK
