### ISSUE TITLE
Set MasterStartDate for a contract when creating from order

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2862]
### Is this a bug or feature request?
FR
### What is the current behavior?
none
### What is the expected or desired behavior?
Set MasterStartDate

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* MasterStartDate set for contract created from sales order: OK
* MasterStartDate is date of order: i think this is OK? was always date of order, also when DatePromised and Date of Provisioning was different

**Comment by metasnw** [comment]
@metas-dh that is fine. we currently using order date as startdate for the contract

**Comment by metas-dh** [comment]
@metasnw thx for the info, closing this task.
