### ISSUE TITLE
Make sure that 'Print All' is working in webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2866]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
And when printing was done, we have also the notification.
![image](https://user-images.githubusercontent.com/15378036/32187591-36c1ec3e-bdae-11e7-8a18-071afe0d9e8f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* set up the printing for testing as described in https://github.com/metasfresh/metasfresh/issues/2103#issuecomment-321497570: printer config had to be set manually, which is OK
* create data for printing queue (invoices, shipments)
* select  "Print All" in Action Menu: printing process is started, notification about print job being completed: OK
