### ISSUE TITLE
Window Design Webui: Improve windows with Posted field

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2871]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Example: The Distribution Order window has a mandatory field (Posted)  that doesn't have a default value (default logic) and is not displayed  => the manual entry cannot be saved because of the mandatory field not set.
* I noticed this problem occures in many other tables and I created an sql to find them: 

`select t.tablename  from ad_column c
join ad_table t on c.ad_table_ID = t.ad_table_ID
where c.columnname = 'Posted' and defaultvalue is null` 

 The result for the db where i test was: 

- "M_Movement"
- "M_Production"
- "RV_Cash_Detail"
- "M_MatchInv"
- "M_MatchPO"
- "C_Payment_v"
- "RV_UnPosted"
- "M_Requisition"
- "C_AllocationHdr"
- "RV_InOutDetails"
- "RV_Payment"
- "PP_Order"
- "PP_Cost_Collector"
- "DD_Order"
- "PP_Order_Header_v"
- "RV_Unprocessed"

#### Which are the steps to reproduce?
* Try to create a new distribution order, or a new inventory. 
* Check in inspection : => "Mandatory field Posted not filled"

### What is the expected or desired behavior?
* Please, add a default value of N in all those tables ( like it is, for instance, in C_Invoice table).  This way it will not stop us from manaully creating new entries from webui.

**Comment by metas-mk** [comment]
Adjusted the selection sql to not show Views.

`select t.tablename from ad_column c join ad_table t on c.ad_table_ID = t.ad_table_ID where c.columnname = 'Posted' and defaultvalue is null and isview = 'N';`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* selection sql: no results, OK
* distribution order: manual entry can be saved, no entry in inspection about  "Mandatory field Posted not filled": OK
