### ISSUE TITLE
Window Design Webui : Improve Distribution Order window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2872]
### Is this a bug or feature request?
* FR
### What is the current behavior?
1) Posting field is mandatory  doesn't have a default value
2) The flag IsApproved is mandatory but does not have a default value. Also, the column is marked as calculated => cloning leads to an error, since this flag is null.
3) Some of the fields in the window and in it's subtab are not translated into English.
4) The included tab does not have a white background
5) Document specific filters are  missing
6) There is no ordering in gridview
7) The document specific fields are not all displayed -> they cannot be seen
8) There is no Date field
9) The order of the column in gridview is not document specific
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
1)  For this I created a generic task:  https://github.com/metasfresh/metasfresh/issues/2871
2) Please, add a default value to the field IsApproved.
3) Please, add English translations for all the window's fields and for its included tab's fields.
4) Please, add a white background to the included tab,
5) Please, add the document specific filters
6) Please, add order by Date desc
7) Please, display fields doc Action, doc status etc.
8) Please, decide which is the document date and translate it with Date
9) Please, order the columns in grid view as we do for the other documents.

**Comment by metas-mk** [comment]
1. ~~For this I created a generic task: #2871~~
2. ~~Please, add a default value to the field IsApproved.~~
3. Please, add English translations for all the window's fields and for its included tab's fields.
4. Please, add a white background to the included tab,
5. Please, add the document specific filters
6. Please, add order by Date desc
7. ~~Please, display fields doc Action, doc status etc.~~
8. ~~Please, decide which is the document date and translate it with Date~~
9. Please, order the columns in grid view as we do for the other documents.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. For this I created a generic task: #2871: OK
2. Please, add a default value to the field IsApproved.: OK
3. Please, add English translations for all the window's fields and for its included tab's fields.: OK
4. Please, add a white background to the included tab,: OK
5. Please, add the document specific filters: OK
6. Please, add order by Date : OK
7. Please, display fields doc Action, doc status etc.: OK
8. Please, decide which is the document date and translate it with Date: OK
9. Please, order the columns in grid view as we do for the other documents.: OK
