### ISSUE TITLE
Create special filters in printing queue

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2874]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
We need:
* a filter for foreigners
* filter for different partner from invoice partner
* regular

**Comment by teosarca** [comment]
i think we already have, see AD_UserQuery table which is also supported by webui.

**Comment by cristinamghita** [comment]
For now, we will create virtual columns and create predefined filters with them.

**The labels approach**
* create a table c_Printing_queue_attribute (similar to c_bpartner_attribute )
* There have a list with what labels we need (regular, foreigners, etc)
* in webui use the labels - link with tab, label, etc
* Create a validator which inserts records in c_Printing_queue_attribute  each time when a record is created

**Comment by cristinamghita** [comment]
See filters created:
![image](https://user-images.githubusercontent.com/15378036/32217662-672504c8-be31-11e7-91c6-ba999a60da1f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* special filters in printing queue: OK
* filtering working correctly: OK
