### ISSUE TITLE
Fix Recreate printing queue for webui

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2876]
### Is this a bug or feature request?
Bug
#### Which are the steps to reproduce?
Try to recreate printing queues. The process is not working.
### What is the expected or desired behavior?
The process shall work from webui.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Recreate printing queue: process is working from WebUI: OK
* print jobs in queue are recreated: OK
