### ISSUE TITLE
Support for 6 digits AccountNo length in ReferenceNumber

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2878]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, the AccoutnNo in ReferenceNumber is preceded by 0 digits until the lenghts on 7
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* The accountNo itself shall be the first one, instead, and followed by 0 digits until the length of 7. This way , account numbers that are of 6 or 5 digits can also be parsed correctly.

**Comment by metas-lc** [comment]
IT
1. make sure you have the esr enabled in sysconfig
2. make sure you have a reference type C_ReferenceNo_Type for invoice, for your org
3. make sure the bpartner of your org has esr acct number
4. create a sales invoice, add a product complete
5. go to reference number window and check your number
=> if you have account no of 6digits or lower to get to 7 it will generate 0s
