### ISSUE TITLE
Add greeting to partner quick creation from order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2880]
### Is this a bug or feature request?
FR

### What is the current behavior?
field is not there
### What is the expected or desired behavior?
![image](https://user-images.githubusercontent.com/16079655/32235084-cc3c5eec-be5e-11e7-8385-0ef3bb95c44b.png)
![image](https://user-images.githubusercontent.com/16079655/32235113-e086da44-be5e-11e7-9aa5-0ad9332b18c6.png)

**Comment by cristinamghita** [comment]
Added the new field and the logic behind.
![image](https://user-images.githubusercontent.com/15378036/32237778-8d0513f8-be6e-11e7-9102-c5d5ad8dabb9.png)

![image](https://user-images.githubusercontent.com/15378036/32237806-9edf4ce2-be6e-11e7-8424-1fb69be14f4e.png)

![image](https://user-images.githubusercontent.com/15378036/32237839-b59b877a-be6e-11e7-953f-ff23263ee7f0.png)

**Comment by metas-lc** [comment]
IT
go to sales order, create a new bpartner on go 
=> notice the first field on right side is Anrede (greetings)
set a greeting, all mandatory fields, ok
go to business partner window, select this bpartner, go to Contact tab => first field, "Greeting", is set OK
