### ISSUE TITLE
Add a process that removes pauses and can be ran from Contract window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2881]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* This process C_SubscriptionProgress_RemovePauses is linked with the table C_SubscriptionProgress table => it can be run only from Subscription History window
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* We need to also be able to call this functionality from the window Contract, so we can stop all the pauses for a certain contract.

Note: Additionally, please repair the classname in this process C_SubscriptionProgress_RemovePauses from the database. It has the wrong qualified name => it is not displayed

**Comment by metas-lc** [comment]
IT (see step 5)
1. created contract term and period according to this docu https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_tests_collection/e2e_subscription_cases.md
2. created order and added the term
3. complete order and go to contract window
=> subscription progress subtab: status - lieferung offen, contract status - laufend
4. go to contract window and pause some days using action "Pause Contract"
=> subscription progress subtab: status - lieferung offen, contract status - pause
=> shipment schedules are closed. 
5. go to contract window and remove the pauses using action "Abo-lieferpause entfernen"
=> subscription progress subtab: status - lieferung offen, contract status - laufend OK
=> shipment schedules are still closed. Shall they be opened? (please check) 
please also translate "Abo-lieferpause entfernen" for en_US

**Comment by metas-lc** [comment]
IT
retested the testcase above
=> the shipment schedules are opened after you remove the pause OK
=> made followup for the translation: https://github.com/metasfresh/metasfresh/issues/3228
