### ISSUE TITLE
Test canceling extended contracts and fix if needed

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2885]

**Comment by cristinamghita** [comment]
After testing, I found these points that we need to fix:
* masterenddate should be the same in all related contracts
* masterstartdate should be copied from the intitila contract
* cancel contracts also backwards, if neede

**Comment by cristinamghita** [comment]
## masterstartdate should be copied from the intitila contract
**Initial contract**
![image](https://user-images.githubusercontent.com/15378036/32285191-34b9b73e-bf32-11e7-909e-39d5649b23ce.png)

**Extended contract**
![image](https://user-images.githubusercontent.com/15378036/32285144-165032dc-bf32-11e7-8c46-25c16c991411.png)

**Comment by metas-rc** [comment]
Results of IT

* canceling and extending terms worked fine in all the cases, with one exception: followup created: https://github.com/metasfresh/metasfresh/issues/2907

* rest of the cases described all worked fine.
