### ISSUE TITLE
Make ShipmentSchedule column reference search in C_SubscriptionProgress

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2887]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Locally, when I want to open the window Contract and then its tab Subscription Progress, it takes very much time loading and I keep getting this in the console: 
> 2017-11-01 15:34:08.121  WARN 22768 --- [mentSchedule_ID] org.compiere.model.MLookupLoader         : M_ShipmentSchedule.M_ShipmentSchedule_ID: Loader - Too many records. Please consider changing it to Search reference or use a (better) validation rule.
 Fetched Rows: 10000
 Max rows allowed: 10000

#### Which are the steps to reproduce?
* Have some contract and subscription progress records, try to open the window and its tab. 
### What is the expected or desired behavior?
* The window shall work smoothly with close to no loading time. 
Sollution: Make the ShipmentSchedule column reference search in C_SubscriptionProgress

**Comment by metas-rc** [comment]
Note for IT

* in webui there's nothing to test
* in swing, just go to Vorgang ( Contracts)  and click on the tab Abo Verlauf ( Subscription progress)  and it should open quickly.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Vertrag, subtab Abo Verlauf: opening smoothly, no long loading time: OK
* nothing in console when opening the tab: OK
