### ISSUE TITLE
AD_Ref_Table needs lower-case WHERE and FROM

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2895]
### Is this a bug or feature request?
FR

### What is the current behavior?

right now, a user can enter a whereclause into AD_Ref_Table that will later fail with the `AccessSqlParser`

### What is the expected or desired behavior?

it would be great to have a model interceptor to lowercase WHERE, FROM any meabe others (please check the code)

**Comment by metas-ts** [comment]
oh, and please add to the documentation which keywords will be lowercased

**Comment by metas-lc** [comment]
IT
go to reference, subtab ref table and write an sql in whereclause. Make sure you write WHERE and FROM in upper case, save
=> right after you save, where and from are changed in lower case. The other words you wrote remain in upper case (or how you wrote them)
