### ISSUE TITLE
Drop out old code related to confirm splitting when printing

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#2897]
### Is this a bug or feature request?
FR
### What is the current behavior?
* asking for confirmation when printing
#### Which are the steps to reproduce?
Try to print in the next conditions:
* sys config `de.metas.printing.MaxLinesPerJob` has value 100
* then  print 102 invoices
* in webui, the printing will fail
* in swing is fine, and after 100 records will ask if you want to continue
### What is the expected or desired behavior?
* We don't want any user confirmation

**Comment by metas-lc** [comment]
IT
made config for printing pdf
set de.metas.printing.MaxLinesPerJob on 2 
created and completed 5 invoices
went to Druck Warteschlange - gear - alle drucken
=> got 3 notifications OK
opened each notification - gear - PDF offen
=> 2 had 2 invoices and 1 only 1 OK
