### ISSUE TITLE
set masterenddate correctly when extending contracts

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#2907]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, if I extend a contract with autorenewal - false, the new contract get a master end date and the inital contract doesn't have one any more
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* When you extend a contract with auto-renewal on false, both contracts should have set the new masterenddate

**Comment by metas-rc** [comment]
Followup for https://github.com/metasfresh/metasfresh/issues/2885

**Comment by cristinamghita** [comment]
Note to IT: redo the tests from https://github.com/metasfresh/metasfresh/issues/2885

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* both contracts have set the new masterenddate after extending a contract that has autorenewal - false: OK

regression testing:
* masterstartdate should be copied from the intitial contract: OK
* masterenddate should be the same in all related contracts: OK
* if is not Autorenew, then set MasterEndDate from the beginning, but set to null when forced extended: the 1st part is OK, the 2nd did not work for me, have to check again
