### ISSUE TITLE
Column-SQL needs lower-case WHERE and FROM

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#2913]
### Is this a bug or feature request?

FR,
analog to [#2895](https://github.com/metasfresh/metasfresh/issues/2895) AD_Ref_Table needs lower-case WHERE and FROM

**Comment by metas-lc** [comment]
IT
go to a table, subtab column and write an sql in columnsql. Make sure you write WHERE and FROM in upper case, save
=> right after you save, where and from are changed in lower case. The other words you wrote remain in upper case (or how you wrote them)
