### ISSUE TITLE
Allow Termination of all selected contract periods

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2924]
### Is this a bug or feature request?
FR

### What is the current behavior?
you can terminate contracts one by one

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/Contract_termination.html

### What is the expected or desired behavior?
shall work the same way but for all selected lines

**Comment by cristinamghita** [comment]
* Implemented the possibility to cancel multiple contracts
* added unit tests for cancelling simple contract, extended contract with diverse date, test subscription progress

**Comment by metasnw** [comment]
@teosarca shouldnt this issue be flagged as branch:master?

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: Closing all selected contracts works.
