### ISSUE TITLE
Postal not Updateable in Swing Client

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2933]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is not possible to update the Postal in c_location. Found in Initial Client Setup.
#### Which are the steps to reproduce?
Do the Initial Client Setup in Swing and try to update the Location info.
### What is the expected or desired behavior?
Allow changing the Postal.

![image](https://user-images.githubusercontent.com/13365687/32533357-8972e91c-c450-11e7-813a-a1e9554a8ad0.png)

**Comment by teosarca** [comment]
pls make the column updateable

**Comment by metas-rc** [comment]
Making the Postal column updateble soled the problem. Thx for hint!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Postal updateable in Swing Client : Initial Client Setup: no error, OK
* Postal updateable in Swing Client :in bpartner window: no error, OK
