### ISSUE TITLE
Additional Locator Dimensions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2934]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we only have 3 Locator Dimensions in metasfresh.
#### Which are the steps to reproduce?
Keine.
### What is the expected or desired behavior?
We want to add 1 additional Dimensions into Locator
- Room (already exists, Locator)
- X (already exists, Shelf Row)
- Segment (NEW, Storage Rack)
- Y (already exists, Self/ Level)
- Z (already exists, Tray)

Rename the Fields in en_US too:
x - Row
x1 - Rack
y - Shelf
z - Tray

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Locator Dimensions:
* de_DE:  Locator, Gang  Regal, Ebene, Fach; OK
* en_US: Locator, Aisle , Regal, Level, Tray: NOK
* Regal cannot be set when setting / adding a locator, in window 139: is that OK?

**Comment by metas-mk** [comment]
@metas-dh thanks for the info
- Translation of Regal -> Rack: done
![image](https://user-images.githubusercontent.com/13365687/32763344-702d912e-c8ff-11e7-83ba-ef38f620962e.png)

About: Regal cannot be set when setting / adding a locator, in window 139: is that OK?
I don't have this issue when creating a new Locator. Can u pls show me?

**Comment by metas-dh** [comment]
@metas-mk: 
About: Regal cannot be set when setting / adding a locator, in window 139: is that OK?
I don't have this issue when creating a new Locator. Can u pls show me?
=> tried again, i can set it now, seemed to be read-only when i last tested; thanks!

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

Translation of Regal -> Rack: OK
