### ISSUE TITLE
Creating new flatrate condition and transition with autoextension became very tricky

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2936]
### Is this a bug or feature request?
FR

### What is the current behavior?
after https://github.com/metasfresh/metasfresh/issues/2693 it became tricky to have a self extending contract condition and transition

#### Which are the steps to reproduce?

1. new condition pointing to new transition
1. new transition pointing to the new condition as next period

problem:
1. can not select the transition until its completed 
1. I can not complete the transition because I need to put the condition first
1. I can not save the condition because I have to put a transition

**workaround:**

1. create the condition and select any other transition
1. create the new transition completely
1. change the condition to use the new transition

### What is the expected or desired behavior?
dont make transition a mandatory field but make sure you can not complete the flatrate condition unless its filled out

**Comment by metas-rc** [comment]
Moving to Done after talking with Torby.
