### ISSUE TITLE
Inout Generate non completed via Shipment Schedule does not create Packing Item Lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2939]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
When creating InOuts via Shipment Schedule, then the Packing Lines in InOut are only generated when the process is started with complete = Yes. If set to No the Packing Item Lines are not created.
#### Which are the steps to reproduce?
See above.
### What is the expected or desired behavior?
Also create the Packing Item Lines when generating the InOut non completed.

**Comment by metas-rc** [comment]
I am closing this since the client issue closed long ago
