### ISSUE TITLE
Shipment Date = Promised Date

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2940]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Orders w/ promised Date in Future, but w/ InOut Generate today always have today as shipment date/ date.
#### Which are the steps to reproduce?
See above.
### What is the expected or desired behavior?
The Process for InOut Generate shall have a new Parm "Shipment Date today" ("Lieferdatum heute"). It shall be initially = 'N'. In this case the InOut Date shall be set via oldest Promised Date in Rows Selection that is younger/ equal today.

**Comment by metas-rc** [comment]
Cases for when the flag is not set to true:
Case 1: One schedule for today, others in the future => take today
Case 2: All shipment schedules in the future => take the minimum date from all the schedules
Case 3: All schedules are in the past => take today

**Comment by metas-dh** [comment]
checked in mf15: not yet included in Actions for shipment schedules, only in w101; to be tested after next rollout

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new Parm "Shipment Date today" ("Lieferdatum heute"): OK, but: translation de_DE is missing, it's IsShipToday!
* shall be initially = 'N': OK
* Shipment Date is today when parm is set 'Y', also for shipment schedules with different date: OK
* All shipment schedules in the future => take the minimum date from all the schedules: OK
* All schedules are in the past => take today: OK
* One schedule for today, others in the future => take today: NOK, a future date was taken
* If we have at least one shipment schedule in the past => take today: NOK, a future date was taken

**Comment by metas-dh** [comment]
Results of IT2

* One schedule for today, others in the future => take today: OK
* If we have at least one shipment schedule in the past => take today: OK
* new Parm "Shipment Date today" : trl missing, as are others in shipment schedule, created #3198
