### ISSUE TITLE
Allow more than 1 PostFinanceUserNo per Account

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2944]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it's only possible to add 1 PostFinanceUserNo (ESR) to a bank account. In ESR Payment Import the Bank Account is added to Header and there is a check if Bank Account matches to PostFinanceUserNo (ESR).
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Extend the PostFinanceUserNo (ESR) recording in Bank Account and allow more than 1 ESR definition. In ESR Import allow to import ESR files which have different PostFinanceUserNo (ESR) in 1 File.

**Comment by metas-rc** [comment]
Concept

* Create a new small table that contains C_BP_BankAccount_ID and ESR_RenderedAccountNo
* When a new esr import comes, compare the number from it to all the ESR_RenderedAccountNo values from all the entries of the C_BP_BankAccount that fits the ESR import
* If any of them fits, chose it. Throw error only if none fits.

**Comment by metas-dh** [comment]
Results of IT1

1. have 2 different PostFinanceUserNo for the same C_BP_BankAccount
2. have 3 sales invoices
3. create an ESR import file, for the resp. C_BP_BankAccount, with a line for each invoice:
* invoice 1 with PostFinanceUserNo 1
* invoice 2 with PostFinanceUserNo 2
* invoice 3 with a PostFinanceUserNo not used for the C_BP_BankAccount
4. import the ESR file and check:
* 1st line is imported without errors and allocated correctly: OK
* 2nd line is imported without errors and allocated correctly: OK
* 3rd line shows an error, no allocation: OK
5. Check the invoices: invoice 1 &2 are paid, 2 is not: OK
