### ISSUE TITLE
Adjustment in pain001

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2945]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Credit Transfer Transaction information hast Structured Data parm.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Shall be Unstructured.
![image](https://user-images.githubusercontent.com/13365687/32610130-16dabd4a-c562-11e7-8f33-8654605071a2.png)

**Comment by metas-dh** [comment]
Results of IT1

* could not be tested, bc the SEPA Export field remained read-only in test db, for whatever reason (no error, exception or anything in console)
* to be tested after next rollout in customer test db

**Comment by metas-dh** [comment]
Results of IT2
tested during e2e on customer db

* Sepa Export worked fine
* waiting for approval from customer (sent test data)

**Comment by metas-dh** [comment]
feedback from customer: OK
