### ISSUE TITLE
Product: New Field Endcustomer productname and translation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2946]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to add the productname for the customer-endcustomer label. Also no Translations for it.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
In window Product>>Busuinesspartner there shall be a new Field "Endcustomer Productname". Also create a Translation Table that allows to translate this Field.

**Comment by metas-ts** [comment]
CPed to `2017-12`

**Comment by metas-lc** [comment]
IT
go to product -> bpartner tab, advance edit
=> Auszeichnungsname field is there OK
followup for trl : https://github.com/metasfresh/metasfresh/issues/3129
