### ISSUE TITLE
Adapt Window Role to WebUI Guidelines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2947]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Role Window in WebUI ist not matching the current WebUI Guidelines and does not have proper Translations.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adapt the window and add Translations for de_DE, en_US

**Comment by metas-lc** [comment]
IT
Role window:
grid: order by Name asc OK
doc: 
TL: mandatory, important fields  OK
TR: isActive, other flags OK
BR: org and client
included tabs: white background OK
translations to en/de OK
