### ISSUE TITLE
webui window: Packing Instructions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#2948]
### Is this a bug or feature request?
FR

### What is the current behavior?
There is no way to manage packing instructions, e.g. to activate/deactivate them.
The packing instructions window is not in menu.
As a workaround i am using: https://w101.metasfresh.com:8443/window/540188

### What is the expected or desired behavior?
Have (at least) a minimal Packing Instructions window where i can browse the activate/deactivate them.

**Comment by metas-mk** [comment]
In webui we have create 2 new windows for packing instructions. They can be found in Logistics folder:
![image](https://user-images.githubusercontent.com/13365687/32665512-cc675b8c-c634-11e7-8abc-3a892504cc65.png)
