### ISSUE TITLE
drop allowconsolidateinvoice from database

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2956]
### Is this a bug or feature request?
FR

### What is the current behavior?
db column is there although its not used anymore as it was replaced with so_invoice_aggregation_id

#### Which are the steps to reproduce?
check table and column

### What is the expected or desired behavior?
1. migrate existing records to std aggregation
1. drop column from db

**Comment by metasnw** [comment]
convert existing records:
```
update c_bpartner
set so_invoice_aggregation_id= 1000000
where so_invoice_aggregation_id is null and allowconsolidateinvoice ='Y';
```

**Comment by metas-lc** [comment]
IT
allowconsolidateinvoice is not in c_bpartner anymore 
there is no element for it 
order to invoice creation works fine, no errors
OK
