### ISSUE TITLE
2nd Discount Break is ignored

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2958]
### Is this a bug or feature request?
bug

### What is the current behavior?
first break works fine and is applied
second break is ignored

#### Which are the steps to reproduce?
https://w101.metasfresh.com:8443/window/233/1000003
![image](https://user-images.githubusercontent.com/16079655/32702075-4dadca52-c7e1-11e7-9c8c-d54e5432de9a.png)

1. assign that discount schema to a partner
1. create an sales order 
1. put convenience salad and qty = 10
1. OK: 10% discount is applied
1. change qty to 20
1. NOK: discount of 20% is not  applied
1. add line with qty 20 via quick product entry
1. NOK: discount of 20% is not  applied

### What is the expected or desired behavior?
shall apply the discount for the break matching qty

thx @metas-kay for finding it

**Comment by metasnw** [comment]
1. fix problem
1. create automatic test for it

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/32952495-2ac54f3c-cbb6-11e7-9c31-4026725aa3dd.png)

**Comment by metas-lc** [comment]
IT
1. had discount schema assigned to a partner BP1
2. discount schema had 3 lines: Product "A", break values: 100, 150 and 200. Discounts 10, 15 and 20
(first tested with 2 lines, later added the 3rd line to make sure it works)
3. created sales order with bpartner BP1, product A:
- added the product 4 times with batch entry. Qtys 10, 100, 150 , 200
- added the product 4 times with add new. Qtys 10, 100, 150 , 200
=> discounts were: 0 for qty 10, 10 for qty 100, 15 for qty 150 , 20 for qty 200 OK
4. manually changed the qtys to all lines
=> discount updates accordingly OK
5. added lines with product "B" (BP1 doesn't have discount schema for product B)
=> discount was always 0, no matter qtys OK
6. created a new sales order with BP2 (one that didn't have discount schema for product A)
7. added lines with product A, qtys 10, 100, 150 , 200
=> discount was 0 OK
