### ISSUE TITLE
Default WebUI Window for Distribution Orderlines Handling

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2959]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently in WebUI the Bereitstellung POS (Swing)) window is missing
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Have a new Window for the Handling of Distribution Orderlines.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for Distribution Orderlines Handling: OK, "Distributions Editor"
* showing Distribution Orders: OK
* Actions for Handling of Distribution Orders? only "Re-create MRP records for current document" available in Action Menu
