### ISSUE TITLE
flatrate: use datepromised instead of order data for master and startdate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2963]
### Is this a bug or feature request?
FR

### What is the current behavior?
order data is used

#### Which are the steps to reproduce?
1. follow http://docs.metasfresh.org/webui_collection/EN/Create_contract.html
1. and set order date to tomorrow
1. open contract window 
1. startdate is same

### What is the expected or desired behavior?
datepromised is used instead

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. sales order with order date != date promised
2. Set contract terms in orderline
3. Contract window: startdate and master startdate = date promised, not order date: OK

**Comment by metasnw** [comment]
@metas-dh wondering if you tested to create an order with datepromised in the past?
@cristinamghita is the flatrate import affected by this?

**Comment by cristinamghita** [comment]
@metasnw no. Is not. Are affected only the contracts created form orders.

**Comment by metas-dh** [comment]
@metasnw i did now: startdate and master startdate = date promised (13.11.), OK i think;
 the first shipment is scheduled for today, 16.11.; is that OK?

**Comment by metasnw** [comment]
@metas-dh thx for testing that case. its fine !
