### ISSUE TITLE
error for HU changing locator if status E

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2965]
### Is this a bug or feature request?
bug
### What is the current behavior?
error for HU changing locator if status E
#### Which are the steps to reproduce?
0. go to customer return (kundenrucklieferung) window and try to reverse one with real HUs
=> error
A HU's locator cannot be changed if the M_HU.HUStatus is E
Additional parameters: HowtoDisableModelInterceptor: Model interceptor method de.metas.handlingunits.model.validator.M_HU#validateLocatorChange threw an exception. You can disable this method with SysConfig IntercetorEnabled_de.metas.handlingunits.model.validator.M_HU#validateLocatorChange='N' (with AD_Client_ID and AD_Org_ID=0!)
.
.
OR (if there is no data you can use) - swing only for now
1.  create and complete a purchase order, warehouse X
2. go to receipt candidates and create inout
3. create and complete a sales order, warehouse X
4. go to picking terminal and pick the hu from step 2
5. create a sales inout using the qty of the HU
=> hu is shipped, wh X
6.  go to shipment and select button: "Return from Customer"
7. go to newly created customer return
=> hu is activ, quality wh
8. try to reverse the document
=> error
A HU's locator cannot be changed if the M_HU.HUStatus is E
Additional parameters: HowtoDisableModelInterceptor: Model interceptor method de.metas.handlingunits.model.validator.M_HU#validateLocatorChange threw an exception. You can disable this method with SysConfig IntercetorEnabled_de.metas.handlingunits.model.validator.M_HU#validateLocatorChange='N' (with AD_Client_ID and AD_Org_ID=0!)

(note: i see the hu status is A and the error says E) 

### What is the expected or desired behavior?
should be able to reverse a customer return document

**Comment by metas-lc** [comment]
note for IT: there is another error when you create a customer return, that appears only in console. We have a task for that: https://github.com/metasfresh/metasfresh/issues/2966

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

`no error for HU changing locator if status E; repeated testcases above, not happening anymore: OK
