### ISSUE TITLE
Add SQL Column M_Warehouse to Distribution Orderline

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2969]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to Filter by Warehouse for Distribution Orderlines.
#### Which are the steps to reproduce?
Open and see in Window Distribution Editor.
### What is the expected or desired behavior?
Create a SQL Column for M_Wareouse in Distribution Orderlines and add a Filter for that Field.

**Comment by metas-lc** [comment]
IT
go to Window Distribution Editor, use filters - standard
=> there we have warehouse to and from OK
