### ISSUE TITLE
sales invoice jasper: group products by product category 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#2975]
### Is this a bug or feature request?
fr
### What is the expected or desired behavior?
we need to be able to group invoices by confirmation group

**Comment by metas-ts** [comment]
reopening after accidental close via commit message

**Comment by metas-dh** [comment]
Results of IT1

checked with lc: customer specifc, cannot be tested in mf15; regression: order jasper in mf15 still working as before, OK
issue in customer project was closed, closing this one too.
