### ISSUE TITLE
Translate Processname to de_DE in Procurement Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2976]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Quickaction Processnames in Procurement Candidates are not Translated to de_DE
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Translate them.

![image](https://user-images.githubusercontent.com/13365687/32784230-8ca6ea86-c94e-11e7-847c-23eb4d5f9ffe.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK: The actions are all translatet to German
OK: All  the fields are translated to German
