### ISSUE TITLE
Tab Org Access not working in webui because of missing primary key

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#2977]
### Is this a bug or feature request?
bug

### What is the current behavior?
if you try to add an org in ad_user tab org acess you get Composed primary key is not supported for AD_User_OrgAccess

### What is the expected or desired behavior?
shall work like in java client

I assume the solution is to add an explicit key to the tab

**Comment by teosarca** [comment]
yup, that's the solution. We even have a process which helps us doing this:
![image](https://user-images.githubusercontent.com/1244701/32857533-ca4b9758-ca50-11e7-9b38-0bf86b699160.png)

**Comment by metasnw** [comment]
@metas-mk could you take a look in your next webui window round? thx!

**Comment by metas-mk** [comment]
@metasnw done.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

OK The Org Access tab is usable and I can record entries in it. There are no errors
