### ISSUE TITLE
New Window in WebUI for EDI DESADV

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2978]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window for EDI DESADV is missing in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window DESADV and add to WebUI Menu.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The window was added in the menu
* OK: The cornerstones are respected
* OK: The included tabs have white background
* OK: All the fields are translated
