### ISSUE TITLE
Date Filter missing in Order Control Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2980]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Date Filter is missing in the Order Control Window.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Date Filter in Order Control window.

**Comment by metas-rc** [comment]
Results of IT

OK: The date filter was added for the Order Control window
I noticed this window doesn't have the fields translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/3197
