### ISSUE TITLE
Filter for Shipment Documentstatus is missing in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2982]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Shipment Documentstatus Filter is missing in Shipment window. The Field "Packvorschrift-Produkt-Zuordnung" is not adjusted.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Date Filter to Shipment Window in WebUI. Adjust "Packvorschrift" fieldname.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

OK: The filter for document status was added in the Shipment window. It is also working
OK: The packing instructions field looks fine.
