### ISSUE TITLE
Refining Distribution Editor Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2985]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Distribution Editor Window in WebUI is created but needs further refinements for better usage.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
- Filter for promised date. 
- Order by promised date desc. 
- Make Distribution Order search Field. 
- Take out SeqNo.
- Rename Warehouse "Warehouse from".
- New Virtual Column "Warehouse To".

**Comment by metas-mk** [comment]
- Filter for promised date. 
- Order by promised date desc. 
- Make Distribution Order search Field. 
- Only show roes with processed = 'N'. 
- Take out SeqNo.
- ~~Rename Warehouse "Warehouse from".~~
- New Virtual Column "Warehouse To".

**Comment by metas-lc** [comment]
IT
Filter for promised date. OK
Order by promised date desc. OK
Make Distribution Order search Field. OK
Take out SeqNo. (from grid?? or?)
Rename Warehouse "Warehouse from". OK
New Virtual Column "Warehouse To". OK
