### ISSUE TITLE
Adjust the Naming of Locators

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2987]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the naming of locators happens in the pattern Warehousename-x-x1-y-z.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the naming of Locators to:
Warehousevalue-locatorvalue-x-x1-y-z.

![image](https://user-images.githubusercontent.com/13365687/32827112-504dba04-c9eb-11e7-83f4-f480cc4b5283.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui



* OK: Now, when a locator is set in a field, the display string is: warehousename-wareheousevalue-locatorvalue-x-x1-y-z
