### ISSUE TITLE
Filter for GAP No. is missing in Businesspartner window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2989]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Filter for GAP No is missing in Businesspartner Window in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Filter GAP No in Businesspartner window in WebUI.

**Comment by metas-lc** [comment]
IT
go to bpartner window, select the filters  -standard
=> NAICS/SIC (en_US) and GAP (de_DE) OK
Filter for GAP
=> works fine OK
