### ISSUE TITLE
WebUI: Window Shipment Packing Item

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#2992]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Packing Item Field ins not renamed/ translated yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Please rename/ translate.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Packing Item Field is translated: OK
