### ISSUE TITLE
WebUI: New Window for HU Transaction

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3002]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window in WebUI to view the Handling Unit Transactions.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window for Handling Unit Transactions and add them to Menu in Logistics.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The window was added in the menu
* OK: The cornerstones are respected
* OK: The window and all the fields are translated into English
