### ISSUE TITLE
Manufacturing Order add Filter for Planstatus

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3005]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Planstatus is not in Filter criteria in Manufacturing Order.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Planstatus to Manufacturing Order Filter criteria.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Planstatus included in filter criteria in  Manufacturing Order: OK
