### ISSUE TITLE
WebUI: Add translations in Procurement Purchase Candidates Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3007]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window Purchase Candidates is missing some Translations for en_US, de_DE in Fields and Actions.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Please add Translations. Also move Purchase Candidates to "Procurement Candidates" in new Folder for Procurement (or similar).

![image](https://user-images.githubusercontent.com/13365687/32942452-6197a44c-cb89-11e7-8244-d88bde87b6c9.png)

**Comment by teosarca** [comment]
@metas-mk  now that we will have true purchase candidates (C_PurchaseCandidate) i would suggest to move this window to some "procurement" folder. wdyt?

**Comment by metas-mk** [comment]
@teosarca yes. good point. shall do this in this issue too.

**Comment by metas-mk** [comment]
Done in https://github.com/metasfresh/metasfresh/issues/2976
