### ISSUE TITLE
Inherit c_order_id and orderline_id from flatrate term to invoice candidate

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3010]
### Is this a bug or feature request?
FR

### Which are the steps to reproduce?
1. create a contract via sales order http://docs.metasfresh.org/webui_collection/EN/Create_contract.html
1. open related documents http://docs.metasfresh.org/webui_collection/EN/JumptoviaSidebar.html
1. NOK: no invoice candidate available

### What is the expected or desired behavior?
be able to jump

technical requirement of @metas-ts : inherit column c_order_id and orderline_id from flatrate term to invoice candidate

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

* I created an order for flatrate term
* I opened the related documents
* => OK: The invoice candidate was available.
