### ISSUE TITLE
WebUI: Add the new Picking TU Label to Picking Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3013]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the New TU Label is not in Picking window.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add an Action to Picking Window to print the Picking Label after a new HU is created.

**Comment by metas-lc** [comment]
Related with https://github.com/metasfresh/metasfresh-webui-api/issues/895
