### ISSUE TITLE
Contracts: ContractDocumentNo is 0 all the time

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3022]
### Is this a bug or feature request?
Bug
### What is the current behavior?
ContractDocumentNo is not changed, so we can't identify any contract by number.
### What is the expected or desired behavior?
ContractDocumentNo should increase with each new contract.

(metas-rc) Note: This task only offers support for Abbonament document type.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK: The document number increases correctly in Contracts, for the document type Abbonament.
