### ISSUE TITLE
WebUI: New Window for Import Product

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3026]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for Import Product in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the window for Import Product in WebUI.

**Comment by metas-lc** [comment]
IT
New Window for Import Product
=> Import Product window is in menu under System, id 247 OK
=> it has Import Product action OK
It has only 1 element group. Shall i create follow-up for window design?
