### ISSUE TITLE
WebUI: New Window for Import BPartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3027]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for Import BPartner in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the window for Import BPartner in WebUI.

**Comment by metas-ts** [comment]
cherry-picked to `release`

**Comment by metas-lc** [comment]
IT
Import BPartner Window
TL: important, mandatory OK
TR: flags OK
BR: org, client OK

Translations: not all fields are translated in en_US (also some in de_DE e.g. "Short Description") https://github.com/metasfresh/metasfresh/issues/3164
