### ISSUE TITLE
SSCC Product description Field cut off

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3032]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Product Description Field on SSCC Label is cut off.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please extend the Field so that it has more space before cutting off (boundary of separator lines/ margin)

**Comment by metas-dh** [comment]
Results of IT1

SSCC Product description Field: no cut-off, long product description is displayed in >1 line: OK
