### ISSUE TITLE
Linenet amount not updated in sales order after setting flatrate condition 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3035]
### Is this a bug or feature request?
bug

### What is the current behavior?
1. add one order line
1. select flatrate condition that has a price system with a different product price
1. NOK: linenetamt is still on the old price
here is a sample case: https://w101.metasfresh.com:8443/window/143/1000113

### What is the expected or desired behavior?
1. should recalculate when selecting the flatrate condition
1. create automatic test for this particular case as it caused trouble before: #2838

**Comment by teosarca** [comment]
note to IT: please do regression on creating order lines and check if price actual is set correctly.

**Comment by metasnw** [comment]
tested bug case on w101 and the original problem is fixed
did not do regression

**Comment by teosarca** [comment]
@metasnw 
> so we can drop the readonly logic from field c_orderline.c_flatrate_term_condition_id

done.


@metas-ts  pls CP my last commit too

**Comment by metasnw** [comment]
@teosarca yes, we can. tested yesterday and its fine

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & in e2e

* testcase working fine, linenetamt is taken from pricelist set in flatrate term: OK
* regression: creating order lines and price actual taken: OK
follow-up: Quantity in Price Unit recalculated for flatrate term #3052

**Comment by metas-ts** [comment]
Hi @teosarca 
thx for the hint, but i prepared the `release` branch only yesterday :blush: , so it was already in
