### ISSUE TITLE
WebUI: New Window for Purchase Order Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3037]
### Is this a bug or feature request?
Feature Request
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664
blocking https://github.com/metasfresh/metasfresh/issues/3054

### What is the current behavior?
Currently, there is no window for Purchase Order Candidates
#### Which are the steps to reproduce?
None.
### What is the expected or desired behavior?
Create a new Window for Purchase Order Candidates.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

new windowfor purchase order candidates: Bestelldisposition / purchase disposition: OK
