### ISSUE TITLE
Forecast Window adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3039]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few detail improvements missing in Forecast window to work smoothly and efficiently.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
1. Enable Clone/ Copy (will be done in https://github.com/metasfresh/metasfresh/issues/3040)
2. Qty TU/ Picking Item in forecast line
3. Businesspartner, Date, Period, Warehouse in Forecast Header, shall be copied down to line but hidden (https://github.com/metasfresh/metasfresh/issues/3041)
4. Set Default Packing Item per product and partner.
5. Enable Batchentry (https://github.com/metasfresh/metasfresh-webui-api/issues/699)

**Comment by metas-mk** [comment]
Done:
a) Businesspartner, Date, Period, Warehouse in Forecast Header
b) Qty TU/ Picking Item in forecast line

**Comment by metas-dh** [comment]
Results of IT1

* Businesspartner, Date, Period, Warehouse in Forecast Header: OK
* Qty TU/ Picking Item in forecast line: OK
