### ISSUE TITLE
Implement Clone/ Copy for Forecast Window WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3040]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, Clone/ Copy is not available in Forecast Window WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Allow the Clone/ Copy in Forecast window WebUI.

**Comment by teosarca** [comment]
note to dev: just implement & register CopyRecordSupport and the Clone menu action shall be automatically activated.

see:
* org.adempiere.model.CopyRecordSupport
* org.adempiere.model.CopyRecordFactory.registerCopyRecordSupport(String, Class<? extends CopyRecordSupport>)
* de.metas.ui.web.window.model.DocumentStandardAction.Clone
* de.metas.ui.web.window.descriptor.DocumentEntityDescriptor.isCloneEnabled()

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Clone/ Copy is  available in Forecast Window WebUI: OK
* Forecast correctly cloned/ copied: OK
