### ISSUE TITLE
Forecast Window copy Field content from header to lines when creation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3041]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Fields Businesspartner, Date, Period, Warehouse are in Forecast Line.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Move the fields to Forecast Header and use the content of these fields when creating the lines as initial value there. When updating the Content in the header, then update the content in all lines too.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* fields Businesspartner, Date, Period, Warehouse are now in Forecast Header: OK
* content of these fields are used when creating the lines as initial value there (values are hidden): OK
* when updating the content in the header, then update the content in all lines too: OK
