### ISSUE TITLE
A contract shall not be created when a completing a quotation

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3043]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When having quotation as doctype , a contract is created when completing the order
#### Which are the steps to reproduce?
Try and see
### What is the expected or desired behavior?
When having quotation as doctype , a contract shall NOT be created when completing the order

**Comment by metas-dh** [comment]
Results of IT1

* no contract is created when completing a quotation: OK
