### ISSUE TITLE
WebUI: New Window for Quality Note

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3047]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Quality Note is missing in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window and add to WebUI menu in product>>settings.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui: 

* OK : The window was added in the menu
* OK: All the fields are translated into English
* NOK: The window name is not translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/3195
