### ISSUE TITLE
WebUI: Date Filter missing in Material Receipt Dispo

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3048]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Date Filter is missing in Material Receipt candidates window
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Date Filter to Material Receipt Candidate window.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

OK: The date filter is available in the Material Receipt Candidates window
OK: This filter is also functional
