### ISSUE TITLE
WebUI: New Window for the Payment Allocation Workflow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3049]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no substitute for the Payment Allocation Form in Swing Client in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a Payment Allocation window in WebUI that allows to efficiently handle the payment allocation requirements.

**Comment by teosarca** [comment]
will be implemented by https://github.com/metasfresh/metasfresh-webui-api/issues/1320
