### ISSUE TITLE
Null in SSCC label

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3050]
### Is this a bug or feature request?
Bug
### What is the current behavior?
SSCC label shows "null" if LotNumberDate is not set, instead of just leaving it empty.
#### Which are the steps to reproduce?
Print a SSCC label for a HU without LotNumberDate set and see.
### What is the expected or desired behavior?
If no LotNumberDate is set, just leave it empty, don't show "null".

**Comment by metas-lc** [comment]
the problem was that the "LotNumberDate " propetry was missing. 
now:
- you have tageslot set: 
Tageslot: 112
- you don't have tageslot set
Tageslot:

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no Null in SSCC label, when Tageslot not set, left empty: OK
* when Tageslot set, correctly displayed in label: OK
