### ISSUE TITLE
purchase candidates: document references

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3054]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the expected or desired behavior?
Make sure we can
* jump from sales order to purchase candidates
* jump from purchase order to purchase candidates
* jump from sales order to purchase order
* jump from purchase order to sales order

**Comment by metas-lc** [comment]
IT
made sure we can:
jump from sales order to purchase candidates OK
jump from purchase order to purchase candidates OK
jump from sales order to purchase order OK
jump from purchase order to sales order OK

purchase candidates is called "Bestelldisposition NEU" - shall be trl to Purchase Disposition (en_US version) . created follow-up https://github.com/metasfresh/metasfresh/issues/3141
