### ISSUE TITLE
purchase candidates: notify user when the purchase order was generated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3055]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the expected or desired behavior?
After the purchase candidates were processed and the purchase order generated,
we shall notify the user that created the sales order.
The notification shall contain the purchase order number that was created and the BPartner name.

**Comment by metas-lc** [comment]
IT
1. go to sales order, add a new line and make sure the product has bpartner product
2. go to that bpartner product and make sure you have pricelist set on vendor tab
3. go back to sales order - actions - create purchase orders
4. add a qty to that bpartner from bpartner product, pres done
5. complete the sales order
=> you get one ore more notifications like "purchase order no for vendor value+name has been created"
