### ISSUE TITLE
purchase candidates: implement locking mechanism

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3056]
### Is this a bug or feature request?
FR
https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the current behavior?
there is no locking mechanism

### What is the expected or desired behavior?
Have a locking mechanism which would prevent editing the purchase candidates while there were enqueued to be processed.

**Comment by teosarca** [comment]
Troubleshooting queries
----

### Check purchase candidate locks
```sql
select
	(select t.TableName from AD_Table t where t.AD_Table_ID=l.AD_Table_ID) as TableName
	, l.*
from T_Lock l
where l.AD_Table_ID=540425
```

### Check purchase candidates enqueued to be processed
```sql
select
	wp.C_Queue_Workpackage_ID
	, wp.Processed as WP_Processed
	, wp.IsError as WP_Error
	-- , qe.AD_Table_ID, qe.Record_ID
	, pc.Processed, C_OrderLinePO_ID, C_OrderSO_ID, C_OrderLineSO_ID, pc.QtyRequiered
from C_Queue_Block qb
inner join C_Queue_Workpackage wp on wp.C_Queue_Block_ID=qb.C_Queue_BLock_ID
inner join C_Queue_Element qe on qe.C_Queue_Workpackage_ID=wp.C_Queue_Workpackage_ID
left outer join C_PurchaseCandidate pc on pc.C_PurchaseCandidate_ID=qe.Record_ID
where qb.C_Queue_PackageProcessor_ID=540053 -- de.metas.purchasecandidate.async.C_PurchaseCandidates_GeneratePurchaseOrders
order by wp.C_Queue_Workpackage_ID
```

**Comment by teosarca** [comment]
note to IT: full purchase candidates regression is needed.

**Comment by metas-lc** [comment]
IT
product has no bp => no detail rows OK
product has 1 bp => one line, one included line (one row selected), 
				 =>	two lines, one included line each (2 rows selected)
				 
product has 2 bp => one line, 2 included lines (one row selected), 
				 =>	two lines, 2 included lines each (2 rows selected)

complete sales order before
=> once you press done in "create purchase orders" and the sales order is completed, the line gets readonly
(even if the qty is 0, but we have a task: https://github.com/metasfresh/metasfresh/issues/3135). The purchase orders are created directly

complete after
=> the lines don't get readonly until you complete the sales order. You can update the candidates as many times as you want. After you complete the sales order, the purchase orders are created
