### ISSUE TITLE
display order, forecast or shipmentschedule in material dispo main window

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3057]
### Is this a bug or feature request?
enhancement
### What is the current behavior?
..currently they can just be seen in the demanddetail subtab

### What is the expected or desired behavior?
they should also be in the "main" tab

**Comment by metas-ts** [comment]
hi @metas-mk , 
i added the SQL columns to MD_Candidate..
feel free to display them and push the issue forward

**Comment by metas-mk** [comment]
@metas-ts 
Tested Reference to materialdispo from sales order. NOK
![image](https://user-images.githubusercontent.com/13365687/33184233-e315b86e-d07b-11e7-8ff1-1717ecd349f9.png)

**Comment by metas-mk** [comment]
@metas-ts order by column leads to this error. NOK
![image](https://user-images.githubusercontent.com/13365687/33184633-d6715314-d07d-11e7-9e1d-ea4444b2fa1d.png)

**Comment by metas-mk** [comment]
@metas-ts filter by order
![image](https://user-images.githubusercontent.com/13365687/33184673-03b51e82-d07e-11e7-935b-84d40e5ab753.png)

**Comment by metas-lc** [comment]
IT
1. order, forecast and shipmentschedule are added in material dispo main window  OK
2. order, forecast and shipmentschedule are not translated (will create a followup)
3. sorting for aufrag, lieferdispo or forecast throws errors NOK
4. reference
