### ISSUE TITLE
TypedSqlQuery Bugs because aggregateList method ignores order

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3060]
### Is this a bug or feature request?
Bug
### What is the current behavior?
E.g. if you invoke `listDistinct(String Class<AT>)` or `first(String Class<AT>)`, the ordering is ignored and therefore you get "something".
It's because they use `aggregateList` which explicitly discards any ordering

### What is the expected or desired behavior?

OrderBy shall be taken into account..at least, when it needed

**Comment by metas-rc** [comment]
Note: There is nothing to IT.
