### ISSUE TITLE
PP Order not shown in materialdispo although automatically generated

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3065]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the PP Order is not shown in manufacturing detail tab after an automatic or manual creation.
#### Which are the steps to reproduce?
Open Try and see.
### What is the expected or desired behavior?
Show the PP Order info in manufacturing detail tab.

![image](https://user-images.githubusercontent.com/13365687/33197226-70f7b642-d0e4-11e7-8e05-b0379aa1e61f.png)

![image](https://user-images.githubusercontent.com/13365687/33197276-b2a0c4c6-d0e4-11e7-9077-2791a1cac06e.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & customer db

*  PP Order info in manufacturing detail tab: for manual PP_Order: OK
*  PP Order info in manufacturing detail tab: for automatically generated PP_Order: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* PP Order info in manufacturing detail tab: for automatically generated PP_Order (status: Drafted): OK
