### ISSUE TITLE
WebUI: Adapt Manufacturing Order window to current guidelines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3066]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Manufacturing Order window is not adapted to the current WebUI guidelines.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adapt the manufacturing order window and check if the most relevant information is shown in the main view and if the translations for en_US and de_De are complete.

**Comment by metas-lc** [comment]
IT
DOC VIEW
TL: mandatory, important OK
TR: doctype, no, date OK
BR: org, client OK

GRIDVIEW
first: doctype, no, date OK
last: status, org - status is missing NOK 
order by: date desc OK
filters: date, bpartner, no, doctype - doctype is missing NOK

INCLUDED TABS
handling units and product attributes tabs don't have white background NOK

TRANSLATIONS
NOKs:
(en_US) 
main: Geschäftspartner (en_US) 
hu assignments tab: Menge (en_US)

(de_DE)
advanced edit: Copy From, MRP Generated Document, MRP Allow Cleanup, To be deleted (MRP) - last element group from advanced edit (de_DE)
arbeitsablauf subtab - i think some words are not transtaled there for de_DE (e.g. Moving Time, Duration Unit etc)
not sure about "Handling Unit Assignment" tab? and handling units field (de_DE)?

followup: https://github.com/metasfresh/metasfresh/issues/3131
