### ISSUE TITLE
de_metas_purchasecandidate schema containing some diagnosis views

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3072]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

### What is the expected or desired behavior?
Create  de_metas_purchasecandidate  db schema.
In that schema add those 2 diagnosis views defined here: https://github.com/metasfresh/metasfresh/issues/3056#issuecomment-346761665 .
You can call them t_lock_diag_c_purchasecandidate and C_PurchaseCandidate_Enqueued respectively.

**Comment by metas-rc** [comment]
Results of IT

* OK: The schema was added in the database
* OK: The schema contains the 2 diagnostic views: de_metas_purchasecandidate.c_purchasecandidate_enqueued and 
select * from de_metas_purchasecandidate.t_lock_diag_c_purchasecandidate
* OK: The view work correctly.
