### ISSUE TITLE
Error: Could not find or load main class ${argLine}

### ISSUE THREAD

**Issue by gp1864** [metasfresh/metasfresh#3073]
### Is this a bug or feature request?
bug
### What is the current behavior?
When running local build of metasfresh distributable from command line, tests fail with a message: 

`Error: Could not find or load main class ${argLine}`

The reason of such behavior is that `argLine` property from POM file of `metasfresh-parent` repository does not have any value and thus is not substituted and left on a command line as `'${argLine}'` string:

`/usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/jre/bin/java '${argLine}' -Xms256m -Xmx2048m -jar /home/xxxxx/tools/metasfresh/repos/metasfresh/de.metas.migration/de.metas.migration.base/target/surefire/surefirebooter4166171272514606443.jar /home/xxxxx/tools/metasfresh/repos/metasfresh/de.metas.migration/de.metas.migration.base/target/surefire 2017-11-24T02-52-24_868-jvmRun1 surefire3861974827102949879tmp surefire_05423199727247223953tmp
`
#### Which are the steps to reproduce?
Steps described in _'Build metasfresh from command line'_ document will reproduce the error: http://docs.metasfresh.org/developers_collection/en/getting_started_mvn_cmdline_en.html.
Build will fail on `mvn install` command run in `metasfresh/de.metas.reactor` directory of  `metasfresh` repository working copy.
### What is the expected or desired behavior?
The build should not fail when `argLine` property does not have any value.
This can be achieved by defining default value of `argLine` in `properties `section of `metasfresh-parent` repository POM file as follows:

		
		<argLine></argLine>

Unfortunately I don't have yet working Jenkins environment and I cannot tell how it works with Jenkins.

**Comment by gp1864** [comment]
Hi,
@metas-ts yes, tests don't fail anymore with that error message and the build finishes successfully. Thank you.
George

**Comment by metas-rc** [comment]
Note: Nothing to IT.
