### ISSUE TITLE
Purchase Candidates add HU_PI_Item and HU_PI_Item Qty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3076]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the HU_PI_Item and HU_PI_Item Qty is missing in Purchase Candidates.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the HU_PI_Item and HU_PI_Item Qty to Purchase Candidates and set them from Sales Orderlines when created. Also used these for the creation of Purchase Orderlines.

Follow-Up of https://github.com/metasfresh/metasfresh-webui-api/issues/664

**Comment by teosarca** [comment]
closing legacy issue
