### ISSUE TITLE
New Picking Configuration Type

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3078]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Picking Window is working with
- 1 Warehouse (Picking Warehouse)
- 1 Product at a time (do all the pickings for 1 Product and then move to the next one)
- multiple picking slots available for usage

#### Which are the steps to reproduce?
Open and see.

### What is the expected or desired behavior?
Have a Picking Terminal configuration that allows to
- aggregate the pickings by sales order (all lines of the sales order grouped) <-- m_picking_config (https://github.com/metasfresh/metasfresh-webui-api/issues/711)
- select a product, scan the picking slot (new barcode scan, will be a barcode on a picking cart). picking slot is selected. (https://github.com/metasfresh/metasfresh-webui-api/issues/716)

- press "open hu editor" button. all HU are shown in the warehouses that are in the picking warehouses group (new dropdown selector in Warehouse)) and are ordered by best-before-date asc (oldest at the top). (https://github.com/metasfresh/metasfresh-webui-api/issues/717)

- the picker scans the locator tray barcode and all hu with the product and are in that locator are filtered. the first hu in that picking tray and product is selected. (https://github.com/metasfresh/metasfresh-webui-api/issues/721)

- the picker presses the pick button and a modal overview opens and shows the product and qty to be picked. a scan of the product is awaited. if it's the correct product then the user can enter the pickedqty. if not then an error appears that says "wrong product". (https://github.com/metasfresh/metasfresh-webui-api/issues/723)

- ... and so on

- at the end the user processes the picking and starts from beginning with a new cart (the carts emptying will be done later with picking slot clearing window).

- the picking will be used on tablets and all the information shall fit on that resolution (has to be detailed).

**Comment by metas-mk** [comment]
Scan Cart Barcode (similar to HU Barcode Scan) in this window
![image](https://user-images.githubusercontent.com/13365687/33216985-6f5e80d4-d136-11e7-8033-3de9cc475f72.png)

**Comment by metas-mk** [comment]
Scan Barcode of Locator can be similar to this just call it "Barcode Locator"
![image](https://user-images.githubusercontent.com/13365687/33217238-52c90b64-d137-11e7-8da3-26277721a45c.png)

**Comment by teosarca** [comment]
note to IT: there was no particular development on this task but on the tasks we split out from this.
Anyways, on this task we need to test if the overall functionality is delivered and if all tasks are gluing together nicely.

**Comment by teosarca** [comment]
TODO: make sure the QtyPicked/to be picked from left side (shipment schedules) are up2date. Need to create a task for it.

**Comment by metas-rc** [comment]
Results of IT


*  OK:  Picking config is around for a while and is working. 

Since all the related tasks are in done, I am moving this task to done, too.
