### ISSUE TITLE
New Window for manual OnHand Qty in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3082]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window in WebUI that allows to record the manual OnHand Qty for puchasing.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the Window in WebUI and add to Material Management.

**Comment by metas-mk** [comment]
Error when creating a new record:
https://github.com/metasfresh/metasfresh-webui-api/issues/704

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for manual OnHand Qty (Zählbestand Einkauf): OK
* translation:  no translation for en_US yet
