### ISSUE TITLE
Get rid of group columns in new window for procurement stock count

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3087]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is an error in the window for procurement stock count that says that sql tables are missing for a virtual column.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Get rid of the sql query in those columns and add a translation for the window "Zählbestand".

**Comment by metas-lc** [comment]
IT
Stock Control Purchase window is translated in en_US OK
no errors OK
