### ISSUE TITLE
Transform in material receipt left destroyed HU behind

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3088]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When Transforming a HU in Material Receipt/ HU Editor, then the source HU is left back in status "destroyed".
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The source HU shall not be shown when destroyed.

![image](https://user-images.githubusercontent.com/13365687/33258884-47ac8460-d35b-11e7-8688-c64baf7bdbac.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

destroyed HUs are still shown after Transform, NOK:

![2017-12-04 16_27_29-metasfresh](https://user-images.githubusercontent.com/18696715/33560617-86d26c08-d910-11e7-87e0-e04791a08f98.png)

**Comment by teosarca** [comment]
@metas-dh   what kind of transform did u do? asking because i will have to handle each operation individually...

**Comment by metas-dh** [comment]
@teosarca i took all TUs out of an LU,  =>"TU to new TUs"

**Comment by teosarca** [comment]
update: fixed the "TU to new TUs" case

**Comment by metas-ts** [comment]
cherry-picked to `2017-12` and `release`

**Comment by metas-lc** [comment]
go to receipt candidates, open HU editor with 2 LUs, each with 1 TU
select a TU -> transform -> **TU to existing LU**
=> the LU is still shown, readonly NOK
=> also noticed that the TU doesn't appear on the other LU NOK (might not be related)
task: https://github.com/metasfresh/metasfresh-webui-api/issues/775

go to receipt candidates, open HU editor with 1 LU, with 1 TU
select the TU -> transform -> **TU to new LU**
=> the LU is still shown, readonly NOK
task https://github.com/metasfresh/metasfresh-webui-api/issues/775

go to receipt candidates, open HU editor with 1 LU, with 6 TUs
select the TU -> transform -> **TU to new TUs**
=> nothing happens NOK - created task: https://github.com/metasfresh/metasfresh-webui-api/issues/774
