### ISSUE TITLE
Not able to start report service with ReportServiceMain.launch

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3089]
### Is this a bug or feature request?
Bug

Thx @seanlixc for pointing out the problem and providing a fix..
Note that everything ReportServiceMain does is also done by the normal app server started via the `\metasfresh-dist\de.metas.ServerBoot_mf15.launch` file.
we have the standalone report service just as an option

**Comment by metas-rc** [comment]
Nothing to IT, after talking with metas-ts. Moving to done
