### ISSUE TITLE
Activity ID in Purchase Orderline Grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3094]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the c_activity_id is not shown in the orderline grid view of purchase order.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the c_activity_id to orderline grid view.

**Comment by metas-lc** [comment]
IT
go to purchase order, create a new one, add a line
=> c_activity_id is shown, and it's translated OK
set a c_activity_id, complete
=> works fine, no errors OK
