### ISSUE TITLE
WebUI: new Window for AD_Session in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3095]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for ad_session in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the window for ad_session in WebUI.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


OK :The window Session Audit was added to the menu
OK: All its fields are translated into English
OK: The included tab is functional and with white background
OK: The cornerstones are respected.
