### ISSUE TITLE
material-dispo: MaterialQuery shall support bpartnerId when fetching available stock

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3098]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3079, https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
there is no way to fetch the available stock for a given bpartner.

### What is the expected or desired behavior?
* MaterialQuery shall support bpartnerId when fetching available stock
* de.metas.material.dispo.commons.repository.AvailableStockResult.ResultGroup shall contain and return: warehouseId, bpartnerId

**Comment by teosarca** [comment]
update: all that needs to be done here is:
* MD_Candidate_Stock_v shall support C_BPartner_ID column
* de.metas.material.dispo.commons.repository.StockRepositorySqlHelper.createDBQueryForMaterialQuery(MaterialQuery) - un-comment the code which is filtering by C_BPartner_ID
* de.metas.material.dispo.commons.repository.StockRepository.createResultGroupAddRequest(I_MD_Candidate_Stock_v) - set ResultGroupAddRequest's bpartnerId from stockRecord

**Comment by metas-dh** [comment]
All testing is done in #3079, moving this to Done.
