### ISSUE TITLE
Improve Product import process 

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3105]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
Improve code and add columns:
* PackageSize
* Package_UOM_ID
* Prescription
* IsColdChain
* M_Indication_ID
* FM_Zub

**Comment by metas-rc** [comment]
Results of IT

Tested on swing

Importing worked correctly
The product was created with the values existing in the import file.

**Comment by metasnw** [comment]
@cristinamghita I tested the import and have two questions 
1. why is Package_UOM_ID a mandatory field?
1. Also I noted that you cant use the product import to update prices anymore but I have not tried that for some time. When I tried I got a message regarding duplicate value. Do you know if you changed something in that area?

**Comment by cristinamghita** [comment]
@metasnw 
1. Package_UOM_ID should not be mandatory; I'll check it
2. I did not touch that area. I think was like that for some time.
