### ISSUE TITLE
Warehouse picking group window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3107]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3079
https://github.com/metasfresh/metasfresh/issues/3078

### What is the expected or desired behavior?
* add Warehouse Picking Group to webui menu (https://w101.metasfresh.com:8443/window/540380)
* check Warehouse window, make sure the Warehouse Picking Group is displayed correctly (atm, it's an advanced field)

** Wait for https://github.com/metasfresh/metasfresh/issues/3079 to be integrated**

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* add Warehouse Picking Group to webui menu: OK (Lager Gruppe Kommissionierung / Warehouse Picking Group, in Warehouse Management / Settings)
* make sure the Warehouse Picking Group is displayed correctly in Warehouse window: displayed in Advanced Edit mode: OK
=> it's "Warehouse Picking Group" in Warehouse window, de_DE, needs to be translated

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

*"Warehouse Picking Group" in Warehouse window, de_DE, now Lager Gruppe Kommissionierung": OK
