### ISSUE TITLE
Request All does not show records

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3110]
### Is this a bug or feature request?
bug

### What is the current behavior?
request (all) window does not show records when opened

#### Which are the steps to reproduce?
1. have one request
1. open window  request (all) 

workaround: click on watch and select all

![image](https://user-images.githubusercontent.com/16079655/33423738-01f13324-d5ba-11e7-9722-78836812ff18.png)

### What is the expected or desired behavior?
should load records right away

**Comment by metas-lc** [comment]
IT
made a request. Opened both request and request (all) => record was loaded OK
