### ISSUE TITLE
Add Netsum to Vendor Invoice Document Grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3122]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Netsum is not shown in the Vendor Invoice Grid View.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add Netsum to Vendor Invoice Document Grid View

**Comment by metas-lc** [comment]
IT
go to vendor invoice - grid view => Net Sum is there (translated) OK
