### ISSUE TITLE
Picking terminal: pimp Picking Configuration window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3124]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3078
https://github.com/metasfresh/metasfresh-webui-api/issues/711

### What is the expected or desired behavior?
Check picking configuration window: https://w101.metasfresh.com:8443/window/540382 (as **System Administrator**).
* make sure it's in the right place in menu
* make sure layout, trls etc are OK

**Comment by metas-lc** [comment]
IT
place: Menu/Lieferung/Einstellungen/Kommissionierung Profil
         /webUI/Shipment/Settings/Picking Configuration OK

translations: fields are not translated to en_US NOK - created follow-up https://github.com/metasfresh/metasfresh/issues/3140

grid view: 
TL: mandatory/important OK
TR: flags OK
BR: org, client OK
