### ISSUE TITLE
Qtydelivered in PMM_Balance gets doubled

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3128]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Qtydelivered in PMM_Balance, used for the the Procurement Excel, is doubled.
#### Which are the steps to reproduce?
1. Have a bpartner with a running flatrate term for procurement
2. Create a purchase order for that bpartner and the product from the procurement flatrate term (does not have to be an order created from procurement candidate, since all Qtydelivered of the product from that bpartner is considered for the Qtydelivered of PMM_Balance, as long as the flatrate term is running)
3. Create a material receipt
4. Check PMM_Balance for that bpartner and the product: Qtydelivered is twice the amt of your actual inout: NOK
### What is the expected or desired behavior?
Qtydelivered in PMM_Balance shall be the correct qty from material receipt.

**Comment by metas-ts** [comment]
cherry-picked to `release` and `2017-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / customer db

* Qtydelivered in PMM_Balance is not doubled anymore: OK
