### ISSUE TITLE
Clean C_PaySelection 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3137]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The C_PaySelection was changed into a document. Remove all that is no longer needed.
### What is the expected or desired behavior?
DONE ( by Tobi):
* rename process to C_PaySelection_SEPA_XmlExport (follow best-practice of having the process value and class start with the table in question)
* assign process to the gear and only show it if the C_PaySelection record is competed/closed
* when exporting to XML, don't filter by C_PayselectionLine.Processed='Y'
* when exporting to XML, use Strd for payment type 1 (ESR) and Ustrd for payment type 3 (iban)

TODO:
* remove processed column from C_PaySelectionLine
* remove sepa-export and processing fields and columns
* remove C_PaySelection_ReActivate process

**Comment by metas-lc** [comment]
IT
made a new C_PaySelection  manually (window payment selection, id 206)
=> there is no action to "Create from" OK???
added a new line, with an invoice, manually
=> the reference was not set (probably i had some config missing?) OK???
i added a reference and completed the payment selection
=> i didn't find any SEPA action OK???

**Comment by metas-lc** [comment]
IT
0. make sure you have some invoices with a bpartner that has bank account andinvoices should have po references
1. made a new C_PaySelection manually (window payment selection, id 206) 
=> there is action to "Create from" OK
(it has Business Partner Group, Business Partner, Match Requirement, Zahldatum, Only Due, Only Discount, Include Disputed)
2. set params (i choose to have all checkboxes on N and Match Requirement on All)
=> new lines were added OK
(in reference field was set the reference from invoice)
3. complete the pay selection, go to actions
=> sepa export action is there OK
(there is no button to choose where to save the file. See if we need a task for that)
