### ISSUE TITLE
Cannot edit System Administrator role (AD_Role_ID=0)

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3139]
### Is this a bug or feature request?
bug
### What is the current behavior?
error in Role window on WEBUI_Role column
#### Which are the steps to reproduce?
1. login as sysadmin, open Role window and try to set WEBUI Rolle on Y
=> System aktualisiert Datensatz. WEBUI_Role= false(java.lang.Boolean) != DB: null -> New: true(java.lang.Boolean)
### What is the expected or desired behavior?
should work

### Note IT
Because this was a generic problem, check the same thing on AD_Client_ID=0, AD_Org_ID=0, AD_User_ID=0.
Regression: try to create some rows (new Role, new User etc) using Swing and webui.

**Comment by metas-lc** [comment]
1. swing (admin and sysadmin): 
set WEBUI_Role on Y/N OK
create new roles and users OK
2. webui
set WEBUI_Role on Y/N NOK
Happens only when you login with sysadmin, when you update System Administrator 
=> the document is not saved:
{saved: false, hasChanges: true, error: true,…}
error:true
hasChanges:true
reason:"org.postgresql.util.PSQLException: ERROR: null value in column "name" violates not-null constraint↵  Detail: Failing row contains (1000050, 0, 0, Y, 2017-12-08 16:30:46+01, 100, 2017-12-08 16:30:46+01, null, 100, null, S__, null, 0, null, N, N, N, N, Y, Y, null, Y, N, N, O, N, N, null, 0, 0, null, N, N, N, N, N, N, N, N, Y, N, N, null, Y, Y, N, N, N, Y, N, null, null, N, N, N, null, null, Y, Y, N, N).↵	SQL: INSERT INTO AD_Role (AD_Client_ID,AD_Org_ID,AD_Role_ID,ConfirmQueryRecords,Created,CreatedBy,IsAccessAllOrgs,IsActive,IsCanExport,IsCanReport,IsChangeLog,IsManual,IsPersonalAccess,IsPersonalLock,IsShowAcct,IsUseUserOrgAccess,MaxQueryRecords,OverwritePriceLimit,PreferenceType,Updated,UpdatedBy,UserLevel,WEBUI_Role) VALUES (0,0,nextval('ad_role_seq'),0,TO_TIMESTAMP('2017-12-08 16:30:46','YYYY-MM-DD HH24:MI:SS'),100,'N','Y','Y','Y','N','N','N','N','N','N',0,'N','O',TO_TIMESTAMP('2017-12-08 16:30:46','YYYY-MM-DD HH24:MI:SS'),100,'S__','Y') RETURNING AD_Role_ID"
saved:false

create new roles and users OK

**Comment by teosarca** [comment]
@metas-lc  please also editing the system client, org zero, and System Administrator user.

**Comment by metas-lc** [comment]
IT
retested the cases above => works fine, no errors

**Comment by metas-ts** [comment]
CPed to `release`
