### ISSUE TITLE
WebUI: Translate Picking Configuration window to en_US

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3140]
### Is this a bug or feature request?
fr
### What is the current behavior?
 Picking Configuration window fields are not translated
#### Which are the steps to reproduce?
open  Picking Configuration window as sysadmin, set language to en_US
=> notice fields are still in de_DE
### What is the expected or desired behavior?
fields shall be translated to en_US

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

OK: The Picking Configuration window is fully translated into English.
