### ISSUE TITLE
Always keep Terms & Conditions equal per Compensation Group

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3150]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user can define different Terms and conditions per group.
#### Which are the steps to reproduce?
- create an orderline and additional group line
- change the terms and conditions per line individually.
### What is the expected or desired behavior?
The Terms and conditions of a compensation group shall always be equal in all lines of the group.
- if the user adjusts the terms & conditions of a line that belongs to a group, then all group lines are updates/ set to the same terms and conditions id
- id the user creates a new line, sets the terms and conditions and then creates a group with another product, then that additional line shall initially have the terms & conditions of the first line.

![image](https://user-images.githubusercontent.com/13365687/33666738-36456b1e-da9b-11e7-8467-cd98ed7bd6f5.png)

**Comment by metasnw** [comment]
tried it https://w101.metasfresh.com:8443/window/143/1000219
but nothing happens when I select a condition on one line of a group

**Comment by metasnw** [comment]
is waiting for #3149 to be working

**Comment by teosarca** [comment]
shall be available on next build/rollout.

**Comment by teosarca** [comment]
Hotfixed following case:
* have a discount schema with a discount defined for your group compensation product
* have an order with a regular order line, terms & conditions not set
* select the line and from menu create a compensation group (on w101, use Discount 10% product which already has a discount schema configured  on bpartner nw_test01) => Compensation Percentage is set from discount schema => OK
* on first line, go and change the term&conditions from "nothing" to "abo".
=> both lines now have the "abo" terms and conditions => OK
=> on second line (i.e. the discount line) remark that there is a difference between PriceEntered and PriceActual => right click on that line and go to Advanced edit. In advanced edit, remark that the Discount (i am not talking about group compensation percent!) is set (to 5% in my case) => NOK, when a line is a group compensation line the Discount shall ALWAYS be ZERO.

**Comment by metasnw** [comment]
testing together with #3149
