### ISSUE TITLE
ZoomTo-Performance Issues

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3151]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Takes too long on DBs with a lot of data

**Comment by metas-ts** [comment]
note to IT: please take a look at zoom from 
* Sales-Order with subscription-lines to C_FlatrateTerm
* Sales- and Purchase-Order to invoice candidate

**Comment by metas-dh** [comment]
Results of IT
tested in mf15 & customer db (last 2 e2e tests)

* Sales-Order with subscription-lines to C_FlatrateTerm: OK
* Sales- and Purchase-Order to invoice candidate: slow in 1st testing, but improved in the 2nd

* Product to Changelog: Dropdown in Zoom into in Product window takes sev. mins to open, in Swing & WEbUI: NOK

**Comment by teosarca** [comment]
IMHO, the change log will always be problematic... We can think for tables like this one to not count how many records there are for our selected thing (e.g. Product)
wdyt?

**Comment by metas-ts** [comment]
> IMHO, the change log will always be problematic...

i don't know that. IMHO, let's look at the particular reason for the reported case first

**Comment by metas-ts** [comment]
Update: checked the situation with the `ZoomInfoFactoryExecute` ("Diagnose ZoomInfoFactory") process:

* the RelationTypeZoomProvider that looked up results for `AD_ChangeLog`: 2ms :triumph: 
* the GenericZoomInfoDescriptor that looked up results for `M_HU` and `RV_C_OrderLine_Overview`: more than 1minute each

in `AD_Column` we have 
* `IsGenericZoomOrigin` but there is no code that evaluates it
* `IsAllowZoomTo` but it's ignored for top-level `AD_Tabs` (i.e. `AD_Tab`s with `SeqNo=10`)

First quick action: evaluate IsGenericZoomOrigin and set it to 'N' for `M_Product.M_Product_ID` that way we at least don't needlessly punish the DB.

TODO (imho): 
* move `IsAllowZoomTo` from `AD_Column` to `AD_Field`
* migration: set it to `'Y'` for fields that point to columns with "Search", "TableDirect" etc, if the respective `AD_Tab` has `SeqNo=10`
* in GenericZoomProvider, only create GenericZoomInfoDescriptors if the respective to.be target-tab has a field with `IsAllowZoomTo = 'Y'`

**Comment by metas-ts** [comment]
Hi @metas-mk @metasnw 
as of me recent commit, zoom is effectively "off" for M_Product (didn't work and caused high DB load on large DBs).
To get it back, please push https://github.com/metasfresh/metasfresh/issues/3519

**Comment by teosarca** [comment]
i think you shall do the same of other highly used master data, e.g. C_BPartner.
wdyt?

**Comment by metasnw** [comment]
I would introduce a switch and make it default Y for small and default systems.
On systems with big data we can switch it off but would not affect the rest of the world.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Zoom into for  M_Product: generally off: OK
* can be set on in db: OK
* Sales-Order with subscription-lines to C_FlatrateTerm: OK
* Sales- and Purchase-Order to invoice candidate: OK


>make it default Y for small and default systems:

@metasnw shall i create a new task for this?

**Comment by teosarca** [comment]
not sure how to differentiate (automatically) between small and big systems...

**Comment by metasnw** [comment]
I dont think we should do it automatically. 
its up to the admin to set the switch when he recognize that db size grows so heavy so zoom into speed drops. That is when he needs the option to switch it off to speed things up.
I would not disable it for all the small default systems.

**Comment by teosarca** [comment]
so it shall be enabled by default and Admins can tweak it for large system.
@metas-ts  wdyt?

**Comment by metas-rc** [comment]
I talked woth Tobi and he agreed to move this task to Done.
