### ISSUE TITLE
Translate new fields in bpartner window for pharmacy

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3152]
## Is this a bug or feature request?
FR
### What is the current behavior?
New fields in bpartner window, introduced in #3042, are not translated / have no proper names yet.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Pls add translations / names.

**Comment by teosarca** [comment]
i think this one was solved by https://github.com/metasfresh/metasfresh/issues/3166
If that's true, @metas-mk  pls close it

**Comment by metas-mk** [comment]
thx @teosarca . yes, did it all in once. closing this one.
