### ISSUE TITLE
Translation Tab content missing for Product_Trl

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3159]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Translations are missing for Product_trl. The content is not shown in the window&tab.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Show the content again.

**Comment by metas-lc** [comment]
IT
swing -> product -> translation tab => can see translations OK
