### ISSUE TITLE
C_Printing_Queue_ReEnqueue with IsSelected doesn't work

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3160]
### Is this a bug or feature request?
Bug

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

1. Have sev. entries in C_Printing_Queue (i filtered by date of creation)
2. Run process C_Printing_Queue_ReEnqueue with IsSelected set:
  * the entries in C_Printing_Queue are re-enqueued: OK
  * the existing entries are marked as processed: OK

**Comment by metas-dh** [comment]
Update:

* WebUI window: OK
* tested again in customer e2e, Swing: OK (customer only uses Swing version)
