### ISSUE TITLE
Material Receipt Candidates not generates when using Purchase Order from Sales Order action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3174]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Material Receipt Candidates are not generated when using Purchase Order from Sales Order Line action.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall automatically generate Material Receipt Candidates.

Testcase:
Sales Order 0151
https://w101.metasfresh.com:8443/window/143/1000223
Jump to Purchase Order.
Open Document Reference -> No Material Receipt Candidates

**Comment by metas-lc** [comment]
IT
1. created new purchase orders from sales order lines. Some with complete sales order before, and some after.
2. went to all new created purchase orders
=> all have receipt candidates OK
3. press on "Receive HUs (default)" action
Error: LU/TU configuration is resulting...
Server error
LU/TU configuration is resulting to infinite quantity: X_M_HU_LUTU_Configuration[M_HU_LUTU_Configuration_ID=1000016, trxName=<<ThreadInherited>>]
4. use receive cus 
=> create material receipt works, as well as transform OK
