### ISSUE TITLE
Translate Sales Order Actions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3176]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, in Sales Order Action menu some entries don't have translations for de_DE.
#### Which are the steps to reproduce?
Open and dee.
### What is the expected or desired behavior?
Add german Translations for those entries and check the english translations too.

![image](https://user-images.githubusercontent.com/13365687/33794247-522247ce-dcc8-11e7-8b36-c0452af1d208.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

NOK: The Action Re-create MRP records for current document is still not translated into German:

![image](https://user-images.githubusercontent.com/16001442/33837834-60d94072-de96-11e7-8f4a-35315d819979.png)


OK: The other actions are translated into German
OK: All the actions are translated into English.

**Comment by metas-ts** [comment]
@metas-rc i believe this process is obsolete.
@metas-mk @teosarca am I right?
If so, I suggest that you remove the AD_Process and also its java class..

**Comment by teosarca** [comment]
@metas-ts yes, it's obsolete together with the whole MRP thing.

**Comment by metas-rc** [comment]
IT update:

The process that was not translated is obsolete. It has to be deleted.
Followup created: https://github.com/metasfresh/metasfresh/issues/3204
