### ISSUE TITLE
New Action add to Shipper transportation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3188]
### Is this a bug or feature request?
Feature Request
related to https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
Currently, in Picking tray Clearing Window, the user can clear the Picking Slots, but not add the cleared HU to a Shipper Transportation.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
a) New Filter on the left side to filter Picking Slots by
* Business Partner (https://github.com/metasfresh/metasfresh-webui-api/issues/747)
* and BP Location (https://github.com/metasfresh/metasfresh-webui-api/issues/748)

b) New Action on the right side that moves all selected HU to a Shipper Transportation defined in Action Parm. (https://github.com/metasfresh/metasfresh-webui-api/issues/751)

![image](https://user-images.githubusercontent.com/13365687/33836430-aff7a78c-de89-11e7-909f-a92c950a7466.png)

### Note to Integrator
There are some commits which were linked by mistake to this task.
I've linked them to their correct task too.
DO NOT INTEGRATE this task because there is nothing to be integrated.

**Comment by teosarca** [comment]
note to IT:

Together with @metas-mk  we decided to postpone the filtering by BPartner Location task (https://github.com/metasfresh/metasfresh-webui-api/issues/748).
Besides that, everything is delivered so, i am moving this task to Test.
Make sure the actual tasks were rolled out.

**Comment by metas-mk** [comment]
Tested. Works. Closing.
