### ISSUE TITLE
New Features in Picking Tray Clearing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3190]
### Is this a bug or feature request?
Feature Request
related to https://github.com/metasfresh/metasfresh/issues/3188

### What is the current behavior?
Currently, the Picking Tray allows to empty picking trays. A few details are missing.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
a) Filter for Picking Slot Barcode on the left view (https://github.com/metasfresh/metasfresh-webui-api/issues/746)
b) Action to take out HU and add to new Packing Material. Add to right view as HU. (https://github.com/metasfresh/metasfresh-webui-api/issues/760)
c) Select line on left side and packing material on right side and allow action "Take out HU" and add to exsting HU. (https://github.com/metasfresh/metasfresh-webui-api/issues/758)
d) Select all in right view and use Action in right view "Add to Transportationorder" and finalize (create Shipment, create invoice (if not Invoice Schedule weekly/ monthly), add to Shipper Transportation, create Label for Package. (https://github.com/metasfresh/metasfresh-webui-api/issues/763, https://github.com/metasfresh/metasfresh-webui-api/issues/768)

![image](https://user-images.githubusercontent.com/13365687/33836980-44d5a06a-de8b-11e7-9642-9cf2b9e52d93.png)

**Comment by metas-dh** [comment]
all related tasks including detailed requirements are done, closing this one as well.
