### ISSUE TITLE
Improve Window for manual OnHand Qty in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3193]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the included Subtab does not have enough fields for recording.
#### Which are the steps to reproduce?
Open, try and see
### What is the expected or desired behavior?
Add the missing fields.

**Comment by metas-ts** [comment]
@metas-mk wdyt about calling this window  StockEstimate/Bestandschätzung? Because "manual" or "counting" don't really capture how this finctionality is different to an inventory..

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

Note: The window this task is about is called Stock Control Purchase.

* OK: The window is added in the menu
* OK: I was able to create entries with lines. They saved correctly.
* OK: The layout conventions are respected.
*OK: There are translations for both English nd German
