### ISSUE TITLE
dunning run: Exception on PDF generation 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3196]
### Is this a bug or feature request?
bug

### What is the current behavior?
dunning doc can be created but no PDF is created.
exception: https://pastebin.com/wd9tYDTv

#### Which are the steps to reproduce?
1. setup dunning https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_webui_collection/EN/Setup_Dunning.md
1. perform a run https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_webui_collection/EN/Dunning_Run.md

**Comment by cristinamghita** [comment]
It was a configuration issue.
In C_Doc_Outbound_Config, for table "C_DunningDoc" should be also set the print format
because doesn't know otherwise from where to take it.
**Updated the documentation. See step 4.**
[Setup Dunning](https://github.com/metasfresh/metasfresh-documentation/blob/gh-pages/_webui_collection/EN/Setup_Dunning.md)

**Comment by teosarca** [comment]
@cristinamghita @metasnw   even if is a config issue, I would suggest to avoid throwing NPE but something with a understandable error message. wdyt?

**Comment by cristinamghita** [comment]
@teosarca @metasnw Agree!
Created a fix for that.
Thx @teosarca !

**Comment by metas-lc** [comment]
IT
1. did all configs for dunning, except setting printformat in  C_Doc_Outbound_Config
2. created some invoices, then create/update dunning candidates
3. processed dunning candidates
4. went to async window, searched for DocOutboundWorkpackageProcessor
=> found one, with error
NoDocPrintFormatAdditional parameters: I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000301, trxName=null] IQueueProcessor: ThreadPoolQueueProcessor{name=DocOutboundWorkpackageProcessor, executor=BlockingThreadPoolExecutor [getPo...
OK
5. went to C_Doc_Outbound_Config, set the print format
6. went to asking and set iserror on N
=> DocOutboundWorkpackageProcessor got processed 
OK
