### ISSUE TITLE
Error in Paymentjournal Process/ Report in Payselection

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3202]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it's not possible to start the Paymentjournal report in Payselection.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work. The issue comes from deleted table c_payselectioncheck.
de.metas.fresh\de.metas.fresh.base\src\main\jasperreports\de\metas\reports\openpayments\report.jrxml

**Comment by metas-lc** [comment]
both payselectioncheck and payment were not used by jasper. Taking them out
