### ISSUE TITLE
Relation sales order - flatrate term is missing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3206]
### Is this a bug or feature request?
Bug
### What is the current behavior?
There is no relation between sales order & flatrate term anymore.
#### Which are the steps to reproduce?
1. Create a flatrate term from sales order, see http://docs.metasfresh.org/webui_collection/EN/Create_contract.html
2. Check related documents in the order: no relation to flatrate term, NOK
### What is the expected or desired behavior?
 Relation between sales order & flatrate term

**Comment by metas-lc** [comment]
IT
1. created new terms and conditions
2. created a new sales order, added a product and set the conditions i created above
3. completed the order, went to related documents
=> Contract was there, and when i selected it the window opened with the correct contract, in grid view OK
