### ISSUE TITLE
Cannot save an attribute in orderline 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3207]
### Is this a bug or feature request?
Bug
### What is the current behavior?
An attribute cannot be saved when set in orderline (sales order). 
Pls note: this is only happening in Swing, it worked fine win WebUI.
#### Which are the steps to reproduce?
1. Have a product from a product category, which has an attributesetinstance set (e.g. Convenience Salate)
2. Create a sales order in Swing Client
3. Create an orderline with that product
4. Change the attribute in orderline, select e.g. Bio
5. Try to save:
>Ausnahme:
Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
Bitte leiten Sie diese Meldung an metas weiter:  Error: This method shall not be called with M_AttributeSetInstance_ID=0

Nothing shown in console though.
### What is the expected or desired behavior?
Should work without errors.

**Comment by metas-lc** [comment]
IT
repeated the testcase above in both swing and webui: works fine OK
