### ISSUE TITLE
Manufacturing Issue action take exact qty from stock

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3210]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is possible in Swing Client to issue qties based on their planned qties. This option is not available in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow to select a component line and start action "Issue planned qties". The action shall take the found matching product in Source HU in the planned qty. If the qty is not sufficient, then issue the qty that's available. The lowest HU ID first.

**Comment by teosarca** [comment]
shall be solved by https://github.com/metasfresh/metasfresh/issues/3463

**Comment by metas-rc** [comment]
Note for IT: Please, check if the process from #3463 is covering the requirements here and put in done if so. Otherwise, please describe what is not covered.

**Comment by metas-rc** [comment]
NOTE: not relevant until #3463 is integrated. There is no implementation in this task.

**Comment by metas-dh** [comment]
see https://github.com/metasfresh/metasfresh/issues/3463#issuecomment-395037308

**Comment by metas-lc** [comment]
see NOKs from https://github.com/metasfresh/metasfresh/issues/3463 related with this task

**Comment by metas-dh** [comment]
see Results of IT3, #3463

**Comment by metas-rc** [comment]
See #3463

**Comment by metas-dh** [comment]
see last IT of 3463
