### ISSUE TITLE
New Action for Repost Document in Accounting Transaction Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3213]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to repost a document in WebUI. This was a functionality in Swing Client that was used often after adjusting accounting parms and reposting single documents in an open period.
#### Which are the steps to reproduce
Open, try and see.
### What is the expected or desired behavior?
Add an action to Accounting Transaction window that allows the user to 
a) select all
b) run action "Report"
c) see the reposted result.

![image](https://user-images.githubusercontent.com/13365687/34030244-6004a294-e16c-11e7-81c8-a4b054d71784.png)

**Comment by metas-lc** [comment]
IT
created invoices and payments, posted them 
went to Accounting Transactions window
=> entries were there OK
select actions
=> there are no actions OK
select a line, select actions
=> action: "Fact Account Repost" appeared
select just one line and run "Fact Account Repost", then check in database for updated in fact_acct
=> that fact_acct you selected + related fact_accts are updated
select all lines and run "Fact Account Repost", then check in database for updated in fact_acct
=> all fact_accts are updated OK
