### ISSUE TITLE
Invoice candidate: The isRecompute flag is not reseted on N ever

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3216]
### Is this a bug or feature request?
Bug
### What is the current behavior?
IsRecompute is never set on Y anymore.
The record from c_invoice_candidate_recompute is not deleted
#### Which are the steps to reproduce?
Have an invoice candidate. Close that IC.
Although the IC is now processed, the flag isRecompute remains on Y and that IC is run forever by the process of updating candidates.
### What is the expected or desired behavior?
The flag shall be reset.

**Comment by cristinamghita** [comment]
Additional infos:
* There is no WP unprocessed for that
* Is nothing locked in T_Lock
* In c_invoice_candidate_recompute , ad_pinstance_id  is null

**Comment by metas-ts** [comment]
from what i can see, the display seems to be wrong..`select * from c_invoice_candidate_recompute;` doesn't give me any row at all, yet that row is flagged in the webui

**Comment by metas-ts** [comment]
despite that dispay issue, there is also the described problem...
going to try reproducing it locally, using the "close" action on an invoice cnadidate

**Comment by teosarca** [comment]
> from what i can see, the display seems to be wrong..select * from c_invoice_candidate_recompute; 
> doesn't give me any row at all, yet that row is flagged in the webui

If that's the case, it might be caching issue on webui.
Remember that the IC's IsToRecompute flag is a virtual column and webui has no idea what to do when somebody INSERTED in C_Invoice_Candidate_Recompute.
Maybe we would need to send some cache invalidation events when the ICs are enqueued to be recomputed....

**Comment by metas-ts** [comment]
@teosarca agree
@cristinamghita sorry, i tried on friday and was still unable to reproduce the issue :-(

**Comment by metasnw** [comment]
IT
after applying the update the WPs for invoice candidate update did not come back

**Comment by metas-dh** [comment]
Results of IT
tested in mf15

* invoice candidate after contract change: IsRecompute=Y, OK
* after cache reset: IC is processed and flag IsToRecompute=N, OK
* DB c_invoice_candidate_recompute: empty, OK

**Comment by metas-ts** [comment]
:cherries: to `release`
