### ISSUE TITLE
refactor trx event listeners

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3222]
### Is this a bug or feature request?
FR
### What is the current behavior?
* currently you have one ITrxListner interface with a number of methods.
* the problem with that is that if you register another listener within a listener's method (for the same transaction), the frameworks can't dedice whether that's OK or not
  * OK-example: register a listener for `after-rollback` from within a listener's `before-commit`
  * NOK: register things other way round

### What is the expected or desired behavior?

With the new API, we register things and explicitly specify what code is to be executed on which event.

**Comment by metas-rc** [comment]
Nothing to IT. Moving to done.
