### ISSUE TITLE
Error on unclosing a "manually" created PPOrder

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3225]
"manually" means not via material dispo

### Is this a bug or feature request?
Bug
### What is the current behavior?
![greenshot_2017-12-19_07-00-29](https://user-images.githubusercontent.com/1264789/34142962-68e50e50-e48a-11e7-9fb1-a7338499003b.png)

**Comment by metas-dh** [comment]
Results of IT1
tested during customer e2e

* unclosing a "manually" created PPOrder: no error, working fine: OK
* received products are destroyed: OK
* remaining problems:
  * issued HUs remain issued, you cannot select the same HUs for issue again (in my case i could not select the Paloxe marked for Waschprobe 1)
  * Waschprobe: qties in Waschprobe Jasper & IC were different, prob. bc of the unclosed PP_Order
