### ISSUE TITLE
Pharma: import prices

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3230]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
Import price for the standard files.

**Comment by metas-lc** [comment]
IT
1. opened window Import Pahrma product
=> atm there are no entries (in my case) OK
2. go to import file loader and import a csv file with pharma products, using "Pharma Product IFA"
3. refresh "Import Pahrma product" window 
=> new entries are there OK
