### ISSUE TITLE
Disposal creates Invoice Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3232]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when creating disposals, then Invoice Candidates are created.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Invoice Candidates shall not be created.

**Comment by metas-rc** [comment]
Concept: 


If we need no invoice candidates for any inventory, for any client, the solutions would be: 
* Delete the invoice caniddate handlers for inventory and inventory lines in the database
* Delete the implementations for them
* Delete the relation type between inventories and invoice candidates
* Delete the column isInvoiceCandiate from the inventory line
* Test and see if there are any leftovers afterwards.

If we want invoice candidates to be created for some of the clients, we can just deactivate the  things I described above for those who don't want it.

**Comment by metas-rc** [comment]
Note: If anybody needs it, here is the task where invoice candidates for garbage were introduced: https://github.com/metasfresh/metasfresh/issues/1604

**Comment by metas-rc** [comment]
Note: after talking with Mark, we decided to not drop the invoice candidates for inventory completely, but only deactivate the handlers for the customers who don't want them. I will not make a pull request for the branch gh3232, but I will create a new branch for only deactivating those handlers.

**Comment by metas-rc** [comment]
Please, run this script only for the customers that don't want invoice candidates for inventories.

**Comment by metas-lc** [comment]
IT
if you go in C_ILCandHandler, you notice that inventory handler and inventory line handler are inactive OK
go to receipt candidates (or wareneingang pos in swing) and create a new receipt. 
then select that HU and make a dispose
=> no invoice cands were created OK

went to cand handler and made the inventory handlers active
retested the testcase above and i still didn't get any invoice cands 
waiting for a server restart and then i'll test again
