### ISSUE TITLE
WebUI: Role permission constraints missing in Subtabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3233]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Role Permission constraints are missing in WebUI. Its possible to create permission entries for the same element multiple times. Is handled in Swing.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall only be able to set a permission once per Role and org/ client combination.

**Comment by metas-mk** [comment]
Erfordert:
https://github.com/metasfresh/metasfresh/issues/3233

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* only 1 permission per Role and org/ client combination is possible: OK

**Comment by metasnw** [comment]
@metas-dh @teosarca 
the script is failing on live instances where duplicates are already existing which is particular difficult to fix when using docker. For somebody who is not a total expert its nearly impossible to fix.

Therefore I recommend to keep regression in mind on this kind of issues in both development AND testing.
