### ISSUE TITLE
Material Tracking ID in Invoice Candidates Filter shall be search

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3234]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Field Material Tracking in Invoice Candidates is a List. This makes it unusable as Filter criteria.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Change the Fields to search in invoice Candidates.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & customer db

* Material Tracking ID in Invoice Candidates Filter shall be search: OK
* search for Material Tracking ID in Invoice Candidates Filter working correctly: OK
