### ISSUE TITLE
Create Missing M_Cost records on the fly

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3238]
### Is this a bug or feature request?
enhancement
### What is the current behavior?
If for whatever reason `M_Cost` records are missing, you might be something like this, e.g. when closing a production order:
![image](https://user-images.githubusercontent.com/1264789/34207354-66aa0a22-e58a-11e7-8adc-3f8356408d09.png)

The problem is that aparently in some demo instances, we have exactly that situation
Actually, they should be created when a new product is  created, but it seems there are caes when we have a product, but no accompanying `M_Cost`

### What is the expected or desired behavior?

the system should not throw this error at the user, but create the record on the fly

**Comment by metas-ts** [comment]
@teosarca M_Cost, C_Cost, where's the difference ;-)

**Comment by cristinamghita** [comment]
## Results of IT
### Tested on webui
* Delete from table M_Cost all records
* Open window Produktionsaufträge and choose an production order
* Close that order
* No error is shown **OK**
* $ records were created in M_Cost **OK**
