### ISSUE TITLE
WebUI: Material Receipt Candidates Fields not readonly

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3239]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, a lot of fields in Material Receipt Candidates are updateable although they are readonly in Swing UI.
#### Which are the steps to reproduce?
Open, try, see and compare.
### What is the expected or desired behavior?
Set the Fields explicitly to readonly in Field definition.

**Comment by metas-lc** [comment]
IT
compared Material Receipt Candidates swing with webui: both are the same: only the override fields and quality note are editable. The rest are readonly OK
also processed a receipt cand => all fields are readonly OK
