### ISSUE TITLE
Drop AD_Field.IsCentrallyMaintained database column

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3240]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/1752

### What is the current behavior?
we added this column temporary because we had some migration scripts which were created when that column existed.

### What is the expected or desired behavior?
drop it again, basically revert the effect of https://github.com/metasfresh/metasfresh/commit/f9bb441c4762d6c07527fbad95a614414e6393cd.

Do it after it 1-2 weeks after that commit.

**Comment by metas-lc** [comment]
nothing to test. Moving to done
