### ISSUE TITLE
WebUI: Create new Customer Accounts Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3242]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Accounting Configuration Tabs are not shown at all in webui windows.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Prepare the Accounting Configuration Tables with unique indexes. Add them as reference to given windows (should happen automatically). Check if the switch in role is needed to show the Accounting Configurations. Add new Window to WebUI menu. Add Translations for en_US.

**Comment by metas-mk** [comment]
**Customer Accounting**
C_BP_Customer_Acct
a) Primary Key generated
b) Window created
c) Menu entry

**Comment by metas-rc** [comment]
Results of IT

* OK: Customer Accounts window was added to the menu.
* OK: All the fields are translated in both German and English.
