### ISSUE TITLE
WebUI: Adjust the BOM Configuration window in Subtab for components

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3243]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the BOM Window is not showing the most important fields in Subtab Grid View for BOM Components.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Adjust the Grid View of BOM Components Subtab and show the most important fields in there.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The most important fields are also displayed in the grid version for the Component subtab.
* OK: All the fields are translated in both English and German
