### ISSUE TITLE
Material Cockpit Details modal overlay

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3245]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are no details shown in material cockpit for purchased/ ordered quantities.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add quickaction that opens a modal overlay for a selected row and shows the purchased/ ordered quantities for the given date promised.

**Comment by metas-ts** [comment]
@metas-mk the issue is integrated into master.
can you please pimp the AD_Window?
* AD_Window_ID = 540395 (Materialcockpit Detail)
* The table name is MD_Cockpit_DocumentDetail

**Comment by metas-rc** [comment]
Note: The window for this task is not in the webui;
Waiting for  https://github.com/metasfresh/metasfresh/issues/3367 to test.
Also, filtering in Material Cockpit doesn't work at all. Maybeit will be solved after this is done: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1387

=> This task's testing is on hold

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* modal overlay in Material Cockpit: opens from quick actions for a selected row: OK
* shows the purchased/ ordered quantities for the given date promised, w/ the resp. doc no. of orders and resp. qties: OK

question: document type is Standardauftrag / sales order for sales orders, but Produktanlieferung (in both de_DE & en_US) for purchase order; @metas-mk  is that wanted?

![2018-02-22 15_35_39-metasfresh](https://user-images.githubusercontent.com/18696715/36544209-2f04bcbe-17e6-11e8-9957-4a1d6a06dc6f.png)

**Comment by metas-dh** [comment]
checked w/ metas-mk: NOK, document type shall be Purchase Order / Bestellung

**Comment by metas-ts** [comment]
:cherries: to branch 2018-12

**Comment by metas-dh** [comment]
Results f IT2
tested in mf15

* document type is Purchase order / Bestellung now for purchase order: OK
