### ISSUE TITLE
WebUI: Window for Warehouse Accounting

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3256]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Accounting Parms for Warehouses are added to a Subtab of Warehouse Window. 
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
The Accounting Parms are only needed for specific users and shall be added to a single window. Take out the accounting Tab from WebUI Warehouse window and create a standalone window for that. Add to WebUI menu in Finance. Check if the document reference works properly from Warehouse Window.

**Comment by metas-rc** [comment]
Results it IT

Tested on webui

* OK: The window Warehouse Accounts was added in the menu
* OK: All the fields are translated into English
* OK: All the fields are translated into German
* OK: Our layout conventions are respected
