### ISSUE TITLE
WebUI: Window for Vendor Accounting

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3257]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for Vendor Accounting in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a Window for vendor Accounting Parms and add to WebUI in Finance. Make sure that the document reference works from Businesspartner Window.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The window Vendor Accounts was added in the menu
* OK: All the fields are translated into English
* OK: All the fields are translated into German
* OK: Our layout conventions are respected
