### ISSUE TITLE
Hide Accounts Tab from Warehouse Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3260]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Accounts Tab is shown in Warehouse Window in WebUI
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Shall not be shown in Warehouse Window in WebUI because we have an explicit Window for Warehouse Accounts in WebUI. Add the @#IsWebUI/N@=N Display Logic to Warehouse Accounts Tab.

Needs: https://github.com/metasfresh/metasfresh-webui-api/issues/769

**Comment by metas-lc** [comment]
IT
checked warehouse window in both swing and webui:
Accounts tab is shown in swing and hidden in webui OK
