### ISSUE TITLE
WebUI: Add Create Periods to Action menu in Calendar Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3267]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Action "Create Periods is not available in Window Calendar & Period.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the action to Action Menu.

**Comment by metas-lc** [comment]
IT
window calendar and year - created a new line for 2019
selected that line and went to actions - Create Periods
selected 01.01.2019 for start date
=> process finished successfully 
zoomed in to the new periods
=> periods created ok
