### ISSUE TITLE
WebUI: Add Shortcut Filter from Calendar Year to Periods Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3269]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is not Shortcut document reference from Calendar Year to Period Window.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add a Shortcut Filter for Period Window from Calendar & Year Window.

**Comment by metas-lc** [comment]
IT
go to Calendar Year window and open one to doc view
right click on 1 year from lines, select Periode => Calendar Periods Window opens with filtered year OK
