### ISSUE TITLE
Implement event log

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3271]
### Is this a bug or feature request?
FR
### What is the current behavior?
Currently, within `de.metas.event` we can post events, but there is no way to store those events, or add logs messages about an event's processing.

This is a problem with material, because
* some of the events to be processed contain delta quantities. if one can't be processed for whatever reason, we
  * don't have a reasonable way to learn about the problem
  * can't resubmit the event after having fixed the problem

### What is the expected or desired behavior?

* provide an easy way for event handler implementors to opt into event logging and  to add log entries
* allow an admin to inspect events and resubmit them

**Comment by metas-rc** [comment]
Note from Tobi, on testing: you can check out the event log window as system admin and see if it's there and seems comprehensible;

**Comment by metas-rc** [comment]
Note:  The window is called Event store

**Comment by metas-rc** [comment]
Results of IT

Tested on swing and webui.

* OK: The window is in the menu
* OK: The info in the window is comprehensible and helpfull for understanding the event.
* Open: The window does not respect our layout conventions and not all the fields are translated into English.  Task created https://github.com/metasfresh/metasfresh/issues/3309
