### ISSUE TITLE
Provide Periods for 2018

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3272]
### Is this a bug or feature request?
FR

### What is the current behavior?
periods are not in db seed for 2018 and need to be added manually via the java client
adding in webui is only possible via #3269 and #3267

#### Which are the steps to reproduce?
open window calendar and check for 2018

### What is the expected or desired behavior?
provide the year via migration script

**Comment by metasnw** [comment]
we got also documentation for this by now: http://docs.metasfresh.org/webui_collection/EN/Add_new_calendar_periods

**Comment by teosarca** [comment]
@metas-ts this task was reverted. It shall not be in release notes.

**Comment by teosarca** [comment]
update: added the initial script but, we check if the year 2018 was already created. If it was then we do nada.

**Comment by metas-ts** [comment]
cherry-picked to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in releasetest

new RC. new db: periods for 2018 are included: OK
