### ISSUE TITLE
Pharma: Copy missing product prices after import

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3279]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
Follow up https://github.com/metasfresh/metasfresh/issues/3230

**Comment by metas-lc** [comment]
IT
1. base pricelist is not set NOK
2. rename internal name in pricelist
3. when actulaize the product it tries to create a new product price NOK

**Comment by metas-lc** [comment]
IT
1. import file loader: use pharma product IFA
2. import your file
3. go to product and import pharma product window
=> 3 new products, 3 new import farmas OK
4. create a new pricelist 
5. new pricelist version (set APU as internal name) and product price
6. process the pricelist version (checkbox freigaben)
7. import your file again
=> now you have 6 import farmas OK
=> still 3 products (if you look in product price tab you 'll see your prices entries) OK
8. go to your pricelist
=> new pricelist version created, completed OK
=> basis pricelist version - the one you created at step 5 OK
9. check product prices
=> your product from last pricelist version was copied OK
=> 3 new product prices from the import are added, with the correct price (A01APU) OK
