### ISSUE TITLE
Translation of eMail Editor in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3284]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The eMail Editor in WebUI is not translated to de_DE.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add the Translations for de_DE Language/ Locale to eMail Editor.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The mail editor has translation for both English and German languages.
