### ISSUE TITLE
Workaround for truncating T_WEBUI_ViewSelection[Line]

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3286]
### Is this a bug or feature request?
FR

### What is the current behavior?
see https://github.com/metasfresh/metasfresh-webui-api/issues/737

### What is the expected or desired behavior?
once a day we need to truncate T_WEBUI_ViewSelection[Line] to limit data growth
truncating takes 1ms and causes no downtime

**Comment by metas-rc** [comment]
Moving to done. Tobi told me that it is already used and works well.
