### ISSUE TITLE
Shipper Transportation: Shipper Location: change validation rule logic

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3288]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/768
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
![image](https://user-images.githubusercontent.com/1244701/34674349-4094eaf6-f48e-11e7-9296-3c2e9cb10d6a.png)

Atm, that field displays all BP locations which have a "C_BP_Relation.IsFetchedFrom=Y" relation with the bpartner selected in the Shipper BP field (the one above).

Technically, the validation rule code is/was:
```sql
EXISTS(
	SELECT 0 FROM C_BP_Relation bpr
	WHERE bpr.C_BPartnerRelation_Location_ID = C_BPartner_Location.C_BPartner_Location_ID
	AND bpr.C_BPartner_ID = @Shipper_BPartner_ID@ AND bpr.isactive = 'Y' AND bpr.IsFetchedFrom = 'Y'
) AND C_BPartner_Location.IsActive = 'Y'
```

#### Which are the steps to reproduce?
open and see, e.g. https://w101.metasfresh.com:8443/window/540020/1000000

### What is the expected or desired behavior?
Shipper Location shall show all locations for all warehouses which are on selected Organization, which are active and which are flagged as IsPickingWarehouse=Y

**Comment by metas-rc** [comment]
Note ( because I didn't understand from the begining, and I had to check)
* The warehouse only supports C_BPartner_Locations that are of the org C_BParnter.


Results of IT

Tested on webui

* OK: The Transportation order now supports any active C_BPartner_Location from a warehouse that is flagged as Picking.
