### ISSUE TITLE
WebUI: New Window for Document Details in Material Cockpit

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3289]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the detailed Window Layout is missing for the document details of Material Cockpit.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create the detailed Layout for that.

**Comment by metas-mk** [comment]
Table Name is md_cockpit_documentdetails

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

Note: The window name is Material Cockpit Details

* OK: The window respects out layout conventions
* OK: The fields are translated in both German and English.


NOK: The window is not added in the menu. Please check https://mf15cloudit/window/540395/1000000.

**Comment by metas-ts** [comment]
@metas-mk can you pls add the window to the webui menu ?
or close this issue if it shouldn't be in the menu?

**Comment by metas-mk** [comment]
Window is not needed in WebUI menu. Shall only be called from Material Cockpit.
