### ISSUE TITLE
Search Icon disappears when switching Main-Subtab in Contract Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3291]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The search Icon disappears when switching Main-Subtab in Contract Window
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall remain visible.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing


* Note: The modifications were not in the Contract window, but in Contract Period window. But I am pretty sure the wrong name is in the title of this task and not in the implementation.

* OK: The Contract Period window has the search (filter) available in webui.
* OK: The filters work well
* OK: The Contract Period window has the search available in swing, too.
