### ISSUE TITLE
Webui: Add Translation Messages for Daterangepicker

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3293]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Range Options are not localized in Daterangepicker in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Add localized messages.

**Comment by metas-rc** [comment]
Result of IT

Tested on webui

* OK: The date range picker has all its fields translated in both German and English
