### ISSUE TITLE
WebUI: New Window for GO! Delivery Orders

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3303]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window for GO! Delivery Orders in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Window for GO! Delivery Orders and add to WebUI menu.

**Comment by metas-rc** [comment]
Note: Unassigned myself because I talked with Teo and he said this should be tested together with the whole GO! funcationality, probably by Torby.

**Comment by metas-mk** [comment]
This issue is about the window, layout, and translations in webui. these requirements can also be done w/o any other functionality. tested. done. closing.
