### ISSUE TITLE
Copy C_DocType.Description/DescriptionBottom to Order and Invoice

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3304]
### What is the expected or desired behavior?
The C_DocType.Description and DescriptionBottom (if set) shall be copied to C_Order and to C_Invoice.
They shall be copied only if the C_DocType.IsCopyDescriptionToDoc flag is checked.
The flag shall be visible only for sales/purchase order/invoice base document types. For other base doc types shall be hidden because it's not supported yet.

This shall happen:
* when user is changing the doc type from window (shall update instantly via callouts)
* when the order or invoice is generated via any process

Jasper report:
* the order jasper report shall take the description only from C_Order and never check C_DocType.

**Comment by teosarca** [comment]
note to IT:
* regression: sales to invoice process... but considering the amount of changes, e2e will be nice

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing
* Open: The description is not calculated. If I copy with details an order without description, it is not set even if the doctype now has a description.

**Comment by metas-rc** [comment]
* NOK: The field description is not displayed in the webui version for the Sales Order window. Followup created: https://github.com/metasfresh/metasfresh/issues/3331

**Comment by metas-rc** [comment]
* OK: The flag is not displayed for doc types that are not covered by this task.

1) Sales Order
* Set a Description and Document Note for docType Sales Order
* Create a Sales Order
* => OK: The Description and Document Note were both set in the order ( checked in DB)

2) Purchase Order
* Set a Description and Document Note for docType Purchase Order
* Create a Purchase Order
* => OK: The Description and Document Note were both set in the order ( checked in DB)

3) Sales Invoice manual
* Set a Description and Document Note for docType Sales Invoice
* Create a manual sales invoice
* => NOK: Neither the  Description or Document Note were set in the invoice

4) Sales Invoice from Sales Order
* Create shipment from the Sales Order above
* Go to the linked invoice candidates
* Create an invoice out of them
* => NOK: The  invoice has both Description and Document Note empty

5) Manual purchase invoice
* Set a Description and Document Note for docType Purchase Invoice
* Create a manual purchase invoice
* => NOK: Neither the  Description or Document Note were set in the invoice.

6) Purchase invoice out of Purchase Order
* Create Receipt from the Purchase Order above
* Go to the linked invoice candidates
* Create an invoice out of them
* => NOK: The  invoice has both Description and Document Note empty.

**Comment by metas-rc** [comment]
Result of IT 2

Tested on webui + db

1) Still OK
2) Still OK
3) The manual Sales invoice takes the description and document note from the docType Sales Invoice
4) The sales invoice from order takes the description and document note from the docType Sales Invoice
5) The manual purchase invoice takes the description and document note from the docType Purchase Invoice
6) The purchase invoice from order takes the description and document note from the docType Purchase Invoice

**Comment by metas-ts** [comment]
Cherry-picked the following commits to `release`
* https://github.com/metasfresh/metasfresh/commit/7ecbe6c3562e30afa1ae11d27767ffcc3791d590
* https://github.com/metasfresh/metasfresh/commit/438c96b02dae07575aeb1c7506a7abb132be57f8
* https://github.com/metasfresh/metasfresh/commit/2b840dadc465f4d739718c2f0d7c0f9b8c68aef6
