### ISSUE TITLE
Order/Invoice jasper: always use the Description/DescriptionBottom from document and don't check C_DocType's description

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3307]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3304

### What is the current behavior?
the Jasper reports are using C_DocType.Description and DocumentNote.

### What is the expected or desired behavior?
The Jasper reports shall always use
* C_Order: Description, DescriptionBottom
* C_Invoice: Description, DescriptionBottom

They shall never check and display the ones from C_DocType.

**Comment by metas-lc** [comment]
searched for description and documentnote from doctype:
jasper: sales and purchase order, report_details_footer
used: dt.documentnote

sql: Docs_Invoice_Details_Footer: documentnote
in sales and purchase invoice

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Jasper reports use
* C_Order: Description& DescriptionBottom:
   * if set, those are used, not Description & DescriptionBottom from C_DocType: OK (both sales & purchase order)
   * if not set, Description & DescriptionBottom from C_DocType are used, if the resp. checkbox "Copy Description to document" in C_DocType is set: OK (not used if checkbox=N)
* C_Invoice: Description & DescriptionBottom:
   * if set, those are used, not Description & DescriptionBottom from C_DocType: OK (both sales & purchase invoice)
  * if not set, Description & DescriptionBottom from C_DocType are used, if the resp. checkbox "Copy Description to document" in C_DocType is set: OK (not used if checkbox=N)
* translations from C_DocType_Trl  are not used, if the bpartner has that resp. language set: NOK??
