### ISSUE TITLE
Webui Window Design: Improve window Table and Column

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3312]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* The window Table and Column does not respect our layout conventions. Also, some fields are not translated into English and some are not translated in German
#### Which are the steps to reproduce?
* Open as Sys Admin and see.
### What is the expected or desired behavior?
* This window shall respect or layout conventions ( main view split in 2 columns, cornerstones, white background for included tabs, etc)
* All the fields shall be translated in both German and English.

**Comment by metas-mk** [comment]
ToDo:

- [ ] Main Window Layout
- [ ] Subtabs Level 1 Layout
- [ ] Separate translation windows
- [ ] Separate Level 2 Subtab Windows

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The window respects our layout conventions and cornerstones
* OK: The included tabs have a white background and respect our layout conventions
