### ISSUE TITLE
Webui Window Design: Improve window Rechnungskandidaten - Handler

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3323]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Please, translate the name of this window into English
* The window  Rechnungskandidaten - Handler does not respect our layout conventions. Also, some fields are not translated into English and others are not translated into German.
#### Which are the steps to reproduce?
* Open as Sys Admin and see.
### What is the expected or desired behavior?
* This window shall respect or layout conventions ( main view split in 2 columns, cornerstones, etc)
* All the fields shall be translated in both German and English.

**Comment by metas-lc** [comment]
IT
1. open Rechnungskandidaten Handler window (540124)
=> fields are trl in both de and en OK
=> window name is trl in EN, de OK
=> This window respects our layout conventions: 
TL: mandatory, important. TR: flags. BR: org, client OK
grid view: shouldn't be ordered by Name asc?
