### ISSUE TITLE
Webui Window Design: Translate all in window Event store

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3329]
* Followup for https://github.com/metasfresh/metasfresh/issues/3309
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Some fields are not translated into English

Here, i am logged in with English: 

![image](https://user-images.githubusercontent.com/16001442/34940435-3363dd32-f9f8-11e7-82fd-7c73402c48bb.png)

Also, in the included tab: 
![image](https://user-images.githubusercontent.com/16001442/34940451-4697c468-f9f8-11e7-9b96-9894cf2e899d.png)

Here I logged in with German: 

![image](https://user-images.githubusercontent.com/16001442/34940550-975e64f6-f9f8-11e7-824a-ad4a7859ccc8.png)

Included tab for German: 

![image](https://user-images.githubusercontent.com/16001442/34940558-a8f143c8-f9f8-11e7-85ae-0a0824bb143b.png)

#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, translate all into English and German.

**Comment by metas-rc** [comment]
Please, add translations for both English and German for all fields.

**Comment by metas-mk** [comment]
All fields mentioned above are translated on w101. Seems as if migration script is missing. Recreating.

**Comment by metas-lc** [comment]
IT
everything is translated to German and English OK
