### ISSUE TITLE
Harmonize description field length between doctype and c_order / c_invoice

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3338]
### Is this a bug or feature request?
FR

### What is the current behavior?
as an effect of #3304 ...

- field c_doctype.description is type string and only 255 chars but description in c_order is 1024 chars
- c_invoice.description is text long which needs to be changed to text 1024 or otherwise invoice with long c_doctype.description wont work (tested it. as a result wp throws exception)

#### Which are the steps to reproduce?
go table and columns for c_doctype.description and check 

### What is the expected or desired behavior?
extend description field length and type to be text, 1024
Check the same for descriptionbottom

**Comment by metas-rc** [comment]
Results of IT

 Checked BD, webui, swing
* OK: Description is Text and has length 1024 in Doctype, Order and Invoice tables
* OK: Description Bottom is Text and has length 1024 in Order and Invoice tables
* NOK: In C_DocType, the DocumentNote column that is inherited bu the DescriptionBottom columns in order and invoice has length 2000 => if I insert a 2000 characters text in the doctype's documentNote, only the first 102 chars will be set in the order or invoice, the rest is lost.

**Comment by metasnw** [comment]
@metas-rc what is the column size of c_doctype.documentnote ?

**Comment by metas-rc** [comment]
@metasnw: It is 2000

**Comment by metasnw** [comment]
@metas-rc then I would suggest to make it 2048 in c_doctype.documentnote, c_oder.descriptionbottom, m_inout.descriptionbottom, c_invoice.descriptionbottom

**Comment by metas-rc** [comment]
Note: I also made the FieldLength od the Column DescriptionBottom from C_Invoice_Candidate 2048.

**Comment by metas-ts** [comment]
CPed the SQL fix into `release`

**Comment by metas-lc** [comment]
IT
0. checked doctype: description is 1024 and documentnote is 2048 
1. set Description and document note in doctype for sales order 
2. created and completed a new sales order and checked the database
=> description was set like doctype's description and descriptionbottom like document note
=> description is 1024 and description bottom is 2048 OK

3. set Description and document note in doctype for sales invoice
4. created and completed a new sales invoice and checked the database
=> description was set like doctype's description and descriptionbottom like document note
=> description is 1024 and description bottom is 2048 OK

5. checked inout but "copy description to document" is not set. Anyways, i looked in the database and description is 1024 and description bottom is 2048 OK
