### ISSUE TITLE
Field "Belegart" is included twice in payment window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3339]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Field "Belegart" (document type) is included twice in payment window, only 1 can be set by user
#### Which are the steps to reproduce?
Open and see
### What is the expected or desired behavior?
Remove the field Doctype from primary group.

copied from https://github.com/metasfresh/metasfresh-webui-api/issues/609

**Comment by metas-lc** [comment]
IT
belegart appears only once, on top right OK
