### ISSUE TITLE
Create purchase order from PMM_PurchaseCandidate not working in Swing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3345]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Creating a purchase order from PMM_PurchaseCandidate is not working in Swing (during customer e2e)
#### Which are the steps to reproduce?
1. Open PMM_PurchaseCandidate in Swing
2. Select PMM_PurchaseCandidates you want to create a purchase order from
3. Run process "Bestellen" on the right side
=> PMM_PurchaseCandidate is marked as being processed, but no order is created, NOK
=> console:
>2018-01-17 14:36:12.974  WARN 5431 --- [WT-EventQueue-0] d.m.process.ProcessPreconditionChecker   : Marked checker as not applicable: de.metas.process.ProcessPreconditionChecker@3708700 because cannot load class de.metas.ui.web.procurement.process.PMM_Purchase_Candidate_CreatePurchaseOrder
java.lang.ClassNotFoundException: de.metas.ui.web.procurement.process.PMM_Purchase_Candidate_CreatePurchaseOrder
### What is the expected or desired behavior?
Purchase order shall be created, with the correct process.

**Comment by teosarca** [comment]
note to dev: debug/BP in de.metas.procurement.base.order.callout.PMM_CreatePurchaseOrders_Action.execute0()

**Comment by metas-dh** [comment]
working fine now, purchase order was created correctly in last customer e2e, closing this issue.
