### ISSUE TITLE
Drop M_Product_Costing 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3347]
Drop M_Product_Costing together with window/tab, processes, code etc.
That is legacy for years now.

### Note to IT
Regression:
* create a new product
* add it to price list
* purchase order, invoice, material receipt => make sure all docs were posted (accounting)
* sales order, invoice, material shipment => make sure all docs were posted (accounting)

**Comment by metas-lc** [comment]
IT
tested in both webui and swing
=> all posting went fine OK
note:
i had to press the posting buttons to have them posted, but that's ok. 
i checked the postings from webui on swing
