### ISSUE TITLE
Add BPartner to User Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3349]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the User Window does not show the Info to which Businesspartner it belongs. This is normally set and shown when the user is defined via Businesspartner>>User Tab.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Business Partner Field to User Window, show in Grid View and allow the editing of it. The Field shall be an autocomplete widget. Show in Filter too.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The Business Partner is displayed in the window User, both in single and grid view
* OK: The Business Partner can be set in an older or new entry of User.
* OK: Business Partner field is with autocomplete.
* NOK: The Business Partner is not showed in filter.
* NOK: One the BPartner was set, it cannot be changed or deleted.

**Comment by metas-mk** [comment]
> NOK: The Business Partner is not shown in filter.
> NOK: Once the BPartner was set, it cannot be changed or deleted.

Both cases are OK and wanted until now.
