### ISSUE TITLE
Invoicing taking wrong Documenttype for Producer Invoice

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#335]
Invoicing taking wrong Documenttype for Producer Invoice

**Comment by metas-ts** [comment]
OK, i understand the case now:
the user set `C_BPartner.Fresh_ProduzentenAbrechnung='Y'` and 20-30 minutes later did an invoicing with *preexisting* ICs.
If `C_BPartner.Fresh_ProduzentenAbrechnung` is changed, then we do **not** automatically update existing ICs. so until the invoicing took place, the ICs still had the "gneral" (i.e. not "Produzentenabrechnung")
* However, after the invoicing took place, the system did not only update the ICs QtyInvoiced etc, but also its *C_DocTypeInvoice_ID`to Produzendenabrechnung.

when i later reversed and recreate the invoice, it was all fine

**Comment by metas-ts** [comment]
Note that i made a sxmall fix for this case.
To test: 
* have an IC with no particula doctype
* set its bpartner to PRoduzentenabrechnung=Y
* invoice (without having made any other change, so the IC shall still have no doctype)

verify that that when the invoice was created and the IC was updated, the ICs doctype is still not produzentenabrechnung (neither is the invoices doctype)
