### ISSUE TITLE
Implement MSV3 availability query

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3353]
### Is this a bug or feature request?
FR

**Comment by metas-mk** [comment]
Requires https://github.com/metasfresh/metasfresh/issues/3387

**Comment by metas-rc** [comment]
Note: to be tested after https://github.com/metasfresh/metasfresh-webui-frontend/issues/1528 is done

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15, w/ #3437 

* metasfresh/metasfresh-webui-frontend#1528 is done
* MSV3 availability was shown in modal window for SO2PO: OK
