### ISSUE TITLE
Add option to automatically credit open invoice for terminated contract / subscription

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3355]
### What is the current behavior?
http://docs.metasfresh.org/webui_collection/EN/Contract_termination.html

### What is the expected or desired behavior?

- [ ] new checkbox set to Y telling "automatically credit any existing invoice for this contract"
- [ ] if an invoice with an open amount (complete or partially) exists create a credit memo for the invoice and allocate so the invoice is paid

**Comment by cristinamghita** [comment]
## Dev test
### Simple contract
* Create a sales order with flatrate conditions
* Invoice the IC for that
* Go to contract window and cancel the contract, choosing to credit open invoices
     ![image](https://user-images.githubusercontent.com/15378036/35554451-6179893a-05a4-11e8-9c52-ab24c120df42.png)
* Result **OK**
    *  The contract was cancelled **OK**
    * Invoice was credited **OK**
### Contract extended
* Create a sales order with flatrate conditions
* Extend that contract
* Invoice the IC for both contracts
* Go to contract window and cancel the initial contract, choosing to credit open invoices
     ![image](https://user-images.githubusercontent.com/15378036/35554451-6179893a-05a4-11e8-9c52-ab24c120df42.png)
* Result **OK**
    *  Both contracts were cancelled **OK**
    * Both invoices were credited **OK**

**Comment by metas-ts** [comment]
CPed into `release`

**Comment by metas-lc** [comment]
IT

see steps: 9, 22

. invoice - cancel contract - credit memo OK
1. create new sales order, add product and a flatrate condition for that bpartner and product
2. complete the order
=> new contract was created OK
=> status running (laufend) OK
3. create invoice
4. go to contract and cancel it (kündigen) + credit open invoices
=> contract status is now Quit (Gekündigt) OK
=> new credit memo was created for my invoice. Invoice is paid OK

. extend contract - invoices - cancel contracts - credit memos NOK?
5. create a new sales order,  add product and same flatrate condition from step 1
6. complete the order
=> new contract was created OK
=> status running (laufend) OK
7. extended contract 
=> contract extended with a month in my case
=> new contract created, new IC created
8. go to IC window and invoice both ICs (one by one)
=> 2 new invoices created
9. go to contract window and cancel the initial contract, choosing to credit open invoices
=> Error:
Für den Abo-Wechsel von 'TestAbo lc' zu 'Qu' zum Datum Mar 20, 2018 sind keine Wechsel-Konditionen hinterlegt. 
OK???
10. go to extended contract and cancel it, choosing to credit open invoices
=> both contracts are canceled OK
=> 2 new credit invoices are created, all 4 invoices are paid OK

. extend contract - invoices - pay 1 invoice/ cancel contracts - credit memos OK
11. create a new sales order,  add product and same flatrate condition from step 1
12. complete the order
=> new contract was created OK
=> status running (laufend) OK
13. extended contract 
=> contract extended with a month in my case
=> new contract created, new IC created
14. go to IC window and invoice both ICs (one by one)
=> 2 new invoices created
15. make a payment for one invoice, complete it
=> that invoice is now paid
16. go to extended contract and cancel it, choosing to credit open invoices
=> both contracts are canceled OK
=> 1 new credit invoice is created, all invoices are paid OK

. invoice - pay invoice - cancel contract OK
17. create/complete a new sales order,  add product and same flatrate condition from step 1
=> new contract was created OK
=> status running (laufend) OK
18. create invoice, pay it 
19. cancel the contract
=> contract is canceled OK
=> no credit invoice was created OK

. invoice - partial pay invoice - cancel contract - credit memo NOK
20. create/complete a new sales order,  add product and same flatrate condition from step 1
=> new contract was created OK
=> status running (laufend) OK
21. create invoice, pay the invoice partially
=> invoice is not paid yet OK
22. cancel the contract
=> contract is canceled OK
=> credit memo was not created, invoice not paid NOK

. Regression test
23. Create a sales order with flatrate conditions
24. create invoice
25. Go to contract window and cancel the contract, choosing NOT to credit open invoices
=>The contract was cancelled OK
=> Invoice wasn't created/paid OK
