### ISSUE TITLE
User Window unlock Account Action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3359]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the unlock account Button is shown in Window User in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Remove the Button and add the Process as an entry in the windows Action menu.

**Comment by metas-rc** [comment]
Resulta of IT

Tested on webui

* OK: The unlock account button is not displayed in the User window, in webui
* OK: The Unlock Account process is present among the actions for User.
