### ISSUE TITLE
Webui Window: Create window for ReferenceNo and Reference Type

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3366]
### Is this a bug or feature request?
FR
### What is the current behavior?
 ![image](https://user-images.githubusercontent.com/15378036/35161931-5f823d46-fd4a-11e7-860c-ea2af085b76e.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui, checked on swing

* NOK: The included tab of Reference Number Type cannot be opened because its  table doesn't have an id. Followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1526
