### ISSUE TITLE
Webui Window Design: Window for Material Cockpit Details

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3367]
### Is this a bug or feature request?
 *FR
* Followup for https://github.com/metasfresh/metasfresh/issues/3245
### What is the current behavior?
* Currently the implementation from #3245 cannot pe tested.
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
```
 please pimp the AD_Window:

AD_Window_ID = 540395 (Materialcockpit Detail)
The table name is MD_Cockpit_DocumentDetail
```

**Comment by metas-mk** [comment]
Done with https://github.com/metasfresh/metasfresh/issues/3245.
