### ISSUE TITLE
WEBUI: Create webui window for Import File Loader Window

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3373]
### Is this a bug or feature request?
FR
### What is the current behavior?
The window exists only in swing
![image](https://user-images.githubusercontent.com/15378036/35266588-6151af00-002c-11e8-84d7-768c53a3f0bb.png)
### What is the expected or desired behavior?
The window should exist in webui.

**Comment by teosarca** [comment]
this task shall be on metasfresh-webui-api.

**Comment by teosarca** [comment]
implemented by https://github.com/metasfresh/metasfresh-webui-api/issues/879
