### ISSUE TITLE
Quantity picked in Shipment Schedules doesn't update

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3375]
### Is this a bug or feature request?
bug
### What is the current behavior?
Quantity picked in Shipment Schedules doesn't update, so you can create lots of open inouts for the same Shipment Schedule 
#### Which are the steps to reproduce?
swing:
1. create and complete a sales order, qty e.g. 40
2. go to shipment schedules and create inout from gear "generate shipments" (don't select any checkbox)
=> inout created, uncompleted OK
=> shipment schedules still have qty to deliver set to 40 (green) NOK
=> qty picked is still 0 NOK
(because of this you can create as many inouts as you want, for the same qty)
### What is the expected or desired behavior?
qty picked shall be updated (to 40 in this case), then qty to deliver will be updated by default to 0

**Comment by metas-dh** [comment]
had a related case during customer e2e:
* created shipment from gear (not completed)
* changed the qty, to get a partial shipment, and completed the shipment
=> Qty Picked afterwards = (Qty Ordered - Qty Delivered), although there was nothing picked and no new shipment was created

**Comment by metas-dh** [comment]
see IT for #3822.
