### ISSUE TITLE
Enlarge column AD_EntityType.EntityType

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3385]
### Is this a bug or feature request?
FR

Set from 40 to 512

Note: i think it's not a great idea to have a 512 chars entitytype..but i didn't want to enter the gray area where the new size might or might not be sufficient

**Comment by metas-rc** [comment]
Results of IT

* Note: there are errors when opening Entity  Type in webui until https://github.com/metasfresh/metasfresh/issues/3357 is done.

* Nevertheless, I was able to create an EntityType entry.
* OK: I was able to set in the field EntityType a text of 512 characters
* OK: The value saved with no error
* OK: The value was registered correctly in the database
