### ISSUE TITLE
Issued HUs retain I status after PP_Order unclose

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3386]
### Is this a bug or feature request?
Bug

### What is the current behavior?

See https://github.com/metasfresh/metasfresh/issues/3225#issuecomment-355912433

### What is the expected or desired behavior?

HUs should be active

**Comment by metas-ts** [comment]
cherry-picked to `2018-06`

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* issued HUs: status Active & can be issued again, after PP_Order unclose: OK
* issued HUs: status Active & can be issued again, after Cost Collector reversal: OK
