### ISSUE TITLE
WebUI New Window for MSV3 Config

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3387]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the MSV3 Configuration per Vendor BPartner in WebUI.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a window for MSV3 Config and add to WebUI Menu in Procurement/ Purchase Settings.

**Comment by metas-rc** [comment]
Modifications did not get to mf15. I will test after they are merged there too

**Comment by metas-rc** [comment]
* It got fixed after the last rollout


Results of IT"

Tested on webui


* OK:  The window MSV3 Lieferanten Konfiguration was added in the menu
* OK: The layout conventions and cornerstones are respected
* OK: The window is functional.
* NOK: The menu entry for the window doesn't have an ENglish Translation. Followup created: https://github.com/metasfresh/metasfresh/issues/3398
