### ISSUE TITLE
Performance issue related to zooming table record references

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3389]
### Is this a bug or feature request?
FR
### What is the current behavior?

For large DBs (e.g. with aprox 100M `AD_ChangeLog` records), the Zoom-To feature can be very slow.

**Comment by metas-rc** [comment]
Resulta of IT

Tested on webui

OK: The zoom to change log works correctly.
Talked with metas-ts and decided to let this fix in even if I can't test the performance for 100M of entries because I don't have them in any testing db. It will be properly tested directly on our customer's database.
