### ISSUE TITLE
Migration - record apply-duration for each script

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3391]
### Is this a bug or feature request?
FR

### What is the current behavior?

Currently, when running migration, the time which the individual script took to be applied on the DB are logged, but not really recorded.

### What is the expected or desired behavior?

I would like to do
```sql
SELECT sum(durationMillis) FROM AD_MigrationScript WHERE Created>'some-past-date'
```

this way i can look at the UAT server  and estimate how long the rollout onto the production server might take.

**Comment by metas-ts** [comment]
how to IT: 
after the rollout, you can do 
```SQL
select * from ad_migrationscript where durationmillis is not null;
```
there should be a durationmillis  column with values

**Comment by metas-ts** [comment]
cherry-picked to `2018-06`

**Comment by metas-rc** [comment]
Results of IT

Tested in db

* OK : The select query above has results; the column was added and has various values.

**Comment by teosarca** [comment]
just saw this task, nice! :)
