### ISSUE TITLE
Sales inout Jasper: HU name taken from line 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3394]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you manually set an HU in inoutline, the jasper will take the one from hu assignments. If the hu is manual, we shall always take the one from the line
#### Which are the steps to reproduce?
make inout using picking, set a line to be manual package, change the HU, print jasper
=> hu is still the one from picking
### What is the expected or desired behavior?
hu shall be taken from the line

**Comment by metas-rc** [comment]
Results of IT


Tested on swing and webuil

* OK: If the ManualPackingMaterial flag is on false in the inouot line, the TU number and the TU from the HUAssignment are taken into the report
* OK: If the flag is on true, the jasper contains the TU number and the TU that are in the inout line.

**Comment by metas-rc** [comment]
Results of IT


 Tested on swing + webui

* OK: All the client reports now contain the TU name
