### ISSUE TITLE
Set Selector in M_Product after Product Data Import

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3406]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Default Distribution Schema Selector for a product is not set after Product Data import. 
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
During Product import, find out which default Distribution Schema Selector fits for the product and add to the product data. This Selector can be a reference list.

**Comment by metas-lc** [comment]
IT
1. created 2 product planning schema
2. added product planning schema selector in an import format
3. imported a file with 3 products, all had that product schema set
=> 3 new products created OK
4. went to product planning data and checked all products
=> the ones i imported had 2 product data OK
