### ISSUE TITLE
New Businesspartner Window for Pharma vertical

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3407]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are Businesspartner Windows in metasfresh for general usage and for B2B companies. A Window for Pharma specific requirements does not exist.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Businesspartner Window. Add to Pharma entity. Add new Pharma specific Fields to the main View. Rearrange the Fields.

**Comment by metas-lc** [comment]
IT
new window: Produkt Pharma
1. usual window
TL mandatory, important OK
TR important flags OK
BR org, client OK
2. grid view: 
order by name asc OK
3. included tabs: white background: NOK (see lieferant)
credit limit tab is missing
4. translations: 
de_DE OK
en_EN NOK: see some fields (check advanced edit as well), included tabs

NOKs
1. credit limit tab is missing but it will be added in this task https://github.com/metasfresh/metasfresh/issues/3414
2. included tab: Lieferant - needs white background
3. translations: included tabs and some fields (e.g. Umsatzsteuer-ID, Autom. Referenz-Wert in Auftrag)
follow-up https://github.com/metasfresh/metasfresh/issues/3479
