### ISSUE TITLE
New Product Window for Pharma vertical

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3408]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we only have a general Product Window in metasfresh.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create an additional Product Window that covers the requirements of Pharma vertical better.

**Comment by metas-lc** [comment]
IT
new window: Produkt Pharma
1. usual window
TL mandatory, important OK
TR important flags OK
BR org, client OK
2. grid view: 
order by name asc OK
3. included tabs: white background: NOK (see geschaftspartner)
4. translations: 
de_DE OK
en_EN NOK: see window name, advanced edit and included tabs

NOKs: 
we need English translations (window name, tabs)
subtabs (e.g. geschaftspartner) don't have white background
subtab UOM conversion shows all conversions (from all products) - shall show the conversions for the current product
subtab cu-tu zuordnung shows all hu pi item products (from all products) - shall show the hupis for the current product

follow-up https://github.com/metasfresh/metasfresh/issues/3478
