### ISSUE TITLE
Save termination date explicitly

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3416]
### Is this a bug or feature request?
FR

### What is the current behavior?
enddate is set according to termination but other than changelog or ad_pinstance you can not find out when the termination was entered

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/Contract_termination.html

### What is the expected or desired behavior?
add a field terminationdate which contains the date when the termination was entered by the user

**Comment by cristinamghita** [comment]
![image](https://user-images.githubusercontent.com/15378036/35633255-6f766d56-06b1-11e8-8da2-e4c4ce119193.png)

**Comment by metas-ts** [comment]
hi @cristinamghita @metasnw 
i integrated now because i understand it should be in release, *but*
i suggest to rename the field. when i looked at the code, i thought it was about the date from which onwards the contract is no more..and i was a bit irritated..
so maybe call it "TerminationRecordedDate" (Termination recorded = Kündigung erfasst) ?

**Comment by metasnw** [comment]
hi @metas-ts 
got your point. if you take into consideration that we also have a masterenddate indicating the end of the contract then it might be fine.
if we want to rename I would go with TerminationDateEntered (like qtyentered) and later we could have TemrinationDateActual or effective if we wanted to store that as well in another field

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* termination date is set correctly: OK
* the field is still called Termination Date, @metasnw is that ok? or shall we rename it (and add de_DE trl)?

**Comment by metasnw** [comment]
@metas-dh Termination Date is fine in EN. for DE it should be "Kündigungsdatum"

**Comment by metas-dh** [comment]
missing trls shall be added in #3709.
