### ISSUE TITLE
Support new VAT rate of 7.7% in Switzerland from 01.01.2018

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3417]
### Is this a bug or feature request?
FR

### What is the current behavior?
new VAT valid in CH starting from 01.01.2018
its easy to configure it manually but I think we should add it to metasfresh in master for convenience

#### Which are the steps to reproduce?
open window tax and search for country switzerland and taxrate 7.7 => not there

### What is the expected or desired behavior?
add new tax rates valid from 01.01.2018

**Comment by metas-lc** [comment]
IT
we have 2 new 7.7 taxes for CH OK
