### ISSUE TITLE
Material Cockpit Document Details Doctype, DocNo wrong/ missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3422]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Doctype and DocumentNo in material Cockpit Document details is wrong/ missing.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Please Fix.

![image](https://user-images.githubusercontent.com/13365687/35624578-b26dff38-068f-11e8-860d-7b6d26adfbb1.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in weekly e2e

Material Cockpit Document Details
* Doc No displayed & correct:  OK
* Doctype displayed & correct:  OK for sales order, but for purchase order the doctype is NOK, see https://github.com/metasfresh/metasfresh/issues/3245#issuecomment-369507461: will be fixed there
