### ISSUE TITLE
Dunning Level is not set in invoice after generating dunning doc

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3426]
### Is this a bug or feature request?
bug

### What is the current behavior?
if you create a dunning doc for an invoice the field c_dunning_level_id remains null

#### Which are the steps to reproduce?
1. follow http://docs.metasfresh.org/webui_collection/EN/Dunning_Run.html
1. open the invoice and check dunning level
1. NOK: its null

### What is the expected or desired behavior?
the field should be filled so people can see the dunning level right on the invoice
if not filled the sql to find is quite heavy:
http://docs.metasfresh.org/sql_collection/c_dunning.html

**Comment by cristinamghita** [comment]
Fixed. See :
![image](https://user-images.githubusercontent.com/15378036/35635837-087c957e-06b8-11e8-9799-fb79435942de.png)

**Comment by metas-ts** [comment]
cherry-picked to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* dunning level set in invoice after generating dunning doc (WebUI: in Advanced Edit): OK
* relation dunning - dunning candidate not working in webui (in Swing there is an extra tab for that)

**Comment by cristinamghita** [comment]
SQL to update old data:
```
update C_Invoice
set C_DunningLevel_ID=cand.C_DunningLevel_ID
FROM (SELECT C_DunningLevel_ID, record_id, AD_Table_ID FROM C_Dunning_Candidate ) AS cand
WHERE C_Invoice.C_Invoice_ID = cand.record_id and cand.AD_Table_ID=318
AND C_Invoice.C_DunningLevel_ID is null;```
