### ISSUE TITLE
Switch off Daterange in Preparation date Filer temporarily

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3428]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Date Range Filter as Range Filter has an initial Range set when opening the filter. This makes it impossible to search without the Date Range Filter set properly.
#### Which are the steps to reproduce?
- Open Manufacturing Order window /window/53009
- Open "Filter"
- Check Preparation Date
### What is the expected or desired behavior?
Switch off temporarily as long as Daterange Initial Date is not fixed.
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1546

**Comment by metas-lc** [comment]
IT
checked preparation date in manufacturing window => it's simple date (not daterange), empty OK
you can filter for Preparation date OK
