### ISSUE TITLE
Best before Date evaluating process/ action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3430]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have best before dates in Handling Unit Attributes. Also a Best before Flag on that level. We don't have a function that checks the dates and sets the flag automatically.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create such a functionality and integrate into a nightly schedule.  ~~The functionality shall take parms that decide under which circumstanced the flag shall be set.~~

**Comment by teosarca** [comment]
Update:
* the process is scheduled to run each night on 2AM
* the GuaranteeDaysMin is configurable on product and product category level. You will be able to edit it after https://github.com/metasfresh/metasfresh/issues/3540

**Comment by metas-lc** [comment]
IT
1. go to product, select one (A) and set min guarantee days: 5
2. go to product category of that product and set min guarantee days: 1
3. go to another product (B), with different category and set to that category min guarantee days: 2. Leave that product how it is (0)
4. create one purchase order with both products
5. create 3 inouts for each product, set best before date as follows:
(note today is 28.02)
5.1 product A: best before date 03.03 (+3 days from today)
5.2 product A: best before date 08.03 (+8 days from today)
5.3 product A: best before date empty
5.4 product B: best before date 01.03 (+1 days from today)
5.5 product B: best before date 08.03 (+8 days from today)
5.6 product B: best before date empty

6. go to HUs and check HU_Expired attribute
=> search key empty

7. run update HU's expired status
=> Process Aktualisiert #4
8. go to HUs and check HU_Expired attribute
5.1 => search key expired
5.2 => search key empty
5.3 => search key empty
5.4 => search key expired
5.5 => search key empty
5.6 => search key empty

OK
recap: 
min guarantee days is taken from product fallback to product category
expired is calculated like bestbeforedate-min guarantee days
HU_Expired attribute has search key expired or empty
there is a scheduler for this process every night at 2
