### ISSUE TITLE
MSV3 handle deviating response from remote MSV3 server

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3437]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
:cherries: to `release`

**Comment by teosarca** [comment]
note to IT: pls also check https://github.com/metasfresh/metasfresh/issues/3525

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

**SetUp:**
* start msv3-server
* make sure msv3 config is set up correctly for the vendor to use in testing, make sure pw is the correct one (check msv3-server)=> run the connection test!
* create a product to be used w/ the test vendor, and set a product no. from the msv3-server as the product no. in bpartner tab, for the test vendor (check current vendor=Y)
* add prices for the product in vendor & customer pricelist for testing

**Test:**
* create a sales order, using the test product
* select the orderline, use "Bestellungen disponieren / Create purchase orders action":
  * modal window opens to set the qty to order: OK
  * modal window shows info about qty that can be delivered from the vendor: OK
* you can select the line w/ the info of deliverable qty, and run the resp. action, Done
* check Bestelldispo window: 
  * a new one was created, w/ the deliverable qty: OK
* complete the sales order
* check Bestelldispo:
  * shows info about the purchase order in tab: NOK, tab was empty
* check Bestellung:
  * no purchase order was created: NOK

**Comment by metas-ts** [comment]
solved the reported NOKs, going to push now..

**Comment by metas-dh** [comment]
checked with metas-mk: was tested successfully in the meantime.
