### ISSUE TITLE
Qty LU wrong in purchase invoice candidates / invoice

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3438]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Qty LU is wrong in purchase invoice.
#### Which are the steps to reproduce?
1. Create a purchase order, with >1 orderline
2. Create material receipts:
  * use Transform to split off TUs & CUs
  * receive standalone TUs and CUs as well as LUs with aggregated TU/CU
3. Check the invoice candidates:  qty LU is not correct; in my case, i had qty LU = qty TU (10) in the invoice candidates & invoice, although i had only 3 LUs used in material receipt
4. Create the invoice: qty LU is not correct: NOK
  
(might be related to the recent changes in #3302, not sure)
### What is the expected or desired behavior?
Qty LU in IC and invoice shall be correct, i.e. the same as the qty from material receipt(s).

**Comment by metas-lc** [comment]
IT
1. purchase order with 2 products
2. tested by making receipts, taking products one by one, used transform
=> correct number of TUs and LUs in IC and invoice OK
3. tested by making receipts, taking both products at the same time, used transform
=> correct number of TUs and LUs in IC and invoice OK

4. purchase order with 1 product
5. tested by transforming: having 2 types of LUs, 2 types of TUs, standalone CUs
=> correct number of TUs and LUs in IC and invoice OK
