### ISSUE TITLE
Improvement of GO Delivery Order Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3439]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Window for Go Delivery Order needs some improvements for better usability.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Move the fields for "HWB Number" and "AX4 Number" to Main View.

**Comment by metas-lc** [comment]
IT
HWB Number and AX4 Number are in main view in GO! Delivery Orders OK
