### ISSUE TITLE
Improvement of Shipper Window in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3440]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Shipper Window needs improvement for the GO! Configuration Subtab.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Check and Improve the GO! Configuration Subtab.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The Shipper window has a GO Configuration subtab
* OK: The Subtab has a white background and respects our layout conventions
* OK: The Subtab has translations for both English and German languages.
* OK: The Subtab is functional ( I was able to create entries in it wintout errors)

Regression: 
* OK: The Shipper window respects our layout conventions
* OK: The othe included tab is also working well.
