### ISSUE TITLE
Qty TU not correct in purchase invoice jasper

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3445]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you have material receipts with standalone TUs, standalone CUs and LUs with aggregated TUs, the qty TU is incorrect in the purchase invoice jasper, in the product part. Invoice itself & material receipt jasper are fine.

Material Receipt Jasper:
![material receipt jasper correct](https://user-images.githubusercontent.com/18696715/35810677-d3c60b0c-0a8c-11e8-9c06-e93578b085b7.png)

Invoice:
![invoice correct](https://user-images.githubusercontent.com/18696715/35810690-db37772c-0a8c-11e8-9b36-e64a1ab01efa.png)

Invoice Jasper:
![invoice jasper incorrect](https://user-images.githubusercontent.com/18696715/35810706-e51635ee-0a8c-11e8-8922-c6afea4ec721.png)

#### Which are the steps to reproduce?
1. Have material receipt candidates with >1 TU
2. In HU Editor, use Transform: e.g. split off TUs from LU, and CU from TU so you have standalone TUs & CUs: in the case above, i had 1 LU with 3 TUs, 1 standalone TU & 1 standalone CU for both Frisée & Radiesli.

### What is the expected or desired behavior?
QtyTU shall be correct in invoice jasper.

**Comment by metas-lc** [comment]
noticed that the product's qty is doubled in some cases. Taking back to check why

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* repeated testcase from above: qties TU in invoice jasper correct: OK
* used different types of TU for the same material receipt candidate: qties in material receipt jasper are ok, also in the invoice, but not in the invoice jasper: 

material receipt:
![2018-02-21 14_25_19-184_1000020 pdf](https://user-images.githubusercontent.com/18696715/36482458-a8cfb946-1713-11e8-838a-1ce4a6638be4.png)

invoice:
![2018-02-21 14_27_58-metasfresh](https://user-images.githubusercontent.com/18696715/36482468-b1af5f4e-1713-11e8-84dd-9552297fb1c2.png)

invoice jasper:
![2018-02-21 14_24_59-183_1000004 pdf](https://user-images.githubusercontent.com/18696715/36482478-ba2db2c4-1713-11e8-9725-b6777b45c31f.png)

* when product was ordered w/ No Packing Item, but a TU was used in material receipt, there is an IC created for the TUs, but they are not included in the invoice: will probably be fixed by #3533

**Comment by metas-lc** [comment]
devtest

- invoice without HU
- order 1 product - 1 inout with 2 different TUs (use split/transform for that) - invoice 
- order multiple products - multiple inouts - multiple HUs (transform) - invoice

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* repeated testcase from above: qties TU in invoice jasper correct: OK
* used different types of TU for the same material receipt candidate: qties in material receipt jasper are ok, also in the invoice, but not in the invoice jasper: OK
=> different TU types are listed together in product line, w/ overall sum, but in Gebinde the resp. qties are shown: OK

had an issue w/ one of the TUs missing at first in the invoice (tax issue: solved), but this subject will be checked again in #3545
