### ISSUE TITLE
Extract esb code into dedicated repo

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3451]
### Is this a bug or feature request?
FR
### What is the current behavior?

Currently the code is in https://github.com/metasfresh/metasfresh, complicates the build process and is barely ever used

### What is the expected or desired behavior?

The code should be in its own repo

**Comment by metas-ts** [comment]
TODO in eclipse:
* make sure that the following projects are removed
  * de.metas.parent
  * de.metas.reactor
  * de.metas.esb
  * de.metas.edi.esb.camel
  * de.metas.printing.esb.camel
* import via "Import .." => "Existing Maven Projects" the parent pom which is now in the metasfresh root folder

**Comment by metas-rc** [comment]
Nothing to IT. Moving to done
