### ISSUE TITLE
Improve performance around update_trl_tables_on_ad_element_trl_update

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3457]
### Is this a bug or feature request?
FR
### What is the current behavior?

I noticed that on a rollout to a large system, the DB spend a lot of time running `update_trl_tables_on_ad_element_trl_update`

I think we need to tweak this:
* check if we have indices to support those joins we do in that function
* in the model interceptor `AD_Field.updateTranslationsForElement()`, 
   * if we need to run it, we should extract the code into a quicker function that just updates field-translactions
   * i'm not sure if we need to run it on "new" anyways..

#### Which are the steps to reproduce?

Rollout the migration file 5484240_sys_gh3411-app_add_window_for_verfuegbarkeit_and_bestellung.sql' to a system and check the duration:

```sql
select name, durationmillis from ad_migrationscript 
where filename='5484240_sys_gh3411-app_add_window_for_verfuegbarkeit_and_bestellung.sql'
```

* on a large user's UAT-DB it took 323 seconds
* on a seed-DB, it only took 13 seconds

Note: this file contains 143 invocation of  `update_TRL_Tables_On_AD_Element_TRL_Update`. (there are 286 `INSERT INTO AD_Field`statements)

**Comment by metas-rc** [comment]
Please, do regression test the update translations.

**Comment by metas-lc** [comment]
https://github.com/metasfresh/metasfresh/issues/1752#issuecomment-357914126
step 7 is not working

**Comment by metas-rc** [comment]
Please, do the config from here https://github.com/metasfresh/metasfresh/issues/1752#issuecomment-357961089 and try again.

**Comment by metas-lc** [comment]
thank you. did that, tried again => worked. Moving it to done
