### ISSUE TITLE
Remove M_Storage-based legacy check from MProduct

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3458]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
Note for follow up:
the old code does the check if
* M_Product is not new
* IsActive='Y'
* ProductType = Item
* IsStocked = Y

**Comment by teosarca** [comment]
For those about to rock, we salute you :)

**Comment by metas-dh** [comment]
checked w/ metas-ts : nothing to test, moving to done.
