### ISSUE TITLE
Window Role Tab User Access shows non systemusers

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3465]
### Is this a bug or feature request?
bug

### What is the current behavior?
Window Role Tab User Access shows non systemusers

#### Which are the steps to reproduce?
1. open window role 
1. tab user
1. add new record
1. select a non systemuser

### What is the expected or desired behavior?
only systemuser=Y should be selectable

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Window Role, Tab User Access shows only systemusers: OK
* checked w/ original SystemUsers & new ones: OK
