### ISSUE TITLE
Preparation Date Filer as Daterange

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3467]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Preparation Date Filter in Manufacturing Order is only a Date.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Change it to Date range.

**Comment by metas-lc** [comment]
IT
checked preparation date filter in manufacturing => date range OK
