### ISSUE TITLE
Add Translation for "All Dates available"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3468]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The initial Filter content for Daterange Filters is shown as "All Dates available". 
#### Which are the steps to reproduce?
Open and see (e.g. Preparation Date Filter in manufacturing Order)
### What is the expected or desired behavior?
Add a Translation to AD Messages.

**Comment by metas-lc** [comment]
IT
1. check Preparation Date Filter in manufacturing Order
=> en: show all dates OK
de: alle zeitraume anzeigen OK
