### ISSUE TITLE
Disable Sales Opportunities Window until its permission is configurable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3471]
### Is this a bug or feature request?
FR

### What is the current behavior?
sales oppportunity window is always displayed
currently there is no way to configure its visibility via permission system

#### Which are the steps to reproduce?
have a role with only one window and you will see two windows in menu

### What is the expected or desired behavior?
disable it for now until we made its visibility configurable for the admin

**Comment by metas-rc** [comment]
Results of IT


Tested on webui and db


* OK: The menu entry for Sales Oportunity is disabled in db
* OK: The window cannot be accessed by Admin
