### ISSUE TITLE
Cannot save manufacturing order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3477]
### Is this a bug or feature request?
bug
### What is the current behavior?
Cannot save manufacturing order
#### Which are the steps to reproduce?
create a new manufacturing order, save =>
"No qualifying bean of type 'org.eevolution.mrp.api.IMRPExecutor' available"
https://pastebin.com/ePcbgvJG
### What is the expected or desired behavior?
shall save

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no error when saving a manufacturing order: OK
* also tried reactivating and saving the order again: working fine, OK

**Comment by metas-ts** [comment]
Cherry-picked to `release`
