### ISSUE TITLE
Force refreshing virtual column CreditLimitIndicator from C_BPartner

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3481]
### Is this a bug or feature request?
FR
### What is the current behavior?
CreditLimitIndicator from C_Bpartner is not refreshed when an order is completed, for example.
#### Which are the steps to reproduce?
Try and see
### What is the expected or desired behavior?
CreditLimitIndicator shall be refresh with the new percent each time when we complete an order, invoice, payment, shipment.

**Comment by metas-lc** [comment]
IT
credit limit from bpartner updates after createing e.g. sales order. Tested here
https://github.com/metasfresh/metasfresh/issues/3414
