### ISSUE TITLE
Default Value for process create order from quotation

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3483]
### Is this a bug or feature request?
FR

### What is the current behavior?
process asks you for the doctype 

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/Quotation_to_SalesOrder.html

### What is the expected or desired behavior?
as we always want to create a sales order the value should be preselected

**Comment by metas-lc** [comment]
IT
opened sales invoice window, selected a completed document
actions -> Create Sales Order from this Quotation
=> document type is already set to Sales Order OK
