### ISSUE TITLE
Extend Identifier Transportation Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3487]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Identifier for Transportation Order is just the Document No.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Extend the Identifier for Transportation Order.

**Comment by metas-lc** [comment]
IT
checked transportation order: set all fields. See identifiers (e.g. breadcrumb)
=> documentno, tour and Abholung am date OK
