### ISSUE TITLE
Paperless Credit Limit approval

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3490]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, credit limits can be recorded and they are checked during sales order completion. The approval of credit limits must be done manually by insurance responsible user and Managing Director.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Enhancement of credit limit approval Action:
- new Field "Approved" (Flag)
- New Field "Created By" (Is set initially with the current user
- Field "Approved By" is initially empty and is only set be autoApproval order Approval Process/ Action
- new Process/ Action "Approve Credit limit" (will be used by the Managing director)
- New Process/ Action "Request Approval for Credit limit" (will be used by User for Request to Managing director. Parm = User Managing Director, Managing director receives a Notification with URL link to business partner) 
- Credit Limit Type. Switch from Reference List to table Reference. Add Column "auto approval". If this is "Y" then auto approve each Credit Limit entry of that type.
- Credit Limit Line is read-only after approval.

**Comment by metas-lc** [comment]
IT
1. window bpartner, tab Busines Partner Credit Limit
=>  new Field "Approved" (Flag) OK But not translated!!!
=>  New Field "Created By" (Is set initially with the current user) OK  But not translated!!!
=> Field "Approved By" is initially empty and is only set after Approval Process/ Action OK
2. create new credit limit
=> Approved N, Approved By empty, line is editable OK
3. select that line and go to actions:
=> new Process/ Action "Approve Credit limit" (will be used by the Managing director) How can i know it can be used only by Managing director?
=> New Process/ Action "Request Approval for Credit limit" (will be used by User for Request to Managing director. Parm = User Managing Director, OK
4. select Approve Credit limit action
=> Approved Y, Approved By set, line is readonly OK
5. create a new line and use "Request Approval" action
=> Managing director receives a Notification with URL link to business partner) OK
=> Approved N, Approved By empty, line is editable OK

6. Open Credit Limit Type window.
=> new Column "auto approval". 
7. set auto approval on "Y" 
8. create a Credit Limit entry of that type.
=> Credit Limit Line approved, readonly and Approved by is empty OK
