### ISSUE TITLE
Improvements to Product Price Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3495]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Window Product Price needs a few improvements for better usability.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Do the following adjustments to product price window in WebUI:
- Add Active Flag to main view/ grid view

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Active Flag is included in grid view: OK
