### ISSUE TITLE
Days Due in Open Items report empty when parameter not set

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3497]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you don't set the Days Due param for Open Items report, then this field remains empty in the report, in WebUI. In Swing, the value is "Unlimited". When you set e.g. 80 days in the param, this is displayed correctly in the report.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Days Due shall show "Unlimited" if param not set, as in Swing.

**Comment by metas-lc** [comment]
DaysDue is a bigdecimal parameter. In jasper is compared with -999999 to print the field or not (didn't work with null)
have to check what value has that parameter in swing and what value has in webui. 
Then we need to see if we can have the same values in both swing and webui or/and update the report

**Comment by metas-lc** [comment]
in jasper, there was a default value for the parameter, -999999 
took that out, compared with null instead of -999999

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Days Due in Open Items report, parameter not set:
* WebUI: "Unlimited", OK
* Swing: "Unlimited", OK
