### ISSUE TITLE
Invoice Schedule is ignored in Invoice Candidates

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3498]
### Is this a bug or feature request?
bug
### What is the current behavior?
invoice schedule does not apply
#### Which are the steps to reproduce?
note: it might be a config problem. This might only need debugging. On some server works
1. i created a new invoice schedule, like that: 
![image](https://user-images.githubusercontent.com/16001666/36249019-16b37d2a-1242-11e8-9518-c53cd1c4d4d1.png)
2. so i would get to invoice every friday. If you are testing on a friday, choose another day!
3. Go to bpartner A, tab customer and set your invoice schedule
4. go to sales order and create a new one, bpartner A, add a product and complete
=> notice the invoice candidate has "invoice date from" something like 12.12.9999 OK
5. go to shipment candidates and create+complete an inout
6. check your invoice candidates
=> "invoice date from" is set on Today, instead of the date you set in steps 1-2. E.g. i got mine on 14.02.2018 instead of 16.02.2018
![image](https://user-images.githubusercontent.com/16001666/36249379-26216ad2-1243-11e8-80ad-994effd735ac.png)

### What is the expected or desired behavior?

might be that some config is missing. If it's a bug, please fix to take the date from invoice schedule

**Comment by metas-rc** [comment]
Documentation

 This was just a configuration detail
 When order and then the invoice candidate have the invoiceRule = After Delivery ( D)  the following happens:
* When the invoice candidate is created, its DateToInvoice becomes something like a maximum, unreachable date ( 31/12/9999)
*  When the shipment is completed, the DateToInvoice from the invoice candidate becomes today = the day when the inout was created
* Obviously, the invoice schedule is ignored for this kind of invoiceRule

* The invoice schedule is used for the invoice rule Customer Schedule after Delivery (S) 
* If the sales order and then the invoicecandidate have this rule, the invoice candidate is created with no DateToInvoice
* This date is only set when the inout is completed
* The date is set to the next day according to the schedule ( in our example, next Friday)
