### ISSUE TITLE
Default Filter Improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3502]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few windows in web UI where some needed filter criteria are missing.
#### Which are the steps to reproduce?
None
### What is the expected or desired behavior?
Add the Filter criteria in:
- [x] Order Candidates: isActive
- [x] Sales Order: Documenttype, Documentstatus
- [x] Bestellung: CreatedBy
- [x] Rechnungsdisposition: isSoTrx, inDispute
- [ ] ~~Shipment Schedule: delivery amount < 0~~

**Comment by metas-lc** [comment]
IT
checked filters:
Order Candidates: isActive OK
Sales Order: Documenttype, Documentstatus OK
Bestellung: CreatedBy OK (not translated!!!!)
Rechnungsdisposition: isSoTrx, inDispute OK
Shipment Schedule: delivery amount < 0 ?

**Comment by metas-mk** [comment]
@metas-lc fixed locally on w101. I propose to move this one to done
![image](https://user-images.githubusercontent.com/13365687/36381850-2c320070-1587-11e8-837c-0041845fd1a3.png)
