### ISSUE TITLE
Use correct picking quantities in shipment

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3503]
### Is this a bug or feature request?
FR

**Comment by metas-dh** [comment]
Results of IT1
tested in weekly e2e

* qty TU in shipment as picked: OK for the cases i tested (will test more different TUs from the same order)
* no TUs in shipment when generated from Gear, although ordered: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* no TUs in shipment when generated from Gear, although ordered: NOK

**Comment by metas-ts** [comment]
fixed in branches `2018-12` and `master`

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* qty TU in shipment as picked: tested with
  * partial qty shipment: OK
  * different TU picked than ordered (different qty per TU): OK
  * mix of different TU picked than ordered (different qty per TU) and TU as ordered: OK
* qty TU in shipment when shipment generated from Gear, without picking, when TU (1 or more) was ordered: TU is included, OK
