### ISSUE TITLE
Improvement of Procurement Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3505]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In window Procurement candidates (disposition), it is hard for the user to recognize what she/ he has already recorded in via grid view. The information that a contract is existing is missing in the grid. This information enables the user to decide which business partners she/ he shall prefer.
Also, the Packing Instruction is missing.

#### Which are the steps to reproduce?
None
### What is the expected or desired behavior?

- [x] Add Packing Instruction in between Attribute and UOM main view
- [x] Add Contract to main view
- [x] Add Qty to Order to main view
- [x] Move TU next week and TU next week orderable to enhanced edit
- [x] Remove currency from the grid view

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* Add Packing Instruction in between Attribute and UOM main view: OK
* Add Contract to main view: OK
* Add Qty to Order to main view: OK
* Move TU next week and TU next week orderable to enhanced edit: OK
* Remove currency from the grid view: OK
