### ISSUE TITLE
QtyOnHand in shipment schedule incorrect

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3507]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Notticed in weekly e2e with different qties in sales order, material receipt & manufacturing order picking & partial shipment of the same product, the QtyOnHand in material cockpit is correctly summed up, but in shipment schedule it's incorrect.
Also QtyOnHand is not set back when an order is reactivated, so the qty for the same order is doubled after reactivating and completing again.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
QtyOnHand in shipment schedule shall be correct.

**Comment by metas-dh** [comment]
Info from #3079:

* when allocating QtyOnHand to shipment schedules, all warehouses from same picking group as the shipment schedule's warehouse shall be considered: this did not work in IT, see https://github.com/metasfresh/metasfresh/issues/3079#issuecomment-351001289

=> pls check / consider QtyOnHand from warehouse picking group in shipment schedule as well.

**Comment by metas-ts** [comment]
solving this together with https://github.com/metasfresh/metasfresh/issues/4683

**Comment by metas-dh** [comment]
Results of IT1
checked in release

QtyToDeliver correct in shipment schedules, was fixed with #4683.
