### ISSUE TITLE
Implement DATEV export window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3508]
### Is this a bug or feature request?
FR

### What is the current behavior?
no DATEV export

### What is the expected or desired behavior?
have a DATEV export window where user can create an export header, specifying the period which he/she is exporting.
System will populate some included tab or something with data to be exported.
System shall also track what was already exported and not export again (optional).

**Comment by teosarca** [comment]
Note to IT:
* regression: make sure documents can be posted (try posting/reposting each document type)


Status/TODO:
* IsExcludeAlreadyExported flag is not yet implemented

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new DATEV export window where user can create an export header, specifying the period which he/she is exporting: OK
* System will populate some included tab or something with data to be exported: if it's only done by the system, why do we have an action "Create export lines"? (which worked, for purchase invoice, btw)
* System shall also track what was already exported and not export again (optional): checkbox for "Exclude already exported": OK i think?


regression: make sure documents can be posted (try posting/reposting each document type): 
* purchase order: OK
* material receipt & purchase invoice: 
   * error when packing items were used, bc those have no data set in M_Product_Acct 
   * i had a 5-digit account in purchase invoice for product: afair we should only have 4-digit accounts? not sure if this only applies to spec. customer, though
* Abgeglichene Rechnungen (MatchInv): OK
* Abgeglichene Bestellungen (MatchPO): OK

ToDo: finish regression

**Comment by metas-dh** [comment]
Update:
* posting worked fine after creating missing data for M_Product_Acct for packing items, using process in product categroy window, Accounting tab (Swing)
* process shall be available in WebUI as well: #3812

**Comment by metas-dh** [comment]
>System will populate some included tab or something with data to be exported: if it's only done by the system, why do we have an action "Create export lines"?

=> action not displayed anymore, OK

* got errors when posting for reversed invoices that included empties: he original reversed invoice is posted OK, but the one created by the system for the reversal does not: 

```
Invalid accounting operation structure (3 DR lines, 2 CR lines)
Posted: Verbuchungs-Fehler (Error) document: MInvoice[1000002-170242,GrandTotal=-7.14 (#2)] Preserve Posted status: false
```

console: https://pastebin.com/8PZCPFKp

=> NOK

**Comment by teosarca** [comment]
@metas-dh  @metas-mk  The solution is to disable `Currency Balancing`.
Ping me for more details.

![image](https://user-images.githubusercontent.com/1244701/38552644-6c19c410-3cc5-11e8-8c2f-86162125b60f.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* no more errors when posting for reversed invoices that included empties: the original reversed invoice is posted OK, as well as the one created by the system: OK
* 5-digit standard accts are OK in posting, check w/ metas-mk: OK
