### ISSUE TITLE
Webui: Pimp DATEV windows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3513]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3508

### What is the expected or desired behavior?
Following windows shall be added to menu and shall be pimped:
* DATEV Format: https://w101.metasfresh.com:8443/window/540414
* DATEV Export: https://w101.metasfresh.com:8443/window/540413

**Comment by teosarca** [comment]
wdyt?
![image](https://user-images.githubusercontent.com/1244701/36504849-7f4462ce-175a-11e8-8206-098fee1cb6b3.png)

**Comment by metas-mk** [comment]
- [ ] NOK: The name of the window Buchungen Export Format is not translated into English. Please, check Teo's picture above. ( Also, please check his suggestion of field position change and fix if it's suitable)
- [ ] NOK: The name of the window Buchungen Export is not translated to English
- [ ] NOK: The process for creating lines is not translated into German.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The 2 window names are translated into english
* OK: The process name is also trasnlated
* OK: The fields are displayed as Teo suggested
