### ISSUE TITLE
Webui: Pimp Compensation Group Schema window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3515]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/853

### What is the expected or desired behavior?
* check/pimp/add to menu compensation schema: http://localhost:3000/window/540415
* check/pimp Product Cateogory - Compensation Schema field
![image](https://user-images.githubusercontent.com/1244701/36373067-a0eac55e-156f-11e8-96fe-8c6ea12155be.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* window Compensation Group Schema: included in menu: OK
* window Product Category: field Compensation Group Schema pimped: OK

=> in de_DE, window Compensation Group Schema: Kompensationsgruppe Schema, OK, but: in Produkt Kategorie, field is called Compensation Group Schema, translation is missing!

**Comment by metas-dh** [comment]
pls add the translation, see above.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* "Kompensationsgruppe Schema" in product category, de_DE: OK
