### ISSUE TITLE
Price/ Discount Change restrictions Order/ Invoice Pharma

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3516]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Prices/ Discounts in german Pharma Industry are restricted by Law. For some combinations of Product and Business partner Customers, it is allowed to adjust prices, for others not.
#### Which are the steps to reproduce?
Keine.
### What is the expected or desired behavior?
Depending on different mechanisms the pricing/ setting of discounts shall be restricted
- Depending on Pricelist (allowed to adjust prices/ not allowed). Not allowed = Price Field read-only in recording Order lines, Invoice lines.
- Discount updateable depending on Product Categories
- Limit Price Functionality (Role + Limit Price in Product Price) shall be checked for updates/ changes prices.

**Comment by teosarca** [comment]
## Configuration, in pictures :)

### Enforcing price limit
![image](https://user-images.githubusercontent.com/1244701/36415554-068f67e2-162f-11e8-8398-58486d62e54b.png)
![image](https://user-images.githubusercontent.com/1244701/36415560-0d0dfe3a-162f-11e8-896d-37eeac205ac4.png)


### Making price/discount readonly
![image](https://user-images.githubusercontent.com/1244701/36415637-49d35d24-162f-11e8-8996-a4580543913a.png)

**Comment by metas-lc** [comment]
IT
price list window: header - Enforce price limit (default on N) OK
role window: Overwrite Price Limit (default on N) OK
product price window: Price Editable, Discount Editable (both default on Y) OK

1. go to product price and update a product you are going to use: set Price Editable and Discount Editable on N
2. create a new sales order and a new sales invoice with that product and try to update price and discount
=> in sales order you can't OK?
=> in sales invoice you can OK

3. go to price list window, set Enforce price limit on Y
4. create a new sales order and purchase order and try to update price and discount
=> in sales order you can't OK?
=> in sales invoice you can OK

5. go to role window and set Overwrite Price Limit on Y
6. create a new sales order and purchase order and try to update price and discount
=> in sales order you can't OK
=> in sales invoice you can OK?

7. go to product price and update the product you using: set Price Editable and Discount Editable on Y
8.  create a new sales order and purchase order and try to update price and discount
=> in sales order you can OK
=> in sales invoice you can OK

>>    Discount updateable depending on Product Categories
i think this was changed with product price, right?
