### ISSUE TITLE
Wrong currency in Dunning type

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3526]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The standard currency for metasfresh (ad_org & ad_client) in new db is currency=CHF. When running the Initial Setup Wizard in weekly e2e for the 1st time, with currency=EUR, the currency seems to remain CHF, which is taken for the dunning type. You have to run the setup wizard again / check the bank data for metasfresh to make sure the currency=EUR, and then create a new dunning type to have the correct currency for dunning.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Currency from Initial Setup Wizard shall be taken with 1st run.

**Comment by teosarca** [comment]
note to dev: 
* de.metas.fresh.setup.process.ClientSetup.ClientSetup(Properties) - there u shall load the dunning type
* de.metas.fresh.setup.process.ClientSetup.setC_Currency_ID(int) - there u shall update it's currency
* de.metas.fresh.setup.process.ClientSetup.saveInTrx() - there u shall save it

**Comment by walmeidasantos** [comment]
Hello there, 
I am working to fix this issue ! 

Wish me luck :)

**Comment by walmeidasantos** [comment]
Hello there,

I need some help to get to the results of this issue.

I did:

1- Start all the apps using docker.
2- Login it user
3- Click on Initial setup. There i can check that the default currency is CHF.
4- Changed the currency. 
5- Click start.
6- Open the Bank account. There i can check that the default currency is USD.

What i am doing wrong?

**Comment by teosarca** [comment]
You should check the Dunning Type window (i.e. C_Dunning table).
Atm the currency is not displayed there but will be fixed by https://github.com/metasfresh/metasfresh/issues/3616 .

See/use de.metas.dunning.interfaces.I_C_Dunning.setC_Currency_ID(int).

**Comment by metas-dh** [comment]
this has been working fine in the e2es of the last weeks, so i'm closing the issue. if the problem pops up again i'll create a new one.
