### ISSUE TITLE
New Window for Shipment Statistics

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3532]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we don't have a window for filtering/ exporting shipment statistics
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new window in WebUI. The window shall be based on a view (read-only). The data that shall be shown is the following:
- [ ] Shipment No.
- [ ] Shipmentdate
- [ ] BPartner Value
- [ ] BPartner Name
- [ ] Postal
- [ ] PZN (Product Value)
- [ ] Product Name
- [ ] Subproducer (origin)
- [ ] Package Size (from M_Product)
- [ ] Packing UOM
- [ ] UOM
- [ ] "Darreichungsform"
- [ ] Quantity
- [ ] "Lieferanten ID (= Hersteller ID)"

Ordered by Shipment No, Product Value

The aim is to use this window for filtering, then selecting rows or all rows, then download/ export excel.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* data shown as described above, except order for "Darreichungsform" & Quantity is switched: i think it's ok like this?
* Ordered by Shipment No, Product Value: OK
* package UOM: is UOM_ID=100, so e.g. 100 for Stück: OK? 
* subproducer: is subproducer_bpartner_id, not name: OK?
* package size: 10 = 10.00000000000 in table view (ok in single view), NOK i think (afair that was a problem we already had before, w/ view?)

**Comment by metas-dh** [comment]
checked w/ metas-mk:

* order for "Darreichungsform" & Quantity is switched: OK
* package UOM: is UOM_ID: NOK, shall be the name
* subproducer: is subproducer_bpartner_id: NOK, shall be the name
* translations are missing: mix of de & en headers: #3591

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* package UOM: is the name, OK
* subproducer: is the name: OK
