### ISSUE TITLE
Webui Window Design: Create window for Picking Config

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3534]
### Is this a bug or feature request?
* FR
* Followup for https://github.com/metasfresh/metasfresh-webui-api/issues/820
### What is the current behavior?
* There is no window for the M_Picking_Config
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* Please, add a window for M_Picking_Config, with all the needed fields ( including IsAllowOverdelivery) 
* Please, make it respect our layout conventions and  add translations for both German and English

**Comment by metas-mk** [comment]
Window ist there, but is system level.
![image](https://user-images.githubusercontent.com/13365687/36633413-7d0dd110-1995-11e8-8630-8b1dc9555ee1.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The window exists i nthe menu, opened as sys admin
* Open: Please, add also the field IsAllowOverdelivery.

**Comment by metas-mk** [comment]
- [ ] Open: Please, add also the field IsAllowOverdelivery

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The flag was also added inthe Pricking Config window
* OK: The field is translated in both German and English.
