### ISSUE TITLE
webui: Show GuaranteeDaysMin on Product and Product Category windows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3540]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3430

### What is the expected or desired behavior?
GuaranteeDaysMin shall be visible and editable on
* product window: https://w101.metasfresh.com:8443/window/140
* product category window: https://w101.metasfresh.com:8443/window/144

**Comment by metas-lc** [comment]
IT
product window: Min Guarantee Days / Mind. Haltbarkeit Tage OK
product category window: Min. Garantie-Tage / Mind. Haltbarkeit Tage OK

one field is not translated in en_US NOK
please translate the one from product category window (144)

**Comment by metas-mk** [comment]
- [ ] please translate the one from product category window (144). one field is not translated in en_US NOK

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The field is present in both window: Product and Product Category
* OK: The field is translated in ENglish and Germant for both windows.
