### ISSUE TITLE
Refactor config for Distribution Order/ Movement after Material Receipt

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3549]
### Is this a bug or feature request?
FR
Follow-up to https://github.com/metasfresh/metasfresh/issues/3409

### What is the current behavior?
Currently in PP_Product_Plan and what comes before and after, we have a Y/N column IsCreateDistributionOrder. 

When looking with mark at the system so see whether material dispo should have created a DD_Order, we found this a bit confusing and first I was going to add documentation.

### What is the expected or desired behavior?

Now i think with a bit of refactoring, the field will speak for itself and we can save both documentation and explanations in the user training:

Please refactor it
* change `IsCreateDistributionOrder` "Distributionsauftrag erstellen" `[Y/N]`
* to `OnMaterialReceiptWithDestWarehouse` "Bei Wareneingang mit Ziellager" [mandatory List] with values
   * `CreateDistributionOrder` "Distributionsauftrag erstellen"
   * `CreateMovement` "Warenbewegung erstellen"

**Comment by metas-lc** [comment]
IT
product planning schema: 
onMaterialReceiptWithDestWarehouse - you can select createMovement or Create Distribution Order OK

product planning and material receipt candidates - it's only in swing. But works fine OK

we have task for webui design : https://github.com/metasfresh/metasfresh/issues/3489
