### ISSUE TITLE
Sales invoice jasper sometimes not correct

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3554]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The sales invoice jasper is not correct when you have partial shipments and did reverse picking.

![2018-02-23 15_58_22-167_145809 pdf](https://user-images.githubusercontent.com/18696715/36600480-b29bbf74-18b2-11e8-87f0-74c3cb86a933.png)

#### Which are the steps to reproduce?
this is how i got the jasper above:
1. Sales order with 2 orderlines, same product:
  * orderline 1: 5 TUs
  * orderline 2: 3 TUs
2. Have the ordered product in stock, from material receipt or production
3. Pick partial qty for each orderline, CU only!
4. Create the shipment for the picked qties
5. Pick again for 1 orderline, with LU/TU, then reverse it
6. Pick remaining qty for both orderlines, with LU/TU
7. Create the shipment for the picked qties again
8. Create the invoice for all ICs
### What is the expected or desired behavior?
Sales invoice jasper shall be correct, showing the PI used / not used in shipments.

**Comment by metas-lc** [comment]
solved by https://github.com/metasfresh/metasfresh/issues/3790

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated the testcase above again, qties of packing items correct in sales invoice jasper: OK
