### ISSUE TITLE
Automatic Group Discount Calculation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3555]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the possibility exists to half-automatically create compensation group lines, but there is no logic to create discounts on the fly-
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?

- [ ] Extend the Compensation group Schema and add the following columns:
- [ ] Seq (Sequence, which discount shall be handled first, second, ...)
- [ ] Discount Group Type (Revenue break, Flatrate)
- [ ] Compensation group Discount
- [ ] Flatrate Term ID
- [ ] Revenue Break

When starting the action Multigroup lines in Sales Order, then

- [ ] Throw away all selected groups and regenerate them new
- [ ] Add the Discount Products based on their selectors
- [ ] in the sequence defined in Compensation Group Schema
- [ ] add the Compensation Group Discount from Schema

![image](https://user-images.githubusercontent.com/13365687/36601354-3728386a-18b5-11e8-9bae-7c2b87bb3afc.png)

**Comment by teosarca** [comment]
note to IT: full regression on Compensation Group functionality is NEEDED

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Extend the Compensation group Schema and add the following columns:

- [ ]  Seq (Sequence, which discount shall be handled first, second, ...)
- [ ]  Discount Group Type (Revenue break, Flatrate)
- [ ]  Compensation group Discount
- [ ]  Flatrate Term ID
- [ ]  Revenue Break

When starting the action Multigroup lines in Sales Order, then

- [ ]  Throw away all selected groups and regenerate them new
=> after grouping lines, multigroup lines action is not available for those lines anymore: OK, see https://github.com/metasfresh/metasfresh/issues/3612#issuecomment-371122822
- [ ]  Add the Discount Products based on their selectors
- [ ]  in the sequence defined in Compensation Group Schema
- [ ]  add the Compensation Group Discount from Schema


Regression on Compensation Group functionality:
* grouping lines and multigroup lines actions not possible already grouped lines: OK
* manual discount still possible after multigroup functionality: OK
* manual discount and multigroup have no effect on each other, see https://github.com/metasfresh/metasfresh/issues/3612#issuecomment-370919595: OK
* manual discount for a group shown at the end of its own group, not at the end of all orderlines: OK
* compensation type break value added / taken away accordingly when qty is increased / decreased: OK
* Automatic Compensation Grouping with Parent Product Category: not working anymore, NOK: #3734
