### ISSUE TITLE
Webui: Pimp Compensation Group Schema window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3556]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3555

#### Which are the steps to reproduce?
Check https://w101.metasfresh.com:8443/window/540415.

### What is the expected or desired behavior?
Make sure newly introduced fields are nicely  displayed.

**Comment by metas-lc** [comment]
IT
seq no, discount type, comp. discount, flatrate term, revenue break were added in compensation group schema subtab Products OK

SeqNo
Type OK
Discount % OK
Break Value (you can set it only if type is revenue) OK
Flatrate Conditions (you can set it only if type is flatrate) OK

translations are fine OK
