### ISSUE TITLE
Respect Picking Group Selection in Picking HU Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3557]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Qty assignments in Shipment Schedule respect the Qties from Warehouse Picking groups, but this does not happen in 
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The picking group shall also be respected when selecting the HU source View in Picking Terminal.

**Comment by metas-lc** [comment]
IT
1. have 3 different wh
2. 2 of them (A and B) have the same group, the 3rd one (C) has another group set
3. make sure you have picking slots for each wh and available hus with products
4. create a sales order with wh A. go to picking terminal, open hu selection window  
=> you can see HUs from both wh: A and B OK
5. pick and process hus from both wh A and B, create inout
=> inout created correctly, wh from order, no errors OK
6. repeat steps 4 and 5 with wh B
=> works the same OK
7. repeat steps 4 and 5 with wh C
=> you can see HUs only from wh C OK
=> inout created correctly, wh from order, no errors OK

regression
1. have a wh without group
2. create/complete sales order with that wh
3. go to picking terminal, pick, open hu selection window
=> you'll see the HUs only from that wh
