### ISSUE TITLE
Add relation between Invoice and Shipment Constraint

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3561]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently we don't have a relation between  Invoice and Shipment Constraint
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, add a relation type between  Invoice and Shipment Constraint

SQL received from Torby: 

```
 from c_invoice i     
    LEFT JOIN c_dunning_candidate dc
      ON dc.record_id = i.c_invoice_id AND dc.ad_table_id = 318 AND dc.c_dunninglevel_id = 540009
    LEFT JOIN c_dunningdoc_line_source dls ON dls.c_dunning_candidate_id = dc.c_dunning_candidate_id
    LEFT JOIN c_dunningdoc_line ddl ON ddl.c_dunningdoc_line_id = dls.c_dunningdoc_line_id
    LEFT JOIN c_dunningdoc dd ON dd.c_dunningdoc_id = ddl.c_dunningdoc_id
    LEFT JOIN m_shipment_constraint sc ON sc.sourcedoc_record_id = dd.c_dunningdoc_id
```

**Comment by metas-lc** [comment]
IT
1. config dunning
2. create/complete invoice
3. go to dunning cands and run create/update dunning candidates
4. process dunning candidates
=> new dunnings are created
5. create new shipment restriction, add table dunning doc and set sourcedoc_record_id = dunning doc id from database
=> referenced documents - you can zoom in to invoice OK
6. zoom in to invoice, see referenced documents
=> shipment restriction is there and you can zoom into OK
