### ISSUE TITLE
Primary Layout in Product Planning Subtabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3562]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Product Planning Subtabs dont't have the primary layout background.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the primary background layout to subtabs, advanced edit.

**Comment by metas-lc** [comment]
IT
checked Product Planning Subtabs => all have primary layout OK
