### ISSUE TITLE
Initial Promised Date calculation and default Preparation Date

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3565]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Promised Date in Sales Order is initially set equal to date ordered. Also, the preparation Date is based on Promised Date, Buffer Hours and delivery days that are prerecorded for each business partner and date.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Do the following changes:
- Add Promised Date Offset to Tour Version header. It allows setting a number of hours that shall allow the calculation of the promised Date + Time
- Allow the Tour Version line to be recorded without Business partner and location. Delivery days calculated with this kind of schema are valid for all business partners that don't have an explicit entry for the given day+time in delivery days.

**Comment by teosarca** [comment]
### Configuration

#### DatePromised offset (in days)
see `de.metas.order.DatePromisedOffsetDays` sysconfig.

#### Tour version
e.g.
![image](https://user-images.githubusercontent.com/1244701/36728517-ac3e4254-1bc9-11e8-97b5-fb07876f2807.png)

=>
![image](https://user-images.githubusercontent.com/1244701/36728543-bfe4030c-1bc9-11e8-92f2-8c22f2b66077.png)

**Comment by teosarca** [comment]
note to IT:
additionally, regression on generating delivery days is needed.

**Comment by metas-rc** [comment]
Note: 
> DatePromised offset (in days)
see de.metas.order.DatePromisedOffsetDays sysconfig.
The Promised Date in Order is not influenced if the sys config above is with value = 0.

**Comment by metas-rc** [comment]
Note 2: I talked with Teo and he told me the C_Order.DatePromised is not at all influenced by any data in TourVersion. 
Basically, datePromised will be:
* The same as it was before (the day of DateOrdered, hour 11:59 PM) if the sys config has value 0
* The day of DateOrdered + x,  hour 11:59 PM, where x is the value in the sys config (e.g. for the DateOrdered 03/21/2018, and sys config value = 2,  it would be 03/23/2018 12:00 AM)

**Comment by metas-rc** [comment]
Note that there are differences in the hour when opening the order in single view and in grid view

![image](https://user-images.githubusercontent.com/16001442/36985549-3af157fe-20a0-11e8-9906-d0fab2916873.png)


![image](https://user-images.githubusercontent.com/16001442/36985732-b77fd69c-20a0-11e8-9164-519ea49e2537.png)

**Comment by metas-rc** [comment]
Hopefully, these problems will be solved in the following tasks: 
* https://github.com/metasfresh/metasfresh-webui-api/issues/789
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1547
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1654
* https://github.com/metasfresh/metasfresh-webui-api/issues/892

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

Having in mind the problems above which are not strictly connected with this task, the functionality alone is correct:

* OK: The value in sys config is added to the number of days added to the Promised Date in order
* OK: The values from the Tour version are respected when calculating the Preparation Date
* OK: The Tour Version Line can be created with no partner and location. 
* OK: The Delivery Days are correctly created for the tour with no partner set.


Regression
* OK: When partner and location are set in Tour Version line, the delivery days are correctly created with the details of the TourVersion header of that line
*OK: When creating an order for a partner that has a tour version line, the preparation time is the one from the  tourversion of that partner.
