### ISSUE TITLE
CustomerLabelName in M_Product and Translation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3570]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no CustomerLabelName in M_Product (only in Product>>BPartner Product).
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Create a new Field in M_Product for CustomerLabelName. Create a field in Product translation for that too. Use that CustomerLabelName in Jasper Customer Labels if no BPartner Product entry is found. (also for Translations)

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db (Swing)

* CustomerLabelName and translation: new fields in product window and translation tab: OK
* CustomerLabelName and translation is used in Jasper Customer Labels: OK
* if BPartner Product entry exists, then that is used in Jasper Customer Labels: OK
* normal product name & translation is used in the other Jasper Labels: OK

(could set BPartner Product translation (C_BPartner_Product_Trl): =>#3626)
