### ISSUE TITLE
Internal usage (Materialentnahme partial) broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3572]
### Is this a bug or feature request?
Bug?
### What is the current behavior?
The Materialentnahme partial brings an exception:
```
105
:
"Caused by: java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result."
106
:
"	at java.math.BigDecimal.divide(BigDecimal.java:1690)"
107
:
"	at de.metas.handlingunits.allocation.transfer.HUTransformService.tuToTopLevelHUs(HUTransformService.java:899)"
108
:
"	at de.metas.handlingunits.allocation.transfer.HUTransformService.tuToNewTUs(HUTransformService.java:603)"
109
:
"	at de.metas.handlingunits.allocation.transfer.HUTransformService.luExtractTUs(HUTransformService.java:707)"
110
:
"	at de.metas.handlingunits.allocation.transfer.HUTransformService.huToNewTUs(HUTransformService.java:665)"
111
:
"	at de.metas.handlingunits.allocation.transfer.HUTransformService.husToNewTUs(HUTransformService.java:648)"
112
:
"	at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_MoveTUsToDirectWarehouse.doIt(WEBUI_M_HU_MoveTUsToDirectWarehouse.java:109)"
113
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)"
114
:
"	... 101 more"
115
:
""
```
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Fix.

**Comment by metas-mk** [comment]
![image](https://user-images.githubusercontent.com/13365687/36720142-6cbd4458-1ba7-11e8-9113-4df87382c3fd.png)

**Comment by metas-lc** [comment]
IT
1. have an LU with 5 TUs, with qty 46.025 kg
2. go to handling units window, select it and run Materialentnahme (partial)
3. select a qty TU 3 , ok
=> your hu is now updated (qty 18,410, qty TU 2) OK
4. select the LU again and do normal Materialentnahme 
=> no errors
5. search for the new TU (from step 3)
=> 3 new created, qty 9,205 each
6. go to movements 
=> 4 new movements created to Materialentnahme OK
(1 for LU+2TU+prod., 3 for TUs+prod. )
