### ISSUE TITLE
make shipment HU aggregation configurable

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3575]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
IT: please look at the PR #3589 for details

**Comment by metas-rc** [comment]
Note: The window is not present in  webui. Followup created: https://github.com/metasfresh/metasfresh/issues/3648

**Comment by metas-rc** [comment]
Results of IT


Tested on webui + swing

* OK: Attribute related config was added to shipment schedule handler.
* OK: All the attributes that were set in the orderline are transmitted to shipment schedule.
* OK: If the attributes in this config are active and they are set in orderline, they are transmitted to shipment schedule, then to shipment.
* OK: The inactive attributes in the config are not transmitted to the shipment line even if they were set in the order line.

**Comment by metas-rc** [comment]
Please, test together with https://github.com/metasfresh/metasfresh/issues/3590

**Comment by metas-rc** [comment]
Results of IT


Tested on webui + swing

* I will describe how the attibutes are propagated (or not)  in some specific cases.
*  IsActive = Y/n  means Attribute has IsActive = true/ false in Shipment Schedule Handler
* NFRD = Y/N means " Nur falls in ref. Datensatz" is true/false in  Shipment Schedule Handler

Case 1) IsActive = N, NFRD = N
* OK: The attribute does not get in the shipment line even if it was set in the orderline or in the HU

Case 2) IsActive = Y, NFRD = N
* OK: The attribute gets in the shipment line if it was set in the orderline and/or in the HU

Case 3) IsActive = Y, NFRD = Y
* OK: The attribute gets in the shipment line if it was set in the orderline
* OK: If it was not in the orderline, it does not get in the shipment line even if it was set in the HU

**Comment by metas-rc** [comment]
* Receive 2 HUs with relevant attributes with equal value
* Receive 1 HU with the same attribute with a different value
* Pick all the hus from the sales order
* Goto the shipment schedule
* Run Generate Shipment with the complete flag n false (so oyu can easily see the attributes and for no other reason) and with the picking flag on true!
* Check the shipment that was created
* OK: There a re 2 lines
* OK: One line has the added qtys for the 2 HUs with the same value in the attribute.
* Ok: One line is for the third HU and has the asi set accordingly.
