### ISSUE TITLE
TU label in picking

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3576]
### Is this a bug or feature request?
fr
### What is the expected or desired behavior?
new jasper label for hu to be used in picking

**Comment by metas-lc** [comment]
currently is not working well, because of the sscc18 attribute. Created task : https://github.com/metasfresh/metasfresh/issues/3579

**Comment by metas-rc** [comment]
Results of IT

Tested on webui



* OK: The process is available after I open picking, open Select HU to Pick and open the available actions.
* OK: When I run the process for a line of a partner with a GLN set in their address, the Label report is displayed and correct
* NOK: When the GLN is missing I get an IO eror. Followup created: https://github.com/metasfresh/metasfresh/issues/3767

**Comment by metas-dh** [comment]
Results of IT2
tested in customer db

* process in HU Editor for selection: not working, got only an empty page: NOK
* process in picking slot, after picking: worked, but the label:
    * shows only part of the location name: NOK
    * the address is cut off: NOK

@metas-lc: pls contact me for pics and more info!

**Comment by metas-lc** [comment]
the address and the location name are now on multiple lines if they don't fit in 1

took out the label from hu editor. But you should be able to see it in picking terminal and shall be able to print it automatically on "pick to new HU"

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* Picking TU Label: not available in HU editor anymore (HU Editor window or material receipt cands), but in picking: OK
* tried printing the label manually in picking and automatically for "Pick to new HU" action: not working, despite no errors in async, AD_Instance was OK as well

**Comment by metas-dh** [comment]
Results of IT4
tested in mf15

* Picking TU Label: not available in HU editor anymore (HU Editor window or material receipt cands), but in picking terminal: OK
* printed the label manually in picking terminal and automatically for "Pick to new HU" action: both worked fine, got all labels in printing queue: OK
* customer with long name, long address & address name: was displayed in multiple lines on the label (PDF), no cut-offs: OK
