### ISSUE TITLE
Implement sales order candidates REST API

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3584]
### Is this a bug or feature request?
FR

**Comment by teosarca** [comment]
note to dev: developed in brach gh3584 (standard), but branched from gh664webui.

**Comment by teosarca** [comment]
note to dev: nothing to test, yet

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* EDI import worked fine, but processing after "Freigabe" did not work: "MScheduler[550015-Auftragskand. Verarb. "EDI-ORDERS Import,"3] - java.lang.StackOverflowErrorLogs deleted=0"

**Comment by metas-dh** [comment]
Results of IT2
tested in customer db

* EDI import worked fine:
   * prices and asi taken from current pricelist, with correct difference from import price: OK
   * correct info for delivery partner, invoice partner etc.: OK
* "Freigabe" working again: OK
* running "Freigabe" excludes OLCands that do not have "Eintrag übernehmen"=Y: OK
* correct error when price is missing, correct update after setting price and running "Suchauswahl überprüfen": OK
* EDI sales order / shipment / invoice correct: OK
