### ISSUE TITLE
WebUI window design: Business Partner Credit Limit

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3585]
### Is this a bug or feature request?
fr
### What is the current behavior?
missing translations in Business Partner Credit Limit, also there is a "main" written in advanced edit
#### Which are the steps to reproduce?
open BPartner window 123 and go to last subtab
=> created by and approved are not translated NOK
=> there is a "main" written in advanced edit OK?
### What is the expected or desired behavior?
trl the fields and probably remove "main"

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* NOK: The 2 fields are not translated in English

![image](https://user-images.githubusercontent.com/16001442/37822705-e0951f68-2e8f-11e8-81bc-5b9b7b6da81f.png)


* OK: these is no "main"  written any more
* OK: The rest of the fields are translated in both English and German.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK:  All the fields are now translated in both English and German
