### ISSUE TITLE
Implement user token authentication for future REST APIs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3587]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh/issues/3584

### What is the current behavior?
there is no such feature

### What is the expected or desired behavior?
Be able to define user authentication tokens and use then on REST APIs

**Comment by teosarca** [comment]
### How to config/use it
![image](https://user-images.githubusercontent.com/1244701/36815630-fcedd3c0-1ce3-11e8-8173-2caccbfefb17.png)

**Comment by teosarca** [comment]
note to IT:
atm there is nothing to test. It will be tested when we will have some REST API to test with.

**Comment by metas-rc** [comment]
Nothing to test. moving to done.
