### ISSUE TITLE
Make shipment line attribute set instance (ASI) configurable

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3590]
### Is this a bug or feature request?
FR 
follow-up to issue https://github.com/metasfresh/metasfresh/issues/3575 make shipment HU aggregation configurable

### What is the current behavior?

Currently, when creating a shipment line from an order line, the shipment line's ASI as a copy of the order line's ASI

### What is the expected or desired behavior?

We should be able to use the config window added in issue https://github.com/metasfresh/metasfresh/issues/3575 to also configure what shall and shall not be part of the shipment line's ASI. 
E.g. `in addition` to the order line's ASI, we might want to have the HU's country's of origin, to end up in the shipment lines' ASIs.

**Comment by metas-ts** [comment]
IT: please look at the PR #3589 for details

**Comment by metas-ts** [comment]
hi @metas-rc when you continue tesing this, pls make sure the jaspers also still look ok

**Comment by metas-rc** [comment]
Resulta of IT2 

Tested on webui

This problem persists: 
> NOK: I had 2 attributes marked as active and "Nur falls in ref. Datensatz" but only one of them had a value in orderline. The HU had values for both of them. The shipment line contained them both!

**Comment by metas-rc** [comment]
Please, test together with https://github.com/metasfresh/metasfresh/issues/3575

**Comment by metas-rc** [comment]
Results of IT

Tested on webui, swing

Problem still persists.

**Comment by metas-rc** [comment]
Results of IT


OK !

Check https://github.com/metasfresh/metasfresh/issues/3575
