### ISSUE TITLE
Add translations for headers in shipment statistics

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3591]
### Is this a bug or feature request?
FR
### What is the current behavior?
Headers in shipment statistics are currently mix of de & en.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Pls add translations for the headers where missing.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


English version: 

![image](https://user-images.githubusercontent.com/16001442/37330126-bedf0efe-26a8-11e8-96b8-95ef0cbf8720.png)


* OK : Most of the fields are translated in English
* NOK: The name of the window is not translated in English
*NOK  One field (Produkt value) is not in English
* Open: Maybe we shall name the Productname field "Product Name".

OK: The window is fully translated into German

**Comment by metas-lc** [comment]
IT
name of the window is still not translated in EN (Liefer Statistik) NOK
Product Value OK
Product Name OK

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: Now all the fields are translated in both German and English
