### ISSUE TITLE
Add invoice related virtual columns in Shipment Restrictions

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3592]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* 2 virtual columns related with invoce are needed in the Shipment Restriction
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
- [ ]  add virtual column c_invoice_id to window shipment restriction
- [ ]  add virtual column ispaid to window shipment restriction
- [ ]  make both column search fields

**Comment by metas-lc** [comment]
IT
1. created/processed dunning candidates
2. create a new Shipment Restrictions, set dunning doc table and record (record from database)
3. had to do cache reset 
=> invoice is set, paid on N OK
4. pay the invoice
5. had to do cache reset
=> paid on Y OK

follow-up for cache reset issue: https://github.com/metasfresh/metasfresh-webui-api/issues/891
