### ISSUE TITLE
Tax Error on w101 Sales Order Batch entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3595]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently (since last rollout on w101) a tax error occurs when recording sales orderlines.
#### Which are the steps to reproduce?
Open, try and see https://w101.metasfresh.com:8443/window/143/1000514
### What is the expected or desired behavior?
Shall work.

![image](https://user-images.githubusercontent.com/13365687/36847162-ac3de9b8-1d5d-11e8-985a-d53c1c328005.png)

**Comment by teosarca** [comment]
note to IT: it was a config issue, but i've improved the error reporting, i.e.
* in exceptionAttributes you can see what params were used and also what SQL query was executed to fetch the C_TaxCategory_ID
* error message is a bit elaborated, you can always see from/to bill/ship addresses or countries

![image](https://user-images.githubusercontent.com/1244701/36851370-bc91511a-1d71-11e8-93dc-1cccd8708b62.png)

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* Added a product to a German- EUR pricelist but I didn't set a correct, German tax category for it
* Added this product in a sales order line
* => I got the error message
``` 
Error: Could not find tax...
Server error
Could not find tax - Tax Category:Reduzierter Satz Waren/ DL, Sales Transaction:Yes, Organisation:metasfresh AG, ShipFrom:Deutschland, BillDate:2018-03-05, Invoice To:teststraße 996, 45678 teststadt 3
```

**Comment by rmandia** [comment]
Have the same error message when adding Purchase Order Line. Tax Category, Tax Rates, and Price Lists are set properly but still get the same "tax not found" message

**Comment by teosarca** [comment]
@rmandia  answered on https://github.com/metasfresh/metasfresh/issues/7096
