### ISSUE TITLE
Pharma: Use IFA category when importing IFA products

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3599]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
In order that category to work, we need the next product categories to exists:
* 00 Pharmazeutische Spezialitäten, human
* 01 Pharmazeutische Spezialitäten, veterinär
* 02 Homöopathie und Biologie
* 03 Diätetika, Kindernahrung
* 04 Verbandst., Krankenpfl., Hygiene, Med.prod.
* 05 Drogen, Vegetabilien, Chemikalien, Galenika
* 06 Pflegendes drogistisches Sortiment
* 07 Technisches drogistisches Sortiment
* 08 Randsortiment
*55 Hilfstaxeartikel

**Comment by metas-lc** [comment]
was tested in https://github.com/metasfresh/metasfresh/issues/3748
