### ISSUE TITLE
Provide AD_Window_ID to running process

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3604]
### Is this a bug or feature request?
FR
### What is the current behavior?
currently the `doIt()` method of a process can't find out from which AD_Window_ID (if any) it was run..at least not unless the process extends ViewBasedProcessTemplate

### What is the expected or desired behavior?

the AD_Window_ID shall be part of the ProcessInfo.
It shall also be stored in the respective AD_Pinstance record

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* AD_Window_ID now included in AD_Pinstance: OK
checked with metas-ts: nothing else to IT
