### ISSUE TITLE
Default Product Window take out Pharma specific fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3609]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are some Pharma specific fields in default product window in webui.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Take out the pharma-specific fields (they are already included in special Product Pharma window).

![image](https://user-images.githubusercontent.com/13365687/36934433-9a7707ea-1ee9-11e8-9067-f8dacd7a834c.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The Pharma specific fields are no longer displayed in the Product window.

* I found some fields in the Product window that are not translated into English. Followup created: https://github.com/metasfresh/metasfresh/issues/3613
