### ISSUE TITLE
Add "technical note" field to AD_Column

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3618]
### Is this a bug or feature request?
FR

Goal: have a field where we can add details about non-obvious choices like
* why did we make this AD_Client_ID column updatable
* why is change log disabled
* is there some DB trigger or contraint acciciated with this column
* ...

**Comment by metas-rc** [comment]
Results of IT

Tested on swing and webui


* OK: The Technical Note column added to AD_Column and field added in Table And Column window.
* NOK: The window Table and Column is not webui conforming. This task has to be done first: https://github.com/metasfresh/metasfresh/issues/3312
