### ISSUE TITLE
Spring model interceptors: support those who implement IModelInterceptor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3620]
### Is this a bug or feature request?
FR

### What is the current behavior?
At the moment only those interceptors which are annotated with `@Interceptor` are discovered.

### What is the expected or desired behavior?
Also discover those which implement `IModelInterceptor` interface.

### Note to IT
nothing to test

**Comment by metas-rc** [comment]
Nothing to IT. Moving to done
