### ISSUE TITLE
Allow semikolon delimiter for Import Format

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3621]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the semicolon is not allowed as a delimiter for Import Formats.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow the semicolon.

**Comment by metas-rc** [comment]
Note: I think this task was not rolled out
I wasn't able to find even the new element in the list. I will keep it on myself until the next rollout

**Comment by metas-rc** [comment]
Results of IT

Tested on webui + swing

* NOK: The window Import Loader Format is not fit for webui. Followup created: https://github.com/metasfresh/metasfresh/issues/3640

* OK: The semicolon option exists in the Format list for the Import Loader Format
* OK: I was able to import a csv file that had semicolon as separator.
* OK: The products I added were inserted correctly in the db.
