### ISSUE TITLE
Make AD_EventLog available for admin

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3622]
### Is this a bug or feature request?
FR
### What is the current behavior?

Currently, eventlog records are stored with AD_Client_ID=0 and AD_Org_ID=0
That means that a "normal" admin can't see them.

Also, if there is an exception, the AD_Issue is stored with the "correct" client and org ID of the exception's context. That means, that "System Admin" can see the respective event log entries, but can's zoom to the AD_Issue

### What is the expected or desired behavior?

event log records should have the AD_Client_ID and AD_Org_ID of the records that are processed withing the event handling code.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: I was able to see the data in the Event Log window while connected as Admin;
* NOK: The window is not available in the menu. I had to manually introduce the window id in the URL so I can access it. Followup created: https://github.com/metasfresh/metasfresh/issues/3642
