### ISSUE TITLE
Fix de.metas.vertical.pharma.vendor.gateway.mvs3 project name

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3627]
it shall be MSV3 instead of MVS3.

check project name, launcher, java package names etc.

**Comment by teosarca** [comment]
note to IT: just check if the available qtys are still displayed in `Create purchase order` modal view. see https://github.com/metasfresh/metasfresh/issues/3353

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


OK: The qtys are displayed in the Create Purchase Order modal view. 
Check IT from https://github.com/metasfresh/metasfresh-webui-frontend/issues/1637

I found a bug in the process itself. Followup created: https://github.com/metasfresh/metasfresh/issues/3686
