### ISSUE TITLE
Fix de.metas.vertical.pharma.vendor.gateway.mvs3 entity type

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3628]
Rename it to de.metas.vertical.pharma.vendor.gateway.msv3.
Make sure the model generate launcher still works.

Follow-up of: https://github.com/metasfresh/metasfresh/issues/3627

**Comment by metas-rc** [comment]
See IT from https://github.com/metasfresh/metasfresh/issues/3627
