### ISSUE TITLE
Standalone Product Translation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3637]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Translation Subtabs are not shown in Product Windows. Further, it's not very efficient needing to open the Product Main View first to the be able to select the translation subtab and advanced edit before one is able to add the translation.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new window for product translations. The window shall be available from product window as document reference filter. it shall also be available in WebUI menu. This way the user can also call the window via the menu and do all the translations at once, or filter by language.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/3241

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new standalone window for product translation: OK
* available from WebUI window: OK
* translation is correctly displayed in Jasper report when bpartner has the resp. language set: OK
* newly created  products have entries in the window: OK

* window shall be available from product window as document reference filter: not yet possible, => #3241
* some products have 6 translations (en_US, en_GB, de_CH, it_CH, fr_CH, dutch_NL), while others have only 3 (en_US, de_CH &  dutch_NL), why?

**Comment by metas-mk** [comment]
@metas-dh 
> window shall be available from product window as document reference filter: not yet possible

is fixed in last PR

> some products have 6 translations (en_US, en_GB, de_CH, it_CH, fr_CH, dutch_NL), while others have only 3 (en_US, de_CH & dutch_NL), why?

that's not an issue of this task. Probably we have to delete the language entries that are not needed.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* window shall be available from product window as document reference filter: works fine now, OK

> that's not an issue of this task. Probably we have to delete the language entries that are not needed.

thanks, closing this one then.
