### ISSUE TITLE
Material dispo - problem with multiple cost collectors

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3639]
### Is this a bug or feature request?
Bug
### What is the current behavior?

If you e.g. receice multiple HUs from one PP_Order, then material dispo doesn't distinguish properly between them and doesn't correctly update the actual qunatity in material dispo

#### Which are the steps to reproduce?

* make a sales order that results in material dispo creating a PP_Order
* receive two HUs
* => only the last HU's qty is show in material dispo

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

material dispo shows correct overall qty for production after receiving >1 HUs: OK
