### ISSUE TITLE
"No Selection" error when generating shipments

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3644]
### Is this a bug or feature request?
Bug
### What is the current behavior?

* do yome filtering in the shipment schedule (Liefer dispo) window, but don't select an records
  * the "Auswahl liefern"/"Generate Shipments" aktion is available
* try to run the action
  * "Error: NoSelection.."

### What is the expected or desired behavior?

if no records are selected, then don't provide this action

**Comment by metas-ts** [comment]
implemented in the `release` branch, merged to `2018-12` and `master`

**Comment by metas-lc** [comment]
IT
if no records are selected, then don't provide this action OK
but if a line is processed you can still run Generate Shipments NOK

**Comment by metas-rc** [comment]
Resulta of IT:

Tested on webui:

* OK: If I only use a filter but do not select any schedule, the " generate shipments action is not available:
* OK: If I select a line that is processed, the action is not available.
* OK: If I select a line that is not processed, the action is available.
* OK: If I select multiple lines that are processed the action is available.
* OK: If I select multiple lines that are not processed, the action is not available.
* OK: If I select both processed and not processed lines, the action is available.
