### ISSUE TITLE
Rewrite the CalloutInventory to fit webui

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3656]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, I get a NPE when trying to insert a product or the locator in an inventory line in webui. The reason is that this callout org.compiere.model.CalloutInventory is not webui friendly.
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Please, rewrite the org.compiere.model.CalloutInventory so it fits webui.

**Comment by teosarca** [comment]
should be fixed in https://github.com/metasfresh/metasfresh/issues/2647

see https://github.com/metasfresh/metasfresh/commit/f4872465dd8bcc0e32c495a61633e2c5a93b3ff0
