### ISSUE TITLE
Introduce specific subtypes for Physical Inventory and for Internal Use Inventory

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3658]
### Is this a bug or feature request?
FR 
follow-up of https://github.com/metasfresh/metasfresh/issues/2647

### What is the current behavior?
there are no specifc types to differentiate those 2 types of M_Inventory docs.

### What is the expected or desired behavior?
* have different subtypes in C_DocType.DocSubType
* check/fix tab where clauses for those 2 windows to filter based on DocSubType and not on some weird things like  `(SELECT COUNT(*) FROM M_InventoryLine WHERE M_InventoryLine.M_Inventory_ID = M_Inventory.M_Inventory_ID) = 0 OR (SELECT COUNT(*) FROM M_InventoryLine WHERE M_InventoryLine.M_Inventory_ID = M_Inventory.M_Inventory_ID AND M_InventoryLine.QtyInternalUse <> 0) > 0`
* M_Inventory.C_DocType_ID: override it's AD_Val_Rule_ID on window level. In one window (AD_Window_ID=168) we shall display the Physical Inventory doc types, in the other window (AD_Window_ID=341) we shall display the Internal Use Inventory doc types
* migrate existing Inventory doc types and the the right DocSubType for them

**Comment by metas-rc** [comment]
I talked about this task with Teo. 
We already have a docSubType that I made for the garbage. It is called "MD_Material Disposal".
Teo advised it would be ok to not add a new one for the physical inventory, but just rename the "MD_Material Disposal" to something more inclusive, like Material Internal Use.
@metas-mk : Do you think this would be ok?

**Comment by metas-rc** [comment]
PR: https://github.com/metasfresh/metasfresh/pull/3672

**Comment by metas-lc** [comment]
1. Internal Use - Entsorgung - only doctype
2. Physical Inventory - Inventur - only doctype
3. create one of each document 
=> both are saved OK
=> Entsorgung is visible only in Internal Use window OK
=> Inventur is visible only in Physical Inventory OK
