### ISSUE TITLE
Refactor/adapt Inventory Disposal

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3659]
### Is this a bug or feature request?
follow-up of https://github.com/metasfresh/metasfresh/issues/2647

### What is the expected or desired behavior?
Check de.metas.handlingunits.inventory.impl.InventoryAllocationDestination.
Don't use
* de.metas.handlingunits.inventory.IHUInventoryBL.assignHU(I_M_InventoryLine, I_M_HU)
* de.metas.handlingunits.inventory.IHUInventoryBL.getAssignedTopLevelHUs(I_M_InventoryLine)
* de.metas.handlingunits.inventory.IHUInventoryBL.getAssignedTopLevelHUsByInventoryId(int)

But instead, use M_InventoryLine.M_HU_ID. Yes, now we create one inventory line for each HU.

Consider dropping those methods.

### Note to IT
Regression. Make sure the the Inventory disposal works as before.
See tasks:
* https://github.com/metasfresh/metasfresh/issues/1064
* https://github.com/metasfresh/metasfresh/issues/1604
* https://github.com/metasfresh/metasfresh/issues/3232

**Comment by teosarca** [comment]
also pls fix de.metas.handlingunits.inventory.impl.HUInternalUseInventoryProducerTests.test()

**Comment by metas-rc** [comment]
OK

**Comment by metas-rc** [comment]
Update: This has to be changed, too: m_inventoryline_productlocattr

![image](https://user-images.githubusercontent.com/16001442/37294377-5a166b32-261e-11e8-9bac-c3d41f149b64.png)

**Comment by teosarca** [comment]
@metas-rc agree, we need the M_HU_ID too

**Comment by metas-rc** [comment]
Note to IT: 

In case your Product Planning has OnMaterialReceiptWithDestWarehouse = M_CreateMovement, make sure you add a line in the Network Distribution also for moving from LocatorDest to Garbage. Because when we do material disposales, we only throw away the products (CUs)  but the boxes are transfered to an empties warehouse.
Not that the netweork distribution shall have the flag "onHUDestroyed".

**Comment by metas-rc** [comment]
PR: https://github.com/metasfresh/metasfresh/pull/3672

**Comment by metas-lc** [comment]
IT
Regression: 
https://github.com/metasfresh/metasfresh/issues/1064 is OK
https://github.com/metasfresh/metasfresh/issues/3232 OK
https://github.com/metasfresh/metasfresh/issues/1604 OK (note that we don't get ICs for disposals - wanted)
