### ISSUE TITLE
WebUI: Add translation for upload notification

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3664]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the translations for the upload notifications are missing.
#### Which are the steps to reproduce?
Open, try and see to upload an attachment.
### What is the expected or desired behavior?
Add translations to the upload notifications.
window.attachment.title.pending "Files pending"
window.attachment.title.done "Files done"
window.attachment.title.error "Files error"

**Comment by metas-lc** [comment]
IT
1. imported attachments while being logged in in de_DE:

Dateien in Verarbeitung
Datei hochladen

Dateien hochgeladen
Dateiupload war erfolgreich

Dateien Fehler
Fehler beim Dateiupload
OK

2. imported attachments while being logged in in en_US:
Files pending
Uploading file

Files uploaded
File upload succeeded

Files error
File upload error
OK
