### ISSUE TITLE
Material Dispo missing Sales Order for Manufacturing Type

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3665]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when creating a Sales Order for Product that shall be manufactured, then the Material Dispo for the manufacturing step "Supply" does not have the sales order set. In this case, it's not shown when using referenced documents for sales order to material dispo.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Sales Order to Material Dispo entry "Supply" of manufacturing.

**Comment by metas-ts** [comment]
the problem occured when the sales order has an ASI, and the PP_Product_Plan didn't have one.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

add Sales Order to Material Dispo entry "Supply" of manufacturing:
* sales order included in Material Dispo entry "Supply" when no asi set: OK
* sales order included in Material Dispo entry "Supply" when asi set: OK
* all entries from Material Dispo regarding production included in referenced docs in the sales order: OK
