### ISSUE TITLE
Manufacturing Order wrong TU Quantity

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3666]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When a manufacturing Order is automatically created after Sales order complete, then it happens that the TU Qty in manufacturing Order is not the same as in Sales Order.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The TU Qty in manufacturing Order shall be the same as in Sales Order. Hint: The CU Qty is correct.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

sales order w/ 2 orderlines, same product, 1 w/ asi, 1 w/o asi:
* orderline w/ asi: manufacturing order automatically created: correct qty TU, correct qty CU: OK
* orderline w/o asi: manufacturing order automatically created: qty > 4000, only 30 PCE ordered:
=> PP_Order is created w/ qty considered as needed overall, not necessarily for only the qty in the orderline, but this needs fixing in general acc. to metas-ts => shall be done in https://github.com/metasfresh/metasfresh-webui-api/issues/863
