### ISSUE TITLE
prospect is converted to customer when completing a quotation

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3667]
### Is this a bug or feature request?
FR

### What is the current behavior?
when you got a partner with isprospect = Y and customer = N
and complete a quotation then automatically its becoming  isprospect = N and iscustomer =Y 

### What is the expected or desired behavior?
apply that logic only on sales order

**Comment by metas-ts** [comment]
The problem happens in `/de.metas.swat.base/src/main/java/de/metas/adempiere/modelvalidator/Order.java`

**Comment by metas-ts** [comment]
:cherries: to `release`

**Comment by metas-lc** [comment]
1. create a quotation for a bpartner that has isprospect = Y and iscustomer = N
=>  isprospect and iscustomer did not change OK
(isprospect is not displayed, and you cannot create a sales order with a bpartner that has iscustomer = N)
2. create a prospect for a bpartner that has isprospect = Y and iscustomer = N
=>  isprospect and iscustomer did not change OK
3. create a sales order for a bpartner that has isprospect = Y and iscustomer = N
=>  isprospect and iscustomer changed:  isprospect  = 'N' iscustomer  = 'Y' and OK

Regression:
1. Create a purchase order for a bpartner that has isprospect = Y and iscustomer = N
=>  isprospect and iscustomer did not change OK
