### ISSUE TITLE
Introducing master documentno to give each contract chain a unique number

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3675]
### Is this a bug or feature request?
FR

### What is the current behavior?
we have a documentno but that is per contract period

### What is the expected or desired behavior?
have a documentno that identifies the complete chain of periods

**Comment by metasnw** [comment]
conceptual question:
what do we do if a contract consists of several products and conditions?
is the number per chain (flatrate term + product => next flatrate term, etc.) or for the whole set ?

**Comment by metas-ts** [comment]
depends..

# if i just take the question at face level i would say:

Maybe we should not call it documentno, but "contractno" or even "groupno"
and if it's called contractno" or "groupno", and we could also group together C_FlatrateTerm with different products..

..and leave DocumentNo to be the same this that also C_Order and C_Invoice have

# buut, i could also say that 

such a thing (i.e. contract with many products) doesn't currently exist, so why talk about it ;-)
For starters, how would we specify which products belong together? 
Something like a bom? 
Or can we build on that new grouping we have in sales orders?
Or on that campaing thingie (buy two "A" and get one "B" for free) the we used some years ago?

**Comment by cristinamghita** [comment]
MasterDocumentNo is filled up by default with DocumentNo.
If the contract is extended, next contract will inherit the MasterDocumentNo of the ancestor.
See screenshot.
![image](https://user-images.githubusercontent.com/15378036/38142842-a578deda-3446-11e8-8925-b193b1efe12a.png)

**Comment by metas-lc** [comment]
IT
1. have  different contract terms and transitions, 
e.g. term1 -> trans1 -> term2 -> trans2 -> term3 -> trans3 -> term4 -> trans4 -> term5 -> trans5
2. create an order with 1 product, condition term1, complete 
=>you'll get 5 contracts like 10000001->10000005, master documentno = 10000001 OK
3. create a new order, different bpartner, 2 products, condition term2 and condition term3
=> you'll get 4+3 contracts like 10000006->10000010, 1000011->1000014, master documentno = 10000006 and 10000011 OK
4. create a new order with a simple contract, that does not extend
=> you'll get only 1 contract, docno 1000015 master documentno = 1000015 OK
