### ISSUE TITLE
Replace flags from tax category with a list

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3687]
### Is this a bug or feature request?
FR
### What is the current behavior?
In C_TaxCategory we have now 3 flags:
* IsDefault
* IsReduced
* IsWithout
### What is the expected or desired behavior?
Those 3 flags should be replaced by a column called VATType with next values:
* N: Regular VAT
* R: Reduced VAT
* E: Tax Exempt

**Comment by cristinamghita** [comment]
Follow up for [#3645 Pharma: Import standard prices ](https://github.com/metasfresh/metasfresh/issues/3645)

**Comment by metas-lc** [comment]
IT
checked tasx category window => there is a new field MwSt-Typ which has all 3 values:
     Regular VAT
     Reduced VAT
     Tax Exempt
OK
