### ISSUE TITLE
Port Printing REST endpoint from servicemix to metasfresh

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3688]
### Is this a bug or feature request?

FR

### What is the current behavior?

In order to do "mass-printing" with the printing client, we need to set up a legacy servicemix and deploy a bundle. That bundle open a rest endpoint and basically forwards everything to the metasfresh replication interface.

### What is the expected or desired behavior?

metasfresh should open basically the same endpoint, bypassing both servicemix and the replication interface.
in the client, we can add an additional API-token to the configfile, to authenticate.

**Comment by metas-dh** [comment]
Update:
did not work on customer server, probably bc of Java problem.
