### ISSUE TITLE
Restore swing MRP ProductInfo

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3690]
### Is this a bug or feature request?
Bug
### What is the current behavior?
![image](https://user-images.githubusercontent.com/1264789/37403845-6f426a92-2790-11e8-9a22-d5b48dc9e3f4.png)

As far as i can tell, if got accidentally deleted here: 4b8a30ee97425fc6aca303d00c11150d1a027e4c
(or even earlier?)

**Comment by metas-ts** [comment]
implemented in branch `2018-12`, merged to `master`

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* MRP PRoduct Info opening and working fine again (correct qties, filtering etc.): OK
