### ISSUE TITLE
docs_flatrate_term_all_procurements_conditions_report fails if M_Product_ID is left empty

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3694]
### Is this a bug or feature request?
bug 
### What is the current behavior?

```
There was an unexpected error (type=Internal Server Error, status=500).
@NotFound@: M_Product_ID Expressions trace: * SELECT * FROM de_metas_procurement.docs_flatrate_term_all_procurements_conditions_report(@C_BPartner_ID/NULL@,@M_Product_ID/NULL@); Partial evaluated expression: SELECT * FROM de_metas_procurement.docs_flatrate_term_all_procurements_conditions_report(2000511,
```

#### Which are the steps to reproduce?

Try to run the `Anbauplanung Auswertung Excel (Jasper)` report, leving the product empty

**Comment by metas-ts** [comment]
fix implemented in branch `2018-12`, merged to `master`

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* ```Anbauplanung Auswertung Excel (Jasper)``` running with product left empty: OK, no error
