### ISSUE TITLE
Jasper: ADR Auswertung report has duplicates

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3701]
### Is this a bug or feature request?
bug
### What is the current behavior?
ADR Auswertung report has duplicates
#### Which are the steps to reproduce?
have same product for different orgs. Must  have bpartner product, with productcategory on 1 org
### What is the expected or desired behavior?
shall not see duplicates

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

Have same product for different orgs. Must have bpartner product, with productcategory on 1 org:
=> ADR Auswertung shows no duplicates: OK

**Comment by metas-lc** [comment]
taking it back because there is another issue, with bpartner product that had org id 0

**Comment by metas-dh** [comment]
Results of IT2
tested in customer db

=>  newly created invoice, with AdR, product category set for bpartner, ord_id= 0
* product category shown inj asper report (params: dates, sales transaction & bpartner): OK
* no product category shown in jasper report, if bpartner param is left empty: NOK

**Comment by metas-lc** [comment]
closing it because i realised it really needs to set a bpartner to be able to see the cat.
