### ISSUE TITLE
Material Receipt Candidates Window, add media types for mobile/ tablet

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3703]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window Material Receipt Candidates is showing all columns no matter what media size it is shown on.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Reduce the number of columns in material Receipt Candidate window for media size mobile and tablet.

**Comment by metas-mk** [comment]
Done
![image](https://user-images.githubusercontent.com/13365687/37474670-3776ead4-2871-11e8-802d-50cb06b85cc9.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / w101

material receipt candidates:
* shows all columns on PC screen, but Attributes, Qty Ordered TU, Moved TU Qty & Packings Description have restrictToMediaTypes: ["screen"]: OK (mf15)
* shows less columns on tablet screen, the columns mentioned above are not displayed, after column Product, Ordered Quantity is displayed: OK (w101)
