### ISSUE TITLE
Inventory Window show Handling Unit Field in Inventorylines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3705]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Field Handling Unit is not shown in Inventory Lines.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Field Handling Unit to Inventory Lines in WebUI.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* inventory window: inventory lines include Handling Unit field: OK
