### ISSUE TITLE
Terminating a Contract that was extended ahead of schedule leaves stumb

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3706]
### Is this a bug or feature request?
FR

### What is the current behavior?
1. contract term period 1
  01.01.2018 - 31.12.2018
1. contract term period 2
  01.01.2019 - 31.12.2019
1. todays date: 01.12.2018
1. terminating contract with effective enddate: 31.12.2018
1. NOK: period 2 looks like:
  01.01.2019 - 01.01.2019

Although contract ended until 31.12. the stumb is adding an extra day to the contract
  
### What is the expected or desired behavior?
If enddate is befofre startdate system should void the period

**Comment by cristinamghita** [comment]
@metas-dh The date is still the same, but the status is **Voided** and that means that we dot care'of the date.

**Comment by metas-dh** [comment]
@cristinamghita thx, i thought the date was relevant too. moving this to Done then.
