### ISSUE TITLE
Send Mail too when notification

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3708]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user can receive Notifications in webui.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Provide a possibility to also receive eMails for Notifications in parallel.

After discussion w/ @teosarca 
- New Structure "Notification group"
- Mail Template
- User Settings for Notification groups

**Comment by teosarca** [comment]
SQL script to generate AD_User_NotificationGroup records:
```sql
INSERT INTO public.ad_user_notificationgroup
(
            ad_user_notificationgroup_id,
            ad_user_id, 
            ad_notificationgroup_id,
            NotificationType, 
            ad_client_id, ad_org_id, isactive, created, createdby, updated, updatedby
)
select
	nextval('ad_user_notificationgroup_seq'),
	u.AD_User_ID,
	ng.AD_NotificationGroup_ID,
	u.NotificationType,
	u.AD_Client_ID, u.AD_Org_ID, 'Y', now(), 0, now(), 0
from AD_User u, AD_NotificationGroup ng
where
	u.IsActive='Y' and u.IsSystemUser='Y'
	and ng.IsActive='Y'
	and not exists (select 1 from ad_user_notificationgroup z where z.AD_User_ID=u.AD_User_ID and z.AD_NotificationGroup_ID=ng.AD_NotificationGroup_ID)
	and u.AD_User_ID in (2188223) -- restrict to some users
```

**Comment by teosarca** [comment]
### Configuration
![image](https://user-images.githubusercontent.com/1244701/38375699-7d495738-38ff-11e8-9708-c0d933c639b5.png)

Fallback:
![image](https://user-images.githubusercontent.com/1244701/38375782-a7c72396-38ff-11e8-9c7a-1ca18f51f082.png)

**Comment by teosarca** [comment]
### note to IT:
regression on:
* async batch notifications - i think @cristinamghita  or @metasnw  know better this functionality
* printing notifications / mfg warehouse report printing notification
* shipment/receipt/returns generated notifications
* invoice generated notifications
* Data Import
* Async error notification (triggered by generate shipment from HU, generate purchase orders from sales order, generate GO delivery order)
* BPartner credit limit approval
* Data import results
* Inventory generated (try move to garbage)
* Procurement (try generating purchase orders from PMM_PurchaseCandidates)

**Comment by metas-dh** [comment]
not included in master, pls test with the latest "gh3708" build in dedicated testing environment!

**Comment by metasnw** [comment]
@teosarca is the mail feature of the request processor also affected?
the feature where you assign a request to a user and he gets a notification (old style)

**Comment by teosarca** [comment]
@metasnw nop, requests are not affected.... but almost all others are. Mainly also which were dependent on AD_User.NotificationType.

**Comment by metas-dh** [comment]
Results of IT1
tested in dev20

Set Email+Notification or Email in My Profile for my test user, tested: the following notification groups:
1. Async - Processing errors: Email + Notification:
* caused async error for workpackageprocessor  "de.metas.handlingunits.shipmentschedule.async.GenerateInOutFromShipmentSchedules": got no email or notification
2. Billing: Email + Notification:
* received email & notification for sales & purchase invoice: OK
3. BPartner - Credit Limit Approval: Email + Notification: ran credit approval action, but got no email or notification (only got that little "process successful" window)
4. Data Import - Results: Email + Notification: 
* created product import, but got no email or notification (only got that little "process successful" window)
5. Material Inventory: Email + Notification:
* created physical inventory data, but got no email or notification 
6. Material Movement: Email + Notification:
* created product movements using distribution editor, but got no email or notification 
* received email & notification for disposal: OK (i think this belongs here, or is it inventory?)
7. Material Shipment/Receipt/Returns: Email + Notification:
* received email & notification for shipment: OK
* received email & notification for material receipt: OK
* got no email or notification for empties return
8. Orders (Sales/Purchase): Email:
* received email (no notification) for purchase order created from purchase disposition: OK
* received no email for purchase order created from sales order

**Comment by metas-dh** [comment]
=> all emails i got were in german, even when i had the user language set to en_US (and the notifications were in english as well): not sure this is OK? or do we not have en_US texts yet?

**Comment by teosarca** [comment]
@metas-mk  @metas-dh  if the issues found here are not critical, i would suggest to do one task for each of them. wdyt?

**Comment by teosarca** [comment]
update: fixed 

> => all emails i got were in german, even when i had the user language set to en_US (and the notifications were in english as well): not sure this is OK? or do we not have en_US texts yet?

**Comment by metas-ts** [comment]
hi @metas-dh , did you check if umlauts etc were shown correctly, both in the mail subject and text?

**Comment by metas-ts** [comment]
> @metas-mk @metas-dh if the issues found here are not critical, i would suggest to do one task for each of them. wdyt?

I suggest not to have follow-up tasks, but to finish everthing in this task. Maybe someone else (e.g. I) could take over the task for that purpose.

**Comment by metas-dh** [comment]
>  did you check if umlauts etc were shown correctly, both in the mail subject and text?

yes, they were fine.

**Comment by metas-dh** [comment]
checked with metas-mk: 
* the one case that has to work is email & notification for BPartner - Credit Limit Approval, we can do follow-ups for the rest
* tested BPartner - Credit Limit Approval again, for a new bpartner: got notification "Approve credit limit", but no email: NOK

**Comment by metas-dh** [comment]
1. Async - Processing errors: Email + Notification:
   * caused async error for workpackageprocessor "de.metas.handlingunits.shipmentschedule.async.GenerateInOutFromShipmentSchedules" (tried to create shipment with "Use PickedQty:Y" for 2 shipment schedules, with 1 having no QtyPicked): got no email or notification: NOK => #4229
4. Data Import - Results: Email + Notification:
   * created product import: got email & notification: OK
5. Material Inventory: Email + Notification:
   * created physical inventory data, but got no email or notification: ?
6. Material Movement: Email + Notification:
   * created product movements using distribution editor
7. Returns: Email + Notification:
   * got no email or notification for empties return: NOK i think

**Comment by teosarca** [comment]
@metas-dh  i suggest to split out pending stuff. we can distribute them among the team.

**Comment by metas-dh** [comment]
checked with metas-mk: => we will create the follow up tasks when needed in the future, atm it's ok as it is with the email & notification working fine for credit limit approval.
