### ISSUE TITLE
Contracts: Detect loops when extending a contract 

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3711]
### Is this a bug or feature request?
FR 
follow up to https://github.com/metasfresh/metasfresh/issues/3669

**Comment by cristinamghita** [comment]
Follow up [#3669 Create all periods of a contract on creation](https://github.com/metasfresh/metasfresh/issues/3669)

**Comment by cristinamghita** [comment]
## Rough concept
* Create a unit test that catches an infinite loop
   * the unit test will have a timer and if the test it takes too much, means that is an infinite loop and will throw an exception
* Modify method de.metas.contracts.impl.FlatrateBL.extendContract(ContractExtendingRequest) to create a breadcrumb(a list) with all C_Flatrate_Conditions which gets trough.
  * when the condition is put again in the breadcrumb and Extension type is 'ExtendAll' it will mean that we are in an infinite loop and will throw an exception and rollback all

**Comment by cristinamghita** [comment]
## Dev test
### Infinite loop case
* Create 5 conditionss with 5 transitions(extension type is ExtendingAll) which points like this:
  * cond1 ->trans1->cond2
  * cond2 ->trans2->cond3
  * cond3 ->trans3->cond4
  * cond4 ->trans4->cond5
  * cond5 ->trans5->cond2
* Create a sales order using condition cond1
  * The order is not completed and we receive an error saying: **"Infinite loop detected!"**  **OK**
### ExtendAll case - regression
* Create 5 conditionss with 5 transitions(extension type is ExtendingAll) which points like this:
  * cond1 ->trans1->cond2
  * cond2 ->trans2->cond3
  * cond3 ->trans3->cond4
  * cond4 ->trans4->cond5
  * cond5 ->trans5->empty
* Create a sales order using condition cond1
  * The order is completed and we get 5 contracts
### ExtendOne case - regression
* Create 1 conditionss with 1 transitions(extension type is ExtendingOne) which points like this:
  * cond1 ->trans1->cond1
* Create a sales order using condition cond1
  * The order is completed and we get 1 contract which can be renewed automatically when the notice date is reached **OK**
### No automatic extension case - regression
* Create 1 conditions with 1 transitions(extension type is empty) which points like this:
  * cond1 ->trans1
* Create a sales order using condition cond1
  * The order is completed and we get 1 contract which is not renewed automatically **OK**
### Mix between ExtendAll and ExtendOne case - regression
* Create 5 conditionss with 5 transitions  which points like this:
  * cond1 ->trans1(extension type is ExtendingAll)->cond2
  * cond2 ->trans2(extension type is ExtendingAll)->cond3
  * cond3 ->trans3(extension type is ExtendingAll)->cond4
  * cond4 ->trans4(extension type is ExtendingAll)->cond5
  * cond5 ->trans5(extension type is ExtendingOne)->cond2
* Create a sales order using condition cond1
  * The order is completed and we get 5 contracts **OK**
* Extend the last contract
  * we get 4 new contracts **OK**

**Comment by metas-lc** [comment]
IT
repeated the testcase above:
1. infinite loop
=>
Error: Error Processing Document document: Standardauftrag...
Server error
Error Processing Document document: Standardauftrag 0029 Document Action: CO Cause: Infinite loop detected! Are you tryng to extend a contract using condition cond2, but these conditions [cond1 , cond2, cond3, cond4, cond5] already seen. (AdempiereException) 

2. trans5 having Next Contract Terms empty
=> sales order was completed correctly, 5 new contracts were created OK

3. extend one (cond1 ->trans1->cond1)
=> order completed, 1 contract created OK
