### ISSUE TITLE
swing - Bereitstellung POS hangs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3717]
### Is this a bug or feature request?
Bug
### What is the current behavior?

Here is where it hangs:
![image](https://user-images.githubusercontent.com/1264789/37587863-ca024f50-2b60-11e8-8aca-56e81ff1fced.png)

..so far I couldn't copy the stacktrace to clipboard

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

selected a HU in Bereitstellung POS, OK: took about 18 sec. until processed and you could use the window again: OK
