### ISSUE TITLE
Create Request on DD_Order to Quarantine warehouse

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#3721]
Followup for https://github.com/metasfresh/metasfresh/issues/3693
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, when 
1) some HUs are received and they have a product- lotno pair that is found in the M_Product_LotNumber_Lock
 or when 
2) the process M_Product_Locked_LotNo is called for such an entry and some HUs with the pair are found, 
=> a new DD_Order is created, for the warehouse flagged as IsQuarantine. 
Please, check https://github.com/metasfresh/metasfresh/issues/3693 to see the more detailed requirements.

#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Now, we want to also have a Request created after a DD_Order of this kind was created.
* This request will be triggered for a special person ( we will see how we will configure this. Maybe with a flag in AD_User, or in the AD_Role)
* The Invoice Candidate will also be flagged as InDispute afterwards.

**Comment by metas-rc** [comment]
There will also be a new Description field in the table Block_Product_Locked_LotNo. If filled, the text will also get to the created dd_orderLines, to explain why the products were quarantined.

**Comment by metas-rc** [comment]
Note: 
I Talked with Mark and Teo and decided to make the Sales_Rep_ID non mandatory for the Request. 
It was almost never set anyways, because it has a default value on @AD_User_ID@  but also a val rule for the user to have IsSystemUser = true. This usually doesn't happen.

**Comment by metas-rc** [comment]
Note: The R_Request.AD_User will be taken from the parent DD_Order.AD_User. It behaves the same way when creating requests from inouts with quality issues. In that case, the R_Request.AD_User = M_InOut.AD_User.

**Comment by metas-rc** [comment]
Note to IT

Please, do regression testing of movement creation after receipt.

**Comment by metas-lc** [comment]
IT
1. when you do a receipt for quarantine, besides dd order, new request is created OK
2. (regression) when you do receipt with quality issues new request is created OK
3. description from lotno lock gets to dd orderline and in reqest at summary OK
4. salesrep is not mandatory in reqest OK
5. quarantine receipts make ICs isindispute OK
