### ISSUE TITLE
Purchase order not created for purchase disposition

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3722]
### Is this a bug or feature request?
Bug
### What is the current behavior?
No purchase order is created for purchase disposition.
#### Which are the steps to reproduce?
1. Set prices for a product, for both sales & purchase side
2. Set a vendor for this product, check "current Vendor"
3. Create a sales order, create an orderline for that product
4. Select the orderline, run action "Create purchase orders": set the qty you want to order, OK => purchase disposition is created, OK
5. Complete the sales order, check purchase order:
=> none was created: NOK
6. Check the purchase dispo again: not processed, NOK
### What is the expected or desired behavior?
Purchase order shall be created for purchase disposition.

**Comment by metas-dh** [comment]
needs https://github.com/metasfresh/metasfresh-webui-frontend/issues/1703

**Comment by metas-ts** [comment]
Hi @metas-dh 
as talked yesterday: 
* i tried it and it seems to work now (also on mf15releasetest)
* the issue might have been the frontend not updating the backend about the qty to purchase, and that's why no purchase was made

**Comment by metas-dh** [comment]
@metas-ts : yes, checked as well and is now working fine again. moving this to Done, thx.
