### ISSUE TITLE
Rack system in picking not working anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3723]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Rack system functionality is not working anymore.
#### Which are the steps to reproduce?
1. Have 2 picking trays, set one Rack system=Y
2. Create sales order, add orderline w/ qty > 1 (have product you order in stock!)
3. Open picking terminal, do picking using
* the normal picking tray for some qty
* the rack system tray for the remaining qty
4. process the picking for both, and close the window
5. Open the modal window again:
=> both picking trays still show the HU picked: NOK, the HU in the rack system shall be moved out of the picking tray once processed
6. Check the picking trays you used:
=> the rack system one has no data in subtab for HU: OK
=> the normal tray shows the picked HU in subtab, OK
### What is the expected or desired behavior?
Rack system in picking shall work.

**Comment by teosarca** [comment]
@metas-dh wondering if you have something in browser console... maybe something like "deleteView is not a function ...".

**Comment by metas-dh** [comment]
@teosarca actually yes, had

```
bundle90c7f322aa636519fad0.js:135211 Uncaught (in promise) TypeError: (0 , _ViewActions.deleteView) is not a function
    at RawModal._callee$ (bundle90c7f322aa636519fad0.js:135211)
    at tryCatch (bundle90c7f322aa636519fad0.js:8211)
    at Generator.invoke [as _invoke] (bundle90c7f322aa636519fad0.js:8449)
    at Generator.prototype.(/window/anonymous function) [as next] (https://mf15cloudit/bundle90c7f322aa636519fad0.js:8263:22)
    at step (bundle90c7f322aa636519fad0.js:135079)
    at bundle90c7f322aa636519fad0.js:135079
```
in console, but got that already before i did the picking

**Comment by teosarca** [comment]
this is an frontend issue.

and yes, you got it because that feature is broken, and the racking system relies on it.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* rack system working fine again in current master, will check once more in RC and then move to done.

**Comment by metas-dh** [comment]
worked well again in RC, closing.
