### ISSUE TITLE
Cannot create material receipt if the ADR attribute is disabled in PI template 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3728]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* disable the ADR attribute in HU template
* from webui, try to receive a new HU => ERROR
![image](https://user-images.githubusercontent.com/1244701/37651148-dd2511c8-2c3f-11e8-97cf-1736da4d9a91.png)

![image](https://user-images.githubusercontent.com/1244701/37651179-f5afcb16-2c3f-11e8-8b21-ea47033e7196.png)

### What is the expected or desired behavior?
shall work

**Comment by metas-lc** [comment]
IT
0. set ADR attribute inactive for packing item template
1. have an order with a product with no ASI
2. go to receipt candidates and receive LU
=> no errors OK
=> ADR is not shown OK
3. also receive TUs and CUs
=> works the same, no errors OK
4. have an order with a product with ADR ASI
5. go to receipt candidates and receive LU
=> no errors OK
=> ADR is not shown OK
6. also receive TUs and CUs
=> works the same, no errors OK
7. set ADR attribute back to active for packing item template
8. go to receipt candidates, receive LU
=> no errors OK
=> ADR is shown and you can change it, no errors OK
