### ISSUE TITLE
Jasper: Qty TU in purchase invoice is wrong again

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3736]
### Is this a bug or feature request?
bug
reverting https://github.com/metasfresh/metasfresh/issues/3445
old issue shall be solved by https://github.com/metasfresh/metasfresh/issues/3545
### What is the current behavior?
Qty TU in purchase invoice jasper is doubled
#### Which are the steps to reproduce?
1 purchase order with 1 product
go to receipt candidates and create an inout with 2 different LUs, each having different ASI
create invoice, run jasper
=> you'll have 2 lines with wrong TU qty
### What is the expected or desired behavior?
qty TU shall be taken from invoiceline. Now is taken from inout

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* repeated testcase described above: OK

had a case of different asi combined with different TU types, qty in invoice jasper were not correct => creating a task for general improvement of qty TU calculation in invoice jasper: #3790
