### ISSUE TITLE
Toplevel TUs are created as aggregate HUs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3739]
### Is this a bug or feature request?
Bug

**Comment by metas-rc** [comment]
Results of IT


Tested on webui: 

* OK: I was able to receive HUs with TU-CU and no LU
* OK: I was able to add a new CU with other product to such a TU
* OK: I was able to pick such an H u( with only CU-TU) , I processed the picking and created a shipment for the schedue => All went fine, the H uwas correctly assigned to the document
* OK : Item type for the top level TU is transport unit (no aggregation)


Regression: adding cus with serial number also works for this kind of HU
