### ISSUE TITLE
WebUI add Warehouse PO column to Organization/Org Info window

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3740]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/3738

### Note to IT
while testing, pls also consider https://github.com/metasfresh/metasfresh-webui-api/issues/914

**Comment by metas-lc** [comment]
IT
1. open window organization
2. see organization info tab
=> grid view and advanced edit: Purchase warehouse is there OK
=> field is also trl: Bestellung Lager OK

this task is still NOK:
https://github.com/metasfresh/metasfresh-webui-api/issues/914
