### ISSUE TITLE
Translation of Distribution Editor Quickaction

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3743]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Quick action in Distribution Editor is not yet translated "Move HU"
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Please translate to de_DE.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

quick action is now called "Produkte umlagern" in de_DE (en_US is "Relocate Products"): OK
