### ISSUE TITLE
Add isPrintPrice flag in orderLine

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3749]
### Is this a bug or feature request?
fr
### What is the current behavior?
we need flag in orderline to show/hide prices
#### Which are the steps to reproduce?
-
### What is the expected or desired behavior?
we would like to have isPrintPrice flag in orderline, to be used for jasper, to show/hide prices

**Comment by metas-rc** [comment]
Results of IT

Tested in db


* OK: The column was added in the  Aplication Dictionary.
* For the actual usability of the glaf, the customer issue shall be tested on the customer database.
