### ISSUE TITLE
Inventory: Allow only "Active" and "Issued" HUs in inventorylines

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3754]
### Is this a bug or feature request?
FR
### What is the current behavior?
While testing #2647, a HU with status "Planning" was included in the inventorylines.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Allow only "Active" and "Issued" HUs in inventorylines.

**Comment by metas-dh** [comment]
Testcase:

* have HUs with status "Planning": create a purchase order, and open the  HU Editor in material receipt candidates (odon't receive anything)
* in a different window or tab, create Inventory and run the "Prepare inventorylines" action for the product you're about to receive=> HUs with status "Planning" shall not be included!

**Comment by metas-lc** [comment]
IT
repeated the testcase above. => works fine, the planned HUs are not added OK
but i had duplicates. We already have a task: https://github.com/metasfresh/metasfresh/issues/3753
