### ISSUE TITLE
Error in search of Businesspartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3755]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Search in Businesspartner throws an SQL Error
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Pls, Fix.
![image](https://user-images.githubusercontent.com/13365687/37780932-0d5c4350-2df0-11e8-8d1a-5e0b584321d2.png)

**Comment by metas-mk** [comment]
wrong:
```
(select CreditLimitIndicator from C_BPartner_Stats s where s.C_BPartner_ID = C_BPartner.C_BPartner_ID)
```

shall be:
(select MAX(CreditLimitIndicator) from C_BPartner_Stats s where s.C_BPartner_ID = C_BPartner.C_BPartner_ID)

**Comment by metas-rc** [comment]
Results of IT

Tested on wbeui


* OK: The window Business partner is usable, no errors occure when I open or when I create new entries.
*OK :All the filters work well and the right results are retrieved.
