### ISSUE TITLE
Check Limit in BPartner increases on purchase side

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#3762]
### Is this a bug or feature request?
bug
### What is the current behavior?
Check Limit in BPartner increases if you create purchase documents
#### Which are the steps to reproduce?
1. go to a bpartner and create  a credit limit, approve it
2. create /complete a purchase order
=> notice that the statistics and credit limit are increasing NOK
### What is the expected or desired behavior?
purchase side should not affect credit limit

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

* OK: Purchase order does not influence statistics

Regression

* OK: Sales order increases the number in statistics
