### ISSUE TITLE
Contracts: Create a function that provides a hierarchy of contracts

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3763]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
Created 2 sql functions:
* getInitialC_Flatrate_term_ID - returns the most distant parent of the given C_Flatrate_term_ID 
* fetchflatratetermhierarchy_byC_Flatrate_Term_id - returns the hierarchy chain of a C_Flatrate_term_ID 

Example of use:
```select * from getInitialC_Flatrate_term_ID(1000033);```
And returns:
![image](https://user-images.githubusercontent.com/15378036/37832800-58aa27f6-2eb2-11e8-91f0-a1b290b95662.png)
Wich is the initial C_Flatrate_term_ID 

```
select * from fetchflatratetermhierarchy_byC_Flatrate_Term_id(1000033);
```
And returns:
![image](https://user-images.githubusercontent.com/15378036/37832839-753947c6-2eb2-11e8-8bcd-b3df39ad1a5e.png)

**Comment by metas-lc** [comment]
IT
1. created new contract transition and contract term, type abo
2. created new sales order and added the contract in orderline
3. completed order and zoomed in to created contract
4. in contract window, on actions, selected "Extend Contract"
5. extended it for next month, complete yes
6. opened the newly created contract and extended it in the same way
7. repeated this several times, then went to database and ran both functions
e.g. 
```select * from de_metas_contracts.fetchInitialC_Flatrate_term_ID(1000001);
select * from de_metas_contracts.fetchflatratetermhierarchy_byC_Flatrate_Term_id(1000001);
results
1000001
1000001;"{1000001,1000002,1000003,1000004,1000005,NULL}"
```
```
select * from de_metas_contracts.fetchInitialC_Flatrate_term_ID(1000002);
select * from de_metas_contracts.fetchflatratetermhierarchy_byC_Flatrate_Term_id(1000002);
results
1000001
1000001;"{1000001,1000002,1000003,1000004,1000005,NULL}"
```
no matter what ID i use, i get the same results (from the IDs of extended contracts)
OK
