### ISSUE TITLE
Excel Report for vendor assessment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3768]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no report that allows gathering the needed information for a yearly vendor assessment.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a SQL and Excel Report that can be used for vendor assessment.

**Comment by metas-dh** [comment]
Results of IT1
tested in customer test db

* new report "Revenue PO Excel": OK (maybe we need a trl for de_CH?)
* SQL was already delivered to customer
* revenue sum (Umsatz Zeitperiode) & compared revenue sum (Umsatz Vergleichsperiode): was the same as in the Umsatzreport bpartner, and the revenue sum was ok (checked purchase invoice): OK
* revenue_change (Umsatz %) is SamePeriodSum*100/compperiodsum: OK
* sum of orders (Bestellungen): was OK, but the drafts were also counted, is that correct?
* sum of requests (Vorgang): checked with Lieferantenbeanstandung (order_id has to be set, grouped by r.M_Product_ID, r.M_QualityNote_ID, r.c_order_id): OK
* request sum*100/POsum (Bestellungen %): OK

**Comment by teosarca** [comment]
> only available in Swing atm, do we need a WebUI version?

the report shall be somewhere in Webui menu folder to be visible on webui.

> sum of orders (Bestellungen): was OK, but the drafts were also counted, is that correct?

IMHO it's not OK.

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* Swing menu (en_US): now correctly called "Vendor Evaluation" in main reports folder, same as the window with params in Swing: OK 
* Excel itself also called "Vendor Evaluation": OK

**Comment by metas-ts** [comment]
:cherries: picked to `2018-12`
