### ISSUE TITLE
DeliveryRule Manual does not trigger Picking when stock available

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3769]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the DeliveryRule Manual does not trigger Picking when stock available and qtytodeliver override > 0.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
closing because it's too old
