### ISSUE TITLE
EventBus shall use RabbitMQ instead of ActiveMQ

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3772]
### Is this a bug or feature request?
FR

### What is the current behavior?
The eventbus is using ActiveMQ.

### What is the expected or desired behavior?
It shall use RabbitMQ.
ActiveMQ will be deprecated. In case you still want to use it, activate `eventbus_activemq` spring profile,
i.e. add you your application.properties for app server, swing ui, webui, material dispo etc:
```
spring.profiles.active=eventbus_activemq
```

**Comment by metas-ts** [comment]
will be integrated with #4033

**Comment by metas-dh** [comment]
checked with metas-ts: working, nothing to IT.
