### ISSUE TITLE
Distribution Editor initial HU Assignment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3776]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In Distribution Editor the user always has to select the Handling Unit in action Relocate Products, although the HU has to be relocated lot-for-lot from material Receipt warehouse.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Always preset/ assign the Handling Unit in Distribution Order Relocate Products Action.

**Comment by metas-rc** [comment]
* Idea: Create M_HU_Assignment entries from DD_OrderLines.

* Note: each Hu shall lead to a new DD_OrderLine. There will not be 2 HUs for the same line

**Comment by metas-lc** [comment]
1. created a distribution order manually
2. went to distribution editor and selected my dd order, ran "relocate products"
3. there was no HU in handling units field OK
4. created a distribution order automatically, by doing quarantine: created new lotno lock and made material receipts with product and lotNo like i had in lotno lock
5. went to distribution editor and selected my dd order, ran "relocate products"
=> an HU was set there (one of those i created in step 4)
6. used "relocate products" until i finished my HUs from dd order
=> after i finished them, there was no HU set in handling units field anymore OK
