### ISSUE TITLE
Show available to promise in Procurement Dispo modal in Sales Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3777]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Stock for a Product is shown to the user in Sales Orderline Batch Entry list. As soon as the user runs the action for Procurement Dispo, there is no stock information available.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Provide the Available to promise stock in procurement dispo modal overlay.

**Comment by metas-lc** [comment]
IT
note: in case atp is negative or 0, you might not see it in batch entry. To show it, you have to set this sysconfig to N: de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.DisplayOnlyPositive

1. go to sales order and create a new one
2. write a product with batch entry (don't add it yet)
=> you'll see something like P002737_Convenience Salat 250g_1-260-1000070: -1,640 Ea  (alle)
=> atp is -1,640 Ea OK
3. select the line, go to actions and select "Create purchase orders"
=> Zusagbar (ATP) is -1,640 OK
4. go to sysconfig and update de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.AttributesKeys with something like <OTHER_STORAGE_ATTRIBUTES_KEYS>, 1000000, 1000007 (those are 2 attribute values ids: bio and inland)
5. go to sales order and create a new one. Start writing in batch entry
=> your product appears 3 times: other (10040), bio (0) and inland (0)
6. add 2 lines: other and inland, select both lines, run create purchase order
=> on both lines ATP is 10040. OK??
7.  go to sysconfig and update de.metas.ui.web.window.descriptor.sql.ProductLookupDescriptor.ATP.AttributesKeys with something like  1000000, 1000007 (those are 2 attribute values ids: bio and inland)
8.  go to sales order and create a new one. Start writing in batch entry
=> your product appears 2 times: bio (0) and inland (0)
9. add 1 line, select it, run create purchase order
=> ATP is 0. OK
10. make some inouts with bio, repeat steps 8 and 9
=> your product appears 2 times: bio (10) and inland (0) OK
=> => ATP is 10 for both inland and bio in "create purchase order" . OK??

**Comment by metas-lc** [comment]
for step 10 in IT
we need: to show the atp / asi
and to show attribute field so we know why

**Comment by metas-lc** [comment]
IT
new field "Attributes" in Create purchase orders
repeated the testcase above
step 6 => in create purchase order had 3 lines, ATP e.g. 10040 for all (no attributes set), other 2 lines qty 0, attributes bio and inland OK
step 10 =>  i'll postpone this a bit, since i don't get to have qty for bio...
