### ISSUE TITLE
Standalone BPartner Product Translation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3784]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Translation Subtabs are not shown in Product Windows. 
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new window for businesspartner product translations. The window shall be available from product window as document reference filter. it shall also be available in WebUI menu. This way the user can also call the window via the menu and do all the translations at once, or filter by language.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The window Product Translation was added in the menu
* OK: The window Product translation opens correctly ( => the composed primary key is ok)
* OK: The window is editable and the changes save correctly.
* OK: The window is accessible from the window Product, if I click on the references.
* OK : WIndow respects layout conventions
*OK: Window translated in both English and German


* NOK: If I click on the references button, I get an error like this: 

![image](https://user-images.githubusercontent.com/16001442/38201170-f4071db8-369f-11e8-96b0-e55148b3bca7.png)

Followup created: https://github.com/metasfresh/metasfresh/issues/3801
