### ISSUE TITLE
Cache: root documents are no longer invalidated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3793]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
You can pick this example: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1542

Or you simply can open same document in 2 different browser tabs and start editing in one tab and check in the other. Pick BPartner, Product, Order or anything else.

### What is the expected or desired behavior?
Changes in one document shall be reflected everywhere.

**Comment by metas-lc** [comment]
IT
already tested in #1542
and also checked order - grid view and doc view as well => you can see the changes in the other tab, without refresh OK
