### ISSUE TITLE
Error in BOM Lines for Packaging Component Type and Variant Groups

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3797]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is not possible to define BOMLines with Packaging Component Type and Variant Group and Variant for Packaging Material.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall be possible.

**Comment by cristinamghita** [comment]
## Dev test
* Create a new BOM
* Add a BOM line with Component Type **Packing** and VariantGroup **01**
* Add other BOM line with Component Type **Variant** and VariantGroup **01**
  * The line can be created **OK**
### Regression test
* Create a new BOM
* Add a BOM line with Component Type **Component** and VariantGroup **01**
* Add other BOM line with Component Type **Variant** and VariantGroup **01**
  * The line can be created **OK**

**Comment by metas-rc** [comment]
Results of IT


Tested on webui

* Executed the tests provided by Cristina. All went fine, with no error.
