### ISSUE TITLE
duplicate lines in inout 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#380]

**Comment by metas-ts** [comment]
This is another printout which needs to be fixed:
In [DOC140916.pdf](https://github.com/metasfresh/metasfresh/files/473888/DOC140916.pdf) on page 3 of 7.
Positions 230 and 300 appear two times. 
I don't know which report this is..

**Comment by metas-dh** [comment]
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-668.md OK

Regression testing (check Jaspers and old isActive tasks, list provided by lc): OK
