### ISSUE TITLE
Improve inventory import

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3800]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
## Prerequisites
* Create a new attribute set
  ![image](https://user-images.githubusercontent.com/15378036/39120916-a868843c-46f8-11e8-9d8e-21b6a724d2ee.png)
  ![image](https://user-images.githubusercontent.com/15378036/39120928-b874bd32-46f8-11e8-974e-41bff921601d.png)
* Create new hu attributes
  ![image](https://user-images.githubusercontent.com/15378036/39120987-e12409b8-46f8-11e8-8edd-f7ba7288c067.png)
 ![image](https://user-images.githubusercontent.com/15378036/39121035-0c291e96-46f9-11e8-9de0-69ce2ce62c4a.png)

## New features/windows
For this task, next attributes were created:
![image](https://user-images.githubusercontent.com/15378036/39121108-46cb05dc-46f9-11e8-914d-4e36be2903a5.png)

Also were 2 windows :
* One for inventory import
  ![image](https://user-images.githubusercontent.com/15378036/39121234-a948413e-46f9-11e8-83c9-c63bcf6ba7df.png)
* One for Internal inventory
  ![image](https://user-images.githubusercontent.com/15378036/39121207-9531aa8c-46f9-11e8-86be-d285f6d803ff.png)

**Comment by metas-rc** [comment]
Note for IT: an example of xls file is provided in the original customer task

**Comment by metas-lc** [comment]
IT
set configs for attribute as above, have an import file
make sure you have a warehouse with the same value as in your file, product values like in file
import file using inventory data import
=> now there is an error in async when you import

**Comment by metas-lc** [comment]
IT
imports went fine OK
wh locators were created OK
inventories were created OK
could not complete inventory because of hu NOK

**Comment by metas-lc** [comment]
1 inventory created, without attributes OK?
completed the inventory => hu is empty OK?
inventory is not working very well...takes a lot to complete, if you reactivate it you won't be able to open it in webui anymore...
