### ISSUE TITLE
packaging-inout-lines are split into too many invoice candidates

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3806]
### Is this a bug or feature request?
Bug

### What is the current behavior?

If invoice candidates are created from a shipment line with `IsPackagingMaterial='Y'` then the system creates one IC for each material-shipment line that references the packaging line.
This can end up in pages of single TU-invoice lines on the invoice PDF.

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* all packaging-inout-lines are summed up in 1 invoice candidate:
   * same pi used for >1 orderline => 1 shipment line and 1 invoice candidate for overall sum: OK
   * only >1 shipmentline and >1 invoice candidate when different pis are used: OK
* invoice also shows each pi, with overall sum: OK
