### ISSUE TITLE
Add process for creating missing M_Product_acct records to WebUI

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3812]
### Is this a bug or feature request?
FR
### What is the current behavior?
Atm we have a process for creating missing M_Product_acct records, in product category window, tab accounting, but only in Swing.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Pls add the process to WebUI as well.

**Comment by metas-lc** [comment]
IT
1. go to product category window 144
(usually, on a new database Gebinde don't have accountings)
2. select the line in subtab accounting, go to actions 
=> Copy accounts (or Konten kopieren) action is there
3. start Copy accounts
=> accounts are added to all Gebinde products (or the one you selected in product category) OK
