### ISSUE TITLE
webui: My Profile: display Notification Type and User In Charge

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3814]
### Is this a bug or feature request?
FR
needed for https://github.com/metasfresh/metasfresh/issues/3708

### What is the current behavior?
My Profile window: Notification Type and User In Charge fields are displayed in advanced layout
![image](https://user-images.githubusercontent.com/1244701/38376444-3c84f78c-3901-11e8-8da7-c0744df0c4b0.png)

### What is the expected or desired behavior?
Show them in basic layout. It would be nice to put those 2 fields in one group.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The 2 fields are now in the main view, translated in both ENglish and German
