### ISSUE TITLE
technical: Adapt Query.list() to avoid ClassCastExceptions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3816]
### Is this a bug or feature request?
FR

triggered by fixes like:
* https://github.com/metasfresh/metasfresh/commit/c8e5880a2c91b1120c879d5cb5a228437b149862
* https://github.com/metasfresh/metasfresh/commit/a7d2778b2cb187724f0a94872a421aa81cb8bd5a

### What is the current behavior?
IQuery method has following signature:
```java
<ET extends T> List<ET> list() throws DBException;
```

### What is the expected or desired behavior?
It shall be
```java
List<T> list() throws DBException;
```

### Note to IT
IMHO one e2e test would be sufficient.

**Comment by metas-dh** [comment]
didn't have any problems in this regard in weekly e2e, so moving this to Done.
