### ISSUE TITLE
ShipmentSchedule.QtyPickList not updated from drafted shipments

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3822]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
:cherries:picked into `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

* ShipmentSchedule.QtyPickList updated from drafted shipment: OK
* ShipmentSchedule.QtyPickList updated after change of qties in drafted shipment: OK
* ShipmentSchedule.QtyPickList updated after shipment completed & reactivated: OK
