### ISSUE TITLE
Support SSL / TLS when sending mails via SMTP making it SMTPS

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3827]
### Is this a bug or feature request?
FR 

### What is the current behavior?
metasfresh uses SMTP for outbound emailing

#### Which are the steps to reproduce?
configure a gmail mailbox to send mails and you will receive an error message that no SSL / TLS handshake was initiated

### What is the expected or desired behavior?
sending mails in metasfresh should support SSL/TLS

### Workaround
http://www.stunnel.org/

when using google:
https://support.google.com/a/answer/176600?hl=en

**Comment by metasnw** [comment]
at the moment we got two places in metasfrehs to setup mailbox:
1. ad_client
1. Email Server

both need to support encryption

**Comment by metas-rc** [comment]
How to test

* Set SMTP host to smtp.gmail.com (see https://support.google.com/a/answer/176600?hl=en)
* Go to AD_Client and set SMTP Port = 587 (see https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)

* Set Start TLS  to true

* Set SMTP Authorization to true

* set a mail , user and password from a real google account ( if you need one for testing, ask me :) I created a dummy google account for this reason)

**Comment by metasnw** [comment]
@metas-rc can you put your dev tests here as well?
cases that i would see:
1. using test mail process in ad_client
1. activating sending email on request via sysconfig and assign a request to an user with your email address
1. send email using process in docoutbound log using the email server config

**Comment by metas-rc** [comment]
Test mail process in AD_Client:

![image](https://user-images.githubusercontent.com/16001442/38877876-52046604-4268-11e8-85e0-bb1205c5bc18.png)


![image](https://user-images.githubusercontent.com/16001442/38877893-5edd1d44-4268-11e8-90c4-934f0f324c0d.png)


![image](https://user-images.githubusercontent.com/16001442/38878451-ac4f90a6-4269-11e8-9e66-39e01ee09f82.png)


![image](https://user-images.githubusercontent.com/16001442/38878475-b8c7f152-4269-11e8-8b6a-fd2b55c5a08f.png)

**Comment by metas-rc** [comment]
2) activating sending email on request via sysconfig and assign a request to an user with your email address

![image](https://user-images.githubusercontent.com/16001442/38879785-dc613a62-426c-11e8-91ea-a96eb930bdae.png)

![image](https://user-images.githubusercontent.com/16001442/38880429-620f14b2-426e-11e8-9fe7-ea7741a1b8e4.png)

**Comment by metas-lc** [comment]
IT
repeated the testcases above
ad_client: 
1. login with sysadmin and open Client / Mandant window
2. set the following
mail host: smtp.gmail.com
request email and request user: testruximetasfresh@gmail.com
request user password: the one from email
smtp port 587
start tls Y
smpt authentication Y
3. press on Test Email button
=> info bout email connection
4. press start
=> info if the mail was sent ok
=> got email with this message:
metasfresh ERP EMail Test
 EMail{to=[testruximetasfresh@gmail.com], subject=metasfresh ERP EMail Test, mailbox=Mailbox(smtpHost=smtp.gmail.com, smtpPort=587, email=testruximetasfresh@gmail.com, username=testruximetasfresh@gmail.com, smtpAuthorization=true, startTLS=true, sendFromServer=false, adClientId=0, adUserId=-1, columnUserTo=null)}
OK
.
repeated the same testcase in webui
From button: 
=>got email with message: ERP EMail Test
 EMail{to=[testruximetasfresh@gmail.com], subject=ERP EMail Test, mailbox=Mailbox(smtpHost=smtp.gmail.com, smtpPort=587, email=testruximetasfresh@gmail.com, username=testruximetasfresh@gmail.com, smtpAuthorization=true, startTLS=true, sendFromServer=false, adClientId=0, adUserId=-1, columnUserTo=null)} OK

=> but i didn't get that email info. As soon as i pressed on test email, an empty window with start button opened. Didn't get to press on start. It started by itself, and closed right after. OK??

From actions:
was asked for data input: set  email to, subject and message, press start:
=> got email with the message and subject i set OK


request:
activating sending email on request via sysconfig and assign a request to an user with your email address


1. set org.compiere.model.MRequest.EnableNotifications on Y
2. went to a bpartner uer and set email: testruximetasfresh@gmail.com, set password, set notification type to email
3. go to request and create a new one for that bpartner, save
=>

**Comment by thelightsense** [comment]
Whats about "German Message for EMail Message" it should be able to be changed
