### ISSUE TITLE
wrong parent.relativePath in different pom.xmls

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3843]
### Is this a bug or feature request?
bug
### What is the current behavior?

https://forum.metasfresh.org/t/metasfresh-repo-build-errors/1003

**Comment by metas-rc** [comment]
Nothing to IT. Moving this to done

**Comment by metas-ts** [comment]
Just for the record, there *is* sth to IT.
I answered to your respective question:

> you could follow the documentation and build metasfresh from cmd line.
but i think it's not necesary. the issue can imho go to done
