### ISSUE TITLE
WebUI: Add Translations for Context Menu to de_DE

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3844]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Context Menu entries are made translatebale now via https://github.com/metasfresh/metasfresh-webui-frontend/issues/1742.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Translations for de_DE for context Menu entries.

- [x] window.table.zoomInto
- [x] window.table.editField
- [x] window.table.advancedEdit
- [x] window.table.openInNewTab
- [x] window.delete.caption

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


*OK :All fields are translated in both English and German
* NOK: Because of the longer names, the fields are sometimes ugly. Followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1750
