### ISSUE TITLE
Error with ATP presentation in Sales Order Batch entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3849]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the ATP Information from Material Dispo is not shown in Sales Order Batch Entry anymore.

```
"Caused by: java.lang.IllegalArgumentException: trls is null or empty"
[100 … 107]
100
:
"	at de.metas.i18n.ITranslatableString.compose(ITranslatableString.java:97)"
101
:
"	at de.metas.ui.web.material.adapter.AvailableToPromiseResultForWebui$Group.createStorageAttributesString(AvailableToPromiseResultForWebui.java:162)"
102
:
"	at de.metas.ui.web.material.adapter.AvailableToPromiseResultForWebui$Group.<init>(AvailableToPromiseResultForWebui.java:112)"
103
:
"	at de.metas.ui.web.material.adapter.AvailableToPromiseResultForWebui$Group$GroupBuilder.build(AvailableToPromiseResultForWebui.java:93)"
104
:
"	at de.metas.ui.web.material.adapter.AvailableToPromiseAdapter.createClientResultGroup0(AvailableToPromiseAdapter.java:112)"
105
:
"	at de.metas.ui.web.material.adapter.AvailableToPromiseAdapter.createClientResultGroup(AvailableToPromiseAdapter.java:83)"
106
:
"	... 94 more"
107
:
""
```
#### Which are the steps to reproduce?
Open, try and see.

**Comment by metas-lc** [comment]
IT
checked in both sales order and purchase order with atp 0 and 100 => no errors, atp was visible OK

steps to have atp there: 
1. made sure sys configs ATP.DisplayOnlyPositive is on N (to also show negatives just in case) and ATP.QueryEnabled on Y (DisplayOnlyPositive is Y by default so i put it back after)
2. in my case the database was new so when i first created a sales order atp was 0
3. to have a bigger qty i created a receipt, qty 100 => then, on batch entry, i could see 100
OK
