### ISSUE TITLE
Request notifications shall use new notifications API

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3875]
### Is this a bug or feature request?
Follow-up of https://github.com/metasfresh/metasfresh/issues/3708#issuecomment-379247122

### What is the current behavior?
the notifications sent on Request creation/updates shall use our new notifications API.

**Comment by metas-lc** [comment]
note for IT: please also retest the IT  part II, with the request (or just to be sure, testcase III with docoutbounds) https://github.com/metasfresh/metasfresh/issues/3827#issuecomment-382479241

**Comment by teosarca** [comment]
note to RM: integrate after https://github.com/metasfresh/metasfresh/issues/3708

**Comment by metas-lc** [comment]
IT
1. update client and user with test email
2. set EnableNotifications config on Y
3. set DebugMailTo config on my email
4. go to your user settings, notifications. Group: request, Type: email+notice
5. go to bpartner window, select one, go to actions: create request. 
6. set all mandatory fields, press done
=> you get notification and email OK
.
repeated the testcase from https://github.com/metasfresh/metasfresh/issues/3827 using gmail 
(created email server and routing, added mail to bpartner's user, sysconfig for debug email empty)
=> works fine OK
note: in this case, i created the request manually, from request window
