### ISSUE TITLE
Add link and templates for email notification

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3879]
### Is this a bug or feature request?
FR
### What is the current behavior?
Follow-up of #3708 
Atm, the emails sent don't include a link and only a short info, like e.g. "Approve credit limit" for BPartner - Credit Limit Approval, so the recipient of the email does not know which bpartner's credit limit shall be approved.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
* add a link in the resp. email, so the recipient can just use it to open the resp. data in WebUI
* add templates for the emails so the resp. information can be improved / customized

**Comment by teosarca** [comment]
fixed in `gh3708` branch. To be tested there.

**Comment by metas-dh** [comment]
Results of IT1
tested in dev30

* bpartner no. is included in email for credit limit approval: OK
* bpartner no. should include link to open the resp. data in WebUI: no link as included, NOK

**Comment by teosarca** [comment]
@metas-dh  it's a config issue.
Sysconfig `webui.frontend.url` shall be set with the frontend's URL.
On w101 i've set it to `https://w101.metasfresh.com:8443` so it shall work.

**Comment by teosarca** [comment]
btw, this one can be tested on master branch

**Comment by metas-lc** [comment]
IT
configs:
1. set email from to client: IsSmtpAuthorization='Y' , RequestEMail, RequestUser, RequestUserPW, SMTPHost
2. set org.adempiere.user.api.IUserBL.DebugMailTo on your email
3. go to Sysconfig webui.frontend.url -> value shall be set with the frontend's URL
4. my profile window, IT user (the one i'm logged in with) -> set your email
5. go to notifications tab, set group: BPartner - Credit Limit Approval, type: EMail+Notice
6. set org.compiere.model.MRequest.EnableNotifications on Y
7. go to bpatrner, create new credit limit
8. select the line of your credit limit, go to actions: credit limit request approval
9. set your user, start
=> notification: Please approve credit limit for 1000001 (if you select it you get to that window)
=> email: Please approve credit limit for 1000001 <[frontend's url]/window/123/2156427>  
OK
