### ISSUE TITLE
Process C_Flatrate_Term_Extend does not work if ContractStatus is null

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3885]
### Is this a bug or feature request?
bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. created contract via sales order
2. set ContractStatus to null in db
3. ran extend contract action: worked fine, contract was extended correctly
4. new contract period: ContractStatus: running: OK
5. old contract: ContractStatus remains null, OK?

**Comment by metas-rc** [comment]
Talked with metas-ts. Will close this
