### ISSUE TITLE
Automatic Setting of Pharma Authorisation for Shipment/ Receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3887]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are Fields in Business Partner Pharma Window that describe the Permissions/ Authorisations for Customers/ Vendors in Pharma Trading (Shipment, Receipt),
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
- If a Pharma Permission is set for the Business Partner, then the "Shipment/ Receipt" Authorisation shall be automatically set to "Type A" and Authorisation Date for "Type A" shall be set to System date.
- If No Pharma Permission is set for the Business Partner, then the "Shipment/ Receipt" Authorisation shall be automatically set to "Type B" and Authorisation Date for "Type A" shall be set to null.
- 5 Fields in customer w/ Shipment Auth + Date
- 3 Fields in Vendor w/ Receipt Auth + Date

**Comment by metas-rc** [comment]
Note: only testable in #3890

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh/issues/3890 OK
