### ISSUE TITLE
Pharma Business Partner Window adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3888]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have a Business Partner Pharma window that stores information about customers/ vendors of pharmaceutical companies.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the following adjustments to the Business partner Pharma Window:
- New Fieldsgroup "Pharma Permissions"
  - Manufacturing Permission
  - Wholesale Permission
  - Agent
  - Pharmacy Permission
  - Veterinary Permission

- New Field "Shipment/ Receipt Authorisation"
  - Type A: Authorisation for all Products
  - Type B: No Authorisation for Pharmaceutical Products
  - Authorisation Date for "Type A"

Important: Correct entity type setting for pharma!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* New Fieldsgroup "Pharma Permissions"

    * Manufacturing Permission: OK
    * Wholesale Permission: OK
    * Agent: OK
    * Pharmacy Permission: OK
    * Veterinary Permission: spelling incorrect:  "Tierärtzliche", shall be "Tierärztliche"

* New Field "Shipment/ Receipt Authorisation"

    * Type A: Authorisation for all Products: can be set per resp. Action: OK
=> authorisation type A is set 'Y' when at least 1 of the params in action is checked: OK
    * Type B: No Authorisation for Pharmaceutical Products: Default value when setting customer / vendor='Y': OK
    * Authorisation Date for "Type A": only in Advanced Edit, not in grid view: OK

**Comment by metas-dh** [comment]
Update:
spelling mistake fixed, now "Tierärztliche": OK
