### ISSUE TITLE
Report for Pharma Permission/ Authorisation control

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3889]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no report available for Pharma Permission/ Authorisation control.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a Jasper Report for Pharma Permission/ Authorisation control.
Parms (optional):
- Business Partner
- Manufacturing Permission
- Wholesale Permission
- Agent
- Pharmacy Permission
- Veterinary Permission

Columns:
- Business Partner Name
- Business Partner Value
- Manufacturing Permission
- Wholesale Permission
- Agent
- Pharmacy Permission
- Veterinary Permission
- Authorisation Date for "Type A"

- 5 Fields in customer w/ Shipment Auth + Date
- 3 Fields in Vendor w/ Receipt Auth + Date

**Comment by metas-lc** [comment]
Liefer-/Bezugsberechtigung Kontrolle
Pharma Permission/ Authorisation control 
Report contains:
title and parameters,
columns: name, name2, bp value, customer/vendor, manufacturer perm, wholesale perm, agent perm, pharmacy perm, veterinary perm, shipment/receipt perm, change date

**Comment by metas-lc** [comment]
taking it back to fix sql

**Comment by metas-lc** [comment]
see how those columns are set: https://github.com/metasfresh/metasfresh/issues/3890

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* de_DE version: Arzneiverm. / Arzneim.vermittler: take out .../, not needed
* date: shown in 2 lines, show only in 1 line: NOK
* sorting?

![2018-04-25 13_46_38-liefer-bezugsberechtigung kontrolle pdf](https://user-images.githubusercontent.com/18696715/39245014-d4276b10-4892-11e8-8d41-e5ef95b2aee9.png)

* parameters in process: 
     * de_DE: Pharmacie Permission, NOK
     * en_US: same as de_DE, NOK

![2018-04-25 14_07_51-metasfresh](https://user-images.githubusercontent.com/18696715/39245027-ddf3ab2c-4892-11e8-8e62-917e8cb26a63.png)

**Comment by metas-lc** [comment]
fixed: 
date on 2 lines
sorting (date desc - nulls last, name asc)
rename Arzneiverm
added missing trls

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* de_DE version: Arzneiverm. / Arzneim.vermittler: take out .../, not needed: OK
* date: shown only in 1 line: OK
* sorting: date desc - nulls last, name asc: OK i think
* added missing trls in parameters for process: OK

* spelling mistakes:
    * "tierärtzliche" => must be "tierärztliche"
    * en_US params: "Pharmacie Permission", shall be "Pharmacy Permission" as in report

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* spelling mistakes fixed: OK
