### ISSUE TITLE
Role Permission for Pharma Permission and Authorization changes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3890]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to allow the update of fields just for users of a specific role.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
In Window Business Partner Pharma, the setting of the following fields shall be restricted to a specific role only:
- Business Partner
- Manufacturing Permission
- Wholesale Permission
- Agent
- Pharmacy Permission
- Veterinary Permission
  - Type A: Authorisation for all Products
  - Type B: No Authorisation for Pharmaceutical Products
  - Authorisation Date for "Type A"

The solution shall be to create 2 process/ actions (1 vendor, 1 customer) that shall be visible (if possible easily) when selecting customer and vendor subtab row and flags customer/ vendor = Y. Only the specific role will have the process permissions. Those fields shall be readonly always.

**Comment by metas-lc** [comment]
IT
1. open Business Partner window, check actions 
=> there are no pharma actions OK
2. open Business Partner Pharma window 
=> there are pharma actions: update customer pharma permissions and  update vendor pharma permissions OK
3. set iscustomer and isVendor on N and check the actions again
=>  update customer pharma permissions and update vendor pharma permissions are there and readonly OK
4. check advance edit in customer and vendor subtabs
=> 
Pharma Manufacturer Permission, Pharma Wholesale Permission, Pharma Agent Permission, Pharmacy Permission, Veterinary Pharmacy Permission, Pharma Shipment Permission, Typ A: Lieferberechtigung für alles, Date Permission Type A
AND
Pharma Manufacturer, Pharma Wholesale, Pharma Agent, Date Permission Type A, Pharma Receipt Permission
are there and readonly OK
5. run Update Customer Pharma Permissions, set some fields on Y
=> the corresponding fields updated, pharma shipment permission is on A, Date Permission type A is on today OK
 6. run Update Customer Pharma Permissions, set all fields on N
=> all fields are on N,  pharma shipment permission is on B, Date Permission type A is null OK
7. repeat the same testcase for  Update Vendor Pharma Permissions
=> works the same OK
8. check translations: fields are translated OK 
the process doesn't have the params/title translated! NOK
created task: https://github.com/metasfresh/metasfresh/issues/3920
