### ISSUE TITLE
Contracts: Allow possibility to copy the prices when extending

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3892]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?

case:

test setup:
-priceliste versions
-01.01.2016 = Price 1
-01.01.2017 = Price 2

compensation group adding discount
flatrate condition has autoextend immediately
execution:

Order
-datepromised: 01.06.2016
product A with Price 1 and 3 years contract condition
create compensation group adding discount
line #2: product B with Price -1 (discount)
flatrate term
NOK: product A has on second term price=2 (should have price=1)
NOK: product B has Price 0 but should remain -1

**Comment by cristinamghita** [comment]
## Dev tests
### Test - Don't compute prices
* Create a new chain of flat rate condition with flag IsCalculatePrice on N.
   * this means that the prices for the next flat rate term will be copied from the previous one
    ![image](https://user-images.githubusercontent.com/15378036/39004828-21d5246e-4407-11e8-9612-9b330251ae07.png)
* Create a sales order using first condition (and having a compensation group)
   ![image](https://user-images.githubusercontent.com/15378036/39005001-8eb880f8-4407-11e8-946f-7454715a5d3c.png)
* Complete the order and check created contracts
  ![image](https://user-images.githubusercontent.com/15378036/39004554-498771ac-4406-11e8-9863-2b53ff5fc334.png)

**Comment by metasnw** [comment]
IT of the requirement was successfull:
1. OK: price is recalculated like before when option is off
1. OK: price is remaining the same on both discount and product  when the option is on

@cristinamghita any regression tests you recommend?

**Comment by cristinamghita** [comment]
@metasnw yes.
Usual case. I described in my tests .

**Comment by metas-dh** [comment]
Regression testing: all worked fine, closing this issue.
