### ISSUE TITLE
extend M_HU_Process

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3895]
### Is this a bug or feature request?
FR
### What is the current behavior?
Currently, if a process in in M_HU_Process, then it's automacially also an action in the HU editor

### What is the expected or desired behavior?
We need to have a process in  M_HU_Process (to specify if it e.g. is for LUs or not), but it may not show up as an action in the webui

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested with TU Picking Label:
* process in M_HU_Process, only available in picking terminal: OK
* not in HU Editor (window and material receipt / manufacturing): OK
