### ISSUE TITLE
Add Translations for Pharma Business Partner Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3897]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
There are a few new Fields from https://github.com/metasfresh/metasfresh/issues/3888 that are not translated to en_US yet.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Translations for en_US.
Also, make new Fields Read Only.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* translations for en_US: OK
* make new Fields Read Only: OK
