### ISSUE TITLE
docoutbound mailing: Autodect if MailWorkpackageProcessor.EmailMessage is HTML

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#3909]
### Is this a bug or feature request?
FR

### What is the current behavior?
when sending emails via a process (Mass Mailing of Invoices) its encoded in plain text

#### Which are the steps to reproduce?
1 put html into sysconfig for email template
1. open window docoutbound log
1. send emails to selected partners
1. open email => html tags are not rendered

### What is the expected or desired behavior?
~~~make this configurable via email server routing~~~
tsa 23.04.2018: automatically figure out if `MailWorkpackageProcessor.EmailMessage` message is HTML. i.e. search for `<html>`.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


I set in the sys config "MailWorkpackageProcessor.EmailMessage" the message text: 

````
<html>
<body>

<h1>My First Heading</h1>

<p>My first paragraph.</p>

</body>
</html>
````

**Comment by metas-rc** [comment]
Note: The sys config or any ther configuration is not needed. If you put a html text in the message and it contains the string <html>  it will be parsed and displayed correctly.

**Comment by metasnw** [comment]
IT:
text without html tag: OK
text with html tag: content type is text/html and email body is rendered to html
