### ISSUE TITLE
Avoid numeric values with too many trailing zeros

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3914]
### Is this a bug or feature request?
FR
### What is the current behavior?
I don't know where it came from, but i found the following value in C_OrderLine.PriceActual:
```java 
0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
#### Which are the steps to reproduce?
unknown

### What is the expected or desired behavior?

the system should log a warning (which creates an AD_Issue) and carry on with a stripped-down value

**Comment by metas-rc** [comment]
Results of IT

Tested on webui and swing


Testcase I tried:
* I created an order and went to quick input
* I selected a product with a TU configured
* In the tu Qty I put 1.234000000000000000000000000000000000
* I pressed enter

* OK: I got this in the console:

> The given value has scale=24; going to proceed with a stripped down value with scale=2; value=12.340000000000000000000000; this=MOrderLine[0, Line=0, Ordered=12.34, Delivered=0, Invoiced=0, Reserved=0, LineNet=0]

**Comment by metas-ts** [comment]
Hi @metas-rc 
> Also, note that the AD_Issue is not created because the message is on level warning.

fixed

**Comment by metas-rc** [comment]
Results of IT 2: 
Tested on swing

OK: Now the adIssues are created.
