### ISSUE TITLE
QtyPicked not updated in shipment schedule after reactivate & unpick in picking terminal

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3916]
### Is this a bug or feature request?
Bug
### What is the current behavior?
After reactivating and unpicking in picking terminal, the QtyPicked in shipment schedule is not updated.
#### Which are the steps to reproduce?
1. Create a sales order, have ordered product in stock
2. in picking terminal, do picking and process it
3. reactivate the picking and unpick the HU
4. pick the same HU once more and process it
5. create the shipment from shipment schedule, with "Use QtyPicked" ='Y':
=> shipment schedule has ToBeUpdated=Y, OK
=> when shipment is created, QtyPicked is not set to 0: NOK
6. reactivate the shipment, and complete it again:
=> shipment schedule has ToBeUpdated=Y, OK
=> when shipment is completed again, QtyPicked is set to 0: OK
### What is the expected or desired behavior?
QtyPicked shall be updated correctly.

**Comment by metas-ts** [comment]
@metas-dh i believe the fix to 
QtyPicked remains set although shipment is completed https://github.com/metasfresh/metasfresh/issues/3981 also solved this issue. therefore i moved this one to "rollout"

**Comment by metas-dh** [comment]
@metas-ts 
checked: was solved by #3981, see IT there, closing this one.
