### ISSUE TITLE
Base Price + Surplus in Pricing Conditions not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3927]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the new Pricing Functionality using Base Pricing System and Surplus does not work. Defining it this way and using in Sales Order, only leaves the surplus as orphaned result. Th Pricestd. from Base Pricing System is not added.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please Fix.

Follow up from https://github.com/metasfresh/metasfresh/issues/3833

**Comment by teosarca** [comment]
update:

have a discount schema break with base pricing. If the price is not found in base pricing, the price is considered zero => NOK, it shall fail.

how to test/reproduce: in base price list make sure the product price has some packing instruction which does not match the one used in order.

**Comment by metas-mk** [comment]
... and more. In Discoutn Schema break set the base pricing system to one with pricelist isSalesPricelist = 'Y'. Using this in Sales order does not "find" the price.

**Comment by metas-lc** [comment]
IT
1. made discount schema break for Product A. isPriceOverride on Y, Price Base: Pricing System, set as a base PS a purchase price system
2. created an order and added that product
=> discount schema was applied OK
=> i was allowed complete the order OK
.
3. go to product prices, take product A from the purchase price system and add an HU to it
4. go to product A and make sure it has at least 2 HUs
5. create a sales order and add a line with product A with the other HU 
=>
Error: Product is not on...
Server error
Product is not on PriceList - Product:A, Price List:Testpreisliste Lieferanten DE, Date:04/26/2018
OK
.
6. go to discount schema and add a price system that does not contain your product
=> Valid field is set on N and Not Valid Reason has the following text: "Product is not on PriceList - Product:A, Price List:Testpreisliste Lieferanten DE, Date:04/26/2018"
OK
7. press done and create a new sales order with that product
=> discount schema was not applied OK
