### ISSUE TITLE
Invoicing Invoice Cadidates with processed = Y "has changes"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#393]
Invoicing Invoice Cadidates with processed = Y "has changes"
* although processed the IC comes into async processing and gets error "has changes"
* seems to only be in Karottenabrechnung
(example IC 3434848, 3422689 has changes 80.00 -> 0)
--> workaround: opened IC, set price overwrite to 0,00 -> processed = Y.

**Comment by metas-ts** [comment]
from the code it seems as if this should not happen.
It looks like this is a manifestation of your problem that invoice candidate updates are lost some times.
I therefore started to implement #302
