### ISSUE TITLE
Create process for importing discount schema

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3937]
### Is this a bug or feature request?
FR

**Comment by metas-lc** [comment]
IT
made sure i had  PriceSytems with the values from column 'Basis' (E.g. APO-EK)
payment terms with value for the content of the column 'Skonto' (E.g. 2)
products with the value from column PZN
make sure that some products are on the pricelist from your import

create new data import with import discount schema
import the file, like in example from devtest
go to Import Discount Schema window 
=> data is imported OK
go to discount schema 
=> all data set. If the product was not on pricelist you get a note "product not on pricelist"
else it's valid OK
