### ISSUE TITLE
Improve the speed of scripts applier

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3960]
### Is this a bug or feature request?
FR

### What is the current behavior?
When applying migration scripts, it takes a long time to find out which scripts were applied and which not.
That's because for each script an SQL SELECT is issued to check if there is an AD_MigrationScript record for it. So for >4000 scripts, >4000 SQL SELECTs are be issued.

#### Which are the steps to reproduce?
Do a rollout or run it locally.

### What is the expected or desired behavior?
Load the AD_MigrationScript table in memory and check if from there.

### Configuration
In case shit hits the fan and you want to switch this feature off, use `-DUseInMemoryScriptsRegistry=false` JVM parameter.

**Comment by teosarca** [comment]
Test results from my laptop:

Before and after: 

Before: 183seconds vs 12seconds :)
```
[INFO ] Evaluated 4294 scripts
[INFO ] Applied 0 scripts
[INFO ] Ignored 0 scripts
[INFO ] Duration: 183697ms
```


After:
```
[INFO ] Evaluated 4294 scripts
[INFO ] Applied 0 scripts
[INFO ] Ignored 0 scripts
[INFO ] Duration: 12081ms
```

**Comment by metas-lc** [comment]
checked with Teo - works fast OK
