### ISSUE TITLE
Translate Actions Update Pharma Conditions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3965]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Actions Update Pharma Conditions Customer/ Vendor are not translated for de_DE.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Translate the Actions to de_DE.

**Comment by metas-lc** [comment]
tested here https://github.com/metasfresh/metasfresh/issues/3967
the actions are translated OK
