### ISSUE TITLE
Translate Process Parm in Update Pharma Conditions for Customers

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3967]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a Translation for de_DE is missing for Pharmacy Permissions in Process/ Action "Update Pharma Conditions for Customers"
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add Translation.

**Comment by metas-lc** [comment]
IT
1. en_US:
1.1 Update Customer Pharma Permissions
params: Pharma Agent Permission, Pharmacie Permission, Pharma Manufacturer Permission, Pharma Wholesale Permission, Veterinary Pharmacy Pemission
1.2 Update Vendor Pharma Permissions
params: Pharma Agent Permission, Pharma Manufacturer Permission, Pharma Wholesale Permission

2. de_DE
2.1 Pharma Qualifikation Kunde
params: Arzneivermittler §52c Abs.1-3 AMG, Apothekenbetriebserlaubnis §1,2 ApoG, Herstellererlaubnis §13 AMG, Großhandelserlaubnis §52a AMG, Tierärtzliche Hausapotheke §67 ApoG
2.2 Pharma Qualifikation Lieferant
params: Arzneimittelvermittler §52c Abs.1-3 AMG, Herstellererlaubnis §13 AMG, Großhandelserlaubnis §52a AMG

Needed small fixes: 
en_US: 
Pharmacie Permission -> Pharmacy Permission 
Veterinary Pharmacy Pemission -> Veterinary Pharmacy Permission
de_DE: 
Tierärtzliche Hausapotheke §67 ApoG -> Tierärztliche Hausapotheke §67 ApoG

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: All the fields are now correctly translated.
