### ISSUE TITLE
Pharma: If Shipment Auth Type B then show in Order Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3969]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Info in Sales/ Purchase Order when a Customer/ Vendor only has Type B Permission.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Show if a Business partner only has Type B Permission.

**Comment by cristinamghita** [comment]
### Customer side
![image](https://user-images.githubusercontent.com/15378036/39513967-95dd47dc-4dfe-11e8-97f8-cc2c47b46436.png)
### Vendor side

**Comment by metas-lc** [comment]
IT
I. Type B
1. go to bpartner A and select actions "Update Customer Pharma Permissions"
2. set all on N, start. Go to customer tab
=> Pharma Shipment Permission = Typ B: Keine Lieferberechtigung für Arzneimittel OK
3. create a new sales order, add bpartner A
=> new field appears: Lieferberechtigung, set on  Typ B: Keine Lieferberechtigung für Arzneimittel OK
4. go back to bpartner, select actions "Update Customer Pharma Permissions", set at least one flag on Y, start. Go to customer tab
=> Pharma Shipment Permission = Typ A: Lieferberechtigung für alles OK
5. go to sales order and create a new one, add bpartner A
=> field does not appear OK
.
6. repeat the same testcase for purchase, using "Update Vendor Pharma Permissions"
=> works the same, when you have type B, Lieferberechtigung field appears OK
.
7. have 2 bpartners, one type A, one B
8. create an order for type A => field does not appear OK
9. remove that bpartner, and change it to the one with type B => field appears OK
