### ISSUE TITLE
New Manufacturing Workflow not saved

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3971]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Manufacturing Workflow in WebUI is not saved. https://forum.metasfresh.org/t/adding-a-new-manufacturing-flow/1036
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall be saved.

**Comment by metas-mk** [comment]
Checked: Field AccessLevel is missing in WebUI Window
![image](https://user-images.githubusercontent.com/13365687/39463919-19015188-4d1b-11e8-88fc-b472db47da0b.png)

**Comment by metas-lc** [comment]
IT
created a new Manufacturing Workflow, added all mandatory fields =>
document is saved, add new button in included tab appears OK
(adding line also works)
