### ISSUE TITLE
Manufacturing Workflow adjustments in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3973]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Window Manufacturing Workflow in WebUI has some elements that don't fit to our current WebUI guidelines.
- Action Button
- 2-Column Layout
- Advanced edit
- Subtab Layout
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Adjust the Window so it meets our WebUI Guideline Criteria.

**Comment by metas-lc** [comment]
IT
open Manufacturing Workflows
=> usual window
TL: mandatory, important OK
TR: active, important flags OK
BR: org, client OK

subtab: white background, 1 element group OK

few de_DE translations missing: Version, Join Element, Split Element
there is no clear sorting in grid view
created follow-up https://github.com/metasfresh/metasfresh/issues/3978
