### ISSUE TITLE
Allow annotating data as personal

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3975]
### Is this a bug or feature request?
FR
### What is the current behavior?

Currently there only are features to obscure or encrypt data

### What is the expected or desired behavior?

We need to be able to flag sensitive data as such.

* Add a "Personal data category" AD_Element

* Add a "Personal data category" list AD_Reference
  * items:
    * not personal
    * personal
       * e.g. AD_User records are mostly personal (exception might be e.g. a "sales@company" user)
    * sensitive personal (genetic data, biometric data, data concerning health)
       * e.g. AD_User.Birthday, or profile photo
  * add description/definition for each. E.g. see here: https://gdpr-info.eu/art-4-gdpr/ (german and english)

* Add a "personal data" column to AD_Table and AD_Column
  * the AD_Table value applies to all AD_Columns, unless it is overridden on column level

* Flag all tables and columns (if needed) as "personal" that could contain personal data.
  * Example: C_BP_BankAccount: for 1-person-C_BPartners it might contain a personal IBAN which can be used to identify the person. So C_BP_BankAccount is potentially personal.

* Create a jasper report that reports all personal and sensitive data tables and columns

**Comment by metas-rc** [comment]
Results of IT

* Tested on swing

* OK: Personal Data category field present in table and column;
* OK: The report Personal Data displays all the tables and columns that contain personal data


1)
* Created a new table, made it Personal
* Created some columns for it, one of them overriden to non personal
* Checked the jasper
* OK: All the columns form the table appear there
* OK: The non personal column also appears and is marked as NP ( non personal)


2)
* Creaated a  non personal table
* Added some columns to it, one of them personal
* Checked the jasper again: 
* OK: The column that is personal is displayed there. The rest of the table is not.
