### ISSUE TITLE
Pharma: Prices  from IFA import are in cents

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#3977]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Now, when import IFA products, we import prices in euros, but in the file, the prices are in cents.
### What is the expected or desired behavior?
When import IFA products, we need to divide the prices per 100, in order to transform from cents to euros.

**Comment by cristinamghita** [comment]
Sql for updating existent one
```
update M_ProductPrice
set PriceStd=round(PriceStd/100,6), PriceList = round(PriceList/100,6), PriceLimit=round(PriceLimit/100,6)
where created >= to_timestamp('02-05-2018','DD-MM-YYYY') and created < to_timestamp('03-05-2018','DD-MM-YYYY')
```

**Comment by metas-lc** [comment]
IT
1. set internal names to pricelists (see those fields that start with price list in this window 540386)
2. add an import csv file (make sure you have a product with the value from the file)
3. go to Data import, create a new one "Pharma product IFA"
4. drag and drop your file
5. go to actions, import attachments
6. go to Import Pharma Product
=> product is imported: pricelists are set and if you had the following prices in your files: e.g. 174, 210 you will see them as 1.74 and 2.1 OK
7. go to product window and select your product, check pricelist tab
=> prices are the same: 1.74 and 2.1 OK
