### ISSUE TITLE
Notifications in Swing Client show no info 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3980]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Notifications in Swing Client are empty: no info or link about the created e.g. shipment or invoice.

![2018-05-02 14_59_55-decloudit001](https://user-images.githubusercontent.com/18696715/39524570-add4c854-4e19-11e8-8658-4d00fa02c504.png)

#### Which are the steps to reproduce?
Create e.g. a shipment in Swing Client and check the notification.
### What is the expected or desired behavior?
Notification shall have info & link.

**Comment by teosarca** [comment]
note to dev: i think u shall debug from org.adempiere.ui.notifications.SwingEventNotifierFrame.toNotificationItem(Event). I suspect the event is not correctly converted to NotificationItem. Might be because we changed a bit how the notification events are structured.

**Comment by cristinamghita** [comment]
## Dev test
Login and the new notificaiton is:
![image](https://user-images.githubusercontent.com/15378036/39633568-018f8b8e-4fc1-11e8-8375-a5061cff8d43.png)

**Comment by metas-lc** [comment]
IT
1. on login there are no notifications. Only on local OK
2. create sales/purchase invoice => notifications appear correctly OK
3. create sales/purchase inout => notifications appear correctly OK
4. credit limit approval in bpartner => notifications appear correctly  OK
