### ISSUE TITLE
QtyPicked remains set although shipment is completed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#3981]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you create a shipment, no matter if it's generated from shipment schedule, Gear or after using picking terminal, and the checkbox for autocomplete is set, the QtyPicked in the shipment schedule remains, although the shipment was completed.
It is updated correctly when the shipment is reacitvated and completed again.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
QtyPicked = QtyOrdered - QtyDelivered (=> shipment completed).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

QtyPicked is 0 after shipment is generated:
* shipment generated from Gear, no picking: OK
* shipment after picking, using QtyPicked: OK
* partial shipment after picking, using QtyPicked: OK
* shipment after picking - unpicking (see #3916), using QtyPicked: OK

Problem:
QtyPicked is set back to 0 in Picking Terminal as well => after a partial shipment, it looks like nothing was yet picked & shipped, since we now have QtyOrdered instead of QtyToDeliver in Picking Terminal!

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
QtyPicked is set back to 0 in Picking Terminal as well: solved in #3986
