### ISSUE TITLE
Pharma vertical for Discount Schema Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#3982]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window for Discount Schema has a lot of settings that are not needed in the Pharma industry.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a Discount Schema Window for Pharma:
- Set IsPriceOverride as 'Y' and hide the field
- Hide the following Fields
  - Attribute
  - Attribute Value
  - Fixed Discount
  - Quality reduction
  - Organisation
  - Client
  - isPriceOverride

Show in Discount Schema as Virtual Column
  - FAM/ ZUB
  - Indication

Order of Fields in the Window
  - Product
  - Quantitybreak
  - Pricebase
  - Discount
  - Fixum
  - FAM/ ZUB (readonly)
  - Indication (readonly)

**Comment by metas-lc** [comment]
IT
1. Pharma Discount Schema window /540433
2. Following Fields are hidden:
    Attribute OK
    Attribute Value OK
    Fixed Discount (the checkbox) OK
    Quality reduction OK
    Organisation OK
    Client OK
    isPriceOverride OK
3. showed virtual columns
    FAM/ ZUB OK
    Indication OK

4. Order of Fields in the Window

    Product OK
    Quantitybreak OK
    Pricebase OK
    Discount (is above Quantitybreak) NOK ?
    Fixum ?
    FAM/ ZUB (readonly) OK
    Indication (readonly) OK


5. TRL
- missing en trl: Gültig, Produkt
-missing de trl: Pharma Discount Schema (window name)

**Comment by metas-lc** [comment]
IT
1. org and client are back - wanted OK
2. virtual columns are still shown OK
3. Order of Fields in the Window
Product, Quantitybreak, Pricebase, Discount, Fixum, FAM/ ZUBOK, Indication OK
4. trl: window name and all fields are translated in de and en OK
5. created a flat discount schema => was not shown in pharma discount schema window OK
