### ISSUE TITLE
Invoice candidate for canceled term and reactivated sales order keeps invalidating itself

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3984]
### Is this a bug or feature request?
Bug
### What is the current behavior?

* invoice candidates keep invalidating and updating themselves endlessly
* the problem is similar to https://github.com/metasfresh/metasfresh/issues/3216

#### Which are the steps to reproduce?

* Create and complete a sales order with a subscription line
  * make sure there is a contract (flatrate term) and an invoice candidate
* reactivate the sales order
* cancel the flatrate term
=> the IC in question will be invalidated and updated, unless you manage to clear `C_Invoice_Candidate_Recompute` at the right time (or while the appserver is stopped)

**Comment by metas-lc** [comment]
IT
1. create a new Contract Term (window 540113)
2. create a new Contract Transition, add a new line and set the following:
```
Contract Terms: the one from step 1 
Deadline: 1 day
Action: Statuswechsel
Contract Status: Gekündigt
```
3. complete Contract Transition. Go to Contract Term, add your Contract Transition and then complete
4. create a new sales order, add a product and set your contract term. Complete order
=> new IC and Contract created OK
5. Open Invoice Candidate in a new tab, the Contract in another one
=> IC is NOT to recompute, NOT processed OK
=> Contract is Completed OK
6. reactivate your sales order
=> status: In Progress OK
=> IC is still NOT to recompute, NOT processed OK
7. go to Contract tab, select actions - Contract Change
8. select action Einzelne Periode stornieren, Date Today. Press Start
=> Contract is now closed OK
=> IC is processed OK
