### ISSUE TITLE
pharma: repack number attributes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3989]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
Configuration: for some attribute sets (in product category) we would like to add 2 more attributes:
* Requires Repack Number: Yes/No
* Repack Number: String

It shall work as follows.

In Order line, user is able to set the `Requires Repack Number` attribute to Yes.

When receiving an HU:
* the `Requires Repack Number` attribute shall be displayed in attributes panel (right side) but it shall be readonly
* Beneath it, the `Repack number` shall be displayed.
* when user trying to receive an HU which requires Repack number but the repack number is not filled, and error shall be displayed and material receipt generation shall be prevented.
* if the `Requires Repack Number` was not set to Yes in Purchase Order Line, both attributes shall be hidden in HU attributes.

### How to enable this feature for a given attribute set
![image](https://user-images.githubusercontent.com/1244701/39626004-d4cec686-4fa8-11e8-8726-915e9125502f.png)

**Comment by metas-lc** [comment]
IT
1. Add require repack number attribute in attribute set of your material category (window 256)
2. create a purchase order with a product from that category
3. add 3 lines: 
Required Repack Number - YES, NO and None
4. complete order, go to receipt candidates
5. receive each line one by one
=> Required Repack Number - 
YES: Repack Number - editable, Required Repack Number readonly OK
NO: Repack Number - hidden, Required Repack Number hidden OK
None: Repack Number - hidden, Required Repack Number hidden OK
6. create material receipts
=> attributes: Yes_2, No, (no attribute) OK
.
7. also tried different attributes (including quality discount)
=> works like before OK
.
8. try to make a material receipt with Required Repack Number YES and Repack Number null
=> error:
```Error: Die Repack Nr. muss...
Server error
Die Repack Nr. muss erfasst werden für 1000040!```
9. set Repack Number to 0
=> works OK
.
10. besides the attribute you set at step 1, also set Repack Number (window 256)
11. create a purchase order with a product from that category
12. add 3 lines: 
Required Repack Number - YES, NO and None. Set a number on each Repack Number
13. complete order, go to receipt candidates
14. receive each line one by one
=> Required Repack Number - 
YES: Repack Number - editable, set, Required Repack Number readonly OK
NO: Repack Number - hidden, Required Repack Number hidden OK
None: Repack Number - hidden, Required Repack Number hidden OK
15. create material receipts
=> attributes: Yes_2, No_3, 1 OK
