### ISSUE TITLE
Implement "Der Kurier" parcel number check digit

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#3991]
### Is this a bug or feature request?
FR
belongs to #3926 

### What is the expected or desired behavior?

please implement this algorithm in the branch `gh3926`, in the class ParcelNumberGenerator, method computeAndAppendCheckDigit.

|Example |Parcel number =10052556876|
|---------|---------------|
|1) Add all odd positions and multiply the sum by 3|odd = (1 + 0 + 2 + 5 + 8 + 6) * 3 = 66|
|2) Add all even positions | even = 0 + 5 + 5 + 6 + 7 = 23|
|3) Build the sum (odd + even) |sum (odd + even) = 89|
|4) Divide the sum by 10 and take the rest (rest = sum modulo 10)|rest of (89 %10) = 9|
|5) count 10 minus rest = number |10 - 9 (rest) = 1|
|6) Divide the number by 10 and take the rest; control digit = number modulo 10|1 % 10 = 1|
|the complete parcel number including controldigit:|10052556876 1|

**Comment by metas-lc** [comment]
IT
checked the already existing entries. Used a check digit calculator to verify if the check digit is correct OK
checked the unit test. since the length will always be 11, it's OK no additional tests to add
