### ISSUE TITLE
webui: Client window: EMail fields layout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#3996]
### What is the current behavior?
Check Client window: https://w101.metasfresh.com:8443/window/109/1000000

Fields needed to configure the EMail server are spread all over.
![image](https://user-images.githubusercontent.com/1244701/39628941-3e06218a-4fb3-11e8-8502-b010dc039fdc.png)

### What is the expected or desired behavior?
* please group then in one "box"
* i would suggest to make them advanced fields (none of those are needed in basic layout)
* take out EMail button and just make the process related

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* all Email related fields are now grouped in one "box": OK
* all are advanced fields: OK
* EMail button taken out, process for sending Test Email in Actions: OK
