### ISSUE TITLE
New Report for Yearly Bonus

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4000]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no report about the contract type for yearly bonus.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a report for the controlling of yeary bonuses. The report shall show the bonuses that shall be invoiced
- Manufacturer, Businesspartner
- Product No.
- Purchased Quantity
- Invoicing Schedule, Invoiceing Date
- Contract details
- Grouped by Manufacturer, Businesspartner, Month, Product Value

**Comment by metas-ts** [comment]
hi @metas-lc  here are some hints:
* The report is based on C_Invoice_Candidate. 
* The bonusses that shall be invoiced are `C_Invoice_Candidate`s which reference (via AD_Table_ID and Record_ID) `C_FlatrateTerms` that have `Type_Conditions='Refund'`
  * as of now, the refund-type is created here https://github.com/metasfresh/metasfresh/commit/8bb0b05eb0e8be2b3bc35c3bb6d8d06289997484 (branch `gh4001-app`)
* Please clarify with @metas-mk : 
  * shall the report show just the bonus, or 
  * shall it also show the details on which the bonus is based? 
     * In that case: the bonus is based on other ("normal") C_Invoice_Candidates that are linked via a not-yet existing table (but will come very soon)

**Comment by metas-lc** [comment]
about the report: Rückvergütung
0. it has 4 parameters: bpartner, product, date from, date to. None is mandatory
1. data is grouped by BPartner (you will see each bpartner will start on a new page)
2. data is also grouped by manufacturer, product, month to invoice . On each line
3. contains: (note that there are 2 types of IC: normal - of your sales order and Refund one, from contract. There can be more normal ICs linked to 1 refund)
Title
bpartner name: taken via normal IC billbpartner_id
manufacturer: taken via product.manufacturer 
product value: taken via normal IC.m_product_ID
month: taken via Refund IC.DateToInvoice (format mm.yyyy)
scheduler: taken via Refund IC.C_InvoiceSchedule_ID
contract details: startdate - enddate via Refund IC's contract
qty ordered: via normal IC.qtyOrdered (sum)
amt to invoice:  via Refund IC.netamttoinvoice (sum)
amt invoiced: via normal IC.netamtinvoiced (sum)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. 4 parameters: bpartner, product, date from, date to. None is mandatory: 
* all data is shown (if existing) when no params set: OK
* data correctly taken for params if set: date to is cut off: NOK
2. data is grouped by BPartner (you will see each bpartner will start on a new page): OK
* bpartner name: taken via normal IC billbpartner_id
3. data is also grouped by manufacturer, product, month to invoice . On each line: OK
4. content:
* manufacturer: taken via product.manufacturer: OK
* product value: taken via normal IC.m_product_ID: OK
* month: taken via Refund IC.DateToInvoice (format mm.yyyy): OK
* scheduler: taken via Refund IC.C_InvoiceSchedule_ID: OK
* contract details: startdate - enddate via Refund IC's contract: enddatecut off, NOK
* qty ordered: via normal IC.qtyOrdered (sum): OK
* amt to invoice: via Refund IC.netamttoinvoice (sum): OK
* amt invoiced: via normal IC.netamtinvoiced (sum): OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* contract details: startdate - enddate via Refund IC's contract: enddate displayed fully: OK
* en_US version: invoice schedule not translated, "quartalsweise": => not translated in general

**Comment by metas-lc** [comment]
Seem to be some problems with the language that gets to the report. It looks like it's always DE, but, if you have report.properties (a default one) and report_en_US.properties, the EN one is taken. If you have report_de_DE.properties - this is taken. 
Somehow, in this case, seems the default one is ignored
have to check..

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

* de_DE version: modal with parameters is de_DE, and report itself also de_DE: OK
* last 2 column headers in de_DE are switched: shall be "Abzurechnen" first and then "In Rechnung gestellt" last: NOK

**Comment by metas-dh** [comment]
Results of IT4
tested in mf15

* last 2 column headers in de_DE are in the correct order:  "Abzurechnen" first and then "In Rechnung gestellt" last: OK
