### ISSUE TITLE
Calculate Purchase price with yearly Bonus

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4001]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In the modal Overlay of Purchase orders in Sales Order Window, we show the calculated Purchase Price of the Product and Vendor.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
If a vendor has a yearly bonus contract, then the price shall respect the expected yearly bonus for the purchase price.

**Comment by metas-ts** [comment]
# In the swing client
![image](https://user-images.githubusercontent.com/1264789/40257209-9cb5a7ba-5aed-11e8-8775-6fee23507373.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
1. product used for bonus contracts, with resp. prices (sales price: 3.00, purchase price: 2.00)
2. created flatrate terms with contract type: Bonus for the resp. bpartners (=> bonus: 1%, invoice schedule: quarterly, see #3999)


Test:
1. create sales order, for the product, price: 3.00
2. create purchase order from sales order: 
=> purchase price in modal overlay: 1.98: OK
3. check created purchase order: 
=> normal price: 2.00, "Rohertragspreis": 1.98: OK (only shown in Swing, missing in WebUI: #4089)
4. create a manual purchase order, for the bpartner with the contract, and the product:
=> normal price: 2.00, "Rohertragspreis": 1.98: OK (only shown in Swing, missing in WebUI: #4089)
5. create a manual purchase order, for the bpartner **without the contract**, and the product:
=> normal price: 2.00, "Rohertragspreis": 2.00: OK
6. check Invoice Candidate:
=> normal IC for sales order: price: 3.00, invoice schedule: after delivery, invoicing date: 31.12.9999: OK
=> normal IC for purchase order: price: 2.00, invoice schedule: after delivery, invoicing date: 31.12.9999: OK
7. create material receipt for the purchase order, check the IC again:
=> normal IC for purchase order: price: 2.00, invoicing date: date of test: OK
=> IC for bonus contract: price: 0.02, tab Refund Assignment: relation to contract and to normal IC of PO: OK (latter only shown in Swing, missing in WebUI: #4089)
8. change the invoice schedule for the sales order IC to immediate:
=> invoicing date: date of test: OK
=> IC for bonus contract: price: 0.03, tab Refund Assignment: relation to contract and to normal IC of SO: OK (latter only shown in Swing, missing in WebUI: #4089)
9. change the invoice schedule for the sales order IC to immediate back to after delivery:
=> invoicing date: set back to 31.12.9999: OK
=> IC for bonus contract: still existing, shall be deleted: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

9. change the invoice schedule for the sales order IC to immediate back to after delivery:
=> invoicing date: set back to 31.12.9999: **OK**
=> IC for bonus contract: still existing, the invoicable amount is now set to zero: in my case the amt to be invoiced from the material receipt was substracted, but the invoicable amount was not set to 0.00: have to check with a new case if this works
10. ICs for bonus contract: aggregation group is set: **OK**
11. change the invoicing date override in the ICs from the orders to after the quarterly invoice date: new IC for the contract is created: did not work for my cases, metas-ts checking why

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

9. change the invoice schedule for the sales order IC to immediate back to after delivery:
* IC for bonus contract: still existing, the invoicable amount is now set to zero: worked fine in a new case i created: **OK**

11. change the invoicing date override in the ICs from the orders to after the quarterly invoice date (quarterly invoice date was 01.08.2018, set it to 15.08.2018): => new IC for the contract is created: 
* new IC for the contract was created: **OK**
* delivery date in the new IC for the contract: 30.10.2018 (end of next quarter): **OK?**
* invoicing date eff. in the new IC for the contract: 30.01.2019 (end of the quarter after next): **why?** would have expected 01.11.2018, beginning of quarter after next

**Comment by metas-dh** [comment]
created follow up for the problem(?) with the delivery & invoice date: #4363
