### ISSUE TITLE
Adjust Window "Der Kurier Versandauftrag"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4003]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The Window "Der Kurier Versandauftrag" does not meet the WebUI Guidelines.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Adjust the Window. Add Translations

**Comment by metas-lc** [comment]
IT
TL: mandatory, important OK
TR: flags OK
BR: org, client OK
included tabs: white background OK
trl: both de and en OK
