### ISSUE TITLE
WebUI: Adjust new Window Discount Schema Pharma

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4004]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The new Window Discount Schema Pharma is not Translated to de_DE. Widget sizes are not set properly in Grid View. Layout Guideline Conventions are not met.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Adjust the Discount Schema Pharma Window in WebUI.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* translated to de_DE: Header and Tabs translated: OK, but: Accumulation Level: in single view it's "Position", while in grid view it's "Line": NOK i think

![2018-05-09 09_08_22-metasfresh](https://user-images.githubusercontent.com/18696715/39800608-a9d2912e-5368-11e8-9f49-818c9b654e01.png)

![2018-05-09 09_08_06-metasfresh](https://user-images.githubusercontent.com/18696715/39800618-af09c59a-5368-11e8-9530-0588d3f377d1.png)

* Widget sizes set properly in Grid View: OK? different from normal Discount!

**Comment by metas-dh** [comment]
checked with metas-mk: OK, customer wanted it like this
