### ISSUE TITLE
Improve callout org.compiere.model.Callout_AD_Column

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4009]
*  Followup for https://github.com/metasfresh/metasfresh/issues/3312

### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, this callout is not webui - friently and it leads to npe when adding new entries via webui.
#### Which are the steps to reproduce?
* GO to table and column window
* New column
* Select an AD_Emelent 
* => NOK: NPE
### What is the expected or desired behavior?
* Please, make this callout webui friendly.

**Comment by metas-rc** [comment]
To be solved in https://github.com/metasfresh/metasfresh/issues/4359

**Comment by metas-rc** [comment]
Results of IT: 

No more NPE> It was solved in the other task.

**Comment by metas-lc** [comment]
callouts, while testing https://github.com/metasfresh/metasfresh/issues/4359 were fine. No issues wiht yes/no columns 
OK
