### ISSUE TITLE
Multiple shipment lines for one order line all have the order line's TU-Qty

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4028]
### Is this a bug or feature request?
Bug
### What is the current behavior?

* Create a partial shipment line for an order line (without picking any HUs!)
* Create a second (partial) shipment line for the same order line (ofc again without picking any HUs!)

=> both shipment lines have the "full" order line's TU-qty

### What is the expected or desired behavior?

The second shipment line should have the order line's TU-qty *minus* the first shipment line's TU-qty.

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

1. partial shipment completed, new shipment created:
* correct Qty product (QtyOrdered - QtyDelivered): OK
* correct Qty TUs (QtyOrdered - QtyDelivered): OK
2. partial shipment not yet completed, new shipment created:
* bpartner with shipment aggregation=Y: 
   * another shipment line for the remaining Qty product is added, in the existing shipment: OK
   * remaining QtyTU is added to the already existing QtyTU, in same shipment line: OK
* bpartner with shipment aggregation=N: new shipment created with correct Qty product (QtyOrdered - QtyDelivered) and correct Qty TUs (QtyOrdered - QtyDelivered): OK
3. partial shipment after picking, new shipment created:
* correct Qty product (QtyOrdered - QtyDelivered): OK
* correct Qty TUs (QtyOrdered - QtyDelivered): OK
* when shipment after picking not completed, and bpartner with shipment aggregation=Y: added to remaining shipment, as described above: OK
* when shipment after picking not completed, and bpartner with shipment aggregation=N: new shipment created with correct Qty product (QtyOrdered - QtyDelivered) and correct Qty TUs (QtyOrdered - QtyDelivered): OK
4. QtyPicked remains set until shipment is completed, after both picking and shipment draft generated from Gear: OK
5. no shipment created with param: use QtyPicked, and QtyPicked:0: OK (but no info for the user)
6. quickly checked #3880: still working the same
