### ISSUE TITLE
Add easy way to add AD_Users to Newsletter marketing campaigns

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4031]
### Is this a bug or feature request?
FR
related to https://github.com/metasfresh/metasfresh/issues/4015

### What is the expected or desired behavior?

* Add checkbox "default-newsletter" to MKTG_Campaign. Just one active record with Y allowed per org
* Add "newsletter column in AD_User
  * if checked then the user is automatically added to that default newsletter campaign (of its resp AD_Org, or fallback to AD_Org_ID=0); if there is no newletter-campaign at all, show a helpful message.

Hints: 
* check out how MKTG_ContactPerson_CreateFrom_AD_User does it
* if a user is added, also create a `MKTG_.._Consent` record if none exists yet.
* if unchecked, the user is removed again; please extend `CampaignRepository` accordingly

**Comment by metas-lc** [comment]
IT
IsDefaultNewsletter is in marketing campaign window OK
but not translated:
https://github.com/metasfresh/metasfresh/issues/4200
