### ISSUE TITLE
Show Pricing Conditions of Business Partner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4032]
### Is this a bug or feature request?
FR

### What is the current behavior?
Currently, there is the possibility to define detailed Pricing Conditions for Customers and Vendors in metasfresh (extended discount_schema and pricing rules). Ther is no possibility to quickly and directly compare conditions among each other. Use Case: Customer calls and asks if a product is available and which to price/ conditions. The sales user must be able to answer quickly.

#### Which are the steps to reproduce?
Open, try and see.

### What is the expected or desired behavior?

- [x] The product availability can be seen in Material Cockpit. 
- [x] The user shall be able to search for a Product No. or part of a product name
- [x] The user be able to select 1 or more lines and call a quick action for the pricing conditions.
- [x] The pricing conditions shall show the following information (row selected, All customer conditions, all vendor conditions, ordered by last shipment/ receipt date desc for the product, filter for isCustomer/ isVendor)

The conditions shown are:

- [x] Date of the last shipment/ receipt for this partner and product
- [x] Date created of the pricing condition
- [x] Quantity Break
- [x] Price Net
- [x] Price Base
- [x] Discount
- [x] Fixum
- [x] Skonto
- [ ] (Margin)
- [x] CreatedBy of the pricing condition

**Comment by metas-lc** [comment]
IT 
1. The user shall be able to search for a Product No. or part of a product name
=> Filter by product name and key? 

2. The user be able to select 1 or more lines and call a quick action for the pricing conditions.
Material Cockpit window, select 2 products, press on Pricing Conditions 
=> discounts schema are shown for all products that you selected and also have schema OK

3. The pricing conditions shall show the following information (row selected, All customer conditions, all vendor conditions, ordered by last shipment/ receipt date desc for the product, filter for isCustomer/ isVendor)
row selected ?
All customer conditions OK
all vendor conditions OK
ordered by last shipment/ receipt date desc for the product NOK? (the selected ones are vendors, rest customers)
![image](https://user-images.githubusercontent.com/16001666/41045100-57995aa6-69b0-11e8-875f-858865f59ec0.png)

filter for isCustomer/ isVendor OK
.
future discounts are visible. I think it's OK
flat discounts are not visible OK
.
4. The conditions shown are:
    Date of the last shipment/ receipt for this partner and product OK
    Date created of the pricing condition OK
    Quantity Break OK
    Price Net OK
    Price Base OK
    Discount OK
    Fixum OK
    Skonto OK
    (Margin) not yet 
    CreatedBy of the pricing condition NO
2 of    Price Net,  Price Base and Fixum are the same... OK?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. pricing conditions for bpartners shown in Material Cockpit, for 1 or more selected products: OK
2. correct details displayed:
* Date of the last shipment/ receipt for this partner and product: OK
* Date created of the pricing condition: OK
*  Quantity Break: OK
*  Price Net: OK
*  Price Base: OK
*  Discount: OK
*  Fixum: OK
*  Skonto: OK
*  CreatedBy of the pricing condition: OK, now also displayed
