### ISSUE TITLE
Pharma: MSV3 Purchase Functionality in purchase candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4033]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, MSV3 Purchase Order can only be created via Sales Orderlines.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?

- [x] Provide the functionality of MSV3 orders also in purchase candidates.
- [x] Make sure that purchase candidates are created via Material Dispo.

**Comment by metas-dh** [comment]
Related problems found while testing:

https://github.com/metasfresh/metasfresh/issues/4172

1. releasetest, 5.60
* the purchase order is created before the sales order is completed, not just the purchase disposition
=> NOK
2. cloudit, 5.61
* no purchase disposition is created at all
=> NOK

**Comment by metas-lc** [comment]
note: still happening:
>the purchase order is created before the sales order is completed

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
* product set as "Eingekauft"=Y
* bpartner as current vendor for this vendor
* product prices for sales & purchase 

Test:
1. Sales order for the product: shipment schedule is created: OK
2. Check Material Dispo: no entries, NOK
3. Event Log: entry for shipment schedule (shall trigger the creation of purchase cands, in Material Dispo): OK

**Comment by metas-dh** [comment]
Update:
* => purchase candidate was created the next day: OK

5. Material Dispo: check:
* tab Einkaufsdetail: purchase candidate: empty, no info about the candidate: why? NOK i think

6. Purchase Candidate: run action "Create Purchase Order": OK
* prepared=Y after create purchase order: OK
* zuordnung: remains empty, no reference / relation to purchase order?
* no purchase order?

7. Run action "Create Purchase Order for selection": OK
* candidate has purchased=Y: OK
* entry in Zuordnung for PO: OK
* purchase order created: OK

8. New entry in Material Dispo:
* reference to PO: OK
* reference to  purchase order cand: OK
* reference to the first material dispo entry: OK

**Comment by metas-dh** [comment]
problem:
sales order is reactivated and completed again:
* new entries in Material Dispo, for the same sales order, with same qty demand of the same product: NOK, still only the qties from the original entries needed
* new purchase candidate is created, every time the sales order is reactivated (same qty of the same product): NOK, only the first candidate is needed
* purchase order(s) for the old(er) purchase candidates are created, and the candidate marked as purchased, when the order is reactivated and completed again: NOK i think

**Comment by metas-dh** [comment]
9. Have Qty planned (ATP) for the product ordered in sales order (purchase order & receipt with qty: 100 planned for end of the day, sales order with qty: 50, and date provisioned & promised for the next day):
* Material Dispo entries for the sales order, for demand: OK
* no new Material Dispo entry created for the supply, purchase side (old one existing from the already existing purchase order): OK
* no purchase candidate created: OK

10. Order more qty than will be on hand for date provisioned & promised in 3 days, midday (sales order with qty: 70):
* Material Dispo entries for the sales order, for demand: OK
* new Material Dispo entry created for purchase side, for the supply needed: OK
* correct qties: original ATP: 100, 1st sales order 50: 2nd sales order: 70: => needed qty: 20, OK
* purchase candidate created for the 2nd sales order: OK

**Comment by metas-dh** [comment]
Update:
11. Attributes in sales order considered correctly in purchase candidates: 
* attributes cannot be set yet in product planning, see #4321 
* attributes in purchase order from purchase cands are not as set in sales order, but as set in attribute set instance, see #3657 
=> to be tested when these issues are solved

checked with metas-ts: 
=> Provide the functionality of MSV3 orders also in purchase candidates: already running in UAT, not to be tested anymore
