### ISSUE TITLE
Add CustomerCode and CollectorCode to Der Kurier

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4034]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
* Add to DerKurier_DeliverOrderLine and to DerKurier config
  * Auftraggeber/CustomerCode
  * Abholer/CollectorCode
* Show them on the DerKurier-Label; the attached pdf 
[Label-020602000000.pdf](https://github.com/metasfresh/metasfresh/files/1986599/Label-020602000000.pdf) has the "Auftraggeber:" and "Abholer:" fields...that's where to add the two new codes.

Hints: 
* add the two new fields to DerKurierConfig and DerKurierDeliveryData
* add them to new delivery orders in DerKurierDraftDeliveryOrderCreator
* store/load them using the DerKurierconfigRepository and DerKurierDeliveryOrderRepository.

**Comment by metas-lc** [comment]
IT
Customer Code and Collector Code are not shown in der kurier order line tab NOK?
Customer Code and Collector Code are shown in der kurier konfig (shipper window) OK

set some numbers in der kurier konfig, created a new der kurier order
checked the database => Customer Code and Collector Code are set correctly OK

**Comment by metas-ts** [comment]
> Customer Code and Collector Code are not shown in der kurier order line tab NOK?

no, please display them

**Comment by metas-lc** [comment]
IT
0. go to shipper window, select der kurier shipper: set Customer Code and Collector Code, also a bpartner
1. create a transportation order, type: der kurier shipper
2. create a new sales order, complete
3. go to related docus: go to picking terminal
4. pick HU and process it
5. go to picking tray clearing
6. select your HU and action: take out HU, then action transport, ship and invoice
=> der kurier order is created 
=> fields are shown in orderline: Customer Code and Collector Code are set like in shipper
OK
