### ISSUE TITLE
Manual discount for orderline not working anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4055]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Manual discount for orderline is not working anymore, the dicount you set is set back to 0.
#### Which are the steps to reproduce?
Try http://docs.metasfresh.org/webui_collection/EN/Order_line_discount.html
### What is the expected or desired behavior?
Shall work.

**Comment by cristinamghita** [comment]
@metas-dh the problem does not exist in master anymore.

**Comment by metas-dh** [comment]
checked in latest e2e: working fine again, closing this issue.
