### ISSUE TITLE
exception handling: make them more translatable

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4071]
### Is this a bug or feature request?
FR
triggered by https://github.com/metasfresh/metasfresh/issues/4063

### What is the expected or desired behavior?
use ITranslatableString as exception messages.

### Note to IT
nothing to test. e2e is sufficient. Pay attention to exception/error messages. They shall be like before, if not sexier.

**Comment by metas-lc** [comment]
e2e was fine OK
checked an error message when you try to order more than the credit limit => message was fine OK
