### ISSUE TITLE
Contact is not set when order is cloned

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4079]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The partner & invoice contact is not set when an order is cloned.
#### Which are the steps to reproduce?
Case No. 1
1. Create e.g. a sales order, set the contact in bpartner field and invoice partner field
2. Clone the order => contact in the new order is empty, in both partner and invoice partner field: NOK

**Comment by metas-lc** [comment]
IT
1. created 2 contacts to bpartner A: contact c1 and contact c2
2. created a new order, set bpartner A, set contact c1 to bpartner field and contact c2 to invoice partner field
3. clone order
=> contacts are added OK
4. add a product, complete order, clone again
=> contacts are added OK
5. clone an order without contacts
=> contacts are not added OK
