### ISSUE TITLE
create relation from candidate to refund-candidate

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4085]
### Is this a bug or feature request?
FR

### What is the current behavior?

In the Rechnungsdispo Window we have a tab "Zuordnung Rückvergütung" that contains the table 
C_Invoice_Candidate_Assignment.
Via this tab for each refund-invoice candidate you can see the "normal" ICs that are assigned to it.

### What is the expected or desired behavior?

I think we need a relation type fior the oppisite direction, i.e. if an IC is assigned to a refund-IC, then we should be able to zoom from that candidate to that refund-candidate.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* relation in normal IC to refund-IC, if existing: relation in referenced docs / Zoom into: OK
* relation in refund-IC to normal IC: in tab "Zuordnung Rückvergütung" : OK
