### ISSUE TITLE
Create missing fields for Bonus in WebUI

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4089]
### Is this a bug or feature request?
FR
### What is the current behavior?
Currently there are 2 fields missing in WebUI, for Bonus (Rückvergütung):

- [x] purchase order: "Rohertragspreis" missing in orderline
- [x] invoice candidate: "Zugeordneter Rechnungskandidat" missing in tab Refund Assignment

#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Pls add the missing fields (en_US trl as well)

**Comment by metas-lc** [comment]
IT
purchase order: Rohertragspreis (Gross profit price) is shown in both gridview and advanced edit OK
invoice candidate, tab Refund Assignment: "Zugeordneter Rechnungskandidat" (Invoice Candidate Assigned ID) is shown in both gridview and advanced edit OK
