### ISSUE TITLE
sync mail address between contactperson and linked user

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4092]
### Is this a bug or feature request?
FR
follow-up of  https://github.com/metasfresh/metasfresh/issues/4031

### What is the current behavior?
* AD_User and MKTG_ContactPerson have their own respective EmailAddress field
* change one, and the other one will remain unchanged

### What is the expected or desired behavior?

* if an AD_User is linked to >=1 MKTG_ContactPerson
  * and you change the AD_User's Email address, 
  * then only update those MKTG_ContactPersons that have the same email address which the AD_User had

* if an AD_User is linked to >=1 MKTG_ContactPerson
  * and you change one MKTG_ContactPerson's email address
  * and the AD_User has the same email-address that the MKTG_ContactPerson had be fore the change
  * then update the AD_User's email address (but don't update the other MKTG_ContactPersons)

**Comment by metas-lc** [comment]
IT
1. have a user A without email
2. create a new Marketing contact person MKTG1 for user A
=> it has no email
3. set an email to the user A
=> email was set to MKTG1 as well OK
4. create another marketing contact person MKTG2 for user A
=> it has no email (was not required to have) OK
5. set another email to MKTG2 
=> user A and MKTG1 still have the old email. Nothing changed OK
6. change the email of User A
=> MKTG1 updated it's email OK
=> MKTG2 kept it's email OK
7. create more marketing contact persons for User A (same and different email), and some for User B (same and different email from user A)
8. change the email of User A
=> only the marketing contact persons with user A and same email got updated OK
9. change the email of a marketing contact person that has the same email as the user and same user
=> user and other marketing contact persons with user A and same email got updated OK
10. change the email of a marketing contact person that has different user
=> User A did not change, as well as other marketing contact persons OK
11. have a user with no email, create a new marketing contact person and add an email
=> user has now the same email OK
12. remove the email from this new marketing contact person
=> user has no email OK
13. set the email back (user has now email) and delete the marketing contact person
=> user still has email OK
