### ISSUE TITLE
Create Mandatory Logic in Contract terms

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4094]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently there are mandatory fields in WebUI not shown for Contracttype Refund.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The Fields shall not be shown, but need a mandatory Logic not for Contract Type Refund.
- Rechnungsstellung
- Behaviour when extending

**Comment by metas-lc** [comment]
IT
1. create an abo contract term
=> Invoice Rule and Behaviour when extending are mandatory. Data is saved after you set them OK
2. create a Refund contract term
=> Invoice Rule and Behaviour when extending are hidden. Data is saved without setting them OK
