### ISSUE TITLE
webui: Purchase schedule tab - trl and display 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4102]
### Is this a bug or feature request?
fr
### What is the current behavior?
follow-up of https://github.com/metasfresh/metasfresh/issues/4056
#### Which are the steps to reproduce?
1. open Business Pharma window (540409), go to vendor tab - advanced edit
=> Aggregate Purchase Orders - missing trl for DE 
2. go to Purchase schedules tab
=> see "Reminder Time in" field. Shall also contain "min" or smth 
(de version: "Wiedervorlage (min)")
3. if you set Frequency Type on weekly, then day of the month should hide
### What is the expected or desired behavior?
trl, add "min" and hide "day of the month"

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. open Business Pharma window (540409), go to vendor tab - advanced edit
=> Aggregate Purchase Orders: translated in de_DE: OK
2. go to Purchase schedules tab
=> see "Reminder Time in" field: also containing "(min)": OK
(de version: "Wiedervorlage (min)")
3. if you set Frequency Type on weekly, then day of the month should hide: OK
