### ISSUE TITLE
WebUI: Translation Window for Tax Rates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4116]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Translation window for Tax Rates is not available in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Tax Rate Translation and add to WebUI Menu. Add the translations in en_US for Tax Rates.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new Window for Tax Rate Translation: OK
* add the translations in en_US for Tax Rates: tax rates are not translated in en_US, all de_DE: NOK

**Comment by metas-mk** [comment]
> add the translations in en_US for Tax Rates: tax rates are not translated in en_US, all de_DE: NOK

This will be done in collection Issue later for all translateable records on client/ org level.
