### ISSUE TITLE
WebUI: Add missing Translations in Product Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4117]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are some untranslated Fields for en_US  in Product Window in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the translations.
![image](https://user-images.githubusercontent.com/13365687/40613760-2628b14c-6280-11e8-8118-d4f5323bd403.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Add Translations in Product Window: missing translations are added: OK
