### ISSUE TITLE
updating record to not match tab where clause leads to error when PKs are different

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4134]
### Is this a bug or feature request?
bug

### What is the current behavior?

IT - Part2

extension of test case 2. of #4073 

2.1. Using the virtual tab together with a tab filter 
- have a virtual tab in a window where the PK is not the PK of the virtual tab. i.e. request tab in window order
- have another virtual tab in a window order with template request 
- put a where clause showing only requests that ARE completed. `r_status_id = <ID>'
- now you got two tabs. one shows open requests the other one shows closed ones
- add a new request which has the status open
- OK: it appears in the open request tab
- edit it via advance edit and close it
- OK:status is set to closed
- NOK: request is still displayed although it is not matchin the criteria anymore
- workaround: server cache reset
- **Info**: when the PK of the parent tab and the virtual tab are the same the filtering works fine

```
console:
validStatus
:
{valid: false, reason: "No document found for /W143/1000954/T541123/R1088038"}
reason
:
"No document found for /W143/1000954/T541123/R1088038"
valid
:
false
```

### What is the expected or desired behavior?
1. record should be filtered
1. tab schould be updated
1. document should be valid

**Comment by teosarca** [comment]
Note to IT:
* pls do regression on changing documents in webui. basically one e2e is enough to cover the cases.
