### ISSUE TITLE
WebUI: Add Document References to all Windows with Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4135]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are different Windows in WebUI that show Translations for Master Data but not all are referenced from the underlying Master Data Window.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the document References for those windows.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Document References to all Windows with Translations:
* BOM: OK
* Tax Rate: OK
* Tax Category: OK
* UOM: OK
* Product: OK (Product Translation & Product BPartner Translation)
* KPI: ??

**Comment by metas-dh** [comment]
* Payment Term: OK
* Dunning Level: OK

=> Document References to Master Data Windows, from Translation Windows: not needed (checked with metas-mk)
