### ISSUE TITLE
WebUI: Translation Window for Paymentterm

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4138]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Paymentterm Translations
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Translations of Paymentterms.

**Comment by metas-lc** [comment]
IT
1. open Paymentterm Translations window 
=> grid view: order by payment term and language asc 
=> TL: important, mandatory
=> TR: flags
=> BR: org, client
=> window is translated in both EN and DE 
OK
