### ISSUE TITLE
WebUI: Translation Window for Dunning Level

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4139]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Dunning Levels
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Translations of Dunning Level.

**Comment by metas-lc** [comment]
IT
1. open Dunning Level Translation window 
=> grid view: order by Dunning Level and language asc 
=> TL: important, mandatory
=> TR: flags
=> BR: org, client
=> window is translated in both EN and DE 
OK
