### ISSUE TITLE
WebUI: Translation Window for Country

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4140]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Countries
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Translations of Countries.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for Translations of Countries: OK
* referenced in window Country: OK
* Translations of Countries is read-only (like Country window): OK
* "Land Übersetzung" also in en_US menu: NOK, pls add the resp. translation

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* "Country, Region Translation" now in en_US menu: OK
