### ISSUE TITLE
WebUI: Translation Window for Currencies

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4141]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Currencies
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Translations of Currencies.

**Comment by metas-lc** [comment]
IT
Currency Translation window is in finance/settings OK
TL: important, TR: flags, BR: org and client OK
referenced documents from Currency to Currency Translation exists OK
(but it doesn't have trl: https://github.com/metasfresh/metasfresh/issues/4198)
