### ISSUE TITLE
WebUI: Translation Window for Document Types

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4142]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Document Types
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Document Types.

**Comment by metas-lc** [comment]
Document type Translation window is in system/settings OK
TL: important, TR: flags, BR: org and client OK
referenced documents from Document type to Document type Translation exists OK
(but it doesn't have trl (Belegart Übersetzung): #4199)
