### ISSUE TITLE
WebUI: Translation Window for Messages

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4143]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no window for the maintenance of Messages
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a new Window for Messages.

**Comment by metas-lc** [comment]
IT
Message Translation window is in system/settings OK
TL: important, TR: flags, BR: org and client OK
referenced documents from Message to Message Translation exists OK
(but it doesn't have trl (Meldung Übersetzung): https://github.com/metasfresh/metasfresh/issues/4199)
