### ISSUE TITLE
User query: IUserQueryRestriction is not built properly all the time

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4149]
### Is this a bug or feature request?
Bug
### What is the current behavior?
IUserQueryRestriction is not built properly when we have more than one segment and the code does not start with 'AND'
So the filter will not work.
#### Which are the steps to reproduce?
Create and user query for C_Invoice_Candidate that has this code:
```<^>InvoiceRule<^> LIKE <^>D<^><~>AND<^>Bill_BPartner_ID<^>=<^>2156423<^>```
### What is the expected or desired behavior?
Even if you write 
```<^>InvoiceRule<^> LIKE <^>D<^><~>AND<^>Bill_BPartner_ID<^>=<^>2156423<^>```
and not
```AND<^>InvoiceRule<^> LIKE <^>D<^><~>AND<^>Bill_BPartner_ID<^>=<^>2156423<^>```
the filter shall work

**Comment by metas-lc** [comment]
IT
1. create a new user query, for rechnungskandidat table and invoice candidates tab
2. add query from example: <^>InvoiceRule<^> LIKE <^>D<^><~>AND<^>Bill_BPartner_ID<^>=<^>2156423<^>
=> works OK
3. regression: add same query with AND in front
=> works OK

(note: had to do cache reset to see the changes)
