### ISSUE TITLE
Serial Letter Feature

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4153]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Serial Letter Feature in metasfresh.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
use new marketing campaign structure
current concept:
- use new marketing campaign structure
- for each serial letter create a marketing campaign
  - type letter
  - put a text template (static template is fine for the first iteration but a dynamic one is preferred and wanted)
- analog to marketing the user goes into either user or partner window and runs an action selecting a campaign
  - if the campaign is a serial letter PDFs are created using the text templates and printed into one big PDF
- the user gets a notification with a link to the pdf containing all the letters
- serial letter PDFs are created in 200er batches

**Comment by metas-ts** [comment]
Hi @cristinamghita ,
here are some hints:
* introduce a new entity type such as `de.metas.marketing.serialletter` (analog to `...cleverreach`) and use it for e.g. the process (if you create one) and generally everything that is just for serialletters
* take a look at the `ContactPerson`'s address; there is already an email address. Add the postal address in a similar fashion.
* add the serialletter code to a new project, analog to marketing-cleverreach (but the postal address code can remain in marketing-base, like the emailaddress)
* try to separate the serial letter feature from marketing-base.
  * take a look at PlatformClient; it's intended foor Cleverreach, MailChimp etc..i suggest not to try to extend it, but add something similar with serialletter-specific functions. We might still later dercide to merge the two, but I'm not sure at all it it makes sense.
* try working with the assumption that the code in marketing-serialletter has **no DB-access** to any of the `MKTG_` tables. I.e. include all the infos (postal address and an ID of the boilerplate to use) in the pojos that you invoke the serialletter-service with.
  * why: we will probably turn cleverreach, serialletter and future extensions into event-driven standalone services. Also 3rd parties wiithout any access to the metasfresh-DB might write their own services.

**Comment by cristinamghita** [comment]
@metas-ts  Thank a lot for the input! it is very helpful!

**Comment by cristinamghita** [comment]
# Concept
## Functional Concept
* User will run the process 'Kontaktperson aus Nutzer', which will add also postal addess(rendered)
* From Marketing Campaign window, the user will run a process which will generate letters and archive them. In the end, this process will trigger the concatenation of generated pdfs
  ** in Marketing Campaign will be possible to add a boiler plate
* When the process is done(background process), user will receive a notification.
## Technical concept
* Will modify process de.metas.marketing.base.process.MKTG_ContactPerson_CreateFrom_AD_User to add in ConctactPerson also the Address
  *  this implies that we add field Address in MKTG_Campaign_ContactPerson
* Create a process for generating letters and archive them(async)
* Create a process for concatenating the pdf generated previously(async)
  * this process will start automatically when the one of generating letters is done and will enqueue printing enqueues, using as async batch parent the async batch of the previous process
* When the async batch will be processed, the user will receive a notification

**Comment by metas-ts** [comment]
hi,
> User will run the process 'Kontaktperson aus Nutzer', which will add also postal addess(rendered)

i suggest to discuss this with @teosarca because maybe it makes sense to just copy the C_Location_ID to avoid the need to keep 2 addresses in sync.
we might still add an "edit address" action where the user can edit the address and decide if that change shall be "synched" to ad_user or if a new C_Location be added
I guess most users will want to have just one c_location for both ad_user and Mktg_contact person.
however, in the address pojo I would not have the C_Location_ID, unless needed, but rather and address pojo with street, zip etc etc as filed.

**Comment by cristinamghita** [comment]
@metas-ts I wrote Address, because @metasnw wants to have there the rendered address.
But I think you are right. We could use C_Location_ID and we skip this sync issue.

**Comment by metasnw** [comment]
@metas-ts @cristinamghita agree with you guys.
we still can have the rendered address in c_letter so jasper can use it

problem I want to solve: not rendering the address in jasper itself

**Comment by cristinamghita** [comment]
## Configuration
### Create new platform
![image](https://user-images.githubusercontent.com/15378036/41227280-e4e1b172-6d7c-11e8-83f1-43aa6a239cf8.png)
### Create new campaign with a new boiler plate
![image](https://user-images.githubusercontent.com/15378036/41227312-00959da2-6d7d-11e8-8ba5-8457e8045d30.png)
## Dev test
* User will run the process 'Kontaktperson aus Nutzer', which will add also postal addess(rendered)
  * make sure you check the flag 'IsReuiredAddress' in platform
![image](https://user-images.githubusercontent.com/15378036/41227536-d8d41c0c-6d7d-11e8-803d-807701e5eedd.png)
* From Marketing Campaign window, the user will run a process which will generate letters and archive them. 
![image](https://user-images.githubusercontent.com/15378036/41227372-295c31d8-6d7d-11e8-8762-806cee25b3a8.png)
* In the end, this process will trigger the concatenation of generated pdfs
* When the process is done, we get a notification.
![image](https://user-images.githubusercontent.com/15378036/41227421-59d555e2-6d7d-11e8-800d-ebc3d7248952.png)
* Click on notification. Printing queue window opens. From actions, run process Opend PDF.
![image](https://user-images.githubusercontent.com/15378036/41227564-f9272ada-6d7d-11e8-91c3-0643d6322bd5.png)

![image](https://user-images.githubusercontent.com/15378036/41227627-2fc79480-6d7e-11e8-96b0-fc3a2dadd8d4.png)

**Comment by metas-dh** [comment]
**SetUP:**
1. Set up PDF printing before testing!
2. Create / have DocOutbound Config with:
 * Table: Letter
 * Print Format: Serial Letter
    * if this is not yet existing, create one, Jasper Process: Serial Letter (=> Advanced Edit in window Print Format) 
=> Server Restart necessary afterwards!

3. Create a new marketing platform, set "Requires Location = 'Y'" see pic above
4. Create a new boiler plate (Textbaustein), with a text to be taken in the serial letter
5. Create a new marketing campaign, and set that boiler plate  (see pic above)
6. Create / have users for bpartners you want to send the letter to (w/ and w/o email address)


**Test:**
1. In bpartner window, run process "Kontaktperson aus Nutzer", for the users you want to send the letter to
2. Check your campaign: => contact persons are added below: OK
3. Open Actions, run process "Create letters": => notification pops up about the PDFs created (took a little <1 min for me, with 3 contact persons)
4. Click on the notification => Printing Queue window opens: OK
5. Run process Open PDF: => PDF opens with the Serial Letter: OK
   * Header: Serial Letter, with date: OK
   * text is taken from your boiler plate: OK
   * address in header is taken from the contact persons: was null for me, NOK

![2018-06-12 11_00_30-1000308](https://user-images.githubusercontent.com/18696715/41282161-ae82c438-6e33-11e8-9ae8-932b0d562863.png)

   
   
question:
* the location for the contact person, in wondow marketing campaign, was only set if location had standard invoice address box checked in bpartner window, not sure why?

**Comment by metas-lc** [comment]
IT
repeated the testcase
=> the action from bpartner was called: Kontakten der ausgewählten Geschäftspartner in Kampagne and had MKTG_Campaign_ContactPerson parameter. There i had to set my campaign OK
=> 4 lines were created in my campaign, for all the users that had bpartner with default invoice location OK
=> after running create letters in campaign i got 1 notification with the printing queue OK
=> open printing queue, run open pdf: a pds with 4 pages is created OK
=> Header: Serial Letter, with date: OK
=>text is taken from your boiler plate: OK
=> address in header is taken from the contact persons default billto locations OK
.
about the question above
>the location for the contact person, in wondow marketing campaign, was only set if location had standard invoice address box checked in bpartner window, not sure why?
- now you don;t get lines in marketing campaign if you don;t have standard invoice address location OK
