### ISSUE TITLE
Extend Billing Candidates Filtering for contracts

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4165]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are some Filter criteria missing in Billing candidates window to efficiently search for data that is used to invoice (Refund) contracts.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the following fields as Filter criteria:
- DocType Invoice
- Invoicecandidate Controller

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new filter criteria in billing candidates: DocType Invoice & Invoicecandidate Controller: OK
* filter working correctly: OK
