### ISSUE TITLE
Pricing Conditions Jasper

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4169]
### Is this a bug or feature request?
fr
### What is the expected or desired behavior?
Pricing Conditions Jasper in bpartner window

**Comment by metas-lc** [comment]
- in address parameter you get all addresses
- fix color
- trl for en (properties)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* address parameter working fine (only addresses of the bpartner are selectable): OK
* Headers have the right colour (black): OK
* properties are correct (de_DE & en_US): OK
* numbers, order etc. in the report are correct (Basis, Skonto etc., all checked in 1st IT but forgot to document, sry): OK
