### ISSUE TITLE
Purchase order from sales order not working as before

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4172]
### Is this a bug or feature request?
Bug
### What is the current behavior?
1. releasetest, 5.60
* the purchase order is created before the sales order is completed, not just the purchase disposition
=> NOK
2. cloudit, 5.61
* no purchase disposition is created at all
=> NOK
#### Which are the steps to reproduce?
see http://docs.metasfresh.org/webui_collection/EN/Create_individual_PO_from_SO.html, Case 1

### What is the expected or desired behavior?
Shall work as described.

**Comment by metas-dh** [comment]
Update: e2e from 11.06.: 5.61: no purchase disposition is created at all: NOK

**Comment by teosarca** [comment]
caused by #4033

**Comment by metas-dh** [comment]
Update: e2e from 19.06.: 5.62: modal for creating purchase cands does not work as before (e.g. qty to purchase cannot be set): checked with metas-ts: no pricing condidtion set for vendor, necessary bc of #4033

**Comment by metas-dh** [comment]
Update:
e2e from 23.07.
* the purchase order is created before the sales order is completed: fixed, purchase order is only created when the sales order is completed, the purchase order candidate is created after action in the modal for the "Create purchase order from sales order" is triggered: OK

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* purchase disposition is created correctly by using the `Create purchase orders` action: **OK**
* no purchase order is created before the sales order is completed, only  the purchase disposition: **OK**
* purchase order is directly created by using the `Create purchase orders` action, when used for an orderline of an already completed sales order: **OK** (see http://docs.metasfresh.org/webui_collection/EN/Create_individual_PO_from_SO.html, Case 2)
* problem described in metasfresh/metasfresh-webui-frontend#1384 also working fine: **OK**
