### ISSUE TITLE
Performance bottleneck at Cache Invalidation

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4177]
### Is this a bug or feature request?
Bug
### What is the current behavior?

Under high load, the webui-api system can become slow (e.g. material receipt takes very long).
When sampling, we see that most of the time is spend in the method `CacheMgt.resetCacheInterfacesNoLock()`

* We think that to solve this, we can index the cache instances per tablename (which is a bit tricky).
* Also there might be a leak where e.g. individual CCaches are not static, but are registered over and over again.
* We also consider to replace the CCache based framework with a modern library

**Comment by metas-rc** [comment]
As discussed,  I will assign this task to  @metas-ts  and he will look into making it testable.

**Comment by teosarca** [comment]
closing because it's too old
