### ISSUE TITLE
WebUI: Show DeliveryRule in Businesspartner Customer and Sales Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4201]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Field DeliveryRule is not shown in Business partner Customer and Sales Order.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Field Deliveryrule to Advanced Edit.

**Comment by metas-lc** [comment]
IT
1. busines partner window, customer tab, advanced edit 
=> DeliveryRule is shown OK
2. sales order, advanced edit 
=> DeliveryRule is shown OK
=> not shown in header or gridview OK
