### ISSUE TITLE
ATP Stock indicator in Sales Orderline

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4212]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no stock indicator in Sales Orderline.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add an ATP Stock indicator in Sales Orderline. It shall show the ATP at the moment of line creation. As soon as the Order is completed, the ATP Information shall be initialized again.

**Comment by cristinamghita** [comment]
### Dev test
* Create a new sales order and add a line
 * notice the new field Qty AvailableToPromise
![image](https://user-images.githubusercontent.com/15378036/41396953-3c55dd6c-6fbb-11e8-845b-c1b29201fa2b.png)

**Comment by metas-ts** [comment]
> As soon as the Order is completed, the ATP Information shall be initialized again.

Note (metas-ts): "initialized" set to zero, right @metas-mk

**Comment by metas-mk** [comment]
@metas-ts 

> "initialized" set to zero, right, @metas-mk ?

right.

**Comment by metas-lc** [comment]
sqls were not applied

**Comment by metas-lc** [comment]
IT
i choose a new product to see how qtys update easier
1.  create/complete a new purchase order and create material receipt for 10 TUs x10
2. create a new sales order, add your product
=> ATP is 100 OK
3. add qty 50, complete
=> ATP is 0 OK
4. create inout using picking
5. create a new sales order and add a line for your product
=> ATP is 50 OK
6. create a new receipt, for 2 TUs x10 with attribute BIO
7. create a new sales order and add a line for your product
=> ATP is 70 OK
8. change attributes and set BIO
=> ATP is 0 OK?
9. update it back to no attributes
=> ATP is 70 OK
.
9. "Update ATP also when C_Order.PreparationDate is changed" - didn't completely test this yet.

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above
=> changing the promised date to future  / past updates qty ATP OK
=> changing attribute to BIO and back - updates qty ATP OK
.
is 0 in some cases for bio. Created task: https://github.com/metasfresh/metasfresh/issues/4335
