### ISSUE TITLE
IFA Product Fields in Pharma Product readonly

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4217]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Product Fields for IFA Product Data are editable.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Make them readonly in Pharma Product Window.

**Comment by cristinamghita** [comment]
**Dev test**
* Open Produkt Pharma window
![image](https://user-images.githubusercontent.com/15378036/42285057-07c1a610-7fb7-11e8-9553-cc8ff376619f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

IFA Product Fields are read only in Product Pharma Window: OK
