### ISSUE TITLE
Lot No. Control without mandatory Product ID

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4220]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Lot-No. Control Action has a mandatory Product ID as Parm.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Allow to run the Process/ Action also without mandatory Product ID.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Lot No. Control with entry that has Product_ID set: works fine
* Lot No. Control with entry that has no Product_ID set: throws error: "Assumption failure: productId > 0 but it was 0": NOK

<details/>:
{timestamp: 1530779283737, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
message
:
"Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
↵Bitte leiten Sie diese Meldung an metas weiter:↵↵Assumption failure: productId > 0 but it was 0"
path
:
"/rest/api/process/ADP_540937/1004658/start"
status
:
500
timestamp
:
1530779283737
trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: productId > 0 but it was 0"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:108)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)"
10
:
"	at org.adempiere.util.Check.assumeGreaterThanZero(Check.java:405)"
11
:
"	at de.metas.product.LotNumberLock.<init>(LotNumberLock.java:47)"
12
:
"	at de.metas.product.LotNumberLock$LotNumberLockBuilder.build(LotNumberLock.java:39)"
13
:
"	at de.metas.product.LotNumberLockRepository.toLotNumberLock(LotNumberLockRepository.java:52)"
14
:
"	at de.metas.product.LotNumberLockRepository.getById(LotNumberLockRepository.java:42)"
15
:
"	at de.metas.product.LotNumberLockRepository$$FastClassBySpringCGLIB$$271364c3.invoke(<generated>)"
16
:
"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
17
:
"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
18
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
19
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
20
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
21
:
"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
22
:
"	at de.metas.product.LotNumberLockRepository$$EnhancerBySpringCGLIB$$85778c96.getById(<generated>)"
23
:
"	at de.metas.ui.web.product.process.WEBUI_M_Product_LotNumber_Lock.createQuarantineHUsByLotNoLockId(WEBUI_M_Product_LotNumber_Lock.java:114)"
24
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)"
25
:
"	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)"
26
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
27
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
28
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
29
:
"	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)"
30
:
"	at java.util.Iterator.forEachRemaining(Iterator.java:116)"
31
:
"	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)"
32
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
33
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
34
:
"	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)"
35
:
"	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)"
36
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
37
:
"	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)"
38
:
"	at de.metas.ui.web.product.process.WEBUI_M_Product_LotNumber_Lock.doIt(WEBUI_M_Product_LotNumber_Lock.java:84)"
39
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)"
40
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
41
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
42
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
43
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
44
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
45
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
46
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
47
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
48
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
49
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
50
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
51
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)"
52
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
53
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
54
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
55
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:285)"
56
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
57
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
58
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
59
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
60
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
61
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
62
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
63
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
64
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
65
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
66
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
67
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
68
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
69
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
70
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
71
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
72
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
73
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
74
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
75
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
76
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
77
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
78
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
79
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
86
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
90
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
92
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
93
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
95
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
97
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
98
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
99
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
[100 … 142]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
102
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
103
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
104
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
105
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
106
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
107
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
108
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
109
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
110
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
111
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
112
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
113
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
114
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
115
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
116
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
117
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
118
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
119
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
120
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
121
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
122
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
123
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
124
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
125
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
126
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
127
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
128
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
129
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
130
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
131
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
132
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
133
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
134
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
135
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
136
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
137
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
138
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
139
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
140
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
141
:
"	at java.lang.Thread.run(Thread.java:748)"
142
:
""
<details>

**Comment by metas-lc** [comment]
IT
1. created receipt with product having lot numbers "888" and "999"
2. created 2 lot controls: one with "888" and product, one with "999" without product
3. ran for each of them "Move Lot. No. to Quarantine Warehouse"
=> 2 distributions orders were created, correct qty OK
=> no errors OK
