### ISSUE TITLE
Recording of Payment Discount instead of Payment Term

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4221]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a lot of Places use the PaymentTerm when wanting to set a Payment Discount.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
- Discount Schema, switch to Payment Discount Field
- PaymentTerm, will remain in BPartner Master Data
- Add PaymentDiscount to Sales Orderline, Shipment Schedule?, Invoice candidates, Invoice, Invoiceline ...
- Adjust Open Items
- Adjust Dunning
- Adjust Margin Calculation in Sales Orderline
- more?

# Documentation

what we did:
* added a new column `PaymentDiscount` to both `C_OrderLine` and `M_DiscountSchemaBreak`
* changed the validationrule for `M_DiscountSchemaBreak.C_PaymentTerm_ID` such that it only shows payment terms that have no discount, like "10 Tage netto".
* with the two together, the system can use the respective payment term as base and derive a new payment term (ofc only if it doesn't yet exist) and set that payment term in `C_OrderLine.C_PaymentTerm_Override_ID`
* also added a Y/N column `C_OrderLine.IsManualPaymentTerm` to protect payment-term-IDs that are not configured in the pricing master data from being overwritten
*

Also see https://github.com/metasfresh/metasfresh/issues/4303

**Comment by metas-dh** [comment]
IT: needs #4303

**Comment by metas-ts** [comment]
hi @metas-dh FYI i just integrated #4303 into `master`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* `PaymentDiscount` in `C_OrderLine` and `M_DiscountSchemaBreak`: **OK**
* selectable payment terms in `M_DiscountSchemaBreak` only those **without** discount: **OK**
* `C_OrderLine.C_PaymentTerm_Override_ID` in orderline is created from payment term in `M_DiscountSchemaBreak` plus `PaymentDiscount`:
e.g. payment term in Discount Schema Break: 30 Tage netto, payment discount in Discount Schema Break: 10%,
=> `C_OrderLine.C_PaymentTerm_Override_ID` in orderline: 30 Tage netto (=>10%): **OK**
* Y/N column `C_OrderLine.IsManualPaymentTerm` (in advanced edit): **OK** (see IT for #4303)
* `PaymentDiscount` from `M_DiscountSchemaBreak` can be selected in pricing conditions (modal overlay in sales order actions), for bpartner where it is not set in bpartner data, and it's correctly applied to the resp. orderline: **OK**
* manually created `C_OrderLine.C_PaymentTerm_Override_ID` can be selected again in future sales orders / sales orderlines: 
    * `C_OrderLine.C_PaymentTerm_Override_ID` manually created in pricing conditions overlay: **OK**
    * `C_OrderLine.C_PaymentTerm_Override_ID` manually created in orderline: **OK**


problems (to check with @metas-mk ):
* names / trls not consistent: "Term of payment" in Discount Schema Break, "Zahlungsbedingung" in orderline (en_US) menu) / "Zahlungsziel" in Discount Schema Break,  "Zahlungsbedingung abw." in orderline (de_DE menu): pls make it consistent
* Jasper for order confirmation: payment term from header is displayed, not the one(s) from orderline(s): NOK i think

**Comment by metas-dh** [comment]
checked with metas-mk:
#4488 & #4489
