### ISSUE TITLE
Pharma: Additional Document/ Certificate Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4224]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently. there are missing Fields in Businesspartner Pharma Window.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the following Y/N Fields to Businesspartner Customer/ Vendor. Create different Columns for Vendor/ Customer.
-GDP-Zertifikat
-QMS-Zertifikat
-F05 Kontakt- und Statusbogen
-Handelsregisterauszug
-Selbstauskunftsbogen

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Business Partner Pharma window:
=> following Y/N Fields to Businesspartner Customer/ Vendor:
-GDP-Zertifikat: OK
-QMS-Zertifikat: OK
-F05 Kontakt- und Statusbogen: OK
-Handelsregisterauszug: OK
-Selbstauskunftsbogen: OK
=> both de_DE and en_US, with correct translation: OK

* Create different Columns for Vendor/ Customer: same columns in both Vendor/ Customer?
* only in Advanced Edit, not grid view: OK?

**Comment by metas-dh** [comment]
checked with metas-mk: all OK
