### ISSUE TITLE
Pharma: Move Businesspartner Fields to Customer/ Vendor Tab

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4225]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there are a few Fields in Business Partner Window that belong to Vendor or Customer Tab.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Move the following Fields to Customer/ Vendor Tab:
- "Bezugsnachweis" shall be called ""Direktbezugsnachweis erforderlich" and moved to customer tab
- "Sepa-Mandat" into customer tab
- Kundenkategorie in customer tab
- Lieferantenkategorie in vendor tab

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* Kundenkategorie in customer tab: Kundengruppe / Customer group: OK
* Lieferanten Kategorie:
    * correct trl in en_US: OK
    * layout: text field? no dropdown (like customer group?)
