### ISSUE TITLE
Attributeset as Sysadmin cannot be created

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4233]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Attributeset as Sysadmin cannot be created. The Client does not have any entries.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall be able to be recorded.

**Comment by metas-dh** [comment]
Results of IT1
tested in releasetest

new M_AttributeSet can be created as SysAdmin:
* in WebUI: OK
* in Swing: OK
