### ISSUE TITLE
Initial Setup Wizard window's layout is distorted

### ISSUE THREAD

**Issue by metas-Kay** [metasfresh/metasfresh#4236]
### Is this a bug or feature request?
FR

### What is the current behavior?
![initial setup wizard window](https://user-images.githubusercontent.com/29163573/41507959-fcab45ec-723c-11e8-94a8-301f86cd6770.png)

#### Which are the steps to reproduce?
Open Initial Setup Wizard from the menu.
(http://docs.metasfresh.org/webui_collection/EN/InitialSetupWizard.html)

### What is the expected or desired behavior?
Should look tidy like this:

![initialsetupwizard](https://user-images.githubusercontent.com/29163573/41507971-3bc0e5b6-723d-11e8-80b2-4801a5da50ec.png)

**Comment by metas-dh** [comment]
frontend issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1850
