### ISSUE TITLE
Implement full text search for BPartners

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4238]

**Comment by metas-lc** [comment]
Created follow-up for when you cannot find a certain bpartner in order https://github.com/metasfresh/metasfresh/issues/4275

**Comment by metas-dh** [comment]
Results of IT1
tested in m15

seach for bpartner: 
1. when FTS is running (FTS index set active):
* enter name of bpartner (3 letters): all matching bpartner names are displayed for selection: OK
* enter value of bpartner (3 digits): all matching bpartner values are displayed for selection: OK
* enter city (3 letters): bpartners with that city set in location are displayed for selection: OK
* enter user name (3 letters): bpartners with that user set in contact are displayed for selection: OK
* enter some letters like "tra": all bpartners that have e.g. location set with "Straße" or a contact set with a name like that (tralala) are displayed for selection: OK i think
* enter postcode (3 numbers): bpartners with that postcode set in location are displayed for selection: OK

2. when FTS is running (FTS index set inactive):
* enter name of bpartner (3 letters): all matching bpartner names are displayed for selection: OK
* enter value of bpartner (3 digits): all matching bpartner values are displayed for selection: OK
* enter city (3 letters): no bpartners displayed for selection: OK
* enter user name (3 letters): no bpartners displayed for selection: OK
* enter some letters like "tra": no bpartners displayed for selection: OK
* enter postcode (3 numbers): no bpartners displayed for selection: OK
