### ISSUE TITLE
Be robust wrt priceentered with too many digits

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4239]
### Is this a bug or feature request?
FR
### What is the current behavior?

you can aparently enter a price such as 0.5021 for some product, even if the respective currency has a precision of 2.
this shall not lead to ArithmeticExceptions

**Comment by metas-lc** [comment]
IT
1. currency precision 2, pricelist precision 2
2. create a sales order and add a product. Change price to 2.8756 
=> changed to 2.88 OK
3. go to product prices and add this price to a product: 6.7281 and one with 2.3746
4. add these 2 products in orderline
=> prices changed into 6.73 and 2.37 OK
5. in product price, make one product: handling unit price and use uom conversion
=> line net amt was calculated fine, no errors OK
6. add some discount to each line
=> no errors OK
.
1. currency precision 2, pricelist precision 3
2. repeat the testcase above using this config
=> prices have 3 digits after the comma like: 6.728, 2.375 OK
.
1. currency precision 3, pricelist precision 2
2. repeat the testcase above using this config
=> prices have 2 digits after the comma like: 6.73, 2.37 OK
.
repeat the testcases for both sales and purchase order
=> works the same OK
