### ISSUE TITLE
Migrate spring-boot from 1.3.3 to 1.4.x

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#424]
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes

**Comment by teosarca** [comment]
Reason: we need a modern elasticsearch version (preferably 2.4.0) the be integrated with spring data.
See https://github.com/metasfresh/metasfresh/issues/425

**Comment by metas-dh** [comment]
Results of IT 2

* App.Server: sp80adrt
* Buildno: #3
* DB: deddb905 : 5432 / sp80_ad_3t

regression e2e (SPV version) worked fine,  procurement webui part included: OK
