### ISSUE TITLE
Translate new Repack Attributes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4240]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the new Repack Attributes are not translated to de_DE.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Check and adjust the Translations for Repack Attributes (for de_DE, en_US)

**Comment by metas-lc** [comment]
IT
1. go to attribute window, see: Repack Nr., Repack Nr. erforderlich, Einkaufspreis, Eingangsdatum OK
