### ISSUE TITLE
WebUI: Window Event Log

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4242]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window Event Log is not available in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the Window Event Log to WebUI.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window Event Log (Ereignis Log) in WebUI: OK
* all fields translated: OK
* "Repost logged event" action: OK
