### ISSUE TITLE
Purchase Candidates adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4244]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
There are new columns that are not added to Purchase Candidates window in WebUI yet.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the following fields to Purchase Candidate:
- IsPrepared (disponiert)
- Processed (bestellt, evtl auch "geschlossen")

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

new columns in purchase candidate window:
* Prepared / Disponiert: OK
* Purchased / Bestellt: OK

* Prepared set correctly after preparing the purchase candidate from sales order: purchase order is already created directly and candidate is set to purchased=Y, see #4172
* Purchased set correctly after purchase order creation: OK
