### ISSUE TITLE
Show c_bpartner memo field of Org BP in document footer

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4252]
### Is this a bug or feature request?
FR

### What is the current behavior?
today we only have one line of text (c_bpartner.description) that we show in jasper document footer.
In case of companies that have more details to put there (e.g. several CEOs etc.) then we are forced to fork the jasper documents.

### What is the expected or desired behavior?
under the line that uses c_bpartner.description we show c_bpartner.memo as well and make it auto adjustable.
From then you can add more text into the memo field of the Org BP.

**Comment by metas-lc** [comment]
instead of showing memo field, i made bpartner description larger. It has 255 characters and it will fit on 2 lines

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* tested with the data that's needed to be displayed in footer by customer:
=> looks fine in order, shipment/receipt & invoice (sales & purchase side): OK

* will test more with more data to check if there are problems / errors coming up with a lot of data in description field

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

tested with a long text in description field:
* text is shown in the whole space of the description field, as long as possible: OK
* no overlays, rest of description text is just cut off, footer looks fine overall: OK
