### ISSUE TITLE
Contract Person in Charge not filtered by Systemuser

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4255]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Field "Person in charge" in Contract Window does show all User/ Contacts.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Only show Systemuser.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Person in charge, contract window, shows only SystemUser:
* changed existing user: only SystemUser displayed and selectable: OK
* added new user: only SystemUser displayed and selectable: OK
