### ISSUE TITLE
Appserver needs to tell SwingUI where to find RabbitMQ

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4260]
### Is this a bug or feature request?
FR follow-up to https://github.com/metasfresh/metasfresh/issues/3772
### What is the current behavior?

RabbitMQ host and port need to be set via `application.properties`, otherwise, the SwingUI can't receive events.

### What is the expected or desired behavior?

The app server needs to tell the SwingUI where to find RAbbitMQ

### Properties

See how to configure which rabbitmq host and port the apps server shall communicate tot he swing clients

```
# rabbitmq host and port to communicate to the swing client when asked.
# If omitted then the app server will return <USE-APPSERVER-HOSTNAME> as host and 5672 as port.
# Background: apps server and rabbitmq are often behind the same "gateway" (e.g. docker-host) when seen from the swing-client
spring.swingui.rabbitmq.host=192.168.99.100
spring.swingui.rabbitmq.port=30050
```

**Comment by metas-rc** [comment]
Talked with metas-ts and he said he doesn't think there is something to IT on this task. Closing it.
