### ISSUE TITLE
Ingredients Data for Consumer Product Label

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4264]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no possibility to record data needed for a consumer product label.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
- Create new Fields in BOM Lines
  - Consumer Label Quantity (Text Field)
  - Flag showSubBOM ingredients

- Create the same Fields in PP_Order_BOMLine

**Comment by metas-lc** [comment]
IT
1. go to Bill of Material, see lines:
=> Consumer Label Quantity (Text Field): CU Label Qty
=> showSubBOM ingredients (Flag): Show Sub BOM Ingredients
=> de and en trl - done
OK
2. go to Manufacturing order window, components tab
=> CU Label Qty, Show Sub BOM Ingredients
=> de and en trl - done
OK
