### ISSUE TITLE
Automatically index data on FTS index creation

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4275]
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh/issues/4238
### What is the current behavior?
Sometimes you cannot find a certain bpartner when you search in order
#### Which are the steps to reproduce?
1. create a new sales order, add kunde bpartner
=> not found NOK
### What is the expected or desired behavior?
should find it

**Comment by metas-dh** [comment]
from e2e:
* bpartner already existing in new db not found, workaround: change their name, e.g. add "1"
* works fine with newly created bpartners

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

bpartner found in order window (sales & purchase):
* new and old bpartners found when searching for name (first 3 letters): OK
* new and old bpartners found when searching for value (first 3 letters / digits): OK
* business partner & invoice partner field: OK

**Comment by metas-ts** [comment]
:cherries: picked to `release` branch
