### ISSUE TITLE
Order line is flagged as Temporary Pricing Conditions when the conditions are actually missing

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4282]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* create a new order
* create a new order line using a product which has no pricing conditions
* the line is created but the pricing conditions indicator is yellow (temporary) instead of "red".

### What is the expected or desired behavior?
see above.

**Comment by metas-lc** [comment]
IT (see 5, 7 and 8)

1. sales order with a bpartner without discount schema
=> line is red (no pricing conditions) OK

2. orderline for a bpartner with discount schema, but not for your product
=> line is red (no pricing conditions) OK

3. bpartner with discount schema for your product
=> no colors, discount schema found OK

4. bpartner with discount schema for your product, but discount break > your qty
=> line is red (no pricing conditions) OK

5. bpartner with discount schema for your product, but flat (shall not be considered)
=> it's yellow (temporary pricing conditions) NOK

6. bpartner with discount schema, but not for your product
=> line is red (no pricing conditions) OK

7. take a bpartner with discount schema, add a product without discount schema - for no pricing conditions. Go to pricing conditions, copy one, press done
=> still red (no pricing conditions) NOK
(if you save it then no color ok)

8. bpartner with discount schema for your product, but discount break > your qty. Color red (no pricing conditions). Update the qty > discount break
=> color turned yellow (temporary pricing conditions) NOK

**Comment by metas-ts** [comment]
> 7. take a bpartner with discount schema, add a product without discount schema - for no pricing conditions. Go to pricing conditions, copy one, press done
=> still red (no pricing conditions) NOK

works now

> 8. bpartner with discount schema for your product, but discount break > your qty. Color red (no pricing conditions). Update the qty > discount break
=> color turned yellow (temporary pricing conditions) NOK
(also the other way around. Have line with pricing conditions, update qty to not fit anymore -> the line still looks like having pricing conditions)

just pushed a fix for this

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

7. take a bpartner with discount schema, add a product without discount schema - for no pricing conditions. Go to pricing conditions, copy one, press done
=> no  colour, pricing condition exists: OK


8. bpartner with discount schema for your product, but discount break > your qty. Color red (no pricing conditions). 
* Update the qty > discount break: no  colour, pricing condition exists: OK
* set qty back < discount break: colour red: OK

=> problem: payment term eff. and price from pricing conditions are set when qty for discount break is reached: OK, but it's not set back when the qty is changed again to < qty discount break, so the price and the payment term are not correct : NOK

**Comment by metas-ts** [comment]
fied the NOK of https://github.com/metasfresh/metasfresh/issues/4282#issuecomment-452738593

**Comment by teosarca** [comment]
Cannot define a schema break which:
* is using a pricing system with multiple price list in different currencies / countries
* it defines a surcharge amount 

Because i get an error about surcharge currency which is not matching the price list currency.
That's happening because each price list is validated so, no matter what currency i will use for surcharge, there will be at least on price list which would not match.

**Comment by metas-dh** [comment]
Results of IT3
tested in release

1. problem from https://github.com/metasfresh/metasfresh/issues/4282: payment term eff. and price from pricing conditions are set when qty for discount break is reached: OK, but it's not set back when the qty is changed again to < qty discount break, so the price and the payment term are not correct: 

=> this was still happening for my testcase (pricing conditions are set for bpartner, not temporary ones): NOK

2. Cannot define a schema break which:
* is using a pricing system with multiple price list in different currencies / countries
* it defines a surcharge amount

=> this worked fine for me while testing

**Comment by metas-dh** [comment]
checked the NOK from last IT again in release:
=> worked fine this time, payment term and Skoknto were updated correctly as well: OK
