### ISSUE TITLE
Document Outbound eMail action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4284]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it is possible to start the action "Send eMails to Business partner" via Doc Outbound window, without selecting lines. In this case, the action is triggered for all Doc Outbound entries.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Doc Outbound:
- [x] only show the action if at least 1 line is selected.
- [x] only trigger the action for the selected lines

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* only show the action if at least 1 line is selected: OK
* only trigger the action for the selected lines: OK

**Comment by metas-dh** [comment]
problem from testing:

=> entry in doc outbound, for sales invoice, had "eMail counter" (header): 0, but sev. entries for mails being sent in the log; was sent once more everytime when it was selected, although the checkbox for sending only data that was not sent already:Y : NOK i think
