### ISSUE TITLE
Allow repost eventlog with forcing handler to be processed again

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4286]
### Is this a bug or feature request?
FR

![image](https://user-images.githubusercontent.com/1264789/41976176-b28c6580-7a1c-11e8-949a-a846f8a2b30f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Event Log with processed entries:
* run new action "Repost logged event for entry" for an already processed entry: entry is reposted, additional entries in the same Event Log: OK
