### ISSUE TITLE
Make a Webui-Window for HU Reservation

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4292]
### Is this a bug or feature request?
FR follow-up to #4248 
#
AD_Window_ID=540453

**Comment by metas-lc** [comment]
IT
0. to have data in HU Reservation window: 
go to purchase order and create one with product A. Receive some qtys. Go to sales order and create a new one with the same product. Complete. Select the product line, go to actions - Reserve. Select your HU, add qty. HUs are now in Reservation window

1. design 
TL: mandatory, important OK
TR: active flag OK
BR: org, client OK
