### ISSUE TITLE
WebUI: New Window for MSV3 Customer Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4293]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no MSV3 Customer Window in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create the Window for MSV3 Customer Maintenance and add to WebUI menu.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for MSV3 customers: OK
* de_DE: "MSV3 Kunden Konfiguration": OK
* en_US:  "MSV3 Customers", but "MSV3 Vendor Configuration": OK?
