### ISSUE TITLE
Jasper: Translations missing in en_US version

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4299]
### Is this a bug or feature request?
FR
### What is the current behavior?
There are some translations missing in Jaspers, for en_US:
* VAT ID: in en_US jasper, it's USt. ID (in header)
* Company registered in: in en_US jasper, it's Sitz der Gesellschaft
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Pls add the missing translations.

**Comment by metas-lc** [comment]
added missing trl: 
USt. ID -> VAT ID
Sitz der Gesellschaft: -> Company registered in:

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


 *For testing, I chose the report for purchase orders

1) German partner: 
* USt. ID 
* Sitz der Gesellschaf


2) English partner:
* VAT ID
* Company registered in
