### ISSUE TITLE
Extend webui for PaymentDiscount

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4303]
### Is this a bug or feature request?
FR belongs to https://github.com/metasfresh/metasfresh/issues/4221

### What is the expected or desired behavior?

AFAIU the TODOs are:
* show `C_OrderLine.PaymentDiscount`
* maybe show `C_OrderLine.IsManualPaymentTerm` after all? 
  Maybe under advanced edit? 
  Why: the flag is set if a user touches `PaymentDiscount` or `C_PaymentTerm_Override_ID` to prevent the system from overriding whatever the user set.
  Now, if the field is not shown, the user can't change her mind and go back to "take what's configured in the system", without having access to this flag.
  * note, thant's not 100% true; she can open the pricing conditions overlay and select a non-temporary pricing condition. that also unsets the flag
* Show `M_DiscountSchemaBreak.PaymentDiscount`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* show `C_OrderLine.PaymentDiscount`: **OK**
* Y/N column `C_OrderLine.IsManualPaymentTerm` in orderline (in advanced edit): **OK**
* column is set to 'Y' when the `C_PaymentTerm_Override_ID` is changed by the user: **OK**
* column is set to 'Y' when the `PaymentDiscount` is changed by the user: **OK**
(in case the `PaymentDiscount` is changed by the use, both the original `PaymentDiscount`  and the changed one are displayed in `C_PaymentTerm_Override_ID` are displayed: checked with metas-ts: OK for now)
* when column is set back to 'N', then the original payment term is set again: **OK**
* Show `M_DiscountSchemaBreak.PaymentDiscount`: **OK**
