### ISSUE TITLE
Zoom from sales order to material dispo should open all referencing records

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4308]
### Is this a bug or feature request?
FR

### What is the current behavior?

currently only MD_Candidates with type = PRODUCTION are opened

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Zoom from sales order to material dispo should open all referencing records:
* referencing records also include type demand & supply

**Comment by metas-dh** [comment]
will check the other types on entries when rolled out in customer db with distribution network, production planning data etc.

**Comment by metas-dh** [comment]
=> checked in latest customer e2e:
* referencing records also include type demand & supply (in picking warehouse, production warehouse, and nec. records for distribution acc. to distribution network): OK
* referencing records also include related production records (BOM within BOM): OK
