### ISSUE TITLE
WebUI: add Manufacturer field in Pricing Conditions

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4310]
### Is this a bug or feature request?
fr
### What is the current behavior?
Manufacturer is not added yet in Pricing Conditions
#### Which are the steps to reproduce?
go to sales order, add a line, select it, go to actions, open Pricing Conditions
### What is the expected or desired behavior?
add Manufacturer field in Pricing Conditions

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* manufacturer field in discount schema: OK
* manufacturer field in pricing conditions: missing in the pricing conditions overlay called from actions in sales order: NOK afaiu?
