### ISSUE TITLE
Purchase schedules date: consider vendor lead time and non business days

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4311]

**Comment by teosarca** [comment]
note to IT:
* lead time and the non business days calendar are defined in BPartner (pharma) -> Purchase schedule tab
* define a calendar with some non business days
* create some purchase candidates, make sure C_PurchaseCandidate's PurchaseDatePromised, PurchaseDateOrdered and ReminderDate are correctly calculated, i.e.

PurchaseDatePromised = sales order's preparation date  (shifted backwards in case that preparation date is not a deliverable date for that vendor)
PurchaseDateOrdered = PurchaseDatePromised minus lead time offset. The leadtime is in days and only the business days are considered. So basically, when the PurchaseDateOrdered is calculated, the non business days calendar is used
ReminderDate = PurchaseDateOrdered minus reminder time (defined in Purchase schedule tab)

**Comment by metas-lc** [comment]
IT
1. without Purchase Schedule
SO:"2018-07-10 23:59:59+02"
Purchase Date Promised: "2018-07-10 23:59:59+02" (same as in sales order) OK
Purchase Date Ordered: "2018-07-10 00:00:00" - shouldn't be h 23:59:59?
Reminder Date: empty OK?

2. with Purchase Schedule (existing deliverable date on 3PM) 
SO:"2018-07-10 23:59:59+02"
Purchase Date Promised: "2018-07-10 15:00:00+02" (same as in sales order, but the hour shifted back to the one in the schedule) OK
Purchase Date Ordered: "2018-07-07 00:00:00" - my offset time was 3 (i suppose days) - exists purchase schedule OK
Reminder Date: empty OK? (my reminder time was 30)

3. with Purchase Schedule (not existing deliverable date)
first purchase schedule back: Saturday 8AM 
SO:"2018-07-15 22:59:59+02"
Purchase Date Promised: "2018-07-14 08:00:00+02" (Saturday at 8 AM) OK
Purchase Date Ordered: "2018-07-11 00:00:00" - my offset time was 3 (i suppose days) - exists purchase schedule OK
Reminder Date: empty OK? (my reminder time was 30)

4. changed reminder time to 10. Select a date promised, without deliverable date. Also changed offset time such as it won't exist purchase schedule in that day
first purchase schedule back: Saturday 8AM 
SO:"2018-07-15 22:59:59+02"
Purchase Date Promised: "2018-07-14 08:00:00+02" (Saturday at 8 AM) OK
Purchase Date Ordered: "2018-07-13 00:00:00" (Friday. I don't have purchase schedule on Friday) OK
Reminder Date: empty OK? (my reminder time was 10)

**Comment by metas-lc** [comment]
i think Reminder Date should not be empty.. i'm moving this back. If it's some config issue or smth, please put it back to IT

**Comment by teosarca** [comment]
closing because it's too old
