### ISSUE TITLE
Window Payment Allocations not editable

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4323]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Window "Payment Allocation" cannot be used for manual Allocation creations. The Fields are all readonly.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Make the Window editable `window/205`, so the user can add manual Payment Allocations.

**Comment by metas-lc** [comment]
IT
1. Go to payment allocations window (205) and create a new one
=> fields are editable OK
2. add all mandatory fields, add a line
=> fields are editable OK
