### ISSUE TITLE
REST API for creating sales orders and attaching files to them

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4340]

**Comment by teosarca** [comment]
### Create & complete a new sales order
![image](https://user-images.githubusercontent.com/1244701/42380025-32ae4ed0-8135-11e8-8f07-453a043cc975.png)

### Attach a file to an existing order
![image](https://user-images.githubusercontent.com/1244701/42380061-52e98160-8135-11e8-9f28-a4ed51f322ce.png)

**Comment by teosarca** [comment]
update: added `docTypeName` property (optional).

**Comment by metasnw** [comment]
@teosarca what matches  `docTypeName` in metasfresh UI ?

**Comment by teosarca** [comment]
@metasnw  `C_DocType.Name`. But DocBaseType=SOO is also enforced.

**Comment by metas-ts** [comment]
:cherries: to `release`
