### ISSUE TITLE
Individual sequences for products and projects

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4346]
### Is this a bug or feature request?
FR
### What is the current behavior?

every `M_Product.Value`and `M_Project.Value` is set from one sequence each.

### What is the expected or desired behavior?

* projects: we want to set the sequence per project type
* products: we want to set the sequence per product category
* both shall be optional

### Results

* webui stuff to be done here:
* there is a sequence-field now on both Porject Type and Product Category
* note that only sequences with AD_Client_ID > 0 can be selected
* the idea is not to reuse an existing sequence (but it can be done), but create one, such as "Software-Project Sequence" and assign it to the respective project type or product category

**Comment by metas-rc** [comment]
Results of IT

Tested on swing

1) Product

* Created a sequence for the product
![image](https://user-images.githubusercontent.com/16001442/42511795-894503d2-845b-11e8-81df-cd50c1a95f32.png)

* Assigned the sequence to a product category
![image](https://user-images.githubusercontent.com/16001442/42511819-96ae5f0a-845b-11e8-90e9-2096dcfac283.png)


* Created a product for that category
![image](https://user-images.githubusercontent.com/16001442/42511839-a788fc5e-845b-11e8-9a72-8ba6ef5fffb8.png)


* => NOK: The product didn't get a value according to the sequence from the category

2) Project

* Created a sequence for projects: 
![image](https://user-images.githubusercontent.com/16001442/42511899-cd290968-845b-11e8-9aee-f8e3841d7371.png)


 * Assigned the sequence to a project type: 

![image](https://user-images.githubusercontent.com/16001442/42511913-d9a32070-845b-11e8-9e1b-72cbc065c8f9.png)


* Created a new project for that type: 

![image](https://user-images.githubusercontent.com/16001442/42511932-e4ac0b12-845b-11e8-8417-e1f9938e2d5d.png)

* => NOK: The project didn't get a value according with the sequence

**Comment by metas-lc** [comment]
IT
1. product category A - set sequence (used the one already existed from IT1. See pics)
=> only those form your client were selectable OK
=> field not mandatory OK
2. created a new product, used product category A
=> the sequence was applied correctly OK
3. created a new product again, same category
=> the sequence was applied/ incremented correctly OK
4. created a new product, product category B (without any sequence set)
=> the default sequence was applied OK
.
5. created a new project type
6. set the sequence (used the one already existed from IT1. See pics)
=> only those form your client were selectable OK
=> field not mandatory OK
7. create a new project, set the type above
=> got a value according with the sequence OK
8. created another one, same way
=> got a value according with the (next) sequence OK
9. created another one, didn't set sequence
=> got a default value OK
.
repeated same testcase on webui:
=> on webui we don't have the fields/project yet and we have a task: https://github.com/metasfresh/metasfresh/issues/4350
=> creating product on webui went fine OK
