### ISSUE TITLE
Sales Orderline:ERROR: duplicate key value violates unique constraint "c_paymentterm_name"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4356]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, a Bug appears when creating a Sales Orderline.
ERROR: duplicate key value violates unique constraint "c_paymentterm_name"
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please fix the Bug.

<details>

trace
:
[,…]
[0 … 99]
0
:
"org.adempiere.exceptions.DBUniqueConstraintException: ERROR: duplicate key value violates unique constraint "c_paymentterm_name""
1
:
"  Detail: Key (ad_client_id, name)=(1000000, 30 Tage 2% (=>0 %)) already exists."
2
:
"	SQL: INSERT INTO C_PaymentTerm (AD_Client_ID,AD_Org_ID,AfterDelivery,C_PaymentTerm_ID,Created,CreatedBy,Discount,Discount2,DiscountDays,DiscountDays2,GraceDays,IsActive,IsDefault,IsDueFixed,IsNextBusinessDay,IsValid,Name,NetDays,Processing,Updated,UpdatedBy,Value) VALUES (1000000,0,'N',nextval('c_paymentterm_seq'),TO_TIMESTAMP('2018-07-10 14:46:07','YYYY-MM-DD HH24:MI:SS'),100,0,0,30,0,25,'Y','N','N','Y','Y','30 Tage 2% (=>0 %)',30,'N',TO_TIMESTAMP('2018-07-10 14:46:07','YYYY-MM-DD HH24:MI:SS'),100,'1000016') RETURNING C_PaymentTerm_ID"
3
:
"	at org.compiere.util.DB.executeUpdate(DB.java:961)"
4
:
"	at org.compiere.model.PO.saveNew(PO.java:3649)"
5
:
"	at org.compiere.model.PO.save0(PO.java:2828)"
6
:
"	at org.compiere.model.PO.access$100(PO.java:139)"
7
:
"	at org.compiere.model.PO$1.run(PO.java:2731)"
8
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
9
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
10
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
11
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
12
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
13
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
14
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
15
:
"	at org.compiere.model.PO.saveEx(PO.java:2725)"
16
:
"	at org.adempiere.model.POWrapper.save(POWrapper.java:799)"
17
:
"	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:595)"
18
:
"	at org.adempiere.model.InterfaceWrapperHelper.saveRecord(InterfaceWrapperHelper.java:577)"
19
:
"	at de.metas.payment.paymentterm.PaymentTermService.getOrCreateDerivedPaymentTerm(PaymentTermService.java:95)"
20
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.toPricingConditionsBreak(PricingConditionsRepository.java:166)"
21
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.lambda$toPricingConditions$1(PricingConditionsRepository.java:138)"
22
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
23
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
24
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
25
:
"	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)"
26
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
27
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
28
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
29
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
30
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
31
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.toPricingConditions(PricingConditionsRepository.java:139)"
32
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.retrievePricingConditionsById(PricingConditionsRepository.java:106)"
33
:
"	at org.compiere.util.CCache.lambda$getOrLoad$0(CCache.java:521)"
34
:
"	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
35
:
"	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
36
:
"	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
37
:
"	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
38
:
"	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
39
:
"	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
40
:
"	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
41
:
"	at org.compiere.util.CCache.get(CCache.java:482)"
42
:
"	at org.compiere.util.CCache.getOrLoad(CCache.java:522)"
43
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsRepository.getPricingConditionsById(PricingConditionsRepository.java:90)"
44
:
"	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.getPricingConditions(CalculatePricingConditionsCommand.java:116)"
45
:
"	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.getDiscountType(CalculatePricingConditionsCommand.java:102)"
46
:
"	at de.metas.pricing.conditions.service.impl.CalculatePricingConditionsCommand.calculate(CalculatePricingConditionsCommand.java:74)"
47
:
"	at de.metas.pricing.conditions.service.impl.PricingConditionsService.calculatePricingConditions(PricingConditionsService.java:17)"
48
:
"	at de.metas.pricing.rules.Discount.calculate(Discount.java:119)"
49
:
"	at de.metas.pricing.rules.AggregatedPricingRule.calculate(AggregatedPricingRule.java:129)"
50
:
"	at de.metas.pricing.service.impl.PricingBL.calculatePrice(PricingBL.java:136)"
51
:
"	at de.metas.order.impl.OrderLinePriceCalculator.updateOrderLine(OrderLinePriceCalculator.java:95)"
52
:
"	at de.metas.order.impl.OrderLineBL.updatePrices(OrderLineBL.java:339)"
53
:
"	at de.metas.adempiere.callout.OrderFastInput.addOrderLine(OrderFastInput.java:297)"
54
:
"	at de.metas.ui.web.quickinput.orderline.OrderLineQuickInputProcessor.process(OrderLineQuickInputProcessor.java:87)"
55
:
"	at de.metas.ui.web.quickinput.QuickInput.complete(QuickInput.java:250)"
56
:
"	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$null$9(WindowQuickInputRestController.java:309)"
57
:
"	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$forQuickInputWritable$3(WindowQuickInputRestController.java:212)"
58
:
"	at de.metas.ui.web.window.model.DocumentCollection.forRootDocumentWritable(DocumentCollection.java:288)"
59
:
"	at de.metas.ui.web.quickinput.WindowQuickInputRestController.forQuickInputWritable(WindowQuickInputRestController.java:205)"
60
:
"	at de.metas.ui.web.quickinput.WindowQuickInputRestController.lambda$complete$10(WindowQuickInputRestController.java:308)"
61
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$4.call(TrxCallableWrappers.java:193)"
62
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
63
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
64
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
65
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
66
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
67
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)"
68
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:475)"
69
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$0(Execution.java:194)"
70
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
71
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
72
:
"	at de.metas.ui.web.window.controller.Execution.callInNewExecution(Execution.java:88)"
73
:
"	at de.metas.ui.web.quickinput.WindowQuickInputRestController.complete(WindowQuickInputRestController.java:307)"
74
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
75
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
76
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
77
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
78
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
79
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
80
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
81
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
82
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
83
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
84
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
85
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
86
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
87
:
"	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)"
88
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)"
89
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
90
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
94
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
96
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
97
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
98
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
99
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
[100 … 167]
100
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
101
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
102
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
103
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
104
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
105
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
106
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
107
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
108
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
109
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
110
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
111
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
112
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
113
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
114
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
115
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
116
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
117
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
118
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
119
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
120
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
121
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
122
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
123
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
124
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
125
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
126
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
127
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
128
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
129
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
130
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
131
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
132
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
133
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
134
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
135
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
136
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
137
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
138
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
139
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
140
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
141
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
142
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
143
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
144
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
145
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
146
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
147
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
148
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
149
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
150
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
151
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
152
:
"	at java.lang.Thread.run(Thread.java:748)"
153
:
"Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "c_paymentterm_name""
154
:
"  Detail: Key (ad_client_id, name)=(1000000, 30 Tage 2% (=>0 %)) already exists."
155
:
"	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2455)"
156
:
"	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2155)"
157
:
"	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)"
158
:
"	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)"
159
:
"	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)"
160
:
"	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)"
161
:
"	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)"
162
:
"	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1418)"
163
:
"	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQuery(CPreparedStatementProxy.java:123)"
164
:
"	at org.adempiere.sql.impl.CPreparedStatementProxy.executeQueryAndLogMigationScripts(CPreparedStatementProxy.java:130)"
165
:
"	at org.compiere.util.DB.executeUpdate(DB.java:920)"
166
:
"	... 149 more"
167
:
""
</details>

**Comment by metas-lc** [comment]
IT
1. create an order, add orderline
=> no errors OK
2. create another order with a bpartner that has dicount schema with payment term, add a line
=> no errors OK
3. create an order with a bpartner without discount schema, add a line
4. select the line, go to Pricing Conditions action and make a temporary condition, containing a payment term, some discount
=> new payment term was created, no errors OK
5. open Pricing Conditions action again and change the payment term
=> payment term in orderline was not updated and if you select the line with right click, you get an error: Error: String document IDs cannot...
Server error
String document IDs cannot be converted to int: 2156425-C-editable
