### ISSUE TITLE
Set default values for new Integer and YesNo AD_Columns

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4359]
### Is this a bug or feature request?
FR follow-up of https://github.com/metasfresh/metasfresh/issues/4356
### What is the current behavior?

* Currently, when creating new Yes/No or Integer columns, the dev needs to remember to make them mandatory and set a default.
* Yes/No or Integer columns with `null` are problematic.

Example:
> i stumbled over a problem with PO and the query builder:
in PaymentTermService, there is a line that sais:
.addEqualsFilter(I_C_PaymentTerm.COLUMNNAME_FixMonthCutoff, basePaymentTermRecord.getFixMonthCutoff())
and fixMonthCutOff has this DDL:
ALTER TABLE public.c_paymentterm ADD COLUMN fixmonthcutoff numeric(10,0);
(i.e. no default).
the problem is that we have a record
so if you have 
final I_C_PaymentTerm newPaymentTerm = newInstance(I_C_PaymentTerm.class);
then newPaymentTerm.getFixMonthCutoff() returns 0. but in the DB we have null.
and if we save that newPaymentTerm and then use that .addEquals(...) from above, nothing is selected

### What is the expected or desired behavior?

change `Callout_AD_Column` and add the requested behavior.
users may still change the value to not-mandatory and no-default, but they shall do it as a conscious step.

**Comment by metas-lc** [comment]
IT
1. login as sysadmin, go to tables, select one and add new column
2. add a yes-no column
=> column is mandatory OK
=> there is no default logic if the column has a name starting with "is" NOK
(on webui is ok. Only in swing we have this problem)
3. add an integer column
=> column is mandatory OK
=> default logic is 0 OK
4. add another kind of column.. like string
=> column is not mandatory OK
=> default logic is empty OK

**Comment by metas-lc** [comment]
IT
repeated the testcase above (swing and webui)
=> all works fine: column is mandatory and default logic is N for y/n and 0 for integer OK
