### ISSUE TITLE
HU Transformation for LU, Packing Item and TU Qty default

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4367]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the LU Packing Item and Qty is not preset by default when doing HU Transformation
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Check the behavior in Swing and add this behavior in WebUI too.
- preset the LU Packing Item
- Preset the TU qty

**Comment by teosarca** [comment]
requires: https://github.com/metasfresh/metasfresh-webui-api/issues/1010

**Comment by metas-lc** [comment]
IT
Receipt candidates:
1. open HU Editor with 2 LUs, each with 3 TUs
2. select a TU line, select transform
3. choose TU to new TUs
=> qty TU is 3 OK
4. choose TU to existing LU
=> LU is not preset OK (i think)
=> qty TU is 3 OK
5. choose TU to new LU
=> LU is preset OK
=> qty TU is 72 (shall be 3?) NOK
6. select another LU with different capacity
=> qty TU updated to 76 OK/ NOK ?

**Comment by metas-dh** [comment]
created follow-up: https://github.com/metasfresh/metasfresh/issues/4617
