### ISSUE TITLE
Sales Order VAT vs. Invoice Candidate VAT

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4371]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When creating a Sales Order with Order/ Shipto BPartner_ID and location A in local country and a BilltoLocation B in foreign country, 
- then the Order Tax is calculated based on location A: OK

After Sales Order complete the invoice candidates are created. The Tax there is based on location B. NOK
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The Tax in Invoice candidates shall be based on the Tax in location A (Shipto location). Pls fix.

**Comment by metas-lc** [comment]
IT
0. to be able to make orderlines for a foreign bpartner, i created a new tax and tax category (to not confuse with the existing ones for local country). In tax i set country to DE (org's country). Set the tax category in the CH pricelist for the product and HU i used
.
1.
1.0 Create Sales Order: BP A (de), Bill BP B (ch), DropShip BP C (de)
add a line
=> tax: usual tax for DE bp OK
=> HU: usual tax for DE bp OK
1.1 check IC for product
=> tax: usual tax for DE bp OK
1.2 create inout, check IC for hu
=> tax: usual tax for DE bp OK
1.3 create invoice
=> taxes: usual tax for DE bp OK

2.
2.0 Sales Order: BP B (ch), bill bp same BP B (ch),  no dropship
2.1 add a line
=> tax: tax of BP B OK
2.2 IC for product
=> tax: of BP B OK
2.3 create inout, check IC for hu
=> tax: of BP B OK
2.4 create invoice
=> taxes: of BP B OK

3.
3.0 Create Sales Order: BP A (de), Bill BP B (ch), no dropship
3.1 add a line
=> tax: usual tax for DE bp OK
=> HU: usual tax for DE bp OK
=> IC for product, tax:  usual tax for DE bp OK
3.2 create inout
=> IC for hu, tax:  usual tax for DE bp OK
3.3 create invoice
=> taxes:  usual tax for DE bp OK

4.
4.0 Create Sales Order: BP A (de), Bill BP A (de),  DropShip BP C (ch)
4.1 add a line
=> tax: welt tax of BP A (not usual tax i would get for bp A) ??
=> HU: welt tax of BP A ??
=> IC for product, tax: welt tax of BP A ??
4.2 create inout
=> IC for hu, tax: of BP B, CH ??
4.3 create invoice
=> got 2 invoices, for 2 different taxes
=> HU invoice: of BP B, CH ??, 
=> product invoice: welt tax of BP A ??

**Comment by metas-rc** [comment]
4. Solved: 
Create Sales Order: BP A (de), Bill BP A (de), DropShip BP C (ch)
4.1 add a line
=> tax:  tax: of BP C, CH
=> HU:  tax: of BP C, CH
=> IC for product, tax: of BP C, CH
4.2 create inout
=> IC for hu,  tax: of BP C, CH
4.3 create invoice
=> got 1 invoice,  tax: of BP C, CH

**Comment by metas-rc** [comment]
Regression:
1. OK
2. OK
3. OK
5. OK

**Comment by metas-lc** [comment]
IT2 
0. to be able to make orderlines for a foreign bpartner, i created a new tax and tax category (to not confuse with the existing ones for local country). In tax i set country to DE (org's country). Set the tax category in the CH pricelist for the product and HU i used
.
1.
1.0 Create Sales Order: BP A (de), Bill BP B (ch), DropShip BP C (de)
add a line
=> tax: usual tax for DE bp OK
=> HU: usual tax for DE bp OK
1.1 check IC for product
=> tax: usual tax for DE bp OK
1.2 create inout, check IC for hu
=> tax: usual tax for DE bp OK
1.3 create invoice
=> taxes: usual tax for DE bp OK

2.
2.0 Sales Order: BP B (ch), bill bp same BP B (ch),  no dropship
2.1 add a line
=> tax: tax of BP B OK
2.2 IC for product
=> tax: of BP B OK
2.3 create inout, check IC for hu
=> tax: of BP B OK
2.4 create invoice
=> taxes: of BP B OK

3.
3.0 Create Sales Order: BP A (de), Bill BP B (ch), no dropship
3.1 add a line
=> tax: usual tax for DE bp OK
=> HU: usual tax for DE bp OK
=> IC for product, tax:  usual tax for DE bp OK
3.2 create inout
=> IC for hu, tax:  usual tax for DE bp OK
3.3 create invoice
=> taxes:  usual tax for DE bp OK

4.
4.0 Create Sales Order: BP A (de), Bill BP A (de),  DropShip BP C (ch)
4.1 add a line
=> tax: tax of BP C OK
=> HU: tax of BP C OK
=> IC for product, tax: welt tax of BP C OK
4.2 create inout
=> IC for hu, tax: of BP C, CH OK
4.3 create invoice
=> got 1 invoices
=> HU: of BP C OK
=> product: tax of BP C OK

5. 
5.0 Create Sales Order: BP B (CH), Bill BP A (de), no DropShip
5.1 add a line
=> tax: tax of BP B (CH) OK
=> HU:tax of BP B (CH) OK
=> IC for product: tax of BP B (CH) OK
5.2 create inout
=> IC for hu, tax of BP B (CH) OK
5.3 create invoice
=> got 1 invoice
=> HU line: tax of BP B (CH) OK
=> product line: tax of BP B (CH) OK

6. 
6.0 Create Sales Order: BP B (CH), Bill BP B (CH), DropShip BP A (DE)
=> had to manually add Payment Term ?
6.1 add a line
=> tax: tax of BP A OK
=> HU: tax of BP A OK
=> IC for product: tax of BP A OK
6.2 create inout
=> IC for hu, tax of BP A OK
6.3 create invoice
=> got 1 invoice
=> HU: tax of BPA OK
=> product: tax of BP A OK
