### ISSUE TITLE
Pricing engine sets the scale of price amounts to the respective precision

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4376]
### Is this a bug or feature request?
Feature
### What is the current behavior?

The pricing engine goes with the amounts with the respective pricing rules come up with.

Problem with that: we observe that some pricing rules (i suggest a discount related one) keeps adding meaningless zeroes (after the decimal point) to the price.
Also, when we have a pricing result with a particular precision, why not make sure that the price amount themselves have this precision too.

**Comment by metas-lc** [comment]
IT
0. make sure your pricelist has price precision 2
1. add a simple orderline, check priceactual, priceentered
=> both prices has precision 2 OK
2. set discount like 1,0985. Check price actual
=> it was updated and precision is still 2 OK
3. add a discount bigger than 100% (e.g. 234.2467). Check price actual
=> price is with minus, precision is still 2 OK
4. set price entered to 2.13, discount to 50.  Check price actual
=> 1.07 (precision 2) OK
5. set price entered to 2.13, discount to 4.258.  Check price actual
=> 2.04 (precision 2) OK
.
6. create a new discount schema, set break discount (like 3.8632). Set a payment term
7. set this schema to your bpartner and create a new line
=> discount is set to the one from schema (3.8632)
=> priceactual has precision 2 OK
8. select the line, actions: pricing conditions. Set a PaymentDiscount, save discount schema
=> priceactual has precision 2 (price didn't change) OK
9. complete the order, create inout and invoice
10. check priceactual in invoice
=> the one from HU is 1.000000000000 OK?
.
11. use the discount schema in a purchase bpartner as well (you cannot set a manual discount in po)
12. create a new purchase order, add line, check priceactual
=> priceactual has precision 2 OK
.
13. go to pricelist and change price precision to 4 and to 0, then check price actual again after setting discounts
=> price has the corresponding precision: 4 or 0 OK

**Comment by metas-lc** [comment]
IT
Retested IT above. 
=> 1-12 OK
(works the same, and price of HU has precision 2)
.
13. went to price list and set the price precision to 4.
created a new sales order, added a new line
=> "ArithmeticException: Rounding necessary" NOK
(is related with the discount schema!
have: Break Discount % 3.8632 and Skonto% 5.00)
rest works fine OK

**Comment by metas-lc** [comment]
IT
works now
- prices have the right precisions
- no errors 
OK
