### ISSUE TITLE
ESR RefNo too short after scan in Purchase Invoice action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4392]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Process "Read Payment" (Zahlung einlesen) takes the number sequence as delivered by reader and saves as is.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Sometimes it happens that the ESR Documents have ESR RefeNo that are too short. In such cases we shall fill the RefNo with leading zeroes up to the default length for the RefNo.

**Comment by metas-lc** [comment]
window zahlung-zuordnung, process Zahlung einlesen
config: 
Payment String: 0100X XXXXXX X8>YYYYYYY00100000642001431904+ ZZZZZZZZZ> 
X XXXXXX X is the amount of the invoice you pay: for 11,90 it will be 0 000119 0
YYYYYYY is the account number 
ZZZZZZZZZ is the ESR account
.
in this case we have to test different length for ESR account (ZZZZZZZZZ)
