### ISSUE TITLE
Process to void order and revert flatrate terms, shipment schedule, invoice candidates

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4403]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?

* new action based on sales order and reverses, closes all references
* rename** the sales order documentno to "S-xxx" for Storno
* copy the sales order in draft mode with the old order no
* payments already allocated with created RC invoice shall be de-allocated

**Comment by metas-lc** [comment]
IT
I. simple order -> invoice
1. create/complete a new sales order
2. create inout directly from shipment dispo
3. create invoice from ICs
4. go to your sales order, actions, run: "Void selected order with related documents"
=> order has now value like S-0036
=> ICs are not processed anymore, all qtys 0 OK
=> shipment dispo is still processed
=> inout is reversed (another one created with minus) OK
=> invoice is reversed (another one created with minus) OK
