### ISSUE TITLE
Action Sales Order from Quotation wrong Prices

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4405]
### Is this a bug or feature request?
Bugfix
### What is the current behavior?
Currently, the action Sales Order from Quotation does not copy the prices to Quotation to Sales Order.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Copy the prices from Quotation to Sales Orderlines.

**Comment by metas-lc** [comment]
IT
1. Go to Sales order and create a new Quotation. Add 2 lines, same product
2. on the first line leave the price as it is (from pricelist), and on the second one change the price
3. complete the Quotation 
4. actions -> Create Sales Order from this Quotation, Start
=> new sales order was created OK
=> both prices were the same, from price list NOK
(will check again after a next rollout)
