### ISSUE TITLE
New Textfield for Product Ingredients without BOM

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4417]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, Ingredients can be recorded via BOM.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
In Product>>Businesspartner it shall be possible to record Product Ingredients without creating a BOM/ BOM Product. Please add a new Field in there (near Customer Label Field) and make it translatable.

**Comment by metas-ts** [comment]
got feedback:	
* somewhere in the UI it sais "Ingredients". pls update the DE and de_CH trls to "Zutaten"
* also please translate the tab; DE/ de_CH should be `Produkt Allergene`
* also, please add an ingredients field to M_Product
* in the swing-ui, make both ingredient fields 2 columns wide and 2 rows deep (or does this collide with the webui's layout?)
* also, pls show CustomerLabelName in M_Product..can be advanced field, such that it looks siming to the C_BPArtner_Product field (i.e. first CustomerLabelName then ingredients)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / customer db

1. Ingredients = Zutaten:
* product window: still "Ingredients" in de_DE & de_CH, WebUI & Swing: NOK
* product window, bpartner tab: "Zutaten" in de_DE & de_CH WebUI, but "Ingredients" in Swing for both: NOK
2. Ingredients field in product window, advanced edit (WebUI): OK
3. Ingredients field in product window, bpartner tab: OK
4. in the swing-ui, make both ingredient fields 2 columns wide and 2 rows deep: OK (not yet in customer db)
5. CustomerLabelName in M_Product: OK

**Comment by metas-lc** [comment]
IT
1. Ingredients in BPartner Product tab
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK
(checked both swing and webui)

2. Ingredients in Product window (adv edit)
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK
(checked both swing-main tab and webui)

3. ingredient fields looks like a help field OK

4. open Product BPartner translation window
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK
does not look like a help field (multiple rows and columns) NOK

5. Product Allergen tab
en_US: Product Allergen OK
de_DE: Produkt Allergene OK
de_CH: M_Product_Allergen NOK
(both swing and webui)

6. CustomerLabelName in M_Product

**Comment by metas-ts** [comment]
hi @metas-rc ,
I got another bit of user feedback:
please add the "ingredients" to `M_Product_Trl` and `C_BPartner_Product_Trl` so they can be translated as well

**Comment by metas-rc** [comment]
on it

**Comment by metas-lc** [comment]
IT
(remaining issue:  BPartner Product TRL in swing: Ingredients not trl for DE and CH)

1. Ingredients in BPartner Product tab WebUI
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

2. Ingredients in BPartner Product tab Swing
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

3. Ingredients in BPartner Product TRL window WebUI
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

4. Ingredients in BPartner Product TRL tab Swing
en_US: Ingredients OK
de_CH/de_DE: Ingredients NOK

5. Ingredients in Product window (adv edit) WebUI
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

6. Ingredients in Product window Swing
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

7. Ingredients in Product TRL window (adv edit) WebUI
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

8. Ingredients in Product TRL tab Swing
en_US: Ingredients OK
de_CH/de_DE: Zutaten OK

9. ingredient fields looks like a help field OK

10. Product Allergen tab WebUI
en_US: Product Allergen OK
de_DE: Produkt Allergene OK
de_CH: Produkt Allergene OK

11. Product Allergen tab Swing
en_US: Product Allergen OK
de_DE: Produkt Allergene OK
de_CH: Produkt Allergene OK

12. CustomerLabelName in M_Product Web UI
Auszeichnungsname? (not trl) NOK

13. CustomerLabelName in M_Product Swing
en_US: CustomerLabelName OK
de_DE: Auszeichnungsname OK
de_CH: Auszeichnungsname OK

**Comment by metas-dh** [comment]
Results of IT4
tested in mf15

checked WebUI & Swing, de_DE, de_CH & en_US:

1. - 13.: all OK
