### ISSUE TITLE
Add vattaxid in Docs_Purchase_Order_Details_Sum function

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4423]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
Function Docs_Purchase_Order_Details_Sum should return also vattaxid

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

normal PO:
* purchase order sums ok, working as before, taxes calculated correctly, Jasper fine as well: OK

need to check on customer db prob. as well

**Comment by metas-dh** [comment]
checked with metas-mk: OK, rolled out at customer, working fine.
