### ISSUE TITLE
Missing lines in jasper documents

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4428]
### Is this a bug or feature request?
bug
### What is the current behavior?
lines are missing from jasper documents if the product category is inactive
#### Which are the steps to reproduce?
make some orders/inouts/invoices with some products
go to product category and make it inactive
print preview
=> line not shown
### What is the expected or desired behavior?
line shall be visible

fix where-clause  
pc.M_Product_Category_ID != getSysConfigAsNumeric('PackingMaterialProductCategoryID', ol.AD_Client_ID, ol.AD_Org_ID)
to work on null cases as well

**Comment by metas-lc** [comment]
(you can also inactivate a product category - the product should still be visible)
check:
1. sales order, invoice, inout
2. purchase order, invoice, inout
3. order control (bestellkontrolle)
4. trace report
5. picking terminal (jasper)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

material receipt Jasper: products of inactive category not displayed: NOK

**Comment by teosarca** [comment]
@metas-lc  @metas-mk  what if the product is deactivated. Which shall be the behaviour? Pls consider creating a follow-up if needed.

**Comment by metas-lc** [comment]
all document, besides inouts, had left join on category, which is used to check if the product is a packing material or not. So i put left join on inouts as well. 
Product category being inactive is not a normal case, but since is used only for this, we made sure the product is still shown. 
If a product is deactivated, should not be visible atm. 
@metas-mk if you think it should be, i'll create a task.

**Comment by metas-lc** [comment]
Actually, i see there are cases where the product's name is hidden if the product is inactive and cases where the whole line is gone (like receipt). We should fix to have the same in all cases..

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* material receipt Jasper: products of inactive category now displayed as well, OK
* inactive product: not shown in the Jaspers, but in material receipt the whole line is not displayed (see comment above): @metas-lc is there a follow up for this already?

**Comment by metas-dh** [comment]
checked with metas-mk: 
inactive product: not shown in the Jaspers, but in material receipt the whole line is not displayed (see comment above): OK for now, might need to fix in the future, will create a task then.
