### ISSUE TITLE
Refund Flatrate Terms adjustments

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4444]
https://github.com/metasfresh/md100/issues/248

Important: the 90 days notification
* The process that runs each night: de.metas.contracts.flatrate.process.C_Flatrate_Term_Extend
* Make sure it also notifies the user.
* Regression testing on flatrate terms for Refund

**Comment by metas-rc** [comment]
TO DO:

* Rename the process de.metas.contracts.flatrate.process.C_Flatrate_Term_Extend and refactor it to make it obvious it also deals with notifications
* Add an entry in AD_Scheduler for the process with FrequencyType = "D", Frequency = 1, cronPattern = "0 4 * * *" ( I think, from some older system which had this process scheduled)
* Implement a notification producer for flatrate terms where a de.metas.notification.UserNotificationRequest is created
* Call it after a notification is created for a term
* Create Notification Group for the flatrate terms in contracts
* Test

**Comment by metas-lc** [comment]
IT
1. process: de.metas.contracts.flatrate.process.C_Flatrate_Term_Extend_And_Notify_User
scheduler: Ablaufende Verträge verarbeiten
2. go to your profile (settings) and add new notification: Contracts. Type notification
3. see https://github.com/metasfresh/metasfresh/issues/3999 for how to configure the refund: create a new contract term of that refund type. For period, create a new contract period, duration 6 months, notice: 3 months, interval e.g. 7 days. Set this period to term and complete both
4. go to a bpartner and run Create Contract: select your term, start date: 3 months before (now we are in 09.08.2018 so i'll set it to 10.05.2018), start
=> new contract was created for my bpartner OK
=> Start Date: 05/10/2018
=> Contract End: 11/09/2018
5. (here i run an sql to have in manu the process that runs 1/day. So i ran Ablaufende Verträge verarbeiten)
=> no notifications. Smth related with priceactual not in context
(besides priceactual, please also check currency, taxcategory?)
also did not get ICs

**Comment by metas-lc** [comment]
IT
tested again. 
Now i get only 1 notification, with the link to contract. OK

also tested notifications for multiple contracts
=> got as many notifications as the contracts OK

(todo: check tomorrow if i get the notification)
