### ISSUE TITLE
HU Editor in picking terminal shows all HUs: not filtered for product 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#4451]
### Is this a bug or feature request?
bug
### What is the current behavior?
picking teriminal: you can see HUs from other products
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh/issues/4276
1. Have sev. HUs with different products, from material receipt or manufacturing
2. Create a sales order, for e.g. Convenience Salat and check the Picking Terminal:
=> HUs with product != Convenience Salat are displayed in HU Editor, NOK 
(the next 2 steps from 4276 seem to work fine)
### What is the expected or desired behavior?
shall see only HUs with the product you selected

**Comment by metas-lc** [comment]
note: checked further. The filter is not working well only on those lines that come from contracts. (that don't have sales order in picking)
Also, another issue: if you create a new sales order (docno 0018), it won't appear in picking. Create a new one (docno 0019) and then 0018 will appear...

**Comment by metas-ts** [comment]
> Also, another issue: if you create a new sales order (docno 0018), it won't appear in picking. Create a new one (docno 0019) and then 0018 will appear...

that's more of a refreshing issue (i believe there is such an issue in development) and not related to this issue.

**Comment by metas-lc** [comment]
IT
1. create a sales order and set Terms and Conditions: add abo
2. complete order 
=> new contract created OK
3. go to picking terminal, select your line (sales order is not set)
4. open hu selection window 
=> HUs != Convenience Salat are displayed NOK 
(will check it again after a new rollout..)
.
about the picking refresh issue - couldn't reproduce it anymore OK
