### ISSUE TITLE
Material Cockpit - allow to configure the attribute detail rows' dimenstion spec

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4456]
### Is this a bug or feature request?
FR
### What is the current behavior?
material cockpit's detail rows are always using the `DIM_Dimension_Spec` record with `InternalName=Material_Cockpit_Default_Spec`

### What is the expected or desired behavior?

add sysconfig `de.metas.ui.web.material.cockpit.DIM_Dimension_Spec.InternalName` so this can be configured

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* `de.metas.ui.web.material.cockpit.DIM_Dimension_Spec.InternalName` to configure the attributes in Material Cockpit: OK
* checked the configs `DIM_damaged_expired` & `Material_Cockpit_Default_Spec`: OK
* when value in the SysConfig is left empty: error when opening Material Cockpit: 
=> `Unable to load DIM_Dimension_Spec record with InternalName=`: NOK, shall fall back to the default spec

**Comment by metas-dh** [comment]
Results of IT2
tested mf15

* `de.metas.ui.web.material.cockpit.DIM_Dimension_Spec.InternalName` to configure the attributes in Material Cockpit: OK
* checked the configs `DIM_damaged_expired` & `Material_Cockpit_Default_Spec`: OK
* when value in the SysConfig is left empty: fallback to default spec, `Material_Cockpit_Default_Spec`: OK
