### ISSUE TITLE
Material Cockpit - show stock details

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4459]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
This is how it currently looks.
![image](https://user-images.githubusercontent.com/1264789/43706595-204876e6-9966-11e8-8112-dd7417e654a4.png)

Notes:
* the right pane opened after the it hit the "Bestandasdetails anzeigen" aktion.
 * **TODOs**
   * it shall not be a "right/detail pane", but an "overlay pane", similar to the ones we have e.g.
     * for the purchase candidates from sales order
     * for the pricing conditions (i guess; didn't see them) from material cockpit itself
   * there needs to be a "Bestätigen" button to close the overlay again.

Some technicalities: 
* the stock details are based on `StockDetailsRow`...
* under the hood it's the view `M_HU_Stock_Detail_V`
* the details pane is opened by the process `MD_Cockpit_ShowStockDetails`
  * most of the process code is about building the filter that is later evaluated in `StockDetailsViewFactory`

**Comment by metas-ts** [comment]
as talked in MM

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. stock details open in modal overlay: OK
2. "Bestätigen" button to close the overlay again: OK
3. stock details are displayed as follows:
* HU value: OK
* per attribute from the attribute set instance (so if the product has an asi with 3 attributes set in category, 1 HU is shown once for each attribute, => 3 times): OK? when no attribute is set?

![2018-08-15 10_59_34-notificationsform](https://user-images.githubusercontent.com/18696715/44140570-ba65d226-a07a-11e8-9254-9efba7494da0.png)


* attribute, warehouse, Gebinde status, bpartner, qty & UOM for each HU: OK
* sum of qties in stock details matches qty shown in main window (also regarding attributes): OK
4. overlay is just called "Modal", see pic: pls make it "Stock details" / "Bestandsdetails"

**Comment by metas-dh** [comment]
checked with metas-mk: 

3. stock details are displayed as follows: per attribute from the attribute set instance: OK
4. overlay is just called "Modal": follow-up: #4510
