### ISSUE TITLE
Wrong pricelist when different invoice partner in sales order

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4463]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you have a sales order with a different invoice partner, then the pricelist set is incorrect.
#### Which are the steps to reproduce?
1. Have 2 partners, with a relation (e.g. partner B as invoice partner for partner A)
2. Both partners shall have the same sales pricelist
3. Create a sales order for partner A:
=> sales pricelist is set, OK
4. Set partner B as invoice partner:
=> pricelist is updated, to Diverse: NOK
### What is the expected or desired behavior?
Shall be the correct pricelist.

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine OK
pricelist is not updated OK
.
created a new sales pricelist and set it to bpartner B
repeat the testcase above
=> pricelist did not change. Still one for BP A OK
Set BP B as business partner
=> pricelist updates for B OK
Set A as bill BP
=> pricelist does not update OK
