### ISSUE TITLE
Refund contract - add further options

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4475]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
## RefundMode = ALL_MAX_SCALE

### Given

#### RefundConfig

| ConfigId | MinQty | %  |
| -------- | ------ | -- |
| 1        | 0      | 10 |
| 2        | 15     | 20 |

#### AssignableCandidate

| AssignableCandidateId | Qty | Money |
| --------------------- | --- | ----- |
| 10                    | 13  | 10    |
| 11                    | 3   | 10    |

#### Assignment

| AssignmentId | ConfigId | AssignableCandidateId | RefundCandidateId | % applied | AssignedQty | UseAssignedQtyInSum | AssignedMoney |
| ------------ | ---------| --------------------- | ----------------- | --------- | ----------- | ------------------- | ------------- |
| 30           | 1        | 10                    | 20                | 10        | 13          | true                | 1             |

Note: AssignableCandidate-10 is already assigned, AssignableCandidate-11 will be assigned in this test.

#### RefundCandidate

| RefundCandidateId | AssignedQty | AssignedMoney |
| ----------------- | ----------- | ------------- |
| 20                | 13          | 1             |


### Expected

#### Assignment

| AssignmentId | ConfigId | AssignableCandidateId | RefundCandidateId | % applied | AssignedQty | UseAssignedQtyInSum | AssignedMoney | Notes |
| ------------ | ---------| --------------------- | ----------------- | --------- | ----------- | ------------------- | ------------- | ----- |
| 30           | 1        | 10                    | 20                | 10        | 13          | true                | 1             | "% applied": % of config-1
| 31           | 2        | 10                    | 20                | 10        | 13          | false               | 1             | "% applied": % of config-2 minus config-1
| 32           | 1        | 11                    | 20                | 10        |  1          | true                | 0.33          | "AssignedMoney": 10% of 1/3 * 10
| 34           | 1        | 11                    | 20                | 10        |  2          | true                | 0.67          | "AssignedMoney": 10% of 2/3 * 10
| 33           | 2        | 11                    | 20                | 10        |  1          | false               | 0.33          |
| 35           | 2        | 11                    | 20                | 10        |  2          | false               | 0.67          |

#### RefundCandidate

| RefundCandidateId | AssignedQty | AssignedMoney | Notes |
| ----------------- | ----------- | ------------- | ----- |
| 20                | 16          | 4             | "AssignedMoney": 20% of (10+10)

Note: if we fall below the  minQty of config-2, then we can simply delete all assignments with ConfigId=2.
After this deletion, both the refundcandidate's AssignedQty and AssignedMoney are updated using the view C_Invoice_Candidate_Assignment_Aggregate_V.

----------------------------------------------------------------

## RefundMode = PER_INDIVIDUAL_SCALE

### Given

#### RefundConfig

| ConfigId | MinQty | %  |
| -------- | ------ | -- |
| 1        | 0      | 10 |
| 2        | 15     | 20 |

#### AssignableCandidate

| AssignableCandidateId | Qty | Money |
| --------------------- | --- | ----- |
| 10                    | 13  | 10    |
| 11                    | 3   | 10    |

#### Assignment

| AssignmentId | ConfigId | AssignableCandidateId | RefundCandidateId | % applied | AssignedQty | UseAssignedQtyInSum | AssignedMoney |
| ------------ | ---------| --------------------- | ----------------- | --------- | ----------- | ------------------- | ------------- |
| 30           | 1        | 10                    | 20                | 10        | 13          | true                | 1             |

Note: AssignableCandidate-10 is already assigned, AssignableCandidate-11 will be assigned in this test.

#### RefundCandidate

| RefundCandidateId | AssignedQty | AssignedMoney |
| ----------------- | ----------- | ------------- |
| 20                | 13          | 1             |

### Expected

#### Assignment

| AssignmentId | ConfigId | AssignableCandidateId | RefundCandidateId | % applied | AssignedQty | UseAssignedQtyInSum | AssignedMoney | Notes |
| ------------ | ---------| --------------------- | ----------------- | --------- | ----------- | ------------------- | ------------- | ----- |
| 30           | 1        | 10                    | 20                | 10        | 13          | true                | 1             | "% applied": % of config-1
| 31           | 1        | 11                    | 20                | 10        |  1          | true                | 0.34          | "AssignedMoney": 10% of 1/3 * 10
| 32           | 2        | 11                    | 20                | 20        |  2          | true                | 1.34          | "% applied": % of config-2; "AssignedMoney": 20% of 2/3 * 10

#### RefundCandidate

| RefundCandidateId | AssignedQty | AssignedMoney | Notes |
| ----------------- | ----------- | ------------- | ----- |
| 20                | 16          | 2.67          | "AssignedMoney": 1 and 10% of ( 10 plus 1/3 of 10 ) + 20% of 2/3 of 10

**Comment by metas-dh** [comment]
Results of IT
tested in customer db

checked results directly w/ metas-dh, documented in https://github.com/metasfresh/md100/issues/291: NOK

**Comment by metas-ts** [comment]
# Dev-Test (partial, WIP)

## Tiered refund (Gestaffelte Rückvergütung)

### Conditions

![image](https://user-images.githubusercontent.com/1264789/49071502-66af9300-f22e-11e8-9bb8-f351df120566.png)

### Refundable invoice candidates

Theses are ICs from two actual purchase orders

#### First (Qty=1)
![image](https://user-images.githubusercontent.com/1264789/49071580-93fc4100-f22e-11e8-99c0-01e8fe9c02ad.png)

#### Second (Qty=30)
![image](https://user-images.githubusercontent.com/1264789/49071640-b55d2d00-f22e-11e8-995a-694751433dcc.png)

### Refund invoice candidates

These are ICs that are created by the system in accordance to the refundable candidates

#### First

![image](https://user-images.githubusercontent.com/1264789/49071807-14bb3d00-f22f-11e8-93b1-921b5b0d0521.png)

Note that it handles 1+13=14 purchased items from both ICs in accordance to the first refund config (for quantities between 0 and 14, give 10% refund)

#### Second

![image](https://user-images.githubusercontent.com/1264789/49072119-d5d9b700-f22f-11e8-97db-816f32a9448a.png)

Note that it handles 17 purchased items from the 2nd IC (the one with qty=30) in accordance to the second refund config (for quantities from 15 upwards, give 20% refund)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

### I. Tiered refund (Gestaffelte Rückvergütung)
**1. refund for percentage:** 
Setup similar to settings in DevTest, but 1st purchase order was created with qty:10, 2nd purchase order was also created with qty:30:
* Refund IC was correctly created after each material receipt: OK
* Refund IC 1 for tier 1: handling qty: 14 (10+4=14, purchased items from both ICs in accordance to the first refund config (for quantities between 0 and 14, give 10% refund), => 1.40 €: OK
* Refund IC 2 for tier 2: handling qty: 26 (30-4=26, purchased items from the 2nd IC (the one with qty=30) in accordance to the second refund config (for quantities from 15 upwards, give 20% refund), => 5.20 €: OK

**but:**  after invoicing the ICs for the purchase orders, the Refund ICs are updated and the tiered refund seems to be ignored:
* Refund IC 1 for tier 1: now only shows qty:10, 1,00 € => 10% for the first order only: NOK
* Refund IC 2 for tier 2: now shows qty:30, 6,00 € => 20% for the second order only: NOK

**2. refund for amount:**
Setup similar to settings in DevTest, but 1st purchase order was created with qty:10, 2nd purchase order was also created with qty:30; Refund: 1€ from qty:0 and 5€ from qty: 30:
* Refund IC was created after each material receipt: OK

**but:** Refund ICs have 
* price eff. 0.00: NOK
* and show no related IC from the order (Rückzuvergütende RKn): NOK
(no change after invoicing the POs)

### II. Accumulated refund (Gesamtrückvergütung)
**1. refund for percentage:** 
Setup similar to settings in DevTest, but 1st purchase order was created with qty:10, 2nd purchase order was also created with qty:30:
* Refund IC was correctly created after material receipt: OK
* Refund IC is updated after 2nd material receipt, shows all related ICs from the orders (1IC per contract term, => 4 ICs): OK

**but:** 
* after invoicing the 1st PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn): NOK
* after invoicing the 2nd PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn), so there are no ICs there at all: NOK
* price in the Refund IC is also updated incorrectly after invoicing the POs NOK

**2. refund for amount:**
Setup similar to settings in DevTest, but 1st purchase order was created with qty:10, 2nd purchase order was also created with qty:30; Refund: 1€ from qty:0 and 5€ from qty: 30:
* Refund IC was created / updated after each material receipt: OK

**but:** Refund IC has
* price eff. 0.00: NOK
* and shows no related IC from the order (Rückzuvergütende RKn): NOK
(no change after invoicing the POs)

**Comment by metas-dh** [comment]
Results of IT3

### I. Tiered refund (Gestaffelte Rückvergütung)
**1. refund for percentage:** 
Setup as in DevTest, 1st purchase order was created with qty:1, 2nd purchase order with qty:30:
=> after invoicing the ICs for the purchase orders, the tiered refund is still considered in the Refund ICs:
qties and amts remain the same: OK

**2. refund for amount:**
Setup as in DevTest, 1st purchase order was created with qty:1, 2nd purchase order was also created with qty:30; Refund: 1€ from qty:0 and 5€ from qty:30:
* Refund IC was created after each material receipt: OK
* Refund IC 1 for tier 1: handling qty: 1, refund: 29,00 €
    * Rückzuvergütende RKn 1: qty:1, amt: 1,00 € (from 1st PO)
    * Rückzuvergütende RKn 2: qty:28, amt: 28,00 € (from 2nd PO)
* Refund IC 2, for tier 2: handling qty: 1, refund: 10,00 €:  (from 2nd PO)
* show the related IC from the order (Rückzuvergütende RKn): OK
(no change after invoicing the POs)
=> after invoicing the ICs for the purchase orders, the tiered refund is still considered in the Refund ICs:
qties and amts remain the same: OK


### II. Accumulated refund (Gesamtrückvergütung)
**1. refund for percentage:** 
Setup as in DevTest, 1st purchase order was created with qty:1, 2nd purchase order was also created with qty:30; Refund: 1€ from qty:0 and 5€ from qty:30:
* Refund IC was correctly created  / updated after material receipt: OK
* Refund IC is updated after 2nd material receipt, shows all related ICs from the orders (1IC per contract term, => 4 ICs): OK
* handling qty: 1, amt: 6,20 (2x 0,10 + 2 x 3,00)

**but:** 
* after invoicing the 1st PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn): NOK
* after invoicing the 2nd PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn), so there are no ICs there at all: NOK
* price in the Refund IC is also updated incorrectly after invoicing the POs (3,10 €): NOK
=> still happening

**2. refund for amount:**
Setup as in DevTest, 1st purchase order was created with qty:1, 2nd purchase order was also created with qty:30; Refund: 1€ from qty:0 and 5€ from qty:30:
* Refund IC was correctly created  / updated after material receipt: OK
* Refund IC is updated after 2nd material receipt, shows all related ICs from the orders (1IC per contract term, => 4 ICs): OK
* handling qty: 1, amt: 155,00 (1x 1,00 + 1 x 4,00 from PO IC1, 1x 30,00 + 1x 120,00 from PO IC2 )

**but:** Refund IC has
* fter invoicing the 1st PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn): NOK
* after invoicing the 2nd PO, the ICs from this order disappear from the Refund IC (Rückzuvergütende RKn), so there are no ICs there at all: NOK
* price in the Refund IC is also updated incorrectly after invoicing the POs (124,00 €): NOK
=> still happening

**Comment by metas-dh** [comment]
Results of IT4
tested in mf15

checked the NOKs from last IT again, for Accumulated refund (Gesamtrückvergütung):

**1. refund for percentage:**
=> after invoicing the ICs for the purchase orders, the tiered refund is still considered in the Refund ICs:
qties and amts remain the same: OK

**2. refund for amount:**
=> after invoicing the ICs for the purchase orders, the refund is still considered in the Refund ICs:
qties and amts remain the same: OK
