### ISSUE TITLE
Support Doctype Text templates also on purchase order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4482]
### Is this a bug or feature request?
FR

### What is the current behavior?
metasfresh supports putting header and footer text tempates into sales order and invoice
http://docs.metasfresh.org/webui_collection/EN/Print_text_on_documents-doctype.html

if you try this for purchase order the text template will be reapplied on completion.
case:
1. configure header and footer text for doctype purchase order
1. create a new purchase order with lines
1. OK: text is copied to fields in purchase order
1. edit the text and put something else
1. OK: text is displayed 
1. complete the order
1. NOK: text is set back to default

### What is the expected or desired behavior?
we do want to support that also in purchase order

todo:
- change that behaviour
- create an automatic test

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* doctype text template is used in new purchase order: OK
* manually changed texts are not set back to default when completing the order: OK

* automatic test = unit  test?
