### ISSUE TITLE
Introduce Window Tab's Internal Name

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4491]
### Is this a bug or feature request?
FR

### Results
The internal name can be set here:
![image](https://user-images.githubusercontent.com/1264789/44910468-97615880-ad23-11e8-8af8-459b642d3fdd.png)

If not set, then the API returns an auto generated internal name as show in Teo's screenshot (see below).
Most AD_Tab.InternalNames were set to the respective AD_Table TableName  via migration script

**Comment by metas-ts** [comment]
related to https://github.com/metasfresh/metasfresh-webui-api/issues/1023

**Comment by metas-ts** [comment]
note to IT: Imho an IT would be to create a cypress test that opens a tab (e.g. in the bpartner window)

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/44386294-ca893800-a52a-11e8-97d9-8206fb622549.png)

**Comment by metas-dh** [comment]
needs https://github.com/metasfresh/metasfresh-webui-frontend/issues/1926 to be implemented before IT.

**Comment by metas-dh** [comment]
Results of IT1
tested in dev120

see IT for  metasfresh/metasfresh-webui-frontend#1926

=> some tabs had an internal name like "Window-123-496", OK, but others had sth like "Customer" (=> Customer tab in bpartner window): bc of "Most AD_Tab.InternalNames were set to the respective AD_Table TableName via migration script", so i guess this is OK?
