### ISSUE TITLE
Projecttype Org Validation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4494]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Projecttype in Project Window does not respect the Org Validation.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Fix it.

**Comment by metas-dh** [comment]
tested by metas-mk, OK, see https://github.com/metasfresh/me03/issues/301
