### ISSUE TITLE
Make fields in explicit user filter mandatory or optional

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4498]
### What is the current behavior?
today all fields are mandatory when you configure a user filter and leave the values empty

### What is the expected or desired behavior?
* show filter fields to user (as today)
* be able to configure if those fields all together are mandatory (like today) or not at all

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/44412393-82d9cf00-a571-11e8-9cfd-614dd50ca825.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. set `Display All Parameters` & `Mandatory Parameters` to `Y` for user filter Abrechnung_offen_normal
2. check filter  in printing queue:
* parameters are not displayed: NOK i think
* mandatory parameters: not sure since they were not displayed
3. question: does it make sense to be able to set `Mandatory Parameters` to `Y`, but have `Display All Parameters`  not set?afaiu the user then cannot see the parameters in the filter, but they are all mandatory; @teosarca wdyt?

**Comment by teosarca** [comment]
note: the default value is not set on frontend side, even though is provided by backend.
Shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1944.

**Comment by metas-mk** [comment]
@teosarca 
caption shall not be set with cornered brackets.
![image](https://user-images.githubusercontent.com/13365687/45164245-6042e980-b1f2-11e8-89b0-62ac6ddbcc9f.png)

**Comment by metas-dh** [comment]
Update:
in latest e2e, the filters did not work, when trying to apply them nothing happens and you get this in console:

<details>

```
daterangepicker.js:12 Uncaught TypeError: Cannot read property 'isActive' of null
    at value (daterangepicker.js:12)
    at value (index.js:9)
    at Object.I (react-dom.production.min.js:13)
    at Object.invokeGuardedCallback (react-dom.production.min.js:13)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:13)
    at K (react-dom.production.min.js:13)
    at ee (react-dom.production.min.js:13)
    at ne (react-dom.production.min.js:13)
    at Array.forEach (<anonymous>)
    at $ (react-dom.production.min.js:13)

```
</details>

**Comment by teosarca** [comment]
@metas-dh  this looks like a frontend issue. I think it's related with those recent filters changes in frontend.
Pls link it there...

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. set Display All Parameters & Mandatory Parameters to `Y` for different user filters in printing queue
2. check filter in printing queue: 
* parameters are displayed: **OK** (needs cache reset!)
* mandatory parameters:
    * checkbox: if mandatory filter is `Y`, then it is set, OK, if the mandatory filter is `N` then the filter is not set => https://github.com/metasfresh/metasfresh-webui-frontend/issues/1962
    * if the mandatory filter is not set, you get an error with info about the mandatory parameter not being set: **OK**
    * dropdown: marked as mandatory field, and set correctly: **OK**
3. filter results are correct: **OK** 
4. if filter params are not set mandatory / not displayed, the filter works fine as well: **OK**
