### ISSUE TITLE
OCRB not available in JVM but needed for ESR page

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#451]
when switching the org partner address to switzerland I get this error when print previewing invoices:
Font "OCRB" is not available to the JVM. See the Javadoc for more details.

background: OCRB is not open source licenced and therefore not part of the official release which is under GPL.

**Comment by metas-ts** [comment]
TODO next: ckeck branch build

**Comment by metas-ts** [comment]
in the branch build, the OCRB-font is back :-) 
integrating now

**Comment by metasnw** [comment]
successfully tested. part of this weeks release
