### ISSUE TITLE
Extend Sales Order REST API to support price and support all product values

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4517]
### Is this a bug or feature request?
FR

### What is the current behavior?
as result of  #4340
- you can not specify price but the price is taken from pricelist
- in some cases the product value is not accepted

#### Which are the steps to reproduce?
details  @metas-nw

### What is the expected or desired behavior?
- stdprice can be delivered
- if delivered checkbox price manual should be Y

**Comment by teosarca** [comment]
Introduced manual price support.

e.g.
```json
{
  "shipBPartnerCode": "G0001",
  "datePromised": "2018-07-05T00:00:00.000Z",
  "lines": [
    {
      "productCode": "G0001",
      "qty": 12, 
      "price": 13
    }
  ]
}
```

Remark the `"price": 13`.
If the `price` property is not set, the standard price will be fetched.

**Comment by metasnw** [comment]
IT: OK
