### ISSUE TITLE
Requests cannot be saved

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4520]
### Is this a bug or feature request?
Bug

### What is the current behavior?

https://github.com/metasfresh/metasfresh/issues/4426 means  that we need to add a ton of AD stuff at a lot of places
* AD_Fields where we don't want to see them, but filter by them or work with them in callouts
* set parent link columns in AD_Tab
* probably more

### What is the expected or desired behavior?

shall work as before. if a weird problem as in https://github.com/metasfresh/metasfresh/issues/4426 happens again, we shall check again..but it probably won't; i believe the actual way to fuix the problem might have been adding a `/-1` to the `@whatever@` expression. meanwhile afaiu the error messages also improved

**Comment by metas-ts** [comment]
* I was unable to reproduce the particular issue that the customer has documented on their instance. Creating new requests work on my more-or-less vanilla local DB.
N ote that afaik the window in question was pretty customized.

* However, I undid the major change from issue https://github.com/metasfresh/metasfresh/issues/4426 so it's not anymore required to have `AD_Field` recrods for each `AD_Column` etc etc.

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
had no problems with creating requests in e2e either, all worked fine.

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/commit/dc874b7507b966fd0354e49b604372e0927f0091 to `release`

**Comment by metas-rc** [comment]
Results of IT

* Request window works correctly -> OK
* Meanwhile we also had this task: https://github.com/metasfresh/metasfresh-webui-api/issues/1040
* If I manually put the window ID for the Requests  window (201) that we used in the past in the URL, I can see the entries that fit the whereclause -> OK
* I cannot create new entries in this Requests window. Created a followup for it: https://github.com/metasfresh/metasfresh-webui-api/issues/1052
