### ISSUE TITLE
Don't create subscription shipment schedules for products that are no items

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4521]
### Is this a bug or feature request?
FR

### What is the current behavior?

If there is a `C_SubscriptionProgress` record, the system ususally creates an `M_ShipmentSchedule` for it.

### What is the expected or desired behavior?

just like we have it with `C_OrderLine`s the system shall only create `M_ShipmentSchedule` records for  `C_SubscriptionProgress` records that are about a product with `M_Product.ProductType == 'I'` ("item").
Not e.g. for products with type S(ervice).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. have 2 products, A with `M_Product.ProductType == 'I'` and B with `M_Product.ProductType == 'S'`
2. create sales order, with an orderline for each product
3. set flatrate term in both orderlines, complete the order
4. check created contracts:
Product A:
* `C_SubscriptionProgress` records created, with an `M_ShipmentSchedule` for the first one: OK
Product B:
* `C_SubscriptionProgress` records created, but **no** `M_ShipmentSchedule` : OK
