### ISSUE TITLE
Fix problems wrt invoice candidate creation from subscription flatrate terms

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4523]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Can't create multiple invoice candidates that refer to the same orderline, because of a DB constraint.
According to the code, this constraint seems obsolete for a long time (see e.g. `IInvoiceCandDAO.retrieveInvoiceCandidatesForOrderLine(...)`).

#### Which are the steps to reproduce?
@metasnw  Knows

### What is the expected or desired behavior?
:rainbow: :rainbow:  & :unicorn: :unicorn:

**Comment by metas-ts** [comment]
Fixes:
* Drop legacy unique constrain in C_Invoice_Candidate
* Fix bug in the BL

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metasnw** [comment]
IT: Problem is solved
