### ISSUE TITLE
Filter for attributes in picking terminal shall be set by default

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4526]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Atm the filter for attribute in picking terminal is `N` by default, but shall be `Y`.

![2018-08-28 12_24_34-metasfresh](https://user-images.githubusercontent.com/18696715/44717502-6c75cb00-aabd-11e8-97fc-8b77ef09004d.png)

#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Attribute filter shall be set by default.

**Comment by cristinamghita** [comment]
Don't IT until this task is not solved
[ #1944 Filter for attributes in picking terminal is not set on Y altough should be](https://github.com/metasfresh/metasfresh-webui-frontend/issues/1944)

**Comment by metas-dh** [comment]
this was fixed now by https://github.com/metasfresh/metasfresh-webui-api/issues/1067.
