### ISSUE TITLE
Can not add new scale price on 5.71

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4528]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
1. open window/540325
1. pick any product
1. click on "add scale price"
1. NOK: exception

<details>

```

Error: Datensatz kann nicht gelöscht...
Server error
Datensatz kann nicht gelöscht werden, weil er von anderen Datensätzen referenziert wird Cause: ERROR: insert or update on table "m_productscaleprice" violates foreign key constraint "mproductprice_mproductscalepri" Detail: Key (m_productprice_id)=(1000004) is not present in table "m_productprice". ERROR: insert or update on table "m_productscaleprice" violates foreign key constraint "mproductprice_mproductscalepri" Detail: Key (m_productprice_id)=(1000004) is not present in table "m_productprice".

```

</details>

**Comment by teosarca** [comment]
might be related to https://github.com/metasfresh/metasfresh/issues/4520, but not sure.

**Comment by metas-ts** [comment]
Solved by @teosarca 's recent fix for https://github.com/metasfresh/metasfresh/issues/4520 :-)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* adding scale price with Scale Price: Add new: no exception, modal window for adding scale price opens and scale price can be set correctly: OK
* setting IsScalePrice=Y in header: new line in Scale Price is created, for qty:1, the price set in header is taken as standard price for the Scale Price: OK
