### ISSUE TITLE
Open PDF from Printing Queue stopped working

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4532]
### Is this a bug or feature request?
bug

### What is the current behavior?
- open window printing queue
- select any record
- click action "open PDF"
- NOK: nothing happens (see example /window/540165/1000144 )

log:
```
2018-09-06 09:13:36.957  WARN 11997 [ 0:0:0:0:0:0:0:1][        it] --- [http-nio-8080-exec-1] 
d.m.a.form.swing.SwingClientUIInstance   : Failed opening 
file:/tmp/10002021586345864525364376.pdf
```

**Note:** checked on server and the file exists and metasfresh user can open it.

### What is the expected or desired behavior?
should open the pdf

### Workaround
1. open printing queue
1. zoom into archive
1. zoom into print package
1. open attachments

**Comment by cristinamghita** [comment]
Fixed in https://github.com/metasfresh/metasfresh-webui-api/issues/1043

**Comment by metas-dh** [comment]
see IT for https://github.com/metasfresh/metasfresh-webui-api/issues/1043
