### ISSUE TITLE
Introduce AD_Table.IsEnableRemoteCacheInvalidation

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4536]
### Is this a bug or feature request?
FR
Required for https://github.com/metasfresh/metasfresh/issues/4524 but can be for many other tasks too.

### What is the expected or desired behavior?
If a table is flagged with IsEnableRemoteCacheInvalidation=Yes then remote cache invalidation for that table shall be enabled no matter what.

### Note to IT
This is pure technical. Cannot test it.

**Comment by metas-dh** [comment]
moving this to Done since it cannot be tested.
