### ISSUE TITLE
WebUI: New Translation Window for R_RequestType

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4538]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no Window to maintain the Translations of Request Types in WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create a Translation Window for Request type.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window for Translation R_RequestType (Request Type Translation / Aufgaben Typ Übersetzung): OK
* reference from window R_RequestType to Translation window: OK
* reference from window Translation R_RequestType to window R_RequestType: not working, see https://github.com/metasfresh/metasfresh-webui-api/issues/982
