### ISSUE TITLE
Return also URL using function de_metas_endcustomer_fresh_reports.Docs_Generics_Org_Report

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4541]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
Function de_metas_endcustomer_fresh_reports.Docs_Generics_Org_Report should return Fax ,	Postal,	City,	Email, and URL.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked in db:
de_metas_endcustomer_fresh_reports.Docs_Generics_Org_Report includes name, address, vataxid, phone, fax, postal, city, email, url: OK
