### ISSUE TITLE
sales order based process for contract extension

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4547]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
hi @cristinamghita 
> add a new column for this

i suggest to call the new column C_Order.Ref_FollowupOrder_ID and link let the old order reference the new one. wdyt?

**Comment by metas-ts** [comment]
>  process that will copy 

the process name shall be "Vertrag Verlängern" / "Extend contract"

**Comment by cristinamghita** [comment]
> i suggest to call the new column C_Order.Ref_FollowupOrder_ID and link let the old order reference the new one. wdyt?

Yes, I think is a good idea. Thx!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. sales order to create flatrate term: flatrate term correctly created: OK
2. call "Vertrag verlängern" for the sales order: status, draft, terms & conditions: as in original order: OK
3. complete the 2nd order:
* new flatrate term created: OK
* original flatrate term has the newly created one set as the following term: OK
* original order has the cloned order set as following order (adv edit): OK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

4. contract status in sales orders:
* original order: active after running the action for extension, before new order is completed, but set to extended when new order is completed and new contact is created: OK
* new order: active: OK
