### ISSUE TITLE
process to create dunning-PDF with concatenated invoice-PDFs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4554]
### Is this a bug or feature request?
FR

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

4. process in dunning doc: new process: "Mahnbeleg mit Rechnungsbelegen", resp. "Concatenate Dunning and Invoices PDFs": OK => **pls rename the en_US version of the process:** "Dunning PDF and attached invoices PDF"
5. process only available for single entry (in single view or selection of 1 doc in grid view): OK
6. process prints the dunning doc and the resp. sales invoice correctly: OK
