### ISSUE TITLE
Improve BPartner Memo-Import

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4557]
### Is this a bug or feature request?
FR
### What is the current behavior?

From `I_BPartner`, the following fields are imported as follows:
* `Memo`
* `Memo1`
* `Memo2`
* `Memo3`

are all concatenamed and imported into `AD_User`

#### TODO

* rename those four memo fields to `AD_User_Memo`, `AD_User_Memo1` , ...
* add another field `C_BPartner_Memo` and import the data from that field into `C_BPartner.Memo`.

**Comment by metas-rc** [comment]
Results of IT

* NOK: The Memo fields in Import Product are not displayed in webui

Tested on swing:

* OK: The 4 memo fields all present in Import Product
* Created an entry with all the 4 fields completed and ran Product Import:
* OK: The BPartner memo was correctly set
* NOK: The Memo field is not displayed in either User window or in the BPartner window's Contact tab, neither on swing nor on webui.
* NOK: The user memo remained empty, the values I entered did not get anywhere. I saw this by searching the database.

**Comment by cristinamghita** [comment]
> NOK: The Memo fields in Import Partnerare not displayed in webui
The field is shown now.
>NOK: The Memo field is not displayed in either User window or in the BPartner window's Contact tab, neither on swing nor on webui.
The field is displayed now in Contact Tab of Bussines Partner Pharma.
>NOK: The user memo remained empty, the values I entered did not get anywhere. I saw this by searching the database.
The data is saved now in AD_user.Memo field.

**Comment by metas-rc** [comment]
Results of IT: 

OK: The Memo fields in Import Partner are displayed in webui, in advanced edit section.

OK: The Memo field is displayed now in Contact Tab of Bussines Partner Pharma.
OK: The data is correctly saved in the AD_User.Memo
