### ISSUE TITLE
Show BPartner memo as tooltip in order

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4558]
### Is this a bug or feature request?
FR
Note: this issue can be ITed when metasfresh/metasfresh-webui-frontend#1952 is ready

### What is the expected or desired behavior?

If `C_BPartner.Memo` ("Sonstiges") is set for a given partner and that partner is selected in a sales or purchase order,
then the "memo" shall be accessible as a tool tip.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Show BPartner memo as tooltip in order:
* small document icon in bpartner field / invoice partner field in order: **OK**

![2018-09-26 09_58_00-metasfresh](https://user-images.githubusercontent.com/18696715/46068444-74d32b80-c179-11e8-987a-4464dcbf85a6.png)

* clicking on document icon opens text in a small box, with scroll bar in case of longer text: **OK**

![2018-09-26 10_18_05-metasfresh](https://user-images.githubusercontent.com/18696715/46068462-7dc3fd00-c179-11e8-9f90-c7160a2f2863.png)

* text from bpartner memo is fully displayed, no cut-offs (tested with ~1.900 characters), not too small to read: **OK**

* working fine for sales order, but missing in purchase order: **NOK**

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

Show BPartner memo as tooltip in order:
also available in Purchase Order now, working as in Sales Order: OK
