### ISSUE TITLE
QueryStatisticsLogger shall use logger instead of stderr

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4561]
#### Which are the steps to reproduce?
Enable SQL tracing. Check where the SQLs are logged.

### What is the expected or desired behavior?
SQLs shall be logged (as WARN) instead of printed to standard error.

Reason: on docker we don;t have access to std out/err.

### Configuration
By default, the SQLs are logged.
If you want to print them to stderr, start JVM with `-Dorg.adempiere.ad.dao.impl.QueryStatisticsLogger.LogToSystemError=true`.

Note: in time, this config might change, please check QueryStatisticsLogger class.

### Note to IT
Nothing to test.

**Comment by metas-dh** [comment]
moving this to Done since there is nothing to test.
