### ISSUE TITLE
sometimes missing purchase candidates aren't created

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4563]
### Is this a bug or feature request?
Bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Set 2 products A & B with a current vendor, have a discount schema for this vendor
2. Create a sales order, and have orderlines for the 2 products
3. Select all orderlines, and open overlay for creating purchase candidates:
* set a qty to order in purchase for 1 product A (partial qty!)
* don't set a qty for the other product B
=> OK
4. Check purchase candidates: candidate created for product A, none for B: **OK**
5. Go back to sales order, and create a purchase candidate for product B (partial qty!)
6. Check purchase candidates: additional candidate for product B: **OK**
7. Go back once to sales order, more and change the qty for the purchase candidate of e.g. product A, in the overlay
8. Check purchase candidates again: purchase candidates for both products, with qties as set / updated: **OK**
9. Complete the sales order, and check purchase candidates / purchase orders:
* purchase candidates marked as ordered: **OK**
* purchase order created with orderlines for both products: **OK**
* qties are as set / updated in the overlay: **OK**
