### ISSUE TITLE
Add note field to invoice candidates

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4568]
### Is this a bug or feature request?
FR

### What is the current behavior?

There is no field to add notes

### What is the expected or desired behavior?

The webui should have a field to add notes.
Note ( ;-) ): of our few swing-UI users, none requested a note, so we don't show the new field in the swingUI until further notice.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

new field for notes in invoice candidate window:
* new field Notiz / memo in advanced edit: OK
* multiline text field: OK
* text that is set not propagated to invoice (shall not be propagated acc. to metas-ts): OK
* texts from description header & bottom description in IC propagated to invoice: was not propagated, but not sure if it should?

**Comment by metas-dh** [comment]
info from testing chat: texts shall be propagated, created new issue, see above. closing this one.
