### ISSUE TITLE
Texts missing in cloned sales quotation 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4572]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Atm when you set texts in a sales quotation and clone it, the texts are missing in the new one. 
#### Which are the steps to reproduce?
1. Create a sales quotation
2. Set texts in header and orderline
3. Complete, and create sales order for the quotation
4. Clone the sales quotation
5. Check the new quotation: texts are missing, NOK
### What is the expected or desired behavior?
Texts shall be included in the new quotation.

**Comment by cristinamghita** [comment]
## Note
The text from order header(description and description bottom) is controlled trough flag isCopyDescriptionToDocument from C_DocType.
![image](https://user-images.githubusercontent.com/15378036/45540143-4e75cd80-b814-11e8-8d89-f3e3dc671bd1.png)
If that flag is set, the text exists in C_DocType will be copied in Order (in our case)
So, I would say, that is a config issue now and just take out that flag or set in there the description that is generally needed.

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. description in orderline was copied correctly in the cloned quotation: **OK**
2. if the isCopyDescriptionToDocument=N, then the text set in cloned quotation will be copied in the new quotation: **OK**
3. if the isCopyDescriptionToDocument=Y, the new quotation has the texts set in C_DocType set: **OK**
4. if the isCopyDescriptionToDocument=Y, then the text set in cloned quotation will also be copied in the new quotation: **OK**
