### ISSUE TITLE
OutOfMemoryError in HUSelectModel

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#458]
In short, the problem arises if a HU select panel is open for a longer time.
The problem is that generally, we dispose components only when a terminal dialog is closed.
This happens very frequently for the hu-editor, but not for the hu selection panes.
Also, the terminal bottons for partners, orders etc etc are frequently reset.
Since they are as of issue #370 added to a TerminalReferences (which is generally not disposed before the dialog is closed), we not agggregate a not of terminal keys.

This issue is about solving that problem by allowing to "detach" an ITerminalReferences instance with all the Disposables after a new set of keys was created (and added to that disposables which is now detached).
This dispatched ITerminalReferences can now be dispoaed with all those terminal buttons when the component considers it necessary.

**Comment by metas-dh** [comment]
Result of IT2
* App.Server: sp80aditdb
* Buildno:  #560
* DB: sp80aditdb : 5432 / metasfresh

* console warning: WARN 5462 — [WT-EventQueue-0] org.compiere.util.Msg : AD_Message not found: mettler-1: fixed, did not appear anymore
* Kommissionier Terminal: bpartner and date fields not displayed when selecting warehouse, cannot be selected; resp. bpartner and date is only displayed when selecting the orderline: fixed, fields are displayed and work as before
* msg in console when using weighing buttons in Wareneingang POS: Waiting 30ms before returning the MockedEndpoint{hostName=DOES NOT MATTER, port=0} result for command 'SI: checked with ts, OK
