### ISSUE TITLE
Excel Export and SQL for Product Specifications 

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4582]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
## Dev test
* The process can be run from product window and is run for all products
![image](https://user-images.githubusercontent.com/15378036/45436964-a6012580-b6bc-11e8-8512-5e5383634431.png)
* The file resulted from looks like the one from bellow.

**Comment by metas-mk** [comment]
@cristinamghita The Dev Test Screenshot of Excel File looks a bit corrupted
![image](https://user-images.githubusercontent.com/13365687/45666489-f857a180-bb15-11e8-8199-4a0b653d9cd5.png)

![image](https://user-images.githubusercontent.com/13365687/45666517-16250680-bb16-11e8-859a-f1b953b84c1d.png)

Can you please check?

**Comment by cristinamghita** [comment]
@metas-mk ,  broke the file when cleaned.
![image](https://user-images.githubusercontent.com/15378036/45669799-c819fe00-bb29-11e8-8ef4-b443b40f577f.png)

**Comment by cristinamghita** [comment]
Follow up in https://github.com/metasfresh/metasfresh/issues/4648

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. Excel export running in Swing as well: OK
2. export results the same from Swing and Excel:
* numbers in Swing were missing decimal dot, e.g. net weight: NOK

WebUI:
![2018-10-24 12_03_32-productspecificationd_20181024 csv - libreoffice calc](https://user-images.githubusercontent.com/18696715/47423429-43a04800-d785-11e8-98cc-128e3fd149c9.png)

Swing:
![2018-10-24 12_03_59-decloudit001](https://user-images.githubusercontent.com/18696715/47423447-4e5add00-d785-11e8-8e47-cf4fef3acae9.png)

* Fields were all the same size, therefore names were often cut off in Swing export: NOK imho
![2018-10-24 12_08_36-decloudit001](https://user-images.githubusercontent.com/18696715/47423570-a5f94880-d785-11e8-9c06-52fed7a11491.png)

**Comment by cristinamghita** [comment]
## Dev test
### Swing test
* Run process "Export product specificatins" from product window
    * And the result is:
![image](https://user-images.githubusercontent.com/15378036/48617692-d193db00-e99f-11e8-8a8d-2ba05d48eaf4.png)

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

1. Excel export running in Swing as well: OK
2. export results the same from Swing and Excel: 
* numbers in Swing not missing decimal dot anymore: OK
* field size is adapted to length of value, no more cut offs in Swing export: OK
