### ISSUE TITLE
Allow custom PDF-creating code to be called via print-format

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4587]
### Is this a bug or feature request?
FR

### What is the current behavior?
A process that is callable via AD_Printformat basically needs to be an "old school Compiere" report, or a "jasper" report.
What's not working is to invoke some other code that returns a `byte[]` containing the report's PDF data

### Documentation

The first example that makes use of this feature is the process `C_DunningDoc_JasperWithInvoicePDFs`.
You can select it in an `AD_Printformat` that then used that printformat like and other.
E.g. in `C_DocType` or `C_DocOutBound_Config`

-------------------------------

Note, the standard process for jasper reports has changed to be `de.metas.report.jasper.client.process.JasperReportStarter`

You don't need to remember, though;  Tehre is a callout for `AD_Process` that inserts this ClassName "IsProcess" is checked and "ClassName" is still empty:
![image](https://user-images.githubusercontent.com/1264789/45533981-d00c3200-b7f9-11e8-8516-8dcd23ea8c66.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested again the new process `C_DunningDoc_JasperWithInvoicePDFs`:

* new process available in DocOutbound Config: **OK**
* process working fine, in dunning: dunning doc and resp. invoice: **OK**
* dunning doc and sales invoice are displayed in Doc Outbound: **OK**
* printing queue: 
   * entry for the sales invoice: OK, PDF: **OK**
   * entry for the dunning doc: OK, PDF: includes the sales invoice as well: **OK**

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4587 to `release`
