### ISSUE TITLE
Number Format Exception

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4592]
Material Receipt Candidates. Select line. Foto Action. Make Foto from Webcam.
--> Number Format Exception.

![image](https://user-images.githubusercontent.com/13365687/45538269-dfde4300-b806-11e8-9cc1-7accd5423a70.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no number format exception when making photo in material receipt cands, from webcam: OK
* no exception or error when uploading a photo: OK
* taking out the photo again also working fine: OK

(=> when taking out the photo i got an error msg "Mandatory field AD_Image_ID not filled" and the red line in header, which i think is OK, but when i closed the overlay with Escape, the red line remained in the window: => https://github.com/metasfresh/metasfresh-webui-frontend/issues/1950)
