### ISSUE TITLE
WebUI: Outbound EMail Server (SMTP)

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4594]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window "Outbound email server" is missing in webui.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create the window.

Table AD_MailBox
Outbound EMail Server (SMTP)
AD_Window_ID=540080

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window Outbound EMail Server (SMTP) in WebUI: OK
* Table AD_MailBox: OK
* AD_Window_ID=540080: OK
