### ISSUE TITLE
WebUI: Window EMail Server Routing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4595]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the window "EMail Server Routing" is missing in webui.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create the window.

Table AD_MailConfig
Fenster "EMail Server Routing" 
AD_Window_ID=540078

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new window EMail Server Routing in WebUI: OK
* Table AD_MailConfig: OK
* AD_Window_ID=540078: OK
* all trls included in de_DE / en_US: OK
