### ISSUE TITLE
Implementation Handling Unit Editor for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#461]
Implementation Handling Unit Editor for WebUI

WebUI for Handling Unit POS and Handling Unit Editor:
- Initial Selection is warehouse (before the user gets into the HU Editor Page)
- After that the can see all HU in that warehouse (as list) with Qty LU, Product, Packing Instruction and Qty TU. If different Attribute Combinations then mark the line and have the possibility to expand and see the qties for different HU Attribute Combinations
- Possibility to sort and filter the list
- HU Combination List shall be shown like this

Palette 1
- Tomatoes 10 M/A x 5 kg
- Salad packed 10 M/A x 6 pce
- Cucumber 10 IFCO 6413 x 12 pce
  - Cucumber 5 IFCO 6413 x 12 pce ES
  - Cucumber 5 IFCO 6413 x 12 pce BIO, CH

Palette 2 Tomatoes 500g 40 IFCO 6413 x 10 pce

(more details to come about selection, split, merge, move, pick, transport, print, label, inventory, garbage, send back to vendor ...)

**Comment by teosarca** [comment]
closing it because it was integrated long time ago
