### ISSUE TITLE
Requests can not be saved II

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4622]
follow up to #4520

### Is this a bug or feature request?
bug

### What is the current behavior?
still a problem

#### Which are the steps to reproduce?
1. open window 540354
1. open any partner
1. click new to create a new request
1. save
1. NOK: request is saved but without reference to the partner

other case:
1. open user
1. create a new token

in sum there are ~70 cases where this might be a problem
```
SELECT

  w.name as window_name,
  t.name as tab_name,
  f.name as field_name,
  tab.tablename,
  c.columnname,
  isparent,
  columnsql

FROM ad_window w
  JOIN ad_tab t ON t.ad_window_id = w.ad_window_id
  JOIN ad_field f ON f.ad_tab_id = t.ad_tab_id
  JOIN ad_table tab on tab.ad_table_id = t.ad_table_id
  JOIN ad_column c on f.ad_column_id = c.ad_column_id
WHERE true --w.name = 'Projekt so101'
  and t.ad_column_id = c.ad_column_id
  and isparent='N' and t.ad_column_id = c.ad_column_id
  and t.isreadonly ='N' and isinsertrecord = 'Y'
ORDER BY w.name
```

**Comment by metasnw** [comment]
@metas-mk suggests to set the parent link column for all 60+ cases and set it in future for new linked tabs manually

**Comment by metas-ts** [comment]
imho it's worthwhile spending 1-2hrs debugging the issue. i hope it's actually a small one.
@teosarca wdyt?

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4622 into `release`

**Comment by metas-dh** [comment]
checked with metas-nw: working fine on live, closing.
