### ISSUE TITLE
invoice candidate recompute flag not always removed in webui

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4623]
### Is this a bug or feature request?
Bug
### What is the current behavior?
if an invoice candidate is validated by the app server, but the validation does not cause any change in the IC, then the webui is not notified to remove the "zu Akt." flag, so the IC stays like this:
![image](https://user-images.githubusercontent.com/1264789/45881392-4fc26f80-bdab-11e8-8417-911504b21bb1.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested together with #4624: 
Recompute flag was correctly removed, ICs could be invoiced without problems: OK
