### ISSUE TITLE
invoice candidate not updated after shipment reactivate and complete

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4624]
### Is this a bug or feature request?
Bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* ICs are updated correctly after shipment is reactivated and completed again: OK
* invoice for the ICs is created correctly: OK
* ICs are still updated correctly after invoice reversal: OK
* invoice for the ICs is created correctly again after reversing: OK
