### ISSUE TITLE
Open Items List Reference Date wrong parm

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4625]
### Is this a bug or feature request?
Bug
### What is the expected or desired behavior?
Report should work and take the  given date

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. had different sales invoices with different dates, ran Open Items Report:
* report with reference date today: all invoices included with date today or in the past: **OK**
* report with reference date 2 days ago: report empty: **OK**
* report with reference date 2 days from now: all invoices included with date until that day: **OK**
* invoices summed up correctly, other data (bpartner, invoice no., Skonto, payment term etc.) correct: **OK**
2. reversed one of the invoices, ran Open Items Report again:
* reversed invoice was not included anymore: **OK**
* remaining invoices included correctly according to reference date: **OK**
