### ISSUE TITLE
Generic Process for SQL -> Excel Export

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4633]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to create a quick Excel Export via SQL in metasfresh WebUI.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create the possibility to have a generic process type that allows to attach a SQL and choose the export type "excel". This SQL delivers the resultset. The Process parses the resultset and does the needed translations. The column types (number, integer, text, date ...) shall be configurable. The process can take parms and these can be used in SQL as placeholder.
Such processes can be defined in ad_process. These can be set in ad_menu or in windows via assigned processes. When user starts such a process then the parm modal overlay is shown. The excel export is provided via browser download as usual.

### Configuration / Sample process
Highlights:
* Type: Excel
* Classname (will be automatically set and made readonly): de.metas.impexp.excel.process.ExportToExcelProcess
* Your select, e.g.
```sql
select 
@C_Order_ID/-1@ as C_Order_ID
, @AD_User_ID/-1@ as AD_User_ID
, @C_BP_Group_ID/-1@ as C_BP_Group_ID
, bp.* 
from C_BPartner bp
```

The context variables used in SQL will be resolved in following order:
* process parameter
* current selected record's field
* global context

![image](https://user-images.githubusercontent.com/1244701/46567456-d181d380-c93b-11e8-82b4-abe2b11f57f5.png)

![image](https://user-images.githubusercontent.com/1244701/46567460-dfcfef80-c93b-11e8-889a-918242ac23bc.png)

![image](https://user-images.githubusercontent.com/1244701/46567510-be233800-c93c-11e8-9fde-441fcf688332.png)

![image](https://user-images.githubusercontent.com/1244701/46567520-d7c47f80-c93c-11e8-9b7c-2e38c435d963.png)

![image](https://user-images.githubusercontent.com/1244701/46567529-e743c880-c93c-11e8-9ebf-28483ddea93c.png)

![image](https://user-images.githubusercontent.com/1244701/46567534-04789700-c93d-11e8-8386-29a0a214a25d.png)

![image](https://user-images.githubusercontent.com/1244701/46567536-1ce8b180-c93d-11e8-88c8-ea8ed998a7aa.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15cloudit webui  

* OK The process works if created as in the documentation above. 
* OK The excel is created correctly

* OK : also works if process appears directly in the menu

**Comment by metasnw** [comment]
http://docs.metasfresh.org/appdictionary_collection/EN/configure_sql_process.html
