### ISSUE TITLE
Option to remove M_Product_Category_ID from Material Cockpit

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4640]
### Is this a bug or feature request?
*FR
### What is the current behavior?
* Now the M_Product_Category_ID column is always displayed in the Material Cockpit.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
*Add a sys config de.metas.ui.web.material.cockpit.field.M_Product_Category_ID.IsDisplayed and change the code to display this column accordingly

**Comment by metas-rc** [comment]
Notes for IT:
* The sys config is called de.metas.ui.web.material.cockpit.field.M_Product_Category_ID.IsDisplayed
* If the sys config's value is 'N', the column shall not be displayed in the Material Cockpit
* If it's on 'Y' it shall be displayed.

**Comment by metas-mk** [comment]
Quick check/ IT: Attribute Rows are still shown. Pls fix.

**Comment by metas-rc** [comment]
There was a misunderstanding first. I understood I had add a display option for the product category column in Material Cockpit. 
Actually, the task was about hiding the included rows in the Material Cockpit.
I aded an option for this via sys config. It is called de.metas.ui.web.material.cockpit.MaterialCockpitViewFactory.DisplayIncludedRows
If this sys config is on true, the included rows should be displayed. If it's on false, they should be hidden.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new sysconfig: `de.metas.ui.web.material.cockpit.MaterialCockpitViewFactory.DisplayIncludedRows`: OK
* when config is set `Y`, attribute rows are displayed: OK
* when config is set `N`, attribute rows are not displayed: OK
