### ISSUE TITLE
BPartners FTS shall not be active by default

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4649]
### Is this a bug or feature request?
FR
follow-up of:
* https://github.com/metasfresh/metasfresh/issues/4238
* https://github.com/metasfresh/metasfresh/issues/4391

#### Which are the steps to reproduce?
Test it on any BPartner lookup

### What is the expected or desired behavior?
FTS index set active shall not be default setting, pls set it inactive as default!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* checked fresh weekly test db: FTS index was not set active by default: OK
