### ISSUE TITLE
AD Element Translations leads to wrong fieldname Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4652]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when Translating an AD_Element the Field Translation is updated wrong.
#### Which are the steps to reproduce?
Try an AD_Element Translation and check the corresponding Field Translation.
### What is the expected or desired behavior?
Shall work and have the correct Field Translation.

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/commit/368ba5c1b2a71b3a79117b016a2cdf190a65bf00 to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* change the name in AD_Element_Trl: nothing changes in  AD_Field o AD_Field_Trl (for the resp. language): NOK
* change name in AD_Element: also changed accordingly in AD_Field & AD_Field_Trl: OK

to be fixed in other task

**Comment by metas-rc** [comment]
Fixed in https://github.com/metasfresh/metasfresh/issues/4664

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* change the name in AD_Element_Trl: 
    * when trying to save, the value is set back to what it was before, cannot be changed: NOK
    * when you check the AD_Element, then the name is changed there, as you tried to change the name in AD_Element_Trl: NOK

**Comment by metas-rc** [comment]
Could not reproduce locally

**Comment by metas-rc** [comment]
Could not reproduce on declouditdb (swing)

**Comment by metas-ts** [comment]
Hi @metas-rc please decide/corrdinate that to do an move the issue forward accordingly

**Comment by metas-dh** [comment]
Results of IT3
tested in mf15

1. changing AD_Element_Trl in base language:
* changes are saved and displayed correctly: OK
* AD_Element is updated correctly: OK

2. changing AD_Element_Trl in another language:
* changes are saved and displayed correctly: OK
* AD_Element stays the same: OK
