### ISSUE TITLE
WebUI: Add missing Translations for en_US in Businesspartner Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4653]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Businesspartner window misses some Translations for en_US.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Complete the missing Translations via AD_Elements.

**Main Window:**

- [x] Firma
- [x] Firmenname
- [x] Umsatzsteuer-ID
- [x] Anbauplanung
- [x] Erhält EDI-Belege
- [x] Autom. Referenz-Wert in Auftrag
- [ ] Pharmaproductpermlaw52
- [ ] Pharmacie Permission

**Customer Tab:**

- [x] Preissystem
- [x] Aggregationsregel für Ausgangsrechungen
- [x] Aggregationsregel für Ausgangsrechungen (Rechnungsposition)
- [x] Sammel-Lieferscheine erlaubt
- [x] ADR Kunde
- [x] keine Bestellkontrolle
- [x] Gebinde auf Lsch. ausblenden
- [x] Kundengruppe

**Vendor Tab:**

- [x] Lieferung
- [x] Einkaufspreissystem
- [x] Anbauplanung
- [x] Flag Urproduzent
- [x] Aggregationsregel für Eingangsrechungen
- [x] Aggregationsregel für Eingangsrechungen (Rechnungspositiion)

**Manufacturer Tab:**

- [x] Aktiv

**Location Tab:**

- [x] Adresse
- [x] Liefer Standard Adresse
- [x] Rechnung Standard Adresse
- [x] Replikations-Standardwert

**Contact Tab:**

- [x] Standard-Ansprechpartner
- [x] Weihnachtsgeschenk
- [ ] Newsletter (move to Flags)

**Bank Account Tab:**

- [x] ESR Konto
- [x] ESR Teilnehmernummer
- [x] ESR Receiver

**Product Tab:**

- [x] Produkt

**Produkt Tab:**

- [x] Sektion
- [x] Hersteller
- [x] Aktiv
- [x] Beschreibung
- [x] Mandant
- [x] Rearrange Fields to meet Layout Guidelines

**Marketing-Einverständnis Tab:**

- [x] Mandant
- [x] Sektion
- [x] Aktiv
- [x] Ansprechpartner
- [x] MKT_ContactPerson
- [x] Marketing Platform GatewayId
- [x] Einverständnis erklärt am
- [x] Einverständnis widerrufen am
- [x] Beschreibung

**Comment by metas-dh** [comment]
Results of IT1
tested in release:

1. main window:
Receipient: shall be Recipient

2. customer tab:
trl still missing (not mentioned above): Statistik Gruppe: NOK

3. vendor tab:
* no trl: Anbauplanung: NOK
* trl still missing (not mentioned above):  ADR Lieferant: NOK

4. product manufacturer tab:
* Beschreibung field is missing: NOK
* Layout: organisation is 1st, client is last: NOK
