### ISSUE TITLE
Configurable Mailtext for Documents in DocOutbound

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4659]
### Is this a bug or feature request?
FR
### What is the current behavior?
There are two AD_Messages:
* `MailWorkpackageProcessor.EmailSubject`
* `MailWorkpackageProcessor.EmailMessage`

whatever the contained is used for every outgoing mail

#### Doc-OutBoundLog

* If the `C_Doc_OutBoundLog` has a `C_DocType` and if that `C_Doctype` has an `AD_BoilerPlate`,
then use that boilerplate's subject and textsnippet
  * Note: variables and sub-boilerplates are not in this issue's scope, they won't work in here
* otherwise, fall back to the two AD_Messages from above
* for both AD_Messages and Boilerplate, if there are any translations for the required language, they shall be used.
  * the required language is determined by checking the following places and using the first one that has a language
    * If `C_Doc_OutBoundLog.CurrentEMailRecipient_ID > 0`, then look for the language of that user
    * If `C_Doc_OutBoundLog.C_BPArtner_ID > 0`  then look for the language of that bpartner
    * If `C_Doc_OutBoundLog.CurrentEMailRecipient_ID > 0`, but the respective user has no language set, then look for that user's bPartner's language
    * Look for the current context-language (e.g. the language of the metasfresh user that created the WP)
    * If all fails, return the base language

#### Marketing

Marketing uses boilerplate, so since we make that boilerplate language-aware, I thought that marketing-contacts also need to be language aware now (to reduce inconsistencies)

*  `MKTG_ContactPerson` now has a non-manadatory language field
* when a new `MKTG_ContactPerson` is created from `AD_User` it gets the user's language.
   * if the user has no language, but the user's bpartner has, it gets the bpartner's language
* if the contact's language is saved, then the for that language, the same rules apply that are described here: https://github.com/metasfresh/metasfresh/issues/4092

**Comment by metas-ts** [comment]
Notes to IT: 
* we have some unit test coverage when it comes to synching language and email between AD_USer and MKTG_ContactPerson, so imho that doesn need (vigorous) testing
* please test the marketing-letter feature with a translated boilerplate
* also, please test the mail-from-docoutbound-feature, with a translated boilerplate to be set in the respective doctype
* i did very little dev-testing. my excluse: i wanted to use cypress, but then thought that it's more important to create this issue to enable future testing: https://github.com/metasfresh/metasfresh-webui-frontend/issues/2002

**Comment by metas-dh** [comment]
tested in release

1. set AD_User language per pgAdmin, could not find language in Swing or WebUI, neither in contact tab for bpartner nor in window User
2. set AD_Boilerplate_Trl per pgAdmin, could not find it in Swing or WebUI
3. MKTG_ContactPerson was created with the same language as set in AD_User: OK
4. Sending emails with the correct language:
    * when AD_Boilerplate was set for the resp. C_Doctype, than this was set as Email text: OK
    * AD_Boilerplate for the correct language is selected: OK
    * when no AD_Boilerplate was set for the resp. C_Doctype, then the Email shows subject / content from AD_Messages: OK
    * AD_Messages for the correct language are selected: OK
5. Create Serial Letter: also did not work in release, acc. to Async no errors etc.

**Comment by metas-dh** [comment]
checked again in release:
* new field for ad_language in ad_user: OK, but cannot be set empty => could not test fallback to bpartner language / menu language: checked with metas-ts: will leave it like that for now
* Serial letter: C_Letters were created, but no entries in printing queue / archive: to be checked in #4813

=> since the main issue of this task (using the correct language / text in email / serial letter) is working fine, i'm closing it.
