### ISSUE TITLE
Add base language to AD_Element Translation Tables

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4663]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the base language is maintained in Application Dictionary Header Tables. The Translations are maintained in corresponding _trl tables.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add the base language to the AD_Element_trl Table. The Name, Description, Translated Field in AD_Element shall be readonly (not for New entries), like in AD_Field and the update shall be done via Function triggered by update in AD_Element_Trl.

**Comment by metas-rc** [comment]
# Testing

* Log in as sys admin in swing

1. AD_Element changes
* Go to the window Element, press new
* Set name, description, help, po column, webui columns and commit warning. 
* Save the entry
* => All of the above should become readonly. 
* Go to the translations tab
* => There should be a translation for the base language ( by default it is de_DE in our case)
* => The entries for the other system languages shall be also generated
* Go to the base language (DE)  translation and modify something (e.g. the name) 
* Go back to the main tab
* => The name of the element should now be changed to the one you set in the base translation
* Go to Window Management and press new
* Set the element above as system element
* Save
* => The window should have received all the details from the element ( see #4662)
* Go back to the element translation, base language (DE)
* Change something again
( TOBE CONTINUED)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

from DevTest:
> Go back to the element translation, base language (DE)
> Change something again
> => The change should be propagated to the element as well as to the window

see IT of #4652:
* change in AD_Element_Trl is not saved, remains the same (as it is displayed): NOK
* the AD_Element has its name changed though, but after change in **every** language in AD_Element_Trl, not just the base language: NOK

from DevTest:

> Go to element translation and change a value for a language
> => The window translation shall update too
> The same shall happen in menu and Tab

* window translation stayed the same, only AD_Element gets changed from change in AD_Element_Trl (which is not displayed): NOK

**Comment by metas-rc** [comment]
Could not reproduce ( tested locally and on declouditdb, swing version)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. changing AD_Element_Trl in base language:
* AD_Element is updated correctly: OK
* AD_Window is updated correctly: the name is updated correctly, but System Element stays the same? although the AD_Element itself was updated?
* AD_Menu works the same as AD_Window, the System Element remains the same as it was when set, only name is updated
* AD_Tab: System Element and Name are changed again when setting DB-Tabelle, they are taken from there: is that OK??
2. changing AD_Element_Trl in another language:
* AD_Element stays the same: OK
* AD_Window_Trl for the resp. language is updated correctly: OK
* AD_Menu works the same as AD_Window: OK
* AD_Tab: REgister & Name are taken from DB-Tabelle when this is set, change in AD_Element_Trl has no effect
