### ISSUE TITLE
WebUI Picking does not return filtered HU for selection

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4671]
### Is this a bug or feature request?
bug

### What is the current behavior?
Picking Terminal -> HUs to Pick shows nothing

### What is the expected or desired behavior?
shall work :)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Picking Terminal (old version):
* HU Editor opens with HU selection to pick from: OK
* HU selection matches the filters (e.g. attributes, Barcode): OK
