### ISSUE TITLE
Enable zoom to doc outbound log

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4676]
### Is this a bug or feature request?
FR

### What is the current behavior?
E.g. you can't zoom from a C_Invoice to its respective C_Doc_Outbound_Log / "Ausgehende Belege"

### What is the expected or desired behavior?
This is what we want:
![image](https://user-images.githubusercontent.com/1264789/47198167-0c87fc00-d36b-11e8-816c-c43953db66a2.png)

..as seen from the document that is referenced by a C_Doc_Outbound_Log record;
No matter whether it's and invoice, dunning or something else.

Note to IT: imho no need to test a lot of different documents..if if e.g. works for dunning, it should also work for invoice

**Comment by metas-dh** [comment]
Results of IT1
tested in release

zoom to doc outbound log: worked fine for e.g. sales & purchase invoice, dunning doc: OK
