### ISSUE TITLE
Deactivate legacy "Order overview (internal)" window

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4678]
### Is this a bug or feature request?
FR

### What is the current behavior?

if you have the rights to see it, this not-working window gets in your way; mostly by taking a lot of time when computing zoom-to target.

this issue is about at least deactivating it

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* "Order overview (internal)" window is inactive: OK
* does not show up in related documents anymore: OK
