### ISSUE TITLE
Solve print info UI performance problem

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4679]
### Is this a bug or feature request?
Bug

### What is the current behavior?

There are two print info tags; one in "Printing queue" / "Druck Warteschlange", one in "Order Control" / "Bestellkontrolle"

both have "Table" and "Table Direct" reference types which doesn't for for larger tables.
I didn't try it in the webui-UI but on swing, it takes ages if you have a big database.

### What is the expected or desired behavior?

The respective printing queu tabs should be fairly responsive

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db (with big db)

print info tab opens directly after selection:
* Printing queue, Swing: OK
* Printing queue, WebUI: OK
* Order Control, Swing: OK
* Order Control, WebUI: OK

(in printing queue, Swing, the Info tab was always empty, even when there was data displayed in WebUI => could not reproduce in current master, worked fine in mf15)
