### ISSUE TITLE
Shipment Schedule does not set QtyToDeliver properly

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4683]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
new behaviors as of this task:

1. if a product is not stocked or not an item, don't care for the stocked qty; deliver everything
   before this issue, *nothing* was delivered in that case;

2. shipmentschedule qtyOnhand now shows the (current) stocked qty, i.e. MD_Stock.
  before this issue, it tried to show the respective ATP

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. product is not stocked or not an item, don't care for the stocked qty; deliver everything:
* qty Stock: 0
* QtytoDeliver: as ordered, full qty: OK

2. shipmentschedule qtyOnhand now shows the (current) stocked qty, i.e. MD_Stock
* qty Stock: as in MD_Stock: OK
* in case of shipment schedule with higher prio (e.g. earlier DatePromised): qty Stock shows qty from MD_Stock - QtytoDeliver of shipment schedule with higher prio: OK
* QtytoDeliver: as QtyOrdered, in case of partial shipment: QtyOrdered - QtyDelivered: OK
