### ISSUE TITLE
Picking Terminal v2: filtering options

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4690]
### Is this a bug or feature request?
FR
follow-up of https://github.com/metasfresh/metasfresh/issues/4577

### What is the expected or desired behavior?
Filter by:
* order
* customer/BP
* warehouse type
* delivery date
* preparation date

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* filter options available: OK
* filter working correctly: shipment date & date ready filter not working, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/2039#issuecomment-434744164
(other filter params working fine)

**Comment by teosarca** [comment]
@metas-dh if only the https://github.com/metasfresh/metasfresh-webui-frontend/issues/2039#issuecomment-434744164 is pending, i think we can close this task.
