### ISSUE TITLE
RabbitMQ: we shall use guest user by default

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4692]
### Is this a bug or feature request?
bugfix

### What is the expected or desired behavior?
guest user shall be used and not metasfresh

### Note to IT
nothing to test.
Rolling out the server and seeing that rabbitMQ connection is working is enough.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

rolled out, checked the connection: no errors regarding rabbitMQ, working fine: OK
