### ISSUE TITLE
Validate ReadonlyLogic, MandatoryLogic and DisplayLogic

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4693]
### Is this a bug or feature request?
FR

### What is the current behavior?
developer can write anything in AD_Column.ReadonyLogic, AD_Column.MandatoryLogic, AD_Field.DisplayLogic

### What is the expected or desired behavior?
Those fields shall be validated if that it's a valid expression or not.

**Comment by metas-rc** [comment]
Results of IT

1) Readonly logic: 

* OK: Correct string

![image](https://user-images.githubusercontent.com/16001442/48486513-6b367d80-e824-11e8-914f-cfa30b272b52.png)



* OK: wrong strings: 

![image](https://user-images.githubusercontent.com/16001442/48486307-cfa50d00-e823-11e8-81a4-dfb4254527a7.png)


![image](https://user-images.githubusercontent.com/16001442/48486427-29a5d280-e824-11e8-87db-1421f0766329.png)


![image](https://user-images.githubusercontent.com/16001442/48486573-97ea9500-e824-11e8-9785-1dccb50a042d.png)

2) Mandatory Logic
*  OK : Same results 

3) Display Logic

* OK: Correct strings: 

![image](https://user-images.githubusercontent.com/16001442/48487547-3677f580-e827-11e8-8cf1-8eac99f31f4e.png)

![image](https://user-images.githubusercontent.com/16001442/48487584-56a7b480-e827-11e8-92ba-2a3e49037988.png)


![image](https://user-images.githubusercontent.com/16001442/48487615-6cb57500-e827-11e8-9b28-97a895ec6d45.png)

![image](https://user-images.githubusercontent.com/16001442/48487710-a5554e80-e827-11e8-831e-6cbff2233d93.png)


* OK: Wrong strings

![image](https://user-images.githubusercontent.com/16001442/48487479-0cbece80-e827-11e8-9da4-ebb2c681fab9.png)


![image](https://user-images.githubusercontent.com/16001442/48487566-48f22f00-e827-11e8-890e-a6cfdaf08467.png)


![image](https://user-images.githubusercontent.com/16001442/48487664-8bb40700-e827-11e8-9b15-54932c270866.png)


![image](https://user-images.githubusercontent.com/16001442/48487697-9a9ab980-e827-11e8-9e34-abb31ad93db9.png)
