### ISSUE TITLE
Follow up #4552 AD_User is wrong in shipment schedule when using isDropShip 

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4696]
### Is this a bug or feature request?
Bug

**Comment by cristinamghita** [comment]
See https://github.com/metasfresh/metasfresh/issues/4552

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated the testcases above: 

**DropShip on Y**
=> after changing the drop ship contact: the new contact did not appear in deliveryaddress in sales order report, it was either empty or still the old contact: NOK

![2018-10-24 13_27_26-metasfresh](https://user-images.githubusercontent.com/18696715/47571900-f4e7df00-d939-11e8-812a-74d1ae1fd17a.png)

![2018-10-24 13_27_35-143_0010 pdf](https://user-images.githubusercontent.com/18696715/47571908-f9ac9300-d939-11e8-8902-fb017dd1ef9c.png)

![2018-10-24 13_27_49-metasfresh](https://user-images.githubusercontent.com/18696715/47571923-04ffbe80-d93a-11e8-90c5-9e3e6f0b50fc.png)

![2018-10-24 13_28_03-143_0008 pdf](https://user-images.githubusercontent.com/18696715/47571934-09c47280-d93a-11e8-83d0-8320e31b3ffa.png)

the new contact did appear in shipment schedule, though: OK


**DropShip on N**
worked fine.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

repeated the testcases above:
*  after changing the drop ship contact: the new contact did correctly appear in deliveryaddress in sales order report: OK
*  new contact does appear in shipment schedule (for both DropShip on Y/N): OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4696 to `release`
