### ISSUE TITLE
Add possibility to have product description as predefined

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4698]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
* Create possibility to have predefined product description and that to be used in sales order line
* shall be list reference
* per product/ bpartner (not mandatory)
* shall be autom. set when product is uised in sales order

**Comment by cristinamghita** [comment]
## Concept
*  Create table M_ProductDescription with fields M_Product_ID, C_BPartner_ID, Name
  * bp can be null
  * product mandatory
  * Unique key per product and bp, but bp can be null
* Add column M_ProductDescription_ID in C_OrderLine
* If exists a matching record in this table, then that value shall be set in C_OrderLine
  * ProductDescription field will be completed with the value from the record M_ProductDescription

**Comment by metas-rc** [comment]
Note to IT: 
I noticed this and I remembered we have this other task pending for a long time: https://github.com/metasfresh/metasfresh/issues/786

I think the old task becomes obsolete now, with the new table solution. Please, check and close the old task if I am right.

**Comment by cristinamghita** [comment]
The FR is not needed. The specification were understood wrong.
