### ISSUE TITLE
Allow appending additional PDF-attachments to invoice-PDF

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4700]
### Is this a bug or feature request?
FR
### What is the current behavior?

Invoice-PDFs are normal jasper reports.

### What is the expected or desired behavior?

When attaching a PDF via REST-Endpoint, the uploader shall be able to specify that the respective PDF be contatenated to the invoice-PDF when that PDF is generated.
* for this, the uploader can tag the new attachment with `Concatenate_Pdf_to_InvoicePdf=true`

**Comment by metas-ts** [comment]
### How I dev-tested

* took an existing invoice
* attached some PDF to it via webui drag&drop.
  * In my case, the PDFs filename was `docker_cheatsheet_r4v2.pdf`
* tagged the attachment: update AD_AttachmentEntry set tags='Concatenate_Pdf_to_InvoicePdf=Y' where filename='docker_cheatsheet_r4v2.pdf'
* Hit the invoice with `Alt+p`
* Voila:
![image](https://user-images.githubusercontent.com/1264789/47554765-5ee89000-d90a-11e8-841b-9ddc715e380f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* appending an additional PDF-attachment to my invoice-PDF: worked fine, used update in db as in devtest: OK
* will test again using attaching a PDF via REST-Endpoint  when testing #4621
