### ISSUE TITLE
Swing Picking Terminal: cannot write upper/lower case passwords when logging to Swing Picking Terminal

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4704]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
try to login with a password which contains upper and lower case letters

### What is the expected or desired behavior?
shall be able to write any type of password.

**Comment by teosarca** [comment]
solution: don't show the soft keyboard when user is typing the password,
because when the soft keyboard is displayed, pressing "SHIFT" key to get the capital/lower case letter does not matter.

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

logging in Swing Picking Terminal, with PW containing upper and lower case:
* using hardware keyboard: OK
* using soft keyboard: OK
* using copy+paste: OK
