### ISSUE TITLE
webui: Change my password does not work

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4708]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?

1. create a new user via user window
1. open process "change password" in same window
1. set password `demo1234`
1. OK: works
1. open process "change password" again
  1. set old password: `demo1234`
  1.  set new password `demo12345`
  1.  set new password (retype) `demo12345`
1. NOK: error message: old password do not match
1. log on as that new user
1. open user profile
1. start process "change MY password" 
  1. set old password: `demo1234`
  1.  set new password `demo12345`
  1.  set new password (retype) `demo12345`
1. NOK: error message: old password do not match

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh/issues/4708 to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* tried with a new user (changed PW sev. times): worked fine, OK
* tried with old user IT: did not work, "old password do not match" when i tried to change the PW the 2nd time (old PW was working fine though when logging in): NOK

**Comment by metas-dh** [comment]
tested once more as part of e2e, worked fine (probably mixed up users & PWs last time): OK
