### ISSUE TITLE
Picking from Handling Unit Editor (WebUI)

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#472]
Picking from Handling Unit Editor (WebUI)
- Possibility to do the picking for a selected/ scanned HU directly in Handling Unit Editor.
- Was the Handling Unity already tied to a Business Partner and Sales order via Manufacturing order, then show this Partner, order, Product, Qty initially. The User just has to confirm.
- Was the HU created through a demand Manufacturing Order but was tied to a Business Partner, then show the sales Order details from promised date = current date initially filtered by Business Partner. User selects a sales Order row and joins the HU to Sales Order with this.
- Possibility to completely overwrite the initial Business Partner.
  --> aim here ist to be able to pick the products early in the process without having to go through picking terminal again.

**Comment by metas-ts** [comment]
if the current location of the HU is e.g. "production warehouse" and the shipment schedule's warehouse is "shipping warehouse", and we pick the HU, then we need to create a distribution order, right?

**Comment by teosarca** [comment]
update:
We need an action which picks an HU. It takes the shipment schedule and picking slot as params.
It shall work from Manufacturing Issue/Receipt and also from regular HUs window.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. picking HU, from material receipt:
* sales order for bpartner A, product X
* sales order for bpartner B, product X
* purchase order & material receipt of product X
* picking in HU Editor: all shipment schedules of all existing sales orders can be selected, all picking slots: OK

2. picking HU, from manual production:
* sales order for bpartner A, product X
* sales order for bpartner B, product X
* manual manufacturing order, for bpartner A
* picking in HU Editor:  all shipment schedules of all existing sales orders can be selected, all picking slots: OK? why is the SO for bpartner B also selectable?

3. picking HU, from production after forecast:
* sales order for bpartner A, product X
* sales order for bpartner B, product X
* forecast for product X, for bpartner B => manufacturing order for bpartner B
* picking in HU Editor:  all shipment schedules of all existing sales orders can be selected, all picking slots: OK? why is the SO for bpartner A also selectable?

**Comment by metas-dh** [comment]
follow-ups:
Picking from HU Editor does not consider bpartner in PP_Order #2827
BPartner from forecast not set in PP_Order #2829
Info about bpartner of HU in HU Editor #2828
