### ISSUE TITLE
Shipper transportation identifier shall contain documentNo, date and the shipper name

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4734]
### Is this a bug or feature request?
Follow-up of https://github.com/metasfresh/metasfresh/issues/4577

**Comment by teosarca** [comment]
implemented, now looks like this:

![image](https://user-images.githubusercontent.com/1244701/47982912-29962c00-e0da-11e8-99af-692a3fb9ff1d.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Shipper transportation identifier contains documentNo, date and the shipper name: OK
* selecting shipper transportation: shipment created, package created etc., shipper transportation updated correctly: OK
