### ISSUE TITLE
Fix attribute value lookup for webui

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4737]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?

**Important:** we can drop the "swingui" requirement; just needs to work with webui

**Comment by metas-ts** [comment]
# Dev-Tested the following

## Material Tracking

* created material tracking
  * related: added [material_tracking_spec.js](https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/cypress/integration/material_tracking_spec.js) cypress test to create material trackings (but without contract - not needed here)
* created purchase order with line for the MT's product and bpartner
  * OK: the material tracking was selectable
  * OK unrelated MTs were not selectable
* created material receipt with the "suggested packaging config", i.e. 
![image](https://user-images.githubusercontent.com/1264789/48415081-b4b39980-e74c-11e8-9c9a-c3fdbced0231.png)
   * OK: selected MT is in the HU's attributes
   * OK: received HUs shows up in the material tracking's HU-tab
   * OK: the created M_InoutLines reference the MT (checked in pgAdmin)

# Subproducer

* created a BPartner relation between Test Lieferant und Test Kunde:
![image](https://user-images.githubusercontent.com/1264789/48415448-b336a100-e74d-11e8-83cf-1fbc1f36b65d.png)
* created a purchase order for "Test Lieferant"
  * OK: in material receipt, i could select "Test Kunde" as subproducer in the HU
  * OK: in the new material receipt line, "Test Kunde" was set as subproducer

**Comment by metas-ts** [comment]
@teosarca thx!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Material Tracking 
* purchase order with line for the MT's product and bpartner: 
     * material tracking is selectable: OK
     * only the material tracking for this bpartner and this product available for selection: OK
* material receipt for the orderline:
     * resp. MT is set in the attributes of each HU: OK
     * MT shows the material receipt in related data tab: OK
     * MT shows the resp. HU from receipt in the HU tab: OK
     * the HUs in the HU tab are marked as destroyed when receipt is reversed: OK, but: i got 2 lines for 1 destroyed HU in material tracking, why?
     * MT does not show the material receipt that was destroyed anymore in related data tab: OK
     * pdAdmin: M_InOutLines reference the MT: OK

2. Subproducer:
* HU in material receipt: Subproducer can be set in attributes: OK
* Subproducer is displayed in the material receipt (for the resp. product in receipt line) and in the resp. HU: OK

3. Repack No.
* if Repack-required = Y is set in attributes in purchase orderline, then the material receipt cannot be created w/o Repack No.: OK
* material receipt shows "Yes/Repack No." in attributes: OK (afaiu)

4. SSCC
SSCC attribute was automatically set for all LUs in material receipt: OK

**Comment by metas-dh** [comment]
**Swing:**
Material Tracking:
* could not set PI for the product of MT: 
`M_HU_PI_Item_Product_ID=3010011: not in Lookup - set to NULL`

* could not set MT in attributes: => mandatory field Vertragsperiode not set in MT: why is that different from WebUI?
* Vertragsperiode could not be set, although C_Flatrate_Term existing for the bpartner?

**Comment by metas-ts** [comment]
Hi @metas-dh 
we don't need to make this work in swing anymore.

Can we therefore move close this issue? wdyt? 
If you agree, pls remove the IT-failed and close it.

**Comment by metas-dh** [comment]
@metas-ts if it's not needed in Swing, then it's fine with me to close, WebUI was working fine.
