### ISSUE TITLE
Fix context parse errors while using order's product batch entry

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4739]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* new sales order
* use batch entry
* start writing in product field
=> console is full of errors & warnings
* set the Qty and press ENTER => error

### What is the expected or desired behavior?
sales order batch entry:
* products searching shall work
* adding a new line shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no errors in console when entering product in batch entry: OK
* set qty TU, Enter: orderline is created correctly, w/o errors: OK
