### ISSUE TITLE
Process C_Order_VoidWithRelatedDocsAndRecreate hangs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4741]
### Is this a bug or feature request?
Bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / customer db

1. process runs normally (~3sec. in mf15), no hang ups: OK
2. order is reversed, order no. no is S-xxxx: OK
3. related docs are reversed as well: 
* invoice is reversed: OK
* add. invoice created with neg. qty: OK
* shipment is reversed: OK
* add. shipment created with neg. qty: OK

=> worked correctly on customer db as well, acc. to metas-ts.
