### ISSUE TITLE
Attachment-Download from BPartner B2C window broken

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4742]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
# Test-Doku

* go to `window/540354`  ("Geschäftspartner B2C")
* drop an attachment
* refresh
  * your attachment is now schon in the "Dokumente" tab, like here:
![image](https://user-images.githubusercontent.com/1264789/48094946-bf81a200-e213-11e8-88cd-23ee3746b548.png)
* select you attachment
* run the "Download" quickaction:
![image](https://user-images.githubusercontent.com/1264789/48095002-e213bb00-e213-11e8-87a9-d6376d876c25.png)

=> viola: the attachment is downloaded

**Comment by metas-ts** [comment]
:cherries: picked to branch `5.79_hf1`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Attachment-Download from BPartner B2C window working fine:
* PDF: new tab opens with PDF: OK
* JPEG: new tab opens with PDF: OK
* Excel file: successful download shown at the bottom:  OK
* Zip file: successful download shown at the bottom:  OK
