### ISSUE TITLE
package order line out of sync when order is reactivated and completed again

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4775]
### Is this a bug or feature request?
Bug
### What is the current behavior?

* create a purchase order (sales order should be no difference) with a packaging line
* reactivate the order
* change the order's DatePromised
* complete the order again
* **NOK** : the package order line still has the old DatePromised
 checked via 
```sql
select c_orderline_id, line, datepromised, isactive, M_HU_PI_Item_Product_id, QtyOrdered from c_orderline where c_order_id=1000024;
```

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* package line's DatePromised is updated correctly after reactivating and completing again: OK
* for both sales & purchase side: OK
