### ISSUE TITLE
MD_Stock_Reset process includes planned HUs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4779]
### Is this a bug or feature request?
Bug

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

started with QtyOnHand: 0

1. purchase order for qty: 100: QtyOnHand: 0 (qty purchased: 100, no HUs): OK
2. material receipt for qty: 30: 
* QtyOnHand: 30 (qty purchased: 70)
* qty of HUs active: 30, qty of HUs planning: 70: OK
3. sales order for qty: 20, picking qty: 10:
* QtyOnHand: 30 (qty purchased: 70, qty ordered: 20)
* qty of HUs active: 30, qty of HUs planning: 70, qty of HUs Picked: 10: OK
4. shipment for qty: 10:
* QtyOnHand: 20 (qty purchased: 70, qty ordered: 10)
* qty of HUs active: 20, qty of HUs planning: 70, qty of HUs Shipped: 10: OK
5. material receipt for qty: 10: 
* QtyOnHand: 30 (qty purchased: 60, qty ordered: 10)
* qty of HUs active: 30, qty of HUs planning: 60, qty of HUs Shipped: 10: OK

=> all qties were updated directly after the resp. action, did not have to run the reset process: OK
=> ran the process manually: qties still the same: OK
