### ISSUE TITLE
Various fixes to import processes

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4782]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
🍒 picked https://github.com/metasfresh/metasfresh/issues/4782 to `release`

**Comment by metas-ts** [comment]
🍒 picked commit https://github.com/metasfresh/metasfresh/commit/233fba6d7ca6c573b5e57cce5c88cd98994d6733 of issue https://github.com/metasfresh/metasfresh/issues/4782 to branch `release`

**Comment by metas-dh** [comment]
closing this since the me03 task was checked by metas-cg on customer db already.
