### ISSUE TITLE
C_BPartner filter for IsActive

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4789]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* No filter for IsActive
#### Which are the steps to reproduce?
* Open Business Partner window, open filters => no filter for IsActive
### What is the expected or desired behavior?
* Add filter for isActive

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* IsActive filter in bpartner: OK
* IsActive filter working correctly: OK
