### ISSUE TITLE
View docs_sales_invoice_details_compensation_subgroup: the invoice detail shall be taken from invoice

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4793]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The view is taking the line net amount and qty from the order line.
### What is the expected or desired behavior?
Shall take the invoicing details from invoice line

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

1. Created quotation / order with sev. products
2. mark orderlines and run `Multigroup lines` action: 
=> compensation group schema is applied, OK
3. set terms & conditions: contract for 3 years:
 => discount for contract is added, 5% (-47,50): OK
4. Add manual discount:
=> discount is added, 10% (-90.25): OK
5. Complete, and check the Jasper: 
=> manual discount is displayed with 10% (-90.25): OK
6. Check the ICs: IC for manual discount is 10% (-90.25): OK
7. Set the Price override for that IC to -100.00: order total is updated accordingly: OK
8. Create the sale invoice, and check the Jasper:
=> manual discount is displayed with 10% but -100.00, as set manually in IC: OK
=> overall Total is correct: OK
9. Reverse the invoice, and in IC change the Price override for the discount for contract to -50.00: order total is updated accordingly: OK
10. Create the sale invoice, and check the Jasper:
=> manual discount is displayed with 10% but -100.00, as set manually in IC: OK
=> discount for contract is displayed with 5% but -50.00: OK
=> overall Total is correct: OK
