### ISSUE TITLE
Product No. of customer also with ASI

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4795]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* There is no ASI field in C_BPartner_Product
#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?

* C_BPartner_Product must have an ASI column
* There should be no duplicate asis per product and partner

Example:
* Product P001
* Partner G001
* Attribute A1

Entry 1: C_BPartner_Product for P001 and G001 , ASI : A1 = 20
Entry 2: C_BPartner_Product for P001 and G001, ASI: null
Entry 3: C_BPartner_Product for P001 and G001, ASI: A1 = 30

* All of the above are correct

Entry 4: C_BPartner_Product for P001 and G001, ASI: A1 = 30 will not be correct because the ASI would be similar with an existing one.

* Create a validator that does now allow a new entry to be added with the same attribute value.

**Comment by metas-dh** [comment]
Results of IT2
tested in customer db

4. product no. is correctly displayed in customer reports:
a. if there is a product no. in C_BPartner_Product matching the attribute in orderline, this is displayed: OK
b. if the attribute in orderline has no specific product no. set in C_BPartner_Product, the product no. with no attribute set is displayed: OK
c. if there is no product no. set in C_BPartner_Product, then no product. no is displayed: OK
d. correctly displayed in all reports:
* order confirmation: OK
* shipment: OK
* invoice: OK
