### ISSUE TITLE
AD_RefList Description shall be shown in webui

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4798]
### Is this a bug or feature request?
FR
### What is the current behavior?
E.g. this description:
![image](https://user-images.githubusercontent.com/1264789/49089970-08e66f80-f25d-11e8-8028-fb8d0c1a783f.png)

is not shown in the webui

#### Which are the steps to reproduce?

hover over the list item:
![image](https://user-images.githubusercontent.com/1264789/49090110-5662dc80-f25d-11e8-986a-ea710f1018f9.png)

also, hover over the list item once the record is saved:
![image](https://user-images.githubusercontent.com/1264789/49090309-b5285600-f25d-11e8-80d5-20c99d629978.png)

### What is the expected or desired behavior?
There should be an overlay showing the the description.

**Comment by metas-ts** [comment]
# Dev-Notes

I believe for this is issue, we need to extend a number of places in both app and webui-api, to add a `description` property

* org.compiere.util.NamePair
* de.metas.ui.web.window.model.lookup.GenericSqlLookupDataSourceFetcher
* de.metas.ui.web.window.datatypes.LookupValue

Then, when the description is passed all the way from AD_RefList to the API-endpoint, we need to extend webui-frontend to display it.

**Comment by metas-dh** [comment]
Results of IT2
tested in dev229

value description is displayed when hovering over field:

* when creating a new flatrate term condition: description of the term condition is displayed, OK
* when hovering over field after condition is completed: OK (for both flatrate condition "Rückvergütung" and the spec. type of latrate condition, e.g. "Gestaffelte Rückvergütung")
