### ISSUE TITLE
Co-Product improvement in Manufacturing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#480]
Co-Product improvement in Manufacturing
- Allow Co-Product Manufacturing triggered by demand
- Could also be an own BOM with Main Product instead of Co-Product (and then have other Co-Products)
- should be possible as long candidates dispo is on lot-4-lot level.

**Comment by metas-ts** [comment]
* for current  MPR: introduce 2ndary BOM. For each Co-Product of the primary BOM, there is one 2ndary BOM which has that particular product as its main product. 
 * Also use "2ndary BOM" flag to avoid circles

* for new MRP: there will certainly be a solution :-)

**Comment by teosarca** [comment]
@metas-ts  no flag is needed. All by/co-products shall be handled in this new way, i.e. just don't explode them.

**Comment by teosarca** [comment]
update: avoid checking BOM cycles in case of Co-Products.
Moving the task to rollout and let's see how far we can get.

**Comment by metas-dh** [comment]
Results of IT1
tested in sp80

1. forecast for P000363, which has Co-Product P000367: 
* PP_Order for P000363: OK
* materialdispo type supply for P000363 in production warehouse: OK
* materialdispo type demand / supply for Co-Product P000367 in production warehouse:  i think this is OK?
* materialdispo type demand / supply for Co-Product P000367 in stock warehouse:  why? afaiu it will be produced as co-product together with P000363 in production warehouse?

2. forecast for P001672, which has component P000363 (which has Co-Product P000367) and variant P000367:
* PP_Order for P001672: OK
* no PP_Order for P000363: why not? => stock?
* materialdispos type demand / supply for P000363 &  P000367 in production warehouse: OK

need to check again in mf15
