### ISSUE TITLE
Price using BOM Line's attribute is not calculated correctly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4811]

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

Test data:
1. Product with BOM consisting of 
* 2 plugs, price: 0,39 each
* cable: 0,42 per meter
* BOM type: Make-To-Order
2. discount schema:
* +1,23 for BOM attribute: 5 (= cable length in m)
* +1,25 for BOM attribute: 6 (= cable length in m)

Test:
Sales order with orderlines for that product:
1. attribute: 5 => 2 plugs (2 + 0,39) + 5m cable (5 * 0,42) + discount schema for 5m cable (1,23) = 4,11: OK
2. attribute: 6 => 2 plugs (2 + 0,39) + 6m cable (6 * 0,42) + discount schema for 6m cable (1,25) = 4,55: OK
3. change the attribute qty, e.g. from 6 to 5: price and net price are updated correctly: OK, but: line amount remains the same (and Ertrag netto is incorrect): NOK => #4814
