### ISSUE TITLE
Payment allocation posting error for currency gain/loss and discount/writeoff case

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4819]

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. checked in customer db: allocation in question is posted correctly now: OK
2. tested in mf15: no posting error in allocations (regression):
a. sales invoice & payment:
* no write-off & no discount: OK
* write-off, but no discount: OK
* no write-off, but discount: OK
* write-off and discount: OK

b. sales invoice and purchase invoice: OK

c. outbound payment / inbound payment: OK
