### ISSUE TITLE
 Categorize Business Partners as "Neukunde", "Stammkunde"

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4820]
### Is this a bug or feature request?
* FR
### What is the current behavior?
-
#### Which are the steps to reproduce?
-
### What is the expected or desired behavior?

* We need to know directly if a Business Partner is a "Stammkunde" or a "Neukunde".  This information shall be stored in a way that it can be easily fetched via SQL reports and virtual columns in WebUI elements.
A Businesspartner shall be set to
* "" in case a subscription contract was never done
* "Neukunde" in case the customer has a new contract (e.g. 3 years) or has a prolonged contract that has a gap larger than 12 months between prolonged contract.
* "Stammkunde" in case the customer has a prolonged contract (e.g. another 3 years) and the prolongation contract start date is without a gap or less than 12 months after the old contract.
* Prolongations shall only happen with prolongation action in Sales Order.

**Comment by metas-dh** [comment]
Results of IT1
tested in dev217

A Businesspartner shall be set to
* "" in case a subscription contract was never done: OK
* "Neukunde" in case the customer has a new contract (e.g. 3 years) or has a prolonged contract that has a gap larger than 12 months between prolonged contract.:
      * new contract (of 1 month): update to "Neukunde": OK
      * prolonged contract that has a gap larger than 12 months between prolonged contract: to test
* "Stammkunde" in case the customer has a prolonged contract (e.g. another 3 years) and the prolongation contract start date is without a gap or less than 12 months after the old contract:
     * prolonged contract and the prolongation contract start date is without a gap: remained "Neukunde" (tried with prolongation action in Sales order and in contract itself): NOK
     * prolonged contract less than 12 months after the old contract: to test
* Prolongations shall only happen with prolongation action in Sales Order:  to test

**Comment by metas-dh** [comment]
Results of IT2
tested in customer db

A Businesspartner shall be set to
* "" in case a subscription contract was never done: OK
* "Neukunde" in case the customer has a new contract (e.g. 3 years) or has a prolonged contract that has a gap larger than 12 months between prolonged contract.:
      * new contract (of 1 month): update to "Neukunde": OK => Update was done after i changed the customer bpartner group, from not classified to e.g. Kunde A: is that OK?
      * prolonged contract that has a gap larger than 12 months between prolonged contract: OK
* "Stammkunde" in case the customer has a prolonged contract (e.g. another 3 years) and the prolongation contract start date is without a gap or less than 12 months after the old contract:
     * prolonged contract and the prolongation contract start date is without a gap: OK
     * prolonged contract less than 12 months after the old contract: OK
* Prolongations shall only happen with prolongation action in Sales Order:  not sure i understand this correctly, shall prolongations from contract not be considered for this? bc in my testcase the update to "Stammkunde" was done also when prolongation was done from contact, not sales order! => is that OK?
