### ISSUE TITLE
CSV import BP URL

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4823]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently the URL of the partner is not importable via I_BPartner's  Import Process
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Add BPartner URL in I_Bpartner, change the import process so it is also set up.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* URL imported correctly with Import Business Partner (importing single bpartners, as described above): URL imported correctly, OK
* URL imported correctly with .csv file (created a small file to import and a new Import Format containing URL as format field): URL was also imported correcly, and the rest of the data  as well: OK
