### ISSUE TITLE
Implement Excel Open XML format support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4842]
### What is the expected or desired behavior?
By default, all excel exports shall export using Excel Open XML format (i.e. `.xlsx` extension).

### Note to IT
Regression:
* webui: view: download selected
* swing: acct viewer export
* swing: any window, File->Export
* Export product specs: https://github.com/metasfresh/metasfresh/issues/4582

#### SysConfig: de.metas.excel.DefaultFileExtension
* xlsx - the Excel Open XML format (aka Excel 2007) will be used by default
* xls - the Excel97 format will be used by default

#### SysConfig: de.metas.excel.MaxRowsToAllowCellWidthAutoSize
Defines the threshold above which the column width auto-adjustment will not be performed.
Useful to speed up the export of huge excels.

By default is set to 100_000 rows.

#### SysConfig: de.metas.excel.UseStreamingWorkbookImplementation
Applies only for Excel Open XML format.

* Y - (enabled) the streaming version of workbook will be used, i.e. SXSSFWorkbook, see https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/streaming/SXSSFWorkbook.html

* N - (disabled) the regular implementation will be used, i.e. XSSFWorkbook, see https://poi.apache.org/apidocs/dev/org/apache/poi/xssf/usermodel/XSSFWorkbook.html

By default streaming is disabled.
Before enabling it read the documentation about the impact (highlights: memory consumption).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

quickly checked Excel exports:
* WebUI download selected: OK
* WebUI Export products: OK
* Swing Export products: OK
* Swing export of report, e.g. Umsatzreport: action for Excel Export missing (afair we already had an older task for that?)

**Comment by metas-dh** [comment]
Results of IT2
tested in release

* quickly checked Excel Export again: `.xlsx` files are exported, all working fine (as in IT1, see above): OK
* checked with metas-mk: working fine for >100.000 rows, in customer db: OK
