### ISSUE TITLE
Contract extension does not set date correctly 

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4846]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Contract extension action in Sales Order does not set the start date correctly for the new contract. It shall be set to the last contract end + 1 day.

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* contract extension from sales order sets the correct dates (start date: end date of original contract +1 day): OK
* new contract is created correctly: same terms as the original one, product, price, etc.: OK
* contract extension from contract window working fine as well: OK
