### ISSUE TITLE
Attribute editor dialog stores empty field as empty string

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#487]
what we want instead is
 both empty and <code>null</code> string values shall be stored as <code>null</code>.<br>
This is because until some time ago, <i>every</i> empty string was stored as <code>null</code> in the database and we want to preserve this behavior in this particular situation.

The reason for that is that a number of old jasper reports, and views and functions might still rely on this

**Comment by mckayERP** [comment]
Hi Tobi,

I just rewrote a lot of the ASI infrastructure for ADempiere.  You may find it helpful.  The ASI fields now accept text to match the ASI ID, a serial number, the lot code, guarantee date.  The save function prevents creation of duplicate ASIs.  I've done this in part to remove the ASI ID as the FIFO/LIFO tracking ID in MStorage and replaced it with a Material Policy Ticket.  I thing the ASI values should be independent of the FIFO/LIFO tracking.  You can see the changes to the callouts, MAttributeSetInstance, VPAttribute and VPAttributeDialog [here](https://github.com/adempiere/adempiere/compare/hotfix/3.8.0%23002...feature/ADEMPIERE_%23453_FixFIFO-LIFO#diff-08e50e15c83f6b5e54d180d98a3d4310). 

Mike

**Comment by metas-ts** [comment]
Hi @mckayERP, 
thx for the pointer and sorry for the late reaction..i saw your comment just now.
I will surely check out the changes in adempiere.

Best regards,
Tobi

**Comment by metas-dh** [comment]
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-770.md: OK
