### ISSUE TITLE
inventory related fixes

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4876]
### Is this a bug or feature request?
Bug
follow-up of metasfresh/metasfresh#4448 and metasfresh/metasfresh#4450

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. Inventur (Physical Inventory):
* automatische Nummernvergabe: OK
* Ergebnisse wenn Parameter gesetzt in Menge & Min. Wert / Min. Wert: OK 
* älteste HUs zu erst: keine Daten bislang in Inventur: HUs were sorted by value, smallest value (= oldest HU) first and biggest value (= newest HU) last: OK
* sortiert nach Lagerort: zuerst die, welche am längsten nicht gezählt wurden:
    * es waren aber andere Lagerorte noch nie in fertig gestellten Inventuren enthalten, sollten die nicht als erstes gelistet werden? => worked this time, OK
* `Zeilen erstellen (Lagerort & Produkt)` : Parameter "Lagerort" dropdown liefert keine Ergebnisse  (Parameter "Lagerort" works only when warehouse is set in main window, not when left empty), NOK (Aktion funktioniert aber ohne Parameter / mit Parameter Produkt) => afais this was not considered in this task, right? do we need another task for this?
* Feld Merkmale was correctly set (in my case, Bio): OK

**question**:
when running both available actions, w/o parameters set, i got different results:
* `Zeilen erstellen (Lagerort & Produkt)` : got 13 lines, including 1 product in Verdichtungslager
* `Zeilen erstellen (Lagerort-Anz. & Min.-Warenwert)`: got 12 lines, w/o the product in Verdichtungslager 
=> shouldn't the results be the same?


2. Inventur-Position Zählen:
* Filter now also includes "Zugewiesen an": OK
* Filter for product and Lagerort also included now: OK
* Filter for Suchschlüssel (value) not included anymore: OK? don't we need that anymore?
* changes like marking as "Gezählt" directly displayed, no window refresh necessary: OK
* field UOM not included anymore: OK

**Comment by metas-dh** [comment]
checked in mf15:

* filter for M_HU_ID included in Inventur-Position Zählen: OK
* working fine: OK
