### ISSUE TITLE
Account Schema window: don't allow creating new accounting schemas

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4886]
### Is this a bug or feature request?
FR/Bug

### What is the current behavior?
User can create a new accounting schema by pressing New button.

### What is the expected or desired behavior?
Don't allow because it's error prone because user also has to:
* create accounting schema GL
* create accounting schema defaults
* etc

If the acct schema is not correct, atm user will not be able to log in.

Instead of manually creating a new account schema, user shall use some process.

**Comment by metas-ts** [comment]
Note: aparently the C_AcctSchema records are created by the system; i.e. not by users via UI and not by some migration script.
I'm checking the issue further..

**Comment by metas-dh** [comment]
Results of IT1
tested in dev233

* creating new accounting schema not allowed: when trying you get an error msg "Create not allowed": OK
