### ISSUE TITLE
Add inactive product fields for hu tracing and label printing

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4892]
### Is this a bug or feature request?
FR

**Comment by metas-dh** [comment]
Results of IT1
tested in medios.metasfresh

* no new fields, in advanced edit (AD_Columns were activated acc. to metas-ts): NOK

**Comment by metas-ts** [comment]
## Dev-Test

* initially the fields are not shown: 
![image](https://user-images.githubusercontent.com/1264789/52127173-99f90e80-2631-11e9-99ab-39f8525e636e.png)

* now I activate those columns:
```sql
UPDATE AD_Column SET IsActive='Y',Updated=TO_TIMESTAMP('2019-01-23 10:10:01','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=563845 AND IsActive='N'
;
--UPDATE 1
--Query returned successfully in 89 msec.

UPDATE AD_Column SET IsActive='Y',Updated=TO_TIMESTAMP('2019-01-23 10:10:10','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Column_ID=563844 AND IsActive='N'
;
-- UPDATE 1
-- Query returned successfully in 84 msec.
```

* then I restart the webui-API 

* et viola:
![image](https://user-images.githubusercontent.com/1264789/52127362-2efc0780-2632-11e9-94b0-73712d9949fd.png)


i believe the previous fail was due to some unrelated glitch.

**Comment by metas-ts** [comment]
closing, as talked with @metas-dh
