### ISSUE TITLE
Support Automatic Numbering on Purchase Requisition

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#4895]
### Is this a bug or feature request?
FR

### What is the current behavior?
you have to put a manual number

#### Which are the steps to reproduce?
go to window https://live975.metasfresh.com/window/322
create a new record
number is null

### What is the expected or desired behavior?
shall be automatically generated

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & customer db

* automatic numbering in purchase requisition: OK
*customer db: 3 doc types in purchase requistion, each with its own document sequence: automatic numbering for each: OK
