### ISSUE TITLE
Errors in Tax Codes Report

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4896]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Seems that the report "Fibu Kontenblatt is not considering all Tax Codes.

**Comment by metas-dh** [comment]
Results of IT1
tested in erpprod

* missing VAT code, e.g. 231 is now included in the Tax Codes Report: OK
* checked both Fibukonto Kontoblatt and Fibukonto - Kontoblatt: VAT code included in both, OK
