### ISSUE TITLE
AD_Val_Rule ESR_Import_AD_AttachmentEntry is broken

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#4900]
### Is this a bug or feature request?
Bug
### What is the current behavior?

![image](https://user-images.githubusercontent.com/1264789/51686440-ab6a6700-1ff0-11e9-9050-7e428b3db6c5.png)

i.e. all attachment entries are shown

### What is the expected or desired behavior?

* only this entries that are actually attached shall be shown
* the attachment entries file name shall be displayed

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* only this entries that are actually attached shall be shown: OK

![2019-01-29 14_02_47-metasfresh](https://user-images.githubusercontent.com/18696715/51910292-15a75100-23cf-11e9-99f7-5103d8a2d261.png)

* attachment entries file name shall be displayed: OK
* ESR import worked fine (Gültig:Y): OK
