### ISSUE TITLE
Pricing: fallback to base price list version if any

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4906]
### Configuration
e.g.
![image](https://user-images.githubusercontent.com/1244701/52054286-af543700-2564-11e9-9640-86466f13f6e3.png)

In the above, if a product is not found in that price list version (PLV),
because the "Fallback to Base Price List Prices" flag is set,
system will search in the base PLV too.

If the product is not found in the base PLV, but the base PLV is configured to base another base PLV to fallback then the system will search in that too.
And so on...

### Note to IT
* test the main functionality: i.e. product price is fetched correctly by fallbacking to base price list versions (PLV)
* make sure, a product which is not in PLV but in some of the base PLVs is visible in
  - order batch entry
  - order line, advanced edit, set the product field

**Comment by metas-dh** [comment]
Results of IT1
tested in release

Product not in PLV, but in Fallback PLV:
* product price is fetched from Fallback PLV: OK (for batch entry)
* product is visible in
     * order batch entry: OK
     * order line: OK
     * advanced edit: i had to mind lower and upper case for this, only when i started writing with upper case the product was found: i think this is NOK?
     * set the product field: same as advanced edit: had to start writing in upper case to have the product displayed: NOK i think

=> problem i had (not sure this is a valid testcase bc of different taxes / countries): 
* the PLV was set for DE, while the fallback PLV had CH set. creating an orderline with batch entry worked fine, tax 0% EU MWSt erm. (Schweiz) was set (order could be completed too); but when i tried to create an orderline using advanced edit, i got an error about "Tax not found"
* after using batch entry and having tax 0% EU MWSt erm. (Schweiz)  set, i could not add another product with another tax, from the original PLV
@teosarca @metas-mk  wdyt?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

Product not in PLV, but in Fallback PLV:

* product price is fetched from Fallback PLV: OK (for batch entry)
* product is visible in
  
  * order batch entry: OK
  * order line: OK
  * advanced edit: OK
  * set the product field: OK
=> did not have any more problems with lower and upper case

* pricelists must have the same country / currency: 
    * when trying to set a fallback list from another country (different currency), i got the resp. error about the currency not matching: OK
    * when trying to set a fallback list from another country (same currency), i got the resp. error about the country not matching: OK
* i could set a pricelist from a different price system as fallback pricelist, but that was for the same country / the same currency, so i guess this is OK?
* "Fallback to Base Price List prices" was not yet translated for de_DE: NOK

**Comment by metas-dh** [comment]
checked again in latest master: trl for de_DE included: OK
