### ISSUE TITLE
Add payment discount when importing discount schema

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4913]
### Is this a bug or feature request?
FR

**Comment by cristinamghita** [comment]
## Dev tests on https://live2277.metasfresh.com
* Import window
![image](https://user-images.githubusercontent.com/15378036/52064760-f26ed400-257d-11e9-93a2-728ecfe92d2b.png)
* Discount schema
![image](https://user-images.githubusercontent.com/15378036/52064866-1f22eb80-257e-11e9-8dc1-3fcba7ae8cb9.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in live4442

* Import Discount Schema with Discount set: 3%, OK
* Discount Schema: Discount Schema Lines have Skonto: 3% set, OK
* in Import Discount Schema, it's called "Rabatt", although it is in fact "Skonto": in Discount Schema Lines it's "Skonto", so that's OK
