### ISSUE TITLE
Add a way to list all fonts available in JasperReport service

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4914]
### Is this a bug or feature request?
FR
### What is the expected or desired behavior?
We want to have a list with the installed fonts on a system that JasperReports serves can use.

 See https://community.jaspersoft.com/questions/533978/list-fonts-available-jasperreport

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* new menu entry to list available fonts (en_US & de_DE): OK
* new report listing all available fonts: OK
