### ISSUE TITLE
Checkbox Newsletter in der Neuaufnahme anzeigen

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4916]
### Is this a bug or feature request?
FR

### What is the current behavior?
* can not save newsletter info when using new partner window

#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* add checkbox newsletter to window "new partner"
* how to: type partner name into sales order - field partner that does not exist => select New Partner
show only when email address if filled (or make email mandatory when newsletter is checked)
store newsletter value on ad_user when window is closed

Dev hints from Tobi

```
> add checkbox newsletter to window "new partner"

"Neuer Geschäftspartner", `AD_Window_ID=540327`, AD_Table `C_BPartner_QuickInput`

> show only when email address if filled (or make email mandatory when newsletter is checked)

add either display rule or mandatory rule

> store newsletter value on ad_user when window is closed

model interceptor

Also: make sure it looks nice
```

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Newsletter checkbox in Neuaufnahme (order window- new bpartner on the fly): OK
* if Newsletter checkbox is checked: => mail address of contact person becomes mandatory: OK
* contact of new bpartner is created (with Newsletter flag `Y`):
     * Newsletter checkbox is checked in contact tab: OK
     * Contact Info also used in Marketing Contact Person: OK
     * Agreement in Marketing Contact Person is created, with date of test: OK
     * Agreement for Marketing is cancelled and has enddate set when Newsletter flag is set `N`: OK
* contact  of new bpartner is created (with Newsletter flag `N`):
    * Newsletter checkbox is NOT checked in contact tab: OK
     * Contact Info also used in Marketing Contact Person: OK
     * No Agreement in Marketing Contact Person is created: OK

**Comment by metas-dh** [comment]
quickly checked again after latest change of metas-rc: still working fine.
