### ISSUE TITLE
Tab AD_Element callout adjustments

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4928]
### Is this a bug or feature request?
Follow-up for #4887
### What is the current behavior?
Problem with AD_Tab, in IT from #4663:

> AD_Tab: Register & Name are taken from DB-Tabelle when this is set, change in AD_Element_Trl has no effect => also bc of https://github.com/metasfresh/metasfresh/issues/4887, this is NOK

from the IT of #4887, pls also keep in mind:

> Note; The above won't work if the table doesn't have a specific primary key. Talked with @teosarca and agreed this is not important since the most used case is working well.

#### Which are the steps to reproduce?
Check and see.

**Comment by teosarca** [comment]
closing because it's too old
