### ISSUE TITLE
Create MTransaction when completing cost collector of type issue/receipt

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4935]
### What is the expected or desired behavior?
When issuing products, the material cockpit balance for that product shall decrease.
When receiving finished goods or co/by-products, it shall increase.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Material Cockpit QtyOnHand:

* qty is correctly increased after receipt in manufacturing (after processing): OK
* qty is correctly decreased after issue in manufacturing (after processing): NOK, no change in qty

**Comment by teosarca** [comment]
closing because it's too old and works nowadays
