### ISSUE TITLE
Phonecall Planning and Execution

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#4951]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* 
#### Which are the steps to reproduce?
* 
### What is the expected or desired behavior?
 - Phonecall Schema like Tour (similar, don't take tour for that) + WebUI Window
- Phonecall data like deliverydays (similar) + WebUI Window
  - Shall Show Date+Time, Business partner, Contact, PhoneNo ...
- New action in Phonecall Data Window, that can be called when a Phonecall Row is selected. The action shall Open the window "Sales Order" and create an Order for the selected Partner and Contact.

**Comment by metas-dh** [comment]
IT1 & 2 documented in me03 task.
