### ISSUE TITLE
Implement Campain Pricing Rule

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4952]
### What is the expected or desired behavior?
* have a window where user can define the campaign price
* if the campaign price is defined 
   * that price shall be applied
   * no other discounts shall be applied

**Comment by teosarca** [comment]
### Dev test
* Configured a campaign price
![image](https://user-images.githubusercontent.com/1244701/52627450-0986bd80-2ebe-11e9-81ce-b03476e0e805.png)


* created a sales order and tried adding that product
=> the campaign price was used

Also tried different cases:
* set the bpartner instead of group => campaign price was used => OK
* disabled the campaign price => campaign price was NOT used => OK
* change the price => the new price was used => OK

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

SetUp:
* created Campaign Price for TestProduct, for bpartner group Standard
* standard prices for sales (>Campaign Price) and for purchase (<Campaign Price)

Test:
* Campaign Price is set when the bpartner belongs to the bpartner group Standard: **OK**
* Campaign Price is set for both sales and purchase: **OK**
* Campaign Price is set no matter if the standard price is higher or lower than the Campaign Price: **OK**
* when Campaign Price is set for a certain bpartner, it's not used in orders for other bpartners: **OK**
* when Campaign Price is set inactive, the normal price is set: **OK**
* Campaign Price is set only when the order's DatePromised matches the ValidFrom-ValidTo period of the price: **OK**
* setting manual discounts in orderline with Campaign Price (Net Price < Campaign Price) is possible: is that OK?
* discount schema for the product and the bpartner set: discount is not applied, the Campaign Price is set / remains (=> qty related discount): **OK** afaiu
* Campaign Price is set even if there is a Price Limit Restriction and Campaign Price < Price Limit Restriction: OK i think?


**problems / questions:**
* i could set a Campaign Price with neither a bpartner group nor a bpartner set, but then it was not set in any order:  NOK i think?
* if a discount schema is set the Campaign Price remains, despite the qty for discount being reached (e.g. 50% discount for qty:10 or more),  which afaiu is OK, **but:** there is no info for the user why there is no discount applied, the Campaign Price just remains: do we need some info for that case? or does the customer not use discount schemas?
* are manual discounts in the orderline (=> Net Price < Campaign Price) OK?
* Campaign Price is set even if there is a Price Limit Restriction and Campaign Price < Price Limit Restriction: OK i think?

@metas-mk @teosarca wdyt?

**Comment by teosarca** [comment]
> * i could set a Campaign Price with neither a bpartner group nor a bpartner set, but then it was not set in any order:  NOK i think? 

NOK: an error shall be shown


> * if a discount schema is set the Campaign Price remains, despite the qty for discount being reached 
(e.g. 50% discount for qty:10 or more),  which afaiu is OK, **but:** there is no info for the user why there is no discount applied, the Campaign Price just remains: do we need some info for that case? or does the customer not use discount schemas?

AFAIK, atm no discount schemas will be used in combination with campain prices.
Anyways, if the campain price is set, that's GOD.
And yes u are right, it's not transparent for the user, but the whole pricing calculation is not transparent for the user (or power user).

> * are manual discounts in the orderline (=> Net Price < Campaign Price) OK?

Yes, they are. User is allowed to change price, discount etc.

> * Campaign Price is set even if there is a Price Limit Restriction and Campaign Price < Price Limit Restriction: OK i think?

IMHO yes, it's OK.
@metas-mk wdyt?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* Campaign Price with neither a bpartner group nor a bpartner cannot be set anymore: bpartner group is preset, and when setting the value to Null an error pops up: OK

**Comment by metas-dh** [comment]
checked remaining questions with metas-mk:

* if a discount schema is set the Campaign Price remains, despite the qty for discount being reached 
(e.g. 50% discount for qty:10 or more),  which afaiu is OK, **but:** there is no info for the user why there is no discount applied, the Campaign Price just remains: do we need some info for that case? or does the customer not use discount schemas? => OK as it is

 * are manual discounts in the orderline (=> Net Price < Campaign Price): OK

* Campaign Price is set even if there is a Price Limit Restriction and Campaign Price < Price Limit Restriction: OK
