### ISSUE TITLE
M_DiscountSchemaBreak.PriceBase shall be nullable

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#4976]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open discount schema (aka pricing conditions)
* try to create/change a break
* try to change the PriceBase from `Pricing System` (or maybe `Fixed pricing`) to empty ... because you just want to give a discount but not override the normal price
=> you cannot, PriceBase is mandatory

### What is the expected or desired behavior?
It shall not be mandatory.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* M_DiscountSchemaBreak.PriceBase shall be nullable: OK
* M_DiscountSchemaBreak is valid and saved correctly when M_DiscountSchemaBreak.PriceBase is null:
    * M_DiscountSchemaBreak is marked as valid, OK 
    * **but** when you try to close the modal, the M_DiscountSchemaBreak is not saved obviously: NOK

![2019-02-21 10_44_59-metasfresh](https://user-images.githubusercontent.com/18696715/53159517-51949700-35c6-11e9-9831-adb0ed4cea55.png)

   
 * after closing the modal, no M_DiscountSchemaBreak exists with M_DiscountSchemaBreak.PriceBase=null: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* M_DiscountSchemaBreak is valid and saved correctly when M_DiscountSchemaBreak.PriceBase is null: no error, OK
* after closing the modal, the M_DiscountSchemaBreak exists with M_DiscountSchemaBreak.PriceBase=null: OK
