### ISSUE TITLE
M_Atribute_Value is not saved correctly

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4987]
### Is this a bug or feature request?
Bug
### What is the current behavior?
* Attributes with type Number are saved wrong in M_Attributevalue when the number ends with 0.
#### Which are the steps to reproduce?
* Have an attribute with type Number
* Use that attribute in Order and set value 20 for example
* Check in db -> in field value from m_attributevalue will be saved 2 instead of 20
### What is the expected or desired behavior?
* Shall be saved 20 or null.

**Comment by metas-dh** [comment]
Results of IT1
tested in live2439

ProductNo for attribute value that ends on "0", e.g. 10 or 20 (=> different ProductNo for attribute value not ending on "0", e.g. 1 or 2!):
* correct in document, e.g. order / shipment: OK
* correct in corresp. report: OK
