### ISSUE TITLE
URL csv Importer for BPartner

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#4991]
### Is this a bug or feature request?
FR

**Comment by metas-dh** [comment]
Results of IT1
tested in IT

(got a test csv.file from metas-cg for testing purposes):

* Import csv.file in Import BPartner Global ID: URL for yousty profile included: OK
* import test csv.file: URL for Yousty-Profil in the resp. bpartner is set and link works: OK
