### ISSUE TITLE
Packed HUs not displayed as Picked in HU Editor

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#4999]
### Is this a bug or feature request?
Bug
### What is the current behavior?
After the `Pack to` action in Picking Terminal v2, the HUs that were packed into another HU are still displayed as Active in HU Editor, not Picked. After the `Process` action, they are still displayed, with qty:0, still Active: NOK

![2019-02-26 15_41_45-notificationsform](https://user-images.githubusercontent.com/18696715/53474880-b0e32300-3a6e-11e9-8f56-317363e3b207.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
After the HUs are packed they shall be displayed as Picked in HU Editor.

**Comment by teosarca** [comment]
IMHO those HUs shall just be destroyed when empty, 
but we shall not change the status to Picked,
because (briefly) what happens when you process those rows is:
* the Qty is picked from those HUs and is packed (i.e. transfered) to some new HUs you specified
* those new HUs are shipment & invoiced etc.

More, imagine those HUs as huge recipients from were we pick small qtys.
What would be the reason to change their status to Picked?

**Comment by metas-dh** [comment]
so:
* in case we pick from 1 big HU (picking smaller qties each time), this HU will remain active, and as soon as the full qty is picked this HU will be destroyed: makes sense to me
* the newly created HUs will be shipped and invoiced: and these HUs will only be created when the `Process` action is called, and then directly be displayed as Delivered? they won't be displayed after `Pack to` action, as Picked? asking bc i did not see any change in status / new HUs in HU Editor after the packing, only after processing

**Comment by teosarca** [comment]
> the newly created HUs will be shipped and invoiced: and these HUs will only be created when the Process action is called, and then directly be displayed as Delivered? they won't be displayed after Pack to action, as Picked? asking bc i did not see any change in status / new HUs in HU Editor after the packing, only after processing

right, until u process, nothing happens. system is just recording ur intention.

**Comment by teosarca** [comment]
note to myself, sql i've used to check if the pick from HUs were destroyed:
```sql
select
	pickFromHU.M_HU_ID,
	pickFromHU.HUStatus,
	pc.*
from M_ShipmentSchedule sched
left outer join M_Picking_Candidate pc on pc.M_ShipmentSchedule_ID=sched.M_ShipmentSchedule_ID
left outer join M_HU pickFromHU on pickFromHU.M_HU_ID=pc.PickFrom_HU_ID
order by sched.M_ShipmentSchedule_ID desc, pc.M_Picking_Candidate_ID
limit 50
```

**Comment by metas-dh** [comment]
worked fine in customer db & weekly e2e: the picked HUs were destroyed (not Status:Active with qty:0), and the ones newly created by the `Process` action were displayed with Status: Delivered: OK
