### ISSUE TITLE
Not all invoice candidates are invoiced with Process action in Picking Terminal v2

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#5000]
### Is this a bug or feature request?
Bug
### What is the current behavior?
After using the `Process` action in Picking Terminal v2, the shipment and invoice are created, but not all ICs are invoiced,  and some are missing in the invoice:
![2019-02-27 09_10_51-169_545152 pdf](https://user-images.githubusercontent.com/18696715/53475409-23083780-3a70-11e9-9fe4-802c68b66fe9.png)

![2019-02-27 09_12_13-metasfresh](https://user-images.githubusercontent.com/18696715/53475424-2d2a3600-3a70-11e9-8389-8e3026dcf391.png)

![2019-02-27 09_11_13-167_145811 pdf](https://user-images.githubusercontent.com/18696715/53475445-32878080-3a70-11e9-8f77-95cfc0e3c0fa.png)

#### Which are the steps to reproduce?
Try and see.

**Comment by teosarca** [comment]
note to IT:
Also for the "won't pick" lines, we shall close the invoice candidates.
The shipment candidates we are already closing.

**Comment by teosarca** [comment]
note to myself, query i've used while i was debugging the invoice candidates stuff:
```sql
select 
ic.C_Invoice_Candidate_ID
, (select p.Name from M_Product p where p.M_Product_ID=ic.M_Product_ID) as Product
, ic.InvoiceRule
, ic.DateToInvoice
, ic.DateOrdered
, ic.DeliveryDate
--
, ic.QtyOrdered
, ic.QtyToInvoice
, ic.QtyInvoiced
, ic.QtyDElivered
--
, (select array_agg(iciol.M_InOutLine_ID)
	from C_InvoiceCandidate_InOutLine iciol
	where iciol.C_Invoice_Candidate_ID=ic.C_Invoice_Candidate_ID) inoutLine_Ids
--
, '--- OL:'
, ic.C_OrderLIne_ID
, ol.Line
, ol.QtyDelivered
, '----'
-- , ic.* 
from C_Invoice_Candidate ic 
left outer join C_OrderLine ol on (ol.C_orderLine_ID=ic.Record_ID)
where ic.C_Order_ID=???

```

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / customer db

* all shipment schedules that were picked were invoiced: OK

* > Also for the "won't pick" lines, we shall close the invoice candidates

=> in my case, the shipment schedule was processed, and the IC was set Processed:Y too, but `Invoiced completely override` was set Y as well and changeable: is that OK?

* the invoice candidate for the packing material, that was used in the `Pack to` action, was not invoiced => is that OK? the resp. product was on the sales pricelist, and also had a price >0

**Comment by teosarca** [comment]
> => in my case, the shipment schedule was processed, and the IC was set Processed:Y too, but Invoiced 
> completely override was set Y as well and changeable: is that OK?

as i saw, that closing in case of invoice candidates.
I think if u close the invoice candidates manually, by calling the "close" process, will happen the same.

> he invoice candidate for the packing material, that was used in the Pack to action, was not invoiced 
> => is that OK? the resp. product was on the sales pricelist, and also had a price >0

i think it's NOK....

**Comment by metas-dh** [comment]
checked with metas-mk: the packing material shall not be invoiced, basically we don't even want an invoice candidate for it in the first place (=> or rather, a possibility to decide when packing material shall be invoiced or not)

@teosarca i guess we'll need a new task for this? since the original problem of this one was solved
