### ISSUE TITLE
Create Sales Order from Quotation (with creating BOMs for order compensation groups)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5003]
#### Defining Quotation Groupping product
![image](https://user-images.githubusercontent.com/1244701/53585800-6efdce00-3b8f-11e9-9e09-d0b6844f28c8.png)

#### Defining the Product Planning schema for generated BOMs
![image](https://user-images.githubusercontent.com/1244701/53585868-9b194f00-3b8f-11e9-8d79-f10895f32e2b.png)

#### Generating the Sales Order from Completed Quotation
Have the complete quotation:
![image](https://user-images.githubusercontent.com/1244701/53586024-f51a1480-3b8f-11e9-8d51-b32f2aa538cf.png)

Run the process:
![image](https://user-images.githubusercontent.com/1244701/53586072-0e22c580-3b90-11e9-87d4-4619901bb501.png)

![image](https://user-images.githubusercontent.com/1244701/53586108-272b7680-3b90-11e9-8be2-57353f5ffca9.png)

Generated Sales Order which is automatically opened after running the process:
![image](https://user-images.githubusercontent.com/1244701/53586365-ae78ea00-3b90-11e9-89e5-59dde477d54e.png)

Generated Product:
* Product Category: it's the parent product category of the product category of the main/groupping product
![image](https://user-images.githubusercontent.com/1244701/53586408-cbadb880-3b90-11e9-93b1-fdee6663c842.png)

**Comment by teosarca** [comment]
### Note to IT
Regression:
* order checkup

**Comment by metas-dh** [comment]
check IT dokus in me03 issue.
