### ISSUE TITLE
Beautify C_PaySelection_CreateFrom and C_PaymentTerm fields

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#503]

**Comment by metas-dh** [comment]
C_PaySelection_CreateFrom: Y/N for 
* 1. Fällige Rechnungen,
* 2. Skonto ausnutzen,
* 3. Strittige einbeziehen: OK

C_PaymentTerm fields:
* Y/N for Fester Fälligkeitstermin taken out: OK
* Tage bis fällig: now Skonto-Karenz Tage: OK
* Net Day field: taken out: OK
