### ISSUE TITLE
Manufacturer Import IFA

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#5058]
### Is this a bug or feature request?
FR
### What is the current behavior?
None
### What is the expected or desired behavior?
We shall be able to import IFA Manufacturers

**Comment by metas-dh** [comment]
Results of IT1
tested in customer IT

1. Import IFA Hersteller:
* bpartners from import are set as Manufacturer:`Y`: OK
* bpartners from import have location data set (address, phone, email etc.): OK
* bpartners already existing were updated, no doubles: OK

2. Import product IFA - IA68:
* products have correct manufacturer info set: OK
(this did not seem to work at first, but the import was not yet processed => after processing the products had the correct manufacturer info set, OK)

(checked quickly in mediosprod: bpartners & products were set correctly with manufacturer info as well)
