### ISSUE TITLE
Allow Copy with details for BOM

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#507]
I as an user want to duplicate an entire BOM including the detail lines to safe myself work

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23507.md: OK

follow up for problem found during testing: https://github.com/metasfresh/metasfresh/issues/807
