### ISSUE TITLE
Don't allow narcotics in Trade (Sales & Purchase)

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5071]
### Is this a bug or feature request?
FR

### What is the current behavior?
Currently the narcotics permissions are not handled.

#### Which are the steps to reproduce?
-

###### Abstract

Atm, BPartner has ShipmentPermissionPharma and ReceiptPermissionPharma dropdowns which can take values like A (Type A), B (Type B).
ShipmentPermissionPharma is for when we are selling to that customer.
ReceiptPermissionPharma is for when we are buying from that vendor.

Type A means that BPartner is allowed to sell/buy RX(prescription) products.
Type B means that BPartner is NOT allowed to sell/buy RX products.

In M_Product we have a flag for "RX/prescription product" and also we have a flag for "is narcotic product" (Betäubungsmittel).

TODO: Introduce Type C:
Introduce Type C which allows BPartner to buy/sell narcotic products.
Type C includes Type A, i.e. RX products.

IMPORTANT: Make sure

if a product is flagged as RX product and also as Narcotic
BPartner ShipmentPermissionPharma/ReceiptPermissionPharma is Type A
then that partner is not allowed to buy/sell that product.
Only with Type C it would be allowed.
TODO: Make sure importing the Product's Narcotic flag (Betäubungsmittel) works
TODO: Make sure nobody can set the Type C
To dev test it, just update it in database.

**Comment by metas-dh** [comment]
IT documented in Don't allow narcotics in Trade (Sales & Purchase).
