### ISSUE TITLE
Enable set/unset of BPartner narcotics pharma permission

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5095]
### Is this a bug or feature request?
FR

### What is the current behavior?
Pharma Bpartner narcotics permission cannot be seen or selected anywhere.

#### Which are the steps to reproduce?
N/A

### What is the expected or desired behavior?

The pharma narcotics permission flag should be visible read-only in 
Business Partner Pharma -> Customer/Vendor
Business Partner Pharma -> Customer/Vendor -> Advanced edit

The narcotics flag should be editable in
Business Partner Pharma -> Actions -> Update Vendor Pharma Permissions
Business Partner Pharma -> Actions -> Update Customer Pharma Permissions

Setting or unsetting the flag should also set/unset the Shipment/Receipt Type C permission.

**Comment by TheBestPessimist** [comment]
dev-instance: https://dev382.metasfresh.com
version: 5.99.2_14888_gh5095

# Customer 

1. customer with no narcotics permission
![1 customer no narcotics permission](https://user-images.githubusercontent.com/4482210/55331988-1b87e400-549d-11e9-84df-10d7df8c9c79.png)

2. customer no narcotics permission -- advanced edit
![2  customer no narcotics permission -- advanced edit](https://user-images.githubusercontent.com/4482210/55331990-1c207a80-549d-11e9-983e-5705f9f299ce.png)

3. customer -- update customer pharma permissions -- enable narcotics
![3 customer -- update customer pharma permissions -- enable narcotics](https://user-images.githubusercontent.com/4482210/55331991-1c207a80-549d-11e9-8820-3b6ce86bef2b.png)

4. customer with narcotics permission
![4 customer with narcotics permission](https://user-images.githubusercontent.com/4482210/55331993-1c207a80-549d-11e9-84b2-2a10f3bf273d.png)

5. customer with narcotics permission -- advanced edit
![5 customer with narcotics permission -- advanced edit](https://user-images.githubusercontent.com/4482210/55331994-1c207a80-549d-11e9-9336-3962a358008f.png)



# Vendor




1. Vendor no narcotics permission
![1 vendor no narcotics permission](https://user-images.githubusercontent.com/4482210/55332187-918c4b00-549d-11e9-8a35-1ecde31ee39f.png)

2. Vendor no narcotics permission -- advanced edit
![2 vendor no narcotics permission -- advanced edit](https://user-images.githubusercontent.com/4482210/55332188-9224e180-549d-11e9-9142-9804c4d1c854.png)

3. Vendor -- update vendor pharma permissions -- enable narcotics
![3 vendon -- update vendor pharma permissions -- enable narcotics](https://user-images.githubusercontent.com/4482210/55332189-9224e180-549d-11e9-9689-c4390cc4a80b.png)

4. Vendor with narcotics permission
![4 vendor with narcotics permission](https://user-images.githubusercontent.com/4482210/55332190-9224e180-549d-11e9-88ba-7e0043ddfefc.png)

5. Vendor with narcotics permission -- advanced edit
![5 vendor with narcotics permission -- advanced edit](https://user-images.githubusercontent.com/4482210/55332192-9224e180-549d-11e9-9991-296541cf9439.png)

**Comment by metas-dh** [comment]
see IT in me03 task.
