### ISSUE TITLE
Area search - Geocoding

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5101]
### Is this a bug or feature request?
FR

### What is the current behavior?
N/A

#### Which are the steps to reproduce?
N/A

### What is the expected or desired behavior?

Note:  initial feature uses OSM integration

1. find and save the Geographical Coordinates (latitude and longitude) of each BParnter by their address or postal code (ref [Geocoding](https://en.wikipedia.org/wiki/Geocoding) )
2. Given a specific postal code, provide a list of all Customers of a Vendor in a 100km radius

**Comment by teosarca** [comment]
For the reference: the database function to be used to calculate the distance between to points is `geographical_distance`.
