### ISSUE TITLE
Tool to run all migration scripts from developer workspace

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5118]

**Comment by teosarca** [comment]
# How to use it from Eclipse
![image](https://user-images.githubusercontent.com/1244701/55661958-19fd4980-5818-11e9-9ecf-f9dcab1f847e.png)

![image](https://user-images.githubusercontent.com/1244701/55661966-2c778300-5818-11e9-89d3-ab668f74dfca.png)

**Comment by metas-dh** [comment]
checked with teo: issue can be closed, not for IT to test.
