### ISSUE TITLE
Fix AD_Element_Link related issues

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5119]
### What is the expected or desired behavior?
Have to DB functions which will be used to create AD_Element_Link records.
Aim: no AD_Window_ID, AD_Tab_ID, AD_Field_ID, AD_Element_ID in `INSERT INTO AD_Element_Link...` because that can corrupt migration scripts.

**Comment by metas-dh** [comment]
cannot be tested, see me03 task. closing.
