### ISSUE TITLE
Avoid generating values for "Value" column when dealing with application dictionary entities

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5128]
### Is this a bug or feature request?
bug

### What is the expected or desired behavior?
Following columns be mandatory and their value shall not be generated:
* AD_Process.Value
* AD_Message.Value
* AD_Ref_List.Value
* etc

Reason: if the value is generated, our migration script will contain things like `CurrentNext=CurrentNext + ?` which will corrupt our migration script.

**Comment by metas-dh** [comment]
closing this since no IT is needed (see me03 task).
