### ISSUE TITLE
Repair Umsatzreport Geschäftspartner Woche Excel

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#5134]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* The report is displaying the numbers correctly in the report but sums them up on each line wehn opening with excel.
#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* Please, fix.

**Comment by metas-dh** [comment]
Results of IT1
tested in customer dbs

Umsatzreport Geschäftspartner Woche, 2018 Week 1-40 compared to 2017 Week 1-40, Sales:Y:
* numbers correct in Excel (Total), same as in PdF: **OK**
* same numbers in both customer dbs: **OK**
