### ISSUE TITLE
Inventory with multiple HUs per inventory line

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#5137]
### Is this a bug or feature request?
FR

Note: take a quick look at https://github.com/metasfresh/metasfresh/issues/3825 too..if there is a problem, or what the issue was about

### What is the current behavior?

One inventory line can have one HU

### What is the expected or desired behavior?

Sometimes we don't care for individual HUs for that case we want one inoutline to represent a set of HUs which all have the same
* product
* storage relevant attribute values
* locator

When correcting the inventory numbers, then we also don't really care to which of those individual HUs the correction is applied.

**Comment by metas-dh** [comment]
ITs documented in me03 issue.
