### ISSUE TITLE
Generating C_Flatrate_Term from C_RfQ_Response then don't complete the term

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#515]
Generating C_Flatrate_Term fromC_RfQ then don't complete
- The C_Flatrate_Term shall not be completed, just draft/ prepered

**Comment by metas-ts** [comment]
* the therm is created in `PMM_RfQ_BL.createDraftContract()`
* it looks as if it is not completed right now

**Comment by metas-mk** [comment]
Is about "LIefervereinbarung" in Window Flatrate_Data. Gear Process "create new Flatrate Term". Additional Parm "shabbBeCompleted" initially set to 'N'. Flatrate Term shall aonly be completed if is set to 'Y' by the user.

**Comment by metas-rc** [comment]
Process C_Flatrate_Term_Create_For_BPartners: for parameter C_Flatrate_Conditions_ID also exclude the Type_Conditions "Procurement"

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #570
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-802.md: OK
