### ISSUE TITLE
Allow to delete Scale Prices

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5151]
### Is this a bug or feature request?
FR

### What is the current behavior?
We don't allow deleting scales prices with qty=1

#### Which are the steps to reproduce?
TIAS (try it and see)

### What is the expected or desired behavior?
Allow deletion of **all** scale prices

**Comment by metas-dh** [comment]
Results of IT1
tested in customer db

deleting scale prices:
* deleting 1st, 2nd 3rd etc. scale price possible: **OK**
* deleting single scale price (1st, 2nd or 3rd) is possible: **OK**
* deleting all scale prices in one go possible: **OK**

note: IsScalePrice:`Y` remains `Y` after deleting scale prices (and main price remains read only): checked with metas-nw: OK
