### ISSUE TITLE
reduce log-output of sequence checks when running migration-script

### ISSUE THREAD

**Issue by metas-jb** [metasfresh/metasfresh#5157]
### Is this a bug or feature request?
Feature request

### What is the current behavior?
When applying migration-scripts, the log-output is spammed with outputs from `SELECT dba_seq_check_native()`.
This is not desirable and makes it difficult to sift through logs.

#### Which are the steps to reproduce?
run an update of metasfresh and check the logs.
This happens everytime `java -jar ./lib/de.metas.migration.cli.jar` is run.

### What is the expected or desired behavior?
There shall only be an output if there are issues/errors.

**Comment by metas-dh** [comment]
closing since no IT is needed, see me03 issue.
