### ISSUE TITLE
Easier solution to clear the Picking Slots

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#518]
Easier solution to clear/ empty the Picking Slots
- atm this is only possible with creation M_ShipperTransportation and complete.
  --> solution could be to have an action which creates LU automatically for each Picking Slot BPartner Location Combination.

**Comment by metas-ts** [comment]
additional infos by @teosarca: 

Technical background: atm the shipper transportation with HUs is created by
* de.metas.handlingunits.client.terminal.aggregate.model.AggregateHUEditorModel.addSelectionToShipperTransportation(int)
* de.metas.handlingunits.shipping.process.M_ShippingPackage_CreateFromPickingSlots
OptionsAttachments

**Comment by metas-ts** [comment]
to implement, in HU-Editor
* use filter to select HUs which are in a picking-slot
* invoke the a new(?) "release from picking slot and build new LU" action for those HUs

note
* HUs with status "picked" need to remain in that status
* the the LUs are created, there needs to be one SSCC18 and one HU-label per LU...including all products and quantities

**Comment by teosarca** [comment]
Note to IT: pls check the frontend tasks before testing this one.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

clearing the Picking Slots in Picking Tray Clearing (Prototype)
* picked HUs: moved from picking slot in Picking Tray Clearing (Prototype) (with action "Take out"): HUs not in picking slot anymore: OK

problems reg. HUs that were taken out in Picking Tray Clearing (Prototype):
* status: Active again, not picked anymore: NOK, should still be picked
* HU is still displayed in the picking slot, in picking terminal: NOK, bc it was taken out
* still referenced in the shipment schedule (Qty picked, and Shipment / Picking subtab): OK
* creating shipment for Qty picked, from this shipment schedule: process is triggered, but no shipment is created: NOK

https://github.com/metasfresh/metasfresh-webui-api/issues/678
https://github.com/metasfresh/metasfresh-webui-api/issues/679
https://github.com/metasfresh/metasfresh-webui-api/issues/680
