### ISSUE TITLE
Invoice candidate from order line candidate - pricelist precision not applied when computing PriceActual

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#5186]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
# How to Test

* create a price list with a pricing precision of 4 (at any rate, something greater that your currency's precision)
* create a sales order with a 4-digit price-entered and a discount
* check out the respective invoice candidate
  * priceentered and priceactual need to be 4-digit
* repeat the same excercise with an order line candidate

**Comment by metas-dh** [comment]
see me03 task for IT.
