### ISSUE TITLE
On-the-fly auto-allocate available HUs while creating shipments

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#5204]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
# Dev-Test

* I tested with sales orders and different stock quantities, always with the same product (convenience salad)

# Nothing on stock - ordered 10 - QuantityType = "Qty to deliver"

* got a shipment with 
  * movementQty=10
  * no HUs assigned

# 2 HUs (10 + 11) on stock - ordered 150 - QuantityType = "Qty to deliver"

* got a shipment with 
  * movementQty=150, 
  * both HUs assigned (visible in the subtabs of both the shipment and the shipment schedule)

# 2 HUs (5 + 6) on stock - ordered 10 - QuantityType = "Qty to deliver"

* got a shipment with 
  * movementQty=10, 
  * 2 HUs (5 + 5) assigned (visible in the subtabs of both the shipment and the shipment schedule)
  * one remaining HU on stock, with qty=1
  * i.e. the 6-HU was split

# 2 HUs (1 + 5) on stock - ordered 10 - picked the HU with qty=1 - QuantityType = "Both"

* got a shipment with 
  * movementQty=10, 
  * 1 HUs (1 + 5) assigned (visible in the subtabs of both the shipment and the shipment schedule)
  * in the shipment schedule's subtab, there are the two sched-shipmentLine-HU-Assignments and one sched-shipmentLine-Assignment

**Comment by metas-dh** [comment]
IT was successful, see me03 issue.
