### ISSUE TITLE
Attribute Age automatism

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5208]
### Is this a bug or feature request?
FR

# Concept

Production Date refers to the date the product was produced. Can be modified only once.

Age Attribute refers to the number of months since Production Date. It is estimated as follows:
00-29 days = 0 months
30-59 days = 1 month
60-90 days = 2 months
etc.

- Update (as needed) HU Attributes:
    - Age: List with values: 0 - 12
    - Production Date: Date

- Add Age to `HUAttributeConstants` (similar to `Expiration date`)
- Extend `IModelAttributeSetInstanceListener` to allow the attribute to be used in AttributeSetInstance and propagate until the HU and documents (similar to `OrderLineExpiryModelAttributeSetInstanceListener`)

- Setting the HU-Attribute Age is done in two occasions
    - AD_Process that runs each night via AD_Scheduler and goes through all CUs and calculates the Age
    - HU-Editor: during material receipt has to propagate Age to enclosing HU (CU -> TU -> LU) (similar to `M_HU_Update_HU_Expired_Attribute`)

Helper/Example classes:

```de.metas.handlingunits.expiry.process.M_HU_Update_HU_Expired_Attribute```
```org.adempiere.mm.attributes.api.IModelAttributeSetInstanceListener```
```org.adempiere.mm.attributes.listeners.expiry.OrderLineExpiryModelAttributeSetInstanceListener```

**Comment by metas-dh** [comment]
see IT documentation in the me03 task.
