### ISSUE TITLE
Easy functionality for Drop Ship maintenance

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#521]
Easy functionality for Drop Ship maintenance
- Purchase Order, Material Receipt, seperate Warehouse
- no stock movements, only confirmations
- Trigger for shipment creation. Also confirmation? What about HU?

**Comment by metas-ts** [comment]
* flags M_ShipmentSchedule, M_ReceiptSchedule and C_InvoiceCandidate: IsDropShip
* we keep the dropship-warehouse
* can be changed later
* can we use M_Receiptconfirmation?
* when there is a confirmation, or if the dropship-vendor sends an vendor-invoice to us, then we also create the receipt and the shipment (both M_InOut)

**Comment by teosarca** [comment]
closing because it's too old
