### ISSUE TITLE
Material Cockpit: date filter not working correctly for stock 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#5220]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In Material Cockpit, the date filter is not working correctly: stock qty is displayed for e.g. 19.05., when there was no stock existing, all receipts were done on 20.05. or later.
#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Shall work.

**Comment by metas-ts** [comment]
hi @metas-dh this is not a bug.
the stock colum always shows the current stock, no matter which date is set.

**Comment by metas-dh** [comment]
hi @metas-ts ok, thx, misunderstood your info on that. closing the issue.
