### ISSUE TITLE
MRP Product Info not correct after VO RC CL

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#527]
MRP Product Info not correct after VO RC CL
- These docactions seem to not affect the MRP Product Info calculations

**Comment by metas-ts** [comment]
Hi @metas-mk, 
looking at the code, I strongly believe that we fixed this meanwhile. 
Moving the issue forward to "testing".

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23527.md: OK
