### ISSUE TITLE
Possibility to easily create more than 1 referenced Doc per Invoice

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#529]
Possibility to easily create more than 1 referenced Doc per Invoice
- Credit Memo
- Additional Invoice

**Comment by metas-ts** [comment]
Idea: don't let the "source invoice" reference the addtitional invoices or credit memory anymore. zoom-into should suffice

**Comment by metas-ts** [comment]
cherry-picked the fixes about manual credit memo creation to branch `2017-09-12`
* 5773667ee9aee52e0f43e4a176158891d3e1f313
* d52bbcdbbe955af385a2cf62101d32de68b91431

**Comment by metas-lc** [comment]
IT
go to sales invoice and create a new one
go to actions and create some credit memos for this invoice
=> you can create multiple credit memos for one invoice OK
=> you can zoom in to all credit memos OK
=> ref_invoice_id is set only to credit memos and not to your invoice as well OK
