### ISSUE TITLE
Fix Processed english name

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5366]
### Is this a bug or feature request?
issue was introduced by https://github.com/metasfresh/metasfresh/issues/5100, i.e. https://github.com/metasfresh/metasfresh/blob/5e116a8fb05667904fa4b0dd4220b2a0dee3a322/de.metas.adempiere.adempiere/migration/src/main/sql/postgresql/system/10-de.metas.adempiere/5518190_sys_gh5100_AustrianPostalCode_3.sql#L1243

### What is the current behavior?
The `Processed` flag was mistakenly named `Approved`.

#### Which are the steps to reproduce?
Open any window where we have that flag.

### What is the expected or desired behavior?
It shall be called Processed.
![image](https://user-images.githubusercontent.com/1244701/60737875-ea6bf380-9f64-11e9-8136-1c2ced9e92a4.png)

**Comment by teosarca** [comment]
@TheBestPessimist pls make sure I did not break something else. thanks.

**Comment by TheBestPessimist** [comment]
I don't think anything is broken with only a trl change
