### ISSUE TITLE
Catch Weight invoicing

### ISSUE THREAD

**Issue by lavinia81** [metasfresh/metasfresh#5384]
### Is this a bug or feature request? 
FR

**Comment by metas-ts** [comment]
# Some column descriptions

## Prices

* `PriceEntered`
  * the `PriceEntered` of any record (IC, orderLine, whatever) is the per-unit-price in the record's `C_UOM_ID`; possible discount **not** applied.
 
* `PriceEntered_Override`
  *  editable field where a different `PriceEntered` can be set by the user - also in the record's `C_UOM_ID`
  
* `PriceActual`
  * the `PriceActual` of any record is the per-unit-price in the record's `M_Product`'s stocking-UOM; possible discount **already** applied.
  * so, the `PriceActual` is `PricEntered` minus `Discount`, converted to stocking-UOM
	
* PriceActual_Override
  * **not editable**
  * computed in `de.metas.invoicecandidate.api.impl.InvoiceCandBL.setPriceActual_Override(I_C_Invoice_Candidate)`
  * computed from (PriceEntered_Override or PriceEntered) and (Discount_Override or Discount), if at least one of those two `_Override` values are not null
  * rounded to the IC's price list's precision

## Discounts

* `Discount`
  * discount as computed with by the pricing engine or inherited from the related record (e.g. order line)

* `Discount_Override`
  * editable field where a different discount can be specified by the user

* `QualityDiscountPercent`
  * computes as the percentage the quantities from related inout lines that were flagged to have issues. The respective quantites are in the `M_Product`'s stocking-UOM
    * example: 
	  * two inout lines: 1st: qty=75 with issues; 2nd qty=25 with no issues;
	  * => QualityDiscountPercent = 75

* `QualityDiscountPercent_Override`
  * editable field where a different `QualityDiscountPercent` can be set by the user
  * also set by metasfresh from pricing conditions' quality discounts

* `QualityDiscountPercent_Eff`
  * **DOESN'T ACTUALLY DO ANYTHING**, only maybe causing C_InvoiceLine.Description to be set  
  * so even if you set QualityDiscountPercent_Override to zero, the auantities of the inout lines with issues won't be invoiced

## Quantities

* `QtyOrdered`
  * ordered quantity, in the `M_Product`'s stocking-UOM

* `QtyEntered`
  * ordered quantity, in the record's `C_UOM_ID`

* `QtyDelivered`
  * shipped/received/fulfilled quantity in the `M_Product`'s stocking-UOM

* `QtyWithIssues`
  * shipped/received quantity in the `M_Product`'s stocking-UOM where the respective inout lines are flagged as having issues and shall therefore not be invoiced

* `QtyWithIssues_Override`
  * editable field a different QtyWithIssues` can be set by the user - also in the `M_Product`'s stocking-UOM

* `QtyWithIssues_Eff`
  * affective value that is usally subtracted from `QtyDelivered` when computing `QtyInvoice`

* `QtyToInvoiceBeforeDiscount`
   * based on *all* delivered quantities (with or without issues) - in the respective product's (stocking-)UOM

* `QtyToInvoice`
  * invoicable quantity in the respective product's (stocking-)UOM
  * usually the value is `QtyDelivered` minus `QtyWithIssues_Eff`
  
* `QtyInvoiced`
  * already invoiced qty in the `M_Product`'s stocking-UOM

* `QtyToInvoice_Override`
  * editable field where a different `QtyToInvoice` can be set by the user - also in the respective product's (stocking-)UOM.
  * will we reset to null by metasfresh as soon as the quantity was fully invoiced
  //* **important** even if a particular quantity was set, the system might invoice a different quantity
  
* `QtyToInvoice_OverrideFulfilled`
  * keeps track of how much from the currently set `QtyToInvoice_Override` was invoiced so far. When `QtyToInvoice_Override` ==  `QtyToInvoice_OverrideFulfilled`, then both values are reset to null

* `QtyToInvoiceInPriceUOM_Nominal`
  * `QtyToInvoice` converted to `Price_UOM_ID`; if there is no `Price_UOM_ID`, then the stocking-UOM is used, so `QtyToInvoice` is used unconverted
  
* `QtyToInvoiceInPriceUOM_Catch`
  * the actual delivered qty from the invoicable inout-lines, converted to `Price_UOM_ID`
  * does *not* include delivered quantities from inout lines are flagged as having issues!

* `QtyToInvoiceInPriceUOM_Eff`
  * see `IsCatchWeight_Eff`
  
## Misc  
  
* IsCatchWeight
  * coming from pricing system or referenced record such as order line
* IsCatchWeight_Override
  * editable Y/N field
* IsCatchWeight_Eff
  * decides if `QtyToInvoiceInPriceUOM_Eff` shall be set from `QtyToInvoiceInPriceUOM_Nominal` or `QtyToInvoiceInPriceUOM_Catch`

* IsInDispute
  * set to true by metasfreesh if there is at least one related inout line flagged to have issues

* InvoiceLine aggregator : if there are inout lines with quanties that have issues
  * **and** if the respective invoice candidate references the "Fresh Qualitätsabzug Aggregator" (not the default one!) via its `C_Invoice_Candidate_Agg_ID`
    * then upon invoicing, metasfresh will create two invoice lines; one line for the complete moved quantity and another line with a minus sign and the quantity with issues
  * **and** if the respective invoice candidate references the "Dafault" Aggregator via its `C_Invoice_Candidate_Agg_ID`
    * then upon invoicing, metasfresh will create one invoice line that contains the moved quantity minus the quantity with issues
