### ISSUE TITLE
Rename PriceListVersion "Discount Schema" to " Price List Schema"

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5414]
### Is this a bug or feature request?
FR.

#### Which are the steps to reproduce?
![image](https://user-images.githubusercontent.com/4482210/62621939-cade3700-b925-11e9-9a14-0fd5001819a6.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

PriceListVersion:

* de_DE: Preislisten-Schema, in grid & single view: **OK**
* en_US: Price List Schema, in grid & single view: **OK**
