### ISSUE TITLE
Translations not inherited when copying a window on version 5.108

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#5429]
### Is this a bug or feature request?
bug

### What is the current behavior?
element translations are not applied

#### Which are the steps to reproduce?
1. create a new window
1. use process "copy from other window" OR use copy fields from tab
1. NOK: field translation is not inherited from ad_element_trl
1. NOK: Tabs are also not translated

Element Translation:
![image](https://user-images.githubusercontent.com/16079655/63183666-d502e280-c055-11e9-87fc-bca9f9d2f3ff.png)

Field Translation AFTER copy:
![image](https://user-images.githubusercontent.com/16079655/63183700-eea42a00-c055-11e9-954c-ff42c5180d90.png)

workaround:

```SQL
create table fix.ad_field_trl_20190615 as
SELECT
  w.name as window_name,
  t.name as tab_name,
  f.ad_field_id,
  ftrl.name as ftrl_name,
       ftrl.description as ftr_desc,
       ftrl.help as ftrl_help,
    aet.name as aet_name,
       aet.description,
       aet.help

FROM ad_window w
  JOIN ad_tab t ON t.ad_window_id = w.ad_window_id
  JOIN ad_field f ON f.ad_tab_id = t.ad_tab_id
  join ad_field_trl ftrl ON f.ad_field_id = ftrl.ad_field_id
  join ad_column ac on f.ad_column_id = ac.ad_column_id
  join ad_element ae on ac.ad_element_id = ae.ad_element_id
  join ad_element_trl aet on ae.ad_element_id = aet.ad_element_id
  WHERE w.ad_window_id = 540668
  and aet.ad_language='en_US'
    and ftrl.ad_language='en_US'
  and f.isdisplayed='Y'
  and aet.name != ftrl.name
ORDER BY w.name

update ad_field_trl as target
  set name =data.aet_name, description=data.description, help = data.help
  from (select * from fix.ad_field_trl_20190615) data
where target.ad_language='en_US' and target.ad_field_id=data.ad_field_id;
```

### What is the expected or desired behavior?
translations shall be inherited as described in SQL

**Comment by teosarca** [comment]
on a quick check i've found out that translations are copied from original window,tabs,fields.

**Comment by teosarca** [comment]
note to dev: check de.metas.process.AD_Window_CopyWindow

**Comment by teosarca** [comment]
My test case: copy Abgabemeldung (i.e. Shipment Declaration, AD_Window_ID=540635) to a new window

### From window: Abgabemeldung
![image](https://user-images.githubusercontent.com/1244701/63447527-dad93900-c444-11e9-9937-999355d43158.png)
![image](https://user-images.githubusercontent.com/1244701/63447553-e75d9180-c444-11e9-9e05-4a5e11385354.png)
![image](https://user-images.githubusercontent.com/1244701/63447586-f3e1ea00-c444-11e9-8324-2f2b873d7d99.png)


### Target (new) window
![image](https://user-images.githubusercontent.com/1244701/63447682-1a078a00-c445-11e9-8167-fa3093b1d461.png)
![image](https://user-images.githubusercontent.com/1244701/63447696-21c72e80-c445-11e9-8d07-5aa2e7478e5a.png)
![image](https://user-images.githubusercontent.com/1244701/63447716-2855a600-c445-11e9-8adf-0a773a18519d.png)
![image](https://user-images.githubusercontent.com/1244701/63447736-31df0e00-c445-11e9-842c-0a557338f404.png)

**Comment by metasnw** [comment]
tested on latest master on #5444 and worked fine
assumption: window that was copied in this issue was already broken
