### ISSUE TITLE
Caching issue after creating a Credit Memo Sales Invoice and completing it

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5435]
### Is this a bug or feature request?
Bug

### What is the current behavior?
After running the whole cypress test suite on a dev instance, there is a caching issue with SI in list vs single view: 
- Single view: SI does not appear Paid (:x:)
- list view: SI is paid (:white_check_mark:)

#### Which are the steps to reproduce?

1. Create SI
    - test lieferant
    - doctype = SI
    - product = convenience salat
    - qty = 333
2. Complete SI
3. Run action "Gutschrift erstellen"
    - Belegart = "Credit Memo"
    - false (default)
    - true (default)
    - true (default)
    - false (default)
4. Select the new Credit Memo SI and complete it
    - it is paid
5. Come back to the SI
    - in single view it is NOT paid
    - in list view it IS paid

A cache reset fixes this, but next time i retry this process, it will have the caching issue again.

Single view
![image](https://user-images.githubusercontent.com/4482210/63319243-17604400-c322-11e9-93a0-6093b4ccdc4f.png)

List view
![image](https://user-images.githubusercontent.com/4482210/63319276-2fd05e80-c322-11e9-936a-42612babfbfa.png)

### What is the expected or desired behavior?

Both single and list view should show the same information: that the SI is paid after completing the Credit Memo.

**Comment by teosarca** [comment]
closing because it's too old
