### ISSUE TITLE
Error `Field DropShip_BPartner_ID already exists in element` in Customer Return window

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh#5439]
### Is this a bug or feature request?

BUG

### What is the current behavior?

Opening the Customer Return window (http://localhost:3000/window/53097) throws an error with the following message:
```
message: "Field DropShip_BPartner_ID already exists in element: Builder{internalName=X_AD_UI_Element[AD_UI_Element_ID=546050, 
Name=Lieferempfänger, 
trxName=<<ThreadInherited>>], 
caption=DropShip_BPartner_ID, 
description=Lieferempfänger - Business Partner to ship to, 
widgetType=Lookup, fields-count=2}"
```

The problem is that the field `DropShip_BPartner_ID` appears twice in advanced edit:
- first as an UI element
![image](https://user-images.githubusercontent.com/4482210/63431424-7a87ce80-c427-11e9-8d90-7597325f695f.png)
- second inside the UI element, as an additional field
![image](https://user-images.githubusercontent.com/4482210/63431468-8e333500-c427-11e9-8d56-c976278e4da5.png)

#### Which are the steps to reproduce?
Open the window.

### What is the expected or desired behavior?
The window appears correctly, no errors are shown.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. no error when opening window/53097: **OK**
2. advanced edit:
* `DropShip_BPartner_ID` field only appears once: **OK**
* checking the `DropShip` checkbox lets appear the `DropShip_BPartner_ID` field, to be filled with DropShip Bpartner (and location): **OK**
