### ISSUE TITLE
keep M_QualityNote and M_AttributeValue in sync

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#548]
This is a follow/up for issues #500 / #534.
In #500 /  #534 we added the table `M_QualityNote`
* When there is a material receipt with a qualiy issue, the created inoutline has a quality note value that came from the attribute value which was selected in the material receipt POS.
* Further, the system creates a `R_Request` with `R_Request.M_QualityNote_ID` referencing the `M_QualityNote` record whose `M_QualityNote.Name` matches the `M_AttributeInstance`'s `M_AttributeValue.Name`.

The big problem is that both `Name`s can be changd by an admin. 
Instead of matching via name, we need to match them via some key that is not subject to change.

TODO:
* Make sure to not depend on the quality note's name. 
   * suggestion: add the attribute value to the ASI of the new inout line when zou creawte it, and when looking up the R_Request.M_QualityNote_ID, use the Attribute_Value.Value from the ASI, not the name string from the inout line.
* `M_QualityNote` and the `M_AttributeValue` records with `M_Attribute_ID=540008` need to be synched with each other. We have something similar around "country" or "language" attributes, but i don't remember how or how well it works.
  * pls find out how it works there and if we need to extend it.
* We can name M_QualityNote the leading table, and sync everything one-way to M_AttrbuteValue. In that case, we need to prohibit edits to the M_Attribute_Values of that attribute.
* Not only changes, but also additional `M_QualityNote`s and deletes/deactivates need to be synched.
* Before implementing, please discuss your planned approach.

**Comment by metas-rc** [comment]
[17:47:56] Ruxandra Craciunescu: I verified how this is implemented.
For country, inaus land, adr etc this interface is used: org.adempiere.mm.attributes.spi.IAttributeValueGenerator
[18:03:22] Ruxandra Craciunescu: I plan to create an implementation of this also for quality. The logic will be in an implementation of org.adempiere.mm.attributes.spi.IAttributeValueGenerator.generateAttributeValue(Properties, int, int, boolean, String).
And I could make the M_QualityNote window editable and add a model interceptor on all creting, updating and deleting things there. all modifications will be also done in the attribute values of the quality note attribute which will be not editable by the user

**Comment by metas-rc** [comment]
Update: I think the AttributeValueGenerator is not needed in our case. I created a simple interceptor and I think it covers our needs.

I also implemented the ASI part in inout line. It works.

The problem I still have is that the attribute instance is not kept until I need it for the request. I will debug this further tomorrow.

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #562
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-834.md: OK
