### ISSUE TITLE
Report Account Info adjustments. Add parms date range.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#553]
Report Account Info adjustments. Add parms date range.

**Comment by metas-dh** [comment]
Results of IT 2 

* App.Server: sp80adit
* Buildno: #570
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-838.md: OK
