### ISSUE TITLE
Businesspartner Location isEDI shall not be ticked by default

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#555]
Businesspartner Location isEDI shall not be ticked by default

**Comment by metas-dh** [comment]
Results of IT 1

* App.Server: sp80adit
* Buildno: #562
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-842.md: OK
