### ISSUE TITLE
Report Saldenbilanz & Account Info native Excel Export

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#557]
Report Saldenbilanz & Account Info native Excel Export 
- to be further adjusted without layout changes
- without locking password

**Comment by metas-dh** [comment]
Results of IT 2  

* App.Server: sp80adit
* Buildno: #570
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-840.md: OK
