### ISSUE TITLE
failed to build metasfresh on eclipse NEON

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#562]
I try to build the actual metasfresh from scratch:

- cloned repo metasfresh
- cloned repo metasfresh-parent

I get ~900 maven dependency problems:
![mvndepprobl](https://cloud.githubusercontent.com/assets/3493126/20058866/a5260a2c-a4f3-11e6-9a8e-64b09e564e81.PNG)

here the first:
`Multiple annotations found at this line:
	- Missing artifact com.lowagie:itext:jar:2.1.7.js5
	- Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the local repository, resolution will not be reattempted 
	 until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://
	 repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find 
	 valid certification path to requested target org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/
	 mvn-public/ was cached in the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not 
	 transfer artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building 
	 failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
	 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238) at 
	 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206) at 
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585) at 
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503) at 
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) at 
	 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) at 
	 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) at 
	 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205) at 
	 org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:215) at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188) 
	 at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119) at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636) at 
	 org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63) at 
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:530) at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager
	 $3.call(ProjectRegistryManager.java:492) at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:1) at 
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:496) at 
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351) at 
	 org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:298) at 
	 org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:405) at 
	 org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:352) at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager
	 $2.call(ProjectConfigurationManager.java:1) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
	 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:
	 1351) at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:349) at 
	 org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77) at 
	 org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39) at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)`

the next some looks similar.

**Comment by metas-ts** [comment]
Hello @homebeaver ,
this is related to our new maven repository [https://repo.metasfresh.com](https://repo.metasfresh.com).
Older java versions aparently don't have our SSL certificate's root certificate in their store.
I had the same problem with java 1.8.0_65, and it was solved with  1.8.0_112.

As an alternative, it should also be possible to somehow add that certificate to your local store, but I didn't explore that possibility further.

Additional notes:
* if you decide to update Java, please make sure that also eclipse itself runs with that new version.
* I recomment to have a look at the new infos in the [Get the code into your IDE](http://docs.metasfresh.org/developers_collection/en/getting_started_ide_en.html) page in the docs. Besided an explanation of how to set the java-version, in also contains a hint to add `-Djavax.xml.accessExternalSchema=all` to the `eclipse.ini` to solve another problem.

Btw, please also feel free to use our brand-new [forum](https://forum.metasfresh.org/) for problems like this one.
That way I hope that Q&As like this one will be easier accessible for future contributors.

Best Regards
Tobias

**Comment by homebeaver** [comment]
thx Tobias,

- I use now jdk1.8.0_112
- NEON ini ist set to this java:
`-vm
C:/Program Files/Java/jdk1.8.0_112/bin
`
- I added also
`-Djavax.xml.accessExternalSchema=all
` to eclipse.ini

But the **maven dependency problems** remain - on another line:

![mbp](https://cloud.githubusercontent.com/assets/3493126/20060745/e0eb9258-a4fc-11e6-8fc1-ad51f731a1ba.PNG)

the problem text:
`Failed to execute goal on project de.metas.payment.sepa: Could not resolve dependencies for project de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: 
 Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the local repository, resolution will not be reattempted until the 
 update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://
 repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to 
 find valid certification path to requested target (org.codehaus.mojo:jaxb2-maven-plugin:1.6:xjc:generate-de.metas.payment.sepa.sdd.jaxb.v1:generate-sources) 
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project de.metas.payment.sepa: Could not resolve dependencies for project 
 de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ 
 was cached in the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer 
 artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221) at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127) at 
 org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245) at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:
 330) at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362) at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:
 1360) at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod
 $1.call(MavenBuilder.java:105) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at org.eclipse.m2e.core.internal.builder.MavenBuilder
 $BuildMethod.execute(MavenBuilder.java:86) at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at org.eclipse.core.internal.events.BuildManager
 $2.run(BuildManager.java:735) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at 
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at 
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project 
 de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ 
 was cached in the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer 
 artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211) at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195) ... 33 more Caused by: 
 org.eclipse.aether.resolution.DependencyResolutionException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in 
 the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact 
 com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384) at 
 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205) ... 34 more Caused by: 
 org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the 
 local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact 
 com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) at 
 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) ... 35 more Caused by: 
 org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the local 
 repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:jar:
 2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238) at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) ... 37 more`

I'll restart my system to check if it persist.

**Comment by metas-ts** [comment]
Hm, i recomend to also check your `JAVA_HOME` environment variable.

**Comment by homebeaver** [comment]
thx Tobias,

- I use now jdk1.8.0_112
- NEON ini ist set to this java:
`-vm
C:/Program Files/Java/jdk1.8.0_112/bin
`
- I added also
`-Djavax.xml.accessExternalSchema=all
` to eclipse.ini

But the **maven dependency problems** remain - on another line:

![mbp](https://cloud.githubusercontent.com/assets/3493126/20060745/e0eb9258-a4fc-11e6-8fc1-ad51f731a1ba.PNG)

the problem text:
`Failed to execute goal on project de.metas.payment.sepa: Could not resolve dependencies for project de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: 
 Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the local repository, resolution will not be reattempted until the 
 update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://
 repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to 
 find valid certification path to requested target (org.codehaus.mojo:jaxb2-maven-plugin:1.6:xjc:generate-de.metas.payment.sepa.sdd.jaxb.v1:generate-sources) 
 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project de.metas.payment.sepa: Could not resolve dependencies for project 
 de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ 
 was cached in the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer 
 artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221) at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127) at 
 org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:245) at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:
 330) at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362) at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:
 1360) at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137) at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172) at 
 org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1) at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112) at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod
 $1.call(MavenBuilder.java:105) at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151) at 
 org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99) at org.eclipse.m2e.core.internal.builder.MavenBuilder
 $BuildMethod.execute(MavenBuilder.java:86) at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200) at org.eclipse.core.internal.events.BuildManager
 $2.run(BuildManager.java:735) at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206) at 
 org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246) at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301) at 
 org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304) at 
 org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360) at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383) at 
 org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144) at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235) at 
 org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project 
 de.metas.payment.sepa:de.metas.payment.sepa:jar:3-development-SNAPSHOT: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ 
 was cached in the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer 
 artifact com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211) at 
 org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195) ... 33 more Caused by: 
 org.eclipse.aether.resolution.DependencyResolutionException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in 
 the local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact 
 com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384) at 
 org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205) ... 34 more Caused by: 
 org.eclipse.aether.resolution.ArtifactResolutionException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the 
 local repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact 
 com.lowagie:itext:jar:2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) at 
 org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367) ... 35 more Caused by: 
 org.eclipse.aether.transfer.ArtifactTransferException: Failure to transfer com.lowagie:itext:jar:2.1.7.js5 from https://repo.metasfresh.com/repository/mvn-public/ was cached in the local 
 repository, resolution will not be reattempted until the update interval of metasfresh-repo has elapsed or updates are forced. Original error: Could not transfer artifact com.lowagie:itext:jar:
 2.1.7.js5 from/to metasfresh-repo (https://repo.metasfresh.com/repository/mvn-public/): sun.security.validator.ValidatorException: PKIX path building failed: 
 sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:238) at 
 org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503) at 
 org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421) ... 37 more`

I'll restart my system to check if it persist.

**Comment by homebeaver** [comment]
JAVA_HOME ist set to jdk1.8.0_112 - the problem remains.

**Comment by metas-ts** [comment]
Did you also already invoke "Update Maven 'Project" with "force update of snapshots" on the de.metas.payment.sepa project?

![image](https://cloud.githubusercontent.com/assets/1264789/20062207/21573c60-a503-11e6-9d09-682b34b51c91.png)

**Comment by homebeaver** [comment]
Yes, I done it.

**Comment by metas-ts** [comment]
hmmm..ok, what about the installed JREs..maybe there you still have the old one, and mave the embedded maven uses that one.. this is how it looks in my instalation:
![image](https://cloud.githubusercontent.com/assets/1264789/20063411/508b1e8a-a507-11e6-85e1-956bc391e328.png)

**Comment by homebeaver** [comment]
That is it. I was sure, I've changed it to 112. 
But I have two workspaces and I chanched it in only one. 
Thank you, Tobias. Feierabend!

**Comment by metas-ts** [comment]
Great, thx for the feedback
