### ISSUE TITLE
Report Statistics qty per Week

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#563]
Report Statistics qty per Week
Already existing qty per month. Same Data, just aggregated per week.

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #570
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-851.md: OK
