### ISSUE TITLE
Report Revenue per Week and BPartner also show qty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#565]
Report Revenue per Week and BPartner also show qty
modify the existing report and add a column with qty

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #656
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-850.md: OK
