### ISSUE TITLE
Rest endpoint which allows the client to create invoices

### ISSUE THREAD

**Issue by cristinastefan90** [metasfresh/metasfresh#5664]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
# Documentation

## Swagger

When running from your IDE, the URL is probably: http://localhost:8181/swagger-ui.html#/invoice-candidates-rest-controller-impl/enqueueForInvoicingUsingPOST

![image](https://user-images.githubusercontent.com/1264789/67816535-85f01980-faaa-11e9-9b3a-85f4b1860ff0.png)


Here is an example for a request with multiple external line IDs, and no additional proameters:

```json
{
  "invoiceCandidates": [
    {
      "externalHeaderId": "abc",
      "externalLineIds": [
        "123", "124"
      ]
    }
  ]
}
```
