### ISSUE TITLE
WebUI - Material Receipt Schedule

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#567]
WebUI - Material Receipt Schedule

- Initial Window and Sidelist

**Comment by metas-dh** [comment]
Results of IT 1  

* tested on: http://w101.metasfresh.com:8090/

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-852.md: OK

remaining problems:
* material receipt schedules created before order is completed: https://github.com/metasfresh/metasfresh-webui/issues/84 (when they are created, you can't delete the resp. orderline, without deleting the receipt schedule first!)
* delete button not reachable at the bottom of the page: https://github.com/metasfresh/metasfresh-webui-frontend/issues/136
* remaining problem with ordering: https://github.com/metasfresh/metasfresh-webui-frontend/issues/135
* occasional problem when opening documents or using back & forth: https://github.com/metasfresh/metasfresh-webui/issues/71
* referencing will be improved: https://github.com/metasfresh/metasfresh-webui-frontend/issues/138
