### ISSUE TITLE
Report Reclamation result, quality note and minor changes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#576]
Report Reclamation 
- result --> missing sometimes
- quality note --> missing sometimes 
- and minor changes (header sometimes too big/ long doesnt fit)

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #575
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-859.md: OK
