### ISSUE TITLE
Button Request shows too many results

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#577]
Button Request shows too many results
- not filtered like when opening in default menu entry

**Comment by metas-dh** [comment]
Results of IT 3  

* App.Server: sp80adit
* Buildno: #598
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-858.md: OK
