### ISSUE TITLE
Request Window Attachment Image too large in viewer

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#578]
Request Window Attachment Image too large in viewer
- the viewer is opened so big that the window must be moved before one can close it again (reach the close button)
- check the solution that was done in Material Receipt (%ual size)

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #656
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-862.md: OK
