### ISSUE TITLE
Handling units without washing cycle shall be allowed in washing Manufacturing Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#579]
Handling units without washing cycle shall be allowed in washing Manufacturing Order

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #573
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-861.md: OK
