### ISSUE TITLE
introduce C_OrderLine.ExplodedFrom_BOMLine_ID

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#5814]

**Comment by metasnw** [comment]
# IT 
on 5.129.1_18354_master

- created new order and added trade BOM with two lines
- checked via sql
```SQL
select c_order_id,c_orderline_id,explodedfrom_bomline_id from c_orderline order by created
```
- explodedfrom_bomline_id is filled with the ID of the pp_product_bomline
  ![image](https://user-images.githubusercontent.com/16079655/69442509-feb26080-0d4c-11ea-81ec-ea877dd06421.png)


=> OK
