### ISSUE TITLE
Adjust the remaining Property names

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#585]
Adjust the remaining property names and switch from ADempiere to metasfresh.

![image](https://cloud.githubusercontent.com/assets/13365687/20186457/5f71ba42-a770-11e6-9089-cbbe3d6d0996.png)

**Comment by teosarca** [comment]
NOTE to dev: pls check org.compiere.util.SupportInfo.getInfo(StringBuilder)

**Comment by metas-dh** [comment]
Results of IT 1 
* App.Server: sp80cloudit / mf15cloudit
* Buildno: #s69 / 1.219
* DB: declouddb001 : 5432 / sp80_cloud_it / mf15_cloud_it

* mf15_cloud_it: no more adempiere in property names: OK
* sp80_cloud_it: one adempiere left, Dorg.adempiere.client.lang="de_CH" (not existing on mf15cloudit): to be solved in #686
