### ISSUE TITLE
Client and Company name in metasfresh Database seed

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#586]
Client and Company name in metasfresh Database seed
- change the names from "metas fresh" to "metasfresh"

**Comment by metas-mk** [comment]
Added the following script to fix the DB Seed:

```
update c_bpartner
set value = 'metasfresh', name = 'metasfresh AG', companyname = 'metasfresh AG'
where true
and name = 'metas fresh AG'
and c_bpartner_id = 2155894
;

update ad_org
set name = 'metasfresh AG'
where true
and name = 'metas fresh AG'
and ad_org_id = 1000000
;
```

**Comment by metas-jb** [comment]
update master release database with new config as stated above

**Comment by metas-dh** [comment]
Results of IT1:

*  "metasfresh" on w101: OK
*  "metasfresh" on mf15releasetest: will check in next e2e on new version

**Comment by metas-dh** [comment]
mf15releasetest latest version: OK
