### ISSUE TITLE
Additional Invoice Information

### ISSUE THREAD

**Issue by pvpurcarcosmin** [metasfresh/metasfresh#5887]
### Is this a bug or feature request?
FR

**Comment by metas-ts** [comment]
Pasting here the documentation creted by @pvpurcarcosmin :

Added the possibility of storing additional information via 'Create new invoice candidates' endpoint. The  additional data must be sent as shown in the example below (see **invoiceDetailItems**).
```
 {
  "items": [
    {
      "orgCode": "001",
      "externalHeaderId": "externalHeaderId_unique6",
      "externalLineId": "externalLineId_7",
      "poReference":"cosmintest1",
      "billPartnerIdentifier": "val-G0002",
      "billLocationIdentifier": null,
      "billContactIdentifier": null,
      "productIdentifier": "val-P002737",
      "soTrx": "PURCHASE",
      "invoiceRuleOverride": "Immediate",
      "qtyOrdered": 10,
      "invoiceDetailItems" : [
        {
          "seqNo": "10",
          "label": "label1",
          "description": "desc1"
        },
        {
          "seqNo": "20",
          "label": "label2",
          "description": "description2"
        }
      ]
    }
  ]
}
```

The data sent for "seqNo","label" and "description"  will be persisted in the 'C_Invoice_Detail' table's columns with the same name. Please note that for each detail item there will be one record stored in DB.

Can be tested by sending an POST HTTP req to '{baseUrl}/api/invoices/createCandidates' with the body displayed above. After successfully storing the invoice candidate, go to 'Billing Candidates' window and generate the invoice by selecting 'generate invoices' from the quick action menu. After this step make sure the invoice details are linked to the invoice and invoice line through 'c_invoice_id' and 'c_invoiceline_id'
