### ISSUE TITLE
Empties mask and functionality with autom. set the selected bpartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#597]
Material Receipt Pos Window. Row is selected (BPartner therfor too)
- press on empties button
--> the BPartner and return shall automatically get filled/ preset

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #573
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-875.md: OK
