### ISSUE TITLE
Backend: Send new field in JSON of available docaction dropdowns for VOID Action.

### ISSUE THREAD

**Issue by dragospodariu96** [metasfresh/metasfresh#6100]
### Is this a bug or feature request?
FR
### What is the current behavior?
No 'validationmessage' field exists for any document's available docactions
#### Which are the steps to reproduce?
Open the docactions dropdown and check the response.
### What is the expected or desired behavior?
A new field, 'validationmessage' with the popup validation question will show in the 'validationmessage' field when clicking on the docaction dropdown.

**Comment by metas-ts** [comment]
see https://github.com/metasfresh/metasfresh/pull/6101#issuecomment-580591145
