### ISSUE TITLE
Purchase Order wrong Price from Contract or Pricesystem for specific Product

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#615]
Purchase Order wrong Price from Flatrate Term/ Contract or Pricesystem for specific Product
Please check and Fix.

**Comment by metas-rc** [comment]
Steps for testing:
*Go to laufender vertrag, select the partner you want to test;
*Run the gear process, create a procurement term using it (classic way), to not complete the term;
Remember the pmm product you used in the term: both product and M_HU_PI_Item_Product;
*Go to the newly created term, and jump to the dataEntry tab => the data entries should have been created
*Select the dataentry for the period you want to test, set a FlatrateAmtPerUOM (this is the price that will get into the orderline)
*After doing the setting above, go back to the term and complete it
*Create a purchase order for the partner you made the term for, set a promised date in the period tou made the term for
*Create a line for the product of the pmm, with the M_HU_PI_Item_Product of the pmm
=> the price you set in the FlatrateAmtPerUOM shall be the priceENtered in your new line

**Comment by metas-ts** [comment]
Integrated into master for now, but please check out the review at https://github.com/metasfresh/metasfresh/pull/756#pullrequestreview-14822182

please don't close after IT, but move back to Ruxi

**Comment by metas-dh** [comment]
* https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-890.md: OK

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 5

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-890.md: OK
