### ISSUE TITLE
Fix operator update in advance search panel

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#617]
When adding an operation in the advance search you can only see the operators that fit the type of the operand (column what you search after) .
Problem is that afterwards, the column can be changed and the operator you chose remains the same even if it doesn't fit the new column.
TODO: Make the operators update when the column changes.

Problem 2 (found while using operator >-< (between)  in a case as described above: The string ">-<" gets in the parsed sql like "C_DocTypeTarget_ID >-< 1000016 AND NULL"
TODO: CHeck the code that parses the search query and fix the issue.

**Comment by metas-rc** [comment]
For the ">-<" ( BETWEEN) issue check the code from org.compiere.model.Restriction.buildSqlWhereClause(String, String, Operator, Object, Object, List<Object>)

**Comment by teosarca** [comment]
closing this one because it was handled & fixed in #674
