### ISSUE TITLE
Marginal Return Report doubled sums for accounting group

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#620]
Marginal Return Report doubled sums for accounting group

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #s 591, 598
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-893.md: OK
