### ISSUE TITLE
Update total ammount when deleting line from payment selection

### ISSUE THREAD

**Issue by dragospodariu96** [metasfresh/metasfresh#6342]
### Is this a bug or feature request?
FR
### What is the current behavior?
Total ammount is not updated after deleting a line from a payment selection document.
#### Which are the steps to reproduce?
Delete a line from a payment selection document and see that the total ammount is not updated unless a cache reset is done.
### What is the expected or desired behavior?
Total ammount to get updated without needing a cache reset.

**Comment by metas-dh** [comment]
https://github.com/metasfresh/me03/issues/4107#issuecomment-653926368
