### ISSUE TITLE
Marginal Return report calculation does not check ad_org_id

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#639]
Marginal Return report calculation does not check ad_org_id

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adrt
* Buildno: #14
* DB: deddb905 : 5432 / sp80_ad_rt

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-913.md: OK
