### ISSUE TITLE
Link from Bank Statement to ESR Import not working / trl missing

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#6500]
### Is this a bug or feature request?
Bug
### What is the current behavior?
* The link from Bank Statement to ESR Import not working. 
* Also, i don't understand the name, what's "Transparenz" supposed to mean in this case??
* Pls also add a trl for "Invoice Document No" in Bank Statement overlay 
#### Which are the steps to reproduce?
Try and see.

**Comment by teosarca** [comment]
closing it because it's too old
