### ISSUE TITLE
Fix or move to defunct the tests that fail

### ISSUE THREAD

**Issue by petrican** [metasfresh/metasfresh#6549]
### Is this a bug or feature request?
B
### What is the current behaviour?
Some tests are failing as a result of running e2e test 
#### Which are the steps to reproduce?
Run entire suite 
### What is the expected or desired behaviour?
All tests should pass. We should have a green build

**Comment by metas-ts** [comment]
Hi @petrican 
it's a little bit depressing, but pls make sure to separate the test for the known problem which we are working on from those other testst that await refurbishing.

**Comment by petrican** [comment]
Hi @metas-ts 
Yeah it's depressing. You see there were modifs in the code like removing `Name` for the  PLV without also adapting the cypress tests involved as a result there are quite some tests that need to be shaped/adapted accordingly. Tried on Fri some fixes with Cristian but it seems the fixes screw other areas. Need to think for a solutions. Also I am thinking to put the picking tests to integration_defunct.  The drawback when working on the cypress tests is that sometime I need to run the complete suite to make sure nothing else gets screwed and that takes a lot of time.
