### ISSUE TITLE
Bug in Import Format - Copy lines process

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#656]
Habe mal Partner-Import probiert nach Anleitung [Wie definiere ich ein Importformat ?](http://docs.metasfresh.org/howto_collection/Wie_definiere_ich_ein_Importformat.html)

Im Punkt 7 : Button “Positionen kopieren” gab es ein Problem 👎 : 

![p](https://cloud.githubusercontent.com/assets/3493126/20724933/821467fc-b670-11e6-9405-e7561a4d15bf.PNG)

Das sieht nach einem Bug aus.

**Comment by teosarca** [comment]
Hi,

can u pls provide us the stacktrace from console?

**Comment by homebeaver** [comment]
_can u pls provide us the stacktrace from console?_
I got this Problem with FRESH-925 branch. Sorry no trace yet.
I cannot reproduce it with Version  4.41.40#593

**Comment by teosarca** [comment]
I've reproduced & fixed on master.

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: mf15cloudit
* Buildno: #1.196
* DB: declouddb001 : 5432 / mf15_cloud_it

*http://docs.metasfresh.org/howto_collection/Wie_definiere_ich_ein_Importformat.html: did how-to documentation, no errors, all worked fine
