### ISSUE TITLE
make Ini more robust

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#658]
Problem: `Ini.loadProperties` handles problems loading the init file very sloppy. this led to problem on a tomcat instance where the file could not be read and the weird things happened (i think also tomcat acted strangely..)

**Comment by teosarca** [comment]
IMHO we shall:
* on server side: get rid of it, at all, and use only spring's application.properties / sysconfigs
* on client side (swing): reduce it to minimum and all other preferences shall go to AD_Preference or something similar

**Comment by metas-ts** [comment]
my intention is just to salvage the fix from that legacy repo..i don't intend to spend the afternoon and more on this ..at least not today..

**Comment by metas-dh** [comment]
Results of IT 1  

* App.Server: sp80adit
* Buildno: #614
* DB: deddb905 : 5432 / sp80_ad_it

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-950.md: OK
