### ISSUE TITLE
Cultivation Planning report adjustments

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#661]
Cultivation Planning report adjustments
- to be detailed

**Comment by metas-dh** [comment]
Results of IT   

* App.Server: sp80adrt
* Buildno: #16
* DB: deddb905 : 5432 / sp80_ad_rt

* "Importsaison" taken out of report, de_CH & fr_CH: OK
* more space between vendor & address field and date, de_CH & fr_CH: OK
* report always has 2 pages even though 2nd is empty: fixed, de_CH & fr_CH: OK
