### ISSUE TITLE
Bug in ClientUpdateValidator

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#679]
ich arbeite mit `de.metas.SwingUIApplication_mf15_with_embedded_server.launch`
und stelle fest, dass seit dem update auf V 45.46 der client nicht mehr startet.

![bug](https://cloud.githubusercontent.com/assets/3493126/20974091/66739faa-bc9b-11e6-857c-dd7de93af429.PNG)

Die Prüfung sollte bei einem LOCAL_BUILD nicht stattfinden.

**Comment by metas-ts** [comment]
Hallo @homebeaver 
danke für den Hinweis, wir schauen nach dem Problem
Du kannst als Workaround in die launch-configuration zur Starten des Clients den Kommandozeilenparameter `-Dde.metas.clientcheck.Enabled=false` einfügen.
Vgl http://docs.metasfresh.org/support_collection/en/client_version_check.html

**Comment by metas-ts** [comment]
fixed the bug in master branch, planned release is next week
