### ISSUE TITLE
Translation in window Material Receipt

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#683]
Translation in window Material Receipt
- shows german name "Auftrag", should be "Bestellung"
- shows german name "Auftragsdatum", should be "Bestelldatum"

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80cloudit
* Buildno: #205
* DB: declouddb001 : 5432 / sp80_cloud_it

window Material Receipt (Wareneingang):
* "Auftrag" now "Bestellung": OK
* "Auftragsdatum", now "Bestelldatum": OK
