### ISSUE TITLE
Do not create receipt schedules for drafter orders

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#688]
Problem first reported in https://github.com/metasfresh/metasfresh-webui/issues/84 but it is not a webui related issue. We just happened to find it there.

Steps to reproduce: 
* Create a purchase order, create an orderline for it
* Go into that orderline and change the Qty ( do not complete the order) 
=> NOK: A receipt schedule is created 

(Teo) : 
the fix shall be at least in de.metas.inoutcandidate.modelvalidator.C_OrderLine_ReceiptSchedule.createReceiptSchedules(I_C_OrderLine)
where we shall check if the order is not Drafted.

**Comment by teosarca** [comment]
pls check if this is still open

**Comment by metas-lc** [comment]
checked. Not happening anymore OK
