### ISSUE TITLE
provide db migration launch for eclipse UI

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#690]
ich entwickele mit  eclipse wie in [getting_started_ide](http://docs.metasfresh.org/developers_collection/en/getting_started_ide_en.html_en.html) beschrieben. Meine EU ist eclipse NEON und eine lokale postgres DB unter WIN 10.

Vor kurzem habe ich ein update der source auf V 45.46 gemacht. Die DB hatte noch einen älteren Stand und ich wollte sie auf die aktuelle Version migrieren - `de.metas.migration.cli.jar`

Dabei stelle ich fest, dass es keine Möglichkeit gibt, das migration-jar von der EU aus zu starten. Das ist schlecht, denn in der EU wird als erstes ein Test gemacht.
Bitte schliesst diese Lücke. Danke.

**Comment by metas-ts** [comment]
Hallo,
Du hast recht, diese Möglichkeit sollte es geben.
Bis es soweit ist kannst Du Dir vieleicht von 
https://jenkins.metasfresh.com/job/metasfresh/job/master/ die "sql-only-tar.gz" des jeweils aktuellsten builds ziehen:
![image](https://cloud.githubusercontent.com/assets/1264789/21046028/eda88072-be02-11e6-92ce-6e44e1c0f436.png)

Diese dann auf entpacken und die enthaltene `remote_sql.sh` laufen lassen..wie bei einen normalen Produktiv-Update (vgl. http://metasfresh.com/dokumentation/serverupdate/ ).

Noch ein Hinweis: Das Anmelden auf jenkins.metasfresh.com sollte mit Deinem github-account funktionieren.

**Comment by homebeaver** [comment]
Danke für den Hinweis zu jenkins. Aber ...

![jenkins](https://cloud.githubusercontent.com/assets/3493126/21047436/2ff45b20-be0a-11e6-859f-cb19efb3b7f4.PNG)

**Comment by metas-ts** [comment]
Kannst Du bitte nochmal versuchen? 
Ich habe es vor ca 10 Minuten selbst auch nochmal mit einem "externen" github account versucht und die Rechte etwas korrigiert.

**Comment by homebeaver** [comment]
Ja, jetzt geht es. Merci

**Comment by metas-ts** [comment]
Hi @homebeaver and a happy new year, 
(note that we decided we would further on like to communicate only in EN on github issues as far as it's possible)

The time between xmas and new year's eve went by too fast and i didn't get to work on this issue. I'm removing the 2015-52 milestone and flagging this issue with "help wanted"

You and everyone is welcome to provide a solution to this issue. The code is in the [de.metas.migration](https://github.com/metasfresh/metasfresh/tree/master/de.metas.migration) folder.

AFAIR one needs to implement and add an [IScriptScanner](https://github.com/metasfresh/metasfresh/blob/master/de.metas.migration/de.metas.migration.base/src/main/java/de/metas/migration/scanner/IScriptScanner.java) that can idendify the migration SQL files (the ones in `sql/postgresql/system`) and pass them over to the "SQL-apply" engine.

Anyone taking this issue, feel free to ask @teosarca or me if you have specific questions.

**Comment by daveyx** [comment]
the link to the new location to this file is now:
https://jenkins.metasfresh.com/job/metasfresh-dist/job/master/
