### ISSUE TITLE
swingUI: provide lib-dirs to access user jars and dlls at runtime 

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#695]
see https://forum.metasfresh.org/t/schnittstellt-zu-ms-com-excel-outlook-via-groovy/98
for a documentation of this issue.
This will be the first part of the implementation - the jars needed.

The second will be the dlls

**Comment by homebeaver** [comment]
I created a pull request #697 which changes the pom in de.metas.endcustomer.mf15.swingui

**Comment by homebeaver** [comment]
I changed the title to match the gereral goal.

**Comment by metas-ts** [comment]
Hi @homebeaver,
on the question of how to make external libs available for metasfresh, I found [this stackoverflow question](http://stackoverflow.com/questions/30745132/external-library-folder-for-spring-boot), and bascially, the answer seems to be that one can add the respective paths to the application's `application.property` file.
The documentation is [here](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-property-launcher-features).

Right now, the metasfresh-swingUI client does not come with such a file, but I'm pretty sure that one can either place it next to the "main" jar (in the `lib` folder) or one can provide the values as command line properties (like for windows `-Dloader.path=".\userlib,.\userlib-x64"`).

So, asuming that we can sort out the part of actual making available the external libaries quickly, the next question I see is *how* the metasfresh-client shall access them.

The simplest answer coming to my mind is to create a model interceptor (a.k.a. model validator), place it into an external jar and add a row which references that model interceptor to the `AD_ModelValidator` table.
That table is read on startup. The system finds the class name in the `ModelValidationClass` column, loads and instantiates it and that interceptor can then register the handlers for the model and document changes on which the system is supposed to interact with the COM bridge.

So, it actually would be like any other module with the only difference that it's placed in an external jar.

To see how such a model interceptor is done more concretely, I recomment to take a look at e.g. [metasfresh-dlm](https://github.com/metasfresh/metasfresh/tree/master/de.metas.dlm). It's started with a module interceptor named [Main](https://github.com/metasfresh/metasfresh/blob/master/de.metas.dlm/src/main/java/de/metas/dlm/model/interceptor/Main.java) which extends [AbstractModuleInterceptor](https://github.com/metasfresh/metasfresh/blob/master/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/AbstractModuleInterceptor.java).
It registers "specific" model interceptors such as [DLM_Partition_Config](https://github.com/metasfresh/metasfresh/blob/master/de.metas.dlm/src/main/java/de/metas/dlm/model/interceptor/DLM_Partition_Config.java) whose methods are invoked on different events.

For further infos about the annotations you can use, i recommend to take a look at [this package](https://github.com/metasfresh/metasfresh/tree/master/de.metas.adempiere.adempiere/base/src/main/java/org/adempiere/ad/modelvalidator/annotations)

Please let us know what you need to further proceed on implementing this feature for your customer.

Best regards
Tobias

**Comment by homebeaver** [comment]
Here is a hello-world-example jar:

[hello-world-example.zip](https://github.com/metasfresh/metasfresh/files/773689/hello-world-example.zip)

* copy HelloWorld.jar to %METASFRESH_HOME%/userlib
* create a process with a groovy-script which includes the jar , you can find the goovy in [the german forum](https://forum.metasfresh.org/t/schnittstelle-zu-ms-com-excel-outlook-via-groovy/98/10)
* run the process

**Comment by metas-ts** [comment]
Adding a migration script to create the test-process:
[5459790_cli_gh695_test_process.sql.zip](https://github.com/metasfresh/metasfresh/files/905523/5459790_cli_gh695_test_process.sql.zip)

**Comment by metas-lc** [comment]
IT
1. added the jar here .metasfresh\userlib 
2. added the process for groovy
3. ran the process 
=> process ran fine, without errors
