### ISSUE TITLE
add multi line description per order line

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#696]
1. default multi line description can be stored on product or be left empty
2. user can edit description in order line to add stuff like contractual hints, details, etc.
3. field is shown both in quotation and order
4. field is displayed on shipment note

**Comment by metas-ts** [comment]
as written in the review of PR 740: please make sure/reassign this task so that there will be a (short) documentation

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23696.md: OK

**Comment by metas-ts** [comment]
Just integrated into master. the changes were only about documentation/comments. no additional IT required
