### ISSUE TITLE
Initial Setup for WebUI window configuration

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#700]
Initial Setup for WebUI window configuration
Due to inconsistent migration scripts, decided to do the following
- delete all current existing migration scripts for webUI
- create a delete script for webUI window elements in exiting databases
- migrate an existing dump of all webUI window elements in development
after that all webUI changes will be backed by migration scripts.

**Comment by teosarca** [comment]
closing it because it was integrated long time ago
