### ISSUE TITLE
Jenkins ERROR: Couldn't find any revision to build

### ISSUE THREAD

**Issue by homebeaver** [metasfresh/metasfresh#703]
habe einen pull request gemacht: #697 und der CI-jenkins liefert failing check:
```
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.
Finished: FAILURE
```

Mit der Information aus https://jenkins.metasfresh.com/job/metasfresh/job/PR-697/1/console kann ich nichts anfangen.
In meiner eclipse-EU gibt es keine Probleme. Daher vermute ich, dass das Problem auf der jenkins Seite liegt.
Aber ich bin nicht stattelfest, sowohl was jenkins wie auch was maven betrifft. Bitte daher um ein review.

**Comment by metas-ts** [comment]
this issue was solved meanwhile, by changing the way we call git from within the Jenkinsfile
