### ISSUE TITLE
Have the same error message when adding Purchase Order Line. Tax Category, Tax Rates, and Price Lists are set properly but still get the same "Could not find tax" message

### ISSUE THREAD

**Issue by rmandia** [metasfresh/metasfresh#7096]
Have the same error message when adding Purchase Order Line. Tax Category, Tax Rates, and Price Lists are set properly but still get the same "Could not find tax" message

_Originally posted by @rmandia in https://github.com/metasfresh/metasfresh/issues/3595#issuecomment-669077560_

Error: Could not find tax...
Server error
Could not find tax - Product: 1000004_Kraft Liner Board 200gsm - Sales Transaction: No - Date: 08/05/2020 - ShipTo: Apollo Center, 4120 Kalayaan Ave, 1205 MakatiPhilippinen OR - BillDate: 08/05/2020 - Invoice To: Apollo Center, 4120 Kalayaan Ave, 1205 MakatiPhilippinen OR

**Comment by teosarca** [comment]
hi @rmandia,

Pls attach screenshots of your:
1. Tax category 
2. Taxes defined in that category
3. Product price 

Just a wild guess, I think there is a wrong configuration on Tax level. 
Mind what countries from/to you set there.
Check which is the Purchase Order BPartner's location country.
Check which is the Warehouse location's country.

**Comment by rmandia** [comment]
> hi @rmandia,
> 
> Pls attach screenshots of your:
> 
> 1. Tax category
> 2. Taxes defined in that category
> 3. Product price
> 
> Just a wild guess, I think there is a wrong configuration on Tax level.
> Mind what countries from/to you set there.
> Check which is the Purchase Order BPartner's location country.
> Check which is the Warehouse location's country.
------------
Hi Teosarca,

I checked teh countries from/to set in the tax and set it to Philippines/Philippines at there is no more error.
Does this mean for each country we are importing (purchase) from we have to set a tax rate record?
Does this mean the same for Export Sales?
Thank you!

Best regards,

Randy M

**Comment by teosarca** [comment]
hi @rmandia,

Depends on Philippines's fiscality and laws which I am not aware of.

**Comment by rmandia** [comment]
thank you
