### ISSUE TITLE
Date in modal overlay is not set correctly when double-clicking in calendar widget

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#7107]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When selecting a date with double click in a calendar widget, in a modal overlay, the date is not always set correctly.

#### Which are the steps to reproduce?
1. open bpartner window
2. call "create request" action
3. in reminder date, open the calendar widget, and select a date from **the following month** with double click: a different date is set, not the one u selected
note: this works when selecting the date with single click, and also with double click in main window
### What is the expected or desired behavior?
Correct date is set.

**Comment by siemiatj** [comment]
@metas-dh Can't reproduce this neither on releasetestit nor releasetestuat:
https://recordit.co/lhV1aI7eqE

**Comment by metas-dh** [comment]
@siemiatj did u actually use double click for selection? from the vid it looks like u single click on the date and then click somewhere else in the window, which works fine; the double clicking creates the problem.
