### ISSUE TITLE
Marginal Return Report (short version) doubled sums for accounting group

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#713]
Marginal Return Report (short version) doubled sums for accounting group
Similar to #620

**Comment by metas-mk** [comment]
Please Check for all of these
![image](https://cloud.githubusercontent.com/assets/13365687/21214630/2acea2cc-c29c-11e6-86dd-5591b20d5343.png)

**Comment by metas-mk** [comment]
Fixed directly in DB with individual migration script. No further changes needed.

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80clouditdb
* Buildno: #1.205
* DB: declouddb001 : 5432 / sp80_cloud_it_db

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-1036.md OK
