### ISSUE TITLE
Marginal Return report calculation add additional Costcenter

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#714]
Marginal Return report calculation add additional Costcenter

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80clouditdb
* Buildno: #1.250
* DB: declouddb001 : 5432 / sp80_cloud_it_db

* IT went fine
* need to document IT

**Comment by metas-dh** [comment]
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-1037.md: OK
