### ISSUE TITLE
Aggregation Shipment Jasper Documents shows reference from other ad_org_id

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#724]
Aggregation Shipment Jasper Documents shows reference from other ad_org_id

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80clouditdb
* Buildno: #1.250
* DB: declouddb001 : 5432 / sp80_cloud_it_db

* IT went fine, follow-up created for another problem: https://github.com/metasfresh/metasfresh/issues/741
* need to document IT

**Comment by metas-dh** [comment]
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-1048.md: OK
