### ISSUE TITLE
remove X_BPartner_Stats_MV

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#739]
This legacy table is not used and keeping it up to date via trigger functions imposes a big performance penalty

**Comment by metas-ts** [comment]
Implementing this within #489 because that's there the acutal itch comes from. 
I.e. performance of updating C_Invoice's DLM_Level is bad due to the triggers updating this table.

**Comment by metas-mk** [comment]
Checked. x_bpartner_stats_mv is now removed.
