### ISSUE TITLE
packing material product category config

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#741]

**Comment by metas-ts** [comment]
Hi @metas-lc,
i cant find the DDL for `getSysConfigAsNumeric` in the PRs or in my workspace.
and the sql migration scripts fail.
Can you please verify where it is?

Best Regards
Tobi

**Comment by metas-dh** [comment]
Results of IT 1 
tested on swing, see jira task for details

* all jaspers worked fine, for both Orgs: OK
* HUs were included where necessary, no mix up with the products: OK
* no HUs in the reports where only products wanted: OK
