### ISSUE TITLE
R_Request column c_order_id autocomplete too slow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#742]
R_Request column c_order_id autocomplete too slow
- take out autocomplete, because it is not really needed there for now.

**Comment by metas-dh** [comment]
Results of IT 1 

* App.Server: sp80clouditdb
* Buildno: #1.303
* DB: declouddb001 : 5432 / sp80_cloud_it_db

* Autocomplete is taken out in R _Request, column c_order_id: OK
