### ISSUE TITLE
Report Bestellkontrolle promised Date-Time seems to have am/pm time formatting

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#744]
Report Bestellkontrolle (for both of them) promised Date-Time seems to have am/pm time formatting. pls fix to 24h format.
- In c_order is set ... 23:59, report shows 11:59

**Comment by metas-dh** [comment]
Results of IT 1&2

    App.Server: sp80clouditdb
    Buildno: #1.275, 1.276 & 1.303
    DB: declouddb001 : 5432 / sp80_cloud_it_db

    date & time for datepromised in Bestellkontrolle (Spedition & normal one) fine: OK
    date & time for datepromised in Bestellkontrolle Archiv: OK (customer specific one fixed)
    date & time for datepromised in Bestellkontrolle für Lager drucken / zum Kunden drucken not included: OK, was like this before
