### ISSUE TITLE
Destroyed HU causes problem with shipment creation

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#759]
Discovered by @metas-dh in today's e2e

The problem is that when checking for not-yet-delivered `M_ShipmentSchedule_QtyPicked` records, the system does not check if they reference actually destroyed HUs. It would need to discount shuch records

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23759.md: OK
