### ISSUE TITLE
Creating PO line for procurement product fails sometimes

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#762]
...if there is a procurement contract, but the price is 0.00

**Comment by metas-dh** [comment]
integrated, built & deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

* no more errors / exceptions when creating PO line for procurement product with price empty or 0.00: OK
* further changes / unit tests are added in https://github.com/metasfresh/metasfresh/issues/615, to be tested again after that task is rolled out
