### ISSUE TITLE
Have logo on jasper report that spans from left to right

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#780]
I as an user want to have my logo not only in the right upper corner but spanning from left border all the way to the right.

**Comment by metasnw** [comment]
![image](https://cloud.githubusercontent.com/assets/16079655/21722927/deec171e-d42e-11e6-9291-b5fbc744eb03.png)

**Comment by metasnw** [comment]
![image](https://cloud.githubusercontent.com/assets/16079655/21723099/7d48f1b6-d42f-11e6-833b-9fea48a25edc.png)

**Comment by metas-ts** [comment]
also cherry-picked into https://github.com/metasfresh/metasfresh/tree/release-2017-03

**Comment by metas-ts** [comment]
@metasnw Integratred into master, also cherry-picked into release 2017-03

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1

* logo shown from left to right across the page, starting at the top left (checked order to invoice, sales & purchase side): OK
