### ISSUE TITLE
ESR scan processing returns improper bpartner

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#781]
ESR scan processing returns improper bpartner
- pls check (and fix)

**Comment by metas-ts** [comment]
cherry-picked this into branch `stable`

**Comment by metas-dh** [comment]
Results of IT 1 
* purchase invoice window (vendor from invoice has the same ESR account like another bpartner): vendor is set when scanning ESR string, OK
* payment allocation window: the other bpartner is set when scanning ESR string, not the vendor, NOK

**Comment by metas-ts** [comment]
@metas-dh i merged the fix for
> payment allocation window: the other bpartner is set when scanning ESR string, not the vendor, NOK

note that we don't need this fix in next week's stable release, it can just go into "the normal" 2017-06

**Comment by metas-dh** [comment]
Results of IT3:

 * tested fix for on-the-fly creation of ESR account: OK
 * repeated original IT: OK
 * updated IT doku: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23781.md
