### ISSUE TITLE
Create Nachbelastung from Invoice Cast exception

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#791]
Create Nachbelastung from Invoice Cast exception

![image](https://cloud.githubusercontent.com/assets/13365687/21806701/301f06d2-d73b-11e6-9be4-9fc85320d377.png)

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23791.md: OK

Note: we still have a bug when creating the Nachbelastung, to be fixed in https://github.com/metasfresh/metasfresh/issues/797
