### ISSUE TITLE
Zoom does not open new document

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#797]
Steps to reproduce:
* Go to a completed sales invoice;
* Create a Credit memo or an adjustment charge (from the button)
* => NOK: An empty invoice window is displayed in the end, instead of the newly created document

Note: The document was correctly created. It should have been displayed as specified in org.adempiere.invoice.process.CreateCreditMemoFromInvoice.postProcess(boolean) and org.adempiere.invoice.process.CreateAdjustmentChargeFromInvoice.postProcess(boolean).

IMO debugging should be start around org.compiere.apps.AEnv.zoom(int, int).

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23797.md
