### ISSUE TITLE
Logfile is filled with warnings when Elasticsearch is not installed on a server

### ISSUE THREAD

**Issue by metas-jb** [metasfresh/metasfresh#798]
Logfile is filled with warnings when Elasticsearch is not installed on a server

**Comment by teosarca** [comment]
Nothing to do on this level. If Elasticsearch is not available and not needed, it shall be disabled per endcustomer project.

i.e.
`UPDATE AD_SysConfig SET Value='N',Updated=TO_TIMESTAMP('2016-11-28 12:15:49','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_SysConfig_ID=541074`
