### ISSUE TITLE
Sorting of Productnames, Businesspartnernames shall made possible in PMM_PurchaseCandidate

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#800]
Sorting of Productnames, Businesspartnernames shall made possible in PMM_PurchaseCandidate.
Widow shall also open with that initial Sort (Product name + BPartner Name)

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23800.md: OK
