### ISSUE TITLE
Customs report minor fixes

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#806]
Customs report minor fixes
- Handling Units are doubles sometimes
- Qties shall be in gros qty. They are in net qty atm.
- Watermark "Aus Bestand" whats that?

**Comment by metas-rc** [comment]
> Watermark "Aus Bestand" whats that?

* There is a boolean field in the report calculated by the following SQL:

`EXISTS(
  SELECT 0
  FROM
   M_InOut io
   INNER JOIN M_HU_Assignment thuas ON iol.M_InOutLine_ID = thuas.Record_ID AND ad_table_id = (SELECT Get_Table_ID('M_InOutLine')) AND thuas.isActive = 'Y'
   -- Get snapshot weight
   INNER JOIN M_HU_Attribute_Snapshot thuwns ON thuas.M_HU_ID = thuwns.M_HU_ID
    AND thuwns.M_Attribute_ID = ((SELECT M_Attribute_ID FROM M_Attribute WHERE value = 'WeightNet'))
    AND thuwns.Snapshot_UUID = io.Snapshot_UUID
	AND thuwns.isActive = 'Y'
  WHERE iol.M_InOut_ID = io.M_InOut_ID AND io.isActive = 'Y'
   
 ) AS HasWeightSnapshot`


* In this field is on false, the watermark with the text "Aus Bestand" is displayed

**Comment by metas-rc** [comment]
* I got rid of the "Aus Bestand" backgroud text in all the cases.
* Weight Gross now displayed correctly
* HUs no longer duplicated
( for reproducing, run the report for an inout with several lines for the same product. For getting to this, you can have an LU with 2 TUs and give the TUs different attributes)
* Also fixed another problem: SOme lines were displayed even if they had no HUs or qtys. Only the product was displayed in the left and some nulls were displayed in the rigt.

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-rc** [comment]
New requirement:
* Do not display information about reversed inout in this report.

**Comment by metas-dh** [comment]
Results of IT 1

* reversed inouts are displayed like normal ones, with LU no. and weight gross: NOK

**Comment by metas-dh** [comment]
Results of IT 2

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23806.md: OK
