### ISSUE TITLE
DocActionBL.retrieveString method is broken

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh#808]
Method  de.metas.document.engine.impl.DocActionBL.retrieveString(Properties, int, int, String) is broken. This will return in almost all cases NULL, due to this piece of code:

```
if (keyColumn != null)
{
	return null;
}
```
The bad effect of that can be seen in C_Doc_Outbound_Log, where the field DocStatus is allways null.

**Comment by metas-dh** [comment]
Integrated, built and deployed for integration test

**Comment by metas-lc** [comment]
Result of IT 1: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23808.md
