### ISSUE TITLE
Propagate Attribute from Issue to Receive in Production

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#810]
Product A which is part of a BOM of Product B
does have an attribute set. 
Is there a propagation type that will copy that attribute to the product that will be received?

What happens if there is more than one product on the BOM?

**Comment by metas-dh** [comment]
Results of IT 4 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23810.md: OK
