### ISSUE TITLE
hide packing instruction and qty when null

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#813]

**Comment by metas-dh** [comment]
Results of IT1:

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23813.md: OK

* we need to decide what to do about "No Handling Unit"; atm this can be selected as PI in order, and gets displayed in the jasper, although it's actually no PI at all: => see https://github.com/metasfresh/metasfresh/issues/960 about No Handling Unit
