### ISSUE TITLE
Jasper Footer: Show bank account in one line

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#815]
1. bank name "test bank" is cut off at "test". Should be displayed despite the space
2. bank name, BIC and iban easily fit in one line so do not break
3. If I have more than one bank account defined it should take the "isdefault" one

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23815.md: OK

* could set isdefault for 2 bank accounts for the same bpartner, NOK: see follow up above
