### ISSUE TITLE
Opening Request Window with empty fields wrong pulse effect

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#820]
Opening Request Window with empty fields wrong pulse effect
Should only have pulse effect if window content changes, not when opened initially.

![image](https://cloud.githubusercontent.com/assets/13365687/21986397/8f5bd56c-dbff-11e6-9888-41ec1231132d.png)

**Comment by teosarca** [comment]
there is nothing to do about it on this project.
