### ISSUE TITLE
use the barcode field to select HU using attribute value

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#827]
I have defined a new attribute as string field and I want that to be checked for matching an HU when I put a value into search field barcode in HU Editor

**Comment by metas-rc** [comment]
I suggest the following approach:
* Add a new flag in M_Attribute: IsUseAsBarcode;
* If flag above is on true, another field (new column) will be displayed, which will contain the java class for that attribute barcode logic
*  To have the posibility to accept several such logics, maybe a seqno would also be useful, to have them ordered by the importance.
* Add a service in de.metas.handlingunits.attribute.spi which will have implementations in the java classes above
* The barcode logic would be called in this method: de.metas.handlingunits.client.terminal.editor.view.HUEditorPanel.doBarcodeScan() ONLY if collectedHUKeys is empty ( barcodes that equal M_HU.value have priority, to keep the existing logic intact)

**Comment by metas-rc** [comment]
I suggest the following approach:
* Add a new flag in M_Attribute: IsUseAsBarcode;
* If flag above is on true, another field (new column) will be displayed, which will contain the java class for that attribute barcode logic
*  To have the posibility to accept several such logics, maybe a seqno would also be useful, to have them ordered by the importance.
* Add a service in de.metas.handlingunits.attribute.spi which will have implementations in the java classes above
* The barcode logic would be called in this method: de.metas.handlingunits.client.terminal.editor.view.HUEditorPanel.doBarcodeScan() ONLY if collectedHUKeys is empty ( barcodes that equal M_HU.value have priority, to keep the existing logic intact)

**Comment by metas-rc** [comment]
I added the DIM_Dimension_Spec DIM_Barcode_Attributes.
Add attributes there. They should work in identifying HUs by them, when inserting them in the barcode field, in HandlingUnit POS.
All attributes must be string.

**Comment by metas-ts** [comment]
Hi @metas-rc, please check out my [review](https://github.com/metasfresh/metasfresh/pull/872#pullrequestreview-18790387)

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23827.md: OK
