### ISSUE TITLE
Default Document Layout for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#831]
Default Document Layout for WebUI

![image](https://cloud.githubusercontent.com/assets/13365687/22065856/6124f6b0-dd8a-11e6-9172-8771d0ef4da4.png)

**Comment by metas-dh** [comment]
Results of IT 1 

* logo has more white on the sides, OK
* line in footer is now gray, OK
* info underneath the line in footer is center aligned, OK (added description for 4th line and IBAN for 6th line for testing, OK)
* DEU- DEU: fixed in https://github.com/metasfresh/metasfresh/issues/864
