### ISSUE TITLE
Invoice Process in Invoice Candidates WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#833]
Invoice Process in Invoice Candidates WebUI

> Caught exception de.metas.document.exceptions.DocumentProcessingException: Error Processing Document document: Ausgangsrechnung 145875 Belegverarbeitung: CO ProcessMsg: Could not update Order Line Cause: Error Processing Document document: Ausgangsrechnung 145875 Belegverarbeitung: CO ProcessMsg: Could not update Order Line (DocumentProcessingException) with meesage: Error Processing Document document: Ausgangsrechnung 145875 Belegverarbeitung: CO ProcessMsg: Could not update Order Line Cause: Error Processing Document document: Ausgangsrechnung 145875 Belegverarbeitung: CO ProcessMsg: Could not update Order Line (DocumentProcessingException)

**Comment by teosarca** [comment]
@metas-mk  so far i've improved the error reporting. If you stumble on this issue again, pls paste the full stacktrace or ping me.

**Comment by metas-mk** [comment]
Tested. Issue https://github.com/metasfresh/metasfresh-webui/issues/126 prevents testing of this currently. Waiting for quick fix.

**Comment by metas-mk** [comment]
Tested. Described error did not happen anymore.  Closing this issue and will create new one if error occurs again.

**Comment by metas-mk** [comment]
Add to release Notes 4.56.55
