### ISSUE TITLE
Gear from Pricing System and PriceList show wrong processes

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh#844]
Steps to reproduce: 
* Fo to pricing system or Pricelist, open the gear
=> NOK: all of the processes are displayed in the list.
![bug in cloudmf15](https://cloud.githubusercontent.com/assets/16001442/22151381/751b25de-df26-11e6-96ee-46338ef39e3b.png)

**Comment by metas-dh** [comment]
Results of IT 1

* Gear from Pricing System and PriceList: no longer showing all processes in a list, no processes are displayed: OK
* Gear from PLV: process Recalculate SeqNo available like before: OK
