### ISSUE TITLE
C_BusinessPartner_ID M_Product_ID Search Fields Config

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#851]
C_BusinessPartner_ID M_Product_ID Search Fields Config
Thinking about to redefine the search fields of C_BusinessPartner_ID M_Product_ID according to the visible information in search widgets. Currently it shows Value + Record-Name
After having a talk with https://github.com/cadavre about this I believe it makes more sense to have Record-Name in first place. wdyt?

**Comment by metas-lc** [comment]
IT:
The products can look like the following:
name_value OK
value_name OK?
name OK?

Same, the bpartners can look like the following:
name_value OK
name OK?

note that all are search fields

Cases for name_value for product:
- add new orderline with batch entry
- adding a product in warehouse, subtab replenish
- add new invoice line with add new
- add new empties line with add new

Cases for name_value for bpartner:
- add new bpartner in Product window, bpartner subtab
- add bpartner in new invoice
- add bpartner in new empties

Cases for value_name for product
- add new orderline with add new 
- add new product in Produkt Preise window

Cases for name for product
- add new line in empties with batch entry 

Cases for name for bpartner
- add new line in empties with batch entry 
- add bpartner in order

**Comment by metas-mk** [comment]
Closing this issue. For further needed changes we will create a new one.
