### ISSUE TITLE
String Value not saved in POS Window

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#857]
1. have an attribute of type string
2. receive HU from Production PO
3. select HU
4. put anything into the attribute field
5. DO Not leave the field
6. click OK 
7. NOK: The value was not saved. Do the same and leave the attribute field it is getting saved.

**Comment by metas-mk** [comment]
The solution could be: When pressing OK, also save the content of the field where the cursor is.

**Comment by metas-lc** [comment]
IT OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23857.md
