### ISSUE TITLE
Process confirmation window needs to be changed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh#863]
Follow up for #835 Switch off Process Confirmation Window

* switching off allowing the process rerun was not effective: process confirmation window is still displayed in e.g. creating shipments, orders and invoicing (without rerun option)
* changes in code necessary

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23863.md
