### ISSUE TITLE
Make payment callouts work in webui

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#866]
This task is required for: https://github.com/metasfresh/metasfresh/issues/862

**Comment by teosarca** [comment]
NOTE to IT: full regression tests on Payment window is needed!

**Comment by teosarca** [comment]
i think the "IT failed" label was added by mistake. Moving it back to Test.

**Comment by metas-lc** [comment]
IT
swing and webui

1. invoice field does not become empty when you first save in Payment (entry is saved) OK

2. make combinations like sales payment + purchase invoice: OK
webui:
Server error
Payment Document Type and Invoice type (AP/AR) inconsistent.
swing: 
Belegart und Rechnung (Debitoren/Kreditoren) inkonsistent.

3. save the zahlung => depending on your zahlungs type, zahlungseingangs checkbox (issotrx) updates accordingly OK

4. payselection: = Sepa button is readonly while document uncomplete. It becomes editable after complete. Erstellen aus is editable while is not completed. Becomes readonly after complete OK
