### ISSUE TITLE
Weekly Revenue Report

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#868]
Weekly Revenue Report
- we already have a monthly revenue report, copy that and allow weekly parameter and presentation.

**Comment by metas-dh** [comment]
Results of IT 1

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23868.md: OK

**Comment by metas-ts** [comment]
cherry-picked into branches release-2017-05 and stable
