### ISSUE TITLE
Invoice Candidate price-qty overwrite lost when ReverseCorrect

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#870]
Invoice Candidates price-qty overwrite lost when ReverseCorrect
Szenario:
* Add price or qty to invoice override
* do the invoicing
* reverse the invoice
Result: the previous recorded qty/ price overwrite are lost

**Comment by metas-dh** [comment]
Results of IT 2

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23870.md: OK
