### ISSUE TITLE
Make "Wareneingang POS (Jasper)" report work with M_ReceiptSchedule_ID as parameter

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#877]
Report:
* AD_Process_ID=540491
* JasperReport=https://github.com/metasfresh/metasfresh/blob/master/de.metas.fresh/de.metas.fresh.base/src/main/jasperreports/de/metas/docs/purchase/inout/pos_report.jrxml

Current status:
That's the report which is printed when user presses on "Drucken Produktanlieferung" button in Wareneingang POS.
The report takes C_OrderLine_ID as parameter.

TODO:
* Make the report work the same for M_ReceiptSchedule_ID parameter. Internally the C_OrderLine_ID shall be fetched from M_ReceiptSchedule.C_OrderLine_ID.
* regression: make sure the report still works with C_OrderLine_ID as parameter

**Comment by teosarca** [comment]
required for: https://github.com/metasfresh/metasfresh/issues/461

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Tetscase_%23877.md: OK

**Comment by metas-ts** [comment]
cherry-picked into stable branch
