### ISSUE TITLE
Fix "ValueType not supported: D" when HU attributes are generated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#879]
> java.lang.UnsupportedOperationException: ValueType not supported: D(attribute=MAttribute[540022-Tageslot Datum,Type=D,Instance=true], generator=org.adempiere.mm.attributes.spi.impl.HULotNumberAttributeHandler@45db880c)
> 	at de.metas.handlingunits.attribute.storage.impl.AbstractHUAttributeStorage.generateAttributeValueOrNull(AbstractHUAttributeStorage.java:226)
> 	at de.metas.handlingunits.attribute.storage.impl.AbstractHUAttributeStorage.generateAndGetInitialAttributes(AbstractHUAttributeStorage.java:169)
> 	at de.metas.handlingunits.attribute.storage.impl.AbstractAttributeStorage.generateInitialAttributes(AbstractAttributeStorage.java:433)
> 	at de.metas.handlingunits.impl.HUBuilder.createInstanceRecursivelly(HUBuilder.java:257)
> 	at de.metas.handlingunits.impl.HUBuilder.create(HUBuilder.java:232)
> 	at de.metas.handlingunits.impl.HUBuilder.create(HUBuilder.java:226)
> 	at de.metas.handlingunits.allocation.impl.AbstractProducerDestination.createNewHU(AbstractProducerDestination.java:241)
> 	at de.metas.handlingunits.allocation.impl.AbstractProducerDestination.getCreateCurrentHU(AbstractProducerDestination.java:176)
> 	at de.metas.handlingunits.allocation.impl.AbstractProducerDestination.load(AbstractProducerDestination.java:499)
> 	at de.metas.handlingunits.allocation.split.impl.LUTUProducerDestination.loadHU(LUTUProducerDestination.java:487)
> 	at de.metas.handlingunits.allocation.impl.AbstractProducerDestination.load(AbstractProducerDestination.java:511)
> 	at de.metas.handlingunits.allocation.impl.HULoader.loadToDestination(HULoader.java:330)
> 	at de.metas.handlingunits.allocation.impl.HULoader.unloadSourceThenLoadDestination(HULoader.java:279)
> 	at de.metas.handlingunits.allocation.impl.HULoader.access$0(HULoader.java:248)
> 	at de.metas.handlingunits.allocation.impl.HULoader$1.process(HULoader.java:178)
> 	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor$1.run(HUContextProcessorExecutor.java:103)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:1)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:494)
> 	at de.metas.handlingunits.allocation.impl.HUContextProcessorExecutor.run(HUContextProcessorExecutor.java:80)
> 	at de.metas.handlingunits.allocation.impl.HULoader.processInHUContext(HULoader.java:202)
> 	at de.metas.handlingunits.allocation.impl.HULoader.load(HULoader.java:167)
> 	at de.metas.handlingunits.receiptschedule.impl.ReceiptScheduleHUGenerator.createHUForQtyToAllocate0(ReceiptScheduleHUGenerator.java:342)
> 	at de.metas.handlingunits.receiptschedule.impl.ReceiptScheduleHUGenerator.access$0(ReceiptScheduleHUGenerator.java:319)
> 	at de.metas.handlingunits.receiptschedule.impl.ReceiptScheduleHUGenerator$1.run(ReceiptScheduleHUGenerator.java:297)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
> 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:1)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:757)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:669)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:570)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:501)
> 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:494)
> 	at de.metas.handlingunits.receiptschedule.impl.ReceiptScheduleHUGenerator.generateLUTUHandlingUnitsForQtyToAllocate(ReceiptScheduleHUGenerator.java:292)
> 	at de.metas.handlingunits.receiptschedule.impl.ReceiptScheduleHUGenerator.generate(ReceiptScheduleHUGenerator.java:284)
> 	at de.metas.inoutcandidate.process.M_ReceiptSchedule_GeneratePlanningHUs.doIt(M_ReceiptSchedule_GeneratePlanningHUs.java:162)
>

**Comment by teosarca** [comment]
@metas-rc do u remember on which task this issue was introduced?

**Comment by metas-ts** [comment]
fixed with [this commit](https://github.com/metasfresh/metasfresh/commit/ff6eb3ba5d1e3c3f94271e0caf69c42ec99c4c15) in issue #460

**Comment by metas-ts** [comment]
the close was a bit premature :flushed:

**Comment by metas-dh** [comment]
Results of IT 1 

* repeated testing of https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_FRESH-934.md: OK
* no errors / exceptions in console: OK

**Comment by metas-ts** [comment]
Just saw there was another unintegrated change in branch `FRESH-1251` that change was ab fix wrt `HULotNumberAttributeHandler`

**Comment by metas-lc** [comment]
IT
worked fine, but i couldn't change tageslot
follow-up https://github.com/metasfresh/metasfresh-webui/issues/170
