### ISSUE TITLE
New Field "Zulieferant" in R_Request Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#904]
New Field "Zulieferant" in R_Request Window
- Shall be a search field with c_bpartner_id and isVendor = 'Y'

**Comment by metas-ts** [comment]
cherry-picked into the `stable` branch

**Comment by metas-dh** [comment]
Results of IT 1 

* new field "Zulieferant" in window R_Request, Vorgang and Vorgang (alle): OK
* checked windows from menu as well as from "Aufgabe" button in main menu (Vorgang) and "Neue Anfrage anlegen" from sales order (Vorgang (alle)): OK
* field to be set by user: vendors are suggested correctly when typing bpartner number or part of bpartner name, bpartners != vendors cannot be selected: OK
