### ISSUE TITLE
Put explicit delivery date on invoice 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#910]
today we already put the shipment document number and date on the invoice.
According to this: http://www.akademie.de/wissen/lieferdatum-leistungsdatum-rechnung
we have to use the explicit term "Lieferdatum" or "Leistungsdatum".

**Comment by metas-mk** [comment]
example string:
Lieferschein: <Beleg Nr.> Lieferdatum/ Leistungsdatum: 01.02.2017

**Comment by metasnw** [comment]
from chat:
Lieferschein: <DocumentNo> Lieferdatum/ Leistungsdatum: 01.02.2017

**Comment by metas-ts** [comment]
..also cherry-picked changeset be1d3ef3f1b61a4f27bee2f03c727c967ca470b5 to the branch `release-2017-07`

**Comment by metas-dh** [comment]
Results of IT 2 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23910.md: OK
