### ISSUE TITLE
Include branch name in build version string

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#913]
here the branch is missing: 

![image](https://cloud.githubusercontent.com/assets/1264789/22544530/69ad31d8-e935-11e6-9d2e-20a3fc32d288.png)

which can be a problem when rolling out from branches that only have a few builds each

**Comment by metas-dh** [comment]
Results of IT 1 

* branch name included as well, e.g. 4.55.54-master-1.589: OK
