### ISSUE TITLE
Customs Report Weight adjustment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#914]
Customs Report Weight adjustment
- shall not be gross nor net. shall be gross - weight of palette (25kg)

**Comment by metas-ts** [comment]
cherry-picked into the `stable` branch

**Comment by metas-ts** [comment]
integrated changeset 1b2e464 and also cherry-picked it to branch `release-2017-06`

**Comment by metas-dh** [comment]
Results of IT 2

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23914.md: OK

   * problems found earlier this week (qual. discount, >1 LU in inout) all fixed
