### ISSUE TITLE
Provide SSL encryption for webui, webapi and docker

### ISSUE THREAD

**Issue by metas-jb** [metasfresh/metasfresh#919]

**Comment by teosarca** [comment]
NOTE: this task is also required in order to be able to capture images from webcam: https://github.com/metasfresh/metasfresh-webui-frontend/issues/228

**Comment by metasnw** [comment]
as discussed. expectation of issue result is to have docker ssl best practices implemented in our public docker image

**Comment by metasnw** [comment]
migrated to https://github.com/metasfresh/metasfresh-docker/issues/4

**Comment by teosarca** [comment]
question: can we have SSL on w101 too?
