### ISSUE TITLE
import metasfresh into eclipse

### ISSUE THREAD

**Issue by pmaingi** [metasfresh/metasfresh#93]
Hello,
Am trying to run metasfresh but when i import into eclipse i get .class java files.
Note i used http://docs.metasfresh.org/developers_collection/en/getting_started_en.html instructions. Please assist

**Comment by metas-ts** [comment]
Hello @pmaingi,
great that you are interested in the code :-).
Can you please explain more about the problem you are facing? 
And/or maybe add a screenshot of how eclipse looks with the error?
Also feel free to join the gitter chat at https://gitter.im/metasfresh/metasfresh.
Maybe I or someone else can help you there, in a more "interactive" way.

Best regards
Tobias

**Comment by metas-ts** [comment]
About the actual problem, we started to deal with it in https://gitter.im/metasfresh/metasfresh, but we aren't through yet. Still i think we don't need this issue here anymore.
I opened https://github.com/metasfresh/metasfresh-documentation/issues/28 to document everything we did along the way.
