### ISSUE TITLE
Improve Transparency & Usability of Pricing definitions

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#942]
Improve Transparency & Usability of Pricing definitions
The Pricing Data Structure has grown during the last decade to allow very detailed price definitions bases on countries, currencies, products, packages, attributes and more. This lead into a data structure that is tough to understand and maintain for new users. The aim of this task is to improve the price hierarchy to allow much easier maintenance and better transparency. Please take care of code and reports.
Current hierarchy:
```
M_PricingSystem (0)
  +M_PriceList (1)
    +M_PriceList_Version (2)
      +M_ProductPrice (3)
        + M_ProductScalePrice (4)
        + M_ProductPrice_Attribute (4)
          + M_ProductPrice_Attribute_Line (5)
```
The development can be decided into the following sub-topics:
a) refactor data structure/ code (getting rid of M_ProductPrice_Attribute, M_ProductPrice_Attribute_Line,M_ProductScalePrice and include in M_ProductPrice)
b) adjust the dependent reports
c) window layout changes and splitting (single window for M_PricingSystem, M_PriceList/ M_PriceList_Version, Subtab in Product for Product Prices, New Window for Product Prices which allows filtering for Pricelist Version)

**Comment by teosarca** [comment]
Note to IT, below is a draft list about what to test, old tasks from where you shall fetch test cases:
* http://dewiki908/mediawiki/index.php/Sp80_07082_Fix_copy_pricelistversion_-_isSeasonFixedPrice_%28Saison_Fix_Preis%29
* http://dewiki908/mediawiki/index.php/Sp80_05832_Saisonfixpreise_%28107780990155%29
** changes: delete all product prices, even if they are season fixed prices
* task 09051
* task 08803
* task 08147
* task 07634: Remove lines of products which are not in the invoice's price list / version.
* task 08839

* M_HU_PI_Item_Product fields in Order, Invoice, PMM_PurchaseCandidate

* test ASI editor

**Comment by metas-dh** [comment]
Results of IT
tested on w101 et al. (Swing & WebUI)

* all tasks mentioned above were re-tested
* problems documented in task chat, fixed in this task or follow ups (see above)
* for future problems, more follow ups will be created
