### ISSUE TITLE
Invoice Document overlapping characters in grouping Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#945]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
Invoice Document shows overlapping characters in grouping Header of Invoice lines.
#### Which are the steps to reproduce?
Create an Invoice with existing Shipment and fairly long location name, so that group header reaches into next line.
### What is the expected or desired behavior?
Don't overlap the JasperReports field content.

![image](https://cloud.githubusercontent.com/assets/13365687/22854368/22d254de-f06d-11e6-93de-26f2060a2152.png)

**Comment by metas-lc** [comment]
was fixed in another task
