### ISSUE TITLE
Address Layout Dunning Document

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh#954]
### What is the current behavior?
address does not fit in letter window when printed

### What is the expected or desired behavior?
change the address layout so it looks like on sales order

**Comment by metas-dh** [comment]
Results of IT 1

* Address layout in dunning doc header as in sales order: OK 
* Address layout in dunning doc header as before where no change needed: OK
* ESR not included in dunning doc if org is DE, included if org is CH: OK
