### ISSUE TITLE
Adjust Price list reports to new data structure

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#956]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
The current Price List reports show data from "old" data hierarchy.
#### Which are the steps to reproduce?
Go to Window Business Partner and start the process for Pricelist generation.
### What is the expected or desired behavior?
Adjust the Pricelist Reports to work with refactored Data structure as done in #942

**Comment by metas-dh** [comment]
Results of IT 1 

* Pricelist report: open questions remaining, see task chat
* Pricelist Excel Export: not working anymore, WhiteLabel Error

**Comment by metas-ts** [comment]
--also cherry-picked this fix into the `release` branch

**Comment by metas-dh** [comment]
Results from IT 2

* Pricelist Excel Export / Import: worked now; to clarify if prices need to be editable!

**Comment by teosarca** [comment]
@metas-dh IMHO, definitely the shall NOT be editable.
AFAIR, that excel is used to be sent to third parties and they fill in the Qty and then they are sending back the excel file. They are not allowed to change the price.

**Comment by metas-dh** [comment]
* Pricelist Excel Export: prices should NOT be editable, only qties: OK
