### ISSUE TITLE
Delete ambiguous "No Handling Unit" record

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#960]
try applying following query to seed database:

`delete from M_HU_PI_Item_Product where M_HU_PI_Item_Product_ID=3010006 and Name='No Handling Unit';
`if not possible, we need to rename it...

**Comment by metas-jb** [comment]
apply config to seed database

**Comment by metas-rc** [comment]
Results of IT 1: 
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23960.md OK

Note: Problems with batch entry for products with no TU. Followup: https://github.com/metasfresh/metasfresh-webui/issues/129
