### ISSUE TITLE
Include webui in the normal rollout process

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#968]
### Is this a bug or feature request?

it's a feature request

### What is the current behavior?

right now, the the "dist.tar.gz" file (e.g. de.metas.endcustomer.mf15.dist-1.648-dist.tar.gz) basically contains
* the matasfresh-backend
* the matasfresh-swing-client
* our jasper files
* rollout/install scripts

### What is the expected or desired behavior?

In addition, the dist.tar.gz shall also include
* the metasfresh-webui-api
* the metasfresh-webui-frontend

..and the rollout scripts shall install them as well.

**Comment by metas-dh** [comment]
Results of IT 1
tested when rolling out to mf15:

* webui included in the rollout process: OK
