### ISSUE TITLE
Set DLM_Level via properties/preferences UI

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#975]
### Is this a bug or feature request?

feature request

### What is the current behavior?

currently, the both DLM_Level for metasfresh to "see" and the implicit DLM_Level that shall be assumed in case a record was not yet evaluated can be set **globally**. either via AD_Sysconfig, or via cmd-line

#### Which are the steps to reproduce?

just to so the `AD_Sysconfig` window, check out

* `de.metas.dlm.DLM_Level`
* `de.metas.dlm.DLM_Coalesce_Level`

### What is the expected or desired behavior?

* we need a user to be able to view and change this setting individually in their settings.
* and it needs to be stored in the user's local metasfresh.properties

**Comment by metas-lc** [comment]
IT. OK: new setting "Data Lifecyple Management Sichtbarkeit".
if you change it, properties file updates OK
