### ISSUE TITLE
Warning during compile time

### ISSUE THREAD

**Issue by petrican** [metasfresh/metasfresh#9845]
![Screenshot 2020-08-26 at 09 46 03](https://user-images.githubusercontent.com/1708561/91271118-5cfbec00-e782-11ea-958e-ef9614994143.png)
### Is this a bug or feature request?
B
### What is the current behavior?
We get a warning during compile 
#### Which are the steps to reproduce?
npm install; npm run start in the frontend folder
### What is the expected or desired behavior?
There should be no warnings displayed

**Comment by petrican** [comment]
![Screenshot 2020-08-26 at 11 57 33](https://user-images.githubusercontent.com/1708561/91284257-54141600-e794-11ea-8190-08683baa618e.png)

This happens as a result of updating babel/* . Basically during compilation step does not like the fact that an import is done in an expression, in our case the way plugins are loaded in src/containers/App.js

**Comment by teosarca** [comment]
@petrican , @siemiatj  I guess we have to do it that way. So my question is, can't we advise the list/babel or who is signal it to not log the warning for that line of code?

**Comment by petrican** [comment]
You mean to ignore that specific line. Should be doable.

**Comment by petrican** [comment]
## 🔀 R&I to branch `master`

### PRs

- [ ] developer also looked over the PR
- https://github.com/metasfresh/metasfresh/pull/10870

<details>
<summary>TODOs for the reviewer</summary>

- [ ] make sure the target-system was set
- [ ] make sure the target-branch is consistent with the Hotfix-Y/N requirement
- [ ] make sure the expectable effort is within the `est:` and `bud:`
    - or if they aren't, make sure it was clarified with the issue-giver (->look for a comment it this issue)
- [ ] make sure the functional concept is consistent with the requirements
- [ ] make sure the technical concept is consistent with the requirements and functional concept
- [ ] understand the code changes if practical
    - https://github.com/metasfresh/me03/wiki/Code-review-guidelines
- [ ] if understanding the code changes is not practical (e.g SQL blob): understand the documented dev-tests and make sure they show that the problem is solved

</details>


#### Review

- review_URLs_here

### After integration

- [ ] set `branch:`-label in metasfresh-issue XOR pullrequest
- [ ] set `branch:`-label in customer-issue
- [ ] set customer milestone (either hotfix milestone or "normal" UAT milestone)
- [ ] if needed, set `rm:manual_rollout`-label in customer-issue
