### ISSUE TITLE
Handle the case that a PO can't load a record

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh#986]
### Is this a bug or feature request?

feature request

### What is the current behavior?

currently, if `PO` is invoked to load a record and can't get it from the DB, then an exception is thrown and an error is logged.

### What is the expected or desired behavior?

1. we need to be able to register handlers that are invoked and check if they can do anything about the situation. In case of a positive answer from the handler, the `PO` shall retry
2. we need DLM to provide such a handler, that shall check if the not-loadable-record was archived. In that case the handler shall un-archive the record in question and shall tell the `PO`to retry.
2.a) also consider showing a message to the user (but there we might need to make sure to collect such events and e.g. only show such a message with all of those events at the end of the transaction)

**Comment by metas-dh** [comment]
Results of IT 1 

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23986.md: OK
