### ISSUE TITLE
ClassNotFoundException: de.metas.dlm.swingui.model.interceptor.Main

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh#998]
I got this on webui project because metasfresh-dlm-swingui is not a dependency of metasfresh-webui and it shall not be.

Suggestion: 
* try registering that interceptor from another interceptor where u can check if is Swing UI
* introduce AD_ModelValidator.Profiles ....

**Comment by metas-ts** [comment]
@teosarca i checked at `de.metas.banking.model.validator.Banking_SwingUI` and thx to the you we already have a solution:
See `ModelValidationEngine.loadModuleActivatorClass()`. I'm going to apply it tomorrow

**Comment by metas-lc** [comment]
webui part is ok
