### ISSUE TITLE
Order indicator vanished after switching detail view back to grid view

### ISSUE THREAD

**Issue by petrican** [metasfresh/metasfresh#9980]
### Is this a bug or feature request?
B
### What is the current behavior?
Sorting indicator lost when come back from inner doc.
#### Which are the steps to reproduce?
If you have an active sorting and you go to one of the items and come back using back button you don't see the chevron showing sorting direction
### What is the expected or desired behavior?
Chevron icon should be present when using back button if you have an active sort

**Comment by siemiatj** [comment]
@petrican I think I've found a much simpler solution : https://recordit.co/v1RgnYq2lK . Check my PR
